{ Grafx2 - The Ultimate 256-color bitmap paint program

  Copyright 1996-2001 Sunset Design (Guillaume Dorme & Karl Maritaud)

  Grafx2 is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; version 2
  of the License.

  Grafx2 is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Grafx2; if not, see <http://www.gnu.org/licenses/> or
  write to the Free Software Foundation, Inc.,
  59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
}
{
  Ce fichier contient la partie "Credits" de l'aide de GRAFX 2
}

procedure Generer_l_aide_Credits;
begin
  Demarrer_section_d_aide;
                        {XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}
                        {XXXXXXXXXXXXXXXXXXXXXX}
  Ecrire_ligne_d_aide(T,'      GRAFX 2.00');
  Ecrire_ligne_d_aide(S,'  THE ULTIMATE MULTI-RESOLUTION GFX EDITOR');
  Ecrire_ligne_d_aide(N,'   Copyright (c) 1996-98 by SUNSET DESIGN');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(T,'CREDITS:');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(S,'  WRITTEN AND DESIGNED BY:');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(S,'    GUILLAUME DORME       KARL MARITAUD');
  Ecrire_ligne_d_aide(N,'   alias "Robinson"   &   alias "X-Man"');
  Ecrire_ligne_d_aide(N,'         programmer       programmer');
  Ecrire_ligne_d_aide(N,'                          GFX artist');
  Ecrire_ligne_d_aide(T,'');
  Ecrire_ligne_d_aide(S,'  MISCELLANEOUS:');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    This is our very first program compiled');
  Ecrire_ligne_d_aide(N,'   in Watcom C (10.6).');
  Ecrire_ligne_d_aide(N,'    Low-level routines were written in 80386');
  Ecrire_ligne_d_aide(N,'   Assembler (optimized for 80486) and');
  Ecrire_ligne_d_aide(N,'   compiled with Borland TASM 5 (4.1).');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    We were inspired by the XSetMode routine');
  Ecrire_ligne_d_aide(N,'   from ''XLIB2'' to create more amazing video');
  Ecrire_ligne_d_aide(N,'   resolutions.');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    Thanks to Eclipse for their EOS 3.05 dos');
  Ecrire_ligne_d_aide(N,'   extender (WEOSlite).');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    Some information taken from several docs');
  Ecrire_ligne_d_aide(N,'   (PCGPE, Intervue, PC Interdit...) gave us');
  Ecrire_ligne_d_aide(N,'   an invaluable help.');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    Thanks to Shawn Hargreaves for his');
  Ecrire_ligne_d_aide(N,'   filled polygon routine from Allegro v2.2.');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    Thanks to Carlos "Made" Pardo for his');
  Ecrire_ligne_d_aide(N,'   great GrafX2 logo.');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    A thousand thanks to the authors of the');
  Ecrire_ligne_d_aide(N,'   different things listed above.');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    We also would like to thank all the');
  Ecrire_ligne_d_aide(N,'   people who gave us ideas to improve');
  Ecrire_ligne_d_aide(N,'   GrafX2.');
  Ecrire_ligne_d_aide(T,'');
  Ecrire_ligne_d_aide(S,'  FILE FORMATS CREDITS:');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'   PKM : Sunset Design');
  Ecrire_ligne_d_aide(N,'   LBM : Electronic Arts');
  Ecrire_ligne_d_aide(N,'   GIF : Compuserve');
  Ecrire_ligne_d_aide(N,'   BMP : Microsoft');
  Ecrire_ligne_d_aide(N,'   PCX : Z-Soft');
  Ecrire_ligne_d_aide(N,'   IMG : Bivas (W. Wiedmann?)');
  Ecrire_ligne_d_aide(N,'   SCx : Colorix (?)');
  Ecrire_ligne_d_aide(N,'   CEL,KCF : K.O.S. (KISekae Set system)');
  Ecrire_ligne_d_aide(N,'   PI1,PC1 : Degas Elite');
  Ecrire_ligne_d_aide(N,'   PAL : ermmh... nobody (?)');
  Ecrire_ligne_d_aide(T,'');
  Ecrire_ligne_d_aide(T,'HOW TO CONTACT US ?');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(S,'  SNAIL MAIL:');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    GUILLAUME DORME (Robinson)');
  Ecrire_ligne_d_aide(N,'    15, rue de l''observatoire');
  Ecrire_ligne_d_aide(N,'    87000 LIMOGES (FRANCE)');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    KARL MARITAUD (X-Man)');
  Ecrire_ligne_d_aide(N,'    10, rue de la Brasserie');
  Ecrire_ligne_d_aide(N,'    87000 LIMOGES (FRANCE)');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(S,'  E-MAIL:');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'    dorme@msi.unilim.fr');
  Ecrire_ligne_d_aide(N,'    maritaud@ensil.unilim.fr');
  Ecrire_ligne_d_aide(T,'');
  Ecrire_ligne_d_aide(T,'USELESS INFORMATION:');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'   Source size: about 1400 Kb');
  Ecrire_ligne_d_aide(N,'   GrafX2''s birth date: July 20th 1996');
  Ecrire_ligne_d_aide(T,'');
  Ecrire_ligne_d_aide(T,'KNOWN BUGS:');
  Ecrire_ligne_d_aide(N,'');
  Ecrire_ligne_d_aide(N,'   - <Ctrl>+<C> stops the program when you');
  Ecrire_ligne_d_aide(N,'     are entering values. So don''t press');
  Ecrire_ligne_d_aide(N,'     these keys until we fix this bug.');
  Ecrire_ligne_d_aide(N,'   - A few different key combinations return');
  Ecrire_ligne_d_aide(N,'     the same code.');
  Ecrire_ligne_d_aide(N,'   - A red flash appears at start up when an');
  Ecrire_ligne_d_aide(N,'     empty Zip drive is found.');
  Ecrire_ligne_d_aide(N,'   - Some functions aren''t finished yet.');
  Ecrire_ligne_d_aide(N,'     This is normal for a Beta version, so');
  Ecrire_ligne_d_aide(N,'     don''t worry.');
  Ecrire_ligne_d_aide(N,'     But if you still find some bugs in the');
  Ecrire_ligne_d_aide(N,'     next versions, then we''d appreciate');
  Ecrire_ligne_d_aide(N,'     that you tell us what they exactly are');
  Ecrire_ligne_d_aide(N,'     and how and when they occur.');
                        {XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}
                        {XXXXXXXXXXXXXXXXXXXXXX}
  Terminer_section_d_aide;
end;
