@rem  Grafx2 - The Ultimate 256-color bitmap paint program
@rem
@rem  Copyright 1996-2001 Sunset Design (Guillaume Dorme & Karl Maritaud)
@rem
@rem  Grafx2 is free software; you can redistribute it and/or
@rem  modify it under the terms of the GNU General Public License
@rem  as published by the Free Software Foundation; version 2
@rem  of the License.
@rem
@rem  Grafx2 is distributed in the hope that it will be useful,
@rem  but WITHOUT ANY WARRANTY; without even the implied warranty of
@rem  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@rem  GNU General Public License for more details.
@rem
@rem  You should have received a copy of the GNU General Public License
@rem  along with Grafx2; if not, see <http://www.gnu.org/licenses/> or
@rem  write to the Free Software Foundation, Inc.,
@rem  59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

@echo off
img2fnt fonts fonte1
img2fnt fonts fonte2 17280