GrafX2: operatio.c File Reference
operatio.c File Reference
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include "const.h"
#include "struct.h"
#include "global.h"
#include "divers.h"
#include "moteur.h"
#include "graph.h"
#include "operatio.h"
#include "boutons.h"
#include "pages.h"
#include "erreurs.h"
#include "sdlscreen.h"
#include "brush.h"
#include "windows.h"
Functions
void Demarrer_pile_operation (word Operation_demandee)
void Initialiser_debut_operation (void)
void Operation_PUSH (short Valeur)
void Operation_POP (short *Valeur)
short Distance (short X1, short Y1, short X2, short Y2)
void Aff_coords_rel_ou_abs (short Debut_X, short Debut_Y)
void Freehand_Mode1_1_0 (void)
void Freehand_Mode1_1_2 (void)
void Freehand_Mode12_0_2 (void)
void Freehand_Mode1_2_0 (void)
void Freehand_Mode1_2_2 (void)
void Freehand_Mode2_1_0 (void)
void Freehand_Mode2_1_2 (void)
void Freehand_Mode2_2_0 (void)
void Freehand_Mode2_2_2 (void)
void Freehand_Mode3_1_0 (void)
void Freehand_Mode3_2_0 (void)
void Freehand_Mode3_0_1 (void)
void Ligne_12_0 (void)
void Ligne_12_5 (void)
void Ligne_0_5 (void)
void K_Ligne_12_0 (void)
void K_Ligne_12_6 (void)
void K_Ligne_0_6 (void)
void K_Ligne_12_7 (void)
void Loupe_12_0 (void)
void Rectangle_12_0 (void)
void Rectangle_12_5 (void)
void Rectangle_vide_0_5 (void)
void Rectangle_plein_0_5 (void)
void Cercle_12_0 (void)
void Cercle_12_5 (void)
void Cercle_vide_0_5 (void)
void Cercle_plein_0_5 (void)
void Ellipse_12_0 (void)
void Ellipse_12_5 (void)
void Ellipse_vide_0_5 (void)
void Ellipse_pleine_0_5 (void)
void Fill_1_0 (void)
void Fill_2_0 (void)
void Remplacer_1_0 (void)
void Remplacer_2_0 (void)
void Pipette_12_0 (void)
void Pipette_1_1 (void)
void Pipette_2_1 (void)
void Pipette_0_1 (void)
void Courbe_Tracer_croix (short Pos_X, short Pos_Y)
void Courbe_34_points_1_0 (void)
void Courbe_34_points_2_0 (void)
void Courbe_34_points_1_5 (void)
void Courbe_34_points_2_5 (void)
void Courbe_4_points_0_5 (void)
void Courbe_4_points_1_9 (void)
void Courbe_4_points_2_9 (void)
void Calculer_courbe_3_points (short X1, short Y1, short X4, short Y4, short *X2, short *Y2, short *X3, short *Y3)
void Courbe_3_points_0_5 (void)
void Courbe_3_points_0_11 (void)
void Courbe_3_points_12_11 (void)
void Spray_1_0 (void)
void Spray_2_0 (void)
void Spray_12_2 (void)
void Spray_0_2 (void)
void Polygone_12_0 (void)
void Polygone_12_9 (void)
void Polyfill_12_0 (void)
void Polyfill_0_8 (void)
void Polyfill_12_8 (void)
void Polyfill_12_9 (void)
void Polyform_12_0 (void)
void Polyform_12_8 (void)
void Polyform_0_8 (void)
void Filled_polyform_12_0 (void)
void Filled_polyform_12_8 (void)
void Filled_polyform_0_8 (void)
void Filled_contour_0_8 (void)
void Brosse_12_0 (void)
void Brosse_12_5 (void)
void Brosse_0_5 (void)
void Polybrosse_12_8 (void)
void Etirer_brosse_12_0 (void)
void Etirer_brosse_1_7 (void)
void Etirer_brosse_0_7 (void)
void Etirer_brosse_2_7 (void)
void Tourner_brosse_12_0 (void)
void Tourner_brosse_1_5 (void)
void Tourner_brosse_0_5 (void)
void Tourner_brosse_2_5 (void)
void Scroll_12_0 (void)
void Scroll_12_4 (void)
void Scroll_0_4 (void)
void Cercle_degrade_12_0 (void)
void Cercle_degrade_12_6 (void)
void Cercle_degrade_0_6 (void)
void Cercle_degrade_12_8 (void)
void Cercle_ou_ellipse_degrade_0_8 (void)
void Ellipse_degradee_12_0 (void)
void Ellipse_degradee_12_6 (void)
void Ellipse_degradee_0_6 (void)
void Ellipse_degradee_12_8 (void)
void Rectangle_Degrade_12_0 (void)
void Rectangle_Degrade_12_5 (void)
void Rectangle_Degrade_0_5 (void)
void Rectangle_Degrade_0_7 (void)
void Rectangle_Degrade_12_7 (void)
void Rectangle_Degrade_12_9 (void)
void Rectangle_Degrade_0_9 (void)
void Lignes_centrees_12_0 (void)
void Lignes_centrees_12_3 (void)
void Lignes_centrees_0_3 (void)
void Lignes_centrees_12_7 (void)
void Lignes_centrees_0_7 (void)
Variables
byte Pinceau_Forme_avant_operation
byte Cacher_pinceau_avant_operation
byte Cacher_curseur_avant_courbe
Uint32 Spray_next_time
short * Polyfill_Table_de_points
int Polyfill_Nombre_de_points
byte Cacher_curseur_avant_scroll
Function Documentation
void Demarrer_pile_operation (word Operation_demandee)
References Autoriser_changement_de_couleur_pendant_operation, Brosse_Centre_rotation_defini, CURSEUR_D_OPERATION, Forme_curseur, Operation_avant_interruption, OPERATION_DESSIN_CONTINU, OPERATION_DESSIN_DISCONTINU, Operation_en_cours, OPERATION_ETIRER_BROSSE, OPERATION_LIGNES_CENTREES, OPERATION_LOUPE, OPERATION_PIPETTE, OPERATION_POLYBROSSE, OPERATION_PRISE_BROSSE, OPERATION_SPRAY, Operation_Taille_pile, and OPERATION_TOURNER_BROSSE.
Referenced by Bouton_Ajuster(), Bouton_Brosse(), Bouton_Brush_FX(), Bouton_Cercle_degrade(), Bouton_Cercle_plein(), Bouton_Cercle_vide(), Bouton_Courbes(), Bouton_Courbes_Switch_mode(), Bouton_desenclencher_Brosse(), Bouton_desenclencher_Lasso(), Bouton_desenclencher_Loupe(), Bouton_desenclencher_Pipette(), Bouton_Dessin(), Bouton_Dessin_Switch_mode(), Bouton_Ellipse_degrade(), Bouton_Ellipse_pleine(), Bouton_Ellipse_vide(), Bouton_Fill(), Bouton_Filled_polyform(), Bouton_Lasso(), Bouton_Lignes(), Bouton_Lignes_Switch_mode(), Bouton_Loupe(), Bouton_Pipette(), Bouton_Polyfill(), Bouton_Polyform(), Bouton_Polygone(), Bouton_Rectangle_degrade(), Bouton_Rectangle_plein(), Bouton_Rectangle_vide(), Bouton_Remplacer(), Bouton_Spray(), Etirer_brosse_12_0(), Gestion_principale(), Loupe_12_0(), and Tourner_brosse_12_0().
void Initialiser_debut_operation (void)
References Mouse_X, Operation_dans_loupe, Principal_X_Zoom, and Smear_Debut.
Referenced by Brosse_12_0(), Cercle_12_0(), Cercle_degrade_12_0(), Courbe_34_points_1_0(), Courbe_34_points_2_0(), Ellipse_12_0(), Ellipse_degradee_12_0(), Etirer_brosse_12_0(), Filled_polyform_12_0(), Freehand_Mode1_1_0(), Freehand_Mode1_2_0(), Freehand_Mode2_1_0(), Freehand_Mode2_2_0(), Freehand_Mode3_1_0(), Freehand_Mode3_2_0(), K_Ligne_12_0(), Ligne_12_0(), Lignes_centrees_12_0(), Pipette_12_0(), Polyfill_12_0(), Polyform_12_0(), Polygone_12_0(), Rectangle_12_0(), Rectangle_Degrade_12_0(), Scroll_12_0(), Spray_1_0(), Spray_2_0(), and Tourner_brosse_12_0().
void Operation_PUSH (short Valeur)
References Operation_Pile, and Operation_Taille_pile.
Referenced by Brosse_12_0(), Brosse_12_5(), Cercle_12_0(), Cercle_12_5(), Cercle_degrade_0_6(), Cercle_degrade_12_0(), Cercle_degrade_12_6(), Cercle_ou_ellipse_degrade_0_8(), Courbe_34_points_1_0(), Courbe_34_points_1_5(), Courbe_34_points_2_0(), Courbe_34_points_2_5(), Courbe_3_points_0_11(), Courbe_3_points_0_5(), Courbe_4_points_0_5(), Courbe_4_points_1_9(), Ellipse_12_0(), Ellipse_12_5(), Ellipse_degradee_0_6(), Ellipse_degradee_12_0(), Ellipse_degradee_12_6(), Etirer_brosse_0_7(), Etirer_brosse_12_0(), Etirer_brosse_1_7(), Filled_polyform_0_8(), Filled_polyform_12_0(), Filled_polyform_12_8(), Freehand_Mode1_1_0(), Freehand_Mode1_1_2(), Freehand_Mode1_2_0(), Freehand_Mode1_2_2(), Freehand_Mode2_1_0(), Freehand_Mode2_1_2(), Freehand_Mode2_2_0(), Freehand_Mode2_2_2(), Freehand_Mode3_1_0(), Freehand_Mode3_2_0(), K_Ligne_0_6(), K_Ligne_12_0(), K_Ligne_12_6(), K_Ligne_12_7(), Ligne_12_0(), Ligne_12_5(), Lignes_centrees_0_3(), Lignes_centrees_0_7(), Lignes_centrees_12_0(), Lignes_centrees_12_3(), Lignes_centrees_12_7(), Pipette_12_0(), Polybrosse_12_8(), Polyfill_0_8(), Polyfill_12_0(), Polyfill_12_8(), Polyfill_12_9(), Polyform_0_8(), Polyform_12_0(), Polyform_12_8(), Polygone_12_0(), Polygone_12_9(), Rectangle_12_0(), Rectangle_12_5(), Rectangle_Degrade_0_5(), Rectangle_Degrade_0_7(), Rectangle_Degrade_12_0(), Rectangle_Degrade_12_5(), Rectangle_Degrade_12_7(), Rectangle_Degrade_12_9(), Scroll_12_0(), Scroll_12_4(), Spray_12_2(), Spray_1_0(), Spray_2_0(), Tourner_brosse_0_5(), Tourner_brosse_12_0(), and Tourner_brosse_1_5().
void Operation_POP (short * Valeur)
References Operation_Pile, and Operation_Taille_pile.
Referenced by Brosse_0_5(), Brosse_12_5(), Cercle_12_5(), Cercle_degrade_0_6(), Cercle_degrade_12_6(), Cercle_degrade_12_8(), Cercle_ou_ellipse_degrade_0_8(), Cercle_plein_0_5(), Cercle_vide_0_5(), Courbe_34_points_1_5(), Courbe_34_points_2_5(), Courbe_3_points_0_11(), Courbe_3_points_0_5(), Courbe_3_points_12_11(), Courbe_4_points_0_5(), Courbe_4_points_1_9(), Courbe_4_points_2_9(), Ellipse_12_5(), Ellipse_degradee_0_6(), Ellipse_degradee_12_6(), Ellipse_degradee_12_8(), Ellipse_pleine_0_5(), Ellipse_vide_0_5(), Etirer_brosse_0_7(), Etirer_brosse_1_7(), Etirer_brosse_2_7(), Filled_contour_0_8(), Filled_polyform_0_8(), Filled_polyform_12_8(), Freehand_Mode1_1_2(), Freehand_Mode1_2_2(), Freehand_Mode2_1_2(), Freehand_Mode2_2_2(), K_Ligne_0_6(), K_Ligne_12_6(), K_Ligne_12_7(), Ligne_0_5(), Ligne_12_5(), Lignes_centrees_0_3(), Lignes_centrees_0_7(), Lignes_centrees_12_3(), Lignes_centrees_12_7(), Pipette_0_1(), Polybrosse_12_8(), Polyfill_0_8(), Polyfill_12_8(), Polyfill_12_9(), Polyform_0_8(), Polyform_12_8(), Polygone_12_9(), Rectangle_12_5(), Rectangle_Degrade_0_5(), Rectangle_Degrade_0_9(), Rectangle_Degrade_12_5(), Rectangle_Degrade_12_7(), Rectangle_Degrade_12_9(), Rectangle_plein_0_5(), Rectangle_vide_0_5(), Scroll_12_4(), Spray_12_2(), Tourner_brosse_0_5(), Tourner_brosse_1_5(), and Tourner_brosse_2_5().
short Distance (short X1, short Y1, short X2, short Y2)
References Round().
Referenced by Cercle_12_5(), Cercle_degrade_12_6(), and Courbe_4_points_1_9().
void Aff_coords_rel_ou_abs (short Debut_X, short Debut_Y)
References Config, S_Config::Coords_rel, Menu_visible, Num2str(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Print_dans_menu().
Referenced by Cercle_degrade_0_6(), Cercle_ou_ellipse_degrade_0_8(), Courbe_34_points_1_5(), Courbe_34_points_2_5(), Ellipse_12_5(), Ellipse_degradee_0_6(), Ellipse_degradee_12_6(), K_Ligne_12_6(), Ligne_12_5(), Lignes_centrees_0_7(), Polyfill_12_8(), Rectangle_Degrade_12_9(), and Scroll_12_4().
void Freehand_Mode1_1_0 (void)
References Afficher_pinceau(), Backup(), Fore_color, Initialiser_debut_operation(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Shade_Table, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Freehand_Mode1_1_2 (void)
References Afficher_curseur(), Effacer_curseur, Fore_color, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Tracer_ligne_Definitif().
Referenced by Initialisation_des_operations().
void Freehand_Mode12_0_2 (void)
References Operation_Taille_pile.
Referenced by Initialisation_des_operations().
void Freehand_Mode1_2_0 (void)
References Afficher_pinceau(), Back_color, Backup(), Initialiser_debut_operation(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Shade_Table, and Shade_Table_droite.
Referenced by Initialisation_des_operations().
void Freehand_Mode1_2_2 (void)
References Afficher_curseur(), Back_color, Effacer_curseur, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Tracer_ligne_Definitif().
Referenced by Initialisation_des_operations().
void Freehand_Mode2_1_0 (void)
References Afficher_pinceau(), Backup(), Fore_color, Initialiser_debut_operation(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), Shade_Table, Shade_Table_gauche, and Wait_VBL().
Referenced by Initialisation_des_operations().
void Freehand_Mode2_1_2 (void)
References Afficher_curseur(), Afficher_pinceau(), Effacer_curseur, Fore_color, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Wait_VBL().
Referenced by Initialisation_des_operations().
void Freehand_Mode2_2_0 (void)
References Afficher_pinceau(), Back_color, Backup(), Initialiser_debut_operation(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), Shade_Table, Shade_Table_droite, and Wait_VBL().
Referenced by Initialisation_des_operations().
void Freehand_Mode2_2_2 (void)
References Afficher_curseur(), Afficher_pinceau(), Back_color, Effacer_curseur, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Wait_VBL().
Referenced by Initialisation_des_operations().
void Freehand_Mode3_1_0 (void)
References Afficher_pinceau(), Backup(), Fore_color, Initialiser_debut_operation(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Shade_Table, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Freehand_Mode3_2_0 (void)
References Afficher_pinceau(), Back_color, Backup(), Initialiser_debut_operation(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Shade_Table, and Shade_Table_droite.
Referenced by Initialisation_des_operations().
void Freehand_Mode3_0_1 (void)
References Operation_Taille_pile.
Referenced by Initialisation_des_operations().
void Ligne_12_0 (void)
References A_GAUCHE, Back_color, Backup(), Config, S_Config::Coords_rel, Fore_color, FORME_PINCEAU_POINT, Initialiser_debut_operation(), Menu_visible, Mettre_Ecran_A_Jour(), Mouse_K, Operation_PUSH(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Ligne_12_5 (void)
References A_GAUCHE, Aff_coords_rel_ou_abs(), Afficher_curseur(), Back_color, Effacer_curseur, Effacer_ligne_Preview(), Fore_color, Mouse_K, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Rectifier_coordonnees_a_45_degres(), and Tracer_ligne_Preview().
Referenced by Initialisation_des_operations().
void Ligne_0_5 (void)
References Afficher_pinceau(), Config, S_Config::Coords_rel, Effacer_ligne_Preview(), Menu_visible, Operation_POP(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pixel_figure_Preview_auto(), Print_coordonnees(), Print_dans_menu(), Rectifier_coordonnees_a_45_degres(), and Tracer_ligne_Definitif().
Referenced by Initialisation_des_operations().
void K_Ligne_12_0 (void)
References A_GAUCHE, Back_color, Backup(), Config, S_Config::Coords_rel, Fore_color, FORME_PINCEAU_POINT, Initialiser_debut_operation(), Menu_visible, Mouse_K, Operation_PUSH(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void K_Ligne_12_6 (void)
References Aff_coords_rel_ou_abs(), Afficher_curseur(), Effacer_curseur, Effacer_ligne_Preview(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), and Tracer_ligne_Preview().
Referenced by Initialisation_des_operations().
void K_Ligne_0_6 (void)
References Afficher_pinceau(), Config, S_Config::Coords_rel, Effacer_ligne_Preview(), FORME_PINCEAU_POINT, Menu_visible, Operation_POP(), Operation_PUSH(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pinceau_X, Pinceau_Y, Pixel_figure_Preview_auto(), Print_dans_menu(), and Tracer_ligne_Definitif().
Referenced by Initialisation_des_operations().
void K_Ligne_12_7 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Config, S_Config::Coords_rel, Effacer_curseur, Effacer_ligne_Preview(), Menu_visible, Mouse_K, Operation_POP(), Operation_PUSH(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pixel_figure_Preview_auto(), Print_coordonnees(), and Print_dans_menu().
Referenced by Initialisation_des_operations().
void Loupe_12_0 (void)
References Afficher_curseur(), Afficher_ecran(), Attendre_fin_de_click(), Calculer_coordonnees_pinceau(), Calculer_limites(), Demarrer_pile_operation(), Limite_Bas, Limite_Droite, Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Hauteur, Loupe_Largeur, Loupe_Mode, Mouse_X, Mouse_Y, Operation_avant_interruption, Pixel_Preview, Pixel_Preview_Loupe, Principal_Decalage_X, Principal_Decalage_Y, and Recadrer_ecran_par_rapport_au_zoom().
Referenced by Initialisation_des_operations().
void Rectangle_12_0 (void)
References A_GAUCHE, Afficher_curseur(), Back_color, Config, S_Config::Coords_rel, Fore_color, Initialiser_debut_operation(), Menu_visible, Mouse_K, Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Rectangle_12_5 (void)
References Config, S_Config::Coords_rel, Menu_visible, Num2str(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Print_dans_menu().
Referenced by Initialisation_des_operations().
void Rectangle_vide_0_5 (void)
References Backup(), Config, S_Config::Coords_rel, Effacer_curseur, Menu_visible, Operation_POP(), Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Tracer_rectangle_vide().
Referenced by Initialisation_des_operations().
void Rectangle_plein_0_5 (void)
References Backup(), Config, S_Config::Coords_rel, Effacer_curseur, Menu_visible, Operation_POP(), Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Tracer_rectangle_plein().
Referenced by Initialisation_des_operations().
void Cercle_12_0 (void)
References A_GAUCHE, Back_color, Backup(), Config, S_Config::Coords_rel, Fore_color, FORME_PINCEAU_POINT, Initialiser_debut_operation(), Menu_visible, Mouse_K, Operation_PUSH(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pinceau_X, Pinceau_Y, Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Cercle_12_5 (void)
References Afficher_curseur(), Cercle_Limite, Config, S_Config::Coords_rel, Distance(), Effacer_cercle_vide_Preview(), Effacer_curseur, Menu_visible, Num2str(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Tracer_cercle_vide_Preview().
Referenced by Initialisation_des_operations().
void Cercle_vide_0_5 (void)
References Cercle_Limite, Config, S_Config::Coords_rel, Effacer_cercle_vide_Preview(), Menu_visible, Operation_POP(), Pinceau_Forme, Pinceau_Forme_avant_operation, Print_coordonnees(), Print_dans_menu(), and Tracer_cercle_vide_Definitif().
Referenced by Initialisation_des_operations().
void Cercle_plein_0_5 (void)
References Cercle_Limite, Config, S_Config::Coords_rel, Effacer_cercle_vide_Preview(), Menu_visible, Operation_POP(), Pinceau_Forme, Pinceau_Forme_avant_operation, Print_coordonnees(), Print_dans_menu(), and Tracer_cercle_plein().
Referenced by Initialisation_des_operations().
void Ellipse_12_0 (void)
References A_GAUCHE, Back_color, Backup(), Config, S_Config::Coords_rel, Fore_color, FORME_PINCEAU_POINT, Initialiser_debut_operation(), Menu_visible, Mouse_K, Operation_PUSH(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pinceau_X, Pinceau_Y, Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Ellipse_12_5 (void)
References Aff_coords_rel_ou_abs(), Afficher_curseur(), Effacer_curseur, Effacer_ellipse_vide_Preview(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, and Tracer_ellipse_vide_Preview().
Referenced by Initialisation_des_operations().
void Ellipse_vide_0_5 (void)
References Config, S_Config::Coords_rel, Effacer_ellipse_vide_Preview(), Menu_visible, Operation_POP(), Pinceau_Forme, Pinceau_Forme_avant_operation, Print_coordonnees(), Print_dans_menu(), and Tracer_ellipse_vide_Definitif().
Referenced by Initialisation_des_operations().
void Ellipse_pleine_0_5 (void)
References Config, S_Config::Coords_rel, Effacer_ellipse_vide_Preview(), Menu_visible, Operation_POP(), Pinceau_Forme, Pinceau_Forme_avant_operation, Print_coordonnees(), Print_dans_menu(), and Tracer_ellipse_pleine().
Referenced by Initialisation_des_operations().
void Fill_1_0 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Effacer_curseur, Fore_color, Remplir(), Shade_Table, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Fill_2_0 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Back_color, Effacer_curseur, Remplir(), Shade_Table, and Shade_Table_droite.
Referenced by Initialisation_des_operations().
void Remplacer_1_0 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Backup(), Effacer_curseur, Fore_color, and Remplacer().
Referenced by Initialisation_des_operations().
void Remplacer_2_0 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Back_color, Backup(), Effacer_curseur, and Remplacer().
Referenced by Initialisation_des_operations().
void Pipette_12_0 (void)
References A_GAUCHE, Afficher_foreback(), Back_color, CM_Blanc, CM_Noir, Encadrer_couleur_menu(), Fore_color, Initialiser_debut_operation(), Mouse_K, Operation_PUSH(), Pipette_Couleur, and Recadrer_palette().
Referenced by Initialisation_des_operations().
void Pipette_1_1 (void)
References Afficher_curseur(), Afficher_foreback(), CM_Blanc, CM_Noir, Effacer_curseur, Encadrer_couleur_menu(), Fore_color, Lit_pixel_dans_ecran_courant(), Menu_Facteur_X, Menu_Ordonnee_Texte, Menu_visible, Num2str(), Pinceau_X, Pinceau_Y, Pipette_Couleur, Pipette_X, Pipette_Y, Principal_Hauteur_image, Principal_Largeur_image, Print_coordonnees(), Print_dans_menu(), Print_general(), and Recadrer_palette().
Referenced by Initialisation_des_operations().
void Pipette_2_1 (void)
References Afficher_curseur(), Afficher_foreback(), Back_color, Effacer_curseur, Lit_pixel_dans_ecran_courant(), Menu_Facteur_X, Menu_Ordonnee_Texte, Menu_visible, Num2str(), Pinceau_X, Pinceau_Y, Pipette_Couleur, Pipette_X, Pipette_Y, Principal_Hauteur_image, Principal_Largeur_image, Print_coordonnees(), Print_dans_menu(), and Print_general().
Referenced by Initialisation_des_operations().
void Pipette_0_1 (void)
References A_GAUCHE, Afficher_foreback(), Back_color, BOUTON_PIPETTE, CM_Blanc, CM_Noir, Desenclencher_bouton(), Encadrer_couleur_menu(), Fore_color, Operation_POP(), Pipette_Couleur, and Recadrer_palette().
Referenced by Initialisation_des_operations().
void Courbe_Tracer_croix (short Pos_X, short Pos_Y)
References Limite_Gauche, Limite_Haut, Limite_visible_Bas, Limite_visible_Droite, Lit_pixel, Mettre_Ecran_A_Jour(), Pixel_Preview, Principal_Decalage_X, and Principal_Decalage_Y.
Referenced by Cercle_degrade_0_6(), Cercle_degrade_12_8(), Courbe_4_points_0_5(), Courbe_4_points_1_9(), Courbe_4_points_2_9(), Ellipse_degradee_0_6(), and Ellipse_degradee_12_8().
void Courbe_34_points_1_0 (void)
References Backup(), Cacher_pinceau, Config, S_Config::Coords_rel, Fore_color, Initialiser_debut_operation(), Menu_visible, Mettre_Ecran_A_Jour(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Print_dans_menu(), Shade_Table, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Courbe_34_points_2_0 (void)
References Back_color, Backup(), Cacher_pinceau, Config, S_Config::Coords_rel, Initialiser_debut_operation(), Menu_visible, Mettre_Ecran_A_Jour(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Print_dans_menu(), Shade_Table, and Shade_Table_droite.
Referenced by Initialisation_des_operations().
void Courbe_34_points_1_5 (void)
References Aff_coords_rel_ou_abs(), Afficher_curseur(), Effacer_curseur, Effacer_ligne_Preview(), Fore_color, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), and Tracer_ligne_Preview().
Referenced by Initialisation_des_operations().
void Courbe_34_points_2_5 (void)
References Aff_coords_rel_ou_abs(), Afficher_curseur(), Back_color, Effacer_curseur, Effacer_ligne_Preview(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), and Tracer_ligne_Preview().
Referenced by Initialisation_des_operations().
void Courbe_4_points_0_5 (void)
References Cacher_curseur, Cacher_curseur_avant_courbe, Config, S_Config::Coords_rel, Courbe_Tracer_croix(), Effacer_ligne_Preview(), Menu_visible, Operation_POP(), Operation_PUSH(), Print_coordonnees(), Print_dans_menu(), Round_div(), and Tracer_courbe_Preview().
Referenced by Initialisation_des_operations().
void Courbe_4_points_1_9 (void)
References Afficher_curseur(), Courbe_Tracer_croix(), Distance(), Effacer_courbe_Preview(), Effacer_curseur, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Tracer_courbe_Preview().
Referenced by Initialisation_des_operations().
void Courbe_4_points_2_9 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Cacher_curseur, Cacher_curseur_avant_courbe, Cacher_pinceau, Courbe_Tracer_croix(), Effacer_courbe_Preview(), Effacer_curseur, Operation_POP(), and Tracer_courbe_Definitif().
Referenced by Initialisation_des_operations().
void Calculer_courbe_3_points (short X1, short Y1, short X4, short Y4, short * X2, short * Y2, short * X3, short * Y3)
References Pinceau_X, Pinceau_Y, and Round().
Referenced by Courbe_3_points_0_11(), Courbe_3_points_0_5(), and Courbe_3_points_12_11().
void Courbe_3_points_0_5 (void)
References Calculer_courbe_3_points(), Config, S_Config::Coords_rel, Effacer_ligne_Preview(), Menu_visible, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Tracer_courbe_Preview().
Referenced by Initialisation_des_operations().
void Courbe_3_points_0_11 (void)
References Afficher_curseur(), Calculer_courbe_3_points(), Effacer_courbe_Preview(), Effacer_curseur, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Tracer_courbe_Preview().
Referenced by Initialisation_des_operations().
void Courbe_3_points_12_11 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Cacher_pinceau, Calculer_courbe_3_points(), Effacer_courbe_Preview(), Effacer_curseur, Operation_POP(), and Tracer_courbe_Definitif().
Referenced by Initialisation_des_operations().
void Spray_1_0 (void)
References A_GAUCHE, Aerographe(), Backup(), Initialiser_debut_operation(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Shade_Table, Shade_Table_gauche, Spray_Delay, and Spray_next_time.
Referenced by Initialisation_des_operations().
void Spray_2_0 (void)
References A_DROITE, Aerographe(), Backup(), Initialiser_debut_operation(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Shade_Table, Shade_Table_droite, Spray_Delay, and Spray_next_time.
Referenced by Initialisation_des_operations().
void Spray_12_2 (void)
References Aerographe(), Afficher_curseur(), Effacer_curseur, Menu_visible, Mouse_K_Unique, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), Spray_Delay, and Spray_next_time.
Referenced by Initialisation_des_operations().
void Spray_0_2 (void)
References Operation_Taille_pile.
Referenced by Initialisation_des_operations().
void Polygone_12_0 (void)
References A_GAUCHE, Back_color, Backup(), Config, S_Config::Coords_rel, Fore_color, FORME_PINCEAU_POINT, Initialiser_debut_operation(), Menu_visible, Mettre_Ecran_A_Jour(), Mouse_K, Operation_PUSH(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Polygone_12_9 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Config, S_Config::Coords_rel, Effacer_curseur, Effacer_ligne_Preview(), FORME_PINCEAU_POINT, Menu_visible, Mouse_K, Operation_POP(), Operation_PUSH(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pixel_figure_Preview_auto(), Print_coordonnees(), Print_dans_menu(), and Tracer_ligne_Definitif().
Referenced by Initialisation_des_operations().
void Polyfill_12_0 (void)
References A_GAUCHE, Back_color, Backup(), Cacher_pinceau, Config, S_Config::Coords_rel, Fore_color, Initialiser_debut_operation(), Menu_visible, Mettre_Ecran_A_Jour(), Mouse_K, S_Config::Nb_max_de_vertex_par_polygon, Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview_xor(), Polyfill_Nombre_de_points, Polyfill_Table_de_points, Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Polyfill_0_8 (void)
References Config, S_Config::Coords_rel, Menu_visible, S_Config::Nb_max_de_vertex_par_polygon, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Polyfill_Nombre_de_points, Polyfill_Table_de_points, Print_dans_menu(), and Tracer_ligne_Preview_xor().
Referenced by Initialisation_des_operations().
void Polyfill_12_8 (void)
References Aff_coords_rel_ou_abs(), Afficher_curseur(), Effacer_curseur, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, and Tracer_ligne_Preview_xor().
Referenced by Initialisation_des_operations().
void Polyfill_12_9 (void)
References Afficher_curseur(), Afficher_ecran(), Attendre_fin_de_click(), Cacher_pinceau, Config, S_Config::Coords_rel, Effacer_curseur, Menu_visible, Mouse_K, Operation_POP(), Operation_PUSH(), Polyfill(), Polyfill_Nombre_de_points, Polyfill_Table_de_points, Print_coordonnees(), Print_dans_menu(), and Tracer_ligne_Preview_xor().
Referenced by Initialisation_des_operations().
void Polyform_12_0 (void)
References A_GAUCHE, Afficher_pinceau(), Back_color, Backup(), Fore_color, Initialiser_debut_operation(), Mouse_K, Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Polyform_12_8 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Effacer_curseur, Effacer_ligne_Preview(), Mouse_K, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Pixel_figure_Preview_auto(), Print_coordonnees(), and Tracer_ligne_Definitif().
Referenced by Initialisation_des_operations().
void Polyform_0_8 (void)
References Afficher_curseur(), Effacer_curseur, Effacer_ligne_Preview(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Tracer_ligne_Preview().
Referenced by Initialisation_des_operations().
void Filled_polyform_12_0 (void)
References A_DROITE, A_GAUCHE, Back_color, Backup(), Cacher_pinceau, Config, Fore_color, Initialiser_debut_operation(), Mettre_Ecran_A_Jour(), Mouse_K, S_Config::Nb_max_de_vertex_par_polygon, Operation_en_cours, OPERATION_FILLED_CONTOUR, OPERATION_FILLED_POLYFORM, Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview_xor(), Polyfill_Nombre_de_points, Polyfill_Table_de_points, Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Filled_polyform_12_8 (void)
References Afficher_curseur(), Afficher_ecran(), Attendre_fin_de_click(), Cacher_pinceau, Config, Effacer_curseur, Mouse_K, S_Config::Nb_max_de_vertex_par_polygon, Operation_en_cours, OPERATION_FILLED_CONTOUR, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Polyfill(), Polyfill_Nombre_de_points, Polyfill_Table_de_points, Print_coordonnees(), Tracer_ligne_Preview_xor(), and Tracer_ligne_Preview_xorback().
Referenced by Initialisation_des_operations().
void Filled_polyform_0_8 (void)
References Afficher_curseur(), Effacer_curseur, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Tracer_ligne_Preview_xor().
Referenced by Initialisation_des_operations().
void Filled_contour_0_8 (void)
References Afficher_curseur(), Afficher_ecran(), Cacher_pinceau, Effacer_curseur, Operation_POP(), Polyfill(), Polyfill_Nombre_de_points, Polyfill_Table_de_points, and Print_coordonnees().
Referenced by Initialisation_des_operations().
void Brosse_12_0 (void)
References A_DROITE, Afficher_curseur(), Backup(), Config, S_Config::Coords_rel, Initialiser_debut_operation(), Menu_visible, Mouse_K, Operation_PUSH(), Pinceau_X, Pinceau_Y, and Print_dans_menu().
Referenced by Initialisation_des_operations().
void Brosse_12_5 (void)
References Config, S_Config::Coords_rel, Hauteur, Largeur, Menu_visible, Num2str(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Print_dans_menu().
Referenced by Initialisation_des_operations().
void Brosse_0_5 (void)
References A_DROITE, A_GAUCHE, S_Config::Adjust_brush_pick, Afficher_curseur(), S_Config::Auto_discontinuous, BOUTON_DESSIN, Brosse_Decalage_X, Brosse_Decalage_Y, Capturer_brosse(), Changer_la_forme_du_pinceau(), Config, S_Config::Coords_rel, Effacer_curseur, Enclencher_bouton(), FORME_PINCEAU_BROSSE_COULEUR, Menu_visible, OPERATION_DESSIN_DISCONTINU, Operation_en_cours, Operation_POP(), Operation_Taille_pile, Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), Snap_Hauteur, Snap_Largeur, and Snap_Mode.
Referenced by Initialisation_des_operations().
void Polybrosse_12_8 (void)
References A_DROITE, A_GAUCHE, S_Config::Adjust_brush_pick, Afficher_curseur(), Afficher_ecran(), Attendre_fin_de_click(), S_Config::Auto_discontinuous, BOUTON_DESSIN, Brosse_Decalage_X, Brosse_Decalage_Y, Cacher_pinceau, Capturer_brosse_au_lasso(), Changer_la_forme_du_pinceau(), Config, Effacer_curseur, Enclencher_bouton(), FORME_PINCEAU_BROSSE_COULEUR, Mouse_K, S_Config::Nb_max_de_vertex_par_polygon, OPERATION_DESSIN_DISCONTINU, Operation_en_cours, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Polyfill_Nombre_de_points, Polyfill_Table_de_points, Print_coordonnees(), Snap_Hauteur, Snap_Largeur, Snap_Mode, and Tracer_ligne_Preview_xor().
Referenced by Initialisation_des_operations().
void Etirer_brosse_12_0 (void)
References A_GAUCHE, Afficher_curseur(), Attendre_fin_de_click(), Config, S_Config::Coords_rel, Demarrer_pile_operation(), Initialiser_debut_operation(), Menu_visible, Mouse_K, Operation_avant_interruption, Operation_PUSH(), Pinceau_X, Pinceau_Y, and Print_dans_menu().
Referenced by Initialisation_des_operations().
void Etirer_brosse_1_7 (void)
References S_Config::Adjust_brush_pick, Afficher_curseur(), Afficher_ecran(), Config, S_Config::Coords_rel, Effacer_curseur, Etirer_brosse_preview(), Hauteur, Largeur, Menu_visible, Num2str(), Operation_POP(), Operation_PUSH(), Operation_Taille_pile, Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Snap_Mode.
Referenced by Initialisation_des_operations().
void Etirer_brosse_0_7 (void)
References Afficher_curseur(), Afficher_ecran(), Brosse_Hauteur, Brosse_Largeur, Config, S_Config::Coords_rel, Etirer_brosse_preview(), Hauteur, Largeur, Menu_visible, Num2str(), Operation_POP(), Operation_PUSH(), Operation_Taille_pile, Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Touche_ANSI.
Referenced by Initialisation_des_operations().
void Etirer_brosse_2_7 (void)
References A_DROITE, A_GAUCHE, Afficher_curseur(), Afficher_ecran(), S_Config::Auto_discontinuous, BOUTON_DESSIN, Changer_la_forme_du_pinceau(), Config, S_Config::Coords_rel, Effacer_curseur, Enclencher_bouton(), Etirer_brosse(), FORME_PINCEAU_BROSSE_COULEUR, Menu_visible, OPERATION_DESSIN_DISCONTINU, Operation_en_cours, Operation_POP(), Operation_Taille_pile, Print_coordonnees(), and Print_dans_menu().
Referenced by Initialisation_des_operations().
void Tourner_brosse_12_0 (void)
References A_GAUCHE, Attendre_fin_de_click(), Brosse_Centre_rotation_defini, Brosse_Centre_rotation_X, Brosse_Centre_rotation_Y, Brosse_Largeur, Config, S_Config::Coords_rel, Demarrer_pile_operation(), Initialiser_debut_operation(), Menu_visible, Mouse_K, Operation_avant_interruption, Operation_PUSH(), Pinceau_X, Pinceau_Y, and Print_dans_menu().
Referenced by Initialisation_des_operations().
void Tourner_brosse_1_5 (void)
References Afficher_curseur(), Afficher_ecran(), Brosse_Centre_rotation_X, Brosse_Centre_rotation_Y, Config, S_Config::Coords_rel, M_2PI, Menu_visible, Num2str(), Operation_POP(), Operation_PUSH(), Operation_Taille_pile, Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Tourner_brosse_preview().
Referenced by Initialisation_des_operations().
void Tourner_brosse_0_5 (void)
References Afficher_curseur(), Afficher_ecran(), Brosse_Centre_rotation_X, Brosse_Centre_rotation_Y, Config, S_Config::Coords_rel, M_2PI, Menu_visible, Num2str(), Operation_POP(), Operation_PUSH(), Operation_Taille_pile, Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), Round(), Touche_ANSI, and Tourner_brosse_preview().
Referenced by Initialisation_des_operations().
void Tourner_brosse_2_5 (void)
References A_DROITE, A_GAUCHE, Afficher_curseur(), Afficher_ecran(), S_Config::Auto_discontinuous, BOUTON_DESSIN, Brosse_Centre_rotation_X, Brosse_Centre_rotation_Y, Changer_la_forme_du_pinceau(), Config, S_Config::Coords_rel, Effacer_curseur, Enclencher_bouton(), FORME_PINCEAU_BROSSE_COULEUR, M_2PI, Menu_visible, OPERATION_DESSIN_DISCONTINU, Operation_en_cours, Operation_POP(), Operation_Taille_pile, Print_coordonnees(), Print_dans_menu(), and Tourner_brosse().
Referenced by Initialisation_des_operations().
void Scroll_12_0 (void)
References Backup(), Cacher_curseur, Cacher_curseur_avant_scroll, Config, S_Config::Coords_rel, Initialiser_debut_operation(), Menu_visible, Operation_PUSH(), Pinceau_X, Pinceau_Y, and Print_dans_menu().
Referenced by Initialisation_des_operations().
void Scroll_12_4 (void)
References Aff_coords_rel_ou_abs(), Afficher_ecran(), Decalage_X, Decalage_Y, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Principal_Hauteur_image, Principal_Largeur_image, and Scroll_picture().
Referenced by Initialisation_des_operations().
void Scroll_0_4 (void)
References Cacher_curseur, Cacher_curseur_avant_scroll, Config, S_Config::Coords_rel, Menu_visible, Operation_Taille_pile, Print_coordonnees(), and Print_dans_menu().
Referenced by Initialisation_des_operations().
void Cercle_degrade_12_0 (void)
References A_GAUCHE, Back_color, Backup(), Cacher_pinceau, Cacher_pinceau_avant_operation, Config, S_Config::Coords_rel, Fore_color, Initialiser_debut_operation(), Menu_visible, Mettre_Ecran_A_Jour(), Mouse_K, Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Cercle_degrade_12_6 (void)
References Afficher_curseur(), Cercle_Limite, Config, S_Config::Coords_rel, Distance(), Effacer_cercle_vide_Preview(), Effacer_curseur, Menu_visible, Num2str(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Tracer_cercle_vide_Preview().
Referenced by Initialisation_des_operations().
void Cercle_degrade_0_6 (void)
References A_GAUCHE, Aff_coords_rel_ou_abs(), Back_color, Cacher_pinceau, Cacher_pinceau_avant_operation, Cercle_Limite, Config, S_Config::Coords_rel, Courbe_Tracer_croix(), Effacer_cercle_vide_Preview(), Forme_curseur, FORME_CURSEUR_CIBLE, FORME_CURSEUR_CIBLE_XOR, Menu_visible, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Tracer_cercle_plein().
Referenced by Initialisation_des_operations().
void Cercle_degrade_12_8 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Cacher_pinceau, Cacher_pinceau_avant_operation, Cercle_Limite, Config, S_Config::Coords_rel, Courbe_Tracer_croix(), Effacer_cercle_vide_Preview(), Effacer_curseur, Forme_curseur, FORME_CURSEUR_CIBLE, Menu_visible, Mouse_K, Operation_POP(), Operation_Taille_pile, Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Tracer_cercle_degrade().
Referenced by Initialisation_des_operations().
void Cercle_ou_ellipse_degrade_0_8 (void)
References Aff_coords_rel_ou_abs(), Operation_POP(), Operation_PUSH(), Pinceau_X, and Pinceau_Y.
Referenced by Initialisation_des_operations().
void Ellipse_degradee_12_0 (void)
References A_GAUCHE, Back_color, Backup(), Cacher_pinceau, Cacher_pinceau_avant_operation, Config, S_Config::Coords_rel, Fore_color, Initialiser_debut_operation(), Menu_visible, Mettre_Ecran_A_Jour(), Mouse_K, Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Ellipse_degradee_12_6 (void)
References Aff_coords_rel_ou_abs(), Afficher_curseur(), Effacer_curseur, Effacer_ellipse_vide_Preview(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, and Tracer_ellipse_vide_Preview().
Referenced by Initialisation_des_operations().
void Ellipse_degradee_0_6 (void)
References A_GAUCHE, Aff_coords_rel_ou_abs(), Back_color, Cacher_pinceau, Cacher_pinceau_avant_operation, Config, S_Config::Coords_rel, Courbe_Tracer_croix(), Effacer_ellipse_vide_Preview(), Forme_curseur, FORME_CURSEUR_CIBLE, FORME_CURSEUR_CIBLE_XOR, Menu_visible, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Tracer_ellipse_pleine().
Referenced by Initialisation_des_operations().
void Ellipse_degradee_12_8 (void)
References Attendre_fin_de_click(), Cacher_pinceau, Cacher_pinceau_avant_operation, Config, S_Config::Coords_rel, Courbe_Tracer_croix(), Effacer_ellipse_vide_Preview(), Forme_curseur, FORME_CURSEUR_CIBLE, Menu_visible, Mouse_K, Operation_POP(), Operation_Taille_pile, Pinceau_X, Pinceau_Y, Print_coordonnees(), Print_dans_menu(), and Tracer_ellipse_degradee().
Referenced by Initialisation_des_operations().
void Rectangle_Degrade_12_0 (void)
References A_GAUCHE, Afficher_curseur(), Backup(), Config, S_Config::Coords_rel, Initialiser_debut_operation(), Menu_visible, Mouse_K, Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Rectangle_Degrade_12_5 (void)
References Config, S_Config::Coords_rel, Menu_visible, Num2str(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_coordonnees(), and Print_dans_menu().
Referenced by Initialisation_des_operations().
void Rectangle_Degrade_0_5 (void)
References Effacer_curseur, Largeur_ecran, Ligne_horizontale_XOR, Ligne_horizontale_XOR_Zoom(), Ligne_verticale_XOR, Ligne_verticale_XOR_Zoom(), Limite_Gauche_Zoom, Limite_Haut_Zoom, Limite_visible_Bas_Zoom, Limite_visible_Droite_Zoom, Loupe_Mode, Max(), Menu_Ordonnee, Min(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Principal_Decalage_X, Principal_Decalage_Y, Principal_Hauteur_image, Principal_Largeur_image, Principal_Split, and UpdateRect().
Referenced by Initialisation_des_operations().
void Rectangle_Degrade_0_7 (void)
References Operation_PUSH(), Operation_Taille_pile, Pinceau_X, Pinceau_Y, and Print_coordonnees().
Referenced by Initialisation_des_operations().
void Rectangle_Degrade_12_7 (void)
References Largeur_ecran, Ligne_horizontale_XOR, Ligne_horizontale_XOR_Zoom(), Ligne_verticale_XOR, Ligne_verticale_XOR_Zoom(), Limite_Gauche_Zoom, Limite_Haut_Zoom, Limite_visible_Bas_Zoom, Limite_visible_Droite_Zoom, Loupe_Mode, Max(), Menu_Ordonnee, Min(), Mouse_K, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Principal_Decalage_X, Principal_Decalage_Y, Principal_Hauteur_image, Principal_Largeur_image, Principal_Split, and UpdateRect().
Referenced by Initialisation_des_operations().
void Rectangle_Degrade_12_9 (void)
References Aff_coords_rel_ou_abs(), Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Rectifier_coordonnees_a_45_degres(), and Tracer_ligne_Preview_xor().
Referenced by Initialisation_des_operations().
void Rectangle_Degrade_0_9 (void)
References Afficher_curseur(), Attendre_fin_de_click(), Config, S_Config::Coords_rel, Effacer_curseur, Effacer_ligne_Preview(), Largeur_ecran, Ligne_horizontale_XOR, Ligne_horizontale_XOR_Zoom(), Ligne_verticale_XOR, Ligne_verticale_XOR_Zoom(), Limite_Gauche_Zoom, Limite_Haut_Zoom, Limite_visible_Bas_Zoom, Limite_visible_Droite_Zoom, Loupe_Mode, Max(), Menu_Ordonnee, Menu_visible, Min(), Operation_POP(), Operation_Taille_pile, Principal_Decalage_X, Principal_Decalage_Y, Principal_Hauteur_image, Principal_Largeur_image, Principal_Split, Print_coordonnees(), Print_dans_menu(), Tracer_rectangle_degrade(), and UpdateRect().
Referenced by Initialisation_des_operations().
void Lignes_centrees_12_0 (void)
References A_GAUCHE, Backup(), Config, S_Config::Coords_rel, Initialiser_debut_operation(), Menu_visible, Mouse_K, Operation_PUSH(), Pinceau_X, Pinceau_Y, Print_dans_menu(), Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Initialisation_des_operations().
void Lignes_centrees_12_3 (void)
References Operation_POP(), Operation_PUSH(), Pinceau_X, and Pinceau_Y.
Referenced by Initialisation_des_operations().
void Lignes_centrees_0_3 (void)
References A_GAUCHE, Back_color, Bouton, Fore_color, FORME_PINCEAU_POINT, Operation_POP(), Operation_PUSH(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pinceau_X, Pinceau_Y, and Pixel_figure_Preview().
Referenced by Initialisation_des_operations().
void Lignes_centrees_12_7 (void)
References A_GAUCHE, Afficher_curseur(), Afficher_pinceau(), Attendre_fin_de_click(), Back_color, Bouton, Config, S_Config::Coords_rel, Effacer_curseur, Effacer_ligne_Preview(), Fore_color, FORME_PINCEAU_POINT, Menu_visible, Mouse_K, Operation_POP(), Operation_PUSH(), Pinceau_Forme, Pinceau_Forme_avant_operation, Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), Pixel_figure_Preview_auto(), Print_coordonnees(), Print_dans_menu(), Smear_Debut, Tracer_ligne_Definitif(), and Tracer_ligne_Preview().
Referenced by Initialisation_des_operations().
void Lignes_centrees_0_7 (void)
References A_GAUCHE, Aff_coords_rel_ou_abs(), Afficher_curseur(), Back_color, Bouton, Effacer_curseur, Effacer_ligne_Preview(), Fore_color, Operation_POP(), Operation_PUSH(), Pinceau_X, Pinceau_Y, Pixel_figure_Preview(), and Tracer_ligne_Preview().
Referenced by Initialisation_des_operations().
Variable Documentation
byte Pinceau_Forme_avant_operation
Referenced by Cercle_12_0(), Cercle_plein_0_5(), Cercle_vide_0_5(), Ellipse_12_0(), Ellipse_pleine_0_5(), Ellipse_vide_0_5(), K_Ligne_0_6(), K_Ligne_12_0(), K_Ligne_12_7(), Ligne_0_5(), Ligne_12_0(), Lignes_centrees_0_3(), Lignes_centrees_12_7(), Polygone_12_0(), and Polygone_12_9().
byte Cacher_pinceau_avant_operation
Referenced by Cercle_degrade_0_6(), Cercle_degrade_12_0(), Cercle_degrade_12_8(), Ellipse_degradee_0_6(), Ellipse_degradee_12_0(), and Ellipse_degradee_12_8().
byte Cacher_curseur_avant_courbe
Referenced by Courbe_4_points_0_5(), and Courbe_4_points_2_9().
Uint32 Spray_next_time
Referenced by Spray_12_2(), Spray_1_0(), and Spray_2_0().
short* Polyfill_Table_de_points
Referenced by Filled_contour_0_8(), Filled_polyform_12_0(), Filled_polyform_12_8(), Polybrosse_12_8(), Polyfill_0_8(), Polyfill_12_0(), and Polyfill_12_9().
int Polyfill_Nombre_de_points
Referenced by Filled_contour_0_8(), Filled_polyform_12_0(), Filled_polyform_12_8(), Polybrosse_12_8(), Polyfill_0_8(), Polyfill_12_0(), and Polyfill_12_9().
byte Cacher_curseur_avant_scroll
Referenced by Scroll_0_4(), and Scroll_12_0().