GrafX2: pxsimple.c File Reference
pxsimple.c File Reference
#include <string.h>
#include <stdlib.h>
#include <SDL.h>
#include "global.h"
#include "sdlscreen.h"
#include "divers.h"
Functions
void Pixel_Simple (word X, word Y, byte Couleur)
byte Lit_Pixel_Simple (word X, word Y)
void Block_Simple (word Debut_X, word Debut_Y, word Largeur, word Hauteur, byte Couleur)
void Afficher_partie_de_l_ecran_Simple (word Largeur, word Hauteur, word Largeur_image)
void Pixel_Preview_Normal_Simple (word X, word Y, byte Couleur)
void Pixel_Preview_Loupe_Simple (word X, word Y, byte Couleur)
void Ligne_horizontale_XOR_Simple (word Pos_X, word Pos_Y, word Largeur)
void Ligne_verticale_XOR_Simple (word Pos_X, word Pos_Y, word Hauteur)
void Display_brush_Color_Simple (word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Hauteur, byte Couleur_de_transparence, word Largeur_brosse)
void Display_brush_Mono_Simple (word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Hauteur, byte Couleur_de_transparence, byte Couleur, word Largeur_brosse)
void Clear_brush_Simple (word Pos_X, word Pos_Y, __attribute__((unused)) word Decalage_X, __attribute__((unused)) word Decalage_Y, word Largeur, word Hauteur, __attribute__((unused)) byte Couleur_de_transparence, word Largeur_image)
void Affiche_brosse_Simple (byte *B, word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Hauteur, byte Couleur_de_transparence, word Largeur_brosse)
void Remap_screen_Simple (word Pos_X, word Pos_Y, word Largeur, word Hauteur, byte *Table_de_conversion)
void Afficher_une_ligne_ecran_Simple (word Pos_X, word Pos_Y, word Largeur, byte *Ligne)
void Afficher_une_ligne_transparente_mono_a_l_ecran_Simple (word Pos_X, word Pos_Y, word Largeur, byte *Ligne, byte Couleur_transparence, byte Couleur)
void Lire_une_ligne_ecran_Simple (word Pos_X, word Pos_Y, word Largeur, byte *Ligne)
void Afficher_partie_de_l_ecran_zoomee_Simple (word Largeur, word Hauteur, word Largeur_image, byte *Buffer)
void Afficher_une_ligne_transparente_a_l_ecran_Simple (word Pos_X, word Pos_Y, word Largeur, byte *Ligne, byte Couleur_transparence)
void Display_brush_Color_zoom_Simple (word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Pos_Y_Fin, byte Couleur_de_transparence, word Largeur_brosse, byte *Buffer)
void Display_brush_Mono_zoom_Simple (word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Pos_Y_Fin, byte Couleur_de_transparence, byte Couleur, word Largeur_brosse, byte *Buffer)
void Clear_brush_zoom_Simple (word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Pos_Y_Fin, __attribute__((unused)) byte Couleur_de_transparence, word Largeur_image, byte *Buffer)
Function Documentation
void Pixel_Simple (word X, word Y, byte Couleur)
References Ecran, and Largeur_ecran.
Referenced by Initialiser_mode_video(), Pixel_Preview_Loupe_Simple(), and Pixel_Preview_Normal_Simple().
byte Lit_Pixel_Simple (word X, word Y)
References Ecran, and Largeur_ecran.
Referenced by Initialiser_mode_video().
void Block_Simple (word Debut_X, word Debut_Y, word Largeur, word Hauteur, byte Couleur)
References Ecran_SDL.
Referenced by Initialiser_mode_video(), and Pixel_Preview_Loupe_Simple().
void Afficher_partie_de_l_ecran_Simple (word Largeur, word Hauteur, word Largeur_image)
References Ecran, Largeur_ecran, Principal_Decalage_X, Principal_Decalage_Y, and Principal_Ecran.
Referenced by Initialiser_mode_video().
void Pixel_Preview_Normal_Simple (word X, word Y, byte Couleur)
References Pixel_Simple(), Principal_Decalage_X, and Principal_Decalage_Y.
Referenced by Initialiser_mode_video().
void Pixel_Preview_Loupe_Simple (word X, word Y, byte Couleur)
References Block_Simple(), Limite_Gauche_Zoom, Limite_Haut_Zoom, Limite_visible_Bas_Zoom, Limite_visible_Droite_Zoom, Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Facteur, Menu_Ordonnee, Pixel_Simple(), Principal_Decalage_X, Principal_Decalage_Y, Principal_X_Zoom, and Table_mul_facteur_zoom.
Referenced by Initialiser_mode_video().
void Ligne_horizontale_XOR_Simple (word Pos_X, word Pos_Y, word Largeur)
References Ecran, and Largeur_ecran.
Referenced by Initialiser_mode_video().
void Ligne_verticale_XOR_Simple (word Pos_X, word Pos_Y, word Hauteur)
References Ecran, and Largeur_ecran.
Referenced by Initialiser_mode_video().
void Display_brush_Color_Simple (word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Hauteur, byte Couleur_de_transparence, word Largeur_brosse)
References Brosse, Ecran, Largeur_ecran, and UpdateRect().
Referenced by Initialiser_mode_video().
void Display_brush_Mono_Simple (word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Hauteur, byte Couleur_de_transparence, byte Couleur, word Largeur_brosse)
References Brosse, Ecran, Largeur_ecran, and UpdateRect().
Referenced by Initialiser_mode_video().
void Clear_brush_Simple (word Pos_X, word Pos_Y, __attribute__((unused)) word Decalage_X, __attribute__((unused)) word Decalage_Y, word Largeur, word Hauteur, __attribute__((unused)) byte Couleur_de_transparence, word Largeur_image)
References Ecran, Largeur_ecran, Principal_Decalage_X, Principal_Decalage_Y, Principal_Ecran, and UpdateRect().
Referenced by Initialiser_mode_video().
void Affiche_brosse_Simple (byte * B, word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Hauteur, byte Couleur_de_transparence, word Largeur_brosse)
References Ecran, and Largeur_ecran.
Referenced by Initialiser_mode_video().
void Remap_screen_Simple (word Pos_X, word Pos_Y, word Largeur, word Hauteur, byte * Table_de_conversion)
References Ecran, Largeur_ecran, and UpdateRect().
Referenced by Initialiser_mode_video().
void Afficher_une_ligne_ecran_Simple (word Pos_X, word Pos_Y, word Largeur, byte * Ligne)
References Ecran, and Largeur_ecran.
Referenced by Afficher_partie_de_l_ecran_zoomee_Simple(), Afficher_partie_de_l_ecran_zoomee_Tall(), Clear_brush_zoom_Simple(), and Initialiser_mode_video().
void Afficher_une_ligne_transparente_mono_a_l_ecran_Simple (word Pos_X, word Pos_Y, word Largeur, byte * Ligne, byte Couleur_transparence, byte Couleur)
References Ecran, and Largeur_ecran.
Referenced by Display_brush_Mono_zoom_Simple(), and Display_brush_Mono_zoom_Tall().
void Lire_une_ligne_ecran_Simple (word Pos_X, word Pos_Y, word Largeur, byte * Ligne)
References Ecran, and Largeur_ecran.
Referenced by Initialiser_mode_video().
void Afficher_partie_de_l_ecran_zoomee_Simple (word Largeur, word Hauteur, word Largeur_image, byte * Buffer)
References Afficher_une_ligne_ecran_Simple(), Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Facteur, Principal_Ecran, Principal_X_Zoom, UpdateRect(), and Zoomer_une_ligne().
Referenced by Initialiser_mode_video().
void Afficher_une_ligne_transparente_a_l_ecran_Simple (word Pos_X, word Pos_Y, word Largeur, byte * Ligne, byte Couleur_transparence)
References Ecran, and Largeur_ecran.
Referenced by Display_brush_Color_zoom_Simple(), and Display_brush_Color_zoom_Tall().
void Display_brush_Color_zoom_Simple (word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Pos_Y_Fin, byte Couleur_de_transparence, word Largeur_brosse, byte * Buffer)
References Afficher_une_ligne_transparente_a_l_ecran_Simple(), Brosse, Loupe_Facteur, and Zoomer_une_ligne().
Referenced by Initialiser_mode_video().
void Display_brush_Mono_zoom_Simple (word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Pos_Y_Fin, byte Couleur_de_transparence, byte Couleur, word Largeur_brosse, byte * Buffer)
References Afficher_une_ligne_transparente_mono_a_l_ecran_Simple(), Brosse, Loupe_Facteur, UpdateRect(), and Zoomer_une_ligne().
Referenced by Initialiser_mode_video().
void Clear_brush_zoom_Simple (word Pos_X, word Pos_Y, word Decalage_X, word Decalage_Y, word Largeur, word Pos_Y_Fin, __attribute__((unused)) byte Couleur_de_transparence, word Largeur_image, byte * Buffer)
References Afficher_une_ligne_ecran_Simple(), Loupe_Facteur, Principal_Ecran, UpdateRect(), and Zoomer_une_ligne().
Referenced by Initialiser_mode_video().