GrafX2: saveini.h File Reference
saveini.h File Reference
Functions
int Sauver_INI (struct S_Config *Conf)
Function Documentation
int Sauver_INI (struct S_Config * Conf)
References S_Config::Adjust_brush_pick, S_Config::Afficher_limites_image, S_Config::Auto_discontinuous, S_Config::Auto_nb_used, S_Config::Auto_save, S_Config::Auto_set_res, S_Config::Backup, S_Config::Bookmark_directory, S_Config::Bookmark_label, S_Config::Chrono_delay, S_Config::Clear_palette, S_Config::Clear_with_stencil, S_Config::Coords_rel, S_Config::Coul_menu_pref, S_Config::Couleurs_separees, S_Config::Curseur, ERREUR_INI_ABSENT, ERREUR_SAUVEGARDE_INI, S_Config::Fast_zoom, Fichier_existe(), S_Config::Find_file_fast, S_Config::Fonte, S_Config::FX_Feedback, S_Mode_video::Hauteur, S_Config::Indice_Sensibilite_souris_X, S_Config::Indice_Sensibilite_souris_Y, S_Mode_video::Largeur, Libelle_mode(), S_Config::Lire_les_fichiers_caches, S_Config::Lire_les_repertoires_caches, S_Config::Maximize_preview, Mode_video, S_Config::Mouse_Facteur_de_correction_X, S_Config::Mouse_Facteur_de_correction_Y, S_Config::Mouse_Merge_movement, NB_BOOKMARKS, S_Config::Nb_max_de_vertex_par_polygon, S_Config::Nb_pages_Undo, S_Config::Opening_message, S_Config::Palette_Cells_X, S_Config::Palette_Cells_Y, S_Config::Ratio, Repertoire_de_configuration, Repertoire_des_donnees, S_Config::Resolution_par_defaut, S_Config::Safety_colors, Sauver_INI_Flush(), Sauver_INI_Reach_group(), Sauver_INI_Set_strings(), Sauver_INI_Set_values(), S_Config::Set_resolution_according_to, TAILLE_CHEMIN_FICHIER, S_Config::Taille_ecran_dans_GIF, S_Config::Valeur_tempo_jauge_droite, and S_Config::Valeur_tempo_jauge_gauche.
Referenced by Fermeture_du_programme(), and Settings_Sauver_config().