main.o: main.c const.h struct.h global.h loadsave.h graph.h divers.h \
  init.h boutons.h moteur.h pages.h files.h sdlscreen.h erreurs.h \
  readini.h saveini.h linux.h
init.o: init.c const.h struct.h global.h loadsave.h graph.h boutons.h \
  palette.h aide.h operatio.h divers.h erreurs.h clavier.h io.h
graph.o: graph.c sdlscreen.h struct.h const.h graph.h divers.h moteur.h \
  boutons.h pages.h global.h loadsave.h erreurs.h
sdlscreen.o: sdlscreen.c global.h struct.h const.h loadsave.h sdlscreen.h \
  divers.h erreurs.h
divers.o: divers.c struct.h const.h sdlscreen.h global.h loadsave.h \
  graph.h erreurs.h boutons.h moteur.h divers.h clavier.h
special.o: special.c const.h struct.h global.h loadsave.h graph.h \
  moteur.h
boutons.o: boutons.c const.h struct.h global.h loadsave.h divers.h \
  graph.h moteur.h readline.h files.h init.h boutons.h operatio.h pages.h \
  erreurs.h readini.h saveini.h shade.h
palette.o: palette.c const.h struct.h global.h loadsave.h divers.h \
  graph.h moteur.h readline.h boutons.h pages.h
aide.o: aide.c const.h struct.h global.h loadsave.h divers.h graph.h \
  moteur.h tables_aide.h
operatio.o: operatio.c const.h struct.h global.h loadsave.h divers.h \
  moteur.h graph.h operatio.h boutons.h pages.h erreurs.h
pages.o: pages.c global.h struct.h const.h loadsave.h pages.h graph.h \
  erreurs.h linux.h
loadsave.o: loadsave.c const.h struct.h global.h loadsave.h graph.h \
  divers.h pages.h op_c.h boutons.h erreurs.h linux.h io.h
readline.o: readline.c const.h struct.h global.h loadsave.h graph.h \
  divers.h erreurs.h linux.h
moteur.o: moteur.c const.h struct.h global.h loadsave.h graph.h divers.h \
  special.h boutons.h operatio.h shade.h erreurs.h linux.h
files.o: files.c const.h struct.h global.h loadsave.h graph.h divers.h \
  erreurs.h linux.h
op_c.o: op_c.c op_c.h struct.h const.h op_asm.h erreurs.h
linux.o: linux.c
op_asm.o: op_asm.c op_c.h struct.h const.h graph.h
readini.o: readini.c const.h global.h struct.h loadsave.h
saveini.o: saveini.c const.h global.h struct.h loadsave.h readini.h \
  files.h erreurs.h
shade.o: shade.c global.h struct.h const.h loadsave.h graph.h moteur.h \
  divers.h readline.h
clavier.o: clavier.c global.h struct.h const.h loadsave.h
io.o: io.c struct.h const.h
