GrafX2: boutons.h File Reference
boutons.h File Reference
Functions
void Message_Non_disponible (void)
Displays an error message when calling an unavailable function.
void Message_Memoire_insuffisante (void)
Displays an error message when there is no more memory for the requested operation.
void Bouton_Message_initial (void)
Displays the splash screen at program startup.
void Changer_la_forme_du_pinceau (byte Numero)
Changes brush shape.
void Bouton_Pal_left (void)
Callback for the palette scroller buttons left click.
void Bouton_Pal_left_fast (void)
Callback for the palette scroller buttons right click.
void Bouton_Pal_right (void)
Callback for the palette scroller buttons left click.
void Bouton_Pal_right_fast (void)
Callback for the palette scroller buttons right click.
void Bouton_Choix_forecolor (void)
Callback for the palette color buttons left click.
void Bouton_Choix_backcolor (void)
Callback for the palette color buttons right click.
void Bouton_Brosse_monochrome (void)
Callback for the brush button left click.
void Bouton_Menu_pinceaux (void)
Callback for the brush button right click.
void Bouton_Dessin (void)
Callback for the freehand draw button left click.
void Bouton_Dessin_Switch_mode (void)
Callback for the freehand draw button right click.
void Bouton_Lignes (void)
Callback for the lines button left click.
void Bouton_Lignes_Switch_mode (void)
Callback for the lines button right click.
void Bouton_Fill (void)
Callback for the fill button left click.
void Bouton_Remplacer (void)
Callback for the fill button right click.
void Bouton_desenclencher_Fill (void)
Disable and release the fill button.
void Bouton_Spray (void)
Callback for the spray button left click.
void Bouton_Spray_Menu (void)
Callback for the spray button right click.
void Bouton_Courbes (void)
Callback for the curves button left click.
void Bouton_Courbes_Switch_mode (void)
Callback for the curves button right click.
void Bouton_Rectangle_vide (void)
Callback for the empty rectangle button.
void Bouton_Rectangle_plein (void)
Callback for the filled rectangle button.
void Bouton_Texte (void)
Callback for the text button.
void Bouton_Degrades (void)
Callback for the gradation button.
void Degrade_Charger_infos_du_tableau (int Indice)
Gets the informations from the gradations table and set the global vars for the current gradation.
void Bouton_Cercle_degrade (void)
Callback for the gradation circle button left click.
void Bouton_Ellipse_degrade (void)
Callback for the gradation circle right click.
void Bouton_Rectangle_degrade (void)
Callback for the gradation rectangle button.
void Bouton_Cercle_vide (void)
Callback for the circle button left click.
void Bouton_Ellipse_vide (void)
Callback for the circle button left click.
void Bouton_Cercle_plein (void)
Callback for the filled circle button ledt click.
void Bouton_Ellipse_pleine (void)
Callback for the filled circle right click.
void Bouton_Polygone (void)
Callback for the polyline button left click.
void Bouton_Polyform (void)
Callback for the polyline right click.
void Bouton_Polyfill (void)
Callback for the polyfill button left click.
void Bouton_Filled_polyform (void)
Callback for the polyfill button right click.
void Bouton_Ajuster (void)
Callback for the adjust picture button.
void Bouton_Shade_Mode (void)
Callback for the shade button (in the FX window).
void Bouton_Quick_shade_Mode (void)
Callback for the QSHade button (in the FX window).
void Bouton_Shade_Menu (void)
Callback for the Shade button (in the FX window) right click.
void Bouton_Stencil_Mode (void)
Callback for the Stencil button (in the FX window) left click.
void Bouton_Menu_Stencil (void)
Callback for the Stencil button (in the FX window) right click.
void Bouton_Mask_Mode (void)
Callback for the Mask button (in the FX window) left click.
void Bouton_Mask_Menu (void)
Callback for the Mask button (in the FX window) right click.
void Bouton_Snap_Mode (void)
Callback for the Grid button (in the FX window) left click.
void Bouton_Menu_Grille (void)
Callback for the Grid button (in the FX window) right click.
void Copier_trame_predefinie (byte Indice)
In the sieve window, copy one of the presets patterns to the current one.
void Inverser_trame (void)
In the sieve window, swaps black and white in the current pattern.
void Bouton_Trame_Mode (void)
Callback for the Sieve button (in the FX window) left click.
void Bouton_Trame_Menu (void)
Callback for the Sieve button (in the FX window) right click.
void Bouton_Smooth_Mode (void)
Callback for the smooth button (in the FX window) left click.
void Calculer_les_tables_de_Colorize (void)
Computes the tables used by the transparency/colorize mode.
void Bouton_Colorize_Mode (void)
Callback for the Tranparency button (in the FX window) left click.
void Bouton_Colorize_Menu (void)
Callback for the Transparency button (in the FX window) right click.
void Bouton_Tiling_Mode (void)
Callback for the Tiling button (in the FX window) left click.
void Bouton_Tiling_Menu (void)
Callback for the Tiling button (in the FX window) right click.
void Bouton_Effets (void)
Callback for the effects button click.
void Bouton_Brosse (void)
Callback for the brush button left click.
void Bouton_Restaurer_brosse (void)
Callback for the brush button right click.
void Bouton_desenclencher_Brosse (void)
Disables the custom brush and set back a regular one.
void Bouton_Lasso (void)
Callback for the freehand brush pick button left click.
void Bouton_desenclencher_Lasso (void)
Disables the custom freehand brush and set back a regular one.
void Bouton_Pipette (void)
Starts the color picking operation.
void Bouton_desenclencher_Pipette (void)
Disables the color picker button and get back to the previously selected drawing mode.
void Bouton_Inverser_foreback (void)
Swap fore- and background colors.
void Bouton_Loupe (void)
Enters magnify mode.
void Bouton_Menu_Loupe (void)
Displays magnify menu.
void Bouton_desenclencher_Loupe (void)
Exit magnify mode.
void Bouton_Brush_FX (void)
Display the Brush effects window.
void Bouton_Page (void)
Swap main and spare drawing pages.
void Bouton_Copy_page (void)
Copy main page to spare page.
void Copier_image_seule (void)
Copy only pixel data from main page to spare page (no palette copy).
void Bouton_Kill (void)
Kill (free from memory) the current page.
void Bouton_Resol (void)
Display the screenmode menu.
void Bouton_Safety_resol (void)
Set the screen to the "safe resolution" (320x200 pixel window).
void Bouton_Load (void)
Opens the load file dialog.
void Bouton_Reload (void)
Reload current picture from disk.
void Bouton_Save (void)
Open the save file dialog.
void Bouton_Autosave (void)
Saves the current file without asking for a new name.
void Bouton_Settings (void)
Display the setting menu.
void Bouton_Undo (void)
Undo the last modification to the picture.
void Bouton_Redo (void)
Redo an operation that has been undone.
void Bouton_Clear (void)
Clear the whole screen with black (color index 0).
void Bouton_Clear_colore (void)
Clear the screen with the selected backcolor.
void Bouton_Quit (void)
Quits the program.
void Bouton_Cacher_menu (void)
Hides the menubar.
void Load_picture (byte Image)
Load picture from file.
void Save_picture (byte Image)
Save picture to file.
void Menu_Tag_couleurs (char *En_tete, byte *Table, byte *Mode, byte Cancel, const char *Section_aide)
Generic color tagging menu, for various effects.
void Bouton_Smooth_Menu (void)
Display the menu for the smooth effect.
void Bouton_Smear_Mode (void)
Toogles the smear mode.
Function Documentation
void Message_Non_disponible (void)
Displays an error message when calling an unavailable function.
Only used in the beta versions for things we haven't coded yet.
References Afficher_curseur(), CM_Clair, CM_Noir, Display_Window, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), Ouvrir_fenetre(), Print_dans_fenetre(), Touche, and TOUCHE_ESC.
Referenced by Bouton_Brush_FX(), Gestion_principale(), and Initialisation_des_boutons().
void Message_Memoire_insuffisante (void)
Displays an error message when there is no more memory for the requested operation.
References Afficher_curseur(), CM_Clair, CM_Noir, Display_Window, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), Ouvrir_fenetre(), Print_dans_fenetre(), Touche, and TOUCHE_ESC.
Referenced by Copier_image_seule(), Initialiser_preview(), Initialiser_preview_24b(), and Redimentionner_image().
void Bouton_Message_initial (void)
Displays the splash screen at program startup.
References Afficher_curseur(), ALPHA_BETA, Attendre_fin_de_click(), Block, CM_Clair, CM_Fonce, CM_Noir, Display_Window, Fenetre_Afficher_cadre_creux(), Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Get_input(), Logo_GrafX2, Menu_Facteur_X, Menu_Facteur_Y, Mouse_K, Ouvrir_fenetre(), Pixel_dans_fenetre(), POURCENTAGE_VERSION, Print_dans_fenetre(), Touche, VERSION1, VERSION2, and Wait_VBL().
Referenced by main().
void Changer_la_forme_du_pinceau (byte Numero)
Changes brush shape.
This function saves the current brush shape and swith to the default one (single pixel brush) for the filler and the color picker. These functions don't need (and will not work with) a custom brush.
References Afficher_pinceau_dans_menu(), FORME_PINCEAU_POINT, Operation_en_cours, OPERATION_FILL, OPERATION_PIPETTE, Pinceau_Forme, Pinceau_Forme_avant_fill, and Pinceau_Forme_avant_pipette.
Referenced by Bouton_Brosse_monochrome(), Bouton_Menu_pinceaux(), Bouton_Restaurer_brosse(), Bouton_Texte(), Bouton_Trame_Menu(), Brosse_0_5(), Etirer_brosse_2_7(), Gestion_principale(), Load_picture(), Polybrosse_12_8(), and Tourner_brosse_2_5().
void Bouton_Pal_left (void)
Callback for the palette scroller buttons left click.
Scrolls the menubar palette one column to the left.
References Afficher_curseur(), Afficher_palette_du_menu(), BOUTON_PAL_LEFT, Couleur_debut_palette, Desenclencher_bouton(), Effacer_curseur, and Palette_Cells_Y().
Referenced by Initialisation_des_boutons().
void Bouton_Pal_left_fast (void)
Callback for the palette scroller buttons right click.
Scrolls the menubar palette faster to the left.
References Afficher_curseur(), Afficher_palette_du_menu(), BOUTON_PAL_LEFT, Couleur_debut_palette, Desenclencher_bouton(), Effacer_curseur, Palette_Cells_X(), and Palette_Cells_Y().
Referenced by Initialisation_des_boutons().
void Bouton_Pal_right (void)
Callback for the palette scroller buttons left click.
Scrolls the menubar palette one column to the right.
References Afficher_curseur(), Afficher_palette_du_menu(), BOUTON_PAL_RIGHT, Couleur_debut_palette, Desenclencher_bouton(), Effacer_curseur, Palette_Cells_X(), and Palette_Cells_Y().
Referenced by Initialisation_des_boutons().
void Bouton_Pal_right_fast (void)
Callback for the palette scroller buttons right click.
Scrolls the menubar palette faster to the right.
References Afficher_curseur(), Afficher_palette_du_menu(), BOUTON_PAL_RIGHT, Couleur_debut_palette, Desenclencher_bouton(), Effacer_curseur, Palette_Cells_X(), and Palette_Cells_Y().
Referenced by Initialisation_des_boutons().
void Bouton_Choix_forecolor (void)
Callback for the palette color buttons left click.
Selects the foreground drawing color when clicking on the menubar palette.
References Afficher_curseur(), Afficher_foreback(), CM_Blanc, CM_Noir, Couleur_palette(), Effacer_curseur, Encadrer_couleur_menu(), and Fore_color.
Referenced by Initialisation_des_boutons().
void Bouton_Choix_backcolor (void)
Callback for the palette color buttons right click.
Selects the background drawing color when clicking on the menubar palette.
References Afficher_curseur(), Afficher_foreback(), Back_color, Couleur_palette(), and Effacer_curseur.
Referenced by Initialisation_des_boutons().
void Bouton_Brosse_monochrome (void)
Callback for the brush button left click.
Selects the monochrome brush mode when right clicking on the brush button.
References Afficher_curseur(), BOUTON_PINCEAUX, Changer_la_forme_du_pinceau(), Desenclencher_bouton(), Effacer_curseur, and FORME_PINCEAU_BROSSE_MONOCHROME.
Referenced by Initialisation_des_boutons().
void Bouton_Menu_pinceaux (void)
Callback for the brush button right click.
Displays the "Paintbrush menu".
References Afficher_curseur(), Afficher_pinceau_dans_fenetre(), BOUTON_AIDE, BOUTON_PINCEAUX, Changer_la_forme_du_pinceau(), Desenclencher_bouton(), Display_Window, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), NB_SPRITES_PINCEAU, Ouvrir_fenetre(), Pinceau_Decalage_X, Pinceau_Decalage_Y, Pinceau_Forme, Pinceau_Hauteur, Pinceau_Largeur, Pinceau_predefini_Decalage_X, Pinceau_predefini_Decalage_Y, Pinceau_predefini_Hauteur, Pinceau_predefini_Largeur, Pinceau_Sprite, Pinceau_Type, SPRITE_PINCEAU, TAILLE_MAXI_PINCEAU, Touche, and TOUCHE_ESC.
Referenced by Initialisation_des_boutons().
void Bouton_Dessin (void)
Callback for the freehand draw button left click.
Selects freehand drawing mode, depending on the current state of the freehand button.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and Mode_de_dessin_en_cours.
Referenced by Initialisation_des_boutons().
void Bouton_Dessin_Switch_mode (void)
Callback for the freehand draw button right click.
Cycles the drawing modes for the freehand tool.
References Afficher_curseur(), Afficher_sprite_dans_menu(), BOUTON_DESSIN, Demarrer_pile_operation(), Effacer_curseur, Mode_de_dessin_en_cours, OPERATION_DESSIN_CONTINU, and OPERATION_FILLED_CONTOUR.
Referenced by Initialisation_des_boutons().
void Bouton_Lignes (void)
Callback for the lines button left click.
Selects lines drawing mode, depending on the current state of the lines button.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and Ligne_en_cours.
Referenced by Initialisation_des_boutons().
void Bouton_Lignes_Switch_mode (void)
Callback for the lines button right click.
Cycles the drawing modes for the lines tool.
References Afficher_curseur(), Afficher_sprite_dans_menu(), BOUTON_LIGNES, Demarrer_pile_operation(), Effacer_curseur, Ligne_en_cours, OPERATION_K_LIGNE, OPERATION_LIGNE, and OPERATION_LIGNES_CENTREES.
Referenced by Initialisation_des_boutons().
void Bouton_Fill (void)
Callback for the fill button left click.
Start the filling operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, FORME_PINCEAU_POINT, Loupe_Mode, Menu_Ordonnee, Menu_visible, Mouse_X, Mouse_Y, Operation_en_cours, OPERATION_FILL, OPERATION_REMPLACER, Pinceau_Forme, Pinceau_Forme_avant_fill, Principal_Split, Principal_X_Zoom, and Print_dans_menu().
Referenced by Initialisation_des_boutons().
void Bouton_Remplacer (void)
Callback for the fill button right click.
Start the color replace operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, FORME_PINCEAU_POINT, Loupe_Mode, Menu_Ordonnee, Menu_visible, Mouse_X, Mouse_Y, Operation_en_cours, OPERATION_FILL, OPERATION_REMPLACER, Pinceau_Forme, Pinceau_Forme_avant_fill, Principal_Split, Principal_X_Zoom, and Print_dans_menu().
Referenced by Initialisation_des_boutons().
void Bouton_desenclencher_Fill (void)
Disable and release the fill button.
Restores the cursor (custom brushes are disabled for the fill operation). Cleans the status bar if the color replacement tool put a preview color inside it.
References Loupe_Mode, Menu_Ordonnee, Menu_visible, Mouse_X, Mouse_Y, Operation_en_cours, OPERATION_REMPLACER, Pinceau_Forme, Pinceau_Forme_avant_fill, Principal_Split, Principal_X_Zoom, and Print_dans_menu().
Referenced by Initialisation_des_boutons().
void Bouton_Spray (void)
Callback for the spray button left click.
Start the spray operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_SPRAY.
Referenced by Initialisation_des_boutons().
void Bouton_Spray_Menu (void)
Callback for the spray button right click.
Opens the spray's setup menu.
References A_GAUCHE, Afficher_curseur(), Attendre_fin_de_click(), BOUTON_AIDE, BOUTON_SPRAY, CM_Blanc, CM_Clair, CM_Fonce, CM_Noir, Display_Window, Effacer_curseur, Enclencher_bouton(), Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_palette(), Fenetre_Definir_bouton_saisie(), Fenetre_Definir_bouton_scroller(), Fenetre_Effacer_tags(), Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Fore_color, Lit_pixel, Menu_Facteur_X, Menu_Facteur_Y, Mouse_K, Mouse_X, Mouse_Y, Num2str(), Operation_en_cours, OPERATION_SPRAY, Ouvrir_fenetre(), Print_dans_fenetre(), Readline(), Recuperer_couleur_derriere_fenetre(), Spray_Delay, Spray_Mode, Spray_Mono_flow, Spray_Multi_flow, Spray_Rafficher_infos(), Spray_Size, Stencil_Actualiser_couleur(), Stencil_Tagger_couleur(), Touche, TOUCHE_ESC, and UpdateRect().
Referenced by Initialisation_des_boutons().
void Bouton_Courbes (void)
Callback for the curves button left click.
Start curve operation according to the selected mode.
References Afficher_curseur(), Courbe_en_cours, Demarrer_pile_operation(), and Effacer_curseur.
Referenced by Initialisation_des_boutons().
void Bouton_Courbes_Switch_mode (void)
Callback for the curves button right click.
Select the curve mode (1-point, 2-point)
References Afficher_curseur(), Afficher_sprite_dans_menu(), BOUTON_COURBES, Courbe_en_cours, Demarrer_pile_operation(), Effacer_curseur, OPERATION_COURBE_3_POINTS, and OPERATION_COURBE_4_POINTS.
Referenced by Initialisation_des_boutons().
void Bouton_Rectangle_vide (void)
Callback for the empty rectangle button.
Start the rectangle operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_RECTANGLE_VIDE.
Referenced by Initialisation_des_boutons().
void Bouton_Rectangle_plein (void)
Callback for the filled rectangle button.
Start the filled rectangle operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_RECTANGLE_PLEIN.
Referenced by Initialisation_des_boutons().
void Bouton_Texte (void)
Callback for the text button.
Opens the text setup window.
References A_DROITE, A_GAUCHE, Affiche_brosse, Afficher_curseur(), S_Config::Auto_discontinuous, Back_color, Block, BOUTON_AIDE, BOUTON_DESSIN, BOUTON_TEXTE, Brosse, Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, Changer_la_forme_du_pinceau(), CM_Clair, CM_Fonce, CM_Noir, Config, Desenclencher_bouton(), Dessiner_selecteur_fontes(), Display_Window, Effacer_curseur, Enclencher_bouton(), Erreur, Est_Raccourci(), Fenetre_Afficher_cadre_creux(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_repetable(), Fenetre_Definir_bouton_saisie(), Fenetre_Definir_bouton_scroller(), Fenetre_Definir_bouton_special(), Fenetre_Dessiner_jauge(), Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Fonte_nombre, FORME_PINCEAU_BROSSE_COULEUR, FORME_PINCEAU_BROSSE_MONOCHROME, T_Bouton_special::Hauteur, T_Bouton_special::Largeur, Menu_Facteur_X, Menu_Facteur_Y, Min(), Mouse_Y, Num2str(), OPERATION_DESSIN_DISCONTINU, Operation_en_cours, Ouvrir_fenetre(), T_Bouton_special::Pos_X, T_Bouton_special::Pos_Y, T_Bouton_scroller::Position, Position_curseur, Print_dans_fenetre(), Readline(), Readline_ex(), Rendu_Texte(), Touche, TOUCHE_ESC, TOUCHE_MOUSEWHEELDOWN, TOUCHE_MOUSEWHEELUP, TrueType_fonte(), and UpdateRect().
Referenced by Initialisation_des_boutons().
void Bouton_Degrades (void)
Callback for the gradation button.
Opens the "Gradation menu".
References Afficher_curseur(), Afficher_pixel(), Attendre_fin_de_click(), BOUTON_AIDE, BOUTON_GRADMENU, CM_Clair, CM_Fonce, CM_Noir, Degrade_Charger_infos_du_tableau(), Degrade_Courant, Degrade_Dessiner_bouton_de_technique(), Degrade_Dessiner_preview(), Degrade_Tableau, Desenclencher_bouton(), Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_Afficher_cadre_creux(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_palette(), Fenetre_Definir_bouton_scroller(), Fenetre_Dessiner_jauge(), Fermer_fenetre(), Lit_pixel, MOD_SHIFT, Mouse_K, Mouse_X, Mouse_Y, Num2str(), Ouvrir_fenetre(), Pixel, T_Bouton_scroller::Position, Print_dans_fenetre(), Recuperer_couleur_derriere_fenetre(), Tagger_intervalle_palette(), Touche, TOUCHE_ESC, and Traiter_pixel_de_degrade.
Referenced by Initialisation_des_boutons().
void Degrade_Charger_infos_du_tableau (int Indice)
Gets the informations from the gradations table and set the global vars for the current gradation.
Parameters:
Indice index of the selected gradation
References Degrade_Borne_Inferieure, Degrade_Borne_Superieure, Degrade_de_base(), Degrade_de_trames_etendues(), Degrade_de_trames_simples(), Degrade_Intervalle_bornes, Degrade_Inverse, Degrade_Melange_aleatoire, Degrade_Tableau, and Traiter_degrade.
Referenced by Bouton_Degrades(), Charger_CFG(), Config_par_defaut(), and Degrade_Dessiner_preview().
void Bouton_Cercle_degrade (void)
Callback for the gradation circle button left click.
Starts drawing a gradation circle.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_CERCLE_DEGRADE.
Referenced by Initialisation_des_boutons().
void Bouton_Ellipse_degrade (void)
Callback for the gradation circle right click.
Starts drawing a gradation ellipsis.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_ELLIPSE_DEGRADEE.
Referenced by Initialisation_des_boutons().
void Bouton_Rectangle_degrade (void)
Callback for the gradation rectangle button.
Starts the gradation rectangle drawing operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_RECTANGLE_DEGRADE.
Referenced by Initialisation_des_boutons().
void Bouton_Cercle_vide (void)
Callback for the circle button left click.
Starts drawing an empty circle
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_CERCLE_VIDE.
Referenced by Initialisation_des_boutons().
void Bouton_Ellipse_vide (void)
Callback for the circle button left click.
Starts drawing an empty ellipsis
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_ELLIPSE_VIDE.
Referenced by Initialisation_des_boutons().
void Bouton_Cercle_plein (void)
Callback for the filled circle button ledt click.
Starts drawing a filled circle.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_CERCLE_PLEIN.
Referenced by Initialisation_des_boutons().
void Bouton_Ellipse_pleine (void)
Callback for the filled circle right click.
Starts drawing a filled ellipsis.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_ELLIPSE_PLEINE.
Referenced by Initialisation_des_boutons().
void Bouton_Polygone (void)
Callback for the polyline button left click.
Starts drawing a polygon.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_POLYGONE.
Referenced by Initialisation_des_boutons().
void Bouton_Polyform (void)
Callback for the polyline right click.
Starts drawing a polyform.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_POLYFORM.
Referenced by Initialisation_des_boutons().
void Bouton_Polyfill (void)
Callback for the polyfill button left click.
Starts drawing a filled polygon.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_POLYFILL.
Referenced by Initialisation_des_boutons().
void Bouton_Filled_polyform (void)
Callback for the polyfill button right click.
Starts drawing a filled polyform.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_FILLED_POLYFORM.
Referenced by Initialisation_des_boutons().
void Bouton_Ajuster (void)
Callback for the adjust picture button.
Start the adjust picture operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_SCROLL.
Referenced by Initialisation_des_boutons().
void Bouton_Shade_Mode (void)
Callback for the shade button (in the FX window).
Toogle the shade mode.
References Aucun_effet(), Colorize_Mode, Effet_Shade(), Fonction_effet, Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, and Tiling_Mode.
Referenced by Bouton_Effets(), Bouton_Shade_Menu(), and Gestion_principale().
void Bouton_Quick_shade_Mode (void)
Callback for the QSHade button (in the FX window).
Toogle the Quick Shade effect.
References Aucun_effet(), Colorize_Mode, Effet_Quick_shade(), Fonction_effet, Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, and Tiling_Mode.
Referenced by Bouton_Effets(), Bouton_Quick_shade_Menu(), and Gestion_principale().
void Bouton_Shade_Menu (void)
Callback for the Shade button (in the FX window) right click.
Displays the shade setup menu.
References Afficher_curseur(), Bouton_Shade_Mode(), Liste2tables(), Menu_Shade(), Shade_Actuel, Shade_Liste, Shade_Mode, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Stencil_Mode (void)
Callback for the Stencil button (in the FX window) left click.
Toogle stencil mode.
References Stencil_Mode.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Menu_Stencil (void)
Callback for the Stencil button (in the FX window) right click.
Displays the stencil setup menu.
References Menu_Tag_couleurs(), Stencil, and Stencil_Mode.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Mask_Mode (void)
Callback for the Mask button (in the FX window) left click.
Toogles the mask mode/
References Mask_Mode.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Mask_Menu (void)
Callback for the Mask button (in the FX window) right click.
Displays the mask setup menu.
References Mask_Mode, Mask_table, and Menu_Tag_couleurs().
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Snap_Mode (void)
Callback for the Grid button (in the FX window) left click.
Toogle the grid.
References Afficher_curseur(), Calculer_coordonnees_pinceau(), Effacer_curseur, and Snap_Mode.
Referenced by Bouton_Effets(), Bouton_Menu_Grille(), and Gestion_principale().
void Bouton_Menu_Grille (void)
Callback for the Grid button (in the FX window) right click.
Displays the grid setup menu.
References Afficher_curseur(), BOUTON_AIDE, BOUTON_EFFETS, Bouton_Snap_Mode(), CM_Clair, CM_Fonce, Display_Window, Est_Raccourci(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fermer_fenetre(), Num2str(), Ouvrir_fenetre(), Print_dans_fenetre(), Readline(), Snap_Decalage_X, Snap_Decalage_Y, Snap_Hauteur, Snap_Largeur, Snap_Mode, Touche, and TOUCHE_ESC.
Referenced by Bouton_Effets(), and Gestion_principale().
void Copier_trame_predefinie (byte Indice)
In the sieve window, copy one of the presets patterns to the current one.
Parameters:
Indice Index of the pattern to copy
References Trame, Trame_Hauteur, Trame_Largeur, and TRAME_PREDEFINIE.
Referenced by Bouton_Trame_Menu(), and Initialisation_du_programme().
void Inverser_trame (void)
In the sieve window, swaps black and white in the current pattern.
References Trame, Trame_Hauteur, and Trame_Largeur.
Referenced by Bouton_Trame_Menu(), and Gestion_principale().
void Bouton_Trame_Mode (void)
Callback for the Sieve button (in the FX window) left click.
Toogle sieve mode.
References Trame_Mode.
Referenced by Bouton_Effets(), Bouton_Trame_Menu(), and Gestion_principale().
void Bouton_Trame_Menu (void)
Callback for the Sieve button (in the FX window) right click.
Displays the sieve setup menu.
References A_GAUCHE, Afficher_curseur(), Back_color, Block, BOUTON_AIDE, BOUTON_EFFETS, Bouton_Trame_Mode(), Brosse, Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, Changer_la_forme_du_pinceau(), CM_Blanc, CM_Clair, CM_Fonce, CM_Noir, Copier_trame_predefinie(), Dessiner_trame_zoomee(), Dessiner_trames_predefinies(), Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_Afficher_cadre_creux(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_repetable(), Fenetre_Definir_bouton_special(), Fenetre_Liste_boutons_special, Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Fore_color, FORME_PINCEAU_BROSSE_COULEUR, Inverser_trame(), Lit_pixel_dans_brosse(), Menu_Facteur_X, Menu_Facteur_Y, Mettre_a_jour_trame(), MOD_SHIFT, Mouse_K, Mouse_X, Mouse_Y, Num2str(), Ouvrir_fenetre(), Pixel_dans_brosse(), T_Bouton_normal::Pos_X, T_Bouton_normal::Pos_Y, Print_dans_fenetre(), Touche, TOUCHE_ESC, Trame, Trame_Hauteur, Trame_Largeur, Trame_Mode, and UpdateRect().
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Smooth_Mode (void)
Callback for the smooth button (in the FX window) left click.
Callback for the Smooth button (in the FX window) right click.
Toogles smooth mode.
Displays the smooth setup menu.
Callback for the smooth button (in the FX window) left click.
Displays the smooth setup menu.
References Aucun_effet(), Colorize_Mode, Effet_Smooth(), Fonction_effet, Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, and Tiling_Mode.
Referenced by Bouton_Effets(), Bouton_Smooth_Menu(), and Gestion_principale().
void Calculer_les_tables_de_Colorize (void)
Computes the tables used by the transparency/colorize mode.
These tables are used to match the drawing color*picture color to the color that is painted on screen.
References Colorize_Opacite, Table_de_multiplication_par_Facteur_A, and Table_de_multiplication_par_Facteur_B.
Referenced by Bouton_Colorize_Menu(), and Initialisation_du_programme().
void Bouton_Colorize_Mode (void)
Callback for the Tranparency button (in the FX window) left click.
Toogles transparent drawing mode.
References Aucun_effet(), Colorize_Mode, Colorize_Mode_en_cours, Effet_Colorize_additif(), Effet_Colorize_interpole(), Effet_Colorize_soustractif(), Fonction_effet, Quick_shade_Mode, Shade_Mode, Smooth_Mode, and Tiling_Mode.
Referenced by Bouton_Colorize_Menu(), Bouton_Effets(), and Gestion_principale().
void Bouton_Colorize_Menu (void)
Callback for the Transparency button (in the FX window) right click.
Displays the tranparency setup menu.
References Afficher_curseur(), BOUTON_AIDE, Bouton_Colorize_Afficher_la_selection(), Bouton_Colorize_Mode(), BOUTON_EFFETS, Calculer_les_tables_de_Colorize(), CM_Clair, CM_Fonce, Colorize_Mode, Colorize_Mode_en_cours, Colorize_Opacite, Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fenetre_Liste_boutons_special, Fermer_fenetre(), Num2str(), Ouvrir_fenetre(), Print_dans_fenetre(), Readline(), Touche, and TOUCHE_ESC.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Tiling_Mode (void)
Callback for the Tiling button (in the FX window) left click.
Toogles tiling mode.
References Aucun_effet(), Colorize_Mode, Effet_Tiling(), Fonction_effet, Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, and Tiling_Mode.
Referenced by Bouton_Effets(), Bouton_Tiling_Menu(), and Gestion_principale().
void Bouton_Tiling_Menu (void)
Callback for the Tiling button (in the FX window) right click.
Displays the tiling setup menu.
References Afficher_curseur(), BOUTON_AIDE, BOUTON_EFFETS, Bouton_Tiling_Mode(), Brosse_Hauteur, Brosse_Largeur, CM_Clair, CM_Fonce, Display_Window, Est_Raccourci(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fermer_fenetre(), Num2str(), Ouvrir_fenetre(), Print_dans_fenetre(), Readline(), Tiling_Decalage_X, Tiling_Decalage_Y, Tiling_Mode, Touche, and TOUCHE_ESC.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Effets (void)
Callback for the effects button click.
Displays the effect selection menu.
!!
References A_GAUCHE, Afficher_curseur(), Afficher_etat_effet(), Afficher_etat_effets(), Afficher_etat_feedback(), Afficher_sprite_effet(), Aucun_effet(), BOUTON_AIDE, Bouton_Colorize_Menu(), Bouton_Colorize_Mode(), BOUTON_EFFETS, Bouton_Mask_Menu(), Bouton_Mask_Mode(), Bouton_Menu_Grille(), Bouton_Menu_Stencil(), Bouton_Quick_shade_Menu(), Bouton_Quick_shade_Mode(), Bouton_Shade_Menu(), Bouton_Shade_Mode(), Bouton_Smear_Mode(), Bouton_Smooth_Menu(), Bouton_Smooth_Mode(), Bouton_Snap_Mode(), Bouton_Stencil_Mode(), Bouton_Tiling_Menu(), Bouton_Tiling_Mode(), Bouton_Trame_Menu(), Bouton_Trame_Mode(), CM_Clair, CM_Fonce, Colorize_Mode, Config, Config_Touche, Desenclencher_bouton(), Display_Window, Ecran_backup, Effacer_curseur, Est_Raccourci(), Fenetre_aide(), Fenetre_Attribut1, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fenetre_Numero_bouton_clicke(), Fermer_fenetre(), Fonction_effet, S_Config::FX_Feedback, FX_Feedback_Ecran, Mask_Mode, Ouvrir_fenetre(), Principal_Ecran, Print_dans_fenetre(), Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, Snap_Mode, SPECIAL_COLORIZE_MODE, SPECIAL_GRID_MODE, SPECIAL_MASK_MODE, SPECIAL_QUICK_SHADE_MODE, SPECIAL_SHADE_MODE, SPECIAL_SIEVE_MODE, SPECIAL_SMEAR_MODE, SPECIAL_SMOOTH_MODE, SPECIAL_STENCIL_MODE, SPECIAL_TILING_MODE, Stencil_Mode, Tiling_Mode, Touche, TOUCHE_ESC, and Trame_Mode.
Referenced by Initialisation_des_boutons().
void Bouton_Brosse (void)
Callback for the brush button left click.
Start the brush picking operation.
References Afficher_curseur(), BOUTON_BROSSE, Demarrer_pile_operation(), Desenclencher_bouton(), Effacer_curseur, Operation_en_cours, and OPERATION_PRISE_BROSSE.
Referenced by Initialisation_des_boutons().
void Bouton_Restaurer_brosse (void)
Callback for the brush button right click.
Activates the last captured custom brush.
References Afficher_curseur(), BOUTON_BROSSE, BOUTON_POLYBROSSE, Changer_la_forme_du_pinceau(), Desenclencher_bouton(), Effacer_curseur, and FORME_PINCEAU_BROSSE_COULEUR.
Referenced by Initialisation_des_boutons().
void Bouton_desenclencher_Brosse (void)
Disables the custom brush and set back a regular one.
References Demarrer_pile_operation(), and Operation_avant_interruption.
Referenced by Initialisation_des_boutons().
void Bouton_Lasso (void)
Callback for the freehand brush pick button left click.
Starts freehand brush picking operation.
References Afficher_curseur(), BOUTON_POLYBROSSE, Demarrer_pile_operation(), Desenclencher_bouton(), Effacer_curseur, FORME_PINCEAU_POINT, Operation_en_cours, OPERATION_POLYBROSSE, Pinceau_Forme, and Pinceau_Forme_avant_lasso.
Referenced by Initialisation_des_boutons().
void Bouton_desenclencher_Lasso (void)
Disables the custom freehand brush and set back a regular one.
References Demarrer_pile_operation(), Operation_avant_interruption, Pinceau_Forme, and Pinceau_Forme_avant_lasso.
Referenced by Initialisation_des_boutons().
void Bouton_Pipette (void)
Starts the color picking operation.
References Afficher_curseur(), BOUTON_PIPETTE, Demarrer_pile_operation(), Desenclencher_bouton(), Effacer_curseur, FORME_PINCEAU_POINT, Loupe_Mode, Menu_Ordonnee, Menu_visible, Mouse_X, Mouse_Y, Operation_avant_interruption, Operation_en_cours, OPERATION_PIPETTE, OPERATION_REMPLACER, Pinceau_Forme, Pinceau_Forme_avant_pipette, Pipette_Couleur, Principal_Split, Principal_X_Zoom, and Print_dans_menu().
Referenced by Initialisation_des_boutons().
void Bouton_desenclencher_Pipette (void)
Disables the color picker button and get back to the previously selected drawing mode.
References Demarrer_pile_operation(), Loupe_Mode, Menu_Ordonnee, Menu_visible, Mouse_X, Mouse_Y, Operation_avant_interruption, Operation_en_cours, OPERATION_PIPETTE, OPERATION_REMPLACER, Pinceau_Forme, Pinceau_Forme_avant_pipette, Principal_Split, Principal_X_Zoom, and Print_dans_menu().
Referenced by Initialisation_des_boutons().
void Bouton_Inverser_foreback (void)
Swap fore- and background colors.
References Afficher_curseur(), Afficher_foreback(), Back_color, BOUTON_PIPETTE, CM_Blanc, CM_Noir, Desenclencher_bouton(), Effacer_curseur, Encadrer_couleur_menu(), Fore_color, and Recadrer_palette().
Referenced by Initialisation_des_boutons().
void Bouton_Loupe (void)
Enters magnify mode.
References Afficher_curseur(), Afficher_ecran(), Ancien_Principal_Decalage_X, Ancien_Principal_Decalage_Y, BOUTON_LOUPE, Calculer_coordonnees_pinceau(), Calculer_donnees_loupe(), Calculer_limites(), Config, Demarrer_pile_operation(), Desenclencher_bouton(), Effacer_curseur, S_Config::Fast_zoom, Limite_Bas, Limite_Droite, Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Hauteur, Loupe_Largeur, Loupe_Mode, Menu_Ordonnee, Mouse_X, Mouse_Y, Operation_en_cours, OPERATION_LOUPE, Pixel_Preview, Pixel_Preview_Loupe, Principal_Decalage_X, Principal_Decalage_Y, Recadrer_ecran_par_rapport_au_zoom(), and UpdateRect().
Referenced by Initialisation_des_boutons().
void Bouton_Menu_Loupe (void)
Displays magnify menu.
References A_GAUCHE, Afficher_curseur(), Afficher_ecran(), BOUTON_AIDE, BOUTON_LOUPE, Changer_facteur_loupe(), Desenclencher_bouton(), Display_Window, Enclencher_bouton(), Est_Raccourci(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), Largeur_ecran, Loupe_Facteur, Loupe_Mode, Menu_Ordonnee, Menu_Ordonnee_avant_fenetre, Operation_en_cours, OPERATION_LOUPE, Ouvrir_fenetre(), Principal_Split, Touche, TOUCHE_ESC, and UpdateRect().
Referenced by Initialisation_des_boutons().
void Bouton_desenclencher_Loupe (void)
Exit magnify mode.
References Afficher_ecran(), Ancien_Principal_Decalage_X, Ancien_Principal_Decalage_Y, Calculer_coordonnees_pinceau(), Calculer_limites(), Demarrer_pile_operation(), Largeur_ecran, Loupe_Mode, Menu_Ordonnee, Old_MX, Old_MY, Operation_avant_interruption, Pixel_Preview, Pixel_Preview_Normal, Principal_Decalage_X, Principal_Decalage_Y, Principal_Hauteur_image, and Principal_Largeur_image.
Referenced by Initialisation_des_boutons().
void Bouton_Brush_FX (void)
Display the Brush effects window.
References Afficher_curseur(), Block, BOUTON_AIDE, BOUTON_EFFETS_BROSSE, Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, CM_Clair, CM_Fonce, CM_Noir, Config_Touche, Demarrer_pile_operation(), Desenclencher_bouton(), Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Flip_X_LOWLEVEL(), Flip_Y_LOWLEVEL(), Get_colors_from_brush(), Load_picture(), Menu_Facteur_X, Menu_Facteur_Y, Message_Non_disponible(), Nibble_brush(), OPERATION_ETIRER_BROSSE, OPERATION_TOURNER_BROSSE, Outline_brush(), Ouvrir_fenetre(), Pixel_dans_fenetre(), Print_dans_fenetre(), Remap_brosse(), Rotate_180_deg_LOWLEVEL(), Rotate_90_deg(), Save_picture(), SPECIAL_BOTTOM_LEFT_ATTACHMENT, SPECIAL_BOTTOM_RIGHT_ATTACHMENT, SPECIAL_CENTER_ATTACHMENT, SPECIAL_DISTORT, SPECIAL_FLIP_X, SPECIAL_FLIP_Y, SPECIAL_GET_BRUSH_COLORS, SPECIAL_LOAD_BRUSH, SPECIAL_NIBBLE, SPECIAL_OUTLINE, SPECIAL_RECOLORIZE_BRUSH, SPECIAL_ROTATE_180, SPECIAL_ROTATE_90, SPECIAL_ROTATE_ANY_ANGLE, SPECIAL_SAVE_BRUSH, SPECIAL_STRETCH, SPECIAL_TOP_LEFT_ATTACHMENT, SPECIAL_TOP_RIGHT_ATTACHMENT, Touche, and TOUCHE_ESC.
Referenced by Initialisation_des_boutons().
void Bouton_Page (void)
Swap main and spare drawing pages.
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), Ancien_Brouillon_Decalage_X, Ancien_Brouillon_Decalage_Y, Ancien_Principal_Decalage_X, Ancien_Principal_Decalage_Y, BOUTON_LOUPE, BOUTON_PAGE, Brouillon_Decalage_X, Brouillon_Decalage_Y, Brouillon_File_list_Decalage, Brouillon_File_list_Position, Brouillon_Format, Brouillon_Image_modifiee, Brouillon_Loupe_Decalage_X, Brouillon_Loupe_Decalage_Y, Brouillon_Loupe_Facteur, Brouillon_Loupe_Hauteur, Brouillon_Loupe_Largeur, Brouillon_Loupe_Mode, Brouillon_Proportion_split, Brouillon_Repertoire_courant, Brouillon_Split, Brouillon_X_Zoom, Calculer_couleurs_menu_optimales(), Changer_facteur_loupe(), Desenclencher_bouton(), Effacer_curseur, FACTEUR_ZOOM, Interchanger_image_principale_et_brouillon(), Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Facteur, Loupe_Hauteur, Loupe_Largeur, Loupe_Mode, Pixel_Preview, Pixel_Preview_Loupe, Pixel_Preview_Normal, Principal_Decalage_X, Principal_Decalage_Y, Principal_File_list_Decalage, Principal_File_list_Position, Principal_Format, Principal_Image_modifiee, Principal_Palette, Principal_Proportion_split, Principal_Repertoire_courant, Principal_Split, Principal_X_Zoom, Set_palette(), and Tracer_cadre_de_bouton_du_menu().
Referenced by Bouton_Quit(), Initialisation_des_boutons(), and main().
void Bouton_Copy_page (void)
Copy main page to spare page.
References Afficher_curseur(), BOUTON_AIDE, BOUTON_PAGE, Brouillon_Image_modifiee, Brouillon_Palette, Copier_certaines_couleurs(), Copier_image_seule(), Demande_de_confirmation(), Desenclencher_bouton(), Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), Ouvrir_fenetre(), Principal_Palette, Remap_picture(), Touche, and TOUCHE_ESC.
Referenced by Initialisation_des_boutons().
void Copier_image_seule (void)
Copy only pixel data from main page to spare page (no palette copy).
References Backuper_et_redimensionner_brouillon(), Brouillon_Decalage_X, Brouillon_Decalage_Y, Brouillon_Ecran, Brouillon_Hauteur_image, Brouillon_Largeur_image, Brouillon_Loupe_Decalage_X, Brouillon_Loupe_Decalage_Y, Brouillon_Loupe_Facteur, Brouillon_Loupe_Hauteur, Brouillon_Loupe_Largeur, Brouillon_Loupe_Mode, Brouillon_Proportion_split, Brouillon_Split, Brouillon_X_Zoom, Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Facteur, Loupe_Hauteur, Loupe_Largeur, Loupe_Mode, Message_Memoire_insuffisante(), Principal_Decalage_X, Principal_Decalage_Y, Principal_Ecran, Principal_Hauteur_image, Principal_Largeur_image, Principal_Proportion_split, Principal_Split, and Principal_X_Zoom.
Referenced by Bouton_Copy_page().
void Bouton_Kill (void)
Kill (free from memory) the current page.
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), BOUTON_KILL, BOUTON_LOUPE, Calculer_couleurs_menu_optimales(), Demande_de_confirmation(), Desenclencher_bouton(), Detruire_la_page_courante(), Effacer_curseur, Loupe_Mode, S_Liste_de_pages::Nb_pages_allouees, Principal_Backups, Principal_Palette, Set_palette(), Tracer_cadre_de_bouton_du_menu(), and Warning_message().
Referenced by Initialisation_des_boutons().
void Bouton_Resol (void)
Display the screenmode menu.
References A_GAUCHE, Afficher_curseur(), Afficher_ecran(), Afficher_liste_modes(), Afficher_menu(), Attendre_fin_de_click(), Block, BOUTON_AIDE, BOUTON_LOUPE, BOUTON_RESOL, CM_Clair, CM_Fonce, CM_Noir, Cocher_bouton_mode(), Desenclencher_bouton(), Display_Window, Effacer_curseur, Erreur, Est_Raccourci(), S_Mode_video::Etat, Fenetre_Afficher_cadre(), Fenetre_Afficher_cadre_creux(), Fenetre_aide(), Fenetre_Attribut1, Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fenetre_Definir_bouton_scroller(), Fenetre_Definir_bouton_special(), Fenetre_Dessiner_bouton_normal(), Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Hauteur, S_Mode_video::Hauteur, Initialiser_mode_video(), Largeur, S_Mode_video::Largeur, Loupe_Mode, Menu_Facteur_X, Menu_Facteur_Y, Mode_video, Mouse_K, Mouse_X, Mouse_Y, Nb_modes_video, Num2str(), Ouvrir_fenetre(), Pinceau_X, Pinceau_Y, Pixel_height, Pixel_width, Position_curseur, Principal_Hauteur_image, Principal_Largeur_image, Print_dans_fenetre(), Readline(), Redimentionner_image(), Resolution_actuelle, Scroller_la_liste_des_modes(), Touche, and TOUCHE_ESC.
Referenced by Initialisation_des_boutons().
void Bouton_Safety_resol (void)
Set the screen to the "safe resolution" (320x200 pixel window).
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), BOUTON_LOUPE, BOUTON_RESOL, Desenclencher_bouton(), Effacer_curseur, S_Mode_video::Hauteur, Hauteur_ecran, Initialiser_mode_video(), S_Mode_video::Largeur, Largeur_ecran, Mode_video, Pixel_height, Pixel_width, and Resolution_actuelle.
Referenced by Initialisation_des_boutons().
void Bouton_Load (void)
Opens the load file dialog.
References Load_picture(), S_Liste_de_pages::Pages, Principal_Backups, and Upload_infos_page_principal().
Referenced by Initialisation_des_boutons().
void Bouton_Reload (void)
Reload current picture from disk.
References Afficher_curseur(), Afficher_ecran(), Afficher_limites_de_l_image(), S_Config::Afficher_limites_image, Afficher_menu(), S_Config::Auto_set_res, BOUTON_CHARGER, BOUTON_LOUPE, Calculer_coordonnees_pinceau(), Calculer_couleurs_menu_optimales(), Calculer_limites(), Charger_image(), Config, Demande_de_confirmation(), Desenclencher_bouton(), Ecran_original_X, Ecran_original_Y, Effacer_curseur, Erreur_fichier, Forme_curseur, FORME_CURSEUR_SABLIER, Hauteur, Initialiser_mode_video(), Largeur, Loupe_Mode, Meilleur_mode_video(), Mode_video, S_Liste_de_pages::Pages, Pixel_Preview, Pixel_Preview_Normal, Principal_Backups, Principal_Decalage_X, Principal_Decalage_Y, Principal_Image_modifiee, Principal_Palette, Resolution_actuelle, Tracer_cadre_de_bouton_du_menu(), Une_resolution_a_ete_passee_en_parametre, and Upload_infos_page_principal().
Referenced by Initialisation_des_boutons(), and main().
void Bouton_Save (void)
Open the save file dialog.
References Save_picture().
Referenced by Initialisation_des_boutons().
void Bouton_Autosave (void)
Saves the current file without asking for a new name.
References Afficher_curseur(), S_Config::Backup, Backup_du_fichier_sauvegarde(), BOUTON_SAUVER, Config, Demande_de_confirmation(), Desenclencher_bouton(), Effacer_curseur, Erreur, Erreur_fichier, Fichier_existe(), Forme_curseur, FORME_CURSEUR_SABLIER, Nom_fichier_complet(), Sauver_image(), and TAILLE_CHEMIN_FICHIER.
Referenced by Initialisation_des_boutons().
void Bouton_Settings (void)
Display the setting menu.
References S_Config::Adjust_brush_pick, Afficher_curseur(), S_Config::Afficher_limites_image, Afficher_menu(), Attendre_fin_de_click(), S_Config::Auto_save, S_Config::Auto_set_res, S_Config::Backup, BOUTON_AIDE, BOUTON_PARAMETRES, Brouillon_File_list_Decalage, Brouillon_File_list_Position, Calculer_couleurs_menu_optimales(), S_Config::Clear_palette, CM_Clair, CM_Fonce, Config, S_Config::Coords_rel, S_Config::Couleurs_separees, S_Config::Curseur, Desenclencher_bouton(), Display_Window, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fenetre_Definir_bouton_scroller(), Fenetre_Liste_boutons_special, Fermer_fenetre(), Fonte, S_Config::Fonte, Fonte_fun, Fonte_systeme, S_Config::Indice_Sensibilite_souris_X, S_Config::Indice_Sensibilite_souris_Y, S_Config::Lire_les_fichiers_caches, S_Config::Lire_les_repertoires_caches, S_Config::Maximize_preview, Menu_Facteur_X, Menu_Facteur_Y, Mouse_Facteur_de_correction_X, Mouse_Facteur_de_correction_Y, S_Config::Nb_pages_Undo, NB_PAGES_UNDO_MAX, Nouveau_nombre_de_backups(), Num2str(), Ouvrir_fenetre(), Principal_File_list_Decalage, Principal_File_list_Position, Principal_Palette, Print_dans_fenetre(), Readline(), S_Config::Safety_colors, Sensibilite_souris(), Settings_Afficher_config(), Settings_Charger_config(), Settings_Sauver_config(), Touche, and TOUCHE_ESC.
Referenced by Initialisation_des_boutons().
void Bouton_Undo (void)
Undo the last modification to the picture.
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), BOUTON_LOUPE, BOUTON_UNDO, Calculer_couleurs_menu_optimales(), Desenclencher_bouton(), Effacer_curseur, Loupe_Mode, Principal_Palette, Set_palette(), Tracer_cadre_de_bouton_du_menu(), and Undo().
Referenced by Initialisation_des_boutons().
void Bouton_Redo (void)
Redo an operation that has been undone.
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), BOUTON_LOUPE, BOUTON_UNDO, Calculer_couleurs_menu_optimales(), Desenclencher_bouton(), Effacer_curseur, Loupe_Mode, Principal_Palette, Redo(), Set_palette(), and Tracer_cadre_de_bouton_du_menu().
Referenced by Initialisation_des_boutons().
void Bouton_Clear (void)
Clear the whole screen with black (color index 0).
References Afficher_curseur(), Afficher_ecran(), Backup(), BOUTON_CLEAR, S_Config::Clear_with_stencil, Config, Desenclencher_bouton(), Effacer_curseur, Effacer_image_courante(), Effacer_image_courante_Stencil(), Stencil, and Stencil_Mode.
Referenced by Initialisation_des_boutons().
void Bouton_Clear_colore (void)
Clear the screen with the selected backcolor.
References Afficher_curseur(), Afficher_ecran(), Back_color, Backup(), BOUTON_CLEAR, S_Config::Clear_with_stencil, Config, Desenclencher_bouton(), Effacer_curseur, Effacer_image_courante(), Effacer_image_courante_Stencil(), Stencil, and Stencil_Mode.
Referenced by Initialisation_des_boutons().
void Bouton_Quit (void)
Quits the program.
Display a requester to save the changes to the picture before exiting if the pic was modified since last save.
References Afficher_curseur(), Bouton_Page(), BOUTON_QUIT, Bouton_Quitter_Routine_locale(), Brouillon_Image_modifiee, Desenclencher_bouton(), Effacer_curseur, Menu_Ordonnee, Menu_visible, Mouse_Y, and Sortir_du_programme.
Referenced by Gestion_principale(), and Initialisation_des_boutons().
void Bouton_Cacher_menu (void)
Hides the menubar.
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), BOUTON_CACHER, Brouillon_Decalage_Y, Brouillon_Hauteur_image, Calculer_coordonnees_pinceau(), Calculer_donnees_loupe(), Calculer_limites(), Desenclencher_bouton(), Effacer_curseur, Hauteur_ecran, HAUTEUR_MENU, Loupe_Decalage_Y, Loupe_Hauteur, Loupe_Mode, Menu_Facteur_Y, Menu_Ordonnee, Menu_visible, Pixel_dans_barre_d_outil(), Pixel_dans_barre_d_outil_cachee(), Pixel_dans_menu, Principal_Decalage_Y, Principal_Hauteur_image, and Recadrer_ecran_par_rapport_au_zoom().
Referenced by Initialisation_des_boutons().
void Load_picture (byte Image)
Load picture from file.
References A_DROITE, A_GAUCHE, Afficher_curseur(), Afficher_ecran(), Afficher_menu(), S_Config::Auto_discontinuous, S_Config::Auto_set_res, BOUTON_DESSIN, Bouton_Load_ou_Save(), BOUTON_LOUPE, Brosse, Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, Calculer_coordonnees_pinceau(), Calculer_couleurs_menu_optimales(), Calculer_limites(), Changer_la_forme_du_pinceau(), Charger_image(), Config, Demande_de_confirmation(), Ecran_original_X, Ecran_original_Y, Effacer_curseur, Enclencher_bouton(), Erreur_fichier, Fore_color, FormatFichier, Forme_curseur, FORME_CURSEUR_SABLIER, FORME_PINCEAU_BROSSE_COULEUR, Hauteur, Initialiser_mode_video(), Largeur, Loupe_Mode, Meilleur_mode_video(), Mode_video, OPERATION_DESSIN_DISCONTINU, Operation_en_cours, Pixel_Chargement_dans_brosse(), Pixel_Chargement_dans_ecran_courant(), Pixel_de_chargement, Pixel_Preview, Pixel_Preview_Normal, Principal_Commentaire, Principal_Decalage_X, Principal_Decalage_Y, Principal_Format_fichier, Principal_Hauteur_image, Principal_Image_modifiee, Principal_Largeur_image, Principal_Nom_fichier, Principal_Palette, Principal_Repertoire_fichier, Print_nom_fichier(), Resolution_actuelle, Set_palette(), Smear_Brosse, Smear_Brosse_Hauteur, Smear_Brosse_Largeur, Swapper_infos_selecteurs_image_et_brosse(), TAILLE_CHEMIN_FICHIER, TAILLE_MAXI_PINCEAU, Tiling_Decalage_X, Tiling_Decalage_Y, and Tracer_cadre_de_bouton_du_menu().
Referenced by Bouton_Brush_FX(), Bouton_Load(), and Gestion_principale().
void Save_picture (byte Image)
Save picture to file.
References Afficher_curseur(), S_Config::Backup, Backup_du_fichier_sauvegarde(), Bouton_Load_ou_Save(), Brosse_Hauteur, Brosse_Largeur, Config, Demande_de_confirmation(), Effacer_curseur, Erreur, Erreur_fichier, Fichier_existe(), FormatFichier, Forme_curseur, FORME_CURSEUR_SABLIER, Principal_Format_fichier, Principal_Hauteur_image, Principal_Largeur_image, Principal_Nom_fichier, Principal_Palette, Principal_Repertoire_fichier, Print_nom_fichier(), Sauver_image(), Set_palette(), Swapper_infos_selecteurs_image_et_brosse(), and TAILLE_CHEMIN_FICHIER.
Referenced by Bouton_Brush_FX(), Bouton_Save(), and Gestion_principale().
void Menu_Tag_couleurs (char * En_tete, byte * Table, byte * Mode, byte Cancel, const char * Section_aide)
Generic color tagging menu, for various effects.
References A_GAUCHE, Afficher_curseur(), Attendre_fin_de_click(), BOUTON_AIDE, BOUTON_EFFETS, CM_Clair, CM_Noir, Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_palette(), Fenetre_Hauteur, Fenetre_Largeur, Fermer_fenetre(), Lit_pixel, Mouse_K, Mouse_X, Mouse_Y, Ouvrir_fenetre(), Recuperer_couleur_derriere_fenetre(), Stencil_Actualiser_couleur(), Stencil_Tagger_couleur(), Touche, and TOUCHE_ESC.
Referenced by Bouton_Mask_Menu(), Bouton_Menu_Stencil(), Bouton_Palette_secondaire(), Copier_certaines_couleurs(), and Gestion_principale().
void Bouton_Smooth_Menu (void)
Display the menu for the smooth effect.
References Afficher_curseur(), BOUTON_AIDE, BOUTON_EFFETS, Bouton_Smooth_Mode(), CM_Clair, CM_Noir, Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fermer_fenetre(), Num2str(), Ouvrir_fenetre(), Print_char_dans_fenetre(), Readline(), Smooth_Matrice, Smooth_Mode, Touche, and TOUCHE_ESC.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Smear_Mode (void)
Toogles the smear mode.
References Aucun_effet(), Colorize_Mode, Fonction_effet, Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, and Tiling_Mode.
Referenced by Bouton_Effets(), and Gestion_principale().