GrafX2: boutons.c File Reference
boutons.c File Reference
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <ctype.h>
#include <SDL.h>
#include "const.h"
#include "struct.h"
#include "global.h"
#include "divers.h"
#include "graph.h"
#include "moteur.h"
#include "readline.h"
#include "files.h"
#include "loadsave.h"
#include "init.h"
#include "boutons.h"
#include "operatio.h"
#include "pages.h"
#include "erreurs.h"
#include "readini.h"
#include "saveini.h"
#include "shade.h"
#include "io.h"
#include "aide.h"
#include "texte.h"
#include "sdlscreen.h"
#include "windows.h"
#include "brush.h"
#include "input.h"
Defines
#define FILENAMESPACE 13
#define Display_Window(X, Y) UpdateRect(Fenetre_Pos_X,Fenetre_Pos_Y,X*Menu_Facteur_X,Y*Menu_Facteur_Y);
#define YES "YES"
#define NO " NO"
#define TOLERANCE_X 8
#define TOLERANCE_Y 4
Functions
void Stencil_Actualiser_couleur (byte Couleur)
void Stencil_Tagger_couleur (byte Couleur, byte Couleur_de_taggage)
void Message_Non_disponible (void)
Displays an error message when calling an unavailable function.
void Message_Memoire_insuffisante (void)
Displays an error message when there is no more memory for the requested operation.
void Bouton_Message_initial (void)
Displays the splash screen at program startup.
void Changer_la_forme_du_pinceau (byte Forme)
Changes brush shape.
void Bouton_Undo (void)
void Bouton_Redo (void)
void Bouton_Pal_left (void)
Callback for the palette scroller buttons left click.
void Bouton_Pal_left_fast (void)
Callback for the palette scroller buttons right click.
void Bouton_Pal_right (void)
Callback for the palette scroller buttons left click.
void Bouton_Pal_right_fast (void)
Callback for the palette scroller buttons right click.
void Bouton_Choix_forecolor (void)
Callback for the palette color buttons left click.
void Bouton_Choix_backcolor (void)
Callback for the palette color buttons right click.
void Pixel_dans_barre_d_outil_cachee (__attribute__((unused)) word X, __attribute__((unused)) word Y, __attribute__((unused)) byte Couleur)
void Bouton_Cacher_menu (void)
byte Bouton_Quitter_Routine_locale (void)
void Bouton_Quit (void)
void Bouton_Clear (void)
void Bouton_Clear_colore (void)
void Menu_Tag_couleurs (char *En_tete, byte *Table, byte *Mode, byte Cancel, const char *Section_aide)
void Bouton_Stencil_Mode (void)
void Bouton_Menu_Stencil (void)
void Bouton_Mask_Mode (void)
void Bouton_Mask_Menu (void)
void Settings_Afficher_config (struct S_Config *Conf)
void Settings_Sauver_config (struct S_Config *Conf)
void Settings_Charger_config (struct S_Config *Conf)
void Bouton_Settings (void)
void Bouton_Page (void)
void Copier_image_seule (void)
void Copier_certaines_couleurs (void)
void Bouton_Copy_page (void)
void Bouton_Kill (void)
void Cocher_bouton_mode (short Pos_X, short Pos_Y, byte Etat)
void Afficher_liste_modes (short Debut_liste, short Position_curseur)
void Scroller_la_liste_des_modes (short Debut_liste, short Position_curseur, int *Mode_choisi)
void Bouton_Resol (void)
void Bouton_Safety_resol (void)
void Bouton_Dessin (void)
Callback for the freehand draw button left click.
void Bouton_Dessin_Switch_mode (void)
Callback for the freehand draw button right click.
void Bouton_Rectangle_vide (void)
Callback for the empty rectangle button.
void Bouton_Rectangle_plein (void)
Callback for the filled rectangle button.
void Bouton_Cercle_vide (void)
Callback for the circle button left click.
void Bouton_Ellipse_vide (void)
Callback for the circle button left click.
void Bouton_Cercle_plein (void)
Callback for the filled circle button ledt click.
void Bouton_Ellipse_pleine (void)
Callback for the filled circle right click.
void Degrade_Dessiner_bouton_de_technique (short Pos_X, short Pos_Y, int Technique)
void Degrade_Charger_infos_du_tableau (int Indice)
Gets the informations from the gradations table and set the global vars for the current gradation.
void Degrade_Dessiner_preview (short Debut_X, short Debut_Y, short Largeur, short Hauteur, int Indice)
void Bouton_Degrades (void)
Callback for the gradation button.
void Bouton_Cercle_degrade (void)
Callback for the gradation circle button left click.
void Bouton_Ellipse_degrade (void)
Callback for the gradation circle right click.
void Bouton_Rectangle_degrade (void)
Callback for the gradation rectangle button.
void Bouton_Fill (void)
Callback for the fill button left click.
void Bouton_Remplacer (void)
Callback for the fill button right click.
void Bouton_desenclencher_Fill (void)
Disable and release the fill button.
void Bouton_Menu_pinceaux (void)
Callback for the brush button right click.
void Bouton_Brosse_monochrome (void)
Callback for the brush button left click.
void Print_repertoire_courant (void)
void Print_Nom_fichier_dans_selecteur (void)
void Preparer_et_afficher_liste_fichiers (short Position, short Decalage, struct Fenetre_Bouton_scroller *Enreg)
void Relire_liste_fichiers (byte Filtre, short Position, short Decalage, struct Fenetre_Bouton_scroller *Enreg)
void On_vient_de_scroller_dans_le_fileselect (struct Fenetre_Bouton_scroller *Scroller_de_fichiers)
short Position_fichier_dans_liste (char *Nom)
void Placer_barre_de_selection_sur (char *Nom)
char * Nom_correspondant_le_mieux_a (char *Nom)
byte Bouton_Load_ou_Save (byte Load, byte Image)
int Meilleur_mode_video (void)
void Swapper_infos_selecteurs_image_et_brosse (void)
void Load_picture (byte Image)
void Bouton_Load (void)
void Bouton_Reload (void)
void Nom_fichier_backup (char *Nom, char *Nom_backup)
void Backup_du_fichier_sauvegarde (void)
void Save_picture (byte Image)
void Bouton_Save (void)
void Bouton_Autosave (void)
void Bouton_Lignes (void)
Callback for the lines button left click.
void Bouton_Lignes_Switch_mode (void)
Callback for the lines button right click.
void Bouton_Brosse (void)
void Bouton_desenclencher_Brosse (void)
void Bouton_Restaurer_brosse (void)
void Bouton_Lasso (void)
void Bouton_desenclencher_Lasso (void)
void Bouton_Pipette (void)
void Bouton_desenclencher_Pipette (void)
void Bouton_Inverser_foreback (void)
void Bouton_Loupe (void)
void Bouton_Menu_Loupe (void)
void Bouton_desenclencher_Loupe (void)
void Bouton_Snap_Mode (void)
void Bouton_Menu_Grille (void)
void Bouton_Brush_FX (void)
void Bouton_Smooth_Mode (void)
void Bouton_Smooth_Menu (void)
void Bouton_Smear_Mode (void)
void Calculer_les_tables_de_Colorize (void)
void Bouton_Colorize_Mode (void)
void Bouton_Colorize_Afficher_la_selection (int Numero)
void Bouton_Colorize_Menu (void)
void Bouton_Tiling_Mode (void)
void Bouton_Tiling_Menu (void)
void Bouton_Courbes (void)
Callback for the curves button left click.
void Bouton_Courbes_Switch_mode (void)
Callback for the curves button right click.
void Bouton_Spray (void)
Callback for the spray button left click.
void Spray_Rafficher_infos (byte Couleur_selectionnee, byte Rafficher_jauge)
void Bouton_Spray_Menu (void)
Callback for the spray button right click.
void Bouton_Trame_Mode (void)
void Dessiner_trame_zoomee (short Orig_X, short Orig_Y)
void Dessiner_trames_predefinies (void)
void Copier_trame_predefinie (byte Indice)
void Inverser_trame (void)
void Mettre_a_jour_trame (short X, short Y)
void Bouton_Trame_Menu (void)
void Bouton_Polygone (void)
Callback for the polyline button left click.
void Bouton_Polyform (void)
Callback for the polyline right click.
void Bouton_Polyfill (void)
Callback for the polyfill button left click.
void Bouton_Filled_polyform (void)
Callback for the polyfill button right click.
void Bouton_Ajuster (void)
Callback for the adjust picture button.
void Afficher_sprite_effet (short Numero_sprite, short Debut_X, short Debut_Y)
void Afficher_etat_effet (short X, short Y, char *Libelle, byte Etat)
void Afficher_etat_effets (void)
void Afficher_etat_feedback (void)
void Bouton_Effets (void)
void Dessiner_selecteur_fontes (short X, short Y, short Debut_liste, short Position_curseur, short Nombre_visibles)
void Bouton_Texte ()
Callback for the text button.
Variables
short Old_MX
short Old_MY
int Type_selectionne
char FFF_Meilleur_nom [TAILLE_CHEMIN_FICHIER]
byte On_vient_du_menu_de_facteurs_de_zoom = 0
byte Smooth_Matrice_defaut [4][3][3]
Define Documentation
#define FILENAMESPACE 13
Referenced by Afficher_la_liste_des_fichiers(), Bouton_Load_ou_Save(), Calculer_decalage_click_dans_fileselector(), Dessiner_preview_palette(), Initialiser_preview(), and Preparer_et_afficher_liste_fichiers().
#define Display_Window (X, Y) UpdateRect(Fenetre_Pos_X,Fenetre_Pos_Y,X*Menu_Facteur_X,Y*Menu_Facteur_Y);
Referenced by Bouton_Brush_FX(), Bouton_Colorize_Menu(), Bouton_Copy_page(), Bouton_Degrades(), Bouton_Effets(), Bouton_Load_ou_Save(), Bouton_Menu_Grille(), Bouton_Menu_Loupe(), Bouton_Menu_pinceaux(), Bouton_Message_initial(), Bouton_Quitter_Routine_locale(), Bouton_Resol(), Bouton_Settings(), Bouton_Smooth_Menu(), Bouton_Spray_Menu(), Bouton_Texte(), Bouton_Tiling_Menu(), Bouton_Trame_Menu(), Menu_Tag_couleurs(), Message_Memoire_insuffisante(), and Message_Non_disponible().
#define YES "YES"
Referenced by main(), and Settings_Afficher_config().
#define NO " NO"
Referenced by main(), and Settings_Afficher_config().
#define TOLERANCE_X 8
Referenced by Meilleur_mode_video().
#define TOLERANCE_Y 4
Referenced by Meilleur_mode_video().
Function Documentation
void Stencil_Actualiser_couleur (byte Couleur)
References Fenetre_Liste_boutons_palette, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, and UpdateRect().
Referenced by Bouton_Spray_Menu(), and Menu_Tag_couleurs().
void Stencil_Tagger_couleur (byte Couleur, byte Couleur_de_taggage)
References Block, Fenetre_Liste_boutons_palette, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, and Menu_Facteur_Y.
Referenced by Bouton_Spray_Menu(), and Menu_Tag_couleurs().
void Message_Non_disponible (void)
Displays an error message when calling an unavailable function.
Only used in the beta versions for things we haven't coded yet.
References Afficher_curseur(), CM_Clair, CM_Noir, Display_Window, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), Ouvrir_fenetre(), Print_dans_fenetre(), Touche, and TOUCHE_ESC.
Referenced by Bouton_Brush_FX(), Gestion_principale(), and Initialisation_des_boutons().
void Message_Memoire_insuffisante (void)
Displays an error message when there is no more memory for the requested operation.
References Afficher_curseur(), CM_Clair, CM_Noir, Display_Window, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), Ouvrir_fenetre(), Print_dans_fenetre(), Touche, and TOUCHE_ESC.
Referenced by Copier_image_seule(), Initialiser_preview(), Initialiser_preview_24b(), and Redimentionner_image().
void Bouton_Message_initial (void)
Displays the splash screen at program startup.
References Afficher_curseur(), ALPHA_BETA, Attendre_fin_de_click(), Block, CM_Clair, CM_Fonce, CM_Noir, Display_Window, Fenetre_Afficher_cadre_creux(), Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Get_input(), Logo_GrafX2, Menu_Facteur_X, Menu_Facteur_Y, Mouse_K, Ouvrir_fenetre(), Pixel_dans_fenetre(), POURCENTAGE_VERSION, Print_dans_fenetre(), Touche, VERSION1, VERSION2, and Wait_VBL().
Referenced by main().
void Changer_la_forme_du_pinceau (byte Numero)
Changes brush shape.
This function saves the current brush shape and swith to the default one (single pixel brush) for the filler and the color picker. These functions don't need (and will not work with) a custom brush.
References Afficher_pinceau_dans_menu(), FORME_PINCEAU_POINT, Operation_en_cours, OPERATION_FILL, OPERATION_PIPETTE, Pinceau_Forme, Pinceau_Forme_avant_fill, and Pinceau_Forme_avant_pipette.
Referenced by Bouton_Brosse_monochrome(), Bouton_Menu_pinceaux(), Bouton_Restaurer_brosse(), Bouton_Texte(), Bouton_Trame_Menu(), Brosse_0_5(), Etirer_brosse_2_7(), Gestion_principale(), Load_picture(), Polybrosse_12_8(), and Tourner_brosse_2_5().
void Bouton_Undo (void)
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), BOUTON_LOUPE, BOUTON_UNDO, Calculer_couleurs_menu_optimales(), Desenclencher_bouton(), Effacer_curseur, Loupe_Mode, Principal_Palette, Set_palette(), Tracer_cadre_de_bouton_du_menu(), and Undo().
Referenced by Initialisation_des_boutons().
void Bouton_Redo (void)
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), BOUTON_LOUPE, BOUTON_UNDO, Calculer_couleurs_menu_optimales(), Desenclencher_bouton(), Effacer_curseur, Loupe_Mode, Principal_Palette, Redo(), Set_palette(), and Tracer_cadre_de_bouton_du_menu().
Referenced by Initialisation_des_boutons().
void Bouton_Pal_left (void)
Callback for the palette scroller buttons left click.
Scrolls the menubar palette one column to the left.
References Afficher_curseur(), Afficher_palette_du_menu(), BOUTON_PAL_LEFT, Couleur_debut_palette, Desenclencher_bouton(), Effacer_curseur, and Palette_Cells_Y().
Referenced by Initialisation_des_boutons().
void Bouton_Pal_left_fast (void)
Callback for the palette scroller buttons right click.
Scrolls the menubar palette faster to the left.
References Afficher_curseur(), Afficher_palette_du_menu(), BOUTON_PAL_LEFT, Couleur_debut_palette, Desenclencher_bouton(), Effacer_curseur, Palette_Cells_X(), and Palette_Cells_Y().
Referenced by Initialisation_des_boutons().
void Bouton_Pal_right (void)
Callback for the palette scroller buttons left click.
Scrolls the menubar palette one column to the right.
References Afficher_curseur(), Afficher_palette_du_menu(), BOUTON_PAL_RIGHT, Couleur_debut_palette, Desenclencher_bouton(), Effacer_curseur, Palette_Cells_X(), and Palette_Cells_Y().
Referenced by Initialisation_des_boutons().
void Bouton_Pal_right_fast (void)
Callback for the palette scroller buttons right click.
Scrolls the menubar palette faster to the right.
References Afficher_curseur(), Afficher_palette_du_menu(), BOUTON_PAL_RIGHT, Couleur_debut_palette, Desenclencher_bouton(), Effacer_curseur, Palette_Cells_X(), and Palette_Cells_Y().
Referenced by Initialisation_des_boutons().
void Bouton_Choix_forecolor (void)
Callback for the palette color buttons left click.
Selects the foreground drawing color when clicking on the menubar palette.
References Afficher_curseur(), Afficher_foreback(), CM_Blanc, CM_Noir, Couleur_palette(), Effacer_curseur, Encadrer_couleur_menu(), and Fore_color.
Referenced by Initialisation_des_boutons().
void Bouton_Choix_backcolor (void)
Callback for the palette color buttons right click.
Selects the background drawing color when clicking on the menubar palette.
References Afficher_curseur(), Afficher_foreback(), Back_color, Couleur_palette(), and Effacer_curseur.
Referenced by Initialisation_des_boutons().
void Pixel_dans_barre_d_outil_cachee (__attribute__((unused)) word X, __attribute__((unused)) word Y, __attribute__((unused)) byte Couleur)
Referenced by Bouton_Cacher_menu().
void Bouton_Cacher_menu (void)
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), BOUTON_CACHER, Brouillon_Decalage_Y, Brouillon_Hauteur_image, Calculer_coordonnees_pinceau(), Calculer_donnees_loupe(), Calculer_limites(), Desenclencher_bouton(), Effacer_curseur, Hauteur_ecran, HAUTEUR_MENU, Loupe_Decalage_Y, Loupe_Hauteur, Loupe_Mode, Menu_Facteur_Y, Menu_Ordonnee, Menu_visible, Pixel_dans_barre_d_outil(), Pixel_dans_barre_d_outil_cachee(), Pixel_dans_menu, Principal_Decalage_Y, Principal_Hauteur_image, and Recadrer_ecran_par_rapport_au_zoom().
Referenced by Initialisation_des_boutons().
byte Bouton_Quitter_Routine_locale (void)
References Afficher_curseur(), BOUTON_AIDE, BOUTON_QUIT, Demande_de_confirmation(), Display_Window, Effacer_curseur, Erreur_fichier, Est_Raccourci(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), Fichier_existe(), Forme_curseur, FORME_CURSEUR_SABLIER, Nom_fichier_complet(), Ouvrir_fenetre(), Principal_Image_modifiee, Sauver_image(), TAILLE_CHEMIN_FICHIER, Touche, and TOUCHE_ESC.
Referenced by Bouton_Quit().
void Bouton_Quit (void)
References Afficher_curseur(), Bouton_Page(), BOUTON_QUIT, Bouton_Quitter_Routine_locale(), Brouillon_Image_modifiee, Desenclencher_bouton(), Effacer_curseur, Menu_Ordonnee, Menu_visible, Mouse_Y, and Sortir_du_programme.
Referenced by Gestion_principale(), and Initialisation_des_boutons().
void Bouton_Clear (void)
References Afficher_curseur(), Afficher_ecran(), Backup(), BOUTON_CLEAR, S_Config::Clear_with_stencil, Config, Desenclencher_bouton(), Effacer_curseur, Effacer_image_courante(), Effacer_image_courante_Stencil(), Stencil, and Stencil_Mode.
Referenced by Initialisation_des_boutons().
void Bouton_Clear_colore (void)
References Afficher_curseur(), Afficher_ecran(), Back_color, Backup(), BOUTON_CLEAR, S_Config::Clear_with_stencil, Config, Desenclencher_bouton(), Effacer_curseur, Effacer_image_courante(), Effacer_image_courante_Stencil(), Stencil, and Stencil_Mode.
Referenced by Initialisation_des_boutons().
void Menu_Tag_couleurs (char * En_tete, byte * Table, byte * Mode, byte Cancel, const char * Section_aide)
References A_GAUCHE, Afficher_curseur(), Attendre_fin_de_click(), BOUTON_AIDE, BOUTON_EFFETS, CM_Clair, CM_Noir, Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_palette(), Fenetre_Hauteur, Fenetre_Largeur, Fermer_fenetre(), Lit_pixel, Mouse_K, Mouse_X, Mouse_Y, Ouvrir_fenetre(), Recuperer_couleur_derriere_fenetre(), Stencil_Actualiser_couleur(), Stencil_Tagger_couleur(), Touche, and TOUCHE_ESC.
Referenced by Bouton_Mask_Menu(), Bouton_Menu_Stencil(), Bouton_Palette_secondaire(), Copier_certaines_couleurs(), and Gestion_principale().
void Bouton_Stencil_Mode (void)
References Stencil_Mode.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Menu_Stencil (void)
References Menu_Tag_couleurs(), Stencil, and Stencil_Mode.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Mask_Mode (void)
References Mask_Mode.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Mask_Menu (void)
References Mask_Mode, Mask_table, and Menu_Tag_couleurs().
Referenced by Bouton_Effets(), and Gestion_principale().
void Settings_Afficher_config (struct S_Config * Conf)
References S_Config::Adjust_brush_pick, Afficher_curseur(), S_Config::Afficher_limites_image, S_Config::Auto_save, S_Config::Auto_set_res, S_Config::Backup, S_Config::Clear_palette, CM_Clair, CM_Noir, S_Config::Coords_rel, S_Config::Couleurs_separees, S_Config::Curseur, Effacer_curseur, Fenetre_Contenu_bouton_saisie(), Fenetre_Dessiner_jauge(), Fenetre_Liste_boutons_scroller, Fenetre_Liste_boutons_special, S_Config::Fonte, S_Config::Indice_Sensibilite_souris_X, S_Config::Indice_Sensibilite_souris_Y, S_Config::Lire_les_fichiers_caches, S_Config::Lire_les_repertoires_caches, S_Config::Maximize_preview, S_Config::Nb_pages_Undo, Fenetre_Bouton_scroller::Next, NO, Num2str(), Fenetre_Bouton_scroller::Position, Print_dans_fenetre(), S_Config::Safety_colors, and YES.
Referenced by Bouton_Settings().
void Settings_Sauver_config (struct S_Config * Conf)
References Erreur, Sauver_CFG(), and Sauver_INI().
Referenced by Bouton_Settings().
void Settings_Charger_config (struct S_Config * Conf)
References Charger_CFG(), Charger_INI(), and Erreur.
Referenced by Bouton_Settings().
void Bouton_Settings (void)
References S_Config::Adjust_brush_pick, Afficher_curseur(), S_Config::Afficher_limites_image, Afficher_menu(), Attendre_fin_de_click(), S_Config::Auto_save, S_Config::Auto_set_res, S_Config::Backup, BOUTON_AIDE, BOUTON_PARAMETRES, Brouillon_File_list_Decalage, Brouillon_File_list_Position, Calculer_couleurs_menu_optimales(), S_Config::Clear_palette, CM_Clair, CM_Fonce, Config, S_Config::Coords_rel, S_Config::Couleurs_separees, S_Config::Curseur, Desenclencher_bouton(), Display_Window, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fenetre_Definir_bouton_scroller(), Fenetre_Liste_boutons_special, Fermer_fenetre(), Fonte, S_Config::Fonte, Fonte_fun, Fonte_systeme, S_Config::Indice_Sensibilite_souris_X, S_Config::Indice_Sensibilite_souris_Y, S_Config::Lire_les_fichiers_caches, S_Config::Lire_les_repertoires_caches, S_Config::Maximize_preview, Menu_Facteur_X, Menu_Facteur_Y, Mouse_Facteur_de_correction_X, Mouse_Facteur_de_correction_Y, S_Config::Nb_pages_Undo, NB_PAGES_UNDO_MAX, Nouveau_nombre_de_backups(), Num2str(), Ouvrir_fenetre(), Principal_File_list_Decalage, Principal_File_list_Position, Principal_Palette, Print_dans_fenetre(), Readline(), S_Config::Safety_colors, Sensibilite_souris(), Settings_Afficher_config(), Settings_Charger_config(), Settings_Sauver_config(), Touche, and TOUCHE_ESC.
Referenced by Initialisation_des_boutons().
void Bouton_Page (void)
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), Ancien_Brouillon_Decalage_X, Ancien_Brouillon_Decalage_Y, Ancien_Principal_Decalage_X, Ancien_Principal_Decalage_Y, BOUTON_LOUPE, BOUTON_PAGE, Brouillon_Decalage_X, Brouillon_Decalage_Y, Brouillon_File_list_Decalage, Brouillon_File_list_Position, Brouillon_Format, Brouillon_Image_modifiee, Brouillon_Loupe_Decalage_X, Brouillon_Loupe_Decalage_Y, Brouillon_Loupe_Facteur, Brouillon_Loupe_Hauteur, Brouillon_Loupe_Largeur, Brouillon_Loupe_Mode, Brouillon_Proportion_split, Brouillon_Repertoire_courant, Brouillon_Split, Brouillon_X_Zoom, Calculer_couleurs_menu_optimales(), Changer_facteur_loupe(), Desenclencher_bouton(), Effacer_curseur, FACTEUR_ZOOM, Interchanger_image_principale_et_brouillon(), Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Facteur, Loupe_Hauteur, Loupe_Largeur, Loupe_Mode, Pixel_Preview, Pixel_Preview_Loupe, Pixel_Preview_Normal, Principal_Decalage_X, Principal_Decalage_Y, Principal_File_list_Decalage, Principal_File_list_Position, Principal_Format, Principal_Image_modifiee, Principal_Palette, Principal_Proportion_split, Principal_Repertoire_courant, Principal_Split, Principal_X_Zoom, Set_palette(), and Tracer_cadre_de_bouton_du_menu().
Referenced by Bouton_Quit(), Initialisation_des_boutons(), and main().
void Copier_image_seule (void)
References Backuper_et_redimensionner_brouillon(), Brouillon_Decalage_X, Brouillon_Decalage_Y, Brouillon_Ecran, Brouillon_Hauteur_image, Brouillon_Largeur_image, Brouillon_Loupe_Decalage_X, Brouillon_Loupe_Decalage_Y, Brouillon_Loupe_Facteur, Brouillon_Loupe_Hauteur, Brouillon_Loupe_Largeur, Brouillon_Loupe_Mode, Brouillon_Proportion_split, Brouillon_Split, Brouillon_X_Zoom, Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Facteur, Loupe_Hauteur, Loupe_Largeur, Loupe_Mode, Message_Memoire_insuffisante(), Principal_Decalage_X, Principal_Decalage_Y, Principal_Ecran, Principal_Hauteur_image, Principal_Largeur_image, Principal_Proportion_split, Principal_Split, and Principal_X_Zoom.
Referenced by Bouton_Copy_page().
void Copier_certaines_couleurs (void)
References Brouillon_Image_modifiee, Brouillon_Palette, Demande_de_confirmation(), Masque_copie_couleurs, Menu_Tag_couleurs(), and Principal_Palette.
Referenced by Bouton_Copy_page().
void Bouton_Copy_page (void)
References Afficher_curseur(), BOUTON_AIDE, BOUTON_PAGE, Brouillon_Image_modifiee, Brouillon_Palette, Copier_certaines_couleurs(), Copier_image_seule(), Demande_de_confirmation(), Desenclencher_bouton(), Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), Ouvrir_fenetre(), Principal_Palette, Remap_picture(), Touche, and TOUCHE_ESC.
Referenced by Initialisation_des_boutons().
void Bouton_Kill (void)
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), BOUTON_KILL, BOUTON_LOUPE, Calculer_couleurs_menu_optimales(), Demande_de_confirmation(), Desenclencher_bouton(), Detruire_la_page_courante(), Effacer_curseur, Loupe_Mode, S_Liste_de_pages::Nb_pages_allouees, Principal_Backups, Principal_Palette, Set_palette(), Tracer_cadre_de_bouton_du_menu(), and Warning_message().
Referenced by Initialisation_des_boutons().
void Cocher_bouton_mode (short Pos_X, short Pos_Y, byte Etat)
References Block, CM_Blanc, CM_Clair, CM_Fonce, CM_Noir, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, and UpdateRect().
Referenced by Afficher_liste_modes(), and Bouton_Resol().
void Afficher_liste_modes (short Debut_liste, short Position_curseur)
References CM_Blanc, CM_Clair, CM_Fonce, CM_Noir, Cocher_bouton_mode(), Hauteur, Largeur, Mode_video, Nb_modes_video, Num2str(), Print_dans_fenetre(), and S_Config::Ratio.
Referenced by Bouton_Resol(), and Scroller_la_liste_des_modes().
void Scroller_la_liste_des_modes (short Debut_liste, short Position_curseur, int * Mode_choisi)
References Afficher_curseur(), Afficher_liste_modes(), Effacer_curseur, Fenetre_Dessiner_jauge(), and Fenetre_Liste_boutons_scroller.
Referenced by Bouton_Resol().
void Bouton_Resol (void)
References A_GAUCHE, Afficher_curseur(), Afficher_ecran(), Afficher_liste_modes(), Afficher_menu(), Attendre_fin_de_click(), Block, BOUTON_AIDE, BOUTON_LOUPE, BOUTON_RESOL, CM_Clair, CM_Fonce, CM_Noir, Cocher_bouton_mode(), Desenclencher_bouton(), Display_Window, Effacer_curseur, Erreur, Est_Raccourci(), S_Mode_video::Etat, Fenetre_Afficher_cadre(), Fenetre_Afficher_cadre_creux(), Fenetre_aide(), Fenetre_Attribut1, Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fenetre_Definir_bouton_scroller(), Fenetre_Definir_bouton_special(), Fenetre_Dessiner_bouton_normal(), Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Hauteur, S_Mode_video::Hauteur, Initialiser_mode_video(), Largeur, S_Mode_video::Largeur, Loupe_Mode, Menu_Facteur_X, Menu_Facteur_Y, Mode_video, Mouse_K, Mouse_X, Mouse_Y, Nb_modes_video, Num2str(), Ouvrir_fenetre(), Pinceau_X, Pinceau_Y, Pixel_height, Pixel_width, Position_curseur, Principal_Hauteur_image, Principal_Largeur_image, Print_dans_fenetre(), Readline(), Redimentionner_image(), Resolution_actuelle, Scroller_la_liste_des_modes(), Touche, and TOUCHE_ESC.
Referenced by Initialisation_des_boutons().
void Bouton_Safety_resol (void)
References Afficher_curseur(), Afficher_ecran(), Afficher_menu(), BOUTON_LOUPE, BOUTON_RESOL, Desenclencher_bouton(), Effacer_curseur, S_Mode_video::Hauteur, Hauteur_ecran, Initialiser_mode_video(), S_Mode_video::Largeur, Largeur_ecran, Mode_video, Pixel_height, Pixel_width, and Resolution_actuelle.
Referenced by Initialisation_des_boutons().
void Bouton_Dessin (void)
Callback for the freehand draw button left click.
Selects freehand drawing mode, depending on the current state of the freehand button.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and Mode_de_dessin_en_cours.
Referenced by Initialisation_des_boutons().
void Bouton_Dessin_Switch_mode (void)
Callback for the freehand draw button right click.
Cycles the drawing modes for the freehand tool.
References Afficher_curseur(), Afficher_sprite_dans_menu(), BOUTON_DESSIN, Demarrer_pile_operation(), Effacer_curseur, Mode_de_dessin_en_cours, OPERATION_DESSIN_CONTINU, and OPERATION_FILLED_CONTOUR.
Referenced by Initialisation_des_boutons().
void Bouton_Rectangle_vide (void)
Callback for the empty rectangle button.
Start the rectangle operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_RECTANGLE_VIDE.
Referenced by Initialisation_des_boutons().
void Bouton_Rectangle_plein (void)
Callback for the filled rectangle button.
Start the filled rectangle operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_RECTANGLE_PLEIN.
Referenced by Initialisation_des_boutons().
void Bouton_Cercle_vide (void)
Callback for the circle button left click.
Starts drawing an empty circle
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_CERCLE_VIDE.
Referenced by Initialisation_des_boutons().
void Bouton_Ellipse_vide (void)
Callback for the circle button left click.
Starts drawing an empty ellipsis
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_ELLIPSE_VIDE.
Referenced by Initialisation_des_boutons().
void Bouton_Cercle_plein (void)
Callback for the filled circle button ledt click.
Starts drawing a filled circle.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_CERCLE_PLEIN.
Referenced by Initialisation_des_boutons().
void Bouton_Ellipse_pleine (void)
Callback for the filled circle right click.
Starts drawing a filled ellipsis.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_ELLIPSE_PLEINE.
Referenced by Initialisation_des_boutons().
void Degrade_Dessiner_bouton_de_technique (short Pos_X, short Pos_Y, int Technique)
References Block, CM_Blanc, CM_Noir, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Pixel_dans_fenetre(), and UpdateRect().
Referenced by Bouton_Degrades().
void Degrade_Charger_infos_du_tableau (int Indice)
Gets the informations from the gradations table and set the global vars for the current gradation.
Parameters:
Indice index of the selected gradation
References T_Degrade_Tableau::Debut, Degrade_Borne_Inferieure, Degrade_Borne_Superieure, Degrade_de_base(), Degrade_de_trames_etendues(), Degrade_de_trames_simples(), Degrade_Intervalle_bornes, Degrade_Inverse, Degrade_Melange_aleatoire, Degrade_Tableau, T_Degrade_Tableau::Fin, T_Degrade_Tableau::Inverse, T_Degrade_Tableau::Melange, and Traiter_degrade.
Referenced by Bouton_Degrades(), Charger_CFG(), Config_par_defaut(), and Degrade_Dessiner_preview().
void Degrade_Dessiner_preview (short Debut_X, short Debut_Y, short Largeur, short Hauteur, int Indice)
References Degrade_Charger_infos_du_tableau(), Degrade_Intervalle_total, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Fenetre_Bouton_special::Pos_X, Fenetre_Bouton_special::Pos_Y, Traiter_degrade, and UpdateRect().
Referenced by Bouton_Degrades().
void Bouton_Degrades (void)
Callback for the gradation button.
Opens the "Gradation menu".
References Afficher_curseur(), Afficher_pixel(), Attendre_fin_de_click(), BOUTON_AIDE, BOUTON_GRADMENU, CM_Clair, CM_Fonce, CM_Noir, T_Degrade_Tableau::Debut, Degrade_Charger_infos_du_tableau(), Degrade_Courant, Degrade_Dessiner_bouton_de_technique(), Degrade_Dessiner_preview(), Degrade_Tableau, Desenclencher_bouton(), Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_Afficher_cadre_creux(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_palette(), Fenetre_Definir_bouton_scroller(), Fenetre_Dessiner_jauge(), Fermer_fenetre(), T_Degrade_Tableau::Fin, T_Degrade_Tableau::Inverse, Lit_pixel, T_Degrade_Tableau::Melange, MOD_SHIFT, Mouse_K, Mouse_X, Mouse_Y, Num2str(), Ouvrir_fenetre(), Pixel, Fenetre_Bouton_scroller::Position, Print_dans_fenetre(), Recuperer_couleur_derriere_fenetre(), Tagger_intervalle_palette(), T_Degrade_Tableau::Technique, Touche, TOUCHE_ESC, and Traiter_pixel_de_degrade.
Referenced by Initialisation_des_boutons().
void Bouton_Cercle_degrade (void)
Callback for the gradation circle button left click.
Starts drawing a gradation circle.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_CERCLE_DEGRADE.
Referenced by Initialisation_des_boutons().
void Bouton_Ellipse_degrade (void)
Callback for the gradation circle right click.
Starts drawing a gradation ellipsis.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_ELLIPSE_DEGRADEE.
Referenced by Initialisation_des_boutons().
void Bouton_Rectangle_degrade (void)
Callback for the gradation rectangle button.
Starts the gradation rectangle drawing operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_RECTANGLE_DEGRADE.
Referenced by Initialisation_des_boutons().
void Bouton_Fill (void)
Callback for the fill button left click.
Start the filling operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, FORME_PINCEAU_POINT, Loupe_Mode, Menu_Ordonnee, Menu_visible, Mouse_X, Mouse_Y, Operation_en_cours, OPERATION_FILL, OPERATION_REMPLACER, Pinceau_Forme, Pinceau_Forme_avant_fill, Principal_Split, Principal_X_Zoom, and Print_dans_menu().
Referenced by Initialisation_des_boutons().
void Bouton_Remplacer (void)
Callback for the fill button right click.
Start the color replace operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, FORME_PINCEAU_POINT, Loupe_Mode, Menu_Ordonnee, Menu_visible, Mouse_X, Mouse_Y, Operation_en_cours, OPERATION_FILL, OPERATION_REMPLACER, Pinceau_Forme, Pinceau_Forme_avant_fill, Principal_Split, Principal_X_Zoom, and Print_dans_menu().
Referenced by Initialisation_des_boutons().
void Bouton_desenclencher_Fill (void)
Disable and release the fill button.
Restores the cursor (custom brushes are disabled for the fill operation). Cleans the status bar if the color replacement tool put a preview color inside it.
References Loupe_Mode, Menu_Ordonnee, Menu_visible, Mouse_X, Mouse_Y, Operation_en_cours, OPERATION_REMPLACER, Pinceau_Forme, Pinceau_Forme_avant_fill, Principal_Split, Principal_X_Zoom, and Print_dans_menu().
Referenced by Initialisation_des_boutons().
void Bouton_Menu_pinceaux (void)
Callback for the brush button right click.
Displays the "Paintbrush menu".
References Afficher_curseur(), Afficher_pinceau_dans_fenetre(), BOUTON_AIDE, BOUTON_PINCEAUX, Changer_la_forme_du_pinceau(), Desenclencher_bouton(), Display_Window, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), NB_SPRITES_PINCEAU, Ouvrir_fenetre(), Pinceau_Decalage_X, Pinceau_Decalage_Y, Pinceau_Forme, Pinceau_Hauteur, Pinceau_Largeur, Pinceau_predefini_Decalage_X, Pinceau_predefini_Decalage_Y, Pinceau_predefini_Hauteur, Pinceau_predefini_Largeur, Pinceau_Sprite, Pinceau_Type, Fenetre_Bouton_scroller::Pos_X, Fenetre_Bouton_scroller::Pos_Y, SPRITE_PINCEAU, TAILLE_MAXI_PINCEAU, Touche, and TOUCHE_ESC.
Referenced by Initialisation_des_boutons().
void Bouton_Brosse_monochrome (void)
Callback for the brush button left click.
Selects the monochrome brush mode when right clicking on the brush button.
References Afficher_curseur(), BOUTON_PINCEAUX, Changer_la_forme_du_pinceau(), Desenclencher_bouton(), Effacer_curseur, and FORME_PINCEAU_BROSSE_MONOCHROME.
Referenced by Initialisation_des_boutons().
void Print_repertoire_courant (void)
References Block, CM_Clair, CM_Noir, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Principal_Repertoire_courant, Print_dans_fenetre(), SEPARATEUR_CHEMIN, TAILLE_MAXI_PATH, and UpdateRect().
Referenced by Preparer_et_afficher_liste_fichiers().
void Print_Nom_fichier_dans_selecteur (void)
References Block, CM_Clair, CM_Noir, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Principal_Nom_fichier, Print_dans_fenetre_limite(), and UpdateRect().
Referenced by Bouton_Load_ou_Save(), On_vient_de_scroller_dans_le_fileselect(), and Preparer_et_afficher_liste_fichiers().
void Preparer_et_afficher_liste_fichiers (short Position, short Decalage, struct Fenetre_Bouton_scroller * Enreg)
References Afficher_la_liste_des_fichiers(), Block, Calculer_hauteur_curseur_jauge(), CM_Noir, Determiner_element_de_la_liste(), Fenetre_Dessiner_jauge(), Fenetre_Pos_X, Fenetre_Pos_Y, FILENAMESPACE, Liste_Nb_elements, Menu_Facteur_X, Menu_Facteur_Y, Fenetre_Bouton_scroller::Nb_elements, Fenetre_Bouton_scroller::Position, Principal_Nom_fichier, Print_Nom_fichier_dans_selecteur(), Print_repertoire_courant(), and UpdateRect().
Referenced by Bouton_Load_ou_Save(), and Relire_liste_fichiers().
void Relire_liste_fichiers (byte Filtre, short Position, short Decalage, struct Fenetre_Bouton_scroller * Enreg)
References Lire_liste_des_fichiers(), Preparer_et_afficher_liste_fichiers(), and Trier_la_liste_des_fichiers().
Referenced by Bouton_Load_ou_Save().
void On_vient_de_scroller_dans_le_fileselect (struct Fenetre_Bouton_scroller * Scroller_de_fichiers)
References Afficher_curseur(), Determiner_element_de_la_liste(), Fenetre_Dessiner_jauge(), Nouvelle_preview, Fenetre_Bouton_scroller::Position, Principal_File_list_Decalage, Principal_File_list_Position, Principal_Nom_fichier, Print_Nom_fichier_dans_selecteur(), and TAILLE_CHEMIN_FICHIER.
Referenced by Bouton_Load_ou_Save().
short Position_fichier_dans_liste (char * Nom)
References Liste_du_fileselect, Element_de_liste_de_fileselect::NomComplet, and Element_de_liste_de_fileselect::Suivant.
Referenced by Placer_barre_de_selection_sur().
void Placer_barre_de_selection_sur (char * Nom)
References Liste_Nb_elements, Position_fichier_dans_liste(), Principal_File_list_Decalage, and Principal_File_list_Position.
Referenced by Bouton_Load_ou_Save().
char* Nom_correspondant_le_mieux_a (char * Nom)
References Config, S_Config::Find_file_fast, Liste_du_fileselect, Element_de_liste_de_fileselect::NomComplet, Principal_Nom_fichier, Element_de_liste_de_fileselect::Suivant, and Element_de_liste_de_fileselect::Type.
Referenced by Bouton_Load_ou_Save().
byte Bouton_Load_ou_Save (byte Load, byte Image)
References A_DROITE, A_GAUCHE, Afficher_bookmark(), Afficher_curseur(), Afficher_la_liste_des_fichiers(), Afficher_menu(), Attendre_fin_de_click(), Back_color, Block, S_Config::Bookmark_directory, S_Config::Bookmark_label, BOUTON_AIDE, BOUTON_CHARGER, BOUTON_SAUVER, Brouillon_File_list_Decalage, Brouillon_File_list_Position, Brouillon_Repertoire_courant, Calculer_couleurs_menu_optimales(), Calculer_decalage_click_dans_fileselector(), CARACTERE_SUSPENSION, Charger_image(), S_Config::Chrono_delay, CM_Clair, CM_Fonce, CM_Noir, Config, Demande_de_confirmation(), Desenclencher_bouton(), Determiner_element_de_la_liste(), Determiner_repertoire_courant(), Detruire_liste_du_fileselect(), Display_Window, Effacer_curseur, Erreur, Est_Raccourci(), Etat_chrono, Fenetre_Afficher_cadre(), Fenetre_Afficher_cadre_creux(), Fenetre_Afficher_sprite_drive(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_dropdown(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fenetre_Definir_bouton_scroller(), Fenetre_Definir_bouton_special(), Fenetre_Dropdown_choix(), Fenetre_Hauteur, Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Fichier_existe(), FILENAMESPACE, FORMAT_PAR_DEFAUT, FormatFichier, Initialiser_chrono(), Lire_liste_des_fichiers(), Lire_liste_des_lecteurs(), Liste_du_fileselect, Liste_Nb_elements, Liste_Nb_repertoires, Menu_Facteur_X, Menu_Facteur_Y, Menu_Ordonnee_avant_fenetre, NB_BOOKMARKS, NB_FORMATS_CONNUS, NB_FORMATS_SAVE, Nom_correspondant_le_mieux_a(), Nom_formate(), Element_de_liste_de_fileselect::NomComplet, Nouvelle_preview, On_vient_de_scroller_dans_le_fileselect(), Ouvrir_fenetre(), PARENT_DIR, Pixel_Chargement_dans_ecran_courant(), Pixel_Chargement_dans_preview(), Pixel_de_chargement, Placer_barre_de_selection_sur(), Position_dernier_slash(), Preparer_et_afficher_liste_fichiers(), Principal_Commentaire, Principal_File_list_Decalage, Principal_File_list_Position, Principal_Format, Principal_Format_fichier, Principal_Hauteur_image, Principal_Image_modifiee, Principal_Largeur_image, Principal_Nom_fichier, Principal_Palette, Principal_Repertoire_courant, Principal_Repertoire_fichier, Print_dans_fenetre(), Print_Nom_fichier_dans_selecteur(), Readline(), Readline_ex(), Relire_liste_fichiers(), Repertoire_existe(), Select_End(), Select_Home(), Select_Page_Down(), Select_Page_Up(), Select_Scroll_Down(), Select_Scroll_Up(), Set_palette(), TAILLE_CHEMIN_FICHIER, TAILLE_COMMENTAIRE, Tester_chrono(), Touche, Touche_ANSI, TOUCHE_ESC, TOUCHE_MOUSEWHEELDOWN, TOUCHE_MOUSEWHEELUP, ToWinH, ToWinL, ToWinX, ToWinY, Trier_la_liste_des_fichiers(), and UpdateRect().
Referenced by Load_picture(), and Save_picture().
int Meilleur_mode_video (void)
References Config, Ecran_original_X, Ecran_original_Y, S_Mode_video::Hauteur, S_Mode_video::Largeur, Mode_video, Nb_modes_video, Principal_Hauteur_image, Principal_Largeur_image, Resolution_actuelle, S_Config::Set_resolution_according_to, TOLERANCE_X, and TOLERANCE_Y.
Referenced by Bouton_Reload(), and Load_picture().
void Swapper_infos_selecteurs_image_et_brosse (void)
References Brosse_Commentaire, Brosse_File_list_Decalage, Brosse_File_list_Position, Brosse_Format, Brosse_Format_fichier, Brosse_Nom_fichier, Brosse_Repertoire_courant, Brosse_Repertoire_fichier, Principal_Commentaire, Principal_File_list_Decalage, Principal_File_list_Position, Principal_Format, Principal_Format_fichier, Principal_Nom_fichier, Principal_Repertoire_courant, Principal_Repertoire_fichier, and TAILLE_CHEMIN_FICHIER.
Referenced by Load_picture(), and Save_picture().
void Load_picture (byte Image)
References A_DROITE, A_GAUCHE, Afficher_curseur(), Afficher_ecran(), Afficher_menu(), S_Config::Auto_discontinuous, S_Config::Auto_set_res, BOUTON_DESSIN, Bouton_Load_ou_Save(), BOUTON_LOUPE, Brosse, Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, Calculer_coordonnees_pinceau(), Calculer_couleurs_menu_optimales(), Calculer_limites(), Changer_la_forme_du_pinceau(), Charger_image(), Config, Demande_de_confirmation(), Ecran_original_X, Ecran_original_Y, Effacer_curseur, Enclencher_bouton(), Erreur_fichier, Fore_color, FormatFichier, Forme_curseur, FORME_CURSEUR_SABLIER, FORME_PINCEAU_BROSSE_COULEUR, Hauteur, Initialiser_mode_video(), Largeur, Loupe_Mode, Meilleur_mode_video(), Mode_video, OPERATION_DESSIN_DISCONTINU, Operation_en_cours, Pixel_Chargement_dans_brosse(), Pixel_Chargement_dans_ecran_courant(), Pixel_de_chargement, Pixel_Preview, Pixel_Preview_Normal, Principal_Commentaire, Principal_Decalage_X, Principal_Decalage_Y, Principal_Format_fichier, Principal_Hauteur_image, Principal_Image_modifiee, Principal_Largeur_image, Principal_Nom_fichier, Principal_Palette, Principal_Repertoire_fichier, Print_nom_fichier(), Resolution_actuelle, Set_palette(), Smear_Brosse, Smear_Brosse_Hauteur, Smear_Brosse_Largeur, Swapper_infos_selecteurs_image_et_brosse(), TAILLE_CHEMIN_FICHIER, TAILLE_MAXI_PINCEAU, Tiling_Decalage_X, Tiling_Decalage_Y, and Tracer_cadre_de_bouton_du_menu().
Referenced by Bouton_Brush_FX(), Bouton_Load(), and Gestion_principale().
void Bouton_Load (void)
References Load_picture(), S_Liste_de_pages::Pages, Principal_Backups, and Upload_infos_page_principal().
Referenced by Initialisation_des_boutons().
void Bouton_Reload (void)
References Afficher_curseur(), Afficher_ecran(), Afficher_limites_de_l_image(), S_Config::Afficher_limites_image, Afficher_menu(), S_Config::Auto_set_res, BOUTON_CHARGER, BOUTON_LOUPE, Calculer_coordonnees_pinceau(), Calculer_couleurs_menu_optimales(), Calculer_limites(), Charger_image(), Config, Demande_de_confirmation(), Desenclencher_bouton(), Ecran_original_X, Ecran_original_Y, Effacer_curseur, Erreur_fichier, Forme_curseur, FORME_CURSEUR_SABLIER, Hauteur, Initialiser_mode_video(), Largeur, Loupe_Mode, Meilleur_mode_video(), Mode_video, S_Liste_de_pages::Pages, Pixel_Preview, Pixel_Preview_Normal, Principal_Backups, Principal_Decalage_X, Principal_Decalage_Y, Principal_Image_modifiee, Principal_Palette, Resolution_actuelle, Tracer_cadre_de_bouton_du_menu(), Une_resolution_a_ete_passee_en_parametre, and Upload_infos_page_principal().
Referenced by Initialisation_des_boutons(), and main().
void Nom_fichier_backup (char * Nom, char * Nom_backup)
References Principal_Nom_fichier.
Referenced by Backup_du_fichier_sauvegarde().
void Backup_du_fichier_sauvegarde (void)
References Erreur_fichier, Fichier_existe(), Nom_fichier_backup(), Nom_fichier_complet(), and TAILLE_CHEMIN_FICHIER.
Referenced by Bouton_Autosave(), and Save_picture().
void Save_picture (byte Image)
References Afficher_curseur(), S_Config::Backup, Backup_du_fichier_sauvegarde(), Bouton_Load_ou_Save(), Brosse_Hauteur, Brosse_Largeur, Config, Demande_de_confirmation(), Effacer_curseur, Erreur, Erreur_fichier, Fichier_existe(), FormatFichier, Forme_curseur, FORME_CURSEUR_SABLIER, Principal_Format_fichier, Principal_Hauteur_image, Principal_Largeur_image, Principal_Nom_fichier, Principal_Palette, Principal_Repertoire_fichier, Print_nom_fichier(), Sauver_image(), Set_palette(), Swapper_infos_selecteurs_image_et_brosse(), and TAILLE_CHEMIN_FICHIER.
Referenced by Bouton_Brush_FX(), Bouton_Save(), and Gestion_principale().
void Bouton_Save (void)
References Save_picture().
Referenced by Initialisation_des_boutons().
void Bouton_Autosave (void)
References Afficher_curseur(), S_Config::Backup, Backup_du_fichier_sauvegarde(), BOUTON_SAUVER, Config, Demande_de_confirmation(), Desenclencher_bouton(), Effacer_curseur, Erreur, Erreur_fichier, Fichier_existe(), Forme_curseur, FORME_CURSEUR_SABLIER, Nom_fichier_complet(), Sauver_image(), and TAILLE_CHEMIN_FICHIER.
Referenced by Initialisation_des_boutons().
void Bouton_Lignes (void)
Callback for the lines button left click.
Selects lines drawing mode, depending on the current state of the lines button.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and Ligne_en_cours.
Referenced by Initialisation_des_boutons().
void Bouton_Lignes_Switch_mode (void)
Callback for the lines button right click.
Cycles the drawing modes for the lines tool.
References Afficher_curseur(), Afficher_sprite_dans_menu(), BOUTON_LIGNES, Demarrer_pile_operation(), Effacer_curseur, Ligne_en_cours, OPERATION_K_LIGNE, OPERATION_LIGNE, and OPERATION_LIGNES_CENTREES.
Referenced by Initialisation_des_boutons().
void Bouton_Brosse (void)
References Afficher_curseur(), BOUTON_BROSSE, Demarrer_pile_operation(), Desenclencher_bouton(), Effacer_curseur, Operation_en_cours, and OPERATION_PRISE_BROSSE.
Referenced by Initialisation_des_boutons().
void Bouton_desenclencher_Brosse (void)
References Demarrer_pile_operation(), and Operation_avant_interruption.
Referenced by Initialisation_des_boutons().
void Bouton_Restaurer_brosse (void)
References Afficher_curseur(), BOUTON_BROSSE, BOUTON_POLYBROSSE, Changer_la_forme_du_pinceau(), Desenclencher_bouton(), Effacer_curseur, and FORME_PINCEAU_BROSSE_COULEUR.
Referenced by Initialisation_des_boutons().
void Bouton_Lasso (void)
References Afficher_curseur(), BOUTON_POLYBROSSE, Demarrer_pile_operation(), Desenclencher_bouton(), Effacer_curseur, FORME_PINCEAU_POINT, Operation_en_cours, OPERATION_POLYBROSSE, Pinceau_Forme, and Pinceau_Forme_avant_lasso.
Referenced by Initialisation_des_boutons().
void Bouton_desenclencher_Lasso (void)
References Demarrer_pile_operation(), Operation_avant_interruption, Pinceau_Forme, and Pinceau_Forme_avant_lasso.
Referenced by Initialisation_des_boutons().
void Bouton_Pipette (void)
References Afficher_curseur(), BOUTON_PIPETTE, Demarrer_pile_operation(), Desenclencher_bouton(), Effacer_curseur, FORME_PINCEAU_POINT, Loupe_Mode, Menu_Ordonnee, Menu_visible, Mouse_X, Mouse_Y, Operation_avant_interruption, Operation_en_cours, OPERATION_PIPETTE, OPERATION_REMPLACER, Pinceau_Forme, Pinceau_Forme_avant_pipette, Pipette_Couleur, Principal_Split, Principal_X_Zoom, and Print_dans_menu().
Referenced by Initialisation_des_boutons().
void Bouton_desenclencher_Pipette (void)
References Demarrer_pile_operation(), Loupe_Mode, Menu_Ordonnee, Menu_visible, Mouse_X, Mouse_Y, Operation_avant_interruption, Operation_en_cours, OPERATION_PIPETTE, OPERATION_REMPLACER, Pinceau_Forme, Pinceau_Forme_avant_pipette, Principal_Split, Principal_X_Zoom, and Print_dans_menu().
Referenced by Initialisation_des_boutons().
void Bouton_Inverser_foreback (void)
References Afficher_curseur(), Afficher_foreback(), Back_color, BOUTON_PIPETTE, CM_Blanc, CM_Noir, Desenclencher_bouton(), Effacer_curseur, Encadrer_couleur_menu(), Fore_color, and Recadrer_palette().
Referenced by Initialisation_des_boutons().
void Bouton_Loupe (void)
References Afficher_curseur(), Afficher_ecran(), Ancien_Principal_Decalage_X, Ancien_Principal_Decalage_Y, BOUTON_LOUPE, Calculer_coordonnees_pinceau(), Calculer_donnees_loupe(), Calculer_limites(), Config, Demarrer_pile_operation(), Desenclencher_bouton(), Effacer_curseur, S_Config::Fast_zoom, Limite_Bas, Limite_Droite, Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Hauteur, Loupe_Largeur, Loupe_Mode, Menu_Ordonnee, Mouse_X, Mouse_Y, Operation_en_cours, OPERATION_LOUPE, Pixel_Preview, Pixel_Preview_Loupe, Principal_Decalage_X, Principal_Decalage_Y, Recadrer_ecran_par_rapport_au_zoom(), and UpdateRect().
Referenced by Initialisation_des_boutons().
void Bouton_Menu_Loupe (void)
References A_GAUCHE, Afficher_curseur(), Afficher_ecran(), BOUTON_AIDE, BOUTON_LOUPE, Changer_facteur_loupe(), Desenclencher_bouton(), Display_Window, Enclencher_bouton(), Est_Raccourci(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fermer_fenetre(), Largeur_ecran, Loupe_Facteur, Loupe_Mode, Menu_Ordonnee, Menu_Ordonnee_avant_fenetre, Operation_en_cours, OPERATION_LOUPE, Ouvrir_fenetre(), Principal_Split, Touche, TOUCHE_ESC, and UpdateRect().
Referenced by Initialisation_des_boutons().
void Bouton_desenclencher_Loupe (void)
References Afficher_ecran(), Ancien_Principal_Decalage_X, Ancien_Principal_Decalage_Y, Calculer_coordonnees_pinceau(), Calculer_limites(), Demarrer_pile_operation(), Largeur_ecran, Loupe_Mode, Menu_Ordonnee, Old_MX, Old_MY, Operation_avant_interruption, Pixel_Preview, Pixel_Preview_Normal, Principal_Decalage_X, Principal_Decalage_Y, Principal_Hauteur_image, and Principal_Largeur_image.
Referenced by Initialisation_des_boutons().
void Bouton_Snap_Mode (void)
References Afficher_curseur(), Calculer_coordonnees_pinceau(), Effacer_curseur, and Snap_Mode.
Referenced by Bouton_Effets(), Bouton_Menu_Grille(), and Gestion_principale().
void Bouton_Menu_Grille (void)
References Afficher_curseur(), BOUTON_AIDE, BOUTON_EFFETS, Bouton_Snap_Mode(), CM_Clair, CM_Fonce, Display_Window, Est_Raccourci(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fermer_fenetre(), Num2str(), Ouvrir_fenetre(), Print_dans_fenetre(), Readline(), Snap_Decalage_X, Snap_Decalage_Y, Snap_Hauteur, Snap_Largeur, Snap_Mode, Touche, and TOUCHE_ESC.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Brush_FX (void)
References Afficher_curseur(), Block, BOUTON_AIDE, BOUTON_EFFETS_BROSSE, Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, CM_Clair, CM_Fonce, CM_Noir, Config_Touche, Demarrer_pile_operation(), Desenclencher_bouton(), Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Flip_X_LOWLEVEL(), Flip_Y_LOWLEVEL(), Get_colors_from_brush(), Load_picture(), Menu_Facteur_X, Menu_Facteur_Y, Message_Non_disponible(), Nibble_brush(), OPERATION_ETIRER_BROSSE, OPERATION_TOURNER_BROSSE, Outline_brush(), Ouvrir_fenetre(), Pixel_dans_fenetre(), Print_dans_fenetre(), Remap_brosse(), Rotate_180_deg_LOWLEVEL(), Rotate_90_deg(), Save_picture(), SPECIAL_BOTTOM_LEFT_ATTACHMENT, SPECIAL_BOTTOM_RIGHT_ATTACHMENT, SPECIAL_CENTER_ATTACHMENT, SPECIAL_DISTORT, SPECIAL_FLIP_X, SPECIAL_FLIP_Y, SPECIAL_GET_BRUSH_COLORS, SPECIAL_LOAD_BRUSH, SPECIAL_NIBBLE, SPECIAL_OUTLINE, SPECIAL_RECOLORIZE_BRUSH, SPECIAL_ROTATE_180, SPECIAL_ROTATE_90, SPECIAL_ROTATE_ANY_ANGLE, SPECIAL_SAVE_BRUSH, SPECIAL_STRETCH, SPECIAL_TOP_LEFT_ATTACHMENT, SPECIAL_TOP_RIGHT_ATTACHMENT, Touche, and TOUCHE_ESC.
Referenced by Initialisation_des_boutons().
void Bouton_Smooth_Mode (void)
References Aucun_effet(), Colorize_Mode, Effet_Smooth(), Fonction_effet, Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, and Tiling_Mode.
Referenced by Bouton_Effets(), Bouton_Smooth_Menu(), and Gestion_principale().
void Bouton_Smooth_Menu (void)
References Afficher_curseur(), BOUTON_AIDE, BOUTON_EFFETS, Bouton_Smooth_Mode(), CM_Clair, CM_Noir, Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fermer_fenetre(), Num2str(), Ouvrir_fenetre(), Fenetre_Bouton_special::Pos_X, Fenetre_Bouton_special::Pos_Y, Print_char_dans_fenetre(), Readline(), Smooth_Matrice, Smooth_Mode, Touche, and TOUCHE_ESC.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Smear_Mode (void)
References Aucun_effet(), Colorize_Mode, Fonction_effet, Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, and Tiling_Mode.
Referenced by Bouton_Effets(), and Gestion_principale().
void Calculer_les_tables_de_Colorize (void)
References Colorize_Opacite, Table_de_multiplication_par_Facteur_A, and Table_de_multiplication_par_Facteur_B.
Referenced by Bouton_Colorize_Menu(), and Initialisation_du_programme().
void Bouton_Colorize_Mode (void)
References Aucun_effet(), Colorize_Mode, Colorize_Mode_en_cours, Effet_Colorize_additif(), Effet_Colorize_interpole(), Effet_Colorize_soustractif(), Fonction_effet, Quick_shade_Mode, Shade_Mode, Smooth_Mode, and Tiling_Mode.
Referenced by Bouton_Colorize_Menu(), Bouton_Effets(), and Gestion_principale().
void Bouton_Colorize_Afficher_la_selection (int Numero)
References CM_Clair, CM_Noir, Fenetre_Bouton_special::Pos_Y, and Print_dans_fenetre().
Referenced by Bouton_Colorize_Menu().
void Bouton_Colorize_Menu (void)
References Afficher_curseur(), BOUTON_AIDE, Bouton_Colorize_Afficher_la_selection(), Bouton_Colorize_Mode(), BOUTON_EFFETS, Calculer_les_tables_de_Colorize(), CM_Clair, CM_Fonce, Colorize_Mode, Colorize_Mode_en_cours, Colorize_Opacite, Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fenetre_Liste_boutons_special, Fermer_fenetre(), Num2str(), Ouvrir_fenetre(), Print_dans_fenetre(), Readline(), Touche, and TOUCHE_ESC.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Tiling_Mode (void)
References Aucun_effet(), Colorize_Mode, Effet_Tiling(), Fonction_effet, Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, and Tiling_Mode.
Referenced by Bouton_Effets(), Bouton_Tiling_Menu(), and Gestion_principale().
void Bouton_Tiling_Menu (void)
References Afficher_curseur(), BOUTON_AIDE, BOUTON_EFFETS, Bouton_Tiling_Mode(), Brosse_Hauteur, Brosse_Largeur, CM_Clair, CM_Fonce, Display_Window, Est_Raccourci(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_saisie(), Fermer_fenetre(), Num2str(), Ouvrir_fenetre(), Print_dans_fenetre(), Readline(), Tiling_Decalage_X, Tiling_Decalage_Y, Tiling_Mode, Touche, and TOUCHE_ESC.
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Courbes (void)
Callback for the curves button left click.
Start curve operation according to the selected mode.
References Afficher_curseur(), Courbe_en_cours, Demarrer_pile_operation(), and Effacer_curseur.
Referenced by Initialisation_des_boutons().
void Bouton_Courbes_Switch_mode (void)
Callback for the curves button right click.
Select the curve mode (1-point, 2-point)
References Afficher_curseur(), Afficher_sprite_dans_menu(), BOUTON_COURBES, Courbe_en_cours, Demarrer_pile_operation(), Effacer_curseur, OPERATION_COURBE_3_POINTS, and OPERATION_COURBE_4_POINTS.
Referenced by Initialisation_des_boutons().
void Bouton_Spray (void)
Callback for the spray button left click.
Start the spray operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_SPRAY.
Referenced by Initialisation_des_boutons().
void Spray_Rafficher_infos (byte Couleur_selectionnee, byte Rafficher_jauge)
References CM_Clair, CM_Noir, Fenetre_Dessiner_jauge(), Fenetre_Liste_boutons_palette, Fenetre_Liste_boutons_scroller, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Num2str(), Print_dans_fenetre(), Spray_Multi_flow, and UpdateRect().
Referenced by Bouton_Spray_Menu().
void Bouton_Spray_Menu (void)
Callback for the spray button right click.
Opens the spray's setup menu.
References A_GAUCHE, Afficher_curseur(), Attendre_fin_de_click(), BOUTON_AIDE, BOUTON_SPRAY, CM_Blanc, CM_Clair, CM_Fonce, CM_Noir, Display_Window, Effacer_curseur, Enclencher_bouton(), Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_palette(), Fenetre_Definir_bouton_saisie(), Fenetre_Definir_bouton_scroller(), Fenetre_Effacer_tags(), Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Fore_color, Lit_pixel, Menu_Facteur_X, Menu_Facteur_Y, Mouse_K, Mouse_X, Mouse_Y, Num2str(), Operation_en_cours, OPERATION_SPRAY, Ouvrir_fenetre(), Print_dans_fenetre(), Readline(), Recuperer_couleur_derriere_fenetre(), Spray_Delay, Spray_Mode, Spray_Mono_flow, Spray_Multi_flow, Spray_Rafficher_infos(), Spray_Size, Stencil_Actualiser_couleur(), Stencil_Tagger_couleur(), Touche, TOUCHE_ESC, and UpdateRect().
Referenced by Initialisation_des_boutons().
void Bouton_Trame_Mode (void)
References Trame_Mode.
Referenced by Bouton_Effets(), Bouton_Trame_Menu(), and Gestion_principale().
void Dessiner_trame_zoomee (short Orig_X, short Orig_Y)
References Block, CM_Blanc, CM_Clair, CM_Fonce, CM_Noir, Fenetre_Liste_boutons_special, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Pixel, Fenetre_Bouton_special::Pos_X, Fenetre_Bouton_special::Pos_Y, Trame, Trame_Hauteur, Trame_Largeur, and UpdateRect().
Referenced by Bouton_Trame_Menu().
void Dessiner_trames_predefinies (void)
References Block, CM_Blanc, CM_Noir, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Min(), ToWinH, ToWinL, ToWinX, ToWinY, TRAME_PREDEFINIE, UpdateRect(), and Zoom().
Referenced by Bouton_Trame_Menu().
void Copier_trame_predefinie (byte Indice)
References Trame, Trame_Hauteur, Trame_Largeur, and TRAME_PREDEFINIE.
Referenced by Bouton_Trame_Menu(), and Initialisation_du_programme().
void Inverser_trame (void)
References Fenetre_Bouton_special::Pos_X, Fenetre_Bouton_special::Pos_Y, Trame, Trame_Hauteur, and Trame_Largeur.
Referenced by Bouton_Trame_Menu(), and Gestion_principale().
void Mettre_a_jour_trame (short X, short Y)
References Menu_Facteur_X, Menu_Facteur_Y, and UpdateRect().
Referenced by Bouton_Trame_Menu().
void Bouton_Trame_Menu (void)
References A_GAUCHE, Afficher_curseur(), Back_color, Block, BOUTON_AIDE, BOUTON_EFFETS, Bouton_Trame_Mode(), Brosse, Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, Changer_la_forme_du_pinceau(), CM_Blanc, CM_Clair, CM_Fonce, CM_Noir, Copier_trame_predefinie(), Dessiner_trame_zoomee(), Dessiner_trames_predefinies(), Display_Window, Effacer_curseur, Est_Raccourci(), Fenetre_Afficher_cadre(), Fenetre_Afficher_cadre_creux(), Fenetre_aide(), Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_repetable(), Fenetre_Definir_bouton_special(), Fenetre_Liste_boutons_special, Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Fore_color, FORME_PINCEAU_BROSSE_COULEUR, Inverser_trame(), Lit_pixel_dans_brosse(), Menu_Facteur_X, Menu_Facteur_Y, Mettre_a_jour_trame(), MOD_SHIFT, Mouse_K, Mouse_X, Mouse_Y, Num2str(), Ouvrir_fenetre(), Pixel_dans_brosse(), Fenetre_Bouton_normal::Pos_X, Fenetre_Bouton_special::Pos_X, Fenetre_Bouton_normal::Pos_Y, Fenetre_Bouton_special::Pos_Y, Print_dans_fenetre(), Touche, TOUCHE_ESC, Trame, Trame_Hauteur, Trame_Largeur, Trame_Mode, and UpdateRect().
Referenced by Bouton_Effets(), and Gestion_principale().
void Bouton_Polygone (void)
Callback for the polyline button left click.
Starts drawing a polygon.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_POLYGONE.
Referenced by Initialisation_des_boutons().
void Bouton_Polyform (void)
Callback for the polyline right click.
Starts drawing a polyform.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_POLYFORM.
Referenced by Initialisation_des_boutons().
void Bouton_Polyfill (void)
Callback for the polyfill button left click.
Starts drawing a filled polygon.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_POLYFILL.
Referenced by Initialisation_des_boutons().
void Bouton_Filled_polyform (void)
Callback for the polyfill button right click.
Starts drawing a filled polyform.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_FILLED_POLYFORM.
Referenced by Initialisation_des_boutons().
void Bouton_Ajuster (void)
Callback for the adjust picture button.
Start the adjust picture operation.
References Afficher_curseur(), Demarrer_pile_operation(), Effacer_curseur, and OPERATION_SCROLL.
Referenced by Initialisation_des_boutons().
void Afficher_sprite_effet (short Numero_sprite, short Debut_X, short Debut_Y)
References HAUTEUR_SPRITE_MENU, LARGEUR_SPRITE_MENU, Menu_Facteur_X, Menu_Facteur_Y, Pixel_dans_fenetre(), Fenetre_Bouton_normal::Pos_X, Fenetre_Bouton_normal::Pos_Y, SPRITE_EFFET, ToWinX, ToWinY, and UpdateRect().
Referenced by Bouton_Effets().
void Afficher_etat_effet (short X, short Y, char * Libelle, byte Etat)
References Block, CM_Blanc, CM_Clair, CM_Noir, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, and Print_dans_fenetre().
Referenced by Afficher_etat_effets(), and Bouton_Effets().
void Afficher_etat_effets (void)
References Afficher_etat_effet(), Colorize_Mode, Mask_Mode, Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, Snap_Mode, Stencil_Mode, Tiling_Mode, and Trame_Mode.
Referenced by Bouton_Effets().
void Afficher_etat_feedback (void)
References CM_Clair, CM_Noir, Config, S_Config::FX_Feedback, and Print_dans_fenetre().
Referenced by Bouton_Effets().
void Bouton_Effets (void)
!!
References A_GAUCHE, Afficher_curseur(), Afficher_etat_effet(), Afficher_etat_effets(), Afficher_etat_feedback(), Afficher_sprite_effet(), Aucun_effet(), BOUTON_AIDE, Bouton_Colorize_Menu(), Bouton_Colorize_Mode(), BOUTON_EFFETS, Bouton_Mask_Menu(), Bouton_Mask_Mode(), Bouton_Menu_Grille(), Bouton_Menu_Stencil(), Bouton_Quick_shade_Menu(), Bouton_Quick_shade_Mode(), Bouton_Shade_Menu(), Bouton_Shade_Mode(), Bouton_Smear_Mode(), Bouton_Smooth_Menu(), Bouton_Smooth_Mode(), Bouton_Snap_Mode(), Bouton_Stencil_Mode(), Bouton_Tiling_Menu(), Bouton_Tiling_Mode(), Bouton_Trame_Menu(), Bouton_Trame_Mode(), CM_Clair, CM_Fonce, Colorize_Mode, Config, Config_Touche, Desenclencher_bouton(), Display_Window, Ecran_backup, Effacer_curseur, Est_Raccourci(), Fenetre_aide(), Fenetre_Attribut1, Fenetre_Bouton_clicke(), Fenetre_Definir_bouton_normal(), Fenetre_Numero_bouton_clicke(), Fermer_fenetre(), Fonction_effet, S_Config::FX_Feedback, FX_Feedback_Ecran, Mask_Mode, Ouvrir_fenetre(), Principal_Ecran, Print_dans_fenetre(), Quick_shade_Mode, Shade_Mode, Smear_Mode, Smooth_Mode, Snap_Mode, SPECIAL_COLORIZE_MODE, SPECIAL_GRID_MODE, SPECIAL_MASK_MODE, SPECIAL_QUICK_SHADE_MODE, SPECIAL_SHADE_MODE, SPECIAL_SIEVE_MODE, SPECIAL_SMEAR_MODE, SPECIAL_SMOOTH_MODE, SPECIAL_STENCIL_MODE, SPECIAL_TILING_MODE, Stencil_Mode, Tiling_Mode, Touche, TOUCHE_ESC, and Trame_Mode.
Referenced by Initialisation_des_boutons().
void Dessiner_selecteur_fontes (short X, short Y, short Debut_liste, short Position_curseur, short Nombre_visibles)
References CM_Clair, CM_Fonce, CM_Noir, Libelle_fonte(), and Print_dans_fenetre().
Referenced by Bouton_Texte().
void Bouton_Texte (void)
Callback for the text button.
Opens the text setup window.
References A_DROITE, A_GAUCHE, Affiche_brosse, Afficher_curseur(), S_Config::Auto_discontinuous, Back_color, Block, BOUTON_AIDE, BOUTON_DESSIN, BOUTON_TEXTE, Brosse, Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, Changer_la_forme_du_pinceau(), CM_Clair, CM_Fonce, CM_Noir, Config, Desenclencher_bouton(), Dessiner_selecteur_fontes(), Display_Window, Effacer_curseur, Enclencher_bouton(), Erreur, Est_Raccourci(), Fenetre_Afficher_cadre_creux(), Fenetre_aide(), Fenetre_Attribut2, Fenetre_Bouton_clicke(), Fenetre_Contenu_bouton_saisie(), Fenetre_Definir_bouton_normal(), Fenetre_Definir_bouton_repetable(), Fenetre_Definir_bouton_saisie(), Fenetre_Definir_bouton_scroller(), Fenetre_Definir_bouton_special(), Fenetre_Dessiner_jauge(), Fenetre_Pos_X, Fenetre_Pos_Y, Fermer_fenetre(), Fonte_nombre, FORME_PINCEAU_BROSSE_COULEUR, FORME_PINCEAU_BROSSE_MONOCHROME, Fenetre_Bouton_special::Hauteur, Fenetre_Bouton_special::Largeur, Menu_Facteur_X, Menu_Facteur_Y, Min(), Mouse_Y, Num2str(), OPERATION_DESSIN_DISCONTINU, Operation_en_cours, Ouvrir_fenetre(), Fenetre_Bouton_special::Pos_X, Fenetre_Bouton_special::Pos_Y, Fenetre_Bouton_scroller::Position, Position_curseur, Print_dans_fenetre(), Readline(), Readline_ex(), Rendu_Texte(), Touche, TOUCHE_ESC, TOUCHE_MOUSEWHEELDOWN, TOUCHE_MOUSEWHEELUP, TrueType_fonte(), and UpdateRect().
Referenced by Initialisation_des_boutons().
Variable Documentation
short Old_MX
Referenced by Bouton_desenclencher_Loupe(), Fermer_fenetre(), Fermer_popup(), and Gestion_principale().
short Old_MY
Referenced by Bouton_desenclencher_Loupe(), Fermer_fenetre(), Fermer_popup(), and Gestion_principale().
int Type_selectionne
char FFF_Meilleur_nom[TAILLE_CHEMIN_FICHIER]
byte On_vient_du_menu_de_facteurs_de_zoom = 0
byte Smooth_Matrice_defaut[4][3][3]
Initial value:
{
 { {1,2,1}, {2,4,2}, {1,2,1} },
 { {1,3,1}, {3,9,3}, {1,3,1} },
 { {0,1,0}, {1,2,1}, {0,1,0} },
 { {2,3,2}, {3,1,3}, {2,3,2} }
}