GrafX2: brush.h File Reference
brush.h File Reference
Actions on the brush.
#include "struct.h"
Functions
void Capture_brush (short start_x, short start_y, short end_x, short end_y, short clear)
Gets the brush from the picture.
void Rotate_90_deg (void)
Rotates the brush to the right.
void Stretch_brush (short x1, short y1, short x2, short y2)
Stretch the brush to fit the given rectangle.
void Stretch_brush_preview (short x1, short y1, short x2, short y2)
Stretch the brush to fit the given rectangle.
void Rotate_brush (float angle)
Rotates the brush to the right from the given angle.
void Rotate_brush_preview (float angle)
Stretch the brush to fit the given rectangle.
void Distort_brush_preview (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4)
Remap the brush palette to the nearest color in the picture one.
void Distort_brush (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4)
Replace the brush by a distorted version of itself.
void Remap_brush (void)
void Get_colors_from_brush (void)
Get color indexes used by the brush.
void Outline_brush (void)
Outline the brush, add 1 foreground-colored pixel on the edges.
void Nibble_brush (void)
Nibble the brush, remove 1 pixel on the edges and make it transparent (ie filled with back color).
void Capture_brush_with_lasso (int vertices, short *points, short clear)
Get brush from picture according to a freehand form.
byte Realloc_brush (word new_brush_width, word new_brush_height)
Changes the Brush size, discarding its previous content.
Detailed Description
Actions on the brush.
Function Documentation
void Capture_brush (short start_x, short start_y, short end_x, short end_y, short clear)
Gets the brush from the picture.
Parameters:
start_x left edge coordinate in the picture
start_y upper edge coordinate in the picture
end_x right edge coordinate in the picture
end_y bottom edge coordinate in the picture
clear If 1, the area is also cleared from the picture.
References Back_color, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, Copy_image_to_brush(), Main_image_height, Main_image_width, Pixel_in_current_screen(), Pixel_preview, Realloc_brush(), Tiling_offset_X, Tiling_offset_Y, Update_part_of_screen(), and word.
Referenced by Brush_0_5(), and Init_program().
void Rotate_90_deg (void)
Rotates the brush to the right.
References Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Error, Rotate_90_deg_lowlevel(), Smear_brush_height, and Smear_brush_width.
Referenced by Button_Brush_FX(), and Main_handler().
void Stretch_brush (short x1, short y1, short x2, short y2)
Stretch the brush to fit the given rectangle.
References Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Error, MAX_PAINTBRUSH_SIZE, Rescale(), Smear_brush, Smear_brush_height, and Smear_brush_width.
Referenced by Stretch_brush_2_7().
void Stretch_brush_preview (short x1, short y1, short x2, short y2)
Stretch the brush to fit the given rectangle.
Uses fast approximation for the preview while drawing the rectangle on screen.
References Back_color, Brush_height, Brush_width, byte, Limit_left, Limit_top, Limit_visible_bottom, Limit_visible_right, Max(), Min(), Pixel_preview, Read_pixel_from_brush(), and Update_part_of_screen().
Referenced by Stretch_brush_0_7(), and Stretch_brush_1_7().
void Rotate_brush (float angle)
Rotates the brush to the right from the given angle.
References Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Compute_quad_texture(), Error, Max(), MAX_PAINTBRUSH_SIZE, Min(), Smear_brush, Smear_brush_height, Smear_brush_width, and Transform_point().
Referenced by Rotate_brush_2_5().
void Rotate_brush_preview (float angle)
Stretch the brush to fit the given rectangle.
Uses fast approximation for the preview while changing the angle.
References Brush_height, Brush_rotation_center_X, Brush_rotation_center_Y, Brush_width, Draw_quad_texture_preview(), Max(), Min(), Transform_point(), and Update_part_of_screen().
Referenced by Rotate_brush_0_5(), and Rotate_brush_1_5().
void Distort_brush_preview (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4)
Remap the brush palette to the nearest color in the picture one.
Used when switching to the spare page.
Distort the brush on the screen.
References Brush_height, Brush_width, Draw_brush_linear_distort(), Pixel_figure_preview(), and Pixel_for_distort.
Referenced by Distort_brush_1_0(), and Distort_brush_1_9().
void Distort_brush (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4)
Replace the brush by a distorted version of itself.
References Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Distort_buffer, Distort_buffer_width, Draw_brush_linear_distort(), Error, Max(), Max4(), MAX_PAINTBRUSH_SIZE, Min4(), Pixel_for_distort, Pixel_in_distort_buffer(), Smear_brush, Smear_brush_height, and Smear_brush_width.
Referenced by Distort_brush_2_8().
void Remap_brush (void)
References Back_color, Best_color(), Brush, Brush_height, Brush_width, byte, Read_pixel_from_brush(), Remap_general_lowlevel(), and Spare_palette.
Referenced by Button_Brush_FX(), and Main_handler().
void Get_colors_from_brush (void)
Get color indexes used by the brush.
References Backup(), Brush_height, Brush_width, byte, Compute_optimal_menu_colors(), Confirmation_box(), Display_all_screen(), Display_cursor(), Display_menu(), End_of_modification(), Hide_cursor, Main_image_is_modified, Main_palette, Read_pixel_from_brush(), Set_palette(), and Spare_palette.
Referenced by Button_Brush_FX(), and Main_handler().
void Outline_brush (void)
Outline the brush, add 1 foreground-colored pixel on the edges.
Edges are detected considering the backcolor as transparent.
References Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Copy_part_of_image_to_another(), Error, Fore_color, MAX_PAINTBRUSH_SIZE, Pixel_in_brush(), Smear_brush, Smear_brush_height, Smear_brush_width, and word.
Referenced by Button_Brush_FX(), and Main_handler().
void Nibble_brush (void)
Nibble the brush, remove 1 pixel on the edges and make it transparent (ie filled with back color).
Edges are detected considering the backcolor as transparent.
References Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Copy_part_of_image_to_another(), Error, MAX_PAINTBRUSH_SIZE, Pixel_in_brush(), Smear_brush, Smear_brush_height, Smear_brush_width, and word.
Referenced by Button_Brush_FX(), and Main_handler().
void Capture_brush_with_lasso (int vertices, short * points, short clear)
Get brush from picture according to a freehand form.
Parameters:
vertices number of points in the freehand form
points array of points coordinates
clear If set to 1, the captured area is also cleared from the picture.
References Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Draw_line_general(), Error, ERROR_MEMORY, Fore_color, Limit_bottom, Limit_left, Limit_right, Limit_top, Main_image_height, Main_image_width, MAX_PAINTBRUSH_SIZE, Pixel_figure, Pixel_figure_in_brush(), Pixel_in_brush(), Pixel_in_current_screen(), Polyfill_general(), Read_pixel_from_brush(), Read_pixel_from_current_screen(), Smear_brush, Smear_brush_height, Smear_brush_width, Tiling_offset_X, Tiling_offset_Y, and word.
Referenced by Polybrush_12_8().
byte Realloc_brush (word new_brush_width, word new_brush_height)
Changes the Brush size, discarding its previous content.
Returns:
0 OK, 1 Failed
References Brush, Brush_height, Brush_width, byte, Error, ERROR_MEMORY, Fore_color, MAX_PAINTBRUSH_SIZE, Smear_brush, Smear_brush_height, and Smear_brush_width.
Referenced by Capture_brush(), and Restore_brush().