GrafX2: brush.c File Reference
brush.c File Reference
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "global.h"
#include "graph.h"
#include "misc.h"
#include "errors.h"
#include "windows.h"
#include "sdlscreen.h"
#include "brush.h"
Defines
#define UNDEFINED (-1.0e20F)
Functions
void Compute_clipped_dimensions (short *x, short *y, short *width, short *height)
void Compute_clipped_dimensions_zoom (short *x, short *y, short *width, short *height)
void Display_paintbrush (short x, short y, byte color, byte is_preview)
byte Realloc_brush (word new_brush_width, word new_brush_height)
Changes the Brush size, discarding its previous content.
void Hide_paintbrush (short x, short y)
void Capture_brush (short start_x, short start_y, short end_x, short end_y, short clear)
Gets the brush from the picture.
void Rotate_90_deg ()
Rotates the brush to the right.
void Remap_brush (void)
void Outline_brush (void)
Outline the brush, add 1 foreground-colored pixel on the edges.
void Nibble_brush (void)
Nibble the brush, remove 1 pixel on the edges and make it transparent (ie filled with back color).
void Capture_brush_with_lasso (int vertices, short *points, short clear)
Get brush from picture according to a freehand form.
void Stretch_brush (short x1, short y1, short x2, short y2)
Stretch the brush to fit the given rectangle.
void Stretch_brush_preview (short x1, short y1, short x2, short y2)
Stretch the brush to fit the given rectangle.
int Min4 (long int a, long int b, long int c, long int d)
Returns the minimum of 4 integers.
void Pixel_in_distort_buffer (word x_pos, word y_pos, byte color)
Draw a pixel in the target buffer. No clipping.
int Max4 (long int a, long int b, long int c, long int d)
Returns the maximum of 4 integers.
void Draw_brush_linear_distort (unsigned long int tex_min_x, unsigned long int tex_min_y, unsigned long int tex_max_x, unsigned long int tex_max_y, long int x1, long int y1, long int x2, long int y2, long int x3, long int y3, long int x4, long int y4)
void Distort_brush_preview (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4)
Draws a distorted version of the brush, mapped over the given quad (picture coordinates).
void Distort_brush (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4)
Modifies the current brush, mapping it over the given quad.
void Interpolate_texture (int start_x, int start_y, int xt1, int yt1, int end_x, int end_y, int xt2, int yt2, int height)
void Compute_quad_texture (int x1, int y1, int xt1, int yt1, int x2, int y2, int xt2, int yt2, int x3, int y3, int xt3, int yt3, int x4, int y4, int xt4, int yt4, byte *buffer, int width, int height)
void Rotate_brush (float angle)
Rotates the brush to the right from the given angle.
void Draw_quad_texture_preview (int x1, int y1, int xt1, int yt1, int x2, int y2, int xt2, int yt2, int x3, int y3, int xt3, int yt3, int x4, int y4, int xt4, int yt4)
void Rotate_brush_preview (float angle)
Stretch the brush to fit the given rectangle.
Variables
static Func_pixel Pixel_for_distort
static byte * Distort_buffer
static short Distort_buffer_width
float * ScanY_Xt [2]
float * ScanY_Yt [2]
float * ScanY_X [2]
Define Documentation
#define UNDEFINED (-1.0e20F)
Referenced by Compute_quad_texture(), Draw_quad_texture_preview(), and Interpolate_texture().
Function Documentation
void Compute_clipped_dimensions (short * x, short * y, short * width, short * height)
References Limit_bottom, Limit_left, Limit_right, and Limit_top.
Referenced by Display_paintbrush(), and Hide_paintbrush().
void Compute_clipped_dimensions_zoom (short * x, short * y, short * width, short * height)
References Limit_bottom_zoom, Limit_left_zoom, Limit_right_zoom, and Limit_top_zoom.
Referenced by Display_paintbrush(), and Hide_paintbrush().
void Display_paintbrush (short x, short y, byte color, byte is_preview)
References Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Compute_clipped_dimensions(), Compute_clipped_dimensions_zoom(), Copy_part_of_image_to_another(), Display_brush_color, Display_brush_color_zoom, Display_brush_mono, Display_brush_mono_zoom, Display_pixel(), Fore_color, Horizontal_line_buffer, Limit_bottom, Limit_left, Limit_right, Limit_top, Main_image_width, Main_magnifier_factor, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_offset_X, Main_offset_Y, Main_screen, Main_X_zoom, MAX_PAINTBRUSH_SIZE, Menu_Y, Mouse_K, Paintbrush_height, Paintbrush_offset_X, Paintbrush_offset_Y, Paintbrush_shape, PAINTBRUSH_SHAPE_COLOR_BRUSH, PAINTBRUSH_SHAPE_MONO_BRUSH, PAINTBRUSH_SHAPE_POINT, Paintbrush_sprite, Paintbrush_width, Paintbrush_X, Paintbrush_Y, Pixel_preview, Read_pixel_from_brush(), Read_pixel_from_current_screen(), Shade_table, Shade_table_left, Smear_brush, Smear_brush_width, Smear_max_X, Smear_max_Y, Smear_min_X, Smear_min_Y, Smear_mode, Smear_start, and Update_part_of_screen().
Referenced by Airbrush(), Centered_lines_12_7(), Display_cursor(), Freehand_mode1_1_0(), Freehand_mode1_2_0(), Freehand_mode2_1_0(), Freehand_mode2_1_2(), Freehand_mode2_2_0(), Freehand_mode2_2_2(), Freehand_mode3_1_0(), Freehand_Mode3_2_0(), K_line_0_6(), Line_0_5(), Pixel_figure_permanent(), and Polyform_12_0().
byte Realloc_brush (word new_brush_width, word new_brush_height)
Changes the Brush size, discarding its previous content.
Returns:
0 OK, 1 Failed
References Brush, Brush_height, Brush_width, byte, Error, ERROR_MEMORY, Fore_color, MAX_PAINTBRUSH_SIZE, Smear_brush, Smear_brush_height, and Smear_brush_width.
Referenced by Capture_brush(), and Restore_brush().
void Hide_paintbrush (short x, short y)
References Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Clear_brush, Clear_brush_scaled, Compute_clipped_dimensions(), Compute_clipped_dimensions_zoom(), Horizontal_line_buffer, Limit_bottom, Limit_left, Limit_right, Limit_top, Main_image_width, Main_magnifier_factor, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_offset_X, Main_offset_Y, Main_X_zoom, Menu_Y, Mouse_K, Paintbrush_height, Paintbrush_offset_X, Paintbrush_offset_Y, Paintbrush_shape, PAINTBRUSH_SHAPE_COLOR_BRUSH, PAINTBRUSH_SHAPE_MONO_BRUSH, PAINTBRUSH_SHAPE_POINT, Paintbrush_sprite, Paintbrush_width, Paintbrush_X, Paintbrush_Y, Pixel_preview, Read_pixel_from_current_screen(), and Update_part_of_screen().
Referenced by Hide_cursor().
void Capture_brush (short start_x, short start_y, short end_x, short end_y, short clear)
Gets the brush from the picture.
Parameters:
start_x left edge coordinate in the picture
start_y upper edge coordinate in the picture
end_x right edge coordinate in the picture
end_y bottom edge coordinate in the picture
clear If 1, the area is also cleared from the picture.
References Back_color, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, Copy_image_to_brush(), Main_image_height, Main_image_width, Pixel_in_current_screen(), Realloc_brush(), Tiling_offset_X, Tiling_offset_Y, Update_part_of_screen(), and word.
Referenced by Brush_0_5(), and Init_program().
void Rotate_90_deg (void)
Rotates the brush to the right.
References Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Error, Rotate_90_deg_lowlevel(), Smear_brush_height, and Smear_brush_width.
Referenced by Button_Brush_FX(), and Main_handler().
void Remap_brush (void)
References Back_color, Best_color(), Brush, Brush_height, Brush_width, byte, Read_pixel_from_brush(), Remap_general_lowlevel(), and Spare_palette.
Referenced by Button_Brush_FX(), and Main_handler().
void Outline_brush (void)
Outline the brush, add 1 foreground-colored pixel on the edges.
Edges are detected considering the backcolor as transparent.
References Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Copy_part_of_image_to_another(), Error, Fore_color, MAX_PAINTBRUSH_SIZE, Pixel_in_brush(), Smear_brush, Smear_brush_height, Smear_brush_width, and word.
Referenced by Button_Brush_FX(), and Main_handler().
void Nibble_brush (void)
Nibble the brush, remove 1 pixel on the edges and make it transparent (ie filled with back color).
Edges are detected considering the backcolor as transparent.
References Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Copy_part_of_image_to_another(), Error, MAX_PAINTBRUSH_SIZE, Pixel_in_brush(), Smear_brush, Smear_brush_height, Smear_brush_width, and word.
Referenced by Button_Brush_FX(), and Main_handler().
void Capture_brush_with_lasso (int vertices, short * points, short clear)
Get brush from picture according to a freehand form.
Parameters:
vertices number of points in the freehand form
points array of points coordinates
clear If set to 1, the captured area is also cleared from the picture.
References Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Draw_line_general(), Error, ERROR_MEMORY, Fore_color, Limit_bottom, Limit_left, Limit_right, Limit_top, Main_image_height, Main_image_width, MAX_PAINTBRUSH_SIZE, Pixel_figure, Pixel_figure_in_brush(), Pixel_in_brush(), Pixel_in_current_screen(), Polyfill_general(), Read_pixel_from_brush(), Read_pixel_from_current_layer(), Smear_brush, Smear_brush_height, Smear_brush_width, Tiling_offset_X, Tiling_offset_Y, and word.
Referenced by Polybrush_12_8().
void Stretch_brush (short x1, short y1, short x2, short y2)
Stretch the brush to fit the given rectangle.
References Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Error, MAX_PAINTBRUSH_SIZE, Rescale(), Smear_brush, Smear_brush_height, and Smear_brush_width.
Referenced by Stretch_brush_2_7().
void Stretch_brush_preview (short x1, short y1, short x2, short y2)
Stretch the brush to fit the given rectangle.
Uses fast approximation for the preview while drawing the rectangle on screen.
References Back_color, Brush_height, Brush_width, byte, Limit_left, Limit_top, Limit_visible_bottom, Limit_visible_right, Max(), Min(), Pixel_preview, Read_pixel_from_brush(), and Update_part_of_screen().
Referenced by Stretch_brush_0_7(), and Stretch_brush_1_7().
int Min4 (long int a, long int b, long int c, long int d)
Returns the minimum of 4 integers.
Referenced by Distort_brush(), and Draw_brush_linear_distort().
void Pixel_in_distort_buffer (word x_pos, word y_pos, byte color)
Draw a pixel in the target buffer. No clipping.
References Distort_buffer, and Distort_buffer_width.
Referenced by Distort_brush().
int Max4 (long int a, long int b, long int c, long int d)
Returns the maximum of 4 integers.
Referenced by Distort_brush(), and Draw_brush_linear_distort().
void Draw_brush_linear_distort (unsigned long int tex_min_x, unsigned long int tex_min_y, unsigned long int tex_max_x, unsigned long int tex_max_y, long int x1, long int y1, long int x2, long int y2, long int x3, long int y3, long int x4, long int y4)
References Back_color, byte, Max4(), Min4(), Pixel_for_distort, and Read_pixel_from_brush().
Referenced by Distort_brush(), and Distort_brush_preview().
void Distort_brush_preview (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4)
Draws a distorted version of the brush, mapped over the given quad (picture coordinates).
Remap the brush palette to the nearest color in the picture one.
References Brush_height, Brush_width, Draw_brush_linear_distort(), Pixel_figure_preview(), and Pixel_for_distort.
Referenced by Distort_brush_1_0(), and Distort_brush_1_9().
void Distort_brush (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4)
Modifies the current brush, mapping it over the given quad.
Replace the brush by a distorted version of itself.
References Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Distort_buffer, Distort_buffer_width, Draw_brush_linear_distort(), Error, Max(), Max4(), MAX_PAINTBRUSH_SIZE, Min4(), Pixel_for_distort, Pixel_in_distort_buffer(), Smear_brush, Smear_brush_height, and Smear_brush_width.
Referenced by Distort_brush_2_8().
void Interpolate_texture (int start_x, int start_y, int xt1, int yt1, int end_x, int end_y, int xt2, int yt2, int height)
References ScanY_X, ScanY_Xt, ScanY_Yt, and UNDEFINED.
Referenced by Compute_quad_texture(), and Draw_quad_texture_preview().
void Compute_quad_texture (int x1, int y1, int xt1, int yt1, int x2, int y2, int xt2, int yt2, int x3, int y3, int xt3, int yt3, int x4, int y4, int xt4, int yt4, byte * buffer, int width, int height)
References Back_color, Interpolate_texture(), Min(), Read_pixel_from_brush(), Round(), ScanY_X, ScanY_Xt, ScanY_Yt, and UNDEFINED.
Referenced by Rotate_brush().
void Rotate_brush (float angle)
Rotates the brush to the right from the given angle.
References Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Compute_quad_texture(), Error, Max(), MAX_PAINTBRUSH_SIZE, Min(), Smear_brush, Smear_brush_height, Smear_brush_width, and Transform_point().
Referenced by Rotate_brush_2_5().
void Draw_quad_texture_preview (int x1, int y1, int xt1, int yt1, int x2, int y2, int xt2, int yt2, int x3, int y3, int xt3, int yt3, int x4, int y4, int xt4, int yt4)
References Back_color, byte, Interpolate_texture(), Limit_bottom, Limit_left, Limit_right, Limit_top, Max(), Min(), Pixel_preview, Read_pixel_from_brush(), Round(), ScanY_X, ScanY_Xt, ScanY_Yt, and UNDEFINED.
Referenced by Rotate_brush_preview().
void Rotate_brush_preview (float angle)
Stretch the brush to fit the given rectangle.
Uses fast approximation for the preview while changing the angle.
References Brush_height, Brush_rotation_center_X, Brush_rotation_center_Y, Brush_width, Draw_quad_texture_preview(), Max(), Min(), Transform_point(), and Update_part_of_screen().
Referenced by Rotate_brush_0_5(), and Rotate_brush_1_5().
Variable Documentation
Func_pixel Pixel_for_distort [static]
Referenced by Distort_brush(), Distort_brush_preview(), and Draw_brush_linear_distort().
byte* Distort_buffer [static]
Referenced by Distort_brush(), and Pixel_in_distort_buffer().
short Distort_buffer_width [static]
Referenced by Distort_brush(), and Pixel_in_distort_buffer().
float* ScanY_Xt[2]
Referenced by Compute_quad_texture(), Draw_quad_texture_preview(), and Interpolate_texture().
float* ScanY_Yt[2]
Referenced by Compute_quad_texture(), Draw_quad_texture_preview(), and Interpolate_texture().
float* ScanY_X[2]
Referenced by Compute_quad_texture(), Draw_quad_texture_preview(), and Interpolate_texture().
Generated for GrafX2 by