GrafX2: buttons_effects.c File Reference
buttons_effects.c File Reference
Handles all the effects buttons and setup windows in the effects menu.
#include <SDL.h>
#include <stdlib.h>
#include <string.h>
#include "buttons.h"
#include "engine.h"
#include "global.h"
#include "graph.h"
#include "help.h"
#include "input.h"
#include "misc.h"
#include "readline.h"
#include "sdlscreen.h"
#include "struct.h"
#include "windows.h"
Functions
void Menu_tag_colors (char *window_title, byte *table, byte *mode, byte can_cancel, const char *help_section, word close_shortcut)
Generic color tagging menu, for various effects.
void Button_Stencil_mode (void)
Callback for the Stencil button (in the FX window) left click.
void Stencil_tag_color (byte color, byte tag_color)
void Stencil_update_color (byte color)
void Button_Stencil_menu (void)
Callback for the Stencil button (in the FX window) right click.
void Button_Mask_mode (void)
Callback for the Mask button (in the FX window) left click.
void Button_Mask_menu (void)
Callback for the Mask button (in the FX window) right click.
void Button_Snap_mode (void)
Callback for the Grid button (in the FX window) left click.
void Button_Grid_menu (void)
Callback for the Grid button (in the FX window) right click.
void Button_Show_grid (void)
Callback to toggle the grid visible in the magnified view.
void Button_Smooth_mode (void)
Callback for the smooth button (in the FX window) left click.
void Button_Smooth_menu (void)
Display the menu for the smooth effect.
void Button_Smear_mode (void)
Toogles the smear mode.
void Compute_colorize_table (void)
Computes the tables used by the transparency/colorize mode.
void Button_Colorize_mode (void)
Callback for the Tranparency button (in the FX window) left click.
void Button_Colorize_display_selection (int mode)
void Button_Colorize_menu (void)
Callback for the Transparency button (in the FX window) right click.
void Button_Tiling_mode (void)
Callback for the Tiling button (in the FX window) left click.
void Button_Tiling_menu (void)
Callback for the Tiling button (in the FX window) right click.
void Effects_off (void)
Callback for the command that turns off all drawaing effects.
void Button_Sieve_mode (void)
Callback for the Sieve button (in the FX window) left click.
void Draw_sieve_scaled (short origin_x, short origin_y)
void Draw_preset_sieve_patterns (void)
void Copy_preset_sieve (byte index)
In the sieve window, copy one of the presets patterns to the current one.
void Invert_trame (void)
In the sieve window, swaps black and white in the current pattern.
void Update_sieve_area (short x, short y)
void Button_Sieve_menu (void)
Callback for the Sieve button (in the FX window) right click.
Variables
byte Smooth_default_matrices [4][3][3]
Detailed Description
Handles all the effects buttons and setup windows in the effects menu.
Function Documentation
void Menu_tag_colors (char * window_title, byte * table, byte * mode, byte can_cancel, const char * help_section, word close_shortcut)
Generic color tagging menu, for various effects.
References BUTTON_EFFECTS, BUTTON_HELP, byte, Close_window(), Display_cursor(), Get_color_behind_window(), Hide_cursor, Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, MC_Black, MC_Light, Mouse_K, Mouse_X, Mouse_Y, Open_window(), Read_pixel, Stencil_tag_color(), Stencil_update_color(), Update_window_area, Wait_end_of_click(), Window_attribute2, Window_clicked_button(), Window_height, Window_help(), Window_set_normal_button(), Window_set_palette_button(), Window_width, and word.
Referenced by Button_Mask_menu(), Button_Secondary_palette(), Button_Stencil_menu(), Copy_some_colors(), and Main_handler().
void Button_Stencil_mode (void)
Callback for the Stencil button (in the FX window) left click.
Toogle stencil mode.
References Stencil_mode.
Referenced by Button_Effects(), and Main_handler().
void Stencil_tag_color (byte color, byte tag_color)
References Block, Menu_factor_X, Menu_factor_Y, Window_palette_button_list, Window_pos_X, and Window_pos_Y.
Referenced by Button_Airbrush_menu(), and Menu_tag_colors().
void Stencil_update_color (byte color)
References Menu_factor_X, Menu_factor_Y, Update_rect(), Window_palette_button_list, Window_pos_X, and Window_pos_Y.
Referenced by Button_Airbrush_menu(), and Menu_tag_colors().
void Button_Stencil_menu (void)
Callback for the Stencil button (in the FX window) right click.
Displays the stencil setup menu.
References Menu_tag_colors(), SPECIAL_STENCIL_MENU, Stencil, and Stencil_mode.
Referenced by Button_Effects(), and Main_handler().
void Button_Mask_mode (void)
Callback for the Mask button (in the FX window) left click.
Toogles the mask mode/
References Mask_mode.
Referenced by Button_Effects(), and Main_handler().
void Button_Mask_menu (void)
Callback for the Mask button (in the FX window) right click.
Displays the mask setup menu.
References Mask_mode, Mask_table, Menu_tag_colors(), and SPECIAL_MASK_MENU.
Referenced by Button_Effects(), and Main_handler().
void Button_Snap_mode (void)
Callback for the Grid button (in the FX window) left click.
Toogle the grid.
References Compute_paintbrush_coordinates(), Display_cursor(), Hide_cursor, and Snap_mode.
Referenced by Button_Effects(), and Main_handler().
void Button_Grid_menu (void)
Callback for the Grid button (in the FX window) right click.
Displays the grid setup menu.
References BUTTON_EFFECTS, BUTTON_HELP, Close_window(), Display_cursor(), Hide_cursor, INPUT_TYPE_INTEGER, Is_shortcut(), Key, KEY_ESC, MC_Black, MC_Dark, MC_Light, Num2str, Open_window(), Print_in_window(), Readline(), Show_grid, Snap_height, Snap_mode, Snap_offset_X, Snap_offset_Y, Snap_width, Update_window_area, Window_clicked_button(), Window_height, Window_help(), Window_input_content(), Window_set_input_button(), Window_set_normal_button(), Window_width, and word.
Referenced by Button_Effects(), and Main_handler().
void Button_Show_grid (void)
Callback to toggle the grid visible in the magnified view.
References Display_all_screen(), Display_cursor(), Hide_cursor, and Show_grid.
Referenced by Main_handler().
void Button_Smooth_mode (void)
Callback for the smooth button (in the FX window) left click.
Callback for the Smooth button (in the FX window) right click.
Toogles smooth mode.
Displays the smooth setup menu.
References Colorize_mode, Effect_function, Effect_smooth(), No_effect(), Quick_shade_mode, Shade_mode, Smear_mode, Smooth_mode, and Tiling_mode.
Referenced by Button_Effects(), Button_Smooth_menu(), and Main_handler().
void Button_Smooth_menu (void)
Display the menu for the smooth effect.
References BUTTON_EFFECTS, BUTTON_HELP, Button_Smooth_mode(), byte, Close_window(), Display_cursor(), Hide_cursor, INPUT_TYPE_INTEGER, Is_shortcut(), Key, KEY_ESC, MC_Black, MC_Light, Num2str, Open_window(), Print_char_in_window(), Readline(), Smooth_default_matrices, Smooth_matrix, Smooth_mode, SPECIAL_SMOOTH_MENU, Update_window_area, Window_clicked_button(), Window_display_frame(), Window_height, Window_help(), Window_input_content(), Window_set_input_button(), Window_set_normal_button(), Window_width, and word.
Referenced by Button_Effects(), and Main_handler().
void Button_Smear_mode (void)
Toogles the smear mode.
References Colorize_mode, Effect_function, No_effect(), Quick_shade_mode, Shade_mode, Smear_mode, Smooth_mode, and Tiling_mode.
Referenced by Button_Effects(), and Main_handler().
void Compute_colorize_table (void)
Computes the tables used by the transparency/colorize mode.
These tables are used to match the drawing color*picture color to the color that is painted on screen.
References Colorize_opacity, Factors_inv_table, Factors_table, and word.
Referenced by Button_Colorize_menu(), Init_program(), and Transparency_set().
void Button_Colorize_mode (void)
Callback for the Tranparency button (in the FX window) left click.
Toogles transparent drawing mode.
References Colorize_current_mode, Colorize_mode, Effect_additive_colorize(), Effect_alpha_colorize(), Effect_function, Effect_interpolated_colorize(), Effect_substractive_colorize(), No_effect(), Quick_shade_mode, Shade_mode, Smooth_mode, and Tiling_mode.
Referenced by Button_Colorize_menu(), Button_Effects(), and Main_handler().
void Button_Colorize_display_selection (int mode)
References MC_Black, MC_Light, and Print_in_window().
Referenced by Button_Colorize_menu().
void Button_Colorize_menu (void)
Callback for the Transparency button (in the FX window) right click.
Displays the tranparency setup menu.
References Button_Colorize_display_selection(), Button_Colorize_mode(), BUTTON_EFFECTS, BUTTON_HELP, Close_window(), Colorize_current_mode, Colorize_mode, Colorize_opacity, Compute_colorize_table(), Display_cursor(), Hide_cursor, INPUT_TYPE_INTEGER, Is_shortcut(), Key, KEY_ESC, MC_Dark, MC_Light, Num2str, Open_window(), Print_in_window(), Readline(), SPECIAL_COLORIZE_MENU, Update_window_area, Window_clicked_button(), Window_display_frame(), Window_height, Window_help(), Window_input_content(), Window_set_input_button(), Window_set_normal_button(), Window_special_button_list, and Window_width.
Referenced by Button_Effects(), and Main_handler().
void Button_Tiling_mode (void)
Callback for the Tiling button (in the FX window) left click.
Toogles tiling mode.
References Colorize_mode, Effect_function, Effect_tiling(), No_effect(), Quick_shade_mode, Shade_mode, Smear_mode, Smooth_mode, and Tiling_mode.
Referenced by Button_Effects(), Button_Tiling_menu(), and Main_handler().
void Button_Tiling_menu (void)
Callback for the Tiling button (in the FX window) right click.
Displays the tiling setup menu.
References Brush_height, Brush_width, BUTTON_EFFECTS, BUTTON_HELP, Button_Tiling_mode(), Close_window(), Display_cursor(), INPUT_TYPE_INTEGER, Is_shortcut(), Key, KEY_ESC, MC_Dark, MC_Light, Num2str, Open_window(), Print_in_window(), Readline(), Tiling_mode, Tiling_offset_X, Tiling_offset_Y, Update_window_area, Window_clicked_button(), Window_height, Window_help(), Window_input_content(), Window_set_input_button(), Window_set_normal_button(), and Window_width.
Referenced by Button_Effects(), and Main_handler().
void Effects_off (void)
Callback for the command that turns off all drawaing effects.
References Colorize_mode, Effect_function, Mask_mode, No_effect(), Quick_shade_mode, Shade_mode, Sieve_mode, Smear_mode, Smooth_mode, Snap_mode, Stencil_mode, and Tiling_mode.
Referenced by Button_Effects(), and Main_handler().
void Button_Sieve_mode (void)
Callback for the Sieve button (in the FX window) left click.
Toogle sieve mode.
References Sieve_mode.
Referenced by Button_Effects(), Button_Sieve_menu(), and Main_handler().
void Draw_sieve_scaled (short origin_x, short origin_y)
References Block, MC_Black, MC_Dark, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, Pixel, Sieve, Sieve_height, Sieve_width, Update_rect(), Window_pos_X, Window_pos_Y, and Window_special_button_list.
Referenced by Button_Sieve_menu().
void Draw_preset_sieve_patterns (void)
References Block, Gfx, MC_Black, MC_White, Menu_factor_X, Menu_factor_Y, Min(), T_Gui_skin::Sieve_pattern, ToWinH, ToWinL, ToWinX, ToWinY, Update_rect(), Window_pos_X, Window_pos_Y, and Zoom().
Referenced by Button_Sieve_menu().
void Copy_preset_sieve (byte index)
In the sieve window, copy one of the presets patterns to the current one.
Parameters:
index Index of the pattern to copy
References Gfx, Sieve, Sieve_height, T_Gui_skin::Sieve_pattern, and Sieve_width.
Referenced by Button_Sieve_menu(), and Init_program().
void Invert_trame (void)
In the sieve window, swaps black and white in the current pattern.
References byte, Sieve, Sieve_height, and Sieve_width.
Referenced by Button_Sieve_menu(), and Main_handler().
void Update_sieve_area (short x, short y)
References Menu_factor_X, Menu_factor_Y, and Update_rect().
Referenced by Button_Sieve_menu().
void Button_Sieve_menu (void)
Callback for the Sieve button (in the FX window) right click.
Displays the sieve setup menu.
References Back_color, Block, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, BUTTON_EFFECTS, BUTTON_HELP, Button_Sieve_mode(), byte, Change_paintbrush_shape(), Close_window(), Copy_preset_sieve(), Display_cursor(), Draw_preset_sieve_patterns(), Draw_sieve_scaled(), Fore_color, Hide_cursor, Invert_trame(), Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, MC_Black, MC_Dark, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, MOD_SHIFT, Mouse_K, Mouse_X, Mouse_Y, Num2str, Open_window(), PAINTBRUSH_SHAPE_COLOR_BRUSH, Pixel_in_brush(), T_Normal_button::Pos_X, T_Normal_button::Pos_Y, Print_in_window(), Read_pixel_from_brush(), Sieve, Sieve_height, Sieve_mode, Sieve_width, Update_rect(), Update_sieve_area(), Update_window_area, Window_clicked_button(), Window_display_frame(), Window_display_frame_in(), Window_height, Window_help(), Window_pos_X, Window_pos_Y, Window_set_normal_button(), Window_set_repeatable_button(), Window_set_special_button(), Window_special_button_list, and Window_width.
Referenced by Button_Effects(), and Main_handler().
Variable Documentation
byte Smooth_default_matrices[4][3][3]
Initial value:
{
 { {1,2,1}, {2,4,2}, {1,2,1} },
 { {1,3,1}, {3,9,3}, {1,3,1} },
 { {0,1,0}, {1,2,1}, {0,1,0} },
 { {2,3,2}, {3,1,3}, {2,3,2} }
}
Referenced by Button_Smooth_menu().