GrafX2: buttons.c File Reference
buttons.c File Reference
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <ctype.h>
#include <sys/stat.h>
#include <SDL.h>
#include "const.h"
#include "struct.h"
#include "global.h"
#include "misc.h"
#include "graph.h"
#include "engine.h"
#include "readline.h"
#include "filesel.h"
#include "loadsave.h"
#include "init.h"
#include "buttons.h"
#include "operatio.h"
#include "pages.h"
#include "palette.h"
#include "errors.h"
#include "readini.h"
#include "saveini.h"
#include "shade.h"
#include "io.h"
#include "help.h"
#include "text.h"
#include "sdlscreen.h"
#include "windows.h"
#include "brush.h"
#include "input.h"
#include "special.h"
#include <dirent.h>
Defines
#define isHidden(x) ((x)->d_name[0]=='.')
#define YES "YES"
#define NO " NO"
#define FILESEL_Y 34
#define SWAP_BYTES(a, b) { byte c=a; a=b; b=c;}
#define SWAP_WORDS(a, b) { word c=a; a=b; b=c;}
#define SWAP_SHORTS(a, b) { short c=a; a=b; b=c;}
#define SWAP_FLOATS(a, b) { float c=a; a=b; b=c;}
#define MODELIST_LINES 10
Number of video modes to display in the resolution menu.
#define TOLERANCE_X 8
#define TOLERANCE_Y 4
Functions
void Stencil_update_color (byte color)
void Stencil_tag_color (byte color, byte tag_color)
void Message_out_of_memory (void)
Displays an error message when there is no more memory for the requested operation.
void Button_Message_initial (void)
Displays the splash screen at program startup.
void Change_paintbrush_shape (byte shape)
Changes brush shape.
void Button_Undo (void)
Undo the last modification to the picture.
void Button_Redo (void)
Redo an operation that has been undone.
void Button_Pal_left (void)
Callback for the palette scroller buttons left click.
void Button_Pal_left_fast (void)
Callback for the palette scroller buttons right click.
void Button_Pal_right (void)
Callback for the palette scroller buttons left click.
void Button_Pal_right_fast (void)
Callback for the palette scroller buttons right click.
void Button_Select_forecolor (void)
Callback for the palette color buttons left click.
void Button_Select_backcolor (void)
Callback for the palette color buttons right click.
void Pixel_in_hidden_toolbar (word x, word y, byte color)
void Button_Hide_menu (void)
Hides the menubar.
byte Button_Quit_local_function (void)
void Button_Quit (void)
Quits the program.
void Button_Clear (void)
Clear the whole screen with black (color index 0).
void Button_Clear_with_backcolor (void)
Clear the screen with the selected backcolor.
void Menu_tag_colors (char *window_title, byte *table, byte *mode, byte can_cancel, const char *help_section, word close_shortcut)
Generic color tagging menu, for various effects.
void Button_Stencil_mode (void)
Callback for the Stencil button (in the FX window) left click.
void Button_Stencil_menu (void)
Callback for the Stencil button (in the FX window) right click.
void Button_Mask_mode (void)
Callback for the Mask button (in the FX window) left click.
void Button_Mask_menu (void)
Callback for the Mask button (in the FX window) right click.
void Settings_display_config (T_Config *conf)
void Settings_save_config (T_Config *conf)
void Settings_load_config (T_Config *conf)
void Button_Settings (void)
Display the setting menu.
char * Format_font_filename (const char *fname)
void Add_font_or_skin (const char *name)
void Draw_one_skin_name (word x, word y, word index, byte highlighted)
void Button_Skins (void)
Skin selector window.
void Button_Page (void)
Swap main and spare drawing pages.
void Copy_image_only (void)
Copy only pixel data from main page to spare page (no palette copy).
void Copy_some_colors (void)
void Button_Copy_page (void)
Copy main page to spare page.
void Button_Kill (void)
Kill (free from memory) the current page.
void Check_mode_button (short x_pos, short y_pos, byte state)
void Display_modes_list (short list_start, short cursor_position)
void Scroll_list_of_modes (short list_start, short cursor_position, int *selected_mode)
void Button_Resolution (void)
Display the screenmode menu.
void Button_Safety_resolution (void)
Set the screen to the "safe resolution" (320x200 pixel window).
void Button_Draw (void)
Callback for the freehand draw button left click.
void Button_Draw_switch_mode (void)
Callback for the freehand draw button right click.
void Button_Empty_rectangle (void)
Callback for the empty rectangle button.
void Button_Filled_rectangle (void)
Callback for the filled rectangle button.
void Button_Empty_circle (void)
Callback for the circle button left click.
void Button_Empty_ellipse (void)
Callback for the circle button left click.
void Button_Filled_circle (void)
Callback for the filled circle button ledt click.
void Button_Filled_ellipse (void)
Callback for the filled circle right click.
void Draw_button_gradient_style (short x_pos, short y_pos, int technique)
void Load_gradient_data (int index)
Gets the informations from the gradations table and set the global vars for the current gradation.
void Draw_gradient_preview (short start_x, short start_y, short width, short height, int index)
void Button_Gradients (void)
Callback for the gradation button.
void Button_Grad_circle (void)
Callback for the gradation circle button left click.
void Button_Grad_ellipse (void)
Callback for the gradation circle right click.
void Button_Grad_rectangle (void)
Callback for the gradation rectangle button.
void Button_Fill (void)
Callback for the fill button left click.
void Button_Replace (void)
Callback for the fill button right click.
void Button_Unselect_fill (void)
Disable and release the fill button.
void Button_Paintbrush_menu (void)
Callback for the brush button right click.
void Button_Brush_monochrome (void)
Callback for the brush button left click.
int Best_video_mode (void)
void Swap_data_of_image_and_brush (void)
void Load_picture (byte image)
Load picture from file.
void Button_Load (void)
Opens the load file dialog.
void Button_Reload (void)
Reload current picture from disk.
void Backup_filename (char *fname, char *backup_name)
void Backup_existing_file (void)
void Save_picture (byte image)
Save picture to file.
void Button_Save (void)
Open the save file dialog.
void Button_Autosave (void)
Saves the current file without asking for a new name.
void Button_Lines (void)
Callback for the lines button left click.
void Button_Lines_switch_mode (void)
Callback for the lines button right click.
void Button_Brush (void)
Callback for the brush button left click.
void Button_Unselect_brush (void)
Disables the custom brush and set back a regular one.
void Button_Restore_brush (void)
Callback for the brush button right click.
void Button_Lasso (void)
Callback for the freehand brush pick button left click.
void Button_Unselect_lasso (void)
Disables the custom freehand brush and set back a regular one.
void Button_Colorpicker (void)
Starts the color picking operation.
void Button_Unselect_colorpicker (void)
Disables the color picker button and get back to the previously selected drawing mode.
void Button_Invert_foreback (void)
Swap fore- and background colors.
void Button_Magnify (void)
Enters magnify mode.
void Button_Magnify_menu (void)
Displays magnify menu.
void Button_Unselect_magnifier (void)
Exit magnify mode.
void Button_Snap_mode (void)
Callback for the Grid button (in the FX window) left click.
void Button_Grid_menu (void)
Callback for the Grid button (in the FX window) right click.
void Button_Show_grid (void)
Callback to toggle the grid visible in the magnified view.
void Button_Brush_FX (void)
Display the Brush effects window.
void Button_Smooth_mode (void)
Callback for the Smooth button (in the FX window) right click.
void Button_Smooth_menu (void)
Display the menu for the smooth effect.
void Button_Smear_mode (void)
Toogles the smear mode.
void Compute_colorize_table (void)
Computes the tables used by the transparency/colorize mode.
void Button_Colorize_mode (void)
Callback for the Tranparency button (in the FX window) left click.
void Button_Colorize_display_selection (int mode)
void Button_Colorize_menu (void)
Callback for the Transparency button (in the FX window) right click.
void Button_Tiling_mode (void)
Callback for the Tiling button (in the FX window) left click.
void Button_Tiling_menu (void)
Callback for the Tiling button (in the FX window) right click.
void Effects_off (void)
Callback for the command that turns off all drawaing effects.
void Transparency_set (byte amount)
Command that sets the transparency level.
void Button_Curves (void)
Callback for the curves button left click.
void Button_Curves_switch_mode (void)
Callback for the curves button right click.
void Button_Airbrush (void)
Callback for the spray button left click.
void Refresh_airbrush_settings (byte selected_color, byte update_slider)
void Button_Airbrush_menu (void)
Callback for the spray button right click.
void Button_Sieve_mode (void)
Callback for the Sieve button (in the FX window) left click.
void Draw_sieve_scaled (short origin_x, short origin_y)
void Draw_preset_sieve_patterns (void)
void Copy_preset_sieve (byte index)
In the sieve window, copy one of the presets patterns to the current one.
void Invert_trame (void)
In the sieve window, swaps black and white in the current pattern.
void Update_sieve_area (short x, short y)
void Button_Sieve_menu (void)
Callback for the Sieve button (in the FX window) right click.
void Button_polygon (void)
Callback for the polyline button left click.
void Button_Polyform (void)
Callback for the polyline right click.
void Button_Polyfill (void)
Callback for the polyfill button left click.
void Button_Filled_polyform (void)
Callback for the polyfill button right click.
void Button_Adjust (void)
Callback for the adjust picture button.
void Display_effect_sprite (short sprite_number, short start_x, short start_y)
void Display_effect_state (short x, short y, char *label, byte state)
void Display_effect_states (void)
void Display_feedback_state (void)
void Button_Effects (void)
Callback for the effects button click.
void Draw_one_font_name (word x, word y, word index, byte highlighted)
void Button_Text ()
Callback for the text button.
void Display_stored_brush_in_window (word x_pos, word y_pos, int index)
void Store_brush (int index)
byte Restore_brush (int index)
void Button_Brush_container (void)
Variables
char Program_version []
short Old_MX
short Old_MY
T_Fileselector Skin_files_list
T_Fileselector Font_files_list
byte Old_black
byte Old_dark
byte Old_light
byte Old_white
byte Old_trans
byte Coming_from_zoom_factor_menu = 0
byte Smooth_default_matrices [4][3][3]
Define Documentation
#define isHidden (x) ((x)->d_name[0]=='.')
Referenced by Read_list_of_files().
#define YES "YES"
Referenced by Settings_display_config().
#define NO " NO"
Referenced by Settings_display_config().
#define FILESEL_Y 34
Referenced by Button_Skins().
#define SWAP_BYTES (a, b) { byte c=a; a=b; b=c;}
Referenced by Button_Page().
#define SWAP_WORDS (a, b) { word c=a; a=b; b=c;}
Referenced by Button_Page().
#define SWAP_SHORTS (a, b) { short c=a; a=b; b=c;}
Referenced by Button_Page().
#define SWAP_FLOATS (a, b) { float c=a; a=b; b=c;}
Referenced by Button_Page().
#define MODELIST_LINES 10
Number of video modes to display in the resolution menu.
Referenced by Button_Resolution(), and Display_modes_list().
#define TOLERANCE_X 8
Referenced by Best_video_mode().
#define TOLERANCE_Y 4
Referenced by Best_video_mode().
Function Documentation
void Stencil_update_color (byte color)
References Menu_factor_X, Menu_factor_Y, Update_rect(), Window_palette_button_list, Window_pos_X, and Window_pos_Y.
Referenced by Button_Airbrush_menu(), and Menu_tag_colors().
void Stencil_tag_color (byte color, byte tag_color)
References Block, Menu_factor_X, Menu_factor_Y, Window_palette_button_list, Window_pos_X, and Window_pos_Y.
Referenced by Button_Airbrush_menu(), and Menu_tag_colors().
void Message_out_of_memory (void)
Displays an error message when there is no more memory for the requested operation.
References Close_window(), Display_cursor(), Key, KEY_ESC, MC_Black, MC_Light, Open_window(), Print_in_window(), Update_window_area, Window_clicked_button(), Window_height, Window_set_normal_button(), and Window_width.
Referenced by Button_Transform_menu(), Copy_image_only(), Init_preview(), Init_preview_24b(), and Resize_image().
void Button_Message_initial (void)
Displays the splash screen at program startup.
References Block, Close_window(), Display_cursor(), Get_input(), Gfx, Key, T_Gui_skin::Logo_grafx2, MC_Black, MC_Dark, MC_Light, Menu_factor_X, Menu_factor_Y, Mouse_K, Open_window(), Pixel_in_window(), Print_in_window(), Program_version, Update_window_area, Wait_end_of_click(), Window_display_frame_in(), Window_height, Window_pos_X, Window_pos_Y, and Window_width.
Referenced by main().
void Change_paintbrush_shape (byte shape)
Changes brush shape.
This function saves the current brush shape and swith to the default one (single pixel brush) for the filler and the color picker. These functions don't need (and will not work with) a custom brush.
References Current_operation, Display_paintbrush_in_menu(), OPERATION_COLORPICK, OPERATION_FILL, Paintbrush_shape, Paintbrush_shape_before_colorpicker, Paintbrush_shape_before_fill, and PAINTBRUSH_SHAPE_POINT.
Referenced by Button_Brush_monochrome(), Button_Paintbrush_menu(), Button_Restore_brush(), Button_Sieve_menu(), Button_Text(), Load_picture(), Main_handler(), Restore_brush(), and Return_to_draw_mode().
void Button_Undo (void)
Undo the last modification to the picture.
References BUTTON_MAGNIFIER, BUTTON_UNDO, Compute_optimal_menu_colors(), Display_all_screen(), Display_cursor(), Display_menu(), Draw_menu_button_frame(), Hide_cursor, Main_magnifier_mode, Main_palette, Set_palette(), Undo(), and Unselect_button().
Referenced by Init_buttons().
void Button_Redo (void)
Redo an operation that has been undone.
References BUTTON_MAGNIFIER, BUTTON_UNDO, Compute_optimal_menu_colors(), Display_all_screen(), Display_cursor(), Display_menu(), Draw_menu_button_frame(), Hide_cursor, Main_magnifier_mode, Main_palette, Redo(), Set_palette(), and Unselect_button().
Referenced by Init_buttons().
void Button_Pal_left (void)
Callback for the palette scroller buttons left click.
Scrolls the menubar palette one column to the left.
References BUTTON_PAL_LEFT, Config, Display_cursor(), Display_menu_palette(), First_color_in_palette, Hide_cursor, Palette_cells_X(), Palette_cells_Y(), T_Config::Palette_vertical, and Unselect_button().
Referenced by Init_buttons().
void Button_Pal_left_fast (void)
Callback for the palette scroller buttons right click.
Scrolls the menubar palette faster to the left.
References BUTTON_PAL_LEFT, Display_cursor(), Display_menu_palette(), First_color_in_palette, Hide_cursor, Palette_cells_X(), Palette_cells_Y(), and Unselect_button().
Referenced by Init_buttons().
void Button_Pal_right (void)
Callback for the palette scroller buttons left click.
Scrolls the menubar palette one column to the right.
References BUTTON_PAL_RIGHT, Config, Display_cursor(), Display_menu_palette(), First_color_in_palette, Hide_cursor, Palette_cells_X(), Palette_cells_Y(), T_Config::Palette_vertical, and Unselect_button().
Referenced by Init_buttons().
void Button_Pal_right_fast (void)
Callback for the palette scroller buttons right click.
Scrolls the menubar palette faster to the right.
References BUTTON_PAL_RIGHT, Display_cursor(), Display_menu_palette(), First_color_in_palette, Hide_cursor, Palette_cells_X(), Palette_cells_Y(), and Unselect_button().
Referenced by Init_buttons().
void Button_Select_forecolor (void)
Callback for the palette color buttons left click.
Selects the foreground drawing color when clicking on the menubar palette.
References Button_Palette(), Config, Display_cursor(), T_Config::Double_click_speed, Fore_color, Hide_cursor, Pick_color_in_palette(), and Set_fore_color().
Referenced by Init_buttons().
void Button_Select_backcolor (void)
Callback for the palette color buttons right click.
Selects the background drawing color when clicking on the menubar palette.
References Display_cursor(), Hide_cursor, Pick_color_in_palette(), and Set_back_color().
Referenced by Init_buttons().
void Pixel_in_hidden_toolbar (word x, word y, byte color)
Referenced by Button_Hide_menu().
void Button_Hide_menu (void)
Hides the menubar.
References BUTTON_HIDE, Compute_limits(), Compute_magnifier_data(), Compute_paintbrush_coordinates(), Display_all_screen(), Display_cursor(), Display_menu(), Hide_cursor, Main_image_height, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_offset_Y, Main_offset_Y, Menu_factor_Y, Menu_height, Menu_is_visible, Menu_Y, Pixel_in_hidden_toolbar(), Pixel_in_menu, Pixel_in_toolbar(), Position_screen_according_to_zoom(), Screen_height, Spare_image_height, Spare_offset_Y, and Unselect_button().
Referenced by Init_buttons().
byte Button_Quit_local_function (void)
References BUTTON_HELP, BUTTON_QUIT, byte, Close_window(), Confirmation_box(), Cursor_shape, CURSOR_SHAPE_HOURGLASS, Display_cursor(), File_error, File_exists(), Get_full_filename(), Hide_cursor, Is_shortcut(), Key, KEY_ESC, Main_image_is_modified, MAX_PATH_CHARACTERS, Open_window(), Save_image(), Update_window_area, Window_clicked_button(), Window_height, Window_help(), Window_set_normal_button(), and Window_width.
Referenced by Button_Quit().
void Button_Quit (void)
Quits the program.
Display a requester to save the changes to the picture before exiting if the pic was modified since last save.
References Button_Page(), BUTTON_QUIT, Button_Quit_local_function(), Display_cursor(), Hide_cursor, Menu_is_visible, Menu_Y, Mouse_Y, Quitting, Spare_image_is_modified, and Unselect_button().
Referenced by Init_buttons(), and Main_handler().
void Button_Clear (void)
Clear the whole screen with black (color index 0).
References Backup(), BUTTON_CLEAR, T_Config::Clear_with_stencil, Config, Display_all_screen(), Display_cursor(), End_of_modification(), Hide_current_image(), Hide_current_image_with_stencil(), Hide_cursor, Stencil, Stencil_mode, and Unselect_button().
Referenced by Init_buttons().
void Button_Clear_with_backcolor (void)
Clear the screen with the selected backcolor.
References Back_color, Backup(), BUTTON_CLEAR, T_Config::Clear_with_stencil, Config, Display_all_screen(), Display_cursor(), End_of_modification(), Hide_current_image(), Hide_current_image_with_stencil(), Hide_cursor, Stencil, Stencil_mode, and Unselect_button().
Referenced by Init_buttons().
void Menu_tag_colors (char * window_title, byte * table, byte * mode, byte can_cancel, const char * help_section, word close_shortcut)
Generic color tagging menu, for various effects.
References BUTTON_EFFECTS, BUTTON_HELP, byte, Close_window(), Display_cursor(), Get_color_behind_window(), Hide_cursor, Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, MC_Black, MC_Light, Mouse_K, Mouse_X, Mouse_Y, Open_window(), Read_pixel, Stencil_tag_color(), Stencil_update_color(), Update_window_area, Wait_end_of_click(), Window_attribute2, Window_clicked_button(), Window_height, Window_help(), Window_set_normal_button(), Window_set_palette_button(), Window_width, and word.
Referenced by Button_Mask_menu(), Button_Secondary_palette(), Button_Stencil_menu(), Copy_some_colors(), and Main_handler().
void Button_Stencil_mode (void)
Callback for the Stencil button (in the FX window) left click.
Toogle stencil mode.
References Stencil_mode.
Referenced by Button_Effects(), and Main_handler().
void Button_Stencil_menu (void)
Callback for the Stencil button (in the FX window) right click.
Displays the stencil setup menu.
References Menu_tag_colors(), SPECIAL_STENCIL_MENU, Stencil, and Stencil_mode.
Referenced by Button_Effects(), and Main_handler().
void Button_Mask_mode (void)
Callback for the Mask button (in the FX window) left click.
Toogles the mask mode/
References Mask_mode.
Referenced by Button_Effects(), and Main_handler().
void Button_Mask_menu (void)
Callback for the Mask button (in the FX window) right click.
Displays the mask setup menu.
References Mask_mode, Mask_table, Menu_tag_colors(), and SPECIAL_MASK_MENU.
Referenced by Button_Effects(), and Main_handler().
void Settings_display_config (T_Config * conf)
References T_Config::Adjust_brush_pick, T_Config::Auto_save, T_Config::Auto_set_res, T_Config::Backup, T_Config::Clear_palette, T_Config::Coords_rel, Display_cursor(), Hide_cursor, T_Config::Max_undo_pages, T_Config::Maximize_preview, MC_Black, MC_Light, T_Config::Mouse_sensitivity_index_x, T_Config::Mouse_sensitivity_index_y, T_Scroller_button::Next, NO, Num2str(), T_Scroller_button::Position, Print_in_window(), T_Config::Safety_colors, T_Config::Show_hidden_directories, T_Config::Show_hidden_files, Window_draw_slider(), Window_input_content(), Window_scroller_button_list, Window_special_button_list, and YES.
Referenced by Button_Settings().
void Settings_save_config (T_Config * conf)
References Error, Save_CFG(), and Save_INI().
Referenced by Button_Settings().
void Settings_load_config (T_Config * conf)
References Error, Load_CFG(), and Load_INI().
Referenced by Button_Settings().
void Button_Settings (void)
Display the setting menu.
References T_Config::Adjust_brush_pick, T_Config::Auto_save, T_Config::Auto_set_res, T_Config::Backup, BUTTON_HELP, BUTTON_SETTINGS, byte, T_Config::Clear_palette, Close_window(), Compute_optimal_menu_colors(), Config, T_Config::Coords_rel, Display_cursor(), Display_menu(), Is_shortcut(), Key, KEY_ESC, Main_fileselector_offset, Main_fileselector_position, Main_palette, T_Config::Max_undo_pages, T_Config::Maximize_preview, MC_Dark, MC_Light, T_Config::Mouse_sensitivity_index_x, T_Config::Mouse_sensitivity_index_y, NB_MAX_PAGES_UNDO, Num2str(), Open_window(), Print_in_window(), Readline(), T_Config::Safety_colors, Set_number_of_backups(), Settings_display_config(), Settings_load_config(), Settings_save_config(), T_Config::Show_hidden_directories, T_Config::Show_hidden_files, Spare_fileselector_offset, Spare_fileselector_position, Unselect_button(), Update_window_area, Wait_end_of_click(), Window_attribute2, Window_clicked_button(), Window_display_frame(), Window_height, Window_help(), Window_input_content(), Window_set_input_button(), Window_set_normal_button(), Window_set_scroller_button(), Window_special_button_list, and Window_width.
Referenced by Init_buttons().
char* Format_font_filename (const char * fname)
References ELLIPSIS_CHARACTER.
Referenced by Add_font_or_skin().
void Add_font_or_skin (const char * name)
References Add_element_to_list(), Find_last_slash(), T_Fileselector::First, Format_filename(), Format_font_filename(), T_Fileselector_item::Full_name, and T_Fileselector_item::Short_name.
Referenced by Button_Skins().
void Draw_one_skin_name (word x, word y, word index, byte highlighted)
References Get_item_by_index(), T_Fileselector::Nb_elements, Print_in_window(), and T_Fileselector_item::Short_name.
Referenced by Button_Skins().
void Button_Skins (void)
Skin selector window.
Display the skin selector window.
References Add_font_or_skin(), BUTTON_SETTINGS, byte, Close_window(), Config, T_Config::Cursor, T_List_button::Cursor_position, Data_directory, Display_cursor(), T_Config::Display_image_limits, Display_menu(), Draw_one_skin_name(), FILESEL_Y, Find_file_in_fileselector(), T_Config::Font_file, For_each_file(), Free_fileselector_list(), T_Fileselector_item::Full_name, Get_item_by_index(), Gfx, Gui_loading_error_message, Hide_cursor, Key, LEFT_SIDE, T_List_button::List_start, Load_font(), Load_graphics(), MAX_PATH_CHARACTERS, MC_Black, MC_Dark, MC_Light, MC_Trans, MC_White, Menu_font, T_Fileselector::Nb_elements, T_Fileselector::Nb_files, Open_window(), Pixel_in_window(), Print_in_window(), RIGHT_SIDE, T_Config::Separate_colors, T_Config::Skin_file, skin_logo, Sort_list_of_files(), Unselect_button(), Update_window_area, Verbose_error_message(), Window_attribute2, Window_clicked_button(), Window_display_frame_in(), Window_dropdown_add_item(), Window_height, Window_redraw_list(), Window_set_dropdown_button(), Window_set_list_button(), Window_set_normal_button(), Window_set_scroller_button(), Window_set_special_button(), Window_width, and word.
Referenced by Init_buttons().
void Button_Page (void)
Swap main and spare drawing pages.
References BUTTON_MAGNIFIER, BUTTON_PAGE, byte, Change_magnifier_factor(), Compute_optimal_menu_colors(), Display_all_screen(), Display_cursor(), Display_menu(), Draw_menu_button_frame(), Exchange_main_and_spare(), Hide_cursor, Main_current_directory, Main_fileselector_offset, Main_fileselector_position, Main_format, Main_image_is_modified, Main_magnifier_factor, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_magnifier_width, Main_offset_X, Main_offset_Y, Main_palette, Main_separator_position, Main_separator_proportion, Main_X_zoom, Old_main_offset_X, Old_main_offset_Y, Old_spare_offset_X, Old_spare_offset_Y, Pixel_preview, Pixel_preview_magnifier, Pixel_preview_normal, Set_palette(), Spare_current_directory, Spare_fileselector_offset, Spare_fileselector_position, Spare_format, Spare_image_is_modified, Spare_magnifier_factor, Spare_magnifier_height, Spare_magnifier_mode, Spare_magnifier_offset_X, Spare_magnifier_offset_Y, Spare_magnifier_width, Spare_offset_X, Spare_offset_Y, Spare_separator_position, Spare_separator_proportion, Spare_X_zoom, SWAP_BYTES, SWAP_FLOATS, SWAP_SHORTS, SWAP_WORDS, Unselect_button(), and ZOOM_FACTOR.
Referenced by Button_Quit(), Init_buttons(), and main().
void Copy_image_only (void)
Copy only pixel data from main page to spare page (no palette copy).
References Backup_and_resize_the_spare(), Main_image_height, Main_image_width, Main_magnifier_factor, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_magnifier_width, Main_offset_X, Main_offset_Y, Main_screen, Main_separator_position, Main_separator_proportion, Main_X_zoom, Message_out_of_memory(), Spare_image_height, Spare_image_width, Spare_magnifier_factor, Spare_magnifier_height, Spare_magnifier_mode, Spare_magnifier_offset_X, Spare_magnifier_offset_Y, Spare_magnifier_width, Spare_offset_X, Spare_offset_Y, Spare_screen, Spare_separator_position, Spare_separator_proportion, and Spare_X_zoom.
Referenced by Button_Copy_page().
void Copy_some_colors (void)
References byte, Confirmation_box(), Main_palette, Menu_tag_colors(), Spare_image_is_modified, and Spare_palette.
Referenced by Button_Copy_page().
void Button_Copy_page (void)
Copy main page to spare page.
References BUTTON_HELP, BUTTON_PAGE, Close_window(), Confirmation_box(), Copy_image_only(), Copy_some_colors(), Display_cursor(), Hide_cursor, Is_shortcut(), Key, KEY_ESC, Main_palette, Open_window(), Remap_spare(), Spare_image_is_modified, Spare_palette, Unselect_button(), Update_window_area, Window_clicked_button(), Window_height, Window_help(), Window_set_normal_button(), and Window_width.
Referenced by Init_buttons().
void Button_Kill (void)
Kill (free from memory) the current page.
References BUTTON_KILL, BUTTON_MAGNIFIER, Compute_optimal_menu_colors(), Confirmation_box(), Display_all_screen(), Display_cursor(), Display_menu(), Draw_menu_button_frame(), Free_current_page(), Hide_cursor, Main_backups, Main_magnifier_mode, Main_palette, T_List_of_pages::Nb_pages_allocated, Set_palette(), Unselect_button(), and Warning_message().
Referenced by Init_buttons().
void Check_mode_button (short x_pos, short y_pos, byte state)
References Block, byte, MC_Black, MC_Dark, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, Update_rect(), Window_pos_X, and Window_pos_Y.
Referenced by Button_Resolution(), and Display_modes_list().
void Display_modes_list (short list_start, short cursor_position)
References byte, Check_mode_button(), Height, MC_Black, MC_Dark, MC_Light, MC_White, MODELIST_LINES, Nb_video_modes, Num2str(), Print_in_window(), Video_mode, and Width.
Referenced by Button_Resolution(), and Scroll_list_of_modes().
void Scroll_list_of_modes (short list_start, short cursor_position, int * selected_mode)
References Display_cursor(), Display_modes_list(), Hide_cursor, Window_draw_slider(), and Window_scroller_button_list.
Referenced by Button_Resolution().
void Button_Resolution (void)
Display the screenmode menu.
References BUTTON_HELP, BUTTON_MAGNIFIER, BUTTON_RESOL, byte, Check_mode_button(), Close_window(), Current_resolution, Display_all_screen(), Display_cursor(), Display_menu(), Display_modes_list(), Error, Height, T_Video_mode::Height, Hide_cursor, Init_mode_video(), Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, Main_image_height, Main_image_width, Main_magnifier_mode, MC_Black, MC_Dark, MC_Light, Menu_factor_Y, MODELIST_LINES, Mouse_K, Mouse_X, Mouse_Y, Nb_video_modes, Num2str(), Open_window(), Paintbrush_X, Paintbrush_Y, Pixel_height, PIXEL_MAX, Pixel_ratio, PIXEL_SIMPLE, Pixel_width, Print_in_window(), Readline(), Reposition_palette(), Resize_image(), RIGHT_SIDE, Scroll_list_of_modes(), T_Video_mode::State, Unselect_button(), Update_window_area, Video_mode, Wait_end_of_click(), Width, T_Video_mode::Width, Window_attribute1, Window_attribute2, Window_clicked_button(), Window_display_frame(), Window_display_frame_in(), Window_draw_normal_bouton(), Window_dropdown_add_item(), Window_height, Window_help(), Window_input_content(), Window_pos_Y, Window_rectangle(), Window_set_dropdown_button(), Window_set_input_button(), Window_set_normal_button(), Window_set_scroller_button(), Window_set_special_button(), Window_width, and word.
Referenced by Init_buttons().
void Button_Safety_resolution (void)
Set the screen to the "safe resolution" (320x200 pixel window).
References BUTTON_MAGNIFIER, BUTTON_RESOL, Current_resolution, Display_all_screen(), Display_cursor(), Display_menu(), Height, Hide_cursor, Init_mode_video(), PIXEL_SIMPLE, Reposition_palette(), Unselect_button(), Video_mode, and Width.
Referenced by Init_buttons().
void Button_Draw (void)
Callback for the freehand draw button left click.
Selects freehand drawing mode, depending on the current state of the freehand button.
References Display_cursor(), Hide_cursor, Selected_freehand_mode, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Draw_switch_mode (void)
Callback for the freehand draw button right click.
Cycles the drawing modes for the freehand tool.
References BUTTON_DRAW, Display_cursor(), Display_sprite_in_menu(), Hide_cursor, OPERATION_CONTINUOUS_DRAW, OPERATION_FILLED_CONTOUR, Selected_freehand_mode, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Empty_rectangle (void)
Callback for the empty rectangle button.
Start the rectangle operation.
References Display_cursor(), Hide_cursor, OPERATION_EMPTY_RECTANGLE, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Filled_rectangle (void)
Callback for the filled rectangle button.
Start the filled rectangle operation.
References Display_cursor(), Hide_cursor, OPERATION_FILLED_RECTANGLE, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Empty_circle (void)
Callback for the circle button left click.
Starts drawing an empty circle
References Display_cursor(), Hide_cursor, OPERATION_EMPTY_CIRCLE, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Empty_ellipse (void)
Callback for the circle button left click.
Starts drawing an empty ellipsis
References Display_cursor(), Hide_cursor, OPERATION_EMPTY_ELLIPSE, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Filled_circle (void)
Callback for the filled circle button ledt click.
Starts drawing a filled circle.
References Display_cursor(), Hide_cursor, OPERATION_FILLED_CIRCLE, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Filled_ellipse (void)
Callback for the filled circle right click.
Starts drawing a filled ellipsis.
References Display_cursor(), Hide_cursor, OPERATION_FILLED_ELLIPSE, and Start_operation_stack().
Referenced by Init_buttons().
void Draw_button_gradient_style (short x_pos, short y_pos, int technique)
References Block, MC_Black, MC_White, Menu_factor_X, Menu_factor_Y, Pixel_in_window(), Update_rect(), Window_pos_X, and Window_pos_Y.
Referenced by Button_Gradients().
void Load_gradient_data (int index)
Gets the informations from the gradations table and set the global vars for the current gradation.
Parameters:
index index of the selected gradation
References T_Gradient_array::End, Gradient_array, Gradient_basic(), Gradient_bounds_range, Gradient_dithered(), Gradient_extra_dithered(), Gradient_function, Gradient_is_inverted, Gradient_lower_bound, Gradient_random_factor, Gradient_upper_bound, T_Gradient_array::Inverse, T_Gradient_array::Mix, and T_Gradient_array::Start.
Referenced by Button_Gradients(), Draw_gradient_preview(), Load_CFG(), and Set_config_defaults().
void Draw_gradient_preview (short start_x, short start_y, short width, short height, int index)
References Gradient_function, Gradient_total_range, Load_gradient_data(), Menu_factor_X, Menu_factor_Y, Update_rect(), Window_pos_X, and Window_pos_Y.
Referenced by Button_Gradients().
void Button_Gradients (void)
Callback for the gradation button.
Opens the "Gradation menu".
References BUTTON_GRADRECT, BUTTON_HELP, byte, Close_window(), Current_gradient, Current_operation, Display_cursor(), Display_pixel(), Draw_button_gradient_style(), Draw_gradient_preview(), T_Gradient_array::End, Get_color_behind_window(), Gradient_array, Gradient_pixel, Hide_cursor, T_Gradient_array::Inverse, Is_shortcut(), Key, KEY_ESC, Load_gradient_data(), MC_Black, MC_Dark, MC_Light, T_Gradient_array::Mix, MOD_SHIFT, Mouse_K, Mouse_X, Mouse_Y, Num2str(), Open_window(), OPERATION_GRAD_RECTANGLE, Pixel, T_Scroller_button::Position, Print_in_window(), Read_pixel, T_Gradient_array::Start, Tag_color_range(), T_Gradient_array::Technique, Unselect_button(), Update_window_area, Wait_end_of_click(), Window_attribute2, Window_clicked_button(), Window_display_frame_in(), Window_draw_slider(), Window_height, Window_help(), Window_set_normal_button(), Window_set_palette_button(), Window_set_scroller_button(), and Window_width.
Referenced by Init_buttons().
void Button_Grad_circle (void)
Callback for the gradation circle button left click.
Starts drawing a gradation circle.
References Display_cursor(), Hide_cursor, OPERATION_GRAD_CIRCLE, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Grad_ellipse (void)
Callback for the gradation circle right click.
Starts drawing a gradation ellipsis.
References Display_cursor(), Hide_cursor, OPERATION_GRAD_ELLIPSE, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Grad_rectangle (void)
Callback for the gradation rectangle button.
Starts the gradation rectangle drawing operation.
References Display_cursor(), Hide_cursor, OPERATION_GRAD_RECTANGLE, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Fill (void)
Callback for the fill button left click.
Start the filling operation.
References Current_operation, Display_cursor(), Hide_cursor, Main_magnifier_mode, Main_separator_position, Main_X_zoom, Menu_is_visible, Menu_Y, Mouse_X, Mouse_Y, OPERATION_FILL, OPERATION_REPLACE, Paintbrush_shape, Paintbrush_shape_before_fill, PAINTBRUSH_SHAPE_POINT, Print_in_menu(), and Start_operation_stack().
Referenced by Init_buttons().
void Button_Replace (void)
Callback for the fill button right click.
Start the color replace operation.
References Current_operation, Display_cursor(), Hide_cursor, Main_magnifier_mode, Main_separator_position, Main_X_zoom, Menu_is_visible, Menu_Y, Mouse_X, Mouse_Y, OPERATION_FILL, OPERATION_REPLACE, Paintbrush_shape, Paintbrush_shape_before_fill, PAINTBRUSH_SHAPE_POINT, Print_in_menu(), and Start_operation_stack().
Referenced by Init_buttons().
void Button_Unselect_fill (void)
Disable and release the fill button.
Restores the cursor (custom brushes are disabled for the fill operation). Cleans the status bar if the color replacement tool put a preview color inside it.
References Current_operation, Main_magnifier_mode, Main_separator_position, Main_X_zoom, Menu_is_visible, Menu_Y, Mouse_X, Mouse_Y, OPERATION_REPLACE, Paintbrush_shape, Paintbrush_shape_before_fill, and Print_in_menu().
Referenced by Init_buttons().
void Button_Paintbrush_menu (void)
Callback for the brush button right click.
Displays the "Paintbrush menu".
References BRUSH_CONTAINER_COLUMNS, BRUSH_CONTAINER_ROWS, BUTTON_HELP, BUTTON_PAINTBRUSHES, byte, Change_paintbrush_shape(), Close_window(), Display_cursor(), Display_paintbrush_in_window(), Display_stored_brush_in_window(), Gfx, Hide_cursor, Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, MAX_PAINTBRUSH_SIZE, NB_PAINTBRUSH_SPRITES, Open_window(), Paintbrush_height, Paintbrush_offset_X, Paintbrush_offset_Y, Paintbrush_shape, T_Gui_skin::Paintbrush_sprite, Paintbrush_sprite, T_Gui_skin::Paintbrush_type, Paintbrush_width, T_Gui_skin::Preset_paintbrush_height, T_Gui_skin::Preset_paintbrush_offset_X, T_Gui_skin::Preset_paintbrush_offset_Y, T_Gui_skin::Preset_paintbrush_width, Restore_brush(), RIGHT_SIDE, Store_brush(), Unselect_button(), Update_window_area, Window_attribute1, Window_clicked_button(), Window_display_frame(), Window_height, Window_help(), Window_set_normal_button(), and Window_width.
Referenced by Init_buttons().
void Button_Brush_monochrome (void)
Callback for the brush button left click.
Selects the monochrome brush mode when right clicking on the brush button.
References BUTTON_PAINTBRUSHES, Change_paintbrush_shape(), Display_cursor(), Hide_cursor, PAINTBRUSH_SHAPE_MONO_BRUSH, and Unselect_button().
Referenced by Init_buttons().
int Best_video_mode (void)
References Config, Current_resolution, T_Video_mode::Height, Main_image_height, Main_image_width, Nb_video_modes, Original_screen_X, Original_screen_Y, T_Config::Set_resolution_according_to, TOLERANCE_X, TOLERANCE_Y, Video_mode, and T_Video_mode::Width.
Referenced by Button_Reload(), and Load_picture().
void Swap_data_of_image_and_brush (void)
References Brush_comment, Brush_current_directory, Brush_file_directory, Brush_fileformat, Brush_filename, Brush_fileselector_offset, Brush_fileselector_position, Brush_format, byte, Main_comment, Main_current_directory, Main_file_directory, Main_fileformat, Main_filename, Main_fileselector_offset, Main_fileselector_position, Main_format, and MAX_PATH_CHARACTERS.
Referenced by Load_picture(), and Save_picture().
void Load_picture (byte image)
Load picture from file.
References T_Config::Auto_discontinuous, T_Config::Auto_set_res, Best_video_mode(), Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, BUTTON_DRAW, Button_Load_or_Save(), BUTTON_MAGNIFIER, byte, Change_paintbrush_shape(), Compute_limits(), Compute_optimal_menu_colors(), Compute_paintbrush_coordinates(), Config, Confirmation_box(), Current_operation, Current_resolution, Cursor_shape, CURSOR_SHAPE_HOURGLASS, Display_all_screen(), Display_cursor(), Display_menu(), Draw_menu_button_frame(), File_error, Fore_color, Get_fileformat(), Height, Hide_cursor, Init_mode_video(), LEFT_SIDE, Load_image(), Main_comment, Main_file_directory, Main_fileformat, Main_filename, Main_image_height, Main_image_is_modified, Main_image_width, Main_magnifier_mode, Main_offset_X, Main_offset_Y, Main_palette, MAX_PAINTBRUSH_SIZE, MAX_PATH_CHARACTERS, OPERATION_DISCONTINUOUS_DRAW, Original_screen_X, Original_screen_Y, PAINTBRUSH_SHAPE_COLOR_BRUSH, Pixel_load_function, Pixel_load_in_brush(), Pixel_load_in_current_screen(), Pixel_preview, Pixel_preview_normal, Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, Print_filename(), Ratio_of_loaded_image, RIGHT_SIDE, Select_button(), Set_palette(), Smear_brush, Smear_brush_height, Smear_brush_width, Swap_data_of_image_and_brush(), Tiling_offset_X, Tiling_offset_Y, Video_mode, and Width.
Referenced by Button_Brush_FX(), Button_Load(), and Main_handler().
void Button_Load (void)
Opens the load file dialog.
References Load_picture(), Main_backups, T_List_of_pages::Pages, and Upload_infos_page_main().
Referenced by Init_buttons().
void Button_Reload (void)
Reload current picture from disk.
References T_Config::Auto_set_res, Best_video_mode(), BUTTON_LOAD, BUTTON_MAGNIFIER, byte, Compute_limits(), Compute_optimal_menu_colors(), Compute_paintbrush_coordinates(), Config, Confirmation_box(), Current_resolution, Cursor_shape, CURSOR_SHAPE_HOURGLASS, Display_all_screen(), Display_cursor(), Display_image_limits(), T_Config::Display_image_limits, Display_menu(), Draw_menu_button_frame(), File_error, Height, Hide_cursor, Init_mode_video(), Load_image(), Main_backups, Main_image_is_modified, Main_magnifier_mode, Main_offset_X, Main_offset_Y, Main_palette, Original_screen_X, Original_screen_Y, T_List_of_pages::Pages, Pixel_preview, Pixel_preview_normal, Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, Ratio_of_loaded_image, Resolution_in_command_line, Unselect_button(), Upload_infos_page_main(), Video_mode, and Width.
Referenced by Init_buttons(), and main().
void Backup_filename (char * fname, char * backup_name)
References Main_filename.
Referenced by Backup_existing_file().
void Backup_existing_file (void)
References Backup_filename(), File_error, File_exists(), Get_full_filename(), and MAX_PATH_CHARACTERS.
Referenced by Button_Autosave(), and Save_picture().
void Save_picture (byte image)
Save picture to file.
References T_Config::Backup, Backup_existing_file(), Brush_height, Brush_width, Button_Load_or_Save(), byte, Config, Confirmation_box(), Cursor_shape, CURSOR_SHAPE_HOURGLASS, Display_cursor(), Error, File_error, File_exists(), Get_fileformat(), Hide_cursor, Main_file_directory, Main_fileformat, Main_filename, Main_image_height, Main_image_width, Main_palette, MAX_PATH_CHARACTERS, Print_filename(), Save_image(), Set_palette(), and Swap_data_of_image_and_brush().
Referenced by Button_Brush_FX(), Button_Save(), and Main_handler().
void Button_Save (void)
Open the save file dialog.
References Save_picture().
Referenced by Init_buttons().
void Button_Autosave (void)
Saves the current file without asking for a new name.
References T_Config::Backup, Backup_existing_file(), BUTTON_SAVE, byte, Config, Confirmation_box(), Cursor_shape, CURSOR_SHAPE_HOURGLASS, Display_cursor(), Error, File_error, File_exists(), Get_full_filename(), Hide_cursor, MAX_PATH_CHARACTERS, Save_image(), and Unselect_button().
Referenced by Init_buttons().
void Button_Lines (void)
Callback for the lines button left click.
Selects lines drawing mode, depending on the current state of the lines button.
References Display_cursor(), Hide_cursor, Selected_line_mode, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Lines_switch_mode (void)
Callback for the lines button right click.
Cycles the drawing modes for the lines tool.
References BUTTON_LINES, Display_cursor(), Display_sprite_in_menu(), Hide_cursor, OPERATION_CENTERED_LINES, OPERATION_K_LIGNE, OPERATION_LINE, Selected_line_mode, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Brush (void)
Callback for the brush button left click.
Start the brush picking operation.
References BUTTON_BRUSH, Current_operation, Display_cursor(), Hide_cursor, OPERATION_GRAB_BRUSH, Start_operation_stack(), and Unselect_button().
Referenced by Init_buttons().
void Button_Unselect_brush (void)
Disables the custom brush and set back a regular one.
References Operation_before_interrupt, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Restore_brush (void)
Callback for the brush button right click.
Activates the last captured custom brush.
References BUTTON_BRUSH, BUTTON_POLYBRUSH, Change_paintbrush_shape(), Display_cursor(), Hide_cursor, PAINTBRUSH_SHAPE_COLOR_BRUSH, and Unselect_button().
Referenced by Init_buttons().
void Button_Lasso (void)
Callback for the freehand brush pick button left click.
Starts freehand brush picking operation.
References BUTTON_POLYBRUSH, Current_operation, Display_cursor(), Hide_cursor, OPERATION_POLYBRUSH, Paintbrush_shape, Paintbrush_shape_before_lasso, PAINTBRUSH_SHAPE_POINT, Start_operation_stack(), and Unselect_button().
Referenced by Init_buttons().
void Button_Unselect_lasso (void)
Disables the custom freehand brush and set back a regular one.
References Operation_before_interrupt, Paintbrush_shape, Paintbrush_shape_before_lasso, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Colorpicker (void)
Starts the color picking operation.
References BUTTON_COLORPICKER, Colorpicker_color, Current_operation, Display_cursor(), Hide_cursor, Main_magnifier_mode, Main_separator_position, Main_X_zoom, Menu_is_visible, Menu_Y, Mouse_X, Mouse_Y, Operation_before_interrupt, OPERATION_COLORPICK, OPERATION_REPLACE, Paintbrush_shape, Paintbrush_shape_before_colorpicker, PAINTBRUSH_SHAPE_POINT, Print_in_menu(), Start_operation_stack(), and Unselect_button().
Referenced by Init_buttons().
void Button_Unselect_colorpicker (void)
Disables the color picker button and get back to the previously selected drawing mode.
References Current_operation, Main_magnifier_mode, Main_separator_position, Main_X_zoom, Menu_is_visible, Menu_Y, Mouse_X, Mouse_Y, Operation_before_interrupt, OPERATION_COLORPICK, OPERATION_REPLACE, Paintbrush_shape, Paintbrush_shape_before_colorpicker, Print_in_menu(), and Start_operation_stack().
Referenced by Init_buttons().
void Button_Invert_foreback (void)
Swap fore- and background colors.
References Back_color, BUTTON_COLORPICKER, byte, Display_cursor(), Display_foreback(), Fore_color, Frame_menu_color(), Hide_cursor, Reposition_palette(), and Unselect_button().
Referenced by Init_buttons().
void Button_Magnify (void)
Enters magnify mode.
References BUTTON_MAGNIFIER, Compute_limits(), Compute_magnifier_data(), Compute_paintbrush_coordinates(), Config, Current_operation, Display_all_screen(), Display_cursor(), T_Config::Fast_zoom, Hide_cursor, Limit_bottom, Limit_right, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_magnifier_width, Main_offset_X, Main_offset_Y, Menu_Y, Mouse_X, Mouse_Y, Old_main_offset_X, Old_main_offset_Y, OPERATION_MAGNIFY, Pixel_preview, Pixel_preview_magnifier, Position_screen_according_to_zoom(), Start_operation_stack(), Unselect_button(), and Update_rect().
Referenced by Init_buttons().
void Button_Magnify_menu (void)
Displays magnify menu.
References BUTTON_HELP, BUTTON_MAGNIFIER, Change_magnifier_factor(), Close_window(), Current_operation, Display_all_screen(), Display_cursor(), Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, Main_magnifier_factor, Main_magnifier_mode, Main_separator_position, Menu_Y, Menu_Y_before_window, Open_window(), OPERATION_MAGNIFY, Screen_width, Select_button(), Unselect_button(), Update_rect(), Update_window_area, Window_clicked_button(), Window_height, Window_help(), Window_set_normal_button(), and Window_width.
Referenced by Init_buttons().
void Button_Unselect_magnifier (void)
Exit magnify mode.
References Compute_limits(), Compute_paintbrush_coordinates(), Display_all_screen(), Main_image_height, Main_image_width, Main_magnifier_mode, Main_offset_X, Main_offset_Y, Menu_Y, Old_main_offset_X, Old_main_offset_Y, Old_MX, Old_MY, Operation_before_interrupt, Pixel_preview, Pixel_preview_normal, Screen_width, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Snap_mode (void)
Callback for the Grid button (in the FX window) left click.
Toogle the grid.
References Compute_paintbrush_coordinates(), Display_cursor(), Hide_cursor, and Snap_mode.
Referenced by Button_Effects(), Button_Grid_menu(), and Main_handler().
void Button_Grid_menu (void)
Callback for the Grid button (in the FX window) right click.
Displays the grid setup menu.
References BUTTON_EFFECTS, BUTTON_HELP, Button_Snap_mode(), Close_window(), Display_cursor(), Is_shortcut(), Key, KEY_ESC, MC_Dark, MC_Light, Num2str(), Open_window(), Print_in_window(), Readline(), Snap_height, Snap_mode, Snap_offset_X, Snap_offset_Y, Snap_width, Update_window_area, Window_clicked_button(), Window_height, Window_help(), Window_input_content(), Window_set_input_button(), Window_set_normal_button(), Window_width, and word.
Referenced by Button_Effects(), and Main_handler().
void Button_Show_grid (void)
Callback to toggle the grid visible in the magnified view.
References Display_all_screen(), Display_cursor(), Hide_cursor, and Show_grid.
Referenced by Main_handler().
void Button_Brush_FX (void)
Display the Brush effects window.
References Block, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, BUTTON_BRUSH_EFFECTS, BUTTON_HELP, Close_window(), Config_Key, Display_cursor(), Flip_X_lowlevel(), Flip_Y_lowlevel(), Get_colors_from_brush(), Hide_cursor, Is_shortcut(), Key, KEY_ESC, Load_picture(), MC_Black, MC_Dark, MC_Light, Menu_factor_X, Menu_factor_Y, Nibble_brush(), Open_window(), OPERATION_DISTORT_BRUSH, OPERATION_ROTATE_BRUSH, OPERATION_STRETCH_BRUSH, Outline_brush(), Pixel_in_window(), Print_in_window(), Remap_brush(), Rotate_180_deg_lowlevel(), Rotate_90_deg(), Save_picture(), SPECIAL_BOTTOM_LEFT_ATTACHMENT, SPECIAL_BOTTOM_RIGHT_ATTACHMENT, SPECIAL_CENTER_ATTACHMENT, SPECIAL_DISTORT, SPECIAL_FLIP_X, SPECIAL_FLIP_Y, SPECIAL_GET_BRUSH_COLORS, SPECIAL_LOAD_BRUSH, SPECIAL_NIBBLE, SPECIAL_OUTLINE, SPECIAL_RECOLORIZE_BRUSH, SPECIAL_ROTATE_180, SPECIAL_ROTATE_90, SPECIAL_ROTATE_ANY_ANGLE, SPECIAL_SAVE_BRUSH, SPECIAL_STRETCH, SPECIAL_TOP_LEFT_ATTACHMENT, SPECIAL_TOP_RIGHT_ATTACHMENT, Start_operation_stack(), Unselect_button(), Update_window_area, Window_clicked_button(), Window_display_frame(), Window_height, Window_help(), Window_pos_X, Window_pos_Y, Window_set_normal_button(), and Window_width.
Referenced by Init_buttons().
void Button_Smooth_mode (void)
Callback for the Smooth button (in the FX window) right click.
Callback for the smooth button (in the FX window) left click.
Displays the smooth setup menu.
References Colorize_mode, Effect_function, Effect_smooth(), No_effect(), Quick_shade_mode, Shade_mode, Smear_mode, Smooth_mode, and Tiling_mode.
Referenced by Button_Effects(), Button_Smooth_menu(), and Main_handler().
void Button_Smooth_menu (void)
Display the menu for the smooth effect.
References BUTTON_EFFECTS, BUTTON_HELP, Button_Smooth_mode(), byte, Close_window(), Display_cursor(), Hide_cursor, Is_shortcut(), Key, KEY_ESC, MC_Black, MC_Light, Num2str(), Open_window(), Print_char_in_window(), Readline(), Smooth_matrix, Smooth_mode, SPECIAL_SMOOTH_MENU, Update_window_area, Window_clicked_button(), Window_display_frame(), Window_height, Window_help(), Window_input_content(), Window_set_input_button(), Window_set_normal_button(), and Window_width.
Referenced by Button_Effects(), and Main_handler().
void Button_Smear_mode (void)
Toogles the smear mode.
References Colorize_mode, Effect_function, No_effect(), Quick_shade_mode, Shade_mode, Smear_mode, Smooth_mode, and Tiling_mode.
Referenced by Button_Effects(), and Main_handler().
void Compute_colorize_table (void)
Computes the tables used by the transparency/colorize mode.
These tables are used to match the drawing color*picture color to the color that is painted on screen.
References Colorize_opacity, Factors_inv_table, Factors_table, and word.
Referenced by Button_Colorize_menu(), Init_program(), and Transparency_set().
void Button_Colorize_mode (void)
Callback for the Tranparency button (in the FX window) left click.
Toogles transparent drawing mode.
References Colorize_current_mode, Colorize_mode, Effect_additive_colorize(), Effect_function, Effect_interpolated_colorize(), Effect_substractive_colorize(), No_effect(), Quick_shade_mode, Shade_mode, Smooth_mode, and Tiling_mode.
Referenced by Button_Colorize_menu(), Button_Effects(), and Main_handler().
void Button_Colorize_display_selection (int mode)
References MC_Black, MC_Light, and Print_in_window().
Referenced by Button_Colorize_menu().
void Button_Colorize_menu (void)
Callback for the Transparency button (in the FX window) right click.
Displays the tranparency setup menu.
References Button_Colorize_display_selection(), Button_Colorize_mode(), BUTTON_EFFECTS, BUTTON_HELP, Close_window(), Colorize_current_mode, Colorize_mode, Colorize_opacity, Compute_colorize_table(), Display_cursor(), Hide_cursor, Is_shortcut(), Key, KEY_ESC, MC_Dark, MC_Light, Num2str(), Open_window(), Print_in_window(), Readline(), SPECIAL_COLORIZE_MENU, Update_window_area, Window_clicked_button(), Window_display_frame(), Window_height, Window_help(), Window_input_content(), Window_set_input_button(), Window_set_normal_button(), Window_special_button_list, and Window_width.
Referenced by Button_Effects(), and Main_handler().
void Button_Tiling_mode (void)
Callback for the Tiling button (in the FX window) left click.
Toogles tiling mode.
References Colorize_mode, Effect_function, Effect_tiling(), No_effect(), Quick_shade_mode, Shade_mode, Smear_mode, Smooth_mode, and Tiling_mode.
Referenced by Button_Effects(), Button_Tiling_menu(), and Main_handler().
void Button_Tiling_menu (void)
Callback for the Tiling button (in the FX window) right click.
Displays the tiling setup menu.
References Brush_height, Brush_width, BUTTON_EFFECTS, BUTTON_HELP, Button_Tiling_mode(), Close_window(), Display_cursor(), Is_shortcut(), Key, KEY_ESC, MC_Dark, MC_Light, Num2str(), Open_window(), Print_in_window(), Readline(), Tiling_mode, Tiling_offset_X, Tiling_offset_Y, Update_window_area, Window_clicked_button(), Window_height, Window_help(), Window_input_content(), Window_set_input_button(), Window_set_normal_button(), and Window_width.
Referenced by Button_Effects(), and Main_handler().
void Effects_off (void)
Callback for the command that turns off all drawaing effects.
References Colorize_mode, Effect_function, Mask_mode, No_effect(), Quick_shade_mode, Shade_mode, Sieve_mode, Smear_mode, Smooth_mode, Snap_mode, Stencil_mode, and Tiling_mode.
Referenced by Button_Effects(), and Main_handler().
void Transparency_set (byte amount)
Command that sets the transparency level.
References Colorize_current_mode, Colorize_mode, Colorize_opacity, Compute_colorize_table(), Config, T_Config::Double_key_speed, Effect_additive_colorize(), Effect_function, Effect_interpolated_colorize(), Effect_substractive_colorize(), Quick_shade_mode, Shade_mode, Smooth_mode, and Tiling_mode.
Referenced by Main_handler().
void Button_Curves (void)
Callback for the curves button left click.
Start curve operation according to the selected mode.
References Display_cursor(), Hide_cursor, Selected_curve_mode, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Curves_switch_mode (void)
Callback for the curves button right click.
Select the curve mode (1-point, 2-point)
References BUTTON_CURVES, Display_cursor(), Display_sprite_in_menu(), Hide_cursor, OPERATION_3_POINTS_CURVE, OPERATION_4_POINTS_CURVE, Selected_curve_mode, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Airbrush (void)
Callback for the spray button left click.
Start the spray operation.
References Display_cursor(), Hide_cursor, OPERATION_AIRBRUSH, and Start_operation_stack().
Referenced by Init_buttons().
void Refresh_airbrush_settings (byte selected_color, byte update_slider)
References Airbrush_multi_flow, MC_Black, MC_Light, Menu_factor_X, Menu_factor_Y, Num2str(), Print_in_window(), Update_rect(), Window_draw_slider(), Window_palette_button_list, Window_pos_X, Window_pos_Y, and Window_scroller_button_list.
Referenced by Button_Airbrush_menu().
void Button_Airbrush_menu (void)
Callback for the spray button right click.
Opens the spray's setup menu.
References Airbrush_delay, Airbrush_mode, Airbrush_mono_flow, Airbrush_multi_flow, Airbrush_size, BUTTON_AIRBRUSH, BUTTON_HELP, byte, Close_window(), Current_operation, Display_cursor(), Fore_color, Get_color_behind_window(), Hide_cursor, Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, MC_Black, MC_Dark, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, Mouse_K, Mouse_X, Mouse_Y, Num2str(), Open_window(), OPERATION_AIRBRUSH, Print_in_window(), Read_pixel, Readline(), Refresh_airbrush_settings(), Select_button(), Stencil_tag_color(), Stencil_update_color(), Update_rect(), Update_window_area, Wait_end_of_click(), Window_attribute2, Window_clear_tags(), Window_clicked_button(), Window_display_frame(), Window_height, Window_help(), Window_input_content(), Window_pos_X, Window_pos_Y, Window_set_input_button(), Window_set_normal_button(), Window_set_palette_button(), Window_set_scroller_button(), Window_width, and word.
Referenced by Init_buttons().
void Button_Sieve_mode (void)
Callback for the Sieve button (in the FX window) left click.
Toogle sieve mode.
References Sieve_mode.
Referenced by Button_Effects(), Button_Sieve_menu(), and Main_handler().
void Draw_sieve_scaled (short origin_x, short origin_y)
References Block, MC_Black, MC_Dark, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, Pixel, Sieve, Sieve_height, Sieve_width, Update_rect(), Window_pos_X, Window_pos_Y, and Window_special_button_list.
Referenced by Button_Sieve_menu().
void Draw_preset_sieve_patterns (void)
References Block, Gfx, MC_Black, MC_White, Menu_factor_X, Menu_factor_Y, Min(), T_Gui_skin::Sieve_pattern, ToWinH, ToWinL, ToWinX, ToWinY, Update_rect(), Window_pos_X, Window_pos_Y, and Zoom().
Referenced by Button_Sieve_menu().
void Copy_preset_sieve (byte index)
In the sieve window, copy one of the presets patterns to the current one.
Parameters:
index Index of the pattern to copy
References Gfx, Sieve, Sieve_height, T_Gui_skin::Sieve_pattern, and Sieve_width.
Referenced by Button_Sieve_menu(), and Init_program().
void Invert_trame (void)
In the sieve window, swaps black and white in the current pattern.
References byte, Sieve, Sieve_height, and Sieve_width.
Referenced by Button_Sieve_menu(), and Main_handler().
void Update_sieve_area (short x, short y)
References Menu_factor_X, Menu_factor_Y, and Update_rect().
Referenced by Button_Sieve_menu().
void Button_Sieve_menu (void)
Callback for the Sieve button (in the FX window) right click.
Displays the sieve setup menu.
References Back_color, Block, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, BUTTON_EFFECTS, BUTTON_HELP, Button_Sieve_mode(), byte, Change_paintbrush_shape(), Close_window(), Copy_preset_sieve(), Display_cursor(), Draw_preset_sieve_patterns(), Draw_sieve_scaled(), Fore_color, Hide_cursor, Invert_trame(), Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, MC_Black, MC_Dark, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, MOD_SHIFT, Mouse_K, Mouse_X, Mouse_Y, Num2str(), Open_window(), PAINTBRUSH_SHAPE_COLOR_BRUSH, Pixel_in_brush(), T_Normal_button::Pos_X, T_Normal_button::Pos_Y, Print_in_window(), Read_pixel_from_brush(), Sieve, Sieve_height, Sieve_mode, Sieve_width, Update_rect(), Update_sieve_area(), Update_window_area, Window_clicked_button(), Window_display_frame(), Window_display_frame_in(), Window_height, Window_help(), Window_pos_X, Window_pos_Y, Window_set_normal_button(), Window_set_repeatable_button(), Window_set_special_button(), Window_special_button_list, and Window_width.
Referenced by Button_Effects(), and Main_handler().
void Button_polygon (void)
Callback for the polyline button left click.
Starts drawing a polygon.
References Display_cursor(), Hide_cursor, OPERATION_POLYGON, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Polyform (void)
Callback for the polyline right click.
Starts drawing a polyform.
References Display_cursor(), Hide_cursor, OPERATION_POLYFORM, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Polyfill (void)
Callback for the polyfill button left click.
Starts drawing a filled polygon.
References Display_cursor(), Hide_cursor, OPERATION_POLYFILL, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Filled_polyform (void)
Callback for the polyfill button right click.
Starts drawing a filled polyform.
References Display_cursor(), Hide_cursor, OPERATION_FILLED_POLYFORM, and Start_operation_stack().
Referenced by Init_buttons().
void Button_Adjust (void)
Callback for the adjust picture button.
Start the adjust picture operation.
References Display_cursor(), Hide_cursor, OPERATION_SCROLL, and Start_operation_stack().
Referenced by Init_buttons().
void Display_effect_sprite (short sprite_number, short start_x, short start_y)
References T_Gui_skin::Effect_sprite, Gfx, Menu_factor_X, Menu_factor_Y, MENU_SPRITE_HEIGHT, MENU_SPRITE_WIDTH, Pixel_in_window(), ToWinX, ToWinY, and Update_rect().
Referenced by Button_Effects().
void Display_effect_state (short x, short y, char * label, byte state)
References Block, MC_Black, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, Print_in_window(), Window_pos_X, and Window_pos_Y.
Referenced by Button_Effects(), and Display_effect_states().
void Display_effect_states (void)
References Colorize_mode, Display_effect_state(), Mask_mode, Quick_shade_mode, Shade_mode, Sieve_mode, Smear_mode, Smooth_mode, Snap_mode, Stencil_mode, and Tiling_mode.
Referenced by Button_Effects().
void Display_feedback_state (void)
References Config, T_Config::FX_Feedback, MC_Black, MC_Light, and Print_in_window().
Referenced by Button_Effects().
void Button_Effects (void)
Callback for the effects button click.
Displays the effect selection menu.
!!
References Button_Colorize_menu(), Button_Colorize_mode(), BUTTON_EFFECTS, Button_Grid_menu(), BUTTON_HELP, Button_Mask_menu(), Button_Mask_mode(), Button_Quick_shade_menu(), Button_Quick_shade_mode(), Button_Shade_menu(), Button_Shade_mode(), Button_Sieve_menu(), Button_Sieve_mode(), Button_Smear_mode(), Button_Smooth_menu(), Button_Smooth_mode(), Button_Snap_mode(), Button_Stencil_menu(), Button_Stencil_mode(), Button_Tiling_menu(), Button_Tiling_mode(), byte, Close_window(), Colorize_mode, Config, Config_Key, Display_cursor(), Display_effect_sprite(), Display_effect_state(), Display_effect_states(), Display_feedback_state(), Effects_off(), T_Config::FX_Feedback, FX_feedback_screen, Hide_cursor, Input_sticky_control, Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, Main_screen, Mask_mode, MC_Dark, MC_Light, Open_window(), Print_in_window(), Quick_shade_mode, Screen_backup, Shade_mode, Sieve_mode, Smear_mode, Smooth_mode, Snap_mode, SPECIAL_COLORIZE_MODE, SPECIAL_GRID_MODE, SPECIAL_MASK_MODE, SPECIAL_QUICK_SHADE_MODE, SPECIAL_SHADE_MODE, SPECIAL_SIEVE_MODE, SPECIAL_SMEAR_MODE, SPECIAL_SMOOTH_MODE, SPECIAL_STENCIL_MODE, SPECIAL_TILING_MODE, Stencil_mode, Tiling_mode, Unselect_button(), Update_window_area, Window_attribute1, Window_clicked_button(), Window_get_clicked_button(), Window_height, Window_help(), Window_set_normal_button(), and Window_width.
Referenced by Init_buttons().
void Draw_one_font_name (word x, word y, word index, byte highlighted)
References Font_label(), MC_Black, MC_Dark, MC_Light, and Print_in_window().
Referenced by Button_Text().
void Button_Text (void)
Callback for the text button.
Opens the text setup window.
References T_Config::Auto_discontinuous, Back_color, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, BUTTON_DRAW, BUTTON_HELP, BUTTON_TEXT, byte, Change_paintbrush_shape(), Close_window(), Config, Current_operation, T_List_button::Cursor_position, Display_brush, Display_cursor(), Draw_one_font_name(), Error, T_Special_button::Height, Hide_cursor, Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, T_List_button::List_start, MC_Black, MC_Dark, MC_Light, Menu_factor_X, Menu_factor_Y, Min(), Nb_fonts, Num2str(), Open_window(), OPERATION_DISCONTINUOUS_DRAW, PAINTBRUSH_SHAPE_COLOR_BRUSH, PAINTBRUSH_SHAPE_MONO_BRUSH, T_Special_button::Pos_X, T_Special_button::Pos_Y, Print_in_window(), Readline(), Readline_ex(), Render_text(), RIGHT_SIDE, Select_button(), TrueType_font(), Unselect_button(), Update_rect(), Update_window_area, T_Special_button::Width, Window_attribute2, Window_clicked_button(), Window_display_frame_in(), Window_height, Window_help(), Window_input_content(), Window_pos_X, Window_pos_Y, Window_rectangle(), Window_redraw_list(), Window_set_input_button(), Window_set_list_button(), Window_set_normal_button(), Window_set_repeatable_button(), Window_set_scroller_button(), Window_set_special_button(), and Window_width.
Referenced by Init_buttons().
void Display_stored_brush_in_window (word x_pos, word y_pos, int index)
References Brush_container, BRUSH_CONTAINER_PREVIEW_HEIGHT, BRUSH_CONTAINER_PREVIEW_WIDTH, byte, T_Brush_template::Height, Height, MC_Black, MC_Light, Paintbrush_shape, PAINTBRUSH_SHAPE_MAX, PAINTBRUSH_SHAPE_MISC, Pixel_in_window(), T_Brush_template::Thumbnail, Update_window_area, T_Brush_template::Width, Width, and Window_rectangle().
Referenced by Button_Brush_container(), and Button_Paintbrush_menu().
void Store_brush (int index)
References T_Brush_template::Brush, Brush, Brush_container, BRUSH_CONTAINER_PREVIEW_HEIGHT, BRUSH_CONTAINER_PREVIEW_WIDTH, Brush_height, Brush_width, byte, Copy_part_of_image_to_another(), Error, T_Brush_template::Height, MAX_PAINTBRUSH_SIZE, Paintbrush_height, T_Brush_template::Paintbrush_shape, Paintbrush_shape, PAINTBRUSH_SHAPE_COLOR_BRUSH, PAINTBRUSH_SHAPE_MAX, PAINTBRUSH_SHAPE_MISC, PAINTBRUSH_SHAPE_MONO_BRUSH, Paintbrush_sprite, Paintbrush_width, Rescale(), T_Brush_template::Transp_color, and T_Brush_template::Width.
Referenced by Button_Brush_container(), and Button_Paintbrush_menu().
byte Restore_brush (int index)
References Brush, Brush_container, BRUSH_CONTAINER_PREVIEW_HEIGHT, BRUSH_CONTAINER_PREVIEW_WIDTH, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Change_paintbrush_shape(), Height, T_Brush_template::Height, MAX_PAINTBRUSH_SIZE, Paintbrush_height, Paintbrush_offset_X, Paintbrush_offset_Y, Paintbrush_shape, T_Brush_template::Paintbrush_shape, PAINTBRUSH_SHAPE_COLOR_BRUSH, PAINTBRUSH_SHAPE_HORIZONTAL_BAR, PAINTBRUSH_SHAPE_MAX, PAINTBRUSH_SHAPE_MISC, PAINTBRUSH_SHAPE_MONO_BRUSH, PAINTBRUSH_SHAPE_VERTICAL_BAR, Paintbrush_sprite, Paintbrush_width, Realloc_brush(), Set_paintbrush_size(), T_Brush_template::Thumbnail, Width, T_Brush_template::Width, and word.
Referenced by Button_Brush_container(), and Button_Paintbrush_menu().
void Button_Brush_container (void)
References BRUSH_CONTAINER_COLUMNS, BRUSH_CONTAINER_PREVIEW_HEIGHT, BRUSH_CONTAINER_PREVIEW_WIDTH, BRUSH_CONTAINER_ROWS, byte, Close_window(), Display_cursor(), Display_stored_brush_in_window(), Hide_cursor, KEY_ESC, Open_window(), Restore_brush(), RIGHT_SIDE, Store_brush(), Update_window_area, Window_attribute1, Window_clicked_button(), Window_height, Window_set_normal_button(), and Window_width.
Variable Documentation
char Program_version[]
Referenced by Button_Message_initial(), and Button_Stats().
short Old_MX
Referenced by Button_Unselect_magnifier(), Close_popup(), Close_window(), and Main_handler().
short Old_MY
Referenced by Button_Unselect_magnifier(), Close_popup(), Close_window(), and Main_handler().
T_Fileselector Skin_files_list
T_Fileselector Font_files_list
byte Old_black
byte Old_dark
byte Old_light
byte Old_white
byte Old_trans
byte Coming_from_zoom_factor_menu = 0
byte Smooth_default_matrices[4][3][3]
Initial value:
{
 { {1,2,1}, {2,4,2}, {1,2,1} },
 { {1,3,1}, {3,9,3}, {1,3,1} },
 { {0,1,0}, {1,2,1}, {0,1,0} },
 { {2,3,2}, {3,1,3}, {2,3,2} }
}