GrafX2: clavier.h File Reference
clavier.h File Reference
Functions
word Keysym_to_ANSI (SDL_keysym keysym)
Convert an SDL keysym to an ANSI/ASCII character.
word Keysym_to_keycode (SDL_keysym keysym)
Convert an SDL keysym to an internal keycode number.
word Key_for_scancode (word scancode)
Helper function to convert between SDL system and old coding for keycodes.
const char * Key_name (word Key)
Returns key name in a string.
word Key_modifiers (SDLMod mod)
Gets the modifiers in our format from the SDL_Mod information.
Function Documentation
word Keysym_to_ANSI (SDL_keysym keysym)
Convert an SDL keysym to an ANSI/ASCII character.
Parameters:
keysym SDL symbol to convert
Referenced by Handle_key_press().
word Keysym_to_keycode (SDL_keysym keysym)
Convert an SDL keysym to an internal keycode number.
This is needed because SDL tends to split the information across the unicode sym, the regular sym, and the raw keycode. We also need to differenciate 1 (keypad) and 1 (regular keyboard), and some other things.
Parameters:
keysym SDL symbol to convert
References Key_modifiers(), and word.
Referenced by Handle_key_press(), and Handle_key_release().
word Key_for_scancode (word scancode)
Helper function to convert between SDL system and old coding for keycodes.
This is needed because some SDL keycode are actually unicode and won't fit in 8 bits.
Parameters:
scancode Scancode to convert
References Scancode_to_sym.
Referenced by Load_CFG().
const char* Key_name (word Key)
Returns key name in a string.
Used to display them in the helpscreens and in the keymapper window.
Parameters:
Key keycode of the key to translate, including modifiers
References KEY_JOYBUTTON, KEY_MOUSEMIDDLE, KEY_MOUSEWHEELDOWN, KEY_MOUSEWHEELUP, Key_name(), MOD_ALT, MOD_CTRL, MOD_SHIFT, and word.
Referenced by Key_name(), Keyboard_shortcut_value(), and Window_set_shortcut().
word Key_modifiers (SDLMod mod)
Gets the modifiers in our format from the SDL_Mod information.
Parameters:
mod SDL modifiers state
References MOD_ALT, MOD_CTRL, MOD_SHIFT, and word.
Referenced by Handle_joystick_press(), Handle_mouse_click(), and Keysym_to_keycode().