GrafX2: engine.c File Reference
engine.c File Reference
: Window engine and interface management
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "const.h"
#include "struct.h"
#include "global.h"
#include "graph.h"
#include "misc.h"
#include "special.h"
#include "buttons.h"
#include "operatio.h"
#include "shade.h"
#include "errors.h"
#include "sdlscreen.h"
#include "windows.h"
#include "brush.h"
#include "input.h"
#include "engine.h"
#include "pages.h"
#include "layers.h"
#include "factory.h"
#include "loadsave.h"
#include "io.h"
Defines
#define SHADOW_RIGHT 3
#define SHADOW_BOTTOM 4
Functions
void Save_background (byte **buffer, int x_pos, int y_pos, int width, int height)
Save a screen block (usually before erasing it with a new window or a dropdown menu)
void Restore_background (byte *buffer, int x_pos, int y_pos, int width, int height)
Restores a screen block.
void Pixel_background (int x_pos, int y_pos, byte color)
Draw a pixel in a saved screen block (when you sort colors in the palette, for example)
int Button_under_mouse (void)
Guess the number of the button that was just clicked.
void Draw_menu_button (byte btn_number, byte pressed)
Draw a menu button, selected or not.
void Unselect_button (int btn_number)
Deselect a button.
void Select_button (int btn_number, byte click)
Select a button and disable all his family (for example, selecting "freehand" unselect "curves", "lines", ...)
void Move_separator (void)
Moves the splitbar between zoom and standard views.
void Status_print_palette_color (byte color)
Updates the status bar line with a color number.
void Main_handler (void)
Main handler for everything. This is the main loop of the program.
void Open_window (word width, word height, const char *title)
void Close_window (void)
void Window_draw_normal_bouton (word x_pos, word y_pos, word width, word height, const char *title, byte undersc_letter, byte clickable)
void Window_select_normal_button (word x_pos, word y_pos, word width, word height)
void Window_unselect_normal_button (word x_pos, word y_pos, word width, word height)
void Window_draw_palette_bouton (word x_pos, word y_pos)
void Window_clear_tags (void)
void Tag_color_range (byte start, byte end)
void Compute_slider_cursor_length (T_Scroller_button *button)
void Window_draw_slider (T_Scroller_button *button)
void Window_draw_scroller_button (T_Scroller_button *button)
void Window_draw_input_bouton (word x_pos, word y_pos, word width_in_characters)
void Window_input_content (T_Special_button *button, char *content)
void Window_clear_input_button (T_Special_button *button)
T_Normal_button * Window_set_normal_button (word x_pos, word y_pos, word width, word height, const char *title, byte undersc_letter, byte clickable, word shortcut)
T_Normal_button * Window_set_repeatable_button (word x_pos, word y_pos, word width, word height, const char *title, byte undersc_letter, byte clickable, word shortcut)
T_Palette_button * Window_set_palette_button (word x_pos, word y_pos)
T_Scroller_button * Window_set_scroller_button (word x_pos, word y_pos, word height, word nb_elements, word nb_elements_visible, word initial_position)
T_Scroller_button * Window_set_horizontal_scroller_button (word x_pos, word y_pos, word width, word nb_elements, word nb_elements_visible, word initial_position)
T_Special_button * Window_set_special_button (word x_pos, word y_pos, word width, word height)
T_Special_button * Window_set_input_button (word x_pos, word y_pos, word width_in_characters)
T_Dropdown_button * Window_set_dropdown_button (word x_pos, word y_pos, word width, word height, word dropdown_width, const char *label, byte display_choice, byte display_centered, byte display_arrow, byte active_button, byte bottom_up)
void Window_dropdown_add_item (T_Dropdown_button *dropdown, word btn_number, const char *label)
Adds an item to a dropdown menu.
void Window_dropdown_clear_items (T_Dropdown_button *dropdown)
T_List_button * Window_set_list_button (T_Special_button *entry_button, T_Scroller_button *scroller, Func_draw_list_item draw_list_item)
void Window_redraw_list (T_List_button *list)
void Open_popup (word x_pos, word y_pos, word width, word height)
void Close_popup (void)
byte Window_click_in_rectangle (short start_x, short start_y, short end_x, short end_y)
short Wait_click_in_palette (T_Palette_button *button)
void Get_color_behind_window (byte *color, byte *click)
void Move_window (short dx, short dy)
T_Dropdown_choice * Dropdown_activate (T_Dropdown_button *button, short off_x, short off_y)
Displays a dropped-down menu and handles the UI logic until the user releases a mouse button.
short Window_dropdown_on_click (T_Dropdown_button *button)
short Window_normal_button_onclick (word x_pos, word y_pos, word width, word height, short btn_number)
short Window_get_clicked_button (void)
short Window_get_button_shortcut (void)
short Window_clicked_button (void)
void Remap_window_backgrounds (byte *conversion_table, int Min_Y, int Max_Y)
void Delay_with_active_mouse (int speed)
Puts the user in wait mode for the specified time (in 1/100s), though the mouse still works.
Variables
short Old_MX = -1
short Old_MY = -1
byte Shade_mode_before_cancel
byte Quick_shade_mode_before_cancel
byte Stencil_mode_before_cancel
byte Sieve_mode_before_cancel
byte Colorize_mode_before_cancel
byte Smooth_mode_before_cancel
byte Tiling_mode_before_cancel
Func_effect Effect_function_before_cancel
byte * Window_background [8]
This table holds pointers to the saved window backgrounds. We can have up to 8 windows open at a time.
char * Menu_tooltip [NB_BUTTONS]
Table of tooltip texts for menu buttons.
Detailed Description
: Window engine and interface management
Define Documentation
#define SHADOW_RIGHT 3
Referenced by Dropdown_activate().
#define SHADOW_BOTTOM 4
Referenced by Dropdown_activate().
Function Documentation
void Save_background (byte ** buffer, int x_pos, int y_pos, int width, int height)
Save a screen block (usually before erasing it with a new window or a dropdown menu)
References byte, DEBUG, Error, Menu_factor_X, Menu_factor_Y, Pixel_width, and Read_line.
Referenced by Get_color_behind_window(), Move_window(), Open_popup(), and Open_window().
void Restore_background (byte * buffer, int x_pos, int y_pos, int width, int height)
Restores a screen block.
References Display_line_fast, Menu_factor_X, Menu_factor_Y, and Pixel_width.
Referenced by Close_popup(), Close_window(), Get_color_behind_window(), and Move_window().
void Pixel_background (int x_pos, int y_pos, byte color)
Draw a pixel in a saved screen block (when you sort colors in the palette, for example)
References Menu_factor_X, Pixel_width, Window_background, and Window_width.
Referenced by Display_menu_palette_avoiding_window().
int Button_under_mouse (void)
Guess the number of the button that was just clicked.
References BUTTON_SHAPE_NO_FRAME, BUTTON_SHAPE_RECTANGLE, BUTTON_SHAPE_TRIANGLE_BOTTOM_RIGHT, BUTTON_SHAPE_TRIANGLE_TOP_LEFT, Buttons_Pool, byte, Height, T_Menu_Bar::Last_button_index, Menu_bars, Menu_factor_X, Menu_factor_Y, Menu_Y, MENUBAR_COUNT, Mouse_X, Mouse_Y, Shape, Width, and X_offset.
Referenced by Button_Help(), Button_Select_backcolor(), Button_Select_forecolor(), and Main_handler().
void Draw_menu_button (byte btn_number, byte pressed)
Draw a menu button, selected or not.
References BUTTON_PAINTBRUSHES, BUTTON_SHAPE_NO_FRAME, BUTTON_SHAPE_RECTANGLE, BUTTON_SHAPE_TRIANGLE_BOTTOM_RIGHT, BUTTON_SHAPE_TRIANGLE_TOP_LEFT, Buttons_Pool, byte, Gfx, MAX_PAINTBRUSH_SIZE, MC_Black, Menu_bars, Menu_factor_X, Menu_factor_Y, Menu_is_visible, T_Gui_skin::Menu_sprite, MENU_SPRITE_WIDTH, Menu_Y, MENUBAR_COUNT, MENUBAR_TOOLS, Paintbrush_height, Paintbrush_offset_X, Paintbrush_offset_Y, Paintbrush_shape, PAINTBRUSH_SHAPE_COLOR_BRUSH, PAINTBRUSH_SHAPE_MONO_BRUSH, Paintbrush_sprite, Paintbrush_width, Pixel_in_menu_and_skin(), Shape, T_Menu_Bar::Skin, T_Menu_Bar::Skin_width, Update_rect(), word, X_offset, and Y_offset.
Referenced by Button_Curves_switch_mode(), Button_Draw_switch_mode(), Button_Kill(), Button_Lines_switch_mode(), Button_Page(), Button_Redo(), Button_Reload(), Button_Secondary_palette(), Button_Skins(), Button_Text(), Button_Undo(), Display_paintbrush_in_menu(), Init_program(), Load_picture(), Main_handler(), Select_button(), and Unselect_button().
void Unselect_button (int btn_number)
Deselect a button.
References BUTTON_RELEASED, Buttons_Pool, Draw_menu_button(), and Pressed.
Referenced by Button_Autosave(), Button_Brush(), Button_Brush_FX(), Button_Brush_monochrome(), Button_Clear(), Button_Clear_with_backcolor(), Button_Colorpicker(), Button_Copy_page(), Button_Effects(), Button_Gradients(), Button_Hide_menu(), Button_Invert_foreback(), Button_Kill(), Button_Lasso(), Button_Layer_add(), Button_Layer_down(), Button_Layer_get_transparent(), Button_Layer_menu(), Button_Layer_merge(), Button_Layer_remove(), Button_Layer_set_transparent(), Button_Layer_up(), Button_Load_or_Save(), Button_Magnify(), Button_Magnify_menu(), Button_Page(), Button_Paintbrush_menu(), Button_Pal_left(), Button_Pal_left_fast(), Button_Pal_right(), Button_Pal_right_fast(), Button_Palette(), Button_Quit(), Button_Redo(), Button_Reload(), Button_Resolution(), Button_Restore_brush(), Button_Safety_resolution(), Button_Secondary_palette(), Button_Settings(), Button_Skins(), Button_Stats(), Button_Text(), Button_Toggle_all_toolbars(), Button_Toggle_toolbar(), Button_Transform_menu(), Button_Undo(), Colorpicker_0_1(), Select_button(), Window_help(), and Zoom_set().
void Select_button (int btn_number, byte click)
Select a button and disable all his family (for example, selecting "freehand" unselect "curves", "lines", ...)
References BUTTON_ADJUST, BUTTON_CIRCLES, BUTTON_FILLCIRC, BUTTON_FLOODFILL, BUTTON_GRADRECT, BUTTON_MAGNIFIER, BUTTON_POLYFILL, BUTTON_POLYGONS, BUTTON_PRESSED, BUTTON_RELEASED, BUTTON_SHAPE_TRIANGLE_BOTTOM_RIGHT, BUTTON_SHAPE_TRIANGLE_TOP_LEFT, BUTTON_SPHERES, Buttons_Pool, Display_cursor(), Display_sprite_in_menu(), Draw_menu_button(), Family, FAMILY_INTERRUPTION, FAMILY_TOOLBAR, Hide_cursor, Left_instant, Main_magnifier_mode, MENU_SPRITE_ELLIPSES, MENU_SPRITE_GRAD_ELLIPSE, MENU_SPRITE_POLYFORM, MENU_SPRITE_REPLACE, NB_BUTTONS, Pressed, Right_instant, RIGHT_SIDE, Shape, Unselect_button(), and Wait_end_of_click().
Referenced by Button_Airbrush_menu(), Button_Magnify_menu(), Button_Palette(), Button_Text(), Init_program(), Load_picture(), Main_handler(), Return_to_draw_mode(), and Zoom_set().
void Move_separator (void)
Moves the splitbar between zoom and standard views.
References byte, Compute_limits(), Compute_magnifier_data(), Compute_separator_data(), Cursor_shape, CURSOR_SHAPE_HORIZONTAL, Display_all_screen(), Display_cursor(), Get_input(), Hide_cursor, Main_separator_position, Main_separator_proportion, Main_X_zoom, Menu_Y, Mouse_K, Mouse_X, Position_screen_according_to_zoom(), Screen_width, Update_rect(), Vertical_XOR_line, and Windows_open.
Referenced by Main_handler().
void Status_print_palette_color (byte color)
Updates the status bar line with a color number.
Used when hovering the menu palette.
References BUTTON_CHOOSE_COL, Main_palette, Menu_tooltip, and Print_in_menu().
Referenced by Button_Select_backcolor(), Button_Select_forecolor(), and Main_handler().
void Main_handler (void)
Main handler for everything. This is the main loop of the program.
References Allow_color_change_during_operation, Bigger_paintbrush(), Block, Brush, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, BUTTON_CHOOSE_COL, Button_Colorize_menu(), Button_Colorize_mode(), BUTTON_DRAW, BUTTON_EFFECTS, Button_Grid_menu(), Button_Mask_menu(), Button_Mask_mode(), Button_Quick_shade_menu(), Button_Quick_shade_mode(), Button_Quit(), Button_Shade_menu(), Button_Shade_mode(), Button_Show_grid(), Button_Sieve_menu(), Button_Sieve_mode(), Button_Smear_mode(), Button_Smooth_menu(), Button_Smooth_mode(), Button_Snap_mode(), Button_Stencil_menu(), Button_Stencil_mode(), Button_Tiling_menu(), Button_Tiling_mode(), Button_under_mouse(), byte, Change_paintbrush_shape(), Colorize_mode, Compute_limits(), Compute_optimal_menu_colors(), Compute_paintbrush_coordinates(), Config, Confirmation_box(), Current_operation, Cursor_hidden, Cursor_in_menu, Cursor_in_menu_previous, Cursor_shape, CURSOR_SHAPE_HOURGLASS, Cycling_mode, Destroy_context(), Display_all_screen(), Display_cursor(), Display_image_limits(), T_Config::Display_image_limits, Display_menu(), Draw_menu_button(), Drop_file_name, dword, Effects_off(), End_of_modification(), Exclude_color, File_error, Find_last_slash(), First_color_in_palette, Flip_X_lowlevel(), Flip_Y_lowlevel(), Get_colors_from_brush(), Get_input(), Hide_cursor, Init_context_layered_image(), Init_mode_video(), Invert_trame(), Is_shortcut(), Key, Layer_activate(), LEFT_SIDE, Load_image(), Load_picture(), Main_backups, Main_image_is_modified, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_width, Main_palette, Main_separator_position, Main_X_zoom, Mask_mode, MC_Light, Menu_factor_X, Menu_factor_Y, Menu_is_visible, Menu_status_Y, Menu_tag_colors(), Menu_tooltip, Menu_Y, Mouse_K, Mouse_K_unique, Mouse_X, Mouse_Y, Move_separator(), NB_BUTTONS, NB_SPECIAL_SHORTCUTS, Nibble_brush(), Old_MX, Old_MY, Operation, OPERATION_COLORPICK, OPERATION_CONTINUOUS_DRAW, OPERATION_DISTORT_BRUSH, OPERATION_REPLACE, OPERATION_ROTATE_BRUSH, Operation_stack_size, OPERATION_STRETCH_BRUSH, Outline_brush(), T_List_of_pages::Pages, Paintbrush_shape, PAINTBRUSH_SHAPE_COLOR_BRUSH, PAINTBRUSH_SHAPE_MONO_BRUSH, PAINTBRUSH_SHAPE_ROUND, Pick_color_in_palette(), Pixel_ratio, Print_in_menu(), Quick_shade_mode, Quit_is_required, Quitting, Redraw_layered_image(), Remap_brush(), Repeat_script(), Reposition_palette(), Resize_height, Resize_width, RIGHT_SIDE, Rotate_180_deg_lowlevel(), Rotate_90_deg(), Run_numbered_script(), Save_picture(), Screen_height, Screen_width, Scroll_magnifier(), Scroll_screen(), Select_button(), Set_paintbrush_size(), Set_palette(), Shade_mode, Sieve_mode, Smaller_paintbrush(), Smear_mode, Smooth_mode, Snap_mode, SPECIAL_BIGGER_PAINTBRUSH, SPECIAL_BOTTOM_LEFT_ATTACHMENT, SPECIAL_BOTTOM_RIGHT_ATTACHMENT, SPECIAL_BRUSH_DOUBLE, SPECIAL_BRUSH_DOUBLE_HEIGHT, SPECIAL_BRUSH_DOUBLE_WIDTH, SPECIAL_BRUSH_HALVE, SPECIAL_CENTER_ATTACHMENT, SPECIAL_CLICK_RIGHT, SPECIAL_COLORIZE_MENU, SPECIAL_COLORIZE_MODE, SPECIAL_CONTINUOUS_DRAW, SPECIAL_CYCLE_MODE, SPECIAL_DISTORT, SPECIAL_DOT_PAINTBRUSH, SPECIAL_EFFECTS_OFF, SPECIAL_EXCLUDE_COLORS_MENU, SPECIAL_FLIP_X, SPECIAL_FLIP_Y, SPECIAL_GET_BRUSH_COLORS, SPECIAL_GRID_MENU, SPECIAL_GRID_MODE, SPECIAL_INVERT_SIEVE, SPECIAL_LAYER1_SELECT, SPECIAL_LAYER1_TOGGLE, SPECIAL_LAYER2_SELECT, SPECIAL_LAYER2_TOGGLE, SPECIAL_LAYER3_SELECT, SPECIAL_LAYER3_TOGGLE, SPECIAL_LAYER4_SELECT, SPECIAL_LAYER4_TOGGLE, SPECIAL_LAYER5_SELECT, SPECIAL_LAYER5_TOGGLE, SPECIAL_LAYER6_SELECT, SPECIAL_LAYER6_TOGGLE, SPECIAL_LAYER7_SELECT, SPECIAL_LAYER7_TOGGLE, SPECIAL_LAYER8_SELECT, SPECIAL_LAYER8_TOGGLE, SPECIAL_LOAD_BRUSH, SPECIAL_MASK_MENU, SPECIAL_MASK_MODE, Special_next_backcolor(), SPECIAL_NEXT_BACKCOLOR, Special_next_forecolor(), SPECIAL_NEXT_FORECOLOR, Special_next_user_backcolor(), SPECIAL_NEXT_USER_BACKCOLOR, Special_next_user_forecolor(), SPECIAL_NEXT_USER_FORECOLOR, SPECIAL_NIBBLE, SPECIAL_OUTLINE, Special_previous_backcolor(), SPECIAL_PREVIOUS_BACKCOLOR, Special_previous_forecolor(), SPECIAL_PREVIOUS_FORECOLOR, Special_previous_user_backcolor(), SPECIAL_PREVIOUS_USER_BACKCOLOR, Special_previous_user_forecolor(), SPECIAL_PREVIOUS_USER_FORECOLOR, SPECIAL_QUICK_SHADE_MENU, SPECIAL_QUICK_SHADE_MODE, SPECIAL_RECOLORIZE_BRUSH, SPECIAL_REPEAT_SCRIPT, SPECIAL_ROTATE_180, SPECIAL_ROTATE_90, SPECIAL_ROTATE_ANY_ANGLE, SPECIAL_RUN_SCRIPT_1, SPECIAL_RUN_SCRIPT_10, SPECIAL_RUN_SCRIPT_2, SPECIAL_RUN_SCRIPT_3, SPECIAL_RUN_SCRIPT_4, SPECIAL_RUN_SCRIPT_5, SPECIAL_RUN_SCRIPT_6, SPECIAL_RUN_SCRIPT_7, SPECIAL_RUN_SCRIPT_8, SPECIAL_RUN_SCRIPT_9, SPECIAL_SAVE_BRUSH, SPECIAL_SCROLL_DOWN, SPECIAL_SCROLL_DOWN_FAST, SPECIAL_SCROLL_DOWN_SLOW, SPECIAL_SCROLL_LEFT, SPECIAL_SCROLL_LEFT_FAST, SPECIAL_SCROLL_LEFT_SLOW, SPECIAL_SCROLL_RIGHT, SPECIAL_SCROLL_RIGHT_FAST, SPECIAL_SCROLL_RIGHT_SLOW, SPECIAL_SCROLL_UP, SPECIAL_SCROLL_UP_FAST, SPECIAL_SCROLL_UP_SLOW, SPECIAL_SHADE_MENU, SPECIAL_SHADE_MODE, SPECIAL_SHOW_GRID, SPECIAL_SHOW_HIDE_CURSOR, SPECIAL_SIEVE_MENU, SPECIAL_SIEVE_MODE, SPECIAL_SMALLER_PAINTBRUSH, SPECIAL_SMEAR_MODE, SPECIAL_SMOOTH_MENU, SPECIAL_SMOOTH_MODE, SPECIAL_STENCIL_MENU, SPECIAL_STENCIL_MODE, SPECIAL_STRETCH, SPECIAL_TILING_MENU, SPECIAL_TILING_MODE, SPECIAL_TOP_LEFT_ATTACHMENT, SPECIAL_TOP_RIGHT_ATTACHMENT, SPECIAL_TRANSPARENCY_0, SPECIAL_TRANSPARENCY_1, SPECIAL_TRANSPARENCY_2, SPECIAL_TRANSPARENCY_3, SPECIAL_TRANSPARENCY_4, SPECIAL_TRANSPARENCY_5, SPECIAL_TRANSPARENCY_6, SPECIAL_TRANSPARENCY_7, SPECIAL_TRANSPARENCY_8, SPECIAL_TRANSPARENCY_9, SPECIAL_ZOOM_1, SPECIAL_ZOOM_10, SPECIAL_ZOOM_12, SPECIAL_ZOOM_14, SPECIAL_ZOOM_16, SPECIAL_ZOOM_18, SPECIAL_ZOOM_2, SPECIAL_ZOOM_20, SPECIAL_ZOOM_3, SPECIAL_ZOOM_4, SPECIAL_ZOOM_5, SPECIAL_ZOOM_6, SPECIAL_ZOOM_8, SPECIAL_ZOOM_IN, SPECIAL_ZOOM_OUT, Start_operation_stack(), Status_print_palette_color(), Stencil_mode, Stretch_brush(), Tiling_mode, Transparency_set(), Update_rect(), Upload_infos_page_main(), Zoom(), and Zoom_set().
Referenced by main().
void Open_window (word width, word height, const char * title)
References Allow_colorcycling, Allow_drag_and_drop(), Block, Cursor_shape, CURSOR_SHAPE_ARROW, Cursor_shape_before_window, Hide_cursor, Main_palette, MC_Black, MC_Dark, MC_Light, MC_White, MC_Window, Menu_factor_X, Menu_factor_Y, Menu_is_visible, Menu_is_visible_before_window, Menu_Y, Menu_Y_before_window, Paintbrush_hidden, Paintbrush_hidden_before_window, Print_in_window_limited(), Save_background(), Screen_height, Screen_width, Set_palette(), Window_background, Window_display_frame_mono(), Window_display_frame_out(), Window_draggable, Window_dropdown_button_list, Window_height, Window_nb_buttons, Window_normal_button_list, Window_palette_button_list, Window_pos_X, Window_pos_Y, Window_scroller_button_list, Window_special_button_list, Window_width, and Windows_open.
Referenced by Button_Airbrush_menu(), Button_Brush_container(), Button_Brush_FX(), Button_Colorize_menu(), Button_Copy_page(), Button_Effects(), Button_Gradients(), Button_Grid_menu(), Button_Layer_menu(), Button_Load_or_Save(), Button_Message_initial(), Button_Paintbrush_menu(), Button_Palette(), Button_Quick_shade_menu(), Button_Quit_local_function(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Skins(), Button_Smooth_menu(), Button_Stats(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Confirmation_box(), Menu_shade(), Menu_tag_colors(), Message_out_of_memory(), Requester_window(), Save_C64_window(), Verbose_message(), Warning_message(), Window_help(), Window_Histogram(), and Window_set_shortcut().
void Close_window (void)
References Allow_colorcycling, Allow_drag_and_drop(), Compute_paintbrush_coordinates(), Cursor_shape, Cursor_shape_before_window, Display_all_screen(), Display_menu(), Hide_cursor, Key, Menu_factor_X, Menu_factor_Y, Menu_is_visible, Menu_is_visible_before_window, Menu_Y, Menu_Y_before_window, Mouse_K, Old_MX, Old_MY, Paintbrush_hidden, Paintbrush_hidden_before_window, Restore_background(), Update_rect(), Window_background, Window_dropdown_button_list, Window_dropdown_clear_items(), Window_height, Window_list_button_list, Window_normal_button_list, Window_palette_button_list, Window_pos_X, Window_pos_Y, Window_scroller_button_list, Window_special_button_list, Window_width, and Windows_open.
Referenced by Button_Airbrush_menu(), Button_Brush_container(), Button_Brush_FX(), Button_Colorize_menu(), Button_Copy_page(), Button_Effects(), Button_Gradients(), Button_Grid_menu(), Button_Layer_menu(), Button_Load_or_Save(), Button_Message_initial(), Button_Paintbrush_menu(), Button_Palette(), Button_Quick_shade_menu(), Button_Quit_local_function(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Skins(), Button_Smooth_menu(), Button_Stats(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Confirmation_box(), Menu_shade(), Menu_tag_colors(), Message_out_of_memory(), Requester_window(), Save_C64_window(), Verbose_message(), Warning_message(), Window_help(), Window_Histogram(), and Window_set_shortcut().
void Window_draw_normal_bouton (word x_pos, word y_pos, word width, word height, const char * title, byte undersc_letter, byte clickable)
References Block, byte, MC_Black, MC_Dark, MC_Light, Menu_factor_X, Menu_factor_Y, Print_in_window(), Window_display_frame_generic(), Window_display_frame_mono(), Window_display_frame_out(), Window_pos_X, Window_pos_Y, and word.
Referenced by Button_Palette(), Button_Resolution(), Window_set_dropdown_button(), Window_set_normal_button(), and Window_set_repeatable_button().
void Window_select_normal_button (word x_pos, word y_pos, word width, word height)
References MC_Black, MC_Dark, Menu_factor_X, Menu_factor_Y, Update_rect(), Window_display_frame_generic(), Window_pos_X, and Window_pos_Y.
Referenced by Window_dropdown_on_click(), Window_get_button_shortcut(), Window_get_clicked_button(), and Window_normal_button_onclick().
void Window_unselect_normal_button (word x_pos, word y_pos, word width, word height)
References Menu_factor_X, Menu_factor_Y, Update_rect(), Window_display_frame_out(), Window_pos_X, and Window_pos_Y.
Referenced by Window_dropdown_on_click(), Window_get_button_shortcut(), Window_get_clicked_button(), and Window_normal_button_onclick().
void Window_draw_palette_bouton (word x_pos, word y_pos)
References Block, Menu_factor_X, Menu_factor_Y, Window_display_frame(), Window_pos_X, Window_pos_Y, and word.
Referenced by Button_Palette(), and Window_set_palette_button().
void Window_clear_tags (void)
References Block, MC_Light, Menu_factor_X, Menu_factor_Y, ToWinH, ToWinL, Update_rect(), Window_palette_button_list, Window_pos_X, Window_pos_Y, and word.
Referenced by Button_Airbrush_menu().
void Tag_color_range (byte start, byte end)
References MC_Black, MC_Light, Pixel_in_window(), Update_window_area, Window_palette_button_list, Window_rectangle(), and word.
Referenced by Button_Gradients(), Button_Palette(), and Menu_shade().
void Compute_slider_cursor_length (T_Scroller_button * button)
References T_Scroller_button::Cursor_length, T_Scroller_button::Length, T_Scroller_button::Nb_elements, and T_Scroller_button::Nb_visibles.
Referenced by Prepare_and_display_filelist(), Scroll_help(), Set_palette_slider(), Window_help(), Window_set_horizontal_scroller_button(), and Window_set_scroller_button().
void Window_draw_slider (T_Scroller_button * button)
References T_Scroller_button::Cursor_length, T_Scroller_button::Is_horizontal, T_Scroller_button::Length, MC_Black, MC_OnBlack, T_Scroller_button::Nb_elements, T_Scroller_button::Nb_visibles, T_Scroller_button::Pos_X, T_Scroller_button::Pos_Y, T_Scroller_button::Position, Update_window_area, Window_rectangle(), and word.
Referenced by Button_Gradients(), Button_Palette(), Button_Secondary_palette(), Button_Settings(), Draw_all_palette_sliders(), Prepare_and_display_filelist(), Quicksearch_list(), Refresh_airbrush_settings(), Scroll_fileselector(), Scroll_help(), Scroll_list_of_modes(), Set_palette_slider(), Window_clicked_button(), Window_draw_scroller_button(), Window_get_clicked_button(), and Window_help().
void Window_draw_scroller_button (T_Scroller_button * button)
References T_Scroller_button::Is_horizontal, T_Scroller_button::Length, MC_Black, MC_Dark, MC_Light, T_Scroller_button::Pos_X, T_Scroller_button::Pos_Y, Print_in_window(), Window_display_frame_generic(), Window_display_frame_mono(), Window_display_frame_out(), and Window_draw_slider().
Referenced by Window_set_horizontal_scroller_button(), and Window_set_scroller_button().
void Window_draw_input_bouton (word x_pos, word y_pos, word width_in_characters)
References Window_display_frame_in().
Referenced by Window_set_input_button().
void Window_input_content (T_Special_button * button, char * content)
References MC_Black, MC_Light, T_Special_button::Pos_X, T_Special_button::Pos_Y, Print_in_window_limited(), and T_Special_button::Width.
Referenced by Button_Airbrush_menu(), Button_Colorize_menu(), Button_Grid_menu(), Button_Quick_shade_menu(), Button_Resolution(), Button_Smooth_menu(), Button_Text(), Button_Tiling_menu(), and Menu_shade().
void Window_clear_input_button (T_Special_button * button)
References Block, MC_Light, Menu_factor_X, Menu_factor_Y, T_Special_button::Pos_X, T_Special_button::Pos_Y, Update_rect(), T_Special_button::Width, Window_pos_X, and Window_pos_Y.
T_Normal_button* Window_set_normal_button (word x_pos, word y_pos, word width, word height, const char * title, byte undersc_letter, byte clickable, word shortcut)
References T_Normal_button::Clickable, T_Normal_button::Height, T_Normal_button::Next, T_Normal_button::Number, T_Normal_button::Pos_X, T_Normal_button::Pos_Y, T_Normal_button::Repeatable, T_Normal_button::Shortcut, T_Normal_button::Width, Window_draw_normal_bouton(), Window_nb_buttons, and Window_normal_button_list.
Referenced by Button_Airbrush_menu(), Button_Brush_container(), Button_Brush_FX(), Button_Colorize_menu(), Button_Copy_page(), Button_Effects(), Button_Gradients(), Button_Grid_menu(), Button_Layer_menu(), Button_Load_or_Save(), Button_Paintbrush_menu(), Button_Palette(), Button_Quick_shade_menu(), Button_Quit_local_function(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Skins(), Button_Smooth_menu(), Button_Stats(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Confirmation_box(), Menu_shade(), Menu_tag_colors(), Message_out_of_memory(), Readline_ex(), Requester_window(), Save_C64_window(), Verbose_message(), Warning_message(), Window_help(), Window_Histogram(), and Window_set_shortcut().
T_Normal_button* Window_set_repeatable_button (word x_pos, word y_pos, word width, word height, const char * title, byte undersc_letter, byte clickable, word shortcut)
References T_Normal_button::Height, T_Normal_button::Next, T_Normal_button::Number, T_Normal_button::Pos_X, T_Normal_button::Pos_Y, T_Normal_button::Repeatable, T_Normal_button::Shortcut, T_Normal_button::Width, Window_draw_normal_bouton(), Window_nb_buttons, and Window_normal_button_list.
Referenced by Button_Palette(), Button_Sieve_menu(), and Button_Text().
T_Palette_button* Window_set_palette_button (word x_pos, word y_pos)
References T_Palette_button::Next, T_Palette_button::Number, T_Palette_button::Pos_X, T_Palette_button::Pos_Y, Window_draw_palette_bouton(), Window_nb_buttons, and Window_palette_button_list.
Referenced by Button_Airbrush_menu(), Button_Gradients(), Button_Palette(), Menu_shade(), and Menu_tag_colors().
T_Scroller_button* Window_set_scroller_button (word x_pos, word y_pos, word height, word nb_elements, word nb_elements_visible, word initial_position)
References Compute_slider_cursor_length(), T_Scroller_button::Is_horizontal, T_Scroller_button::Length, T_Scroller_button::Nb_elements, T_Scroller_button::Nb_visibles, T_Scroller_button::Next, T_Scroller_button::Number, T_Scroller_button::Pos_X, T_Scroller_button::Pos_Y, T_Scroller_button::Position, Window_draw_scroller_button(), Window_nb_buttons, and Window_scroller_button_list.
Referenced by Button_Airbrush_menu(), Button_Gradients(), Button_Load_or_Save(), Button_Palette(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Skins(), Button_Text(), Menu_shade(), and Window_help().
T_Scroller_button* Window_set_horizontal_scroller_button (word x_pos, word y_pos, word width, word nb_elements, word nb_elements_visible, word initial_position)
References Compute_slider_cursor_length(), T_Scroller_button::Is_horizontal, T_Scroller_button::Length, T_Scroller_button::Nb_elements, T_Scroller_button::Nb_visibles, T_Scroller_button::Next, T_Scroller_button::Number, T_Scroller_button::Pos_X, T_Scroller_button::Pos_Y, T_Scroller_button::Position, Window_draw_scroller_button(), Window_nb_buttons, and Window_scroller_button_list.
Referenced by Button_Gradients().
T_Special_button* Window_set_special_button (word x_pos, word y_pos, word width, word height)
References T_Special_button::Height, T_Special_button::Next, T_Special_button::Number, T_Special_button::Pos_X, T_Special_button::Pos_Y, T_Special_button::Width, Window_nb_buttons, and Window_special_button_list.
Referenced by Button_Load_or_Save(), Button_Resolution(), Button_Settings(), Button_Sieve_menu(), Button_Skins(), Button_Text(), Menu_shade(), Window_help(), Window_Histogram(), and Window_set_input_button().
T_Special_button* Window_set_input_button (word x_pos, word y_pos, word width_in_characters)
References Window_draw_input_bouton(), and Window_set_special_button().
Referenced by Button_Airbrush_menu(), Button_Colorize_menu(), Button_Grid_menu(), Button_Load_or_Save(), Button_Quick_shade_menu(), Button_Resolution(), Button_Smooth_menu(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Menu_shade(), and Requester_window().
T_Dropdown_button* Window_set_dropdown_button (word x_pos, word y_pos, word width, word height, word dropdown_width, const char * label, byte display_choice, byte display_centered, byte display_arrow, byte active_button, byte bottom_up)
References T_Dropdown_button::Active_button, T_Dropdown_button::Bottom_up, T_Dropdown_button::Display_arrow, T_Dropdown_button::Display_centered, T_Dropdown_button::Display_choice, T_Dropdown_button::Dropdown_width, T_Dropdown_button::First_item, T_Dropdown_button::Height, ICON_DROPDOWN, MC_Black, MC_Light, T_Dropdown_button::Next, T_Dropdown_button::Number, T_Dropdown_button::Pos_X, T_Dropdown_button::Pos_Y, Print_in_window(), T_Dropdown_button::Width, Window_display_icon_sprite(), Window_draw_normal_bouton(), Window_dropdown_button_list, and Window_nb_buttons.
Referenced by Button_Load_or_Save(), Button_Paintbrush_menu(), Button_Palette(), Button_Resolution(), Button_Skins(), Button_Transform_menu(), and Save_C64_window().
void Window_dropdown_add_item (T_Dropdown_button * dropdown, word btn_number, const char * label)
Adds an item to a dropdown menu.
References T_Dropdown_button::First_item, T_Dropdown_choice::Label, T_Dropdown_choice::Next, and T_Dropdown_choice::Number.
Referenced by Button_Load_or_Save(), Button_Magnify_menu(), Button_Paintbrush_menu(), Button_Palette(), Button_Resolution(), Button_Skins(), Button_Toggle_toolbar(), Button_Transform_menu(), Display_bookmark(), and Save_C64_window().
void Window_dropdown_clear_items (T_Dropdown_button * dropdown)
References T_Dropdown_button::First_item, and T_Dropdown_choice::Next.
Referenced by Button_Magnify_menu(), Button_Palette(), Button_Toggle_toolbar(), Close_popup(), Close_window(), Display_bookmark(), and Save_C64_window().
T_List_button* Window_set_list_button (T_Special_button * entry_button, T_Scroller_button * scroller, Func_draw_list_item draw_list_item)
References T_List_button::Cursor_position, T_List_button::Draw_list_item, T_List_button::Entry_button, T_List_button::List_start, T_List_button::Next, T_List_button::Number, T_List_button::Scroller, Window_list_button_list, and Window_nb_buttons.
Referenced by Button_Skins(), and Button_Text().
void Window_redraw_list (T_List_button * list)
References T_List_button::Cursor_position, T_List_button::Draw_list_item, T_List_button::Entry_button, T_List_button::List_start, MC_Light, Min(), T_Scroller_button::Nb_elements, T_Scroller_button::Nb_visibles, T_Special_button::Pos_X, T_Special_button::Pos_Y, T_List_button::Scroller, T_Special_button::Width, and Window_rectangle().
Referenced by Button_Skins(), Button_Text(), Quicksearch_list(), and Window_clicked_button().
void Open_popup (word x_pos, word y_pos, word width, word height)
References Cursor_shape, CURSOR_SHAPE_ARROW, Cursor_shape_before_window, Menu_is_visible, Menu_is_visible_before_window, Menu_Y, Menu_Y_before_window, Paintbrush_hidden, Paintbrush_hidden_before_window, Save_background(), Screen_height, Window_background, Window_draggable, Window_dropdown_button_list, Window_height, Window_nb_buttons, Window_normal_button_list, Window_palette_button_list, Window_pos_X, Window_pos_Y, Window_scroller_button_list, Window_special_button_list, Window_width, and Windows_open.
Referenced by Dropdown_activate(), and Init_virtual_keyboard().
void Close_popup (void)
References Compute_paintbrush_coordinates(), Cursor_shape, Cursor_shape_before_window, Display_all_screen(), Display_menu(), Hide_cursor, Key, Menu_factor_X, Menu_factor_Y, Menu_is_visible, Menu_is_visible_before_window, Menu_Y, Menu_Y_before_window, Mouse_K, Old_MX, Old_MY, Paintbrush_hidden, Paintbrush_hidden_before_window, Restore_background(), Update_rect(), Window_background, Window_dropdown_button_list, Window_dropdown_clear_items(), Window_height, Window_list_button_list, Window_normal_button_list, Window_palette_button_list, Window_pos_X, Window_pos_Y, Window_scroller_button_list, Window_special_button_list, Window_width, and Windows_open.
Referenced by Dropdown_activate(), and Readline_ex().
byte Window_click_in_rectangle (short start_x, short start_y, short end_x, short end_y)
References Menu_factor_X, Menu_factor_Y, Mouse_X, Mouse_Y, Window_pos_X, and Window_pos_Y.
Referenced by Dropdown_activate(), Wait_click_in_palette(), Wait_click_in_shade_table(), Window_get_clicked_button(), Window_Histogram(), and Window_normal_button_onclick().
short Wait_click_in_palette (T_Palette_button * button)
References byte, Cursor_hidden, Cursor_shape, CURSOR_SHAPE_ARROW, CURSOR_SHAPE_TARGET, Display_cursor(), Get_input(), Hide_cursor, Key, KEY_ESC, LEFT_SIDE, Main_magnifier_mode, Menu_factor_X, Menu_factor_Y, Mouse_K, Mouse_X, Mouse_Y, T_Palette_button::Pos_X, T_Palette_button::Pos_Y, Read_pixel, RIGHT_SIDE, Window_click_in_rectangle(), Window_height, Window_pos_X, Window_pos_Y, and Window_width.
Referenced by Button_Palette().
void Get_color_behind_window (byte * color, byte * click)
References BUTTON_CHOOSE_COL, byte, Cursor_hidden, Cursor_shape, CURSOR_SHAPE_ARROW, CURSOR_SHAPE_COLORPICKER, Display_all_screen(), Display_cursor(), Display_menu(), Get_input(), Hide_cursor, Key, KEY_ESC, Main_palette, Menu_factor_X, Menu_factor_Y, Menu_is_visible, Menu_is_visible_before_window, Menu_status_Y, Menu_tooltip, Menu_Y, Menu_Y_before_window, Mouse_K, Mouse_X, Mouse_Y, Paintbrush_hidden, Print_general(), Print_in_menu(), Read_pixel, Restore_background(), Save_background(), Update_rect(), Window_height, Window_pos_X, Window_pos_Y, and Window_width.
Referenced by Button_Airbrush_menu(), Button_Gradients(), Button_Layer_menu(), Button_Palette(), Menu_shade(), and Menu_tag_colors().
void Move_window (short dx, short dy)
References byte, Cursor_shape, CURSOR_SHAPE_ARROW, CURSOR_SHAPE_MULTIDIRECTIONAL, Display_cursor(), Get_input(), Hide_cursor, Horizontal_XOR_line, Menu_factor_X, Menu_factor_Y, Menu_is_visible, Menu_is_visible_before_window, Menu_Y, Menu_Y_before_window, Mouse_K, Mouse_X, Mouse_Y, Restore_background(), Save_background(), Screen_height, Screen_width, Update_rect(), Vertical_XOR_line, Window_background, Window_height, Window_pos_X, Window_pos_Y, Window_width, and Windows_open.
Referenced by Window_clicked_button().
T_Dropdown_choice* Dropdown_activate (T_Dropdown_button * button, short off_x, short off_y)
Displays a dropped-down menu and handles the UI logic until the user releases a mouse button.
This function then clears the dropdown and returns the selected item, or NULL if the user wasn't highlighting an item when he closed.
References Block, T_Dropdown_button::Bottom_up, byte, Close_popup(), Display_cursor(), T_Dropdown_button::Dropdown_width, T_Dropdown_button::First_item, Get_input(), T_Dropdown_button::Height, Hide_cursor, T_Dropdown_choice::Label, MC_Black, MC_Dark, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, Mouse_K, Mouse_Y, T_Dropdown_choice::Next, Open_popup(), T_Dropdown_button::Pos_X, T_Dropdown_button::Pos_Y, Print_in_window(), SHADOW_BOTTOM, SHADOW_RIGHT, Update_rect(), Window_click_in_rectangle(), Window_display_frame_out(), Window_height, Window_pos_X, Window_pos_Y, and Window_width.
Referenced by Button_Magnify_menu(), Button_Palette(), Button_Toggle_toolbar(), and Window_dropdown_on_click().
short Window_dropdown_on_click (T_Dropdown_button * button)
References T_Dropdown_button::Display_arrow, T_Dropdown_button::Display_choice, Display_cursor(), Dropdown_activate(), T_Dropdown_button::Height, Hide_cursor, T_Dropdown_choice::Label, MC_Black, MC_Light, T_Dropdown_button::Number, T_Dropdown_choice::Number, T_Dropdown_button::Pos_X, T_Dropdown_button::Pos_Y, Print_in_window_limited(), T_Dropdown_button::Width, Window_attribute2, Window_pos_X, Window_pos_Y, Window_rectangle(), Window_select_normal_button(), and Window_unselect_normal_button().
Referenced by Window_get_clicked_button().
short Window_normal_button_onclick (word x_pos, word y_pos, word width, word height, short btn_number)
References Display_cursor(), Get_input(), Hide_cursor, Mouse_K, Window_click_in_rectangle(), Window_select_normal_button(), and Window_unselect_normal_button().
Referenced by Button_Settings(), and Window_get_clicked_button().
short Window_get_clicked_button (void)
References T_Dropdown_button::Active_button, Config, T_Scroller_button::Cursor_length, T_Config::Delay_left_click_on_slider, T_Config::Delay_right_click_on_slider, Delay_with_active_mouse(), Display_cursor(), T_Dropdown_button::Height, T_Special_button::Height, T_Normal_button::Height, Hide_cursor, Input_sticky_control, T_Scroller_button::Is_horizontal, T_Scroller_button::Length, Menu_factor_X, Menu_factor_Y, Mouse_K, Mouse_X, Mouse_Y, T_Scroller_button::Nb_elements, T_Scroller_button::Nb_visibles, T_Dropdown_button::Next, T_Special_button::Next, T_Scroller_button::Next, T_Palette_button::Next, T_Normal_button::Next, T_Dropdown_button::Number, T_Special_button::Number, T_Scroller_button::Number, T_Palette_button::Number, T_Normal_button::Number, T_Dropdown_button::Pos_X, T_Special_button::Pos_X, T_Scroller_button::Pos_X, T_Palette_button::Pos_X, T_Normal_button::Pos_X, T_Dropdown_button::Pos_Y, T_Special_button::Pos_Y, T_Scroller_button::Pos_Y, T_Palette_button::Pos_Y, T_Normal_button::Pos_Y, T_Scroller_button::Position, T_Normal_button::Repeatable, T_Dropdown_button::Width, T_Special_button::Width, T_Normal_button::Width, Window_attribute1, Window_attribute2, Window_click_in_rectangle(), Window_draw_slider(), Window_dropdown_button_list, Window_dropdown_on_click(), Window_normal_button_list, Window_normal_button_onclick(), Window_palette_button_list, Window_pos_X, Window_pos_Y, Window_scroller_button_list, Window_select_normal_button(), Window_special_button_list, and Window_unselect_normal_button().
Referenced by Button_Effects(), and Window_clicked_button().
short Window_get_button_shortcut (void)
References Config, T_Config::Delay_right_click_on_slider, Delay_with_active_mouse(), Display_cursor(), T_Normal_button::Height, Hide_cursor, Key, LEFT_SIDE, MOD_SHIFT, T_List_button::Next, T_Normal_button::Next, T_Normal_button::Number, T_Normal_button::Pos_X, T_Normal_button::Pos_Y, RIGHT_SIDE, T_Normal_button::Shortcut, T_Normal_button::Width, Window_attribute1, Window_list_button_list, Window_normal_button_list, Window_select_normal_button(), and Window_unselect_normal_button().
Referenced by Window_clicked_button().
short Window_clicked_button (void)
References T_List_button::Cursor_position, Display_cursor(), T_List_button::Draw_list_item, T_List_button::Entry_button, Get_input(), Hide_cursor, Input_sticky_control, Key, KEY_MOUSEWHEELDOWN, KEY_MOUSEWHEELUP, T_List_button::List_start, Menu_factor_X, Menu_factor_Y, Mouse_K, Mouse_X, Mouse_Y, Move_window(), T_Scroller_button::Nb_elements, T_Scroller_button::Nb_visibles, T_List_button::Next, T_Scroller_button::Number, T_List_button::Number, T_Special_button::Number, T_Special_button::Pos_X, T_Special_button::Pos_Y, T_Scroller_button::Position, T_List_button::Scroller, Window_attribute2, Window_draggable, Window_draw_slider(), Window_get_button_shortcut(), Window_get_clicked_button(), Window_height, Window_list_button_list, Window_pos_X, Window_pos_Y, Window_redraw_list(), and Window_width.
Referenced by Button_Airbrush_menu(), Button_Brush_container(), Button_Brush_FX(), Button_Colorize_menu(), Button_Copy_page(), Button_Effects(), Button_Gradients(), Button_Grid_menu(), Button_Layer_menu(), Button_Load_or_Save(), Button_Paintbrush_menu(), Button_Palette(), Button_Quick_shade_menu(), Button_Quit_local_function(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Skins(), Button_Smooth_menu(), Button_Stats(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Confirmation_box(), Menu_shade(), Menu_tag_colors(), Message_out_of_memory(), Readline_ex(), Requester_window(), Save_C64_window(), Verbose_message(), Warning_message(), Window_help(), Window_Histogram(), and Window_set_shortcut().
void Remap_window_backgrounds (byte * conversion_table, int Min_Y, int Max_Y)
References byte, T_Window::Height, Menu_factor_X, Menu_factor_Y, Pixel_width, Width, T_Window::Width, Window_background, Window_stack, and Windows_open.
Referenced by Remap_image_highlevel(), and Remap_screen_after_menu_colors_change().
void Delay_with_active_mouse (int delay)
Puts the user in wait mode for the specified time (in 1/100s), though the mouse still works.
References byte, Get_input(), and Mouse_K.
Referenced by Error_function(), Window_get_button_shortcut(), and Window_get_clicked_button().
Variable Documentation
short Old_MX = -1
Referenced by Button_Unselect_magnifier(), Close_popup(), Close_window(), and Main_handler().
short Old_MY = -1
Referenced by Button_Unselect_magnifier(), Close_popup(), Close_window(), and Main_handler().
byte Shade_mode_before_cancel
byte Quick_shade_mode_before_cancel
byte Stencil_mode_before_cancel
byte Sieve_mode_before_cancel
byte Colorize_mode_before_cancel
byte Smooth_mode_before_cancel
byte Tiling_mode_before_cancel
Func_effect Effect_function_before_cancel
byte* Window_background[8]
This table holds pointers to the saved window backgrounds. We can have up to 8 windows open at a time.
Referenced by Close_popup(), Close_window(), Move_window(), Open_popup(), Open_window(), Pixel_background(), and Remap_window_backgrounds().
char* Menu_tooltip[NB_BUTTONS]
Table of tooltip texts for menu buttons.
Referenced by Get_color_behind_window(), Main_handler(), and Status_print_palette_color().