GrafX2: factory.h File Reference
factory.h File Reference
Functions
void Button_Brush_Factory (void)
void Repeat_script (void)
void Run_numbered_script (byte index)
Run a lua script linked to a shortcut, 0-9.
Variables
char * Bound_script [10]
Lua scripts bound to shortcut keys.
Function Documentation
void Button_Brush_Factory (void)
References Verbose_message().
Referenced by Init_buttons().
void Repeat_script (void)
Referenced by Main_handler().
void Run_numbered_script (byte index)
Run a lua script linked to a shortcut, 0-9.
Before: Cursor hidden After: Cursor shown
Referenced by Main_handler().
Variable Documentation
char* Bound_script[10]
Lua scripts bound to shortcut keys.
Referenced by Load_CFG(), and Save_CFG().