GrafX2: files.h File Reference
files.h File Reference
Functions
int Determiner_repertoire_courant (void)
void Detruire_liste_du_fileselect (void)
void Lire_liste_des_fichiers (byte Format_demande)
void Lire_liste_des_lecteurs (void)
void Trier_la_liste_des_fichiers (void)
void Afficher_la_liste_des_fichiers (short Decalage_premier, short Decalage_select)
void Determiner_element_de_la_liste (short Decalage_premier, short Decalage_select, char *Libelle, int *Type)
void Afficher_bookmark (struct Fenetre_Bouton_dropdown *Bouton, int Numero_bookmark)
void Select_Scroll_Down (short *Decalage_premier, short *Decalage_select)
void Select_Scroll_Up (short *Decalage_premier, short *Decalage_select)
void Select_Page_Down (short *Decalage_premier, short *Decalage_select, short Lignes)
void Select_Page_Up (short *Decalage_premier, short *Decalage_select, short Lignes)
void Select_End (short *Decalage_premier, short *Decalage_select)
void Select_Home (short *Decalage_premier, short *Decalage_select)
short Calculer_decalage_click_dans_fileselector (void)
char * Nom_formate (char *Nom, int Type)
void for_each_file (const char *Nom_repertoire, void Callback(const char *))
Function Documentation
int Determiner_repertoire_courant (void)
References Principal_Repertoire_courant.
Referenced by Bouton_Load_ou_Save(), and Initialisation_du_programme().
void Detruire_liste_du_fileselect (void)
References Liste_du_fileselect, and Element_de_liste_de_fileselect::Suivant.
Referenced by Bouton_Load_ou_Save(), Lire_liste_des_fichiers(), and Lire_liste_des_lecteurs().
void Lire_liste_des_fichiers (byte Format_demande)
References Ajouter_element_a_la_liste(), Config, Detruire_liste_du_fileselect(), T_Format::Extension, FormatFichier, isHidden, S_Config::Lire_les_fichiers_caches, S_Config::Lire_les_repertoires_caches, Liste_Nb_elements, Liste_Nb_fichiers, Liste_Nb_repertoires, PARENT_DIR, and VerifieExtension().
Referenced by Bouton_Load_ou_Save(), and Relire_liste_fichiers().
void Lire_liste_des_lecteurs (void)
References Ajouter_element_a_la_liste(), Detruire_liste_du_fileselect(), LECTEUR_CDROM, LECTEUR_FLOPPY_3_5, LECTEUR_HDD, LECTEUR_NETWORK, Liste_Nb_elements, Liste_Nb_fichiers, Liste_Nb_repertoires, mount_entry::me_devname, mount_entry::me_dummy, mount_entry::me_mountdir, mount_entry::me_next, mount_entry::me_type, and read_file_system_list().
Referenced by Bouton_Load_ou_Save().
void Trier_la_liste_des_fichiers (void)
References Liste_du_fileselect, Liste_Nb_elements, Element_de_liste_de_fileselect::NomComplet, Element_de_liste_de_fileselect::Precedent, Element_de_liste_de_fileselect::Suivant, and Element_de_liste_de_fileselect::Type.
Referenced by Bouton_Load_ou_Save(), and Relire_liste_fichiers().
void Afficher_la_liste_des_fichiers (short Decalage_premier, short Decalage_select)
References COULEUR_FICHIER_NORMAL, COULEUR_FICHIER_SELECT, COULEUR_FOND_NORMAL, COULEUR_FOND_SELECT, COULEUR_REPERTOIRE_NORMAL, COULEUR_REPERTOIRE_SELECT, FILENAMESPACE, Liste_du_fileselect, Liste_Nb_elements, Element_de_liste_de_fileselect::NomAbrege, Print_dans_fenetre(), Element_de_liste_de_fileselect::Suivant, and Element_de_liste_de_fileselect::Type.
Referenced by Bouton_Load_ou_Save(), Preparer_et_afficher_liste_fichiers(), Select_End(), Select_Home(), Select_Page_Down(), Select_Page_Up(), Select_Scroll_Down(), and Select_Scroll_Up().
void Determiner_element_de_la_liste (short Decalage_premier, short Decalage_select, char * Libelle, int * Type)
References Liste_du_fileselect, Liste_Nb_elements, Element_de_liste_de_fileselect::NomComplet, Element_de_liste_de_fileselect::Suivant, and Element_de_liste_de_fileselect::Type.
Referenced by Bouton_Load_ou_Save(), On_vient_de_scroller_dans_le_fileselect(), and Preparer_et_afficher_liste_fichiers().
void Afficher_bookmark (struct Fenetre_Bouton_dropdown * Bouton, int Numero_bookmark)
References A_DROITE, A_GAUCHE, Block, S_Config::Bookmark_directory, S_Config::Bookmark_label, Fenetre_Bouton_dropdown::Bouton_actif, CM_Clair, CM_Fonce, CM_Noir, Config, Fenetre_Dropdown_choix(), Fenetre_Dropdown_vider_choix(), Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Fenetre_Bouton_dropdown::Pos_X, Fenetre_Bouton_dropdown::Pos_Y, Print_dans_fenetre(), and Print_dans_fenetre_limite().
Referenced by Bouton_Load_ou_Save().
void Select_Scroll_Down (short * Decalage_premier, short * Decalage_select)
References Afficher_la_liste_des_fichiers(), and Liste_Nb_elements.
Referenced by Bouton_Load_ou_Save().
void Select_Scroll_Up (short * Decalage_premier, short * Decalage_select)
References Afficher_la_liste_des_fichiers().
Referenced by Bouton_Load_ou_Save().
void Select_Page_Down (short * Decalage_premier, short * Decalage_select, short Lignes)
References Afficher_la_liste_des_fichiers(), and Liste_Nb_elements.
Referenced by Bouton_Load_ou_Save().
void Select_Page_Up (short * Decalage_premier, short * Decalage_select, short Lignes)
References Afficher_la_liste_des_fichiers().
Referenced by Bouton_Load_ou_Save().
void Select_End (short * Decalage_premier, short * Decalage_select)
References Afficher_la_liste_des_fichiers(), and Liste_Nb_elements.
Referenced by Bouton_Load_ou_Save().
void Select_Home (short * Decalage_premier, short * Decalage_select)
References Afficher_la_liste_des_fichiers().
Referenced by Bouton_Load_ou_Save().
short Calculer_decalage_click_dans_fileselector (void)
References Fenetre_Pos_Y, FILENAMESPACE, Liste_Nb_elements, Menu_Facteur_Y, and Mouse_Y.
Referenced by Bouton_Load_ou_Save().
char* Nom_formate (char * Nom, int Type)
References CARACTERE_SUSPENSION, and PARENT_DIR.
Referenced by Ajouter_element_a_la_liste(), and Bouton_Load_ou_Save().
void for_each_file (const char * Nom_repertoire, void Callbackconst char *)
References Nom_fichier_complet(), SEPARATEUR_CHEMIN, and TAILLE_CHEMIN_FICHIER.
Referenced by Initialisation_Texte().