GrafX2: files.c File Reference
files.c File Reference
#include <stdlib.h>
#include <fcntl.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <dirent.h>
#include "const.h"
#include "struct.h"
#include "global.h"
#include "divers.h"
#include "erreurs.h"
#include "io.h"
#include "windows.h"
#include "sdlscreen.h"
#include "loadsave.h"
#include "mountlist.h"
#include "moteur.h"
#include "readline.h"
#include "input.h"
#include "aide.h"
Defines
#define isHidden(x) ((x)->d_name[0]=='.')
#define NORMAL_FILE_COLOR MC_Light
#define NORMAL_DIRECTORY_COLOR MC_Dark
#define NORMAL_BACKGROUND_COLOR MC_Black
#define SELECTED_FILE_COLOR MC_White
#define SELECTED_DIRECTORY_COLOR MC_Light
#define SELECTED_BACKGROUND_COLOR MC_Dark
Functions
void Free_fileselector_list (void)
char * Format_filename (char *fname, int type)
void Add_element_to_list (char *fname, int type)
int Check_extension (const char *filename, char *filter)
void Read_list_of_files (byte selected_format)
void Read_list_of_drives (void)
void Sort_list_of_files (void)
void Display_file_list (short offset_first, short selector_offset)
void Get_selected_item (short offset_first, short selector_offset, char *label, int *type)
void Selector_scroll_down (short *offset_first, short *selector_offset)
void Selector_scroll_up (short *offset_first, short *selector_offset)
void Selector_page_down (short *offset_first, short *selector_offset, short lines)
void Selector_page_up (short *offset_first, short *selector_offset, short lines)
void Selector_end (short *offset_first, short *selector_offset)
void Selector_home (short *offset_first, short *selector_offset)
short Compute_click_offset_in_fileselector (void)
void Display_bookmark (T_Dropdown_button *Button, int bookmark_number)
void Print_current_directory (void)
void Print_filename_in_fileselector (void)
void Prepare_and_display_filelist (short Position, short offset, T_Scroller_button *button)
void Reload_list_of_files (byte filter, short Position, short offset, T_Scroller_button *button)
void Scroll_fileselector (T_Scroller_button *file_scroller)
short Find_file_in_fileselector (char *fname)
void Highlight_file (char *fname)
char * Find_filename_match (char *fname)
byte Button_Load_or_Save (byte load, byte image)
Variables
int Selected_type
char FFF_best_name [MAX_PATH_CHARACTERS]
Define Documentation
#define isHidden (x) ((x)->d_name[0]=='.')
Referenced by Read_list_of_files().
#define NORMAL_FILE_COLOR MC_Light
Referenced by Display_file_list().
#define NORMAL_DIRECTORY_COLOR MC_Dark
Referenced by Display_file_list().
#define NORMAL_BACKGROUND_COLOR MC_Black
Referenced by Display_file_list().
#define SELECTED_FILE_COLOR MC_White
Referenced by Display_file_list().
#define SELECTED_DIRECTORY_COLOR MC_Light
Referenced by Display_file_list().
#define SELECTED_BACKGROUND_COLOR MC_Dark
Referenced by Display_file_list().
Function Documentation
void Free_fileselector_list (void)
References Filelist, and T_Fileselector_item::Next.
Referenced by Button_Load_or_Save(), Read_list_of_drives(), and Read_list_of_files().
char* Format_filename (char * fname, int type)
References ELLIPSIS_CHARACTER, and PARENT_DIR.
Referenced by Add_element_to_list(), and Button_Load_or_Save().
void Add_element_to_list (char * fname, int type)
References Filelist, Format_filename(), T_Fileselector_item::Full_name, T_Fileselector_item::Next, T_Fileselector_item::Previous, T_Fileselector_item::Short_name, and T_Fileselector_item::Type.
Referenced by Read_list_of_drives(), and Read_list_of_files().
int Check_extension (const char * filename, char * filter)
Referenced by Read_list_of_files().
void Read_list_of_files (byte selected_format)
References Add_element_to_list(), Check_extension(), Config, T_Format::Extension, File_formats, Filelist_nb_directories, Filelist_nb_elements, Filelist_nb_files, Free_fileselector_list(), isHidden, PARENT_DIR, T_Config::Show_hidden_directories, and T_Config::Show_hidden_files.
Referenced by Button_Load_or_Save(), and Reload_list_of_files().
void Read_list_of_drives (void)
References Add_element_to_list(), Filelist_nb_directories, Filelist_nb_elements, Filelist_nb_files, Free_fileselector_list(), ICON_CDROM, ICON_FLOPPY_3_5, ICON_HDD, ICON_NETWORK, mount_entry::me_devname, mount_entry::me_dummy, mount_entry::me_mountdir, mount_entry::me_next, mount_entry::me_type, and read_file_system_list().
Referenced by Button_Load_or_Save().
void Sort_list_of_files (void)
References byte, Filelist, Filelist_nb_elements, T_Fileselector_item::Full_name, T_Fileselector_item::Next, T_Fileselector_item::Previous, and T_Fileselector_item::Type.
Referenced by Button_Load_or_Save(), and Reload_list_of_files().
void Display_file_list (short offset_first, short selector_offset)
References byte, Filelist, Filelist_nb_elements, T_Fileselector_item::Next, NORMAL_BACKGROUND_COLOR, NORMAL_DIRECTORY_COLOR, NORMAL_FILE_COLOR, Print_in_window(), SELECTED_BACKGROUND_COLOR, SELECTED_DIRECTORY_COLOR, SELECTED_FILE_COLOR, T_Fileselector_item::Short_name, and T_Fileselector_item::Type.
Referenced by Button_Load_or_Save(), Prepare_and_display_filelist(), Selector_end(), Selector_home(), Selector_page_down(), Selector_page_up(), Selector_scroll_down(), and Selector_scroll_up().
void Get_selected_item (short offset_first, short selector_offset, char * label, int * type)
References Filelist, Filelist_nb_elements, T_Fileselector_item::Full_name, T_Fileselector_item::Next, and T_Fileselector_item::Type.
Referenced by Button_Load_or_Save(), Prepare_and_display_filelist(), and Scroll_fileselector().
void Selector_scroll_down (short * offset_first, short * selector_offset)
References Display_file_list(), and Filelist_nb_elements.
Referenced by Button_Load_or_Save().
void Selector_scroll_up (short * offset_first, short * selector_offset)
References Display_file_list().
Referenced by Button_Load_or_Save().
void Selector_page_down (short * offset_first, short * selector_offset, short lines)
References Display_file_list(), and Filelist_nb_elements.
Referenced by Button_Load_or_Save().
void Selector_page_up (short * offset_first, short * selector_offset, short lines)
References Display_file_list().
Referenced by Button_Load_or_Save().
void Selector_end (short * offset_first, short * selector_offset)
References Display_file_list(), and Filelist_nb_elements.
Referenced by Button_Load_or_Save().
void Selector_home (short * offset_first, short * selector_offset)
References Display_file_list().
Referenced by Button_Load_or_Save().
short Compute_click_offset_in_fileselector (void)
References Filelist_nb_elements, Menu_factor_Y, Mouse_Y, and Window_pos_Y.
Referenced by Button_Load_or_Save().
void Display_bookmark (T_Dropdown_button * Button, int bookmark_number)
References T_Dropdown_button::Active_button, T_Config::Bookmark_directory, T_Config::Bookmark_label, Config, LEFT_SIDE, MC_Black, MC_Dark, MC_Light, T_Dropdown_button::Pos_X, T_Dropdown_button::Pos_Y, Print_in_window(), Print_in_window_limited(), RIGHT_SIDE, Window_dropdown_add_item(), Window_dropdown_clear_items(), and Window_rectangle().
Referenced by Button_Load_or_Save().
void Print_current_directory (void)
References Main_current_directory, MAX_DISPLAYABLE_PATH, MC_Black, MC_Light, PATH_SEPARATOR, Print_in_window(), Update_window_area, and Window_rectangle().
Referenced by Prepare_and_display_filelist().
void Print_filename_in_fileselector (void)
References Main_filename, MC_Black, MC_Light, Print_in_window_limited(), Update_window_area, and Window_rectangle().
Referenced by Button_Load_or_Save(), Prepare_and_display_filelist(), and Scroll_fileselector().
void Prepare_and_display_filelist (short Position, short offset, T_Scroller_button * button)
References Compute_slider_cursor_height(), Display_file_list(), Filelist_nb_elements, Get_selected_item(), Main_filename, MC_Black, T_Scroller_button::Nb_elements, T_Scroller_button::Position, Print_current_directory(), Print_filename_in_fileselector(), Update_window_area, Window_draw_slider(), and Window_rectangle().
Referenced by Button_Load_or_Save(), and Reload_list_of_files().
void Reload_list_of_files (byte filter, short Position, short offset, T_Scroller_button * button)
References Prepare_and_display_filelist(), Read_list_of_files(), and Sort_list_of_files().
Referenced by Button_Load_or_Save().
void Scroll_fileselector (T_Scroller_button * file_scroller)
References Display_cursor(), Get_selected_item(), Main_filename, Main_fileselector_offset, Main_fileselector_position, MAX_PATH_CHARACTERS, New_preview_is_needed, T_Scroller_button::Position, Print_filename_in_fileselector(), and Window_draw_slider().
Referenced by Button_Load_or_Save().
short Find_file_in_fileselector (char * fname)
References Filelist, T_Fileselector_item::Full_name, and T_Fileselector_item::Next.
Referenced by Highlight_file().
void Highlight_file (char * fname)
References Filelist_nb_elements, Find_file_in_fileselector(), Main_fileselector_offset, and Main_fileselector_position.
Referenced by Button_Load_or_Save().
char* Find_filename_match (char * fname)
References byte, Config, Filelist, T_Config::Find_file_fast, T_Fileselector_item::Full_name, Main_filename, T_Fileselector_item::Next, and T_Fileselector_item::Type.
Referenced by Button_Load_or_Save().
byte Button_Load_or_Save (byte load, byte image)
References Back_color, T_Config::Bookmark_directory, T_Config::Bookmark_label, BUTTON_HELP, BUTTON_LOAD, BUTTON_SAVE, byte, Check_timer(), Close_window(), COMMENT_SIZE, Compute_click_offset_in_fileselector(), Compute_optimal_menu_colors(), Config, Confirmation_box(), DEFAULT_FILEFORMAT, Directory_exists(), Display_bookmark(), Display_cursor(), Display_file_list(), Display_menu(), ELLIPSIS_CHARACTER, Error, File_exists(), File_formats, Filelist, Filelist_nb_directories, Filelist_nb_elements, Find_filename_match(), Find_last_slash(), Format_filename(), Free_fileselector_list(), T_Fileselector_item::Full_name, Get_selected_item(), Hide_cursor, Highlight_file(), Init_chrono(), Is_shortcut(), Key, Key_ANSI, KEY_ESC, KEY_MOUSEWHEELDOWN, KEY_MOUSEWHEELUP, LEFT_SIDE, Load_image(), Main_comment, Main_current_directory, Main_file_directory, Main_fileformat, Main_filename, Main_fileselector_offset, Main_fileselector_position, Main_format, Main_image_height, Main_image_is_modified, Main_image_width, Main_palette, MAX_PATH_CHARACTERS, MC_Black, MC_Dark, MC_Light, Menu_factor_Y, Menu_Y_before_window, NB_BOOKMARKS, NB_FORMATS_SAVE, NB_KNOWN_FORMATS, New_preview_is_needed, Open_window(), PARENT_DIR, Pixel_load_function, Pixel_load_in_current_screen(), Pixel_load_in_preview(), Prepare_and_display_filelist(), Print_filename_in_fileselector(), Print_in_window(), Read_list_of_drives(), Read_list_of_files(), Readline(), Readline_ex(), Reload_list_of_files(), RIGHT_SIDE, Scroll_fileselector(), Selector_end(), Selector_home(), Selector_page_down(), Selector_page_up(), Selector_scroll_down(), Selector_scroll_up(), Set_palette(), Sort_list_of_files(), Spare_current_directory, Spare_fileselector_offset, Spare_fileselector_position, T_Config::Timer_delay, Timer_state, Unselect_bouton(), Update_window_area, Wait_end_of_click(), Window_attribute2, Window_clicked_button(), Window_display_frame_in(), Window_display_icon_sprite(), Window_dropdown_add_item(), Window_height, Window_help(), Window_pos_Y, Window_rectangle(), Window_set_dropdown_button(), Window_set_input_button(), Window_set_normal_button(), Window_set_scroller_button(), Window_set_special_button(), and Window_width.
Referenced by Load_picture(), and Save_picture().
Variable Documentation
int Selected_type
char FFF_best_name[MAX_PATH_CHARACTERS]