GrafX2: fileformats.c File Reference
fileformats.c File Reference
Saving and loading different picture formats.
#include <png.h>
#include <stdlib.h>
#include "errors.h"
#include "global.h"
#include "loadsave.h"
#include "misc.h"
#include "struct.h"
#include "io.h"
#include "windows.h"
#include "pages.h"
Data Structures
struct T_LBM_Header
struct T_BMP_Header
struct T_GIF_LSDB
struct T_GIF_IDB
struct T_GIF_GCE
struct T_PCX_Header
struct T_SCx_Header
Defines
#define png_set_expand_gray_1_2_4_to_8(x) png_set_gray_1_2_4_to_8(x)
#define png_get_rowbytes(png_ptr, info_ptr) ((info_ptr)->rowbytes)
#define png_get_image_width(png_ptr, info_ptr) ((info_ptr)->width)
#define png_get_image_height(png_ptr, info_ptr) ((info_ptr)->height)
#define png_get_bit_depth(png_ptr, info_ptr) ((info_ptr)->bit_depth)
#define png_get_color_type(png_ptr, info_ptr) ((info_ptr)->color_type)
#define ID4(a, b, c, d) ((((a)&255)<<24) | (((b)&255)<<16) | (((c)&255)<<8) | (((d)&255)))
Functions
void Test_IMG (T_IO_Context *context)
void Load_IMG (T_IO_Context *context)
void Save_IMG (T_IO_Context *context)
void Test_LBM (T_IO_Context *context)
void Adapt_palette_HAM (T_IO_Context *context)
int LBM_Skip_section (void)
Skips the current section in an ILBM file.
byte LBM_Wait_for (byte *expected_section)
byte Color_ILBM_line (word x_pos, word real_line_size, byte HBPm1)
void Draw_ILBM_line (T_IO_Context *context, short y_pos, short real_line_size)
void Load_LBM (T_IO_Context *context)
void Transfer_colors (void)
void New_color (byte color)
void Save_LBM (T_IO_Context *context)
void Test_BMP (T_IO_Context *context)
byte Bitmap_mask (dword pixel, dword mask)
void Load_BMP (T_IO_Context *context)
void Save_BMP (T_IO_Context *context)
void Test_GIF (T_IO_Context *context)
word GIF_get_next_code (void)
void GIF_new_pixel (T_IO_Context *context, T_GIF_IDB *idb, byte color)
void Load_GIF (T_IO_Context *context)
void GIF_empty_buffer (void)
void GIF_set_code (word Code)
byte GIF_next_pixel (T_IO_Context *context, T_GIF_IDB *idb)
void Save_GIF (T_IO_Context *context)
void Test_PCX (T_IO_Context *context)
void Draw_PCX_line (T_IO_Context *context, short y_pos, byte depth)
void Load_PCX (T_IO_Context *context)
void Save_PCX (T_IO_Context *context)
void Test_SCx (T_IO_Context *context)
void Load_SCx (T_IO_Context *context)
void Save_SCx (T_IO_Context *context)
void Save_XPM (T_IO_Context *context)
void Test_PNG (T_IO_Context *context)
void Load_PNG (T_IO_Context *context)
void Save_PNG (T_IO_Context *context)
Variables
byte * LBM_buffer
FILE * LBM_file
byte Image_HAM
byte HBPm1
byte LBM_color_list [129]
word LBM_list_size
byte LBM_repetition_mode
word GIF_nb_bits
word GIF_remainder_bits
byte GIF_remainder_byte
word GIF_current_code
byte GIF_last_byte
word GIF_pos_X
word GIF_pos_Y
word GIF_interlaced
word GIF_finished_interlaced_image
word GIF_pass
FILE * GIF_file
int GIF_stop
byte GIF_buffer [256]
T_PCX_Header PCX_header
png_bytep * Row_pointers
Detailed Description
Saving and loading different picture formats.
Define Documentation
#define png_set_expand_gray_1_2_4_to_8 (x) png_set_gray_1_2_4_to_8(x)
Referenced by Load_PNG().
#define png_get_rowbytes (png_ptr, info_ptr) ((info_ptr)->rowbytes)
Referenced by Load_PNG().
#define png_get_image_width (png_ptr, info_ptr) ((info_ptr)->width)
Referenced by Load_PNG().
#define png_get_image_height (png_ptr, info_ptr) ((info_ptr)->height)
Referenced by Load_PNG().
#define png_get_bit_depth (png_ptr, info_ptr) ((info_ptr)->bit_depth)
Referenced by Load_PNG().
#define png_get_color_type (png_ptr, info_ptr) ((info_ptr)->color_type)
Referenced by Load_PNG().
#define ID4 (a, b, c, d) ((((a)&255)<<24) | (((b)&255)<<16) | (((c)&255)<<8) | (((d)&255)))
Function Documentation
void Test_IMG (T_IO_Context * context)
References byte, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_IMG_Header::Filler1, T_IMG_Header::Filler2, Get_full_filename(), T_IMG_Header::Height, MAX_PATH_CHARACTERS, T_IMG_Header::Palette, Read_bytes(), Read_word_le(), and T_IMG_Header::Width.
void Load_IMG (T_IO_Context * context)
References byte, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_IMG_Header::Filler1, T_IMG_Header::Filler2, FORMAT_IMG, Get_full_filename(), T_IO_Context::Height, T_IMG_Header::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, T_IMG_Header::Palette, Palette_loaded(), PIXEL_SIMPLE, Pre_load(), Read_bytes(), Read_word_le(), Set_pixel(), T_IO_Context::Width, T_IMG_Header::Width, and word.
void Save_IMG (T_IO_Context * context)
References byte, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_IMG_Header::Filler1, T_IMG_Header::Filler2, Get_full_filename(), Get_pixel(), T_IO_Context::Height, T_IMG_Header::Height, Init_write_buffer(), MAX_PATH_CHARACTERS, T_IO_Context::Palette, T_IMG_Header::Palette, T_IO_Context::Width, T_IMG_Header::Width, Write_bytes(), Write_one_byte(), and Write_word_le().
void Test_LBM (T_IO_Context * context)
References dword, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), LBM_file, MAX_PATH_CHARACTERS, Read_bytes(), and Read_dword_be().
void Adapt_palette_HAM (T_IO_Context * context)
References byte, Image_HAM, and T_IO_Context::Palette.
Referenced by Load_LBM().
int LBM_Skip_section (void)
Skips the current section in an ILBM file.
This function should be called while the file pointer is right after the 4-character code that identifies the section.
References dword, LBM_file, and Read_dword_be().
Referenced by LBM_Wait_for(), and Load_LBM().
byte LBM_Wait_for (byte * expected_section)
References byte, LBM_file, LBM_Skip_section(), and Read_bytes().
Referenced by Load_LBM().
byte Color_ILBM_line (word x_pos, word real_line_size, byte HBPm1)
References byte, and LBM_buffer.
Referenced by Draw_ILBM_line().
void Draw_ILBM_line (T_IO_Context * context, short y_pos, short real_line_size)
References Best_color(), byte, Color_ILBM_line(), HBPm1, Image_HAM, T_IO_Context::Palette, Set_pixel(), and T_IO_Context::Width.
Referenced by Load_LBM(), Load_PCX(), and Load_SCx().
void Load_LBM (T_IO_Context * context)
References Adapt_palette_HAM(), Back_color, T_LBM_Header::BitPlanes, byte, T_Config::Clear_palette, T_IO_Context::Color_cycles, T_LBM_Header::Compression, Config, T_IO_Context::Cycle_range, Draw_ILBM_line(), dword, T_Color_cycle::End, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_LBM, Get_full_filename(), HBPm1, T_IO_Context::Height, T_LBM_Header::Height, Image_HAM, T_Color_cycle::Inverse, LBM_buffer, LBM_file, LBM_Skip_section(), LBM_Wait_for(), T_LBM_Header::Mask, MAX_PATH_CHARACTERS, Original_screen_X, Original_screen_Y, T_LBM_Header::Pad1, T_IO_Context::Palette, Palette_256_to_64(), Palette_64_to_256(), Palette_loaded(), PIXEL_SIMPLE, Pre_load(), Read_byte(), Read_bytes(), Read_dword_be(), Read_word_be(), Set_file_error(), Set_pixel(), T_Color_cycle::Speed, T_Color_cycle::Start, SWAP_BYTES, T_LBM_Header::Transp_col, T_IO_Context::Width, T_LBM_Header::Width, word, T_LBM_Header::X_aspect, T_LBM_Header::X_org, T_LBM_Header::X_screen, T_LBM_Header::Y_aspect, T_LBM_Header::Y_org, and T_LBM_Header::Y_screen.
void Transfer_colors (void)
References byte, LBM_color_list, LBM_file, LBM_list_size, LBM_repetition_mode, and Write_one_byte().
Referenced by New_color(), and Save_LBM().
void New_color (byte color)
References byte, LBM_color_list, LBM_list_size, LBM_repetition_mode, and Transfer_colors().
Referenced by Save_LBM().
void Save_LBM (T_IO_Context * context)
References Back_color, T_LBM_Header::BitPlanes, byte, T_IO_Context::Color_cycles, T_LBM_Header::Compression, T_IO_Context::Cycle_range, T_Color_cycle::End, End_write(), T_IO_Context::File_directory, File_error, File_length(), T_IO_Context::File_name, Get_full_filename(), Get_pixel(), T_IO_Context::Height, T_LBM_Header::Height, Init_write_buffer(), T_Color_cycle::Inverse, LBM_file, LBM_list_size, T_LBM_Header::Mask, MAX_PATH_CHARACTERS, New_color(), T_LBM_Header::Pad1, T_IO_Context::Palette, Screen_height, Screen_width, T_Color_cycle::Speed, T_Color_cycle::Start, Transfer_colors(), T_LBM_Header::Transp_col, T_LBM_Header::Width, T_IO_Context::Width, word, Write_byte(), Write_bytes(), Write_dword_be(), Write_word_be(), T_LBM_Header::X_aspect, T_LBM_Header::X_org, T_LBM_Header::X_screen, T_LBM_Header::Y_aspect, T_LBM_Header::Y_org, and T_LBM_Header::Y_screen.
void Test_BMP (T_IO_Context * context)
References T_BMP_Header::Clr_Imprt, T_BMP_Header::Compression, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), T_BMP_Header::Height, MAX_PATH_CHARACTERS, T_BMP_Header::Nb_bits, T_BMP_Header::Nb_Clr, T_BMP_Header::Offset, T_BMP_Header::Planes, Read_bytes(), Read_dword_le(), Read_word_le(), T_BMP_Header::Reserved_1, T_BMP_Header::Reserved_2, T_BMP_Header::Signature, T_BMP_Header::Size_1, T_BMP_Header::Size_2, T_BMP_Header::Size_3, T_BMP_Header::Width, T_BMP_Header::XPM, and T_BMP_Header::YPM.
byte Bitmap_mask (dword pixel, dword mask)
References byte.
Referenced by Load_BMP().
void Load_BMP (T_IO_Context * context)
References Bitmap_mask(), byte, T_Config::Clear_palette, T_BMP_Header::Clr_Imprt, T_BMP_Header::Compression, Config, dword, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_BMP, Get_full_filename(), T_IO_Context::Height, T_BMP_Header::Height, MAX_PATH_CHARACTERS, T_BMP_Header::Nb_bits, T_BMP_Header::Nb_Clr, T_BMP_Header::Offset, T_IO_Context::Palette, Palette_loaded(), PIXEL_SIMPLE, T_BMP_Header::Planes, Pre_load(), Read_byte(), Read_bytes(), Read_dword_le(), Read_word_le(), T_BMP_Header::Reserved_1, T_BMP_Header::Reserved_2, Set_pixel(), Set_pixel_24b(), T_BMP_Header::Signature, T_BMP_Header::Size_1, T_BMP_Header::Size_2, T_BMP_Header::Size_3, T_IO_Context::Width, T_BMP_Header::Width, word, T_BMP_Header::XPM, and T_BMP_Header::YPM.
void Save_BMP (T_IO_Context * context)
References byte, T_BMP_Header::Clr_Imprt, T_BMP_Header::Compression, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), Get_pixel(), T_BMP_Header::Height, T_IO_Context::Height, Init_write_buffer(), MAX_PATH_CHARACTERS, T_BMP_Header::Nb_bits, T_BMP_Header::Nb_Clr, T_BMP_Header::Offset, T_IO_Context::Palette, T_BMP_Header::Planes, T_BMP_Header::Reserved_1, T_BMP_Header::Reserved_2, T_BMP_Header::Signature, T_BMP_Header::Size_1, T_BMP_Header::Size_2, T_BMP_Header::Size_3, T_BMP_Header::Width, T_IO_Context::Width, word, Write_bytes(), Write_dword_le(), Write_one_byte(), Write_word_le(), T_BMP_Header::XPM, and T_BMP_Header::YPM.
void Test_GIF (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, and Read_bytes().
word GIF_get_next_code (void)
References File_error, GIF_current_code, GIF_file, GIF_last_byte, GIF_nb_bits, GIF_remainder_bits, GIF_remainder_byte, Read_byte(), and word.
Referenced by Load_GIF().
void GIF_new_pixel (T_IO_Context * context, T_GIF_IDB * idb, byte color)
References GIF_finished_interlaced_image, GIF_interlaced, GIF_pass, GIF_pos_X, GIF_pos_Y, T_GIF_IDB::Image_height, T_GIF_IDB::Image_width, T_GIF_IDB::Pos_X, T_GIF_IDB::Pos_Y, and Set_pixel().
Referenced by Load_GIF().
void Load_GIF (T_IO_Context * context)
References T_GIF_LSDB::Aspect, T_GIF_LSDB::Backcol, T_IO_Context::Background_transparent, byte, T_Config::Clear_palette, T_IO_Context::Color_cycles, T_IO_Context::Comment, COMMENT_SIZE, Config, T_IO_Context::Cycle_range, T_GIF_GCE::Delay_time, T_Color_cycle::End, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_GIF, Get_full_filename(), GIF_current_code, GIF_file, GIF_finished_interlaced_image, GIF_get_next_code(), GIF_interlaced, GIF_last_byte, GIF_nb_bits, GIF_new_pixel(), GIF_pass, GIF_pos_X, GIF_pos_Y, GIF_remainder_bits, GIF_remainder_byte, T_IO_Context::Height, T_GIF_LSDB::Height, T_GIF_IDB::Image_height, T_GIF_IDB::Image_width, T_GIF_IDB::Indicator, T_Color_cycle::Inverse, MAX_PATH_CHARACTERS, Min(), T_IO_Context::Original_file_directory, T_IO_Context::Original_file_name, Original_screen_X, Original_screen_Y, T_GIF_GCE::Packed_fields, T_IO_Context::Palette, Palette_loaded(), PIXEL_SIMPLE, T_GIF_IDB::Pos_X, T_GIF_IDB::Pos_Y, Pre_load(), Read_byte(), Read_bytes(), Read_word_be(), Read_word_le(), T_GIF_LSDB::Resol, Set_layer(), T_Color_cycle::Speed, T_Color_cycle::Start, SWAP_BYTES, T_IO_Context::Transparent_color, T_GIF_GCE::Transparent_color, T_IO_Context::Width, T_GIF_LSDB::Width, and word.
void GIF_empty_buffer (void)
References GIF_buffer, GIF_file, GIF_remainder_byte, word, and Write_one_byte().
Referenced by GIF_set_code(), and Save_GIF().
void GIF_set_code (word Code)
References GIF_buffer, GIF_empty_buffer(), GIF_last_byte, GIF_nb_bits, GIF_remainder_bits, GIF_remainder_byte, and word.
Referenced by Save_GIF().
byte GIF_next_pixel (T_IO_Context * context, T_GIF_IDB * idb)
References byte, Get_pixel(), GIF_pos_X, GIF_pos_Y, GIF_stop, T_GIF_IDB::Image_height, and T_GIF_IDB::Image_width.
Referenced by Save_GIF().
void Save_GIF (T_IO_Context * context)
References T_GIF_LSDB::Aspect, T_GIF_LSDB::Backcol, T_IO_Context::Background_transparent, byte, T_IO_Context::Color_cycles, T_IO_Context::Comment, Config, T_IO_Context::Cycle_range, T_Color_cycle::End, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), GIF_empty_buffer(), GIF_file, GIF_last_byte, GIF_nb_bits, GIF_next_pixel(), GIF_pos_X, GIF_pos_Y, GIF_remainder_bits, GIF_remainder_byte, GIF_set_code(), GIF_stop, T_IO_Context::Height, T_GIF_LSDB::Height, T_GIF_IDB::Image_height, T_GIF_IDB::Image_width, T_GIF_IDB::Indicator, Init_write_buffer(), T_Color_cycle::Inverse, MAX_PATH_CHARACTERS, T_GIF_IDB::Nb_bits_pixel, T_IO_Context::Nb_layers, T_IO_Context::Original_file_directory, T_IO_Context::Original_file_name, T_IO_Context::Palette, T_GIF_IDB::Pos_X, T_GIF_IDB::Pos_Y, T_GIF_LSDB::Resol, Screen_height, T_Config::Screen_size_in_GIF, Screen_width, Set_layer(), T_Color_cycle::Speed, T_Color_cycle::Start, T_IO_Context::Transparent_color, T_IO_Context::Width, T_GIF_LSDB::Width, word, Write_byte(), Write_bytes(), Write_word_be(), and Write_word_le().
void Test_PCX (T_IO_Context * context)
References T_PCX_Header::Bytes_per_plane_line, T_PCX_Header::Compression, T_PCX_Header::Depth, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_PCX_Header::Filler, Get_full_filename(), T_PCX_Header::Manufacturer, MAX_PATH_CHARACTERS, T_PCX_Header::Palette_16c, T_PCX_Header::Palette_info, T_PCX_Header::Plane, Read_byte(), Read_bytes(), Read_word_le(), T_PCX_Header::Reserved, T_PCX_Header::Screen_X, T_PCX_Header::Screen_Y, T_PCX_Header::Version, T_PCX_Header::X_dpi, T_PCX_Header::X_max, T_PCX_Header::X_min, T_PCX_Header::Y_dpi, T_PCX_Header::Y_max, and T_PCX_Header::Y_min.
void Draw_PCX_line (T_IO_Context * context, short y_pos, byte depth)
References byte, LBM_buffer, Set_pixel(), and T_IO_Context::Width.
Referenced by Load_PCX().
void Load_PCX (T_IO_Context * context)
References byte, T_PCX_Header::Bytes_per_plane_line, T_Config::Clear_palette, T_PCX_Header::Compression, Config, DEBUG, T_PCX_Header::Depth, Draw_ILBM_line(), Draw_PCX_line(), dword, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_PCX_Header::Filler, FORMAT_PCX, Get_full_filename(), HBPm1, T_IO_Context::Height, Image_HAM, LBM_buffer, T_PCX_Header::Manufacturer, MAX_PATH_CHARACTERS, Original_screen_X, Original_screen_Y, T_IO_Context::Palette, T_PCX_Header::Palette_16c, T_PCX_Header::Palette_info, Palette_loaded(), PIXEL_SIMPLE, T_PCX_Header::Plane, Pre_load(), Read_byte(), Read_bytes(), Read_word_le(), T_PCX_Header::Reserved, T_PCX_Header::Screen_X, T_PCX_Header::Screen_Y, Set_file_error(), Set_pixel(), Set_pixel_24b(), T_PCX_Header::Version, T_IO_Context::Width, T_PCX_Header::X_dpi, T_PCX_Header::X_max, T_PCX_Header::X_min, T_PCX_Header::Y_dpi, T_PCX_Header::Y_max, and T_PCX_Header::Y_min.
void Save_PCX (T_IO_Context * context)
References byte, T_PCX_Header::Bytes_per_plane_line, T_PCX_Header::Compression, T_PCX_Header::Depth, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_PCX_Header::Filler, Get_full_filename(), Get_pixel(), T_IO_Context::Height, Init_write_buffer(), T_PCX_Header::Manufacturer, MAX_PATH_CHARACTERS, T_IO_Context::Palette, T_PCX_Header::Palette_16c, T_PCX_Header::Palette_info, T_PCX_Header::Plane, T_PCX_Header::Reserved, Screen_height, Screen_width, T_PCX_Header::Screen_X, T_PCX_Header::Screen_Y, T_PCX_Header::Version, T_IO_Context::Width, Write_bytes(), Write_one_byte(), Write_word_le(), T_PCX_Header::X_dpi, T_PCX_Header::X_max, T_PCX_Header::X_min, T_PCX_Header::Y_dpi, T_PCX_Header::Y_max, and T_PCX_Header::Y_min.
void Test_SCx (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_SCx_Header::Filler1, T_SCx_Header::Filler2, Get_full_filename(), T_SCx_Header::Height, MAX_PATH_CHARACTERS, T_SCx_Header::Planes, Read_byte(), Read_bytes(), Read_word_le(), and T_SCx_Header::Width.
void Load_SCx (T_IO_Context * context)
References byte, T_Config::Clear_palette, Config, Draw_ILBM_line(), T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_SCx_Header::Filler1, T_SCx_Header::Filler2, FORMAT_SCx, Get_full_filename(), HBPm1, T_IO_Context::Height, T_SCx_Header::Height, Image_HAM, LBM_buffer, MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_64_to_256(), Palette_loaded(), PIXEL_SIMPLE, T_SCx_Header::Planes, Pre_load(), Read_byte(), Read_bytes(), Read_word_le(), Set_pixel(), T_IO_Context::Width, T_SCx_Header::Width, and word.
void Save_SCx (T_IO_Context * context)
References byte, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_SCx_Header::Filler1, T_SCx_Header::Filler2, Get_full_filename(), Get_pixel(), T_IO_Context::Height, T_SCx_Header::Height, Init_write_buffer(), MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_256_to_64(), T_SCx_Header::Planes, T_SCx_Header::Width, T_IO_Context::Width, Write_byte(), Write_bytes(), Write_one_byte(), and Write_word_le().
void Save_XPM (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), Get_pixel(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, and T_IO_Context::Width.
void Test_PNG (T_IO_Context * context)
References byte, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, and Read_bytes().
void Load_PNG (T_IO_Context * context)
References T_IO_Context::Background_transparent, T_IO_Context::Buffer_image_24b, byte, T_Config::Clear_palette, T_IO_Context::Comment, COMMENT_SIZE, Config, CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_PNG, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, Min(), T_IO_Context::Palette, Palette_loaded(), PIXEL_SIMPLE, PIXEL_TALL, PIXEL_WIDE, png_get_bit_depth, png_get_color_type, png_get_image_height, png_get_image_width, png_get_rowbytes, png_set_expand_gray_1_2_4_to_8, Pre_load(), T_IO_Context::Ratio, Read_bytes(), Row_pointers, Set_pixel(), Set_pixel_24b(), T_IO_Context::Transparent_color, T_IO_Context::Type, and T_IO_Context::Width.
void Save_PNG (T_IO_Context * context)
References T_IO_Context::Background_transparent, byte, T_IO_Context::Comment, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, T_IO_Context::Pitch, Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, Row_pointers, T_IO_Context::Target_address, T_IO_Context::Transparent_color, and T_IO_Context::Width.
Variable Documentation
byte* LBM_buffer
Referenced by Color_ILBM_line(), Draw_PCX_line(), Load_LBM(), Load_PCX(), and Load_SCx().
FILE* LBM_file
Referenced by LBM_Skip_section(), LBM_Wait_for(), Load_LBM(), Save_LBM(), Test_LBM(), and Transfer_colors().
byte Image_HAM
Referenced by Adapt_palette_HAM(), Draw_ILBM_line(), Load_LBM(), Load_PCX(), and Load_SCx().
byte HBPm1
Referenced by Draw_ILBM_line(), Load_LBM(), Load_PCX(), and Load_SCx().
byte LBM_color_list[129]
Referenced by New_color(), and Transfer_colors().
word LBM_list_size
Referenced by New_color(), Save_LBM(), and Transfer_colors().
byte LBM_repetition_mode
Referenced by New_color(), and Transfer_colors().
word GIF_nb_bits
Referenced by GIF_get_next_code(), GIF_set_code(), Load_GIF(), and Save_GIF().
word GIF_remainder_bits
Referenced by GIF_get_next_code(), GIF_set_code(), Load_GIF(), and Save_GIF().
byte GIF_remainder_byte
Referenced by GIF_empty_buffer(), GIF_get_next_code(), GIF_set_code(), Load_GIF(), and Save_GIF().
word GIF_current_code
Referenced by GIF_get_next_code(), and Load_GIF().
byte GIF_last_byte
Referenced by GIF_get_next_code(), GIF_set_code(), Load_GIF(), and Save_GIF().
word GIF_pos_X
Referenced by GIF_new_pixel(), GIF_next_pixel(), Load_GIF(), and Save_GIF().
word GIF_pos_Y
Referenced by GIF_new_pixel(), GIF_next_pixel(), Load_GIF(), and Save_GIF().
word GIF_interlaced
Referenced by GIF_new_pixel(), and Load_GIF().
word GIF_finished_interlaced_image
Referenced by GIF_new_pixel(), and Load_GIF().
word GIF_pass
Referenced by GIF_new_pixel(), and Load_GIF().
FILE* GIF_file
Referenced by GIF_empty_buffer(), GIF_get_next_code(), Load_GIF(), and Save_GIF().
int GIF_stop
Referenced by GIF_next_pixel(), and Save_GIF().
byte GIF_buffer[256]
Referenced by GIF_empty_buffer(), and GIF_set_code().
T_PCX_Header PCX_header
png_bytep* Row_pointers
Referenced by Load_PNG(), and Save_PNG().