GrafX2: filesel.h File Reference
filesel.h File Reference
Fileselector window, used for loading and saving images and brushes.
#include "struct.h"
#include "loadsave.h"
Functions
byte Button_Load_or_Save (byte load, T_IO_Context *context)
void Add_element_to_list (T_Fileselector *list, const char *full_name, const char *short_name, int type, byte icon)
char * Format_filename (const char *fname, word max_length, int type)
Formats a display name for a file, directory, or similar name (drive, volume).
void Free_fileselector_list (T_Fileselector *list)
void Sort_list_of_files (T_Fileselector *list)
void Recount_files (T_Fileselector *list)
T_Fileselector_item * Get_item_by_index (T_Fileselector *list, short index)
short Find_file_in_fileselector (T_Fileselector *list, const char *fname)
void Locate_list_item (T_List_button *list, T_Fileselector *selector, short selected_item)
int Quicksearch_list (T_List_button *list, T_Fileselector *selector)
void Reset_quicksearch (void)
Detailed Description
Fileselector window, used for loading and saving images and brushes.
Function Documentation
byte Button_Load_or_Save (byte load, T_IO_Context * context)
References Back_color, T_Config::Bookmark_directory, T_Config::Bookmark_label, BUTTON_HELP, BUTTON_LOAD, BUTTON_SAVE, byte, Check_timer(), Close_window(), T_IO_Context::Comment, COMMENT_SIZE, Compute_click_offset_in_fileselector(), Compute_optimal_menu_colors(), Config, Confirmation_box(), CONTEXT_MAIN_IMAGE, DEBUG, T_Format::Default_extension, DEFAULT_FILEFORMAT, Destroy_context(), Directory_exists(), Display_bookmark(), Display_cursor(), Display_file_list(), Display_menu(), ELLIPSIS_CHARACTER, Error, Extract_filename(), T_IO_Context::File_directory, File_exists(), File_formats, T_IO_Context::File_name, Find_file_in_fileselector(), Find_last_slash(), T_Fileselector::First, T_IO_Context::Format, FORMAT_ALL_FILES, Free_fileselector_list(), T_Fileselector_item::Full_name, Get_fileformat(), Get_selected_item(), Hide_cursor, Highlight_file(), ICON_STAR, Init_chrono(), Init_context_preview(), INPUT_TYPE_FILENAME, INPUT_TYPE_STRING, Is_shortcut(), Key, KEY_ESC, KEY_MOUSEWHEELDOWN, KEY_MOUSEWHEELUP, LEFT_SIDE, Load_image(), Main_current_directory, Main_fileformat, Main_fileselector_offset, Main_fileselector_position, Main_format, Main_palette, MAX_PATH_CHARACTERS, MC_Black, MC_Dark, MC_Light, Menu_factor_Y, Menu_Y_before_window, Mouse_K, NB_BOOKMARKS, T_Fileselector::Nb_directories, T_Fileselector::Nb_elements, NB_KNOWN_FORMATS, New_preview_is_needed, Open_window(), PARENT_DIR, Prepare_and_display_filelist(), PREVIEW_HEIGHT, PREVIEW_WIDTH, Print_filename_in_fileselector(), Print_in_window(), Quicksearch(), Read_list_of_drives(), Read_list_of_files(), Readline(), Readline_ex(), Reload_list_of_files(), Reset_quicksearch(), RIGHT_SIDE, Scroll_fileselector(), Selector_end(), Selector_filename, Selector_home(), Selector_page_down(), Selector_page_up(), Selector_scroll_down(), Selector_scroll_up(), Set_palette(), Sort_list_of_files(), Spare_current_directory, Spare_fileselector_offset, Spare_fileselector_position, SPECIAL_LOAD_BRUSH, SPECIAL_SAVE_BRUSH, T_Config::Timer_delay, Timer_state, T_IO_Context::Type, Unselect_button(), Update_window_area, Wait_end_of_click(), Window_attribute2, Window_clicked_button(), Window_display_frame_in(), Window_display_icon_sprite(), Window_dropdown_add_item(), Window_height, Window_help(), Window_pos_Y, Window_rectangle(), Window_set_dropdown_button(), Window_set_input_button(), Window_set_normal_button(), Window_set_scroller_button(), Window_set_special_button(), and Window_width.
Referenced by Load_picture(), and Save_picture().
void Add_element_to_list (T_Fileselector * list, const char * full_name, const char * short_name, int type, byte icon)
References T_Fileselector::First, T_Fileselector_item::Full_name, T_Fileselector_item::Icon, T_Fileselector_item::Next, T_Fileselector_item::Previous, T_Fileselector_item::Short_name, and T_Fileselector_item::Type.
Referenced by Add_font_or_skin(), Read_list_of_drives(), and Read_list_of_files().
char* Format_filename (const char * fname, word max_length, int type)
Formats a display name for a file, directory, or similar name (drive, volume).
The returned value is a pointer to a single static buffer of maximum 40 characters including the '\0'.
References ELLIPSIS_CHARACTER, and PARENT_DIR.
Referenced by Add_font_or_skin(), Read_list_of_drives(), and Read_list_of_files().
void Free_fileselector_list (T_Fileselector * list)
References T_Fileselector::First, T_Fileselector_item::Next, and Recount_files().
Referenced by Button_Load_or_Save(), Button_Skins(), Read_list_of_drives(), and Read_list_of_files().
void Sort_list_of_files (T_Fileselector * list)
References byte, FILENAME_COMPARE, T_Fileselector::First, T_Fileselector_item::Full_name, T_Fileselector_item::Next, T_Fileselector_item::Previous, Recount_files(), and T_Fileselector_item::Type.
Referenced by Button_Load_or_Save(), Button_Skins(), and Reload_list_of_files().
void Recount_files (T_Fileselector * list)
References T_Fileselector::First, T_Fileselector::Index, T_Fileselector::Nb_directories, T_Fileselector::Nb_elements, T_Fileselector::Nb_files, T_Fileselector_item::Next, and T_Fileselector_item::Type.
Referenced by Free_fileselector_list(), Read_list_of_drives(), Read_list_of_files(), and Sort_list_of_files().
T_Fileselector_item* Get_item_by_index (T_Fileselector * list, short index)
References T_Fileselector::First, T_Fileselector::Index, T_Fileselector::Nb_elements, and T_Fileselector_item::Next.
Referenced by Button_Skins(), Display_file_list(), Draw_one_skin_name(), and Get_selected_item().
short Find_file_in_fileselector (T_Fileselector * list, const char * fname)
References T_Fileselector::First, T_Fileselector_item::Full_name, and T_Fileselector_item::Next.
Referenced by Button_Load_or_Save(), and Button_Skins().
void Locate_list_item (T_List_button * list, T_Fileselector * selector, short selected_item)
References T_List_button::Cursor_position, T_List_button::List_start, T_Scroller_button::Nb_elements, T_Scroller_button::Nb_visibles, and T_List_button::Scroller.
Referenced by Quicksearch_list().
int Quicksearch_list (T_List_button * list, T_Fileselector * selector)
References T_List_button::Cursor_position, Display_cursor(), Hide_cursor, T_List_button::List_start, Locate_list_item(), T_List_button::Number, T_Scroller_button::Position, Quicksearch(), T_List_button::Scroller, Window_attribute2, Window_draw_slider(), and Window_redraw_list().
void Reset_quicksearch (void)
Referenced by Button_Load_or_Save().