GrafX2: graph.h File Reference
graph.h File Reference
Defines
#define ToWinX(x) (((x)*Menu_Facteur_X)+Fenetre_Pos_X)
#define ToWinY(y) (((y)*Menu_Facteur_Y)+Fenetre_Pos_Y)
#define ToWinL(l) ((l)*Menu_Facteur_X)
#define ToWinH(h) ((h)*Menu_Facteur_Y)
Functions
void Liste2tables (word *Liste, short Pas, byte Mode, byte *Table_inc, byte *Table_dec)
void Transformer_point (short X, short Y, float cosA, float sinA, short *Xr, short *Yr)
int Initialiser_mode_video (int Largeur, int Hauteur, int Fullscreen)
byte Aucun_effet (word X, word Y, byte Couleur)
byte Effet_Shade (word X, word Y, byte Couleur)
byte Effet_Quick_shade (word X, word Y, byte Couleur)
byte Effet_Tiling (word X, word Y, byte Couleur)
byte Effet_Smooth (word X, word Y, byte Couleur)
void Afficher_foreback (void)
void Afficher_pixel (word X, word Y, byte Couleur)
void Afficher_pinceau (short X, short Y, byte Couleur, byte Preview)
void Effacer_pinceau (short X, short Y)
void Redimentionner_image (word Largeur_choisie, word Hauteur_choisie)
void Remplir (byte Couleur_de_remplissage)
void Remplacer (byte Nouvelle_couleur)
void Pixel_figure_Preview (word Pos_X, word Pos_Y, byte Couleur)
void Pixel_figure_Preview_auto (word Pos_X, word Pos_Y)
void Pixel_figure_Preview_xor (word Pos_X, word Pos_Y, byte Couleur)
void Pixel_figure_Preview_xorback (word Pos_X, word Pos_Y, byte Couleur)
void Pixel_figure_Dans_brosse (word Pos_X, word Pos_Y, byte Couleur)
void Tracer_cercle_vide_Definitif (short Centre_X, short Centre_Y, short Rayon, byte Couleur)
void Tracer_cercle_vide_Preview (short Centre_X, short Centre_Y, short Rayon, byte Couleur)
void Effacer_cercle_vide_Preview (short Centre_X, short Centre_Y, short Rayon)
void Tracer_cercle_plein (short Centre_X, short Centre_Y, short Rayon, byte Couleur)
void Tracer_ellipse_vide_Definitif (short Centre_X, short Centre_Y, short Rayon_horizontal, short Rayon_vertical, byte Couleur)
void Tracer_ellipse_vide_Preview (short Centre_X, short Centre_Y, short Rayon_horizontal, short Rayon_vertical, byte Couleur)
void Effacer_ellipse_vide_Preview (short Centre_X, short Centre_Y, short Rayon_horizontal, short Rayon_vertical)
void Tracer_ellipse_pleine (short Centre_X, short Centre_Y, short Rayon_horizontal, short Rayon_vertical, byte Couleur)
void Rectifier_coordonnees_a_45_degres (short AX, short AY, short *BX, short *BY)
void Tracer_ligne_General (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
void Tracer_ligne_Definitif (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
void Tracer_ligne_Preview (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
void Tracer_ligne_Preview_xor (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
void Tracer_ligne_Preview_xorback (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
void Effacer_ligne_Preview (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y)
void Tracer_rectangle_vide (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
void Tracer_rectangle_plein (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
void Tracer_courbe_Definitif (short X1, short Y1, short X2, short Y2, short X3, short Y3, short X4, short Y4, byte Couleur)
void Tracer_courbe_Preview (short X1, short Y1, short X2, short Y2, short X3, short Y3, short X4, short Y4, byte Couleur)
void Effacer_courbe_Preview (short X1, short Y1, short X2, short Y2, short X3, short Y3, short X4, short Y4, byte Couleur)
void Aerographe (short Bouton_clicke)
void Degrade_de_base (long Indice, short Pos_X, short Pos_Y)
void Degrade_de_trames_simples (long Indice, short Pos_X, short Pos_Y)
void Degrade_de_trames_etendues (long Indice, short Pos_X, short Pos_Y)
void Degrade_aleatoire (long Indice, short Pos_X, short Pos_Y)
void Tracer_cercle_degrade (short Centre_X, short Centre_Y, short Rayon, short Eclairage_X, short Eclairage_Y)
void Tracer_ellipse_degradee (short Centre_X, short Centre_Y, short Rayon_horizontal, short Rayon_vertical, short Eclairage_X, short Eclairage_Y)
void Tracer_rectangle_degrade (short RAX, short RAY, short RBX, short RBY, short VAX, short VAY, short VBX, short VBY)
void Polyfill_General (int Vertices, short *Points, int Color)
void Polyfill (int Vertices, short *Points, int Color)
void Download_infos_page_principal (S_Page *Page)
void Download_infos_page_brouillon (S_Page *Page)
void Download_infos_backup (S_Liste_de_pages *Liste)
void Detruire_les_listes_de_backups_en_fin_de_programme (void)
void Nouveau_nombre_de_backups (int Nouveau)
int Backup_avec_nouvelles_dimensions (int Upload, int Largeur, int Hauteur)
int Backuper_et_redimensionner_brouillon (int Largeur, int Hauteur)
void Undo (void)
void Redo (void)
void Detruire_la_page_courante (void)
void Interchanger_image_principale_et_brouillon (void)
void Changer_facteur_loupe (byte Indice_facteur)
void Remap_picture (void)
void Mettre_Ecran_A_Jour (short X, short Y, short Largeur, short Hauteur)
Variables
fonction_afficheur Pixel_figure
Define Documentation
#define ToWinX (x) (((x)*Menu_Facteur_X)+Fenetre_Pos_X)
Referenced by Afficher_pinceau_dans_fenetre(), Afficher_sprite_effet(), Bloc_degrade_dans_fenetre(), Bouton_Load_ou_Save(), Dessiner_trames_predefinies(), Fenetre_Afficher_sprite_drive(), and Tagger_intervalle_palette().
#define ToWinY (y) (((y)*Menu_Facteur_Y)+Fenetre_Pos_Y)
Referenced by Afficher_pinceau_dans_fenetre(), Afficher_sprite_effet(), Bloc_degrade_dans_fenetre(), Bouton_Load_ou_Save(), Dessiner_trames_predefinies(), Fenetre_Afficher_sprite_drive(), and Tagger_intervalle_palette().
#define ToWinL (l) ((l)*Menu_Facteur_X)
Referenced by Afficher_pinceau_dans_fenetre(), Bloc_degrade_dans_fenetre(), Bouton_Load_ou_Save(), Dessiner_trames_predefinies(), Fenetre_Afficher_sprite_drive(), Fenetre_Effacer_tags(), and Tagger_intervalle_palette().
#define ToWinH (h) ((h)*Menu_Facteur_Y)
Referenced by Afficher_pinceau_dans_fenetre(), Bloc_degrade_dans_fenetre(), Bouton_Load_ou_Save(), Dessiner_trames_predefinies(), Fenetre_Afficher_sprite_drive(), Fenetre_Effacer_tags(), and Tagger_intervalle_palette().
Function Documentation
void Liste2tables (word * Liste, short Pas, byte Mode, byte * Table_inc, byte * Table_dec)
References MODE_SHADE_BOUCLE, and MODE_SHADE_NORMAL.
Referenced by Bouton_Shade_Menu(), Charger_CFG(), and Config_par_defaut().
void Transformer_point (short X, short Y, float cosA, float sinA, short * Xr, short * Yr)
References Round().
Referenced by Afficher_curseur(), Effacer_curseur(), Tourner_brosse(), and Tourner_brosse_preview().
int Initialiser_mode_video (int Largeur, int Hauteur, int Fullscreen)
References Affiche_brosse, Affiche_brosse_Double(), Affiche_brosse_Simple(), Affiche_brosse_Tall(), Affiche_brosse_Wide(), Afficher_ecran(), Afficher_ligne, Afficher_ligne_fast, Afficher_partie_de_l_ecran_Double(), Afficher_partie_de_l_ecran_Simple(), Afficher_partie_de_l_ecran_Tall(), Afficher_partie_de_l_ecran_Wide(), Afficher_partie_de_l_ecran_zoomee_Double(), Afficher_partie_de_l_ecran_zoomee_Simple(), Afficher_partie_de_l_ecran_zoomee_Tall(), Afficher_partie_de_l_ecran_zoomee_Wide(), Afficher_une_ligne_ecran_Double(), Afficher_une_ligne_ecran_fast_Double(), Afficher_une_ligne_ecran_fast_Wide(), Afficher_une_ligne_ecran_Simple(), Afficher_une_ligne_ecran_Tall(), Afficher_une_ligne_ecran_Wide(), Block, Block_Double(), Block_Simple(), Block_Tall(), Block_Wide(), Brouillon_Decalage_X, Brouillon_Decalage_Y, Brouillon_Loupe_Mode, Buffer_de_ligne_horizontale, Calculer_coordonnees_pinceau(), Calculer_donnees_loupe(), Calculer_limites(), Changer_cellules_palette(), Clear_brush, Clear_brush_Double(), Clear_brush_Simple(), Clear_brush_Tall(), Clear_brush_Wide(), Clear_brush_zoom, Clear_brush_zoom_Double(), Clear_brush_zoom_Simple(), Clear_brush_zoom_Tall(), Clear_brush_zoom_Wide(), Config, Display_brush_Color, Display_brush_Color_Double(), Display_brush_Color_Simple(), Display_brush_Color_Tall(), Display_brush_Color_Wide(), Display_brush_Color_zoom, Display_brush_Color_zoom_Double(), Display_brush_Color_zoom_Simple(), Display_brush_Color_zoom_Tall(), Display_brush_Color_zoom_Wide(), Display_brush_Mono, Display_brush_Mono_Double(), Display_brush_Mono_Simple(), Display_brush_Mono_Tall(), Display_brush_Mono_Wide(), Display_brush_Mono_zoom, Display_brush_Mono_zoom_Double(), Display_brush_Mono_zoom_Simple(), Display_brush_Mono_zoom_Tall(), Display_brush_Mono_zoom_Wide(), Display_screen, Display_zoomed_screen, Hauteur_ecran, HAUTEUR_MENU, S_Config::Indice_Sensibilite_souris_X, S_Config::Indice_Sensibilite_souris_Y, Largeur_ecran, Ligne_horizontale_XOR, Ligne_horizontale_XOR_Double(), Ligne_horizontale_XOR_Simple(), Ligne_horizontale_XOR_Tall(), Ligne_horizontale_XOR_Wide(), Ligne_verticale_XOR, Ligne_verticale_XOR_Double(), Ligne_verticale_XOR_Simple(), Ligne_verticale_XOR_Tall(), Ligne_verticale_XOR_Wide(), Lire_ligne, Lire_une_ligne_ecran_Double(), Lire_une_ligne_ecran_Simple(), Lire_une_ligne_ecran_Tall(), Lire_une_ligne_ecran_Wide(), Lit_pixel, Lit_Pixel_Double(), Lit_Pixel_Simple(), Lit_Pixel_Tall(), Lit_Pixel_Wide(), Loupe_Mode, Menu_Facteur_X, Menu_Facteur_Y, Menu_Ordonnee, Menu_Ordonnee_Texte, Menu_visible, Mode_video, Mouse_Facteur_de_correction_X, Mouse_Facteur_de_correction_Y, Nb_modes_video, Pixel, Pixel_Double(), PIXEL_DOUBLE, Pixel_height, Pixel_Preview, Pixel_Preview_Loupe, Pixel_Preview_Loupe_Double(), Pixel_Preview_Loupe_Simple(), Pixel_Preview_Loupe_Tall(), Pixel_Preview_Loupe_Wide(), Pixel_Preview_Normal, Pixel_Preview_Normal_Double(), Pixel_Preview_Normal_Simple(), Pixel_Preview_Normal_Tall(), Pixel_Preview_Normal_Wide(), Pixel_ratio, Pixel_Simple(), PIXEL_SIMPLE, Pixel_Tall(), PIXEL_TALL, Pixel_Wide(), PIXEL_WIDE, Pixel_width, Principal_Decalage_X, Principal_Decalage_Y, Principal_Hauteur_image, Principal_Largeur_image, Principal_Palette, S_Config::Ratio, Recadrer_ecran_par_rapport_au_zoom(), Remap_screen, Remap_screen_Double(), Remap_screen_Simple(), Remap_screen_Tall(), Remap_screen_Wide(), Resize_Hauteur, Resize_Largeur, Resolution_actuelle, Sensibilite_souris(), Set_Mode_SDL(), and Set_palette().
Referenced by Bouton_Reload(), Bouton_Resol(), Bouton_Safety_resol(), Gestion_principale(), Initialisation_du_programme(), and Load_picture().
byte Aucun_effet (word X, word Y, byte Couleur)
byte Effet_Shade (word X, word Y, byte Couleur)
byte Effet_Quick_shade (word X, word Y, byte Couleur)
References Back_color, Fore_color, Largeur, Lit_pixel_dans_ecran_feedback(), MODE_SHADE_BOUCLE, MODE_SHADE_NORMAL, Quick_shade_Loop, Quick_shade_Step, Shade_Table, Shade_Table_droite, and Shade_Table_gauche.
Referenced by Bouton_Quick_shade_Mode().
byte Effet_Tiling (word X, word Y, byte Couleur)
byte Effet_Smooth (word X, word Y, byte Couleur)
void Afficher_foreback (void)
References Back_color, Block, Fore_color, LARGEUR_MENU, Menu_Facteur_X, Menu_Facteur_Y, Menu_Ordonnee, Menu_visible, and UpdateRect().
Referenced by Afficher_menu(), Bouton_Choix_backcolor(), Bouton_Choix_forecolor(), Bouton_Inverser_foreback(), Pipette_0_1(), Pipette_12_0(), Pipette_1_1(), Pipette_2_1(), Special_Next_backcolor(), Special_Next_forecolor(), Special_Previous_backcolor(), and Special_Previous_forecolor().
void Afficher_pixel (word X, word Y, byte Couleur)
References Effet_Trame(), Fonction_effet, Lit_pixel_dans_ecran_brouillon(), Lit_pixel_dans_ecran_courant(), Mask_Mode, Mask_table, Pixel_dans_ecran_courant(), Pixel_Preview, Stencil, Stencil_Mode, and Trame_Mode.
Referenced by Afficher_pinceau(), Bouton_Degrades(), Initialisation_du_programme(), Pixel_clippe(), Remplir(), Tracer_cercle_plein(), Tracer_ellipse_pleine(), and Tracer_rectangle_plein().
void Afficher_pinceau (short X, short Y, byte Couleur, byte Preview)
References Afficher_pixel(), Back_color, Brosse, Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, Buffer_de_ligne_horizontale, Calculer_dimensions_clipees(), Calculer_dimensions_clipees_zoom(), Copier_une_partie_d_image_dans_une_autre(), Display_brush_Color, Display_brush_Color_zoom, Display_brush_Mono, Display_brush_Mono_zoom, Fore_color, FORME_PINCEAU_BROSSE_COULEUR, FORME_PINCEAU_BROSSE_MONOCHROME, FORME_PINCEAU_POINT, Hauteur, Largeur, Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, Lit_pixel_dans_brosse(), Lit_pixel_dans_ecran_courant(), Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Facteur, Loupe_Mode, Menu_Ordonnee, Mettre_Ecran_A_Jour(), Mouse_K, Pinceau_Decalage_X, Pinceau_Decalage_Y, Pinceau_Forme, Pinceau_Hauteur, Pinceau_Largeur, Pinceau_Sprite, Pinceau_X, Pinceau_Y, Pixel_Preview, Fenetre_Bouton_scroller::Pos_X, Fenetre_Bouton_scroller::Pos_Y, Fenetre_Bouton_scroller::Position, Principal_Decalage_X, Principal_Decalage_Y, Principal_Ecran, Principal_Largeur_image, Principal_X_Zoom, Shade_Table, Shade_Table_gauche, Smear_Brosse, Smear_Brosse_Largeur, Smear_Debut, Smear_Max_X, Smear_Max_Y, Smear_Min_X, Smear_Min_Y, Smear_Mode, and TAILLE_MAXI_PINCEAU.
Referenced by Aerographe(), Afficher_curseur(), Freehand_Mode1_1_0(), Freehand_Mode1_2_0(), Freehand_Mode2_1_0(), Freehand_Mode2_1_2(), Freehand_Mode2_2_0(), Freehand_Mode2_2_2(), Freehand_Mode3_1_0(), Freehand_Mode3_2_0(), K_Ligne_0_6(), Ligne_0_5(), Lignes_centrees_12_7(), Pixel_figure_Definitif(), Polyform_12_0(), and Tracer_rectangle_vide().
void Effacer_pinceau (short X, short Y)
References Back_color, Brosse, Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, Buffer_de_ligne_horizontale, Calculer_dimensions_clipees(), Calculer_dimensions_clipees_zoom(), Clear_brush, Clear_brush_zoom, FORME_PINCEAU_BROSSE_COULEUR, FORME_PINCEAU_BROSSE_MONOCHROME, FORME_PINCEAU_POINT, Hauteur, Largeur, Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, Lit_pixel_dans_ecran_courant(), Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Facteur, Loupe_Mode, Menu_Ordonnee, Mettre_Ecran_A_Jour(), Mouse_K, Pinceau_Decalage_X, Pinceau_Decalage_Y, Pinceau_Forme, Pinceau_Hauteur, Pinceau_Largeur, Pinceau_Sprite, Pinceau_X, Pinceau_Y, Pixel_Preview, Principal_Decalage_X, Principal_Decalage_Y, Principal_Largeur_image, and Principal_X_Zoom.
Referenced by Effacer_curseur().
void Redimentionner_image (word Largeur_choisie, word Hauteur_choisie)
References Afficher_curseur(), Backup_avec_nouvelles_dimensions(), Copier_une_partie_d_image_dans_une_autre(), Ecran_backup, Effacer_curseur, Message_Memoire_insuffisante(), Min(), Principal_Ecran, Principal_Hauteur_image, and Principal_Largeur_image.
Referenced by Bouton_Resol().
void Remplir (byte Couleur_de_remplissage)
References Afficher_curseur(), Afficher_pixel(), Backup(), Copier_une_partie_d_image_dans_une_autre(), Ecran_backup, Effacer_curseur, Fill(), Forme_curseur, FORME_CURSEUR_SABLIER, FX_Feedback_Ecran, Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, Lit_pixel_dans_ecran_backup(), Lit_pixel_dans_ecran_courant(), Pinceau_X, Pinceau_Y, Pixel_dans_ecran_courant(), Principal_Ecran, Principal_Largeur_image, Remplacer_toutes_les_couleurs_dans_limites(), and UpdateRect().
Referenced by Fill_1_0(), and Fill_2_0().
void Remplacer (byte Nouvelle_couleur)
References Afficher_ecran(), Lit_pixel_dans_ecran_courant(), Pinceau_X, Pinceau_Y, Principal_Hauteur_image, Principal_Largeur_image, Remplacer_une_couleur(), Stencil, and Stencil_Mode.
Referenced by Remplacer_1_0(), and Remplacer_2_0().
void Pixel_figure_Preview (word Pos_X, word Pos_Y, byte Couleur)
References Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, and Pixel_Preview.
Referenced by Cercle_degrade_12_0(), Courbe_34_points_1_0(), Courbe_34_points_1_5(), Courbe_34_points_2_0(), Courbe_34_points_2_5(), Ellipse_degradee_12_0(), K_Ligne_12_0(), K_Ligne_12_6(), Ligne_12_0(), Ligne_12_5(), Lignes_centrees_0_3(), Lignes_centrees_0_7(), Lignes_centrees_12_7(), Polyform_12_0(), Polyform_12_8(), Polygone_12_0(), Tracer_cercle_vide_Preview(), Tracer_courbe_Preview(), Tracer_ellipse_vide_Preview(), and Tracer_ligne_Preview().
void Pixel_figure_Preview_auto (word Pos_X, word Pos_Y)
References Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, Lit_pixel_dans_ecran_courant(), and Pixel_Preview.
Referenced by K_Ligne_0_6(), K_Ligne_12_7(), Ligne_0_5(), Lignes_centrees_12_7(), Polyform_12_8(), and Polygone_12_9().
void Pixel_figure_Preview_xor (word Pos_X, word Pos_Y, byte Couleur)
void Pixel_figure_Preview_xorback (word Pos_X, word Pos_Y, byte Couleur)
void Pixel_figure_Dans_brosse (word Pos_X, word Pos_Y, byte Couleur)
References Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, and Pixel_dans_brosse().
Referenced by Capturer_brosse_au_lasso().
void Tracer_cercle_vide_Definitif (short Centre_X, short Centre_Y, short Rayon, byte Couleur)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Definitif(), and Tracer_cercle_vide_General().
Referenced by Cercle_vide_0_5().
void Tracer_cercle_vide_Preview (short Centre_X, short Centre_Y, short Rayon, byte Couleur)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Preview(), and Tracer_cercle_vide_General().
Referenced by Cercle_12_5(), and Cercle_degrade_12_6().
void Effacer_cercle_vide_Preview (short Centre_X, short Centre_Y, short Rayon)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Effacer_preview(), and Tracer_cercle_vide_General().
Referenced by Cercle_12_5(), Cercle_degrade_0_6(), Cercle_degrade_12_6(), Cercle_degrade_12_8(), Cercle_plein_0_5(), and Cercle_vide_0_5().
void Tracer_cercle_plein (short Centre_X, short Centre_Y, short Rayon, byte Couleur)
References Afficher_pixel(), Cercle_Curseur_X, Cercle_Curseur_Y, Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, Mettre_Ecran_A_Jour(), and Pixel_dans_cercle().
Referenced by Cercle_degrade_0_6(), and Cercle_plein_0_5().
void Tracer_ellipse_vide_Definitif (short Centre_X, short Centre_Y, short Rayon_horizontal, short Rayon_vertical, byte Couleur)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Definitif(), and Tracer_ellipse_vide_General().
Referenced by Ellipse_vide_0_5().
void Tracer_ellipse_vide_Preview (short Centre_X, short Centre_Y, short Rayon_horizontal, short Rayon_vertical, byte Couleur)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Preview(), and Tracer_ellipse_vide_General().
Referenced by Ellipse_12_5(), and Ellipse_degradee_12_6().
void Effacer_ellipse_vide_Preview (short Centre_X, short Centre_Y, short Rayon_horizontal, short Rayon_vertical)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Effacer_preview(), and Tracer_ellipse_vide_General().
Referenced by Ellipse_12_5(), Ellipse_degradee_0_6(), Ellipse_degradee_12_6(), Ellipse_degradee_12_8(), Ellipse_pleine_0_5(), and Ellipse_vide_0_5().
void Tracer_ellipse_pleine (short Centre_X, short Centre_Y, short Rayon_horizontal, short Rayon_vertical, byte Couleur)
References Afficher_pixel(), Ellipse_Calculer_limites(), Ellipse_Curseur_X, Ellipse_Curseur_Y, Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, Mettre_Ecran_A_Jour(), and Pixel_dans_ellipse().
Referenced by Ellipse_degradee_0_6(), and Ellipse_pleine_0_5().
void Rectifier_coordonnees_a_45_degres (short AX, short AY, short * BX, short * BY)
Referenced by Ligne_0_5(), Ligne_12_5(), and Rectangle_Degrade_12_9().
void Tracer_ligne_General (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
References Pixel_figure.
Referenced by Capturer_brosse_au_lasso(), Effacer_ligne_Preview(), Polyfill(), Tracer_courbe_General(), Tracer_ligne_Definitif(), Tracer_ligne_Preview(), Tracer_ligne_Preview_xor(), and Tracer_ligne_Preview_xorback().
void Tracer_ligne_Definitif (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Definitif(), and Tracer_ligne_General().
Referenced by Freehand_Mode1_1_2(), Freehand_Mode1_2_2(), K_Ligne_0_6(), Ligne_0_5(), Lignes_centrees_12_7(), Polyform_12_8(), and Polygone_12_9().
void Tracer_ligne_Preview (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Preview(), and Tracer_ligne_General().
Referenced by Courbe_34_points_1_5(), Courbe_34_points_2_5(), K_Ligne_12_6(), Ligne_12_5(), Lignes_centrees_0_7(), Lignes_centrees_12_7(), and Polyform_0_8().
void Tracer_ligne_Preview_xor (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Preview_xor(), and Tracer_ligne_General().
Referenced by Afficher_curseur(), Effacer_curseur(), Filled_polyform_0_8(), Filled_polyform_12_8(), Polybrosse_12_8(), Polyfill_0_8(), Polyfill_12_8(), Polyfill_12_9(), and Rectangle_Degrade_12_9().
void Tracer_ligne_Preview_xorback (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Preview_xorback(), and Tracer_ligne_General().
Referenced by Filled_polyform_12_8().
void Effacer_ligne_Preview (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y)
References Mettre_Ecran_A_Jour(), Pixel_figure, Pixel_figure_Effacer_preview(), and Tracer_ligne_General().
Referenced by Courbe_34_points_1_5(), Courbe_34_points_2_5(), Courbe_3_points_0_5(), Courbe_4_points_0_5(), K_Ligne_0_6(), K_Ligne_12_6(), K_Ligne_12_7(), Ligne_0_5(), Ligne_12_5(), Lignes_centrees_0_7(), Lignes_centrees_12_7(), Polyform_0_8(), Polyform_12_8(), Polygone_12_9(), and Rectangle_Degrade_0_9().
void Tracer_rectangle_vide (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
References Afficher_pinceau(), and Mettre_Ecran_A_Jour().
Referenced by Rectangle_vide_0_5().
void Tracer_rectangle_plein (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y, byte Couleur)
References Afficher_pixel(), Limite_Bas, Limite_Droite, and Mettre_Ecran_A_Jour().
Referenced by Rectangle_plein_0_5().
void Tracer_courbe_Definitif (short X1, short Y1, short X2, short Y2, short X3, short Y3, short X4, short Y4, byte Couleur)
References Pixel_figure, Pixel_figure_Definitif(), and Tracer_courbe_General().
Referenced by Courbe_3_points_12_11(), and Courbe_4_points_2_9().
void Tracer_courbe_Preview (short X1, short Y1, short X2, short Y2, short X3, short Y3, short X4, short Y4, byte Couleur)
References Pixel_figure, Pixel_figure_Preview(), and Tracer_courbe_General().
Referenced by Courbe_3_points_0_11(), Courbe_3_points_0_5(), Courbe_4_points_0_5(), and Courbe_4_points_1_9().
void Effacer_courbe_Preview (short X1, short Y1, short X2, short Y2, short X3, short Y3, short X4, short Y4, byte Couleur)
References Pixel_figure, Pixel_figure_Effacer_preview(), and Tracer_courbe_General().
Referenced by Courbe_3_points_0_11(), Courbe_3_points_12_11(), Courbe_4_points_1_9(), and Courbe_4_points_2_9().
void Aerographe (short Bouton_clicke)
References A_GAUCHE, Afficher_curseur(), Afficher_pinceau(), Back_color, Effacer_curseur, Fore_color, Pinceau_X, Pinceau_Y, Spray_Mode, Spray_Mono_flow, Spray_Multi_flow, and Spray_Size.
Referenced by Spray_12_2(), Spray_1_0(), and Spray_2_0().
void Degrade_de_base (long Indice, short Pos_X, short Pos_Y)
References Degrade_Borne_Inferieure, Degrade_Borne_Superieure, Degrade_Intervalle_bornes, Degrade_Intervalle_total, Degrade_Inverse, Degrade_Melange_aleatoire, and Traiter_pixel_de_degrade.
Referenced by Degrade_Charger_infos_du_tableau().
void Degrade_de_trames_simples (long Indice, short Pos_X, short Pos_Y)
References Degrade_Borne_Inferieure, Degrade_Borne_Superieure, Degrade_Intervalle_bornes, Degrade_Intervalle_total, Degrade_Inverse, Degrade_Melange_aleatoire, and Traiter_pixel_de_degrade.
Referenced by Degrade_Charger_infos_du_tableau().
void Degrade_de_trames_etendues (long Indice, short Pos_X, short Pos_Y)
References Degrade_Borne_Inferieure, Degrade_Borne_Superieure, Degrade_Intervalle_bornes, Degrade_Intervalle_total, Degrade_Inverse, Degrade_Melange_aleatoire, and Traiter_pixel_de_degrade.
Referenced by Degrade_Charger_infos_du_tableau().
void Degrade_aleatoire (long Indice, short Pos_X, short Pos_Y)
void Tracer_cercle_degrade (short Centre_X, short Centre_Y, short Rayon, short Eclairage_X, short Eclairage_Y)
References Cercle_Curseur_X, Cercle_Curseur_Y, Cercle_Limite, Degrade_Intervalle_total, Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, Mettre_Ecran_A_Jour(), Pixel_dans_cercle(), and Traiter_degrade.
Referenced by Cercle_degrade_12_8().
void Tracer_ellipse_degradee (short Centre_X, short Centre_Y, short Rayon_horizontal, short Rayon_vertical, short Eclairage_X, short Eclairage_Y)
References Degrade_Intervalle_total, Ellipse_Calculer_limites(), Ellipse_Curseur_X, Ellipse_Curseur_Y, Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, Mettre_Ecran_A_Jour(), Pixel_dans_ellipse(), and Traiter_degrade.
Referenced by Ellipse_degradee_12_8().
void Tracer_rectangle_degrade (short RAX, short RAY, short RBX, short RBY, short VAX, short VAY, short VBX, short VBY)
References Degrade_Intervalle_total, Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, Mettre_Ecran_A_Jour(), and Traiter_degrade.
Referenced by Rectangle_Degrade_0_9().
void Polyfill_General (int Vertices, short * Points, int Color)
References add_edge(), POLYGON_EDGE::bottom, POLYGON_EDGE::dx, fill_edge_structure(), Limite_Bas, Limite_Droite, Limite_Gauche, Limite_Haut, Mettre_Ecran_A_Jour(), POLYGON_EDGE::next, Pixel_figure, POLYGON_EDGE::prev, Principal_Largeur_image, remove_edge(), POLYGON_EDGE::top, POLYGON_EDGE::w, and POLYGON_EDGE::x.
Referenced by Capturer_brosse_au_lasso(), and Polyfill().
void Polyfill (int Vertices, short * Points, int Color)
References Ecran_backup, FX_Feedback_Ecran, Mettre_Ecran_A_Jour(), Pixel_clippe(), Pixel_figure, Polyfill_General(), and Tracer_ligne_General().
Referenced by Filled_contour_0_8(), Filled_polyform_12_8(), and Polyfill_12_9().
void Download_infos_page_principal (S_Page * Page)
Referenced by Backup(), Backup_avec_nouvelles_dimensions(), Charger_image(), Detruire_la_page_courante(), Initialiser_les_listes_de_backups_en_debut_de_programme(), Interchanger_image_principale_et_brouillon(), Redo(), and Undo().
void Download_infos_page_brouillon (S_Page * Page)
Referenced by Backuper_et_redimensionner_brouillon(), Initialiser_les_listes_de_backups_en_debut_de_programme(), and Interchanger_image_principale_et_brouillon().
void Download_infos_backup (S_Liste_de_pages * Liste)
Referenced by Backup(), Backup_avec_nouvelles_dimensions(), Detruire_la_page_courante(), Initialiser_les_listes_de_backups_en_debut_de_programme(), Interchanger_image_principale_et_brouillon(), Redo(), and Undo().
void Detruire_les_listes_de_backups_en_fin_de_programme (void)
void Nouveau_nombre_de_backups (int Nouveau)
Referenced by Bouton_Settings(), and Fermeture_du_programme().
int Backup_avec_nouvelles_dimensions (int Upload, int Largeur, int Hauteur)
Referenced by Initialiser_preview(), and Redimentionner_image().
int Backuper_et_redimensionner_brouillon (int Largeur, int Hauteur)
Referenced by Copier_image_seule().
void Undo (void)
Referenced by Bouton_Undo().
void Redo (void)
Referenced by Bouton_Redo().
void Detruire_la_page_courante (void)
Referenced by Bouton_Kill().
void Interchanger_image_principale_et_brouillon (void)
Referenced by Bouton_Page().
void Changer_facteur_loupe (byte Indice_facteur)
References Calculer_coordonnees_pinceau(), Calculer_donnees_loupe(), Calculer_limites(), FACTEUR_ZOOM, Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Facteur, Loupe_Hauteur, Loupe_Largeur, Loupe_Mode, Pixel_Preview, Pixel_Preview_Loupe, Pixel_Preview_Normal, Principal_Hauteur_image, Principal_Largeur_image, Recadrer_ecran_par_rapport_au_zoom(), Table_mul_facteur_zoom, and TABLE_ZOOM.
Referenced by Bouton_Menu_Loupe(), Bouton_Page(), and Zoom().
void Remap_picture (void)
References Brouillon_Ecran, Brouillon_Hauteur_image, Brouillon_Largeur_image, Brouillon_Palette, Lit_pixel_dans_ecran_brouillon(), Meilleure_couleur(), and Remap_general_LOWLEVEL().
Referenced by Bouton_Copy_page().
void Mettre_Ecran_A_Jour (short X, short Y, short Largeur, short Hauteur)
References LARGEUR_BARRE_SPLIT, Largeur_ecran, Loupe_Decalage_X, Loupe_Decalage_Y, Loupe_Facteur, Loupe_Mode, Menu_Facteur_X, Menu_Ordonnee, Principal_Decalage_X, Principal_Decalage_Y, Principal_Split, and UpdateRect().
Referenced by Afficher_pinceau(), Capturer_brosse(), Cercle_degrade_12_0(), Courbe_34_points_1_0(), Courbe_34_points_2_0(), Courbe_Tracer_croix(), Effacer_cercle_vide_Preview(), Effacer_ellipse_vide_Preview(), Effacer_ligne_Preview(), Effacer_pinceau(), Ellipse_degradee_12_0(), Etirer_brosse_preview(), Filled_polyform_12_0(), Ligne_12_0(), Polyfill(), Polyfill_12_0(), Polyfill_General(), Polygone_12_0(), Tourner_brosse_preview(), Tracer_cercle_degrade(), Tracer_cercle_plein(), Tracer_cercle_vide_Definitif(), Tracer_cercle_vide_General(), Tracer_cercle_vide_Preview(), Tracer_courbe_General(), Tracer_ellipse_degradee(), Tracer_ellipse_pleine(), Tracer_ellipse_vide_Definitif(), Tracer_ellipse_vide_General(), Tracer_ellipse_vide_Preview(), Tracer_ligne_Definitif(), Tracer_ligne_Preview(), Tracer_ligne_Preview_xor(), Tracer_ligne_Preview_xorback(), Tracer_rectangle_degrade(), Tracer_rectangle_plein(), and Tracer_rectangle_vide().
Variable Documentation
fonction_afficheur Pixel_figure
Referenced by Capturer_brosse_au_lasso(), Effacer_cercle_vide_Preview(), Effacer_courbe_Preview(), Effacer_ellipse_vide_Preview(), Effacer_ligne_Preview(), Polyfill(), Polyfill_General(), Tracer_cercle_vide_Definitif(), Tracer_cercle_vide_General(), Tracer_cercle_vide_Preview(), Tracer_courbe_Definitif(), Tracer_courbe_General(), Tracer_courbe_Preview(), Tracer_ellipse_vide_Definitif(), Tracer_ellipse_vide_General(), Tracer_ellipse_vide_Preview(), Tracer_ligne_Definitif(), Tracer_ligne_General(), Tracer_ligne_Preview(), Tracer_ligne_Preview_xor(), and Tracer_ligne_Preview_xorback().