GrafX2: graph.c File Reference
graph.c File Reference
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include "global.h"
#include "struct.h"
#include "engine.h"
#include "buttons.h"
#include "pages.h"
#include "errors.h"
#include "sdlscreen.h"
#include "graph.h"
#include "misc.h"
#include "pxsimple.h"
#include "pxtall.h"
#include "pxwide.h"
#include "pxdouble.h"
#include "pxtriple.h"
#include "pxwide2.h"
#include "pxtall2.h"
#include "pxquad.h"
#include "windows.h"
#include "input.h"
Data Structures
struct T_Polygon_edge
Functions
void Update_part_of_screen (short x, short y, short width, short height)
void Transform_point (short x, short y, float cos_a, float sin_a, short *rx, short *ry)
int Init_mode_video (int width, int height, int fullscreen, int pix_ratio)
void Resize_image (word chosen_width, word chosen_height)
void Remap_spare (void)
Remap the spare page according to the main page's palette.
void Get_colors_from_brush (void)
Get color indexes used by the brush.
void Fill (short *top_reached, short *bottom_reached, short *left_reached, short *right_reached)
byte Read_pixel_from_backup_layer (word x, word y)
void Fill_general (byte fill_color)
void Init_permanent_draw (void)
void Pixel_figure_permanent (word x_pos, word y_pos, byte color)
void Pixel_clipped (word x_pos, word y_pos, byte color)
void Pixel_figure_preview (word x_pos, word y_pos, byte color)
void Pixel_figure_preview_auto (word x_pos, word y_pos)
void Pixel_figure_preview_xor (word x_pos, word y_pos, byte color)
void Pixel_figure_preview_xorback (word x_pos, word y_pos, byte color)
void Pixel_figure_clear_preview (word x_pos, word y_pos, byte color)
void Pixel_figure_in_brush (word x_pos, word y_pos, byte color)
void Draw_empty_circle_general (short center_x, short center_y, short radius, byte color)
void Draw_empty_circle_permanent (short center_x, short center_y, short radius, byte color)
void Draw_empty_circle_preview (short center_x, short center_y, short radius, byte color)
void Hide_empty_circle_preview (short center_x, short center_y, short radius)
void Draw_filled_circle (short center_x, short center_y, short radius, byte color)
void Draw_empty_ellipse_general (short center_x, short center_y, short horizontal_radius, short vertical_radius, byte color)
void Draw_empty_ellipse_permanent (short center_x, short center_y, short horizontal_radius, short vertical_radius, byte color)
void Draw_empty_ellipse_preview (short center_x, short center_y, short horizontal_radius, short vertical_radius, byte color)
void Hide_empty_ellipse_preview (short center_x, short center_y, short horizontal_radius, short vertical_radius)
void Draw_filled_ellipse (short center_x, short center_y, short horizontal_radius, short vertical_radius, byte color)
void Clamp_coordinates_regular_angle (short ax, short ay, short *bx, short *by)
Alters bx and by so the (AX,AY)-(BX,BY) segment becomes either horizontal, vertical, 45degrees, or isometrical for pixelart (ie 2:1 ratio)
void Draw_line_general (short start_x, short start_y, short end_x, short end_y, byte color)
void Draw_line_permanent (short start_x, short start_y, short end_x, short end_y, byte color)
void Draw_line_preview (short start_x, short start_y, short end_x, short end_y, byte color)
void Draw_line_preview_xor (short start_x, short start_y, short end_x, short end_y, byte color)
void Draw_line_preview_xorback (short start_x, short start_y, short end_x, short end_y, byte color)
void Hide_line_preview (short start_x, short start_y, short end_x, short end_y)
void Draw_empty_rectangle (short start_x, short start_y, short end_x, short end_y, byte color)
void Draw_filled_rectangle (short start_x, short start_y, short end_x, short end_y, byte color)
void Draw_curve_general (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4, byte color)
void Draw_curve_permanent (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4, byte color)
void Draw_curve_preview (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4, byte color)
void Hide_curve_preview (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4, byte color)
void Airbrush (short clicked_button)
void Gradient_basic (long index, short x_pos, short y_pos)
void Gradient_dithered (long index, short x_pos, short y_pos)
void Gradient_extra_dithered (long index, short x_pos, short y_pos)
void Draw_grad_circle (short center_x, short center_y, short radius, short spot_x, short spot_y)
void Draw_grad_ellipse (short center_x, short center_y, short horizontal_radius, short vertical_radius, short spot_x, short spot_y)
void Draw_grad_rectangle (short rax, short ray, short rbx, short rby, short vax, short vay, short vbx, short vby)
void Fill_edge_structure (T_Polygon_edge *edge, short *i1, short *i2)
T_Polygon_edge * Add_edge (T_Polygon_edge *list, T_Polygon_edge *edge, int sort_by_x)
T_Polygon_edge * Remove_edge (T_Polygon_edge *list, T_Polygon_edge *edge)
void Polyfill_general (int vertices, short *points, int color)
void Polyfill (int vertices, short *points, int color)
void Replace (byte New_color)
void Shade_list_to_lookup_tables (word *list, short step, byte mode, byte *table_inc, byte *table_dec)
void Display_pixel (word x, word y, byte color)
byte No_effect (word x, word y, byte color)
byte Effect_shade (word x, word y, byte color)
byte Effect_quick_shade (word x, word y, byte color)
byte Effect_tiling (word x, word y, byte color)
byte Effect_smooth (word x, word y, byte color)
void Horizontal_grid_line (word x_pos, word y_pos, word width)
void Vertical_grid_line (word x_pos, word y_pos, word height)
void Redraw_grid (short x, short y, unsigned short w, unsigned short h)
byte Read_pixel_from_current_screen (word x, word y)
void Pixel_in_current_screen (word x, word y, byte color, int with_preview)
void Pixel_in_current_layer (word x, word y, byte color)
byte Read_pixel_from_current_layer (word x, word y)
Variables
Func_pixel Pixel_figure
All the figure-drawing functions work by calling this function for each pixel to draw.
static Uint32 Permanent_draw_next_refresh = 0
static int Permanent_draw_count = 0
Function Documentation
void Update_part_of_screen (short x, short y, short width, short height)
References Main_image_height, Main_image_width, Main_magnifier_factor, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_offset_X, Main_offset_Y, Main_separator_position, Main_X_zoom, Menu_factor_X, Menu_Y, Min(), Redraw_grid(), Screen_width, SEPARATOR_WIDTH, and Update_rect().
Referenced by Capture_brush(), Curve_34_points_1_0(), Curve_34_points_2_0(), Display_paintbrush(), Distort_brush_1_0(), Draw_curve_cross(), Draw_curve_general(), Draw_empty_circle_general(), Draw_empty_circle_permanent(), Draw_empty_circle_preview(), Draw_empty_ellipse_general(), Draw_empty_ellipse_permanent(), Draw_empty_ellipse_preview(), Draw_empty_rectangle(), Draw_filled_circle(), Draw_filled_ellipse(), Draw_filled_rectangle(), Draw_grad_circle(), Draw_grad_ellipse(), Draw_grad_rectangle(), Draw_line_permanent(), Draw_line_preview(), Draw_line_preview_xor(), Draw_line_preview_xorback(), Draw_stretch_spot(), Filled_polyform_12_0(), Grad_circle_12_0(), Grad_ellipse_12_0(), Hide_empty_circle_preview(), Hide_empty_ellipse_preview(), Hide_line_preview(), Hide_paintbrush(), Line_12_0(), Polyfill(), Polyfill_12_0(), Polyfill_general(), Polygon_12_0(), Rotate_brush_preview(), and Stretch_brush_preview().
void Transform_point (short x, short y, float cos_a, float sin_a, short * rx, short * ry)
References Round().
Referenced by Display_cursor(), Hide_cursor(), Rotate_brush(), and Rotate_brush_preview().
int Init_mode_video (int width, int height, int fullscreen, int pix_ratio)
References Adjust_mouse_sensitivity(), Block, Block_double(), Block_quad(), Block_simple(), Block_tall(), Block_tall2(), Block_triple(), Block_wide(), Block_wide2(), byte, Change_palette_cells(), Clear_border(), Clear_brush, Clear_brush_double(), Clear_brush_quad(), Clear_brush_scaled, Clear_brush_scaled_double(), Clear_brush_scaled_quad(), Clear_brush_scaled_simple(), Clear_brush_scaled_tall(), Clear_brush_scaled_tall2(), Clear_brush_scaled_triple(), Clear_brush_scaled_wide(), Clear_brush_scaled_wide2(), Clear_brush_simple(), Clear_brush_tall(), Clear_brush_tall2(), Clear_brush_triple(), Clear_brush_wide(), Clear_brush_wide2(), Compute_limits(), Compute_magnifier_data(), Compute_paintbrush_coordinates(), Config, Current_resolution, Display_brush, Display_brush_color, Display_brush_color_double(), Display_brush_color_quad(), Display_brush_color_simple(), Display_brush_color_tall(), Display_brush_color_tall2(), Display_brush_color_triple(), Display_brush_color_wide(), Display_brush_color_wide2(), Display_brush_color_zoom, Display_brush_color_zoom_double(), Display_brush_color_zoom_quad(), Display_brush_color_zoom_simple(), Display_brush_color_zoom_tall(), Display_brush_color_zoom_tall2(), Display_brush_color_zoom_triple(), Display_brush_color_zoom_wide(), Display_brush_color_zoom_wide2(), Display_brush_double(), Display_brush_mono, Display_brush_mono_double(), Display_brush_mono_quad(), Display_brush_mono_simple(), Display_brush_mono_tall(), Display_brush_mono_tall2(), Display_brush_mono_triple(), Display_brush_mono_wide(), Display_brush_mono_wide2(), Display_brush_mono_zoom, Display_brush_mono_zoom_double(), Display_brush_mono_zoom_quad(), Display_brush_mono_zoom_simple(), Display_brush_mono_zoom_tall(), Display_brush_mono_zoom_tall2(), Display_brush_mono_zoom_triple(), Display_brush_mono_zoom_wide(), Display_brush_mono_zoom_wide2(), Display_brush_quad(), Display_brush_simple(), Display_brush_tall(), Display_brush_tall2(), Display_brush_triple(), Display_brush_wide(), Display_brush_wide2(), Display_line, Display_line_fast, Display_line_on_screen_double(), Display_line_on_screen_fast_double(), Display_line_on_screen_fast_quad(), Display_line_on_screen_fast_tall2(), Display_line_on_screen_fast_triple(), Display_line_on_screen_fast_wide(), Display_line_on_screen_fast_wide2(), Display_line_on_screen_quad(), Display_line_on_screen_simple(), Display_line_on_screen_tall(), Display_line_on_screen_tall2(), Display_line_on_screen_triple(), Display_line_on_screen_wide(), Display_line_on_screen_wide2(), Display_part_of_screen_double(), Display_part_of_screen_quad(), Display_part_of_screen_scaled_double(), Display_part_of_screen_scaled_quad(), Display_part_of_screen_scaled_simple(), Display_part_of_screen_scaled_tall(), Display_part_of_screen_scaled_tall2(), Display_part_of_screen_scaled_triple(), Display_part_of_screen_scaled_wide(), Display_part_of_screen_scaled_wide2(), Display_part_of_screen_simple(), Display_part_of_screen_tall(), Display_part_of_screen_tall2(), Display_part_of_screen_triple(), Display_part_of_screen_wide(), Display_part_of_screen_wide2(), Display_screen, Display_zoomed_screen, T_Video_mode::Fullscreen, Height, T_Video_mode::Height, Horizontal_line_buffer, Horizontal_XOR_line, Horizontal_XOR_line_double(), Horizontal_XOR_line_quad(), Horizontal_XOR_line_simple(), Horizontal_XOR_line_tall(), Horizontal_XOR_line_tall2(), Horizontal_XOR_line_triple(), Horizontal_XOR_line_wide(), Horizontal_XOR_line_wide2(), Main_image_height, Main_image_width, Main_magnifier_mode, Main_offset_X, Main_offset_Y, Main_palette, Max(), MC_Black, Menu_factor_X, Menu_factor_Y, Menu_height, Menu_is_visible, Menu_status_Y, Menu_Y, Min(), Mouse_X, Mouse_Y, Nb_video_modes, Pixel, Pixel_double(), PIXEL_DOUBLE, Pixel_height, Pixel_preview, Pixel_preview_magnifier, Pixel_preview_magnifier_double(), Pixel_preview_magnifier_quad(), Pixel_preview_magnifier_simple(), Pixel_preview_magnifier_tall(), Pixel_preview_magnifier_tall2(), Pixel_preview_magnifier_triple(), Pixel_preview_magnifier_wide(), Pixel_preview_magnifier_wide2(), Pixel_preview_normal, Pixel_preview_normal_double(), Pixel_preview_normal_quad(), Pixel_preview_normal_simple(), Pixel_preview_normal_tall(), Pixel_preview_normal_tall2(), Pixel_preview_normal_triple(), Pixel_preview_normal_wide(), Pixel_preview_normal_wide2(), Pixel_quad(), PIXEL_QUAD, Pixel_ratio, Pixel_simple(), PIXEL_SIMPLE, Pixel_tall(), PIXEL_TALL, Pixel_tall2(), PIXEL_TALL2, Pixel_triple(), PIXEL_TRIPLE, Pixel_wide(), PIXEL_WIDE, Pixel_wide2(), PIXEL_WIDE2, Pixel_width, Position_screen_according_to_zoom(), T_Config::Ratio, Read_line, Read_line_screen_double(), Read_line_screen_quad(), Read_line_screen_simple(), Read_line_screen_tall(), Read_line_screen_tall2(), Read_line_screen_triple(), Read_line_screen_wide(), Read_line_screen_wide2(), Read_pixel, Read_pixel_double(), Read_pixel_quad(), Read_pixel_simple(), Read_pixel_tall(), Read_pixel_tall2(), Read_pixel_triple(), Read_pixel_wide(), Read_pixel_wide2(), Remap_screen, Remap_screen_double(), Remap_screen_quad(), Remap_screen_simple(), Remap_screen_tall(), Remap_screen_tall2(), Remap_screen_triple(), Remap_screen_wide(), Remap_screen_wide2(), Resize_height, Resize_width, Screen_height, Screen_width, Set_mode_SDL(), Set_mouse_position(), Set_palette(), Spare_magnifier_mode, Spare_offset_X, Spare_offset_Y, Verbose_message(), Vertical_XOR_line, Vertical_XOR_line_double(), Vertical_XOR_line_quad(), Vertical_XOR_line_simple(), Vertical_XOR_line_tall(), Vertical_XOR_line_tall2(), Vertical_XOR_line_triple(), Vertical_XOR_line_wide(), Vertical_XOR_line_wide2(), Video_mode, Width, and T_Video_mode::Width.
Referenced by Button_Reload(), Button_Resolution(), Button_Safety_resolution(), Init_program(), Load_picture(), and Main_handler().
void Resize_image (word chosen_width, word chosen_height)
References Backup_with_new_dimensions(), Copy_part_of_image_to_another(), Display_cursor(), Hide_cursor, T_Page::Image, Main_backups, Main_image_height, Main_image_is_modified, Main_image_width, Message_out_of_memory(), Min(), T_Page::Nb_layers, T_Page::Next, T_List_of_pages::Pages, Redraw_layered_image(), Upload_infos_page_main(), and word.
Referenced by Button_Resolution().
void Remap_spare (void)
Remap the spare page according to the main page's palette.
References Best_color_perceptual(), byte, T_Page::Image, T_Page::Nb_layers, T_List_of_pages::Pages, Remap_general_lowlevel(), Spare_backups, Spare_image_height, Spare_image_width, Spare_palette, and T_Page::Transparent_color.
Referenced by Button_Copy_page().
void Get_colors_from_brush (void)
Get color indexes used by the brush.
References Backup_layers(), Brush_height, Brush_width, byte, Compute_optimal_menu_colors(), Confirmation_box(), Display_all_screen(), Display_cursor(), Display_menu(), End_of_modification(), Hide_cursor, Main_image_is_modified, Main_palette, Read_pixel_from_brush(), Set_palette(), and Spare_palette.
Referenced by Button_Brush_FX(), and Main_handler().
void Fill (short * top_reached, short * bottom_reached, short * left_reached, short * right_reached)
References Limit_bottom, Limit_left, Limit_right, Limit_top, Min(), Paintbrush_X, Paintbrush_Y, Pixel_in_current_layer(), and Read_pixel_from_current_layer().
Referenced by Fill_general().
byte Read_pixel_from_backup_layer (word x, word y)
References T_Page::Image, Main_backups, Main_current_layer, Main_image_width, T_Page::Next, and T_List_of_pages::Pages.
Referenced by Fill_general().
void Fill_general (byte fill_color)
References Backup(), byte, Config, Copy_part_of_image_to_another(), Cursor_shape, CURSOR_SHAPE_HOURGLASS, Display_cursor(), Display_pixel(), End_of_modification(), Fill(), T_Config::FX_Feedback, Hide_cursor, T_Page::Image, Limit_bottom, Limit_left, Limit_right, Limit_top, Main_backups, Main_current_layer, Main_image_height, Main_image_width, Main_magnifier_factor, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_X_zoom, Menu_Y, Min(), T_Page::Next, T_List_of_pages::Pages, Paintbrush_X, Paintbrush_Y, Pixel_in_current_screen(), Read_pixel_from_backup_layer(), Read_pixel_from_current_layer(), Redraw_grid(), Replace_colors_within_limits(), Screen_width, Update_FX_feedback(), and Update_rect().
Referenced by Fill_1_0(), and Fill_2_0().
void Init_permanent_draw (void)
References Permanent_draw_count, and Permanent_draw_next_refresh.
Referenced by Draw_curve_permanent(), Draw_empty_circle_permanent(), Draw_empty_ellipse_permanent(), Draw_empty_rectangle(), and Draw_line_permanent().
void Pixel_figure_permanent (word x_pos, word y_pos, byte color)
References Display_paintbrush(), Flush_update(), Permanent_draw_count, and Permanent_draw_next_refresh.
Referenced by Draw_curve_permanent(), Draw_empty_circle_permanent(), Draw_empty_ellipse_permanent(), Draw_empty_rectangle(), and Draw_line_permanent().
void Pixel_clipped (word x_pos, word y_pos, byte color)
References Display_pixel(), Limit_bottom, Limit_left, Limit_right, and Limit_top.
Referenced by Polyfill().
void Pixel_figure_preview (word x_pos, word y_pos, byte color)
References Limit_bottom, Limit_left, Limit_right, Limit_top, and Pixel_preview.
Referenced by Centered_lines_0_3(), Centered_lines_0_7(), Centered_lines_12_7(), Curve_34_points_1_0(), Curve_34_points_1_5(), Curve_34_points_2_0(), Curve_34_points_2_5(), Distort_brush_preview(), Draw_curve_preview(), Draw_empty_circle_preview(), Draw_empty_ellipse_preview(), Draw_line_preview(), Grad_circle_12_0(), Grad_ellipse_12_0(), K_line_12_0(), K_line_12_6(), Line_12_0(), Line_12_5(), Polyform_12_0(), Polyform_12_8(), and Polygon_12_0().
void Pixel_figure_preview_auto (word x_pos, word y_pos)
References Limit_bottom, Limit_left, Limit_right, Limit_top, Pixel_preview, and Read_pixel_from_current_screen().
Referenced by Centered_lines_12_7(), K_line_0_6(), K_line_12_7(), Line_0_5(), Polyform_12_8(), and Polygon_12_9().
void Pixel_figure_preview_xor (word x_pos, word y_pos, byte color)
References Limit_bottom, Limit_left, Limit_right, Limit_top, Main_offset_X, Main_offset_Y, Pixel_preview, and Read_pixel.
Referenced by Display_cursor(), Draw_line_preview_xor(), Filled_polyform_12_0(), Hide_cursor(), and Polyfill_12_0().
void Pixel_figure_preview_xorback (word x_pos, word y_pos, byte color)
References Limit_bottom, Limit_left, Limit_right, Limit_top, Main_image_width, Pixel_preview, and Screen_backup.
Referenced by Draw_line_preview_xorback().
void Pixel_figure_clear_preview (word x_pos, word y_pos, byte color)
References Limit_bottom, Limit_left, Limit_right, Limit_top, Pixel_preview, and Read_pixel_from_current_screen().
Referenced by Hide_curve_preview(), Hide_empty_circle_preview(), Hide_empty_ellipse_preview(), and Hide_line_preview().
void Pixel_figure_in_brush (word x_pos, word y_pos, byte color)
References Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, and Pixel_in_brush().
Referenced by Capture_brush_with_lasso().
void Draw_empty_circle_general (short center_x, short center_y, short radius, byte color)
References Circle_cursor_X, Circle_cursor_Y, Main_magnifier_mode, Pixel_figure, Pixel_in_circle(), and Update_part_of_screen().
Referenced by Draw_empty_circle_permanent(), Draw_empty_circle_preview(), and Hide_empty_circle_preview().
void Draw_empty_circle_permanent (short center_x, short center_y, short radius, byte color)
References Draw_empty_circle_general(), Init_permanent_draw(), Pixel_figure, Pixel_figure_permanent(), and Update_part_of_screen().
Referenced by Empty_circle_0_5().
void Draw_empty_circle_preview (short center_x, short center_y, short radius, byte color)
References Draw_empty_circle_general(), Pixel_figure, Pixel_figure_preview(), and Update_part_of_screen().
Referenced by Circle_12_5(), and Grad_circle_12_6().
void Hide_empty_circle_preview (short center_x, short center_y, short radius)
References Draw_empty_circle_general(), Pixel_figure, Pixel_figure_clear_preview(), and Update_part_of_screen().
Referenced by Circle_12_5(), Empty_circle_0_5(), Filled_circle_0_5(), Grad_circle_0_6(), Grad_circle_12_6(), and Grad_circle_12_8().
void Draw_filled_circle (short center_x, short center_y, short radius, byte color)
References Circle_cursor_X, Circle_cursor_Y, Display_pixel(), Limit_bottom, Limit_left, Limit_right, Limit_top, Pixel_in_circle(), and Update_part_of_screen().
Referenced by Filled_circle_0_5(), and Grad_circle_0_6().
void Draw_empty_ellipse_general (short center_x, short center_y, short horizontal_radius, short vertical_radius, byte color)
References Ellipse_compute_limites(), Ellipse_cursor_X, Ellipse_cursor_Y, Pixel_figure, Pixel_in_ellipse(), and Update_part_of_screen().
Referenced by Draw_empty_ellipse_permanent(), Draw_empty_ellipse_preview(), and Hide_empty_ellipse_preview().
void Draw_empty_ellipse_permanent (short center_x, short center_y, short horizontal_radius, short vertical_radius, byte color)
References Draw_empty_ellipse_general(), Init_permanent_draw(), Pixel_figure, Pixel_figure_permanent(), and Update_part_of_screen().
Referenced by Empty_ellipse_0_5().
void Draw_empty_ellipse_preview (short center_x, short center_y, short horizontal_radius, short vertical_radius, byte color)
References Draw_empty_ellipse_general(), Pixel_figure, Pixel_figure_preview(), and Update_part_of_screen().
Referenced by Ellipse_12_5(), and Grad_ellipse_12_6().
void Hide_empty_ellipse_preview (short center_x, short center_y, short horizontal_radius, short vertical_radius)
References Draw_empty_ellipse_general(), Pixel_figure, Pixel_figure_clear_preview(), and Update_part_of_screen().
Referenced by Ellipse_12_5(), Empty_ellipse_0_5(), Filled_ellipse_0_5(), Grad_ellipse_0_6(), Grad_ellipse_12_6(), and Grad_ellipse_12_8().
void Draw_filled_ellipse (short center_x, short center_y, short horizontal_radius, short vertical_radius, byte color)
References Display_pixel(), Ellipse_compute_limites(), Ellipse_cursor_X, Ellipse_cursor_Y, Limit_bottom, Limit_left, Limit_right, Limit_top, Pixel_in_ellipse(), and Update_part_of_screen().
Referenced by Filled_ellipse_0_5(), and Grad_ellipse_0_6().
void Clamp_coordinates_regular_angle (short ax, short ay, short * bx, short * by)
Alters bx and by so the (AX,AY)-(BX,BY) segment becomes either horizontal, vertical, 45degrees, or isometrical for pixelart (ie 2:1 ratio)
Referenced by Grad_rectangle_12_9(), Line_12_5(), Rotate_brush_0_5(), and Rotate_brush_1_5().
void Draw_line_general (short start_x, short start_y, short end_x, short end_y, byte color)
References Pixel_figure.
Referenced by Capture_brush_with_lasso(), Draw_curve_general(), Draw_line_permanent(), Draw_line_preview(), Draw_line_preview_xor(), Draw_line_preview_xorback(), Hide_line_preview(), and Polyfill().
void Draw_line_permanent (short start_x, short start_y, short end_x, short end_y, byte color)
References Draw_line_general(), Init_permanent_draw(), Pixel_figure, Pixel_figure_permanent(), and Update_part_of_screen().
Referenced by Centered_lines_12_7(), Freehand_mode1_1_2(), Freehand_mode1_2_2(), K_line_0_6(), Line_0_5(), Polyform_12_8(), and Polygon_12_9().
void Draw_line_preview (short start_x, short start_y, short end_x, short end_y, byte color)
References Draw_line_general(), Pixel_figure, Pixel_figure_preview(), and Update_part_of_screen().
Referenced by Centered_lines_0_7(), Centered_lines_12_7(), Curve_34_points_1_5(), Curve_34_points_2_5(), K_line_12_6(), Line_12_5(), and Polyform_0_8().
void Draw_line_preview_xor (short start_x, short start_y, short end_x, short end_y, byte color)
References Draw_line_general(), Pixel_figure, Pixel_figure_preview_xor(), and Update_part_of_screen().
Referenced by Display_cursor(), Filled_polyform_0_8(), Filled_polyform_12_8(), Grad_rectangle_12_9(), Hide_cursor(), Polybrush_12_8(), Polyfill_0_8(), Polyfill_12_8(), and Polyfill_12_9().
void Draw_line_preview_xorback (short start_x, short start_y, short end_x, short end_y, byte color)
References Draw_line_general(), Pixel_figure, Pixel_figure_preview_xorback(), and Update_part_of_screen().
Referenced by Filled_polyform_12_8().
void Hide_line_preview (short start_x, short start_y, short end_x, short end_y)
References Draw_line_general(), Pixel_figure, Pixel_figure_clear_preview(), and Update_part_of_screen().
Referenced by Centered_lines_0_7(), Centered_lines_12_7(), Curve_34_points_1_5(), Curve_34_points_2_5(), Curve_3_points_0_5(), Curve_4_points_0_5(), Grad_rectangle_0_9(), K_line_0_6(), K_line_12_6(), K_line_12_7(), Line_0_5(), Line_12_5(), Polyform_0_8(), Polyform_12_8(), and Polygon_12_9().
void Draw_empty_rectangle (short start_x, short start_y, short end_x, short end_y, byte color)
References Init_permanent_draw(), Pixel_figure_permanent(), and Update_part_of_screen().
Referenced by Empty_rectangle_0_5().
void Draw_filled_rectangle (short start_x, short start_y, short end_x, short end_y, byte color)
References Display_pixel(), Limit_bottom, Limit_right, and Update_part_of_screen().
Referenced by Filled_rectangle_0_5().
void Draw_curve_general (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4, byte color)
References Draw_line_general(), Max(), Min(), Pixel_figure, Round(), Update_part_of_screen(), and word.
Referenced by Draw_curve_permanent(), Draw_curve_preview(), and Hide_curve_preview().
void Draw_curve_permanent (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4, byte color)
References Draw_curve_general(), Init_permanent_draw(), Pixel_figure, and Pixel_figure_permanent().
Referenced by Curve_4_points_2_9(), and Curve_finalize().
void Draw_curve_preview (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4, byte color)
References Draw_curve_general(), Pixel_figure, and Pixel_figure_preview().
Referenced by Curve_3_points_0_5(), Curve_4_points_0_5(), Curve_4_points_1_9(), and Curve_drag().
void Hide_curve_preview (short x1, short y1, short x2, short y2, short x3, short y3, short x4, short y4, byte color)
References Draw_curve_general(), Pixel_figure, and Pixel_figure_clear_preview().
Referenced by Curve_4_points_1_9(), Curve_4_points_2_9(), Curve_drag(), and Curve_finalize().
void Airbrush (short clicked_button)
References Airbrush_mode, Airbrush_mono_flow, Airbrush_multi_flow, Airbrush_size, Back_color, byte, Display_cursor(), Display_paintbrush(), Fore_color, Hide_cursor, LEFT_SIDE, Paintbrush_X, and Paintbrush_Y.
Referenced by Airbrush_12_2(), Airbrush_1_0(), and Airbrush_2_0().
void Gradient_basic (long index, short x_pos, short y_pos)
References Gradient_bounds_range, Gradient_is_inverted, Gradient_lower_bound, Gradient_pixel, Gradient_random_factor, Gradient_total_range, and Gradient_upper_bound.
Referenced by Load_gradient_data(), and Set_config_defaults().
void Gradient_dithered (long index, short x_pos, short y_pos)
References Gradient_bounds_range, Gradient_is_inverted, Gradient_lower_bound, Gradient_pixel, Gradient_random_factor, Gradient_total_range, and Gradient_upper_bound.
Referenced by Load_gradient_data().
void Gradient_extra_dithered (long index, short x_pos, short y_pos)
References Gradient_bounds_range, Gradient_is_inverted, Gradient_lower_bound, Gradient_pixel, Gradient_random_factor, Gradient_total_range, and Gradient_upper_bound.
Referenced by Load_gradient_data().
void Draw_grad_circle (short center_x, short center_y, short radius, short spot_x, short spot_y)
References Circle_cursor_X, Circle_cursor_Y, Circle_limit, Gradient_function, Gradient_total_range, Limit_bottom, Limit_left, Limit_right, Limit_top, Pixel_in_circle(), and Update_part_of_screen().
Referenced by Grad_circle_12_8().
void Draw_grad_ellipse (short center_x, short center_y, short horizontal_radius, short vertical_radius, short spot_x, short spot_y)
References Ellipse_compute_limites(), Ellipse_cursor_X, Ellipse_cursor_Y, Gradient_function, Gradient_total_range, Limit_bottom, Limit_left, Limit_right, Limit_top, Pixel_in_ellipse(), and Update_part_of_screen().
Referenced by Grad_ellipse_12_8().
void Draw_grad_rectangle (short rax, short ray, short rbx, short rby, short vax, short vay, short vbx, short vby)
References Gradient_function, Gradient_total_range, Limit_bottom, Limit_left, Limit_right, Limit_top, and Update_part_of_screen().
Referenced by Grad_rectangle_0_9().
void Fill_edge_structure (T_Polygon_edge * edge, short * i1, short * i2)
References T_Polygon_edge::bottom, T_Polygon_edge::dx, T_Polygon_edge::next, T_Polygon_edge::prev, T_Polygon_edge::top, T_Polygon_edge::w, and T_Polygon_edge::x.
Referenced by Polyfill_general().
T_Polygon_edge* Add_edge (T_Polygon_edge * list, T_Polygon_edge * edge, int sort_by_x)
References T_Polygon_edge::dx, T_Polygon_edge::next, T_Polygon_edge::prev, T_Polygon_edge::top, T_Polygon_edge::w, and T_Polygon_edge::x.
Referenced by Polyfill_general().
T_Polygon_edge* Remove_edge (T_Polygon_edge * list, T_Polygon_edge * edge)
References T_Polygon_edge::next, and T_Polygon_edge::prev.
Referenced by Polyfill_general().
void Polyfill_general (int vertices, short * points, int color)
References Add_edge(), T_Polygon_edge::bottom, T_Polygon_edge::dx, Fill_edge_structure(), Limit_bottom, Limit_left, Limit_right, Limit_top, Main_image_width, T_Polygon_edge::next, Pixel_figure, T_Polygon_edge::prev, Remove_edge(), T_Polygon_edge::top, Update_part_of_screen(), T_Polygon_edge::w, and T_Polygon_edge::x.
Referenced by Capture_brush_with_lasso(), and Polyfill().
void Polyfill (int vertices, short * points, int color)
References Config, Draw_line_general(), T_Config::FX_Feedback, Pixel_clipped(), Pixel_figure, Polyfill_general(), Update_FX_feedback(), and Update_part_of_screen().
Referenced by Filled_contour_0_8(), Filled_polyform_12_8(), and Polyfill_12_9().
void Replace (byte New_color)
References byte, Display_all_screen(), Main_image_height, Main_image_width, Paintbrush_X, Paintbrush_Y, Read_pixel_from_current_layer(), Replace_a_color(), Stencil, and Stencil_mode.
Referenced by Replace_1_0(), and Replace_2_0().
void Shade_list_to_lookup_tables (word * list, short step, byte mode, byte * table_inc, byte * table_dec)
References SHADE_MODE_LOOP, and SHADE_MODE_NORMAL.
Referenced by Load_CFG(), Set_config_defaults(), and Shade_settings_menu().
void Display_pixel (word x, word y, byte color)
References Effect_function, Effect_sieve(), Mask_mode, Mask_table, Pixel_in_current_screen(), Read_pixel_from_current_layer(), Read_pixel_from_spare_screen(), Sieve_mode, Stencil, and Stencil_mode.
Referenced by Button_Gradients(), Display_paintbrush(), Draw_filled_circle(), Draw_filled_ellipse(), Draw_filled_rectangle(), Fill_general(), Init_program(), and Pixel_clipped().
byte No_effect (word x, word y, byte color)
Referenced by Button_Colorize_mode(), Button_Quick_shade_mode(), Button_Shade_mode(), Button_Smear_mode(), Button_Smooth_mode(), Button_Tiling_mode(), Effects_off(), and Init_program().
byte Effect_shade (word x, word y, byte color)
References Read_pixel_from_feedback_screen(), and Shade_table.
Referenced by Button_Shade_mode().
byte Effect_quick_shade (word x, word y, byte color)
References Back_color, byte, Fore_color, Quick_shade_loop, Quick_shade_step, Read_pixel_from_feedback_screen(), SHADE_MODE_LOOP, SHADE_MODE_NORMAL, Shade_table, Shade_table_left, and Shade_table_right.
Referenced by Button_Quick_shade_mode().
byte Effect_tiling (word x, word y, byte color)
References Brush_height, Brush_width, Read_pixel_from_brush(), Tiling_offset_X, and Tiling_offset_Y.
Referenced by Button_Tiling_mode().
byte Effect_smooth (word x, word y, byte color)
References Best_color(), byte, Main_image_height, Main_image_width, Main_palette, Read_pixel_from_current_screen(), Read_pixel_from_feedback_screen(), Round_div(), and Smooth_matrix.
Referenced by Button_Smooth_mode().
void Horizontal_grid_line (word x_pos, word y_pos, word width)
References Config, T_Config::Grid_XOR_color, Pixel, Pixel_height, Pixel_width, Screen_pixels, VIDEO_LINE_WIDTH, and T_Polygon_edge::x.
Referenced by Redraw_grid().
void Vertical_grid_line (word x_pos, word y_pos, word height)
References Config, T_Config::Grid_XOR_color, Pixel, Pixel_height, Pixel_width, Screen_pixels, and VIDEO_LINE_WIDTH.
Referenced by Redraw_grid().
void Redraw_grid (short x, short y, unsigned short w, unsigned short h)
References Horizontal_grid_line(), Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_X_zoom, Show_grid, Snap_height, Snap_offset_X, Snap_offset_Y, Snap_width, and Vertical_grid_line().
Referenced by Clear_brush_scaled_double(), Clear_brush_scaled_quad(), Clear_brush_scaled_simple(), Clear_brush_scaled_tall(), Clear_brush_scaled_tall2(), Clear_brush_scaled_triple(), Clear_brush_scaled_wide(), Clear_brush_scaled_wide2(), Display_brush_mono_zoom_double(), Display_brush_mono_zoom_quad(), Display_brush_mono_zoom_simple(), Display_brush_mono_zoom_tall(), Display_brush_mono_zoom_tall2(), Display_brush_mono_zoom_triple(), Display_brush_mono_zoom_wide(), Display_brush_mono_zoom_wide2(), Display_part_of_screen_scaled_double(), Display_part_of_screen_scaled_quad(), Display_part_of_screen_scaled_simple(), Display_part_of_screen_scaled_tall(), Display_part_of_screen_scaled_tall2(), Display_part_of_screen_scaled_triple(), Display_part_of_screen_scaled_wide(), Display_part_of_screen_scaled_wide2(), Fill_general(), and Update_part_of_screen().
byte Read_pixel_from_current_screen (word x, word y)
References byte, T_Page::Image, T_Bitmap::Image, Main_backups, Main_current_layer, Main_image_width, Main_screen, Main_visible_image_depth_buffer, T_List_of_pages::Pages, T_Page::Transparent_color, and T_Polygon_edge::x.
Referenced by Colorpicker_1_1(), Colorpicker_2_1(), Display_paintbrush(), Effect_smooth(), Hide_paintbrush(), Pixel_figure_clear_preview(), Pixel_figure_preview_auto(), Print_coordinates(), and Rightclick_colorpick_2_1().
void Pixel_in_current_screen (word x, word y, byte color, int with_preview)
References byte, T_Page::Image, T_Bitmap::Image, Main_backups, Main_current_layer, Main_image_width, Main_screen, Main_visible_image_depth_buffer, T_List_of_pages::Pages, Pixel_preview, and T_Page::Transparent_color.
Referenced by Capture_brush(), Capture_brush_with_lasso(), Display_pixel(), Fill_general(), Replace_a_color(), and Set_pixel().
void Pixel_in_current_layer (word x, word y, byte color)
References T_Page::Image, Main_backups, Main_current_layer, Main_image_width, and T_List_of_pages::Pages.
Referenced by Fill().
byte Read_pixel_from_current_layer (word x, word y)
References T_Page::Image, Main_backups, Main_current_layer, Main_image_width, and T_List_of_pages::Pages.
Referenced by Capture_brush_with_lasso(), Display_pixel(), Fill(), Fill_general(), Replace(), and Replace_a_color().
Variable Documentation
Func_pixel Pixel_figure
All the figure-drawing functions work by calling this function for each pixel to draw.
Before calling these functions, you should assign Pixel_figure depending on what you where you want to draw:
Pixel_figure_preview : On screen.
Pixel_figure_preview_xor : On screen, XORing the color.
Pixel_figure_permanent : On screen and in the image.
Pixel_figure_clear_preview : On screen, reverting to the image's pixels.
Referenced by Capture_brush_with_lasso(), Draw_curve_general(), Draw_curve_permanent(), Draw_curve_preview(), Draw_empty_circle_general(), Draw_empty_circle_permanent(), Draw_empty_circle_preview(), Draw_empty_ellipse_general(), Draw_empty_ellipse_permanent(), Draw_empty_ellipse_preview(), Draw_line_general(), Draw_line_permanent(), Draw_line_preview(), Draw_line_preview_xor(), Draw_line_preview_xorback(), Hide_curve_preview(), Hide_empty_circle_preview(), Hide_empty_ellipse_preview(), Hide_line_preview(), Polyfill(), and Polyfill_general().
Uint32 Permanent_draw_next_refresh = 0 [static]
Referenced by Init_permanent_draw(), and Pixel_figure_permanent().
int Permanent_draw_count = 0 [static]
Referenced by Init_permanent_draw(), and Pixel_figure_permanent().