GrafX2: help.h File Reference
help.h File Reference
Functions related to the help browser.
Functions
void Button_Help (void)
Called to open the help window with the keyboard shortcut.
void Button_Stats (void)
Displays and runs the "Statistics" window.
void Window_help (int section, const char *sub_section)
Displays and runs the "Help / About..." window.
void Window_set_shortcut (int action_id)
Opens a window where you can change a shortcut key(s).
short Print_help (short x_pos, short y_pos, const char *line, char line_type, short link_position, short link_size)
Print a line with the 'help' (6x8) font.
const char * Keyboard_shortcut_value (word shortcut_number)
Detailed Description
Functions related to the help browser.
The help data is in helpfile.h
Function Documentation
void Button_Help (void)
Called to open the help window with the keyboard shortcut.
If the mouse is over a button, its contextual help will be displayed. Else, the default helpscreen will be shown.
References Button_under_mouse(), Key, and Window_help().
Referenced by Init_buttons().
void Button_Stats (void)
Displays and runs the "Statistics" window.
References Block, BUTTON_HELP, Close_window(), Count_used_colors(), Display_cursor(), dword, haiku_get_free_space(), Is_shortcut(), Key, KEY_ESC, Main_current_directory, Main_image_height, Main_image_width, MC_Black, Memory_free(), Menu_factor_X, Menu_factor_Y, Open_window(), Print_in_window(), Program_version, qword, Screen_height, Screen_width, STATS_DATA_COLOR, Stats_pages_memory, Stats_pages_number, STATS_TITLE_COLOR, SVN_revision, TrueType_is_supported(), Unselect_button(), Update_rect(), Window_clicked_button(), Window_display_frame_in(), Window_pos_X, Window_pos_Y, and Window_set_normal_button().
Referenced by Init_buttons().
void Window_help (int section, const char * sub_section)
Displays and runs the "Help / About..." window.
Parameters:
section Number of the help section page to display (equals the button number the mouse was hovering for the contextual help), -1 for the main help page.
sub_section Help sub-section title (the page will be scrolled so this title is at the top).
References Block, BUTTON_HELP, Close_window(), Compute_slider_cursor_length(), Current_help_section, Display_cursor(), Display_help(), Help_position, Help_section, Hide_cursor, Is_shortcut(), Key, KEY_ESC, KEY_MOUSEWHEELDOWN, KEY_MOUSEWHEELUP, T_Help_section::Length, MC_Black, Menu_factor_X, Menu_factor_Y, Mouse_Y, T_Scroller_button::Nb_elements, Open_window(), T_Scroller_button::Position, Scroll_help(), Unselect_button(), Update_rect(), Wait_end_of_click(), Window_attribute2, Window_clicked_button(), Window_display_frame_in(), Window_draw_slider(), Window_pos_X, Window_pos_Y, Window_set_normal_button(), Window_set_scroller_button(), Window_set_shortcut(), and Window_set_special_button().
Referenced by Button_Airbrush_menu(), Button_Brush_FX(), Button_Colorize_menu(), Button_Copy_page(), Button_Effects(), Button_Gradients(), Button_Grid_menu(), Button_Help(), Button_Layer_menu(), Button_Load_or_Save(), Button_Paintbrush_menu(), Button_Palette(), Button_Quick_shade_menu(), Button_Quit_local_function(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Skins(), Button_Smooth_menu(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Menu_shade(), and Menu_tag_colors().
void Window_set_shortcut (int action_id)
Opens a window where you can change a shortcut key(s).
References Block, Close_window(), ConfigKey, Display_cursor(), Error, Hide_cursor, Key, T_Key_config::Key, T_Key_config::Key2, KEY_ESC, Key_name(), KEY_NONE, MC_Black, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, NB_SHORTCUTS, Open_window(), Ordering, Print_in_window(), Print_in_window_limited(), Redefine_control(), Shortcut(), Update_rect(), Window_clicked_button(), Window_display_frame_in(), Window_pos_X, Window_pos_Y, Window_set_normal_button(), and word.
Referenced by Window_help().
short Print_help (short x_pos, short y_pos, const char * line, char line_type, short link_position, short link_size)
Print a line with the 'help' (6x8) font.
References T_Gui_skin::Bold_font, byte, Display_line_fast, Gfx, T_Gui_skin::Help_font_norm, T_Gui_skin::Help_font_t1, T_Gui_skin::Help_font_t2, T_Gui_skin::Help_font_t3, T_Gui_skin::Help_font_t4, Horizontal_line_buffer, MC_Dark, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, Pixel_width, ToWinX, ToWinY, and T_Polygon_edge::x.
Referenced by Display_help().
const char* Keyboard_shortcut_value (word shortcut_number)
References Key_name(), Shortcut(), and word.
Referenced by Display_help().