GrafX2: help.c File Reference
help.c File Reference
#include <stdio.h>
#include <string.h>
#include "const.h"
#include "struct.h"
#include "global.h"
#include "misc.h"
#include "engine.h"
#include "helpfile.h"
#include "help.h"
#include "sdlscreen.h"
#include "text.h"
#include "keyboard.h"
#include "windows.h"
#include "input.h"
#include "hotkeys.h"
#include "errors.h"
Defines
#define STATS_TITLE_COLOR MC_White
#define STATS_DATA_COLOR MC_Light
Functions
word * Shortcut (word shortcut_number)
const char * Keyboard_shortcut_value (word shortcut_number)
void Redefine_control (word *shortcut, int x_pos, int y_pos)
void Window_set_shortcut (int action_id)
void Display_help (void)
void Scroll_help (T_Scroller_button *scroller)
void Button_Help (void)
Called to open the help window with the keyboard shortcut.
void Window_help (int section, const char *sub_section)
Displays and runs the "Help / About..." window.
void Button_Stats (void)
Displays and runs the "Statistics" window.
Variables
char Program_version []
char SVN_revision []
Define Documentation
#define STATS_TITLE_COLOR MC_White
Referenced by Button_Stats().
#define STATS_DATA_COLOR MC_Light
Referenced by Button_Stats().
Function Documentation
word* Shortcut (word shortcut_number)
References Buttons_Pool, and Config_Key.
Referenced by Keyboard_shortcut_value(), and Window_set_shortcut().
const char* Keyboard_shortcut_value (word shortcut_number)
References Key_name(), Shortcut(), and word.
Referenced by Display_help().
void Redefine_control (word * shortcut, int x_pos, int y_pos)
References Display_cursor(), Get_input(), Hide_cursor, Key, KEY_ESC, MC_Black, MC_Light, and Print_in_window().
Referenced by Window_set_shortcut().
void Window_set_shortcut (int action_id)
References Block, Close_window(), ConfigKey, Display_cursor(), Error, Hide_cursor, Key, T_Key_config::Key, T_Key_config::Key2, KEY_ESC, Key_name(), KEY_NONE, MC_Black, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, NB_SHORTCUTS, Open_window(), Ordering, Print_in_window(), Print_in_window_limited(), Redefine_control(), Shortcut(), Update_rect(), Window_clicked_button(), Window_display_frame_in(), Window_pos_X, Window_pos_Y, Window_set_normal_button(), and word.
Referenced by Window_help().
void Display_help (void)
References Block, T_Gui_skin::Bold_font, byte, Current_help_section, Display_line_fast, ELLIPSIS_CHARACTER, Gfx, T_Gui_skin::Help_font_norm, T_Gui_skin::Help_font_t1, T_Gui_skin::Help_font_t2, T_Gui_skin::Help_font_t3, T_Gui_skin::Help_font_t4, Help_position, Help_section, T_Help_section::Help_table, Horizontal_line_buffer, Keyboard_shortcut_value(), T_Help_table::Line_type, MC_Black, MC_Dark, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, Pixel_width, T_Help_table::Text, Update_rect(), Window_pos_X, Window_pos_Y, and T_Polygon_edge::x.
Referenced by Scroll_help(), and Window_help().
void Scroll_help (T_Scroller_button * scroller)
References Compute_slider_cursor_height(), Display_cursor(), Display_help(), Help_position, Hide_cursor, T_Scroller_button::Position, and Window_draw_slider().
Referenced by Window_help().
void Button_Help (void)
Called to open the help window with the keyboard shortcut.
If the mouse is over a button, its contextual help will be displayed. Else, the default helpscreen will be shown.
References Button_under_mouse(), Key, and Window_help().
Referenced by Init_buttons().
void Window_help (int section, const char * sub_section)
Displays and runs the "Help / About..." window.
Parameters:
section Number of the help section page to display (equals the button number the mouse was hovering for the contextual help), -1 for the main help page.
sub_section Help sub-section title (the page will be scrolled so this title is at the top).
References Block, BUTTON_HELP, Close_window(), Compute_slider_cursor_height(), Current_help_section, Display_cursor(), Display_help(), Help_position, Help_section, Hide_cursor, Is_shortcut(), Key, KEY_ESC, KEY_MOUSEWHEELDOWN, KEY_MOUSEWHEELUP, T_Help_section::Length, MC_Black, Menu_factor_X, Menu_factor_Y, Mouse_Y, T_Scroller_button::Nb_elements, Open_window(), T_Scroller_button::Position, Scroll_help(), Unselect_button(), Update_rect(), Wait_end_of_click(), Window_attribute2, Window_clicked_button(), Window_display_frame_in(), Window_draw_slider(), Window_pos_X, Window_pos_Y, Window_set_normal_button(), Window_set_scroller_button(), Window_set_shortcut(), and Window_set_special_button().
Referenced by Button_Airbrush_menu(), Button_Brush_FX(), Button_Colorize_menu(), Button_Copy_page(), Button_Effects(), Button_Gradients(), Button_Grid_menu(), Button_Help(), Button_Load_or_Save(), Button_Magnify_menu(), Button_Paintbrush_menu(), Button_Palette(), Button_Quick_shade_menu(), Button_Quit_local_function(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Smooth_menu(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Menu_shade(), and Menu_tag_colors().
void Button_Stats (void)
Displays and runs the "Statistics" window.
References Block, BUTTON_HELP, Close_window(), Count_used_colors(), Display_cursor(), dword, Is_shortcut(), Key, KEY_ESC, Main_current_directory, Main_image_height, Main_image_width, MC_Black, Memory_free(), Menu_factor_X, Menu_factor_Y, Open_window(), Print_in_window(), Program_version, qword, Screen_height, Screen_width, STATS_DATA_COLOR, STATS_TITLE_COLOR, SVN_revision, TrueType_is_supported(), Unselect_button(), Update_rect(), Window_clicked_button(), Window_display_frame_in(), Window_pos_X, Window_pos_Y, and Window_set_normal_button().
Referenced by Init_buttons().
Variable Documentation
char Program_version[]
char SVN_revision[]
Referenced by Button_Stats().