GrafX2: init.c File Reference
init.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <errno.h>
#include <SDL_byteorder.h>
#include <SDL_image.h>
#include <SDL_syswm.h>
#include "buttons.h"
#include "const.h"
#include "errors.h"
#include "global.h"
#include "graph.h"
#include "init.h"
#include "io.h"
#include "factory.h"
#include "help.h"
#include "hotkeys.h"
#include "keyboard.h"
#include "loadsave.h"
#include "misc.h"
#include "mountlist.h"
#include "operatio.h"
#include "palette.h"
#include "sdlscreen.h"
#include "setup.h"
#include "struct.h"
#include "transform.h"
#include "windows.h"
#include "layers.h"
Defines
#define _XOPEN_SOURCE 500
#define HIDE_CURSOR 1
#define FAST_MOUSE 1
Functions
byte GUI_seek_down (SDL_Surface *gui, int *start_x, int *start_y, byte neutral_color, char *section)
byte GUI_seek_right (SDL_Surface *gui, int *start_x, int start_y, byte neutral_color, char *section)
byte Read_GUI_block (T_Gui_skin *gfx, SDL_Surface *gui, int start_x, int start_y, void *dest, int width, int height, char *section, int type)
byte Read_GUI_pattern (T_Gui_skin *gfx, SDL_Surface *gui, int start_x, int start_y, word *dest, char *section)
void Center_GUI_cursor (T_Gui_skin *gfx, byte *cursor_buffer, int cursor_number)
byte Parse_skin (SDL_Surface *gui, T_Gui_skin *gfx)
T_Gui_skin * Load_graphics (const char *skin_file)
byte Parse_font (SDL_Surface *image, byte *font)
byte * Load_font (const char *font_name)
Loads a 8x8 monochrome font, the kind used in all menus and screens.
void Do_nothing (void)
void Init_button (byte btn_number, word x_offset, word y_offset, word width, word height, byte shape, Func_action left_action, Func_action right_action, byte left_instant, byte right_instant, Func_action unselect_action, byte family)
void Init_buttons (void)
void Init_operation (byte operation_number, byte mouse_button, byte stack_index, Func_action action, byte hide_cursor, byte fast_mouse)
void Init_operations (void)
void Set_video_mode (short width, short height, byte mode, word fullscreen)
int Compare_video_modes (const void *p1, const void *p2)
void Set_all_video_modes (void)
int Load_CFG (int reload_all)
int Save_CFG (void)
void Set_config_defaults (void)
void Init_sighandler (void)
void Init_brush_container (void)
void Set_current_skin (const char *skinfile, T_Gui_skin *gfx)
void Compute_menu_offsets (void)
Based on which toolbars are visible, updates their offsets and computes Menu_height and Menu_Y.
void Init_paintbrush (int index, int width, int height, byte shape, const char *bitmap)
void Init_paintbrushes (void)
void Define_icon (void)
Set application icon(s)
Variables
char Gui_loading_error_message [512]
Define Documentation
#define _XOPEN_SOURCE 500
#define HIDE_CURSOR 1
Referenced by Init_operations().
#define FAST_MOUSE 1
Referenced by Init_operations().
Function Documentation
byte GUI_seek_down (SDL_Surface * gui, int * start_x, int * start_y, byte neutral_color, char * section)
References byte, Get_SDL_pixel_8(), and Gui_loading_error_message.
Referenced by Parse_skin().
byte GUI_seek_right (SDL_Surface * gui, int * start_x, int start_y, byte neutral_color, char * section)
References byte, Get_SDL_pixel_8(), and Gui_loading_error_message.
Referenced by Parse_skin().
byte Read_GUI_block (T_Gui_skin * gfx, SDL_Surface * gui, int start_x, int start_y, void * dest, int width, int height, char * section, int type)
References byte, T_Gui_skin::Color, T_Gui_skin::Color_trans, Get_SDL_pixel_8(), and Gui_loading_error_message.
Referenced by Parse_skin(), and Read_GUI_pattern().
byte Read_GUI_pattern (T_Gui_skin * gfx, SDL_Surface * gui, int start_x, int start_y, word * dest, char * section)
References byte, and Read_GUI_block().
Referenced by Parse_skin().
void Center_GUI_cursor (T_Gui_skin * gfx, byte * cursor_buffer, int cursor_number)
References byte, T_Gui_skin::Color_trans, T_Gui_skin::Cursor_offset_X, T_Gui_skin::Cursor_offset_Y, T_Gui_skin::Cursor_sprite, CURSOR_SPRITE_HEIGHT, and CURSOR_SPRITE_WIDTH.
Referenced by Parse_skin().
byte Parse_skin (SDL_Surface * gui, T_Gui_skin * gfx)
References T_Gui_skin::Bold_font, byte, Center_GUI_cursor(), T_Gui_skin::Color, T_Gui_skin::Color_trans, T_Gui_skin::Default_palette, T_Gui_skin::Effect_sprite, EFFECT_SPRITE_HEIGHT, EFFECT_SPRITE_WIDTH, Get_SDL_Palette(), Get_SDL_pixel_8(), Gui_loading_error_message, GUI_seek_down(), GUI_seek_right(), T_Menu_Bar::Height, T_Gui_skin::Help_font_norm, T_Gui_skin::Help_font_t1, T_Gui_skin::Help_font_t2, T_Gui_skin::Help_font_t3, T_Gui_skin::Help_font_t4, T_Gui_skin::Icon_sprite, ICON_SPRITE_HEIGHT, ICON_SPRITE_WIDTH, T_Gui_skin::Layer_sprite, LAYER_SPRITE_HEIGHT, LAYER_SPRITE_WIDTH, T_Gui_skin::Layerbar_block, T_Gui_skin::Logo_grafx2, Menu_bars, T_Gui_skin::Menu_block, T_Gui_skin::Menu_sprite, MENU_SPRITE_HEIGHT, MENU_SPRITE_WIDTH, MENUBAR_LAYERS, MENUBAR_STATUS, MENUBAR_TOOLS, NB_CURSOR_SPRITES, NB_EFFECTS_SPRITES, NB_ICON_SPRITES, NB_MENU_SPRITES, NB_PRESET_SIEVE, T_Gui_skin::Preview, Read_GUI_block(), Read_GUI_pattern(), T_Gui_skin::Sieve_pattern, T_Menu_Bar::Skin_width, and T_Gui_skin::Statusbar_block.
Referenced by Load_graphics().
T_Gui_skin* Load_graphics (const char * skin_file)
References Data_directory, Gui_loading_error_message, Load_surface(), MAX_PATH_CHARACTERS, Parse_skin(), and PATH_SEPARATOR.
Referenced by Button_Skins(), and Init_program().
byte Parse_font (SDL_Surface * image, byte * font)
References byte, Get_SDL_pixel_8(), and Gui_loading_error_message.
Referenced by Load_font().
byte* Load_font (const char * font_name)
Loads a 8x8 monochrome font, the kind used in all menus and screens.
This function allocates the memory, and returns a pointer to it when successful. If an error is encountered, it frees what needs it, prints an error message in Gui_loading_error_message, and returns NULL.
References byte, Data_directory, Gui_loading_error_message, Load_surface(), MAX_PATH_CHARACTERS, Parse_font(), and PATH_SEPARATOR.
Referenced by Button_Skins(), and Init_program().
void Do_nothing (void)
Referenced by Init_buttons().
void Init_button (byte btn_number, word x_offset, word y_offset, word width, word height, byte shape, Func_action left_action, Func_action right_action, byte left_instant, byte right_instant, Func_action unselect_action, byte family)
References Buttons_Pool.
Referenced by Init_buttons().
void Init_buttons (void)
References Button_Adjust(), BUTTON_ADJUST, Button_Airbrush(), BUTTON_AIRBRUSH, Button_Airbrush_menu(), Button_Autosave(), Button_Brush(), BUTTON_BRUSH, BUTTON_BRUSH_EFFECTS, Button_Brush_Factory(), Button_Brush_FX(), Button_Brush_monochrome(), BUTTON_CHOOSE_COL, BUTTON_CIRCLES, Button_Clear(), BUTTON_CLEAR, Button_Clear_with_backcolor(), Button_Colorpicker(), BUTTON_COLORPICKER, Button_Copy_page(), Button_Curves(), BUTTON_CURVES, Button_Curves_switch_mode(), Button_Draw(), BUTTON_DRAW, Button_Draw_switch_mode(), Button_Effects(), BUTTON_EFFECTS, Button_Empty_circle(), Button_Empty_ellipse(), Button_Empty_rectangle(), Button_Fill(), BUTTON_FILLCIRC, Button_Filled_circle(), Button_Filled_ellipse(), Button_Filled_polyform(), Button_Filled_rectangle(), BUTTON_FILLRECT, BUTTON_FLOODFILL, Button_Grad_circle(), Button_Grad_ellipse(), Button_Grad_rectangle(), Button_Gradients(), BUTTON_GRADRECT, Button_Help(), BUTTON_HELP, BUTTON_HIDE, Button_Invert_foreback(), Button_Kill(), BUTTON_KILL, Button_Lasso(), Button_Layer_add(), BUTTON_LAYER_ADD, BUTTON_LAYER_COLOR, Button_Layer_down(), BUTTON_LAYER_DOWN, Button_Layer_get_transparent(), Button_Layer_menu(), BUTTON_LAYER_MENU, Button_Layer_merge(), BUTTON_LAYER_MERGE, Button_Layer_remove(), BUTTON_LAYER_REMOVE, Button_Layer_select(), BUTTON_LAYER_SELECT, Button_Layer_set_transparent(), Button_Layer_toggle(), Button_Layer_up(), BUTTON_LAYER_UP, Button_Lines(), BUTTON_LINES, Button_Lines_switch_mode(), Button_Load(), BUTTON_LOAD, BUTTON_MAGNIFIER, Button_Magnify(), Button_Magnify_menu(), Button_Page(), BUTTON_PAGE, Button_Paintbrush_menu(), BUTTON_PAINTBRUSHES, Button_Pal_left(), BUTTON_PAL_LEFT, Button_Pal_left_fast(), Button_Pal_right(), BUTTON_PAL_RIGHT, Button_Pal_right_fast(), Button_Palette(), BUTTON_PALETTE, BUTTON_POLYBRUSH, Button_Polyfill(), BUTTON_POLYFILL, Button_Polyform(), Button_polygon(), BUTTON_POLYGONS, Button_Quit(), BUTTON_QUIT, BUTTON_RECTANGLES, Button_Redo(), Button_Reload(), Button_Replace(), BUTTON_RESOL, Button_Resolution(), Button_Restore_brush(), Button_Safety_resolution(), Button_Save(), BUTTON_SAVE, Button_Secondary_palette(), Button_Select_backcolor(), Button_Select_forecolor(), Button_Settings(), BUTTON_SETTINGS, BUTTON_SHAPE_NO_FRAME, BUTTON_SHAPE_RECTANGLE, BUTTON_SHAPE_TRIANGLE_BOTTOM_RIGHT, BUTTON_SHAPE_TRIANGLE_TOP_LEFT, Button_Skins(), BUTTON_SPHERES, Button_Stats(), Button_Text(), BUTTON_TEXT, Button_Toggle_all_toolbars(), Button_Toggle_toolbar(), Button_Transform_menu(), Button_Undo(), BUTTON_UNDO, Button_Unselect_brush(), Button_Unselect_colorpicker(), Button_Unselect_fill(), Button_Unselect_lasso(), Button_Unselect_magnifier(), Buttons_Pool, byte, Do_nothing(), FAMILY_EFFECTS, FAMILY_INSTANT, FAMILY_INTERRUPTION, FAMILY_TOOL, FAMILY_TOOLBAR, Init_button(), MENU_WIDTH, and NB_BUTTONS.
Referenced by Init_program().
void Init_operation (byte operation_number, byte mouse_button, byte stack_index, Func_action action, byte hide_cursor, byte fast_mouse)
References Operation.
Referenced by Init_operations().
void Init_operations (void)
References Airbrush_0_2(), Airbrush_12_2(), Airbrush_1_0(), Airbrush_2_0(), Brush_0_5(), Brush_12_0(), Brush_12_5(), byte, Centered_lines_0_3(), Centered_lines_0_7(), Centered_lines_12_0(), Centered_lines_12_3(), Centered_lines_12_7(), Circle_12_0(), Circle_12_5(), Colorpicker_0_1(), Colorpicker_12_0(), Colorpicker_1_1(), Colorpicker_2_1(), Colorpicker_color, Curve_34_points_1_0(), Curve_34_points_1_5(), Curve_34_points_2_0(), Curve_34_points_2_5(), Curve_3_points_0_11(), Curve_3_points_0_5(), Curve_3_points_12_11(), Curve_4_points_0_5(), Curve_4_points_1_9(), Curve_4_points_2_9(), Distort_brush_0_0(), Distort_brush_0_9(), Distort_brush_1_0(), Distort_brush_1_8(), Distort_brush_1_9(), Distort_brush_2_0(), Distort_brush_2_8(), Ellipse_12_0(), Ellipse_12_5(), Empty_circle_0_5(), Empty_ellipse_0_5(), Empty_rectangle_0_5(), FAST_MOUSE, Fill_1_0(), Fill_2_0(), Filled_circle_0_5(), Filled_contour_0_8(), Filled_ellipse_0_5(), Filled_polyform_0_8(), Filled_polyform_12_0(), Filled_polyform_12_8(), Filled_rectangle_0_5(), Freehand_mode12_0_2(), Freehand_mode1_1_0(), Freehand_mode1_1_2(), Freehand_mode1_2_0(), Freehand_mode1_2_2(), Freehand_mode2_1_0(), Freehand_mode2_1_2(), Freehand_mode2_2_0(), Freehand_mode2_2_2(), Freehand_mode3_0_1(), Freehand_mode3_1_0(), Freehand_Mode3_2_0(), Grad_circle_0_6(), Grad_circle_12_0(), Grad_circle_12_6(), Grad_circle_12_8(), Grad_circle_or_ellipse_0_8(), Grad_ellipse_0_6(), Grad_ellipse_12_0(), Grad_ellipse_12_6(), Grad_ellipse_12_8(), Grad_rectangle_0_5(), Grad_rectangle_0_7(), Grad_rectangle_0_9(), Grad_rectangle_12_0(), Grad_rectangle_12_5(), Grad_rectangle_12_7(), Grad_rectangle_12_9(), HIDE_CURSOR, Init_operation(), K_line_0_6(), K_line_12_0(), K_line_12_6(), K_line_12_7(), Line_0_5(), Line_12_0(), Line_12_5(), Magnifier_12_0(), NB_OPERATIONS, OPERATION_3_POINTS_CURVE, OPERATION_4_POINTS_CURVE, OPERATION_AIRBRUSH, OPERATION_CENTERED_LINES, OPERATION_COLORPICK, OPERATION_CONTINUOUS_DRAW, OPERATION_DISCONTINUOUS_DRAW, OPERATION_DISTORT_BRUSH, OPERATION_EMPTY_CIRCLE, OPERATION_EMPTY_ELLIPSE, OPERATION_EMPTY_RECTANGLE, OPERATION_FILL, OPERATION_FILLED_CIRCLE, OPERATION_FILLED_CONTOUR, OPERATION_FILLED_ELLIPSE, OPERATION_FILLED_POLYFORM, OPERATION_FILLED_RECTANGLE, OPERATION_GRAB_BRUSH, OPERATION_GRAD_CIRCLE, OPERATION_GRAD_ELLIPSE, OPERATION_GRAD_RECTANGLE, OPERATION_K_LINE, OPERATION_LINE, OPERATION_MAGNIFY, OPERATION_POINT_DRAW, OPERATION_POLYBRUSH, OPERATION_POLYFILL, OPERATION_POLYFORM, OPERATION_POLYGON, OPERATION_REPLACE, OPERATION_RMB_COLORPICK, OPERATION_ROTATE_BRUSH, OPERATION_SCROLL, OPERATION_STACK_SIZE, OPERATION_STRETCH_BRUSH, Polybrush_12_8(), Polyfill_0_8(), Polyfill_12_0(), Polyfill_12_8(), Polyfill_12_9(), Polyform_0_8(), Polyform_12_0(), Polyform_12_8(), Polygon_12_0(), Polygon_12_9(), Print_coordinates(), Rectangle_12_0(), Rectangle_12_5(), Replace_1_0(), Replace_2_0(), Rightclick_colorpick_0_1(), Rotate_brush_0_5(), Rotate_brush_12_0(), Rotate_brush_1_5(), Rotate_brush_2_5(), Scroll_0_5(), Scroll_12_0(), Scroll_12_5(), Stretch_brush_0_7(), Stretch_brush_12_0(), Stretch_brush_1_7(), and Stretch_brush_2_7().
Referenced by Init_program().
void Set_video_mode (short width, short height, byte mode, word fullscreen)
References byte, DEBUG, T_Video_mode::Fullscreen, T_Video_mode::Height, MAX_VIDEO_MODES, T_Video_mode::Mode, Nb_video_modes, T_Video_mode::State, Video_mode, and T_Video_mode::Width.
Referenced by Set_all_video_modes().
int Compare_video_modes (const void * p1, const void * p2)
References T_Video_mode::Height, and T_Video_mode::Width.
Referenced by Set_all_video_modes().
void Set_all_video_modes (void)
References Compare_video_modes(), Height, Nb_video_modes, Set_video_mode(), Video_mode, and Width.
Referenced by Init_program().
int Load_CFG (int reload_all)
References BETA1, T_Config_header::Beta1, BETA2, T_Config_header::Beta2, Bound_script, Buttons_Pool, byte, CHUNK_BRUSH, CHUNK_EXCLUDE_COLORS, CHUNK_GRADIENTS, CHUNK_GRID, CHUNK_KEYS, CHUNK_MASK, CHUNK_QUICK_SHADE, CHUNK_SCRIPTS, CHUNK_SHADE, CHUNK_SMOOTH, CHUNK_STENCIL, CHUNK_VIDEO_MODES, Config_directory, Config_Key, ConfigKey, ERROR_CFG_CORRUPTED, ERROR_CFG_MISSING, ERROR_CFG_OLD, ERROR_MEMORY, Exclude_color, File_length(), T_Paintbrush::Height, T_Video_mode::Height, T_Config_video_mode::Height, T_Config_shortcut_info::Key, T_Config_shortcut_info::Key2, Key_for_scancode(), Mask_table, MAX_PATH_CHARACTERS, NB_PAINTBRUSH_SPRITES, NB_SHORTCUTS, Nb_video_modes, T_Config_shortcut_info::Number, T_Config_chunk::Number, Ordering, Paintbrush, Quick_shade_loop, Quick_shade_step, Read_byte(), Read_bytes(), Read_word_le(), Shade_current, Shade_list, Shade_list_to_lookup_tables(), Shade_table_left, Shade_table_right, Shape, T_Config_header::Signature, T_Config_chunk::Size, Smooth_matrix, Snap_height, Snap_offset_X, Snap_offset_Y, Snap_width, T_Paintbrush::Sprite, T_Config_video_mode::State, Stencil, VERSION1, T_Config_header::Version1, VERSION2, T_Config_header::Version2, Video_mode, T_Paintbrush::Width, Width, T_Config_video_mode::Width, and word.
Referenced by Init_program(), and Settings_load_config().
int Save_CFG (void)
References BETA1, T_Config_header::Beta1, BETA2, T_Config_header::Beta2, Bound_script, Buttons_Pool, byte, CHUNK_BRUSH, CHUNK_EXCLUDE_COLORS, CHUNK_GRID, CHUNK_KEYS, CHUNK_MASK, CHUNK_QUICK_SHADE, CHUNK_SCRIPTS, CHUNK_SHADE, CHUNK_SMOOTH, CHUNK_STENCIL, CHUNK_VIDEO_MODES, Config_directory, Config_Key, ConfigKey, ERROR_SAVING_CFG, Exclude_color, T_Paintbrush::Height, T_Video_mode::Height, T_Config_video_mode::Height, T_Config_shortcut_info::Key, T_Config_shortcut_info::Key2, Mask_table, MAX_PATH_CHARACTERS, NB_PAINTBRUSH_SPRITES, NB_SHORTCUTS, Nb_video_modes, T_Key_config::Number, T_Config_shortcut_info::Number, T_Config_chunk::Number, Ordering, Paintbrush, Quick_shade_loop, Quick_shade_step, Shade_current, Shade_list, Shape, T_Config_header::Signature, T_Config_chunk::Size, Smooth_matrix, Snap_height, Snap_offset_X, Snap_offset_Y, Snap_width, T_Video_mode::State, T_Config_video_mode::State, Stencil, VERSION1, T_Config_header::Version1, VERSION2, T_Config_header::Version2, Video_mode, T_Paintbrush::Width, T_Video_mode::Width, T_Config_video_mode::Width, word, Write_byte(), Write_bytes(), and Write_word_le().
Referenced by Program_shutdown(), and Settings_save_config().
void Set_config_defaults (void)
References Buttons_Pool, Config_Key, ConfigKey, Exclude_color, Gradient_basic(), Gradient_bounds_range, Gradient_function, Gradient_lower_bound, Gradient_random_factor, Gradient_upper_bound, T_Key_config::Key, T_Key_config::Key2, Mask_table, T_Shade::Mode, NB_SHORTCUTS, Ordering, Quick_shade_loop, Quick_shade_step, Shade_current, Shade_list, Shade_list_to_lookup_tables(), Shade_table_left, Shade_table_right, Smooth_matrix, Snap_height, Snap_offset_X, Snap_offset_Y, Snap_width, Stencil, and T_Shade::Step.
Referenced by Init_program().
void Init_sighandler (void)
Referenced by Init_program().
void Init_brush_container (void)
References T_Brush_template::Brush, Brush_container, BRUSH_CONTAINER_COLUMNS, BRUSH_CONTAINER_PREVIEW_HEIGHT, BRUSH_CONTAINER_PREVIEW_WIDTH, BRUSH_CONTAINER_ROWS, T_Brush_template::Height, T_Brush_template::Paintbrush_shape, PAINTBRUSH_SHAPE_MAX, T_Brush_template::Transp_color, and T_Brush_template::Width.
Referenced by Init_program().
void Set_current_skin (const char * skinfile, T_Gui_skin * gfx)
References byte, T_Gui_skin::Color, T_Gui_skin::Color_trans, Config, Gfx, T_Gui_skin::Layerbar_block, MC_Black, MC_Dark, MC_Darker, MC_Light, MC_Lighter, MC_OnBlack, MC_Trans, MC_White, MC_Window, Menu_bars, T_Gui_skin::Menu_block, MENUBAR_LAYERS, MENUBAR_STATUS, MENUBAR_TOOLS, T_Menu_Bar::Skin, T_Config::Skin_file, and T_Gui_skin::Statusbar_block.
Referenced by Button_Skins(), and Init_program().
void Compute_menu_offsets (void)
Based on which toolbars are visible, updates their offsets and computes Menu_height and Menu_Y.
References T_Menu_Bar::Height, Menu_bars, Menu_factor_Y, Menu_height, Menu_Y, MENUBAR_COUNT, Screen_height, and T_Menu_Bar::Top.
Referenced by Init_program(), and Set_bar_visibility().
void Init_paintbrush (int index, int width, int height, byte shape, const char * bitmap)
References T_Paintbrush::Height, T_Paintbrush::Offset_X, T_Paintbrush::Offset_Y, Paintbrush, Paintbrush_shape, Set_paintbrush_size(), T_Paintbrush::Shape, T_Paintbrush::Sprite, Store_paintbrush(), and T_Paintbrush::Width.
Referenced by Init_paintbrushes().
void Init_paintbrushes (void)
References T_Paintbrush::Height, Init_paintbrush(), NB_PAINTBRUSH_SPRITES, T_Paintbrush::Offset_X, T_Paintbrush::Offset_Y, Paintbrush, PAINTBRUSH_SHAPE_ANTISLASH, PAINTBRUSH_SHAPE_CROSS, PAINTBRUSH_SHAPE_DIAMOND, PAINTBRUSH_SHAPE_HORIZONTAL_BAR, PAINTBRUSH_SHAPE_MISC, PAINTBRUSH_SHAPE_PLUS, PAINTBRUSH_SHAPE_RANDOM, PAINTBRUSH_SHAPE_ROUND, PAINTBRUSH_SHAPE_SIEVE_ROUND, PAINTBRUSH_SHAPE_SIEVE_SQUARE, PAINTBRUSH_SHAPE_SLASH, PAINTBRUSH_SHAPE_SQUARE, PAINTBRUSH_SHAPE_VERTICAL_BAR, and T_Paintbrush::Width.
Referenced by Init_program().
void Define_icon (void)
Set application icon(s)
References byte, Data_directory, Get_SDL_pixel_hicolor(), and MAX_PATH_CHARACTERS.
Referenced by Init_program().
Variable Documentation
char Gui_loading_error_message[512]
Referenced by Button_Skins(), GUI_seek_down(), GUI_seek_right(), Init_program(), Load_font(), Load_graphics(), Parse_font(), Parse_skin(), and Read_GUI_block().