GrafX2: input.c File Reference
input.c File Reference
#include <SDL.h>
#include "global.h"
#include "keyboard.h"
#include "sdlscreen.h"
#include "windows.h"
#include "errors.h"
#include "misc.h"
#include "input.h"
Functions
void Handle_window_resize (SDL_ResizeEvent event)
void Handle_window_exit (SDL_QuitEvent event)
int Is_shortcut (word Key, word function)
Returns true if the keycode has been set as a keyboard shortcut for the function.
int Move_cursor_with_constraints ()
dword Inhibit_shortcut (dword key)
int Handle_mouse_move (SDL_MouseMotionEvent event)
int Handle_mouse_click (SDL_MouseButtonEvent event)
int Handle_mouse_release (SDL_MouseButtonEvent event)
int Handle_key_press (SDL_KeyboardEvent event)
int Release_control (int key_code, int modifier)
int Handle_key_release (SDL_KeyboardEvent event)
int Handle_joystick_press (SDL_JoyButtonEvent event)
int Handle_joystick_release (SDL_JoyButtonEvent event)
void Handle_joystick_movement (SDL_JoyAxisEvent event)
int Cursor_displace (short delta_x, short delta_y)
int Get_input (void)
This is the keyboard/mouse/joystick input polling function.
void Adjust_mouse_sensitivity (word fullscreen)
Adjust mouse sensitivity (and actual mouse input mode).
void Set_mouse_position (void)
Variables
int Input_sticky_control = 0
This holds the ID of the GUI control that the mouse is manipulating.
int Snap_axis = 0
Allows locking movement to X or Y axis: 0=normal, 1=lock on next move, 2=locked horizontally, 3=locked vertically.
int Snap_axis_origin_X
For the :Snap_axis mode, sets the origin's point (in image coordinates).
int Snap_axis_origin_Y
For the :Snap_axis mode, sets the origin's point (in image coordinates).
byte Directional_up
byte Directional_up_right
byte Directional_right
byte Directional_down_right
byte Directional_down
byte Directional_down_left
byte Directional_left
byte Directional_up_left
byte Directional_click
long Directional_delay
long Directional_last_move
long Directional_step
int Mouse_moved
Boolean, Set to true if any cursor movement occurs.
word Input_new_mouse_X
word Input_new_mouse_Y
byte Input_new_mouse_K
byte Mouse_mode = 0
Mouse mode = 0:normal, 1:emulated with custom sensitivity.
short Mouse_virtual_x_position
short Mouse_virtual_y_position
short Mouse_virtual_width
short Mouse_virtual_height
short Joybutton_shift = -1
short Joybutton_control = -1
short Joybutton_alt = -1
short Joybutton_left_click = 0
short Joybutton_right_click = 0
Function Documentation
void Handle_window_resize (SDL_ResizeEvent event)
References Resize_height, and Resize_width.
Referenced by Get_input().
void Handle_window_exit (SDL_QuitEvent event)
References Quit_is_required.
Referenced by Get_input().
int Is_shortcut (word Key, word function)
Returns true if the keycode has been set as a keyboard shortcut for the function.
References Buttons_Pool, Config_Key, Left_shortcut, and Right_shortcut.
Referenced by Button_Airbrush_menu(), Button_Brush_FX(), Button_Colorize_menu(), Button_Copy_page(), Button_Effects(), Button_Gradients(), Button_Grid_menu(), Button_Load_or_Save(), Button_Magnify_menu(), Button_Paintbrush_menu(), Button_Palette(), Button_Quick_shade_menu(), Button_Quit_local_function(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Smooth_menu(), Button_Stats(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Handle_key_press(), Inhibit_shortcut(), Main_handler(), Menu_shade(), Menu_tag_colors(), and Window_help().
int Move_cursor_with_constraints ()
< Boolean, Set to true if mouse movement was clipped.
References Config, Current_operation, Fast_mouse, Hide_cursor, Input_new_mouse_K, Input_new_mouse_X, Input_new_mouse_Y, Input_sticky_control, Main_magnifier_mode, Main_separator_position, Main_X_zoom, Menu_Y, Mouse_K, Mouse_K_unique, T_Config::Mouse_merge_movement, Mouse_moved, Mouse_X, Mouse_Y, Operation, Operation_in_magnifier, Operation_stack_size, Screen_height, Screen_width, and Set_mouse_position().
Referenced by Cursor_displace(), Handle_joystick_press(), Handle_joystick_release(), Handle_key_press(), Handle_mouse_click(), Handle_mouse_move(), Handle_mouse_release(), and Release_control().
dword Inhibit_shortcut (dword key)
References Allow_color_change_during_operation, Is_shortcut(), Operation_stack_size, SPECIAL_BIGGER_PAINTBRUSH, SPECIAL_NEXT_BACKCOLOR, SPECIAL_NEXT_FORECOLOR, SPECIAL_NEXT_USER_BACKCOLOR, SPECIAL_NEXT_USER_FORECOLOR, SPECIAL_PREVIOUS_BACKCOLOR, SPECIAL_PREVIOUS_FORECOLOR, SPECIAL_PREVIOUS_USER_BACKCOLOR, SPECIAL_PREVIOUS_USER_FORECOLOR, and SPECIAL_SMALLER_PAINTBRUSH.
Referenced by Handle_key_press(), and Handle_mouse_click().
int Handle_mouse_move (SDL_MouseMotionEvent event)
References Config, Input_new_mouse_X, Input_new_mouse_Y, Mouse_mode, T_Config::Mouse_sensitivity_index_x, T_Config::Mouse_sensitivity_index_y, Mouse_virtual_height, Mouse_virtual_width, Mouse_virtual_x_position, Mouse_virtual_y_position, Move_cursor_with_constraints(), Pixel_height, and Pixel_width.
Referenced by Get_input().
int Handle_mouse_click (SDL_MouseButtonEvent event)
References Inhibit_shortcut(), Input_new_mouse_K, Key, Key_modifiers(), KEY_MOUSEMIDDLE, KEY_MOUSEWHEELDOWN, KEY_MOUSEWHEELUP, and Move_cursor_with_constraints().
Referenced by Get_input().
int Handle_mouse_release (SDL_MouseButtonEvent event)
References Input_new_mouse_K, and Move_cursor_with_constraints().
Referenced by Get_input().
int Handle_key_press (SDL_KeyboardEvent event)
References Directional_click, Directional_down, Directional_left, Directional_right, Directional_up, Inhibit_shortcut(), Input_new_mouse_K, Is_shortcut(), Key, Key_ANSI, Keyboard_click_allowed, Keysym_to_ANSI(), Keysym_to_keycode(), Move_cursor_with_constraints(), SPECIAL_CLICK_LEFT, SPECIAL_CLICK_RIGHT, SPECIAL_MOUSE_DOWN, SPECIAL_MOUSE_LEFT, SPECIAL_MOUSE_RIGHT, and SPECIAL_MOUSE_UP.
Referenced by Get_input().
int Release_control (int key_code, int modifier)
References Config_Key, Directional_click, Directional_down, Directional_left, Directional_right, Directional_up, Input_new_mouse_K, MOD_SHIFT, Move_cursor_with_constraints(), Snap_axis, SPECIAL_CLICK_LEFT, SPECIAL_CLICK_RIGHT, SPECIAL_MOUSE_DOWN, SPECIAL_MOUSE_LEFT, SPECIAL_MOUSE_RIGHT, and SPECIAL_MOUSE_UP.
Referenced by Handle_joystick_release(), and Handle_key_release().
int Handle_key_release (SDL_KeyboardEvent event)
References Keysym_to_keycode(), MOD_ALT, MOD_CTRL, MOD_META, MOD_SHIFT, and Release_control().
Referenced by Get_input().
int Handle_joystick_press (SDL_JoyButtonEvent event)
References Directional_down, Directional_down_left, Directional_down_right, Directional_left, Directional_right, Directional_up, Directional_up_left, Directional_up_right, GP2X_BUTTON_DOWN, GP2X_BUTTON_DOWNLEFT, GP2X_BUTTON_DOWNRIGHT, GP2X_BUTTON_LEFT, GP2X_BUTTON_RIGHT, GP2X_BUTTON_UP, GP2X_BUTTON_UPLEFT, GP2X_BUTTON_UPRIGHT, Input_new_mouse_K, Joybutton_alt, Joybutton_control, Joybutton_left_click, Joybutton_right_click, Joybutton_shift, Key, KEY_JOYBUTTON, Key_modifiers(), and Move_cursor_with_constraints().
Referenced by Get_input().
int Handle_joystick_release (SDL_JoyButtonEvent event)
References Directional_down, Directional_down_left, Directional_down_right, Directional_left, Directional_right, Directional_up, Directional_up_left, Directional_up_right, GP2X_BUTTON_DOWN, GP2X_BUTTON_DOWNLEFT, GP2X_BUTTON_DOWNRIGHT, GP2X_BUTTON_LEFT, GP2X_BUTTON_RIGHT, GP2X_BUTTON_UP, GP2X_BUTTON_UPLEFT, GP2X_BUTTON_UPRIGHT, Input_new_mouse_K, Joybutton_alt, Joybutton_control, Joybutton_left_click, Joybutton_right_click, Joybutton_shift, MOD_ALT, MOD_CTRL, MOD_SHIFT, Move_cursor_with_constraints(), and Release_control().
Referenced by Get_input().
void Handle_joystick_movement (SDL_JoyAxisEvent event)
References Directional_down, Directional_left, Directional_right, and Directional_up.
Referenced by Get_input().
int Cursor_displace (short delta_x, short delta_y)
References Input_new_mouse_X, Input_new_mouse_Y, Main_magnifier_factor, Main_magnifier_mode, Main_separator_position, Max(), Min(), Move_cursor_with_constraints(), Screen_height, and Screen_width.
Referenced by Get_input().
int Get_input (void)
This is the keyboard/mouse/joystick input polling function.
Returns 1 if a significant changed occurred, such as a mouse button pressed or depressed, or a new keypress was in the keyboard buffer. The latest input variables are held in Key, Key_ANSI, Mouse_X, Mouse_Y, Mouse_K. Note that Key and Key_ANSI are not persistent, they will be reset to 0 on subsequent calls to Get_input().
References Compute_paintbrush_coordinates(), Cursor_displace(), Directional_delay, Directional_down, Directional_down_left, Directional_down_right, Directional_last_move, Directional_left, Directional_right, Directional_step, Directional_up, Directional_up_left, Directional_up_right, Display_cursor(), Flush_update(), Handle_joystick_movement(), Handle_joystick_press(), Handle_joystick_release(), Handle_key_press(), Handle_key_release(), Handle_mouse_click(), Handle_mouse_move(), Handle_mouse_release(), Handle_window_exit(), Handle_window_resize(), Input_new_mouse_X, Input_new_mouse_Y, Key, Key_ANSI, Mouse_moved, Mouse_X, and Mouse_Y.
Referenced by Button_Message_initial(), Get_color_behind_window(), Main_handler(), Move_separator(), Move_window(), Readline_ex(), Redefine_control(), Slider_timer(), Wait_click_in_palette(), Wait_click_in_shade_table(), Wait_end_of_click(), Window_clicked_button(), Window_dropdown_on_click(), and Window_normal_button_onclick().
void Adjust_mouse_sensitivity (word fullscreen)
Adjust mouse sensitivity (and actual mouse input mode).
References Mouse_mode, Mouse_virtual_height, Mouse_virtual_width, Mouse_virtual_x_position, Mouse_virtual_y_position, Mouse_X, Mouse_Y, Pixel_height, Pixel_width, Screen_height, and Screen_width.
Referenced by Init_mode_video().
void Set_mouse_position (void)
References Mouse_mode, Mouse_virtual_x_position, Mouse_virtual_y_position, Mouse_X, Mouse_Y, Pixel_height, and Pixel_width.
Referenced by Init_mode_video(), and Move_cursor_with_constraints().
Variable Documentation
int Input_sticky_control = 0
This holds the ID of the GUI control that the mouse is manipulating.
The input system will reset it to zero when mouse button is released, but it's the engine that will record and retrieve a real control ID.
Referenced by Button_Effects(), Move_cursor_with_constraints(), Window_clicked_button(), and Window_get_clicked_button().
int Snap_axis = 0
Allows locking movement to X or Y axis: 0=normal, 1=lock on next move, 2=locked horizontally, 3=locked vertically.
Referenced by Compute_paintbrush_coordinates(), and Release_control().
int Snap_axis_origin_X
For the :Snap_axis mode, sets the origin's point (in image coordinates).
Referenced by Compute_paintbrush_coordinates().
int Snap_axis_origin_Y
For the :Snap_axis mode, sets the origin's point (in image coordinates).
Referenced by Compute_paintbrush_coordinates().
byte Directional_up
Referenced by Get_input(), Handle_joystick_movement(), Handle_joystick_press(), Handle_joystick_release(), Handle_key_press(), and Release_control().
byte Directional_up_right
Referenced by Get_input(), Handle_joystick_press(), and Handle_joystick_release().
byte Directional_right
Referenced by Get_input(), Handle_joystick_movement(), Handle_joystick_press(), Handle_joystick_release(), Handle_key_press(), and Release_control().
byte Directional_down_right
Referenced by Get_input(), Handle_joystick_press(), and Handle_joystick_release().
byte Directional_down
Referenced by Get_input(), Handle_joystick_movement(), Handle_joystick_press(), Handle_joystick_release(), Handle_key_press(), and Release_control().
byte Directional_down_left
Referenced by Get_input(), Handle_joystick_press(), and Handle_joystick_release().
byte Directional_left
Referenced by Get_input(), Handle_joystick_movement(), Handle_joystick_press(), Handle_joystick_release(), Handle_key_press(), and Release_control().
byte Directional_up_left
Referenced by Get_input(), Handle_joystick_press(), and Handle_joystick_release().
byte Directional_click
Referenced by Handle_key_press(), and Release_control().
long Directional_delay
Referenced by Get_input().
long Directional_last_move
Referenced by Get_input().
long Directional_step
Referenced by Get_input().
int Mouse_moved
Boolean, Set to true if any cursor movement occurs.
Referenced by Get_input(), and Move_cursor_with_constraints().
word Input_new_mouse_X
Referenced by Cursor_displace(), Get_input(), Handle_mouse_move(), and Move_cursor_with_constraints().
word Input_new_mouse_Y
Referenced by Cursor_displace(), Get_input(), Handle_mouse_move(), and Move_cursor_with_constraints().
byte Input_new_mouse_K
Referenced by Handle_joystick_press(), Handle_joystick_release(), Handle_key_press(), Handle_mouse_click(), Handle_mouse_release(), Move_cursor_with_constraints(), and Release_control().
byte Mouse_mode = 0
Mouse mode = 0:normal, 1:emulated with custom sensitivity.
Referenced by Adjust_mouse_sensitivity(), Handle_mouse_move(), and Set_mouse_position().
short Mouse_virtual_x_position
Referenced by Adjust_mouse_sensitivity(), Handle_mouse_move(), and Set_mouse_position().
short Mouse_virtual_y_position
Referenced by Adjust_mouse_sensitivity(), Handle_mouse_move(), and Set_mouse_position().
short Mouse_virtual_width
Referenced by Adjust_mouse_sensitivity(), and Handle_mouse_move().
short Mouse_virtual_height
Referenced by Adjust_mouse_sensitivity(), and Handle_mouse_move().
short Joybutton_shift = -1
Referenced by Handle_joystick_press(), and Handle_joystick_release().
short Joybutton_control = -1
Referenced by Handle_joystick_press(), and Handle_joystick_release().
short Joybutton_alt = -1
Referenced by Handle_joystick_press(), and Handle_joystick_release().
short Joybutton_left_click = 0
Referenced by Handle_joystick_press(), and Handle_joystick_release().
short Joybutton_right_click = 0
Referenced by Handle_joystick_press(), and Handle_joystick_release().