GrafX2: input.h File Reference
input.h File Reference
Functions for mouse, keyboard and joystick input.
Functions
int Get_input (int sleep_time)
This is the keyboard/mouse/joystick input polling function.
int Is_shortcut (word key, word function)
Returns true if the keycode has been set as a keyboard shortcut for the function.
int Has_shortcut (word function)
Returns true if the function has any shortcut key.
void Adjust_mouse_sensitivity (word fullscreen)
Adjust mouse sensitivity (and actual mouse input mode)
void Set_mouse_position (void)
Variables
int Input_sticky_control
This holds the ID of the GUI control that the mouse is manipulating.
int Snap_axis
Allows locking movement to X or Y axis: 0=normal, 1=lock on next move, 2=locked horizontally, 3=locked vertically.
int Snap_axis_origin_X
For the :Snap_axis mode, sets the origin's point (in image coordinates)
int Snap_axis_origin_Y
For the :Snap_axis mode, sets the origin's point (in image coordinates)
char * Drop_file_name
This malloced string is set when a drag-and-drop event brings a file to Grafx2's window.
Detailed Description
Functions for mouse, keyboard and joystick input.
Joystick input is used to emulate mouse on platforms that don't have a pointing device, ie: the GP2X.
Function Documentation
int Get_input (int sleep_time)
This is the keyboard/mouse/joystick input polling function.
Returns 1 if a significant changed occurred, such as a mouse button pressed or depressed, or a new keypress was in the keyboard buffer. The latest input variables are held in Key, Key_ANSI, Mouse_X, Mouse_Y, Mouse_K. Note that Key and Key_ANSI are not persistent, they will be reset to 0 on subsequent calls to Get_input().
References Color_cycling(), Compute_paintbrush_coordinates(), Cursor_displace(), Directional_acceleration(), Display_cursor(), Flush_update(), Handle_joystick_movement(), Handle_joystick_press(), Handle_joystick_release(), Handle_key_press(), Handle_key_release(), Handle_mouse_click(), Handle_mouse_move(), Handle_mouse_release(), Handle_window_exit(), Handle_window_resize(), Key, Key_ANSI, Mouse_X, and Mouse_Y.
Referenced by Button_Message_initial(), Button_Select_backcolor(), Button_Select_forecolor(), Curve_3_points_0_5(), Delay_with_active_mouse(), Dropdown_activate(), Get_color_behind_window(), Main_handler(), Move_separator(), Move_window(), Readline_ex(), Redefine_control(), Wait_click_in_palette(), Wait_click_in_shade_table(), Wait_end_of_click(), Window_clicked_button(), and Window_normal_button_onclick().
int Is_shortcut (word key, word function)
Returns true if the keycode has been set as a keyboard shortcut for the function.
References Buttons_Pool, Config_Key, Left_shortcut, and Right_shortcut.
Referenced by Button_Airbrush_menu(), Button_Brush_FX(), Button_Colorize_menu(), Button_Copy_page(), Button_Effects(), Button_Gradients(), Button_Grid_menu(), Button_Layer_menu(), Button_Load_or_Save(), Button_Paintbrush_menu(), Button_Palette(), Button_Quick_shade_menu(), Button_Quit_local_function(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Skins(), Button_Smooth_menu(), Button_Stats(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Handle_key_press(), Main_handler(), Menu_shade(), Menu_tag_colors(), and Window_help().
int Has_shortcut (word function)
Returns true if the function has any shortcut key.
References Buttons_Pool, Config_Key, KEY_NONE, Left_shortcut, and Right_shortcut.
void Adjust_mouse_sensitivity (word fullscreen)
Adjust mouse sensitivity (and actual mouse input mode)
References Mouse_X, Mouse_Y, Pixel_height, Pixel_width, Screen_height, and Screen_width.
Referenced by Init_mode_video().
void Set_mouse_position (void)
References Mouse_X, Mouse_Y, Pixel_height, and Pixel_width.
Referenced by Init_mode_video(), and Move_cursor_with_constraints().
Variable Documentation
int Input_sticky_control
This holds the ID of the GUI control that the mouse is manipulating.
The input system will reset it to zero when mouse button is released, but it's the engine that will record and retrieve a real control ID.
Referenced by Button_Effects(), Button_Gradients(), Button_Palette(), Readline_ex(), Window_clicked_button(), and Window_get_clicked_button().
int Snap_axis
Allows locking movement to X or Y axis: 0=normal, 1=lock on next move, 2=locked horizontally, 3=locked vertically.
Referenced by Compute_paintbrush_coordinates().
int Snap_axis_origin_X
For the :Snap_axis mode, sets the origin's point (in image coordinates)
Referenced by Compute_paintbrush_coordinates().
int Snap_axis_origin_Y
For the :Snap_axis mode, sets the origin's point (in image coordinates)
Referenced by Compute_paintbrush_coordinates().
char* Drop_file_name
This malloced string is set when a drag-and-drop event brings a file to Grafx2's window.
Referenced by Main_handler().