GrafX2: io.h File Reference
io.h File Reference
Low-level endian-neutral file operations, and also some filesystem operations.
Defines
#define PATH_SEPARATOR "/"
Functions
int Read_byte (FILE *file, byte *dest)
Reads a single byte from an open file. Returns true if OK, false if a file i/o error occurred.
int Write_byte (FILE *file, byte b)
Writes a single byte to an open file. Returns true if OK, false if a file i/o error occurred.
int Read_bytes (FILE *file, void *dest, size_t size)
Reads several bytes from an open file. Returns true if OK, false if a file i/o error occurred.
int Write_bytes (FILE *file, void *dest, size_t size)
Writes several bytes to an open file. Returns true if OK, false if a file i/o error occurred.
int Read_word_le (FILE *file, word *dest)
Reads a 16-bit Low-Endian word from an open file. Returns true if OK, false if a file i/o error occurred.
int Write_word_le (FILE *file, word w)
Writes a 16-bit Low-Endian word to an open file. Returns true if OK, false if a file i/o error occurred.
int Read_dword_le (FILE *file, dword *dest)
Reads a 32-bit Low-Endian dword from an open file. Returns true if OK, false if a file i/o error occurred.
int Write_dword_le (FILE *file, dword dw)
Writes a 32-bit Low-Endian dword to an open file. Returns true if OK, false if a file i/o error occurred.
int Read_word_be (FILE *file, word *dest)
Reads a 16-bit Big-Endian word from an open file. Returns true if OK, false if a file i/o error occurred.
int Write_word_be (FILE *file, word w)
Writes a 16-bit Big-Endian word to an open file. Returns true if OK, false if a file i/o error occurred.
int Read_dword_be (FILE *file, dword *dest)
Reads a 32-bit Big-Endian dword from an open file. Returns true if OK, false if a file i/o error occurred.
int Write_dword_be (FILE *file, dword dw)
Writes a 32-bit Big-Endian dword to an open file. Returns true if OK, false if a file i/o error occurred.
void Extract_filename (char *dest, const char *source)
Extracts the filename part from a full file name.
void Extract_path (char *dest, const char *source)
Extracts the directory from a full file name.
char * Find_last_slash (const char *str)
Finds the rightmost path separator in a full filename. Used to separate directory from file.
int File_length (const char *fname)
Size of a file, in bytes. Returns 0 in case of error.
int File_length_file (FILE *file)
Size of a file, in bytes. Takes an open file as argument, returns 0 in case of error.
int File_exists (char *fname)
Returns true if a file passed as a parameter exists in the current directory.
int Directory_exists (char *directory)
Returns true if a directory passed as a parameter exists in the current directory.
void For_each_file (const char *directory_name, void Callback(const char *))
Scans a directory, calls Callback for each file in it,.
void For_each_directory_entry (const char *directory_name, void Callback(const char *, byte is_file, byte is_directory, byte is_hidden))
Scans a directory, calls Callback for each file or directory in it,.
void Get_full_filename (char *output_name, char *file_name, char *directory_name)
Creates a fully qualified name from a directory and filename.
byte Create_lock_file (const char *file_directory)
Creates a lock file, to check if an other instance of Grafx2 is running.
void Release_lock_file (const char *file_directory)
Release a lock file created by ::Create_Lock_file.
Detailed Description
Low-level endian-neutral file operations, and also some filesystem operations.
Many of these may seem trivial, but the wrappers eliminate the need for a forest of preprocessor defines in each file. You MUST use the functions in this file instead of:
fread() and fwrite()
stat()
fstat()
opendir()
readdir()
Also, don't assume "/" or "\\", use PATH_SEPARATOR If you don't, you break another platform.
Define Documentation
#define PATH_SEPARATOR "/"
Referenced by Extract_path(), Find_last_slash(), For_each_directory_entry(), For_each_file(), Get_full_filename(), Load_font(), Load_graphics(), Print_current_directory(), and Set_config_directory().
Function Documentation
int Read_byte (FILE * file, byte * dest)
Reads a single byte from an open file. Returns true if OK, false if a file i/o error occurred.
Referenced by GIF_get_next_code(), Load_BMP(), Load_C64(), Load_CEL(), Load_CFG(), Load_GIF(), Load_KCF(), Load_LBM(), Load_PCX(), Load_PKM(), Load_SCx(), Test_CEL(), Test_KCF(), Test_PCX(), Test_PKM(), and Test_SCx().
int Write_byte (FILE * file, byte b)
Writes a single byte to an open file. Returns true if OK, false if a file i/o error occurred.
Referenced by Emergency_backup(), Save_C64_hires(), Save_C64_multi(), Save_CEL(), Save_CFG(), Save_GIF(), Save_KCF(), Save_LBM(), Save_PKM(), and Save_SCx().
int Read_bytes (FILE * file, void * dest, size_t size)
Reads several bytes from an open file. Returns true if OK, false if a file i/o error occurred.
Referenced by LBM_Wait_for(), Load_BMP(), Load_C64(), Load_CEL(), Load_CFG(), Load_GIF(), Load_IMG(), Load_KCF(), Load_LBM(), Load_NEO(), Load_PAL(), Load_PC1(), Load_PCX(), Load_PI1(), Load_PKM(), Load_PNG(), Load_SCx(), Test_BMP(), Test_CEL(), Test_GIF(), Test_IMG(), Test_KCF(), Test_LBM(), Test_PCX(), Test_PKM(), Test_PNG(), and Test_SCx().
int Write_bytes (FILE * file, void * dest, size_t size)
Writes several bytes to an open file. Returns true if OK, false if a file i/o error occurred.
Referenced by Emergency_backup(), End_write(), Save_BMP(), Save_C64_hires(), Save_C64_multi(), Save_CEL(), Save_CFG(), Save_GIF(), Save_IMG(), Save_KCF(), Save_LBM(), Save_NEO(), Save_PC1(), Save_PCX(), Save_PI1(), Save_PKM(), Save_SCR(), Save_SCx(), and Write_one_byte().
int Read_word_le (FILE * file, word * dest)
Reads a 16-bit Low-Endian word from an open file. Returns true if OK, false if a file i/o error occurred.
References word.
Referenced by Load_BMP(), Load_CEL(), Load_CFG(), Load_GIF(), Load_IMG(), Load_KCF(), Load_PCX(), Load_PKM(), Load_SCx(), Test_BMP(), Test_CEL(), Test_IMG(), Test_KCF(), Test_NEO(), Test_PC1(), Test_PCX(), Test_PI1(), Test_PKM(), and Test_SCx().
int Write_word_le (FILE * file, word w)
Writes a 16-bit Low-Endian word to an open file. Returns true if OK, false if a file i/o error occurred.
References word.
Referenced by Emergency_backup(), Save_BMP(), Save_CEL(), Save_CFG(), Save_GIF(), Save_IMG(), Save_KCF(), Save_PCX(), Save_PKM(), and Save_SCx().
int Read_dword_le (FILE * file, dword * dest)
Reads a 32-bit Low-Endian dword from an open file. Returns true if OK, false if a file i/o error occurred.
References dword.
Referenced by Load_BMP(), and Test_BMP().
int Write_dword_le (FILE * file, dword dw)
Writes a 32-bit Low-Endian dword to an open file. Returns true if OK, false if a file i/o error occurred.
References dword.
Referenced by Save_BMP().
int Read_word_be (FILE * file, word * dest)
Reads a 16-bit Big-Endian word from an open file. Returns true if OK, false if a file i/o error occurred.
References word.
Referenced by Load_GIF(), Load_LBM(), and Load_PKM().
int Write_word_be (FILE * file, word w)
Writes a 16-bit Big-Endian word to an open file. Returns true if OK, false if a file i/o error occurred.
References word.
Referenced by Save_GIF(), and Save_LBM().
int Read_dword_be (FILE * file, dword * dest)
Reads a 32-bit Big-Endian dword from an open file. Returns true if OK, false if a file i/o error occurred.
References dword.
Referenced by LBM_Skip_section(), Load_LBM(), and Test_LBM().
int Write_dword_be (FILE * file, dword dw)
Writes a 32-bit Big-Endian dword to an open file. Returns true if OK, false if a file i/o error occurred.
References dword.
Referenced by Save_LBM().
void Extract_filename (char * dest, const char * source)
Extracts the filename part from a full file name.
References Find_last_slash().
Referenced by Add_backup_file(), Analyze_command_line(), and Button_Load_or_Save().
void Extract_path (char * dest, const char * source)
Extracts the directory from a full file name.
References Find_last_slash(), PATH_SEPARATOR, and Realpath().
Referenced by Analyze_command_line(), and Set_program_directory().
char* Find_last_slash (const char * str)
Finds the rightmost path separator in a full filename. Used to separate directory from file.
References PATH_SEPARATOR.
Referenced by Add_font(), Add_font_or_skin(), Button_Load_or_Save(), Extract_filename(), Extract_path(), and Main_handler().
int File_length (const char * fname)
Size of a file, in bytes. Returns 0 in case of error.
Referenced by Load_CFG(), Load_SDL_Image(), Save_LBM(), and Test_CEL().
int File_length_file (FILE * file)
Size of a file, in bytes. Takes an open file as argument, returns 0 in case of error.
Referenced by Load_BMP(), Load_C64(), Load_CEL(), Load_GIF(), Load_IMG(), Load_KCF(), Load_LBM(), Load_NEO(), Load_PAL(), Load_PC1(), Load_PCX(), Load_PI1(), Load_PKM(), Load_PNG(), Load_SCx(), Test_C64(), Test_KCF(), Test_NEO(), Test_PAL(), Test_PC1(), and Test_PI1().
int File_exists (char * fname)
Returns true if a file passed as a parameter exists in the current directory.
Referenced by Analyze_command_line(), Backup_existing_file(), Button_Autosave(), Button_Load_or_Save(), Button_Quit_local_function(), Save_INI(), Save_picture(), and Set_config_directory().
int Directory_exists (char * directory)
Returns true if a directory passed as a parameter exists in the current directory.
References PARENT_DIR.
Referenced by Button_Load_or_Save(), and Set_config_directory().
void For_each_file (const char * directory_name, void Callbackconst char *)
Scans a directory, calls Callback for each file in it,.
References MAX_PATH_CHARACTERS, and PATH_SEPARATOR.
Referenced by Button_Skins(), Check_recovery(), Delete_safety_backups(), and Init_text().
void For_each_directory_entry (const char * directory_name, void Callbackconst char *, byte is_file, byte is_directory, byte is_hidden)
Scans a directory, calls Callback for each file or directory in it,.
References isHidden, MAX_PATH_CHARACTERS, and PATH_SEPARATOR.
void Get_full_filename (char * output_name, char * file_name, char * directory_name)
Creates a fully qualified name from a directory and filename.
The point is simply to insert a PATH_SEPARATOR when needed.
References PATH_SEPARATOR.
Referenced by Backup_existing_file(), Button_Autosave(), Button_Quit_local_function(), Load_BMP(), Load_C64(), Load_CEL(), Load_GIF(), Load_IMG(), Load_KCF(), Load_LBM(), Load_NEO(), Load_PAL(), Load_PC1(), Load_PCX(), Load_PI1(), Load_PKM(), Load_PNG(), Load_SCx(), Load_SDL_Image(), Save_BMP(), Save_C64(), Save_CEL(), Save_GIF(), Save_IMG(), Save_KCF(), Save_LBM(), Save_NEO(), Save_PAL(), Save_PC1(), Save_PCX(), Save_PI1(), Save_PKM(), Save_PNG(), Save_SCR(), Save_SCx(), Save_XPM(), Test_BMP(), Test_C64(), Test_CEL(), Test_GIF(), Test_IMG(), Test_KCF(), Test_LBM(), Test_NEO(), Test_PAL(), Test_PC1(), Test_PCX(), Test_PI1(), Test_PKM(), Test_PNG(), and Test_SCx().
byte Create_lock_file (const char * file_directory)
Creates a lock file, to check if an other instance of Grafx2 is running.
Returns:
0 on success (first instance), -1 on failure (others are running)
References MAX_PATH_CHARACTERS.
Referenced by Check_recovery().
void Release_lock_file (const char * file_directory)
Release a lock file created by ::Create_Lock_file.
References MAX_PATH_CHARACTERS.
Referenced by Delete_safety_backups().