GrafX2: keyboard.h File Reference
keyboard.h File Reference
Functions to convert bewteen the SDL key formats and the keycode we use in grafx2.
Functions
word Keysym_to_ANSI (SDL_keysym keysym)
Convert an SDL keysym to an ANSI/ASCII character.
word Keysym_to_keycode (SDL_keysym keysym)
Convert an SDL keysym to an internal keycode number.
word Key_for_scancode (word scancode)
Helper function to convert between SDL system and the old coding for PC keycodes.
const char * Key_name (word key)
Returns key name in a string.
word Key_modifiers (SDLMod mod)
Gets the modifiers in our format from the SDL_Mod information.
Detailed Description
Functions to convert bewteen the SDL key formats and the keycode we use in grafx2.
The keycode we're using is generalized to handle mouse and joystick shortcuts as well. The format can be broken down as:
0x0000 + a number between 0 and SDLK_LAST (about 324) : the SDL "sym" key number.
0x0000 + SDLK_LAST+1: Mouse middle button.
0x0000 + SDLK_LAST+2: Mouse wheel up.
0x0000 + SDLK_LAST+3: Mouse wheel down.
0x0000 + SDLK_LAST+4+B : Joystick button number "B", starting at B=0.
0x0800 + a number between 0 and 0x7FF: The scancode key number, for keys which have no "sym", such as keys from multimedia keyboards, and "fn" and "Thinkpad" key for a laptop. Add 0x1000 for the Shift modifier MOD_SHIFT Add 0x2000 for the Control modifier ::MOD_CONTROL Add 0x4000 for the Alt modifier MOD_ALT Add 0x8000 for the "Meta" modifier MOD_META (On MacOS X it's the CMD key)
Function Documentation
word Keysym_to_ANSI (SDL_keysym keysym)
Convert an SDL keysym to an ANSI/ASCII character.
This is used to type text and numeric values in input boxes.
Parameters:
keysym SDL symbol to convert
References KEY_ESC.
Referenced by Handle_key_press().
word Keysym_to_keycode (SDL_keysym keysym)
Convert an SDL keysym to an internal keycode number.
This is needed because SDL tends to split the information across the unicode sym, the regular sym, and the raw keycode. We also need to differenciate 1 (keypad) and 1 (regular keyboard), and some other things. See the notice at the beginning of keyboard.h for the format of a keycode.
Parameters:
keysym SDL symbol to convert
References Key_modifiers(), and word.
Referenced by Handle_key_press(), and Handle_key_release().
word Key_for_scancode (word scancode)
Helper function to convert between SDL system and the old coding for PC keycodes.
This is only used to convert configuration files from the DOS version of Grafx2, where keyboard codes are in in the IBM PC AT form.
Parameters:
scancode Scancode to convert
References Scancode_to_sym.
Referenced by Load_CFG().
const char* Key_name (word key)
Returns key name in a string.
Used to display them in the helpscreens and in the keymapper window.
Parameters:
Key keycode of the key to translate, including modifiers
References KEY_JOYBUTTON, KEY_MOUSEMIDDLE, KEY_MOUSEWHEELDOWN, KEY_MOUSEWHEELUP, Key_name(), MOD_ALT, MOD_CTRL, MOD_META, MOD_SHIFT, and word.
Referenced by Key_name(), Keyboard_shortcut_value(), and Window_set_shortcut().
word Key_modifiers (SDLMod mod)
Gets the modifiers in our format from the SDL_Mod information.
Returns a combination of MOD_SHIFT, MOD_ALT, ::MOD_CONTROL
Parameters:
mod SDL modifiers state
References MOD_ALT, MOD_CTRL, MOD_META, MOD_SHIFT, and word.
Referenced by Handle_joystick_press(), Handle_mouse_click(), and Keysym_to_keycode().