GrafX2: keyboard.c File Reference
keyboard.c File Reference
#include <string.h>
#include <ctype.h>
#include "global.h"
#include "keyboard.h"
Functions
word Key_for_scancode (word scancode)
Helper function to convert between SDL system and the old coding for PC keycodes.
word Key_modifiers (SDLMod mod)
Gets the modifiers in our format from the SDL_Mod information.
word Keysym_to_keycode (SDL_keysym keysym)
Convert an SDL keysym to an internal keycode number.
const char * Key_name (word Key)
Returns key name in a string.
word Keysym_to_ANSI (SDL_keysym keysym)
Convert an SDL keysym to an ANSI/ASCII character.
Variables
const word Scancode_to_sym [256][4]
Function Documentation
word Key_for_scancode (word scancode)
Helper function to convert between SDL system and the old coding for PC keycodes.
This is only used to convert configuration files from the DOS version of Grafx2, where keyboard codes are in in the IBM PC AT form.
Parameters:
scancode Scancode to convert
References Scancode_to_sym.
Referenced by Load_CFG().
word Key_modifiers (SDLMod mod)
Gets the modifiers in our format from the SDL_Mod information.
Returns a combination of MOD_SHIFT, MOD_ALT, MOD_CONTROL
Parameters:
mod SDL modifiers state
References MOD_ALT, MOD_CTRL, MOD_META, MOD_SHIFT, and word.
Referenced by Handle_joystick_press(), Handle_mouse_click(), and Keysym_to_keycode().
word Keysym_to_keycode (SDL_keysym keysym)
Convert an SDL keysym to an internal keycode number.
This is needed because SDL tends to split the information across the unicode sym, the regular sym, and the raw keycode. We also need to differenciate 1 (keypad) and 1 (regular keyboard), and some other things. See the notice at the beginning of keyboard.h for the format of a keycode.
Parameters:
keysym SDL symbol to convert
References Key_modifiers(), and word.
Referenced by Handle_key_press(), and Handle_key_release().
const char* Key_name (word Key)
Returns key name in a string.
Used to display them in the helpscreens and in the keymapper window.
Parameters:
Key keycode of the key to translate, including modifiers
References GP2X_BUTTON_A, GP2X_BUTTON_B, GP2X_BUTTON_CLICK, GP2X_BUTTON_DOWN, GP2X_BUTTON_DOWNLEFT, GP2X_BUTTON_DOWNRIGHT, GP2X_BUTTON_L, GP2X_BUTTON_LEFT, GP2X_BUTTON_R, GP2X_BUTTON_RIGHT, GP2X_BUTTON_SELECT, GP2X_BUTTON_START, GP2X_BUTTON_UP, GP2X_BUTTON_UPLEFT, GP2X_BUTTON_UPRIGHT, GP2X_BUTTON_VOLDOWN, GP2X_BUTTON_VOLUP, GP2X_BUTTON_X, GP2X_BUTTON_Y, KEY_JOYBUTTON, KEY_MOUSEMIDDLE, KEY_MOUSEWHEELDOWN, KEY_MOUSEWHEELUP, Key_name(), MOD_ALT, MOD_CTRL, MOD_META, MOD_SHIFT, and word.
Referenced by Key_name(), Keyboard_shortcut_value(), and Window_set_shortcut().
word Keysym_to_ANSI (SDL_keysym keysym)
Convert an SDL keysym to an ANSI/ASCII character.
This is used to type text and numeric values in input boxes.
Parameters:
keysym SDL symbol to convert
References KEY_ESC.
Referenced by Handle_key_press().
Variable Documentation
const word Scancode_to_sym[256][4]
Referenced by Key_for_scancode().