GrafX2: layers.h File Reference
layers.h File Reference
Functions
void Button_Layer_add (void)
void Button_Layer_remove (void)
void Button_Layer_menu (void)
void Button_Layer_set_transparent (void)
void Button_Layer_get_transparent (void)
void Button_Layer_merge (void)
void Button_Layer_up (void)
void Button_Layer_down (void)
void Button_Layer_select (void)
void Button_Layer_toggle (void)
void Layer_activate (byte layer, short side)
Function Documentation
void Button_Layer_add (void)
References Add_layer(), Backup_layers(), BUTTON_LAYER_ADD, Display_all_screen(), Display_cursor(), Display_layerbar(), End_of_modification(), Hide_cursor, Main_backups, Main_current_layer, MAX_NB_LAYERS, T_Page::Nb_layers, T_List_of_pages::Pages, Unselect_button(), and Update_depth_buffer().
Referenced by Init_buttons().
void Button_Layer_remove (void)
References Backup_layers(), BUTTON_LAYER_REMOVE, Delete_layer(), Display_all_screen(), Display_cursor(), Display_layerbar(), End_of_modification(), Hide_cursor, Main_backups, Main_current_layer, T_Page::Nb_layers, T_List_of_pages::Pages, Redraw_layered_image(), Unselect_button(), and Update_screen_targets().
Referenced by Init_buttons().
void Button_Layer_menu (void)
References T_Page::Background_transparent, Backup_layers(), BUTTON_HELP, BUTTON_LAYER_MENU, byte, Close_window(), Display_all_screen(), Display_cursor(), Draw_transparent_background(), Draw_transparent_color(), End_of_modification(), Get_color_behind_window(), Hide_cursor, Is_shortcut(), Key, KEY_ESC, KEY_NONE, Main_backups, MC_Black, MC_Dark, MC_Light, Open_window(), T_List_of_pages::Pages, Print_in_window(), Redraw_layered_image(), T_Page::Transparent_color, Unselect_button(), Update_window_area, Wait_end_of_click(), Window_clicked_button(), Window_display_frame_in(), Window_height, Window_help(), Window_set_normal_button(), and Window_width.
Referenced by Init_buttons().
void Button_Layer_set_transparent (void)
References Back_color, Backup_layers(), BUTTON_LAYER_COLOR, Display_all_screen(), Display_cursor(), End_of_modification(), Hide_cursor, Main_backups, T_List_of_pages::Pages, Redraw_layered_image(), T_Page::Transparent_color, and Unselect_button().
Referenced by Init_buttons().
void Button_Layer_get_transparent (void)
References Back_color, BUTTON_LAYER_COLOR, Display_cursor(), Hide_cursor, Main_backups, T_List_of_pages::Pages, Set_back_color(), T_Page::Transparent_color, and Unselect_button().
Referenced by Init_buttons().
void Button_Layer_merge (void)
References Backup_layers(), BUTTON_LAYER_MERGE, Display_all_screen(), Display_cursor(), Display_layerbar(), End_of_modification(), Hide_cursor, Main_current_layer, Merge_layer(), Redraw_layered_image(), Unselect_button(), and Update_screen_targets().
Referenced by Init_buttons().
void Button_Layer_up (void)
References Backup_layers(), BUTTON_LAYER_UP, byte, Display_all_screen(), Display_cursor(), Display_layerbar(), dword, End_of_modification(), Hide_cursor, T_Page::Image, Main_backups, Main_current_layer, Main_layers_visible, T_Page::Nb_layers, T_List_of_pages::Pages, Redraw_layered_image(), Unselect_button(), and Update_screen_targets().
Referenced by Init_buttons().
void Button_Layer_down (void)
References Backup_layers(), BUTTON_LAYER_DOWN, byte, Display_all_screen(), Display_cursor(), Display_layerbar(), dword, End_of_modification(), Hide_cursor, T_Page::Image, Main_backups, Main_current_layer, Main_layers_visible, T_List_of_pages::Pages, Redraw_layered_image(), Unselect_button(), and Update_screen_targets().
Referenced by Init_buttons().
void Button_Layer_select (void)
References Layer_activate(), Layer_button_width, LEFT_SIDE, Main_backups, Menu_bars, Menu_factor_X, MENUBAR_LAYERS, Mouse_X, T_Page::Nb_layers, T_List_of_pages::Pages, and T_Menu_Bar::Skin_width.
Referenced by Init_buttons().
void Button_Layer_toggle (void)
References Layer_activate(), Layer_button_width, Main_backups, Menu_bars, Menu_factor_X, MENUBAR_LAYERS, Mouse_X, T_Page::Nb_layers, T_List_of_pages::Pages, RIGHT_SIDE, and T_Menu_Bar::Skin_width.
Referenced by Init_buttons().
void Layer_activate (byte layer, short side)
References Display_all_screen(), Display_cursor(), Display_layerbar(), dword, Hide_cursor, LEFT_SIDE, Main_backups, Main_current_layer, Main_layers_visible, T_Page::Nb_layers, T_List_of_pages::Pages, Redraw_layered_image(), RIGHT_SIDE, Update_depth_buffer(), Update_screen_targets(), and word.
Referenced by Button_Layer_select(), Button_Layer_toggle(), and Main_handler().