GrafX2: libraw2crtc.h File Reference
libraw2crtc.h File Reference
Defines
#define LIBRAW2CRTC_H 1
Functions
unsigned char * raw2crtc (unsigned short width, unsigned short height, unsigned char mode, unsigned char r9, unsigned long *outSize, unsigned char *r1, unsigned char r12, unsigned char r13)
Define Documentation
#define LIBRAW2CRTC_H 1
Function Documentation
unsigned char* raw2crtc (unsigned short width, unsigned short height, unsigned char mode, unsigned char r9, unsigned long * outSize, unsigned char * r1, unsigned char r12, unsigned char r13)
References addrCalc(), mode0interlace(), mode1interlace(), mode2interlace(), mode3interlace(), and ptrMode.
Referenced by Save_SCR().