GrafX2: libraw2crtc.c File Reference
libraw2crtc.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "const.h"
#include "global.h"
#include "struct.h"
#include "loadsave.h"
Functions
unsigned short addrCalc (unsigned char vcc, unsigned char rcc, unsigned char hcc, unsigned char cclk, unsigned char r1, unsigned char r12, unsigned char r13)
unsigned char mode0interlace (T_IO_Context *context, unsigned char x, unsigned char y)
unsigned char mode1interlace (T_IO_Context *context, unsigned char x, unsigned char y)
unsigned char mode2interlace (T_IO_Context *context, unsigned char x, unsigned char y)
unsigned char mode3interlace (T_IO_Context *context, unsigned char x, unsigned char y)
unsigned char * raw2crtc (T_IO_Context *context, unsigned short width, unsigned short height, unsigned char mode, unsigned char r9, unsigned long *outSize, unsigned char *r1, unsigned char r12, unsigned char r13)
Variables
unsigned char(* ptrMode)(T_IO_Context *context, unsigned char x, unsigned char y)
Function Documentation
unsigned short addrCalc (unsigned char vcc, unsigned char rcc, unsigned char hcc, unsigned char cclk, unsigned char r1, unsigned char r12, unsigned char r13)
Referenced by raw2crtc().
unsigned char mode0interlace (T_IO_Context * context, unsigned char x, unsigned char y)
References Get_pixel().
Referenced by raw2crtc().
unsigned char mode1interlace (T_IO_Context * context, unsigned char x, unsigned char y)
References Get_pixel().
Referenced by raw2crtc().
unsigned char mode2interlace (T_IO_Context * context, unsigned char x, unsigned char y)
References Get_pixel().
Referenced by raw2crtc().
unsigned char mode3interlace (T_IO_Context * context, unsigned char x, unsigned char y)
References Get_pixel().
Referenced by raw2crtc().
unsigned char* raw2crtc (T_IO_Context * context, unsigned short width, unsigned short height, unsigned char mode, unsigned char r9, unsigned long * outSize, unsigned char * r1, unsigned char r12, unsigned char r13)
References addrCalc(), mode0interlace(), mode1interlace(), mode2interlace(), mode3interlace(), and ptrMode.
Referenced by Save_SCR().
Variable Documentation
unsigned char(* ptrMode)(T_IO_Context *context, unsigned char x, unsigned char y)
Referenced by raw2crtc().