GrafX2: loadsave.c File Reference
loadsave.c File Reference
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <SDL_image.h>
#include <SDL_endian.h>
#include "buttons.h"
#include "const.h"
#include "errors.h"
#include "global.h"
#include "io.h"
#include "loadsave.h"
#include "misc.h"
#include "graph.h"
#include "op_c.h"
#include "pages.h"
#include "palette.h"
#include "sdlscreen.h"
#include "struct.h"
#include "windows.h"
#include "engine.h"
Data Structures
struct T_String_list
Defines
#define _XOPEN_SOURCE 500
Functions
void Test_PKM (T_IO_Context *)
void Load_PKM (T_IO_Context *)
void Save_PKM (T_IO_Context *)
void Test_LBM (T_IO_Context *)
void Load_LBM (T_IO_Context *)
void Save_LBM (T_IO_Context *)
void Test_GIF (T_IO_Context *)
void Load_GIF (T_IO_Context *)
void Save_GIF (T_IO_Context *)
void Test_PCX (T_IO_Context *)
void Load_PCX (T_IO_Context *)
void Save_PCX (T_IO_Context *)
void Test_BMP (T_IO_Context *)
void Load_BMP (T_IO_Context *)
void Save_BMP (T_IO_Context *)
void Test_IMG (T_IO_Context *)
void Load_IMG (T_IO_Context *)
void Save_IMG (T_IO_Context *)
void Test_SCx (T_IO_Context *)
void Load_SCx (T_IO_Context *)
void Save_SCx (T_IO_Context *)
void Test_CEL (T_IO_Context *)
void Load_CEL (T_IO_Context *)
void Save_CEL (T_IO_Context *)
void Test_KCF (T_IO_Context *)
void Load_KCF (T_IO_Context *)
void Save_KCF (T_IO_Context *)
void Test_PAL (T_IO_Context *)
void Load_PAL (T_IO_Context *)
void Save_PAL (T_IO_Context *)
void Test_PI1 (T_IO_Context *)
void Load_PI1 (T_IO_Context *)
void Save_PI1 (T_IO_Context *)
void Test_PC1 (T_IO_Context *)
void Load_PC1 (T_IO_Context *)
void Save_PC1 (T_IO_Context *)
void Test_NEO (T_IO_Context *)
void Load_NEO (T_IO_Context *)
void Save_NEO (T_IO_Context *)
void Test_C64 (T_IO_Context *)
void Load_C64 (T_IO_Context *)
void Save_C64 (T_IO_Context *)
void Save_SCR (T_IO_Context *)
void Save_XPM (T_IO_Context *)
void Test_PNG (T_IO_Context *)
void Load_PNG (T_IO_Context *)
void Save_PNG (T_IO_Context *)
void Load_SDL_Image (T_IO_Context *)
void Set_pixel (T_IO_Context *context, short x_pos, short y_pos, byte color)
Set the color of a pixel (on load)
void Palette_loaded (T_IO_Context *context)
Remaps the window. To call after palette (last) changes.
void Set_pixel_24b (T_IO_Context *context, short x_pos, short y_pos, byte r, byte g, byte b)
Set the color of a 24bit pixel (on load)
void Set_palette_fake_24b (T_Palette palette)
void Pre_load (T_IO_Context *context, short width, short height, long file_size, int format, enum PIXEL_RATIO ratio, byte truecolor)
Generic allocation and similar stuff, done at beginning of image load, as soon as size is known.
void Init_write_buffer (void)
void Write_one_byte (FILE *file, byte b)
void End_write (FILE *file)
void Set_file_error (int value)
void Load_image (T_IO_Context *context)
High-level picture loading function.
void Save_image (T_IO_Context *context)
High-level picture saving function.
SDL_Surface * Load_surface (char *full_name)
Load an arbitrary SDL_Surface.
void Emergency_backup (const char *fname, byte *source, int width, int height, T_Palette *palette)
Saves an image.
void Image_emergency_backup ()
Function which attempts to save backups of the images (main and spare), called in case of SIGSEGV.
T_Format * Get_fileformat (byte format)
byte Get_pixel (T_IO_Context *context, short x, short y)
Query the color of a pixel (to save)
void Destroy_context (T_IO_Context *context)
Cleans up resources.
void Init_context_preview (T_IO_Context *context, char *file_name, char *file_directory)
Setup for loading a preview in fileselector.
void Init_context_backup_image (T_IO_Context *context, char *file_name, char *file_directory)
void Init_context_layered_image (T_IO_Context *context, char *file_name, char *file_directory)
Setup for loading/saving the current main image.
void Init_context_brush (T_IO_Context *context, char *file_name, char *file_directory)
Setup for loading/saving the flattened version of current main image.
void Init_context_surface (T_IO_Context *context, char *file_name, char *file_directory)
void Set_layer (T_IO_Context *context, byte layer)
Function to call when need to switch layers.
void Add_backup_file (const char *name)
Adds a file to Backups_main or Backups_spare lists, if it's a backup.
int String_compare (const void *a, const void *b)
String comparer for sorting.
byte Process_backups (T_String_list **list)
Reload safety backups, by loading several files in the right order.
int Check_recovery (void)
Checks if there are any pending safety backups, and then opens them.
void Rotate_safety_backups (void)
Makes a safety backup periodically.
void Delete_safety_backups (void)
Remove safety backups. Need to call on normal program exit.
Variables
T_Format File_formats [NB_KNOWN_FORMATS]
Array of the known file formats.
byte * Write_buffer
word Write_buffer_index
T_String_list * Backups_main = NULL
A list of files, used for scanning a directory.
T_String_list * Backups_spare = NULL
A list of files, used for scanning a directory.
const int Rotation_safety_backup = 8
const int Min_interval_for_safety_backup = 30000
const int Min_edits_for_safety_backup = 10
const int Max_interval_for_safety_backup = 60000
const int Max_edits_for_safety_backup = 30
byte Safety_backup_active = 0
Global indicator that tells if the safety backup system is active.
Define Documentation
#define _XOPEN_SOURCE 500
Function Documentation
void Test_PKM (T_IO_Context *)
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), T_PKM_Header::Height, T_PKM_Header::Ident, T_PKM_Header::Jump, MAX_PATH_CHARACTERS, T_PKM_Header::Method, T_PKM_Header::Palette, Read_byte(), Read_bytes(), Read_word_le(), T_PKM_Header::Recog1, T_PKM_Header::Recog2, and T_PKM_Header::Width.
void Load_PKM (T_IO_Context *)
References Back_color, byte, T_IO_Context::Comment, COMMENT_SIZE, dword, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_PKM, Get_full_filename(), T_IO_Context::Height, T_PKM_Header::Height, T_PKM_Header::Ident, T_PKM_Header::Jump, MAX_PATH_CHARACTERS, T_PKM_Header::Method, Original_screen_X, Original_screen_Y, T_IO_Context::Palette, T_PKM_Header::Palette, Palette_64_to_256(), Palette_loaded(), PIXEL_SIMPLE, Pre_load(), Read_byte(), Read_bytes(), Read_word_be(), Read_word_le(), T_PKM_Header::Recog1, T_PKM_Header::Recog2, Set_pixel(), T_IO_Context::Width, T_PKM_Header::Width, and word.
void Save_PKM (T_IO_Context *)
References Back_color, byte, T_IO_Context::Comment, dword, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Find_recog(), Get_full_filename(), Get_pixel(), T_IO_Context::Height, T_PKM_Header::Height, T_PKM_Header::Ident, Init_write_buffer(), T_PKM_Header::Jump, MAX_PATH_CHARACTERS, T_PKM_Header::Method, T_IO_Context::Palette, T_PKM_Header::Palette, Palette_256_to_64(), T_PKM_Header::Recog1, T_PKM_Header::Recog2, Screen_height, Screen_width, T_IO_Context::Width, T_PKM_Header::Width, word, Write_byte(), Write_bytes(), Write_one_byte(), and Write_word_le().
void Test_LBM (T_IO_Context *)
References dword, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), LBM_file, MAX_PATH_CHARACTERS, Read_bytes(), and Read_dword_be().
void Load_LBM (T_IO_Context *)
References Adapt_palette_HAM(), Back_color, T_LBM_Header::BitPlanes, byte, T_Config::Clear_palette, T_IO_Context::Color_cycles, T_LBM_Header::Compression, Config, T_IO_Context::Cycle_range, Draw_ILBM_line(), dword, T_Color_cycle::End, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_LBM, Get_full_filename(), HBPm1, T_IO_Context::Height, T_LBM_Header::Height, Image_HAM, T_Color_cycle::Inverse, LBM_buffer, LBM_file, LBM_Skip_section(), LBM_Wait_for(), T_LBM_Header::Mask, MAX_PATH_CHARACTERS, Original_screen_X, Original_screen_Y, T_LBM_Header::Pad1, T_IO_Context::Palette, Palette_256_to_64(), Palette_64_to_256(), Palette_loaded(), PIXEL_SIMPLE, Pre_load(), Read_byte(), Read_bytes(), Read_dword_be(), Read_word_be(), Set_file_error(), Set_pixel(), T_Color_cycle::Speed, T_Color_cycle::Start, SWAP_BYTES, T_LBM_Header::Transp_col, T_IO_Context::Width, T_LBM_Header::Width, word, T_LBM_Header::X_aspect, T_LBM_Header::X_org, T_LBM_Header::X_screen, T_LBM_Header::Y_aspect, T_LBM_Header::Y_org, and T_LBM_Header::Y_screen.
void Save_LBM (T_IO_Context *)
References Back_color, T_LBM_Header::BitPlanes, byte, T_IO_Context::Color_cycles, T_LBM_Header::Compression, T_IO_Context::Cycle_range, T_Color_cycle::End, End_write(), T_IO_Context::File_directory, File_error, File_length(), T_IO_Context::File_name, Get_full_filename(), Get_pixel(), T_IO_Context::Height, T_LBM_Header::Height, Init_write_buffer(), T_Color_cycle::Inverse, LBM_file, LBM_list_size, T_LBM_Header::Mask, MAX_PATH_CHARACTERS, New_color(), T_LBM_Header::Pad1, T_IO_Context::Palette, Screen_height, Screen_width, T_Color_cycle::Speed, T_Color_cycle::Start, Transfer_colors(), T_LBM_Header::Transp_col, T_LBM_Header::Width, T_IO_Context::Width, word, Write_byte(), Write_bytes(), Write_dword_be(), Write_word_be(), T_LBM_Header::X_aspect, T_LBM_Header::X_org, T_LBM_Header::X_screen, T_LBM_Header::Y_aspect, T_LBM_Header::Y_org, and T_LBM_Header::Y_screen.
void Test_GIF (T_IO_Context *)
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, and Read_bytes().
void Load_GIF (T_IO_Context *)
References T_GIF_LSDB::Aspect, T_GIF_LSDB::Backcol, T_IO_Context::Background_transparent, byte, T_Config::Clear_palette, T_IO_Context::Color_cycles, T_IO_Context::Comment, COMMENT_SIZE, Config, T_IO_Context::Cycle_range, T_GIF_GCE::Delay_time, T_Color_cycle::End, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_GIF, Get_full_filename(), GIF_current_code, GIF_file, GIF_finished_interlaced_image, GIF_get_next_code(), GIF_interlaced, GIF_last_byte, GIF_nb_bits, GIF_new_pixel(), GIF_pass, GIF_pos_X, GIF_pos_Y, GIF_remainder_bits, GIF_remainder_byte, T_IO_Context::Height, T_GIF_LSDB::Height, T_GIF_IDB::Image_height, T_GIF_IDB::Image_width, T_GIF_IDB::Indicator, T_Color_cycle::Inverse, MAX_PATH_CHARACTERS, Min(), T_IO_Context::Original_file_directory, T_IO_Context::Original_file_name, Original_screen_X, Original_screen_Y, T_GIF_GCE::Packed_fields, T_IO_Context::Palette, Palette_loaded(), PIXEL_SIMPLE, T_GIF_IDB::Pos_X, T_GIF_IDB::Pos_Y, Pre_load(), Read_byte(), Read_bytes(), Read_word_be(), Read_word_le(), T_GIF_LSDB::Resol, Set_layer(), T_Color_cycle::Speed, T_Color_cycle::Start, SWAP_BYTES, T_IO_Context::Transparent_color, T_GIF_GCE::Transparent_color, T_IO_Context::Width, T_GIF_LSDB::Width, and word.
void Save_GIF (T_IO_Context *)
References T_GIF_LSDB::Aspect, T_GIF_LSDB::Backcol, T_IO_Context::Background_transparent, byte, T_IO_Context::Color_cycles, T_IO_Context::Comment, Config, T_IO_Context::Cycle_range, T_Color_cycle::End, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), GIF_empty_buffer(), GIF_file, GIF_last_byte, GIF_nb_bits, GIF_next_pixel(), GIF_pos_X, GIF_pos_Y, GIF_remainder_bits, GIF_remainder_byte, GIF_set_code(), GIF_stop, T_IO_Context::Height, T_GIF_LSDB::Height, T_GIF_IDB::Image_height, T_GIF_IDB::Image_width, T_GIF_IDB::Indicator, Init_write_buffer(), T_Color_cycle::Inverse, MAX_PATH_CHARACTERS, T_GIF_IDB::Nb_bits_pixel, T_IO_Context::Nb_layers, T_IO_Context::Original_file_directory, T_IO_Context::Original_file_name, T_IO_Context::Palette, T_GIF_IDB::Pos_X, T_GIF_IDB::Pos_Y, T_GIF_LSDB::Resol, Screen_height, T_Config::Screen_size_in_GIF, Screen_width, Set_layer(), T_Color_cycle::Speed, T_Color_cycle::Start, T_IO_Context::Transparent_color, T_IO_Context::Width, T_GIF_LSDB::Width, word, Write_byte(), Write_bytes(), Write_word_be(), and Write_word_le().
void Test_PCX (T_IO_Context *)
References T_PCX_Header::Bytes_per_plane_line, T_PCX_Header::Compression, T_PCX_Header::Depth, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_PCX_Header::Filler, Get_full_filename(), T_PCX_Header::Manufacturer, MAX_PATH_CHARACTERS, T_PCX_Header::Palette_16c, T_PCX_Header::Palette_info, T_PCX_Header::Plane, Read_byte(), Read_bytes(), Read_word_le(), T_PCX_Header::Reserved, T_PCX_Header::Screen_X, T_PCX_Header::Screen_Y, T_PCX_Header::Version, T_PCX_Header::X_dpi, T_PCX_Header::X_max, T_PCX_Header::X_min, T_PCX_Header::Y_dpi, T_PCX_Header::Y_max, and T_PCX_Header::Y_min.
void Load_PCX (T_IO_Context *)
References byte, T_PCX_Header::Bytes_per_plane_line, T_Config::Clear_palette, T_PCX_Header::Compression, Config, DEBUG, T_PCX_Header::Depth, Draw_ILBM_line(), Draw_PCX_line(), dword, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_PCX_Header::Filler, FORMAT_PCX, Get_full_filename(), HBPm1, T_IO_Context::Height, Image_HAM, LBM_buffer, T_PCX_Header::Manufacturer, MAX_PATH_CHARACTERS, Original_screen_X, Original_screen_Y, T_IO_Context::Palette, T_PCX_Header::Palette_16c, T_PCX_Header::Palette_info, Palette_loaded(), PIXEL_SIMPLE, T_PCX_Header::Plane, Pre_load(), Read_byte(), Read_bytes(), Read_word_le(), T_PCX_Header::Reserved, T_PCX_Header::Screen_X, T_PCX_Header::Screen_Y, Set_file_error(), Set_pixel(), Set_pixel_24b(), T_PCX_Header::Version, T_IO_Context::Width, T_PCX_Header::X_dpi, T_PCX_Header::X_max, T_PCX_Header::X_min, T_PCX_Header::Y_dpi, T_PCX_Header::Y_max, and T_PCX_Header::Y_min.
void Save_PCX (T_IO_Context *)
References byte, T_PCX_Header::Bytes_per_plane_line, T_PCX_Header::Compression, T_PCX_Header::Depth, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_PCX_Header::Filler, Get_full_filename(), Get_pixel(), T_IO_Context::Height, Init_write_buffer(), T_PCX_Header::Manufacturer, MAX_PATH_CHARACTERS, T_IO_Context::Palette, T_PCX_Header::Palette_16c, T_PCX_Header::Palette_info, T_PCX_Header::Plane, T_PCX_Header::Reserved, Screen_height, Screen_width, T_PCX_Header::Screen_X, T_PCX_Header::Screen_Y, T_PCX_Header::Version, T_IO_Context::Width, Write_bytes(), Write_one_byte(), Write_word_le(), T_PCX_Header::X_dpi, T_PCX_Header::X_max, T_PCX_Header::X_min, T_PCX_Header::Y_dpi, T_PCX_Header::Y_max, and T_PCX_Header::Y_min.
void Test_BMP (T_IO_Context *)
References T_BMP_Header::Clr_Imprt, T_BMP_Header::Compression, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), T_BMP_Header::Height, MAX_PATH_CHARACTERS, T_BMP_Header::Nb_bits, T_BMP_Header::Nb_Clr, T_BMP_Header::Offset, T_BMP_Header::Planes, Read_bytes(), Read_dword_le(), Read_word_le(), T_BMP_Header::Reserved_1, T_BMP_Header::Reserved_2, T_BMP_Header::Signature, T_BMP_Header::Size_1, T_BMP_Header::Size_2, T_BMP_Header::Size_3, T_BMP_Header::Width, T_BMP_Header::XPM, and T_BMP_Header::YPM.
void Load_BMP (T_IO_Context *)
References Bitmap_mask(), byte, T_Config::Clear_palette, T_BMP_Header::Clr_Imprt, T_BMP_Header::Compression, Config, dword, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_BMP, Get_full_filename(), T_IO_Context::Height, T_BMP_Header::Height, MAX_PATH_CHARACTERS, T_BMP_Header::Nb_bits, T_BMP_Header::Nb_Clr, T_BMP_Header::Offset, T_IO_Context::Palette, Palette_loaded(), PIXEL_SIMPLE, T_BMP_Header::Planes, Pre_load(), Read_byte(), Read_bytes(), Read_dword_le(), Read_word_le(), T_BMP_Header::Reserved_1, T_BMP_Header::Reserved_2, Set_pixel(), Set_pixel_24b(), T_BMP_Header::Signature, T_BMP_Header::Size_1, T_BMP_Header::Size_2, T_BMP_Header::Size_3, T_IO_Context::Width, T_BMP_Header::Width, word, T_BMP_Header::XPM, and T_BMP_Header::YPM.
void Save_BMP (T_IO_Context *)
References byte, T_BMP_Header::Clr_Imprt, T_BMP_Header::Compression, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), Get_pixel(), T_BMP_Header::Height, T_IO_Context::Height, Init_write_buffer(), MAX_PATH_CHARACTERS, T_BMP_Header::Nb_bits, T_BMP_Header::Nb_Clr, T_BMP_Header::Offset, T_IO_Context::Palette, T_BMP_Header::Planes, T_BMP_Header::Reserved_1, T_BMP_Header::Reserved_2, T_BMP_Header::Signature, T_BMP_Header::Size_1, T_BMP_Header::Size_2, T_BMP_Header::Size_3, T_BMP_Header::Width, T_IO_Context::Width, word, Write_bytes(), Write_dword_le(), Write_one_byte(), Write_word_le(), T_BMP_Header::XPM, and T_BMP_Header::YPM.
void Test_IMG (T_IO_Context *)
References byte, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_IMG_Header::Filler1, T_IMG_Header::Filler2, Get_full_filename(), T_IMG_Header::Height, MAX_PATH_CHARACTERS, T_IMG_Header::Palette, Read_bytes(), Read_word_le(), and T_IMG_Header::Width.
void Load_IMG (T_IO_Context *)
References byte, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_IMG_Header::Filler1, T_IMG_Header::Filler2, FORMAT_IMG, Get_full_filename(), T_IO_Context::Height, T_IMG_Header::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, T_IMG_Header::Palette, Palette_loaded(), PIXEL_SIMPLE, Pre_load(), Read_bytes(), Read_word_le(), Set_pixel(), T_IO_Context::Width, T_IMG_Header::Width, and word.
void Save_IMG (T_IO_Context *)
References byte, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_IMG_Header::Filler1, T_IMG_Header::Filler2, Get_full_filename(), Get_pixel(), T_IO_Context::Height, T_IMG_Header::Height, Init_write_buffer(), MAX_PATH_CHARACTERS, T_IO_Context::Palette, T_IMG_Header::Palette, T_IO_Context::Width, T_IMG_Header::Width, Write_bytes(), Write_one_byte(), and Write_word_le().
void Test_SCx (T_IO_Context *)
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_SCx_Header::Filler1, T_SCx_Header::Filler2, Get_full_filename(), T_SCx_Header::Height, MAX_PATH_CHARACTERS, T_SCx_Header::Planes, Read_byte(), Read_bytes(), Read_word_le(), and T_SCx_Header::Width.
void Load_SCx (T_IO_Context *)
References byte, T_Config::Clear_palette, Config, Draw_ILBM_line(), T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_SCx_Header::Filler1, T_SCx_Header::Filler2, FORMAT_SCx, Get_full_filename(), HBPm1, T_IO_Context::Height, T_SCx_Header::Height, Image_HAM, LBM_buffer, MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_64_to_256(), Palette_loaded(), PIXEL_SIMPLE, T_SCx_Header::Planes, Pre_load(), Read_byte(), Read_bytes(), Read_word_le(), Set_pixel(), T_IO_Context::Width, T_SCx_Header::Width, and word.
void Save_SCx (T_IO_Context *)
References byte, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_SCx_Header::Filler1, T_SCx_Header::Filler2, Get_full_filename(), Get_pixel(), T_IO_Context::Height, T_SCx_Header::Height, Init_write_buffer(), MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_256_to_64(), T_SCx_Header::Planes, T_SCx_Header::Width, T_IO_Context::Width, Write_byte(), Write_bytes(), Write_one_byte(), and Write_word_le().
void Test_CEL (T_IO_Context *)
References T_IO_Context::File_directory, File_error, File_length(), T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, Get_full_filename(), T_CEL_Header2::Height, T_CEL_Header1::Height, T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, Read_byte(), Read_bytes(), Read_word_le(), T_CEL_Header2::Signature, T_CEL_Header2::Width, T_CEL_Header1::Width, T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Load_CEL (T_IO_Context *)
References byte, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, FORMAT_CEL, Get_full_filename(), Height, T_CEL_Header2::Height, T_IO_Context::Height, T_CEL_Header1::Height, T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, Original_screen_X, Original_screen_Y, PIXEL_SIMPLE, Pre_load(), Read_byte(), Read_bytes(), Read_word_le(), Set_pixel(), T_CEL_Header2::Signature, T_CEL_Header2::Width, T_IO_Context::Width, T_CEL_Header1::Width, T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Save_CEL (T_IO_Context *)
References byte, Count_used_colors(), dword, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, Get_full_filename(), Get_pixel(), T_CEL_Header2::Height, T_IO_Context::Height, T_CEL_Header1::Height, Init_write_buffer(), T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, T_CEL_Header2::Signature, T_CEL_Header2::Width, T_IO_Context::Width, T_CEL_Header1::Width, Write_byte(), Write_bytes(), Write_one_byte(), Write_word_le(), T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Test_KCF (T_IO_Context *)
References T_KCF_Header::color, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, Get_full_filename(), T_CEL_Header2::Height, T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, T_KCF_Header::Palette, Read_byte(), Read_bytes(), Read_word_le(), T_CEL_Header2::Signature, T_CEL_Header2::Width, T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Load_KCF (T_IO_Context *)
References byte, T_Config::Clear_palette, T_KCF_Header::color, Config, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, Get_full_filename(), T_CEL_Header2::Height, T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, T_IO_Context::Palette, T_KCF_Header::Palette, Palette_loaded(), Read_byte(), Read_bytes(), Read_word_le(), T_CEL_Header2::Signature, T_CEL_Header2::Width, T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Save_KCF (T_IO_Context *)
References byte, T_KCF_Header::color, Count_used_colors(), dword, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, Get_full_filename(), T_CEL_Header2::Height, T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, T_IO_Context::Palette, T_KCF_Header::Palette, T_CEL_Header2::Signature, T_CEL_Header2::Width, Write_byte(), Write_bytes(), Write_word_le(), T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Test_PAL (T_IO_Context *)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), and MAX_PATH_CHARACTERS.
void Load_PAL (T_IO_Context *)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_64_to_256(), Palette_loaded(), and Read_bytes().
void Save_PAL (T_IO_Context *)
< full filename
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, and T_IO_Context::Palette.
void Test_PI1 (T_IO_Context *)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, Read_word_le(), and word.
void Load_PI1 (T_IO_Context *)
References byte, T_Config::Clear_palette, Config, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_PI1, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_loaded(), PI1_8b_to_16p(), PI1_decode_palette(), PIXEL_SIMPLE, Pre_load(), Read_bytes(), Set_pixel(), T_IO_Context::Width, and word.
void Save_PI1 (T_IO_Context *)
References byte, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), Get_pixel(), Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, PI1_16p_to_8b(), PI1_code_palette(), Width, and Write_bytes().
void Test_PC1 (T_IO_Context *)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, Read_word_le(), and word.
void Load_PC1 (T_IO_Context *)
References byte, T_Config::Clear_palette, Config, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_PC1, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_loaded(), PC1_4bp_to_1line(), PC1_uncompress_packbits(), PI1_decode_palette(), PIXEL_SIMPLE, Pre_load(), Read_bytes(), Set_pixel(), T_IO_Context::Width, and word.
void Save_PC1 (T_IO_Context *)
References byte, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), Get_pixel(), Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, PC1_1line_to_4bp(), PC1_compress_packbits(), PI1_code_palette(), Width, and Write_bytes().
void Test_NEO (T_IO_Context *)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, Read_word_le(), and word.
void Load_NEO (T_IO_Context *)
References byte, T_Config::Clear_palette, Config, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_NEO, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_loaded(), PI1_8b_to_16p(), PI1_decode_palette(), PIXEL_SIMPLE, Pre_load(), Read_bytes(), Set_pixel(), T_IO_Context::Width, and word.
void Save_NEO (T_IO_Context *)
References byte, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), Get_pixel(), Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, PI1_16p_to_8b(), PI1_code_palette(), Width, and Write_bytes().
void Test_C64 (T_IO_Context *)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), and MAX_PATH_CHARACTERS.
void Load_C64 (T_IO_Context *)
References byte, T_IO_Context::Comment, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_C64, Get_full_filename(), T_IO_Context::Height, Load_C64_hires(), Load_C64_multi(), MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_loaded(), PIXEL_WIDE, Pre_load(), T_IO_Context::Ratio, Read_byte(), Read_bytes(), T_IO_Context::Width, and word.
void Save_C64 (T_IO_Context *)
References byte, Count_used_colors(), dword, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, Save_C64_hires(), Save_C64_multi(), Save_C64_window(), Warning_message(), and T_IO_Context::Width.
void Save_SCR (T_IO_Context *)
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, raw2crtc(), T_IO_Context::Width, and Write_bytes().
void Save_XPM (T_IO_Context *)
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), Get_pixel(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, and T_IO_Context::Width.
void Test_PNG (T_IO_Context *)
References byte, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, and Read_bytes().
void Load_PNG (T_IO_Context *)
References T_IO_Context::Background_transparent, T_IO_Context::Buffer_image_24b, byte, T_Config::Clear_palette, T_IO_Context::Comment, COMMENT_SIZE, Config, CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_PNG, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, Min(), T_IO_Context::Palette, Palette_loaded(), PIXEL_SIMPLE, PIXEL_TALL, PIXEL_WIDE, png_get_bit_depth, png_get_color_type, png_get_image_height, png_get_image_width, png_get_rowbytes, png_set_expand_gray_1_2_4_to_8, Pre_load(), T_IO_Context::Ratio, Read_bytes(), Row_pointers, Set_pixel(), Set_pixel_24b(), T_IO_Context::Transparent_color, T_IO_Context::Type, and T_IO_Context::Width.
void Save_PNG (T_IO_Context *)
References T_IO_Context::Background_transparent, byte, T_IO_Context::Comment, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, T_IO_Context::Pitch, Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, Row_pointers, T_IO_Context::Target_address, T_IO_Context::Transparent_color, and T_IO_Context::Width.
void Load_SDL_Image (T_IO_Context * context)
References dword, T_IO_Context::File_directory, File_error, File_length(), T_IO_Context::File_name, FORMAT_ALL_IMAGES, FORMAT_MISC, Get_full_filename(), Get_SDL_Palette(), Get_SDL_pixel_8(), Get_SDL_pixel_hicolor(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, PIXEL_SIMPLE, Pre_load(), Set_pixel(), Set_pixel_24b(), T_IO_Context::Width, and word.
Referenced by Load_image().
void Set_pixel (T_IO_Context * context, short x_pos, short y_pos, byte color)
Set the color of a pixel (on load)
References T_IO_Context::Buffer_image, byte, CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, T_IO_Context::Current_layer, T_IO_Context::Height, Menu_factor_X, T_IO_Context::Pitch, Pixel_in_current_screen(), Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, T_IO_Context::Preview_bitmap, T_IO_Context::Preview_factor_X, T_IO_Context::Preview_factor_Y, T_IO_Context::Preview_usage, PREVIEW_WIDTH, T_IO_Context::Ratio, T_IO_Context::Surface, T_IO_Context::Transparent_color, T_IO_Context::Type, and T_IO_Context::Width.
Referenced by Draw_ILBM_line(), Draw_PCX_line(), GIF_new_pixel(), Load_BMP(), Load_C64_hires(), Load_C64_multi(), Load_CEL(), Load_IMG(), Load_LBM(), Load_NEO(), Load_PC1(), Load_PCX(), Load_PI1(), Load_PKM(), Load_PNG(), Load_SCx(), and Load_SDL_Image().
void Palette_loaded (T_IO_Context * context)
Remaps the window. To call after palette (last) changes.
References CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, and T_IO_Context::Type.
Referenced by Load_BMP(), Load_C64(), Load_GIF(), Load_image(), Load_IMG(), Load_KCF(), Load_LBM(), Load_NEO(), Load_PAL(), Load_PC1(), Load_PCX(), Load_PI1(), Load_PKM(), Load_PNG(), Load_SCx(), and Pre_load().
void Set_pixel_24b (T_IO_Context * context, short x_pos, short y_pos, byte r, byte g, byte b)
Set the color of a 24bit pixel (on load)
References T_Components::B, T_IO_Context::Buffer_image_24b, byte, CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, T_Components::G, T_IO_Context::Height, Menu_factor_X, T_IO_Context::Preview_bitmap, T_IO_Context::Preview_factor_X, T_IO_Context::Preview_factor_Y, T_IO_Context::Preview_usage, PREVIEW_WIDTH, T_Components::R, T_IO_Context::Type, and T_IO_Context::Width.
Referenced by Load_BMP(), Load_PCX(), Load_PNG(), and Load_SDL_Image().
void Set_palette_fake_24b (T_Palette palette)
Referenced by Convert_24b_bitmap_to_256_fast(), and Pre_load().
void Pre_load (T_IO_Context * context, short width, short height, long file_size, int format, enum PIXEL_RATIO ratio, byte truecolor)
Generic allocation and similar stuff, done at beginning of image load, as soon as size is known.
References T_IO_Context::Background_transparent, Backup_new_image(), T_IO_Context::Buffer_image, T_IO_Context::Buffer_image_24b, byte, T_IO_Context::Comment, Compute_optimal_menu_colors(), Config, CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, File_error, T_IO_Context::Format, Get_fileformat(), T_IO_Context::Height, Main_current_layer, Main_format, Main_layers_visible, T_Config::Maximize_preview, MC_Black, MC_Light, Menu_factor_X, Menu_factor_Y, Message_out_of_memory(), T_IO_Context::Nb_layers, Num2str, T_IO_Context::Palette, Palette_loaded(), T_Format::Palette_only, T_IO_Context::Pitch, Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, T_IO_Context::Preview_bitmap, T_IO_Context::Preview_factor_X, T_IO_Context::Preview_factor_Y, PREVIEW_HEIGHT, T_IO_Context::Preview_pos_X, T_IO_Context::Preview_pos_Y, PREVIEW_WIDTH, Print_in_window(), T_IO_Context::Ratio, Round_div_max(), Set_layer(), Set_palette_fake_24b(), T_IO_Context::Surface, T_IO_Context::Target_address, T_IO_Context::Transparent_color, T_IO_Context::Type, Update_window_area, T_IO_Context::Width, Window_pos_X, Window_pos_Y, and Window_rectangle().
Referenced by Load_BMP(), Load_C64(), Load_CEL(), Load_GIF(), Load_IMG(), Load_LBM(), Load_NEO(), Load_PC1(), Load_PCX(), Load_PI1(), Load_PKM(), Load_PNG(), Load_SCx(), and Load_SDL_Image().
void Init_write_buffer (void)
References byte, Write_buffer, and Write_buffer_index.
Referenced by Save_BMP(), Save_CEL(), Save_GIF(), Save_IMG(), Save_LBM(), Save_PCX(), Save_PKM(), and Save_SCx().
void Write_one_byte (FILE * file, byte b)
References File_error, Write_buffer, Write_buffer_index, and Write_bytes().
Referenced by GIF_empty_buffer(), Save_BMP(), Save_CEL(), Save_IMG(), Save_PCX(), Save_PKM(), Save_SCx(), and Transfer_colors().
void End_write (FILE * file)
References File_error, Write_buffer, Write_buffer_index, and Write_bytes().
Referenced by Save_BMP(), Save_CEL(), Save_GIF(), Save_IMG(), Save_LBM(), Save_PCX(), Save_PKM(), and Save_SCx().
void Set_file_error (int value)
References File_error.
Referenced by Load_LBM(), and Load_PCX().
void Load_image (T_IO_Context * context)
High-level picture loading function.
References T_IO_Context::Background_transparent, T_Page::Background_transparent, Backup_layers(), Brush, Brush_height, Brush_width, T_IO_Context::Buffer_image, T_IO_Context::Buffer_image_24b, byte, T_IO_Context::Color_cycles, T_IO_Context::Comment, Compute_optimal_menu_colors(), Config, CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, Convert_24b_bitmap_to_256(), Count_used_colors(), Cursor_shape, CURSOR_SHAPE_ARROW, CURSOR_SHAPE_HOURGLASS, T_IO_Context::Cycle_range, DEFAULT_FILEFORMAT, Display_cursor(), Download_infos_page_main(), dword, T_Color_cycle::End, T_Gradient_range::End, Error, Favorite_GUI_color(), T_IO_Context::File_directory, T_Page::File_directory, File_error, T_IO_Context::File_name, T_Page::Filename, Flush_update(), T_IO_Context::Format, FORMAT_ALL_FILES, Get_fileformat(), T_Page::Gradients, T_IO_Context::Height, Hide_cursor, T_Format::Identifier, T_Page::Image, T_Color_cycle::Inverse, T_Gradient_range::Inverse, T_Format::Load, Load_SDL_Image(), Main_backups, Main_comment, Main_current_layer, Main_fileformat, Main_image_height, Main_image_is_modified, Main_image_width, Main_layers_visible, Main_palette, MAX_PAINTBRUSH_SIZE, MC_Black, MC_Light, MC_Window, Menu_factor_X, NB_KNOWN_FORMATS, T_IO_Context::Nb_layers, T_IO_Context::Original_file_directory, T_IO_Context::Original_file_name, T_List_of_pages::Pages, T_Page::Palette, T_IO_Context::Palette, Palette_loaded(), T_Format::Palette_only, Pixel, Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, T_IO_Context::Preview_bitmap, T_IO_Context::Preview_factor_X, T_IO_Context::Preview_factor_Y, PREVIEW_HEIGHT, T_IO_Context::Preview_pos_X, T_IO_Context::Preview_pos_Y, T_IO_Context::Preview_usage, PREVIEW_WIDTH, Print_in_window(), T_Gradient_array::Range, T_IO_Context::Ratio, Remap_screen_after_menu_colors_change(), T_Config::Safety_colors, Set_palette(), Smear_brush, Smear_brush_height, Smear_brush_width, T_Color_cycle::Speed, T_Gradient_range::Speed, T_Color_cycle::Start, T_Gradient_range::Start, T_IO_Context::Surface, T_Format::Test, T_IO_Context::Transparent_color, T_Page::Transparent_color, T_IO_Context::Type, Update_window_area, T_IO_Context::Width, and Window_rectangle().
Referenced by Button_Load_or_Save(), Button_Reload(), Init_program(), Load_picture(), Load_surface(), Main_handler(), and Process_backups().
void Save_image (T_IO_Context * context)
High-level picture saving function.
References Confirmation_box(), CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, Error, File_error, T_IO_Context::Format, Get_fileformat(), Main_backups, T_Page::Nb_layers, T_List_of_pages::Pages, T_Format::Save, T_Format::Supports_layers, and T_IO_Context::Type.
Referenced by Button_Autosave(), Button_Quit_local_function(), Rotate_safety_backups(), and Save_picture().
SDL_Surface* Load_surface (char * full_name)
Load an arbitrary SDL_Surface.
References Destroy_context(), Init_context_surface(), Load_image(), and T_IO_Context::Surface.
Referenced by Load_font(), and Load_graphics().
void Emergency_backup (const char * fname, byte * source, int width, int height, T_Palette * palette)
Saves an image.
This routine will only be called when all hope is lost, memory thrashed, etc It's the last chance to save anything, but the code has to be extremely careful, anything could happen. The chosen format is IMG since it's extremely simple, difficult to make it create an unusable image.
References Config_directory, File_error, T_IMG_Header::Filler1, T_IMG_Header::Filler2, MAX_PATH_CHARACTERS, Write_byte(), Write_bytes(), and Write_word_le().
Referenced by Image_emergency_backup().
void Image_emergency_backup (void)
Function which attempts to save backups of the images (main and spare), called in case of SIGSEGV.
It will save an image only if it has just one layer... otherwise, the risk of flattening a layered image (or saving just one detail layer) is too high.
References Emergency_backup(), T_Bitmap::Image, Main_backups, Main_image_height, Main_image_width, Main_palette, Main_screen, T_Page::Nb_layers, T_List_of_pages::Pages, Spare_backups, Spare_image_height, Spare_image_width, Spare_palette, and Spare_visible_image.
T_Format* Get_fileformat (byte format)
References File_formats, FORMAT_GIF, and NB_KNOWN_FORMATS.
Referenced by Button_Load_or_Save(), Load_image(), Load_picture(), Pre_load(), Read_list_of_files(), Save_image(), and Save_picture().
byte Get_pixel (T_IO_Context * context, short x, short y)
Query the color of a pixel (to save)
Generic cleanup done on end of loading (ex: color-conversion from the temporary 24b buffer)
References T_IO_Context::Pitch, and T_IO_Context::Target_address.
Referenced by GIF_next_pixel(), mode0interlace(), mode1interlace(), mode2interlace(), mode3interlace(), Save_BMP(), Save_C64_hires(), Save_C64_multi(), Save_CEL(), Save_IMG(), Save_LBM(), Save_NEO(), Save_PC1(), Save_PCX(), Save_PI1(), Save_PKM(), Save_SCx(), and Save_XPM().
void Destroy_context (T_IO_Context * context)
Cleans up resources.
References T_IO_Context::Buffer_image, T_IO_Context::Buffer_image_24b, and T_IO_Context::Preview_bitmap.
Referenced by Button_Autosave(), Button_Load_or_Save(), Button_Quit_local_function(), Button_Reload(), Init_program(), Load_picture(), Load_surface(), Main_handler(), Process_backups(), Rotate_safety_backups(), and Save_picture().
void Init_context_preview (T_IO_Context * context, char * file_name, char * file_directory)
Setup for loading a preview in fileselector.
References CONTEXT_PREVIEW, T_IO_Context::File_directory, T_IO_Context::File_name, T_IO_Context::Format, Main_fileformat, and T_IO_Context::Type.
Referenced by Button_Load_or_Save().
void Init_context_backup_image (T_IO_Context * context, char * file_name, char * file_directory)
References Init_context_layered_image().
Referenced by Process_backups(), and Rotate_safety_backups().
void Init_context_layered_image (T_IO_Context * context, char * file_name, char * file_directory)
Setup for loading/saving the current main image.
References T_Page::Background_transparent, T_IO_Context::Background_transparent, T_IO_Context::Color_cycles, T_IO_Context::Comment, CONTEXT_MAIN_IMAGE, T_IO_Context::Cycle_range, T_Color_cycle::End, T_Gradient_range::End, T_IO_Context::File_directory, T_IO_Context::File_name, T_IO_Context::Format, T_Page::Gradients, T_IO_Context::Height, T_Page::Image, T_Gradient_range::Inverse, T_Color_cycle::Inverse, Main_backups, Main_comment, Main_fileformat, Main_image_height, Main_image_width, Main_palette, T_Page::Nb_layers, T_IO_Context::Nb_layers, T_List_of_pages::Pages, T_IO_Context::Palette, T_IO_Context::Pitch, Pixel_ratio, PIXEL_SIMPLE, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, T_Gradient_array::Range, T_IO_Context::Ratio, T_Gradient_range::Speed, T_Color_cycle::Speed, T_Color_cycle::Start, T_Gradient_range::Start, T_IO_Context::Target_address, T_Page::Transparent_color, T_IO_Context::Transparent_color, T_IO_Context::Type, and T_IO_Context::Width.
Referenced by Button_Autosave(), Button_Quit_local_function(), Button_Reload(), Init_context_backup_image(), Init_program(), Load_picture(), Main_handler(), and Save_picture().
void Init_context_brush (T_IO_Context * context, char * file_name, char * file_directory)
Setup for loading/saving the flattened version of current main image.
Setup for loading/saving the user's brush
References T_IO_Context::Background_transparent, Brush, Brush_fileformat, Brush_height, Brush_width, CONTEXT_BRUSH, T_IO_Context::File_directory, T_IO_Context::File_name, T_IO_Context::Format, T_IO_Context::Height, Main_palette, T_IO_Context::Nb_layers, T_IO_Context::Palette, T_IO_Context::Pitch, PIXEL_SIMPLE, T_IO_Context::Ratio, T_IO_Context::Target_address, T_IO_Context::Transparent_color, T_IO_Context::Type, and T_IO_Context::Width.
Referenced by Load_picture(), and Save_picture().
void Init_context_surface (T_IO_Context * context, char * file_name, char * file_directory)
References T_IO_Context::Background_transparent, CONTEXT_SURFACE, DEFAULT_FILEFORMAT, T_IO_Context::File_directory, T_IO_Context::File_name, T_IO_Context::Format, T_IO_Context::Nb_layers, PIXEL_SIMPLE, T_IO_Context::Ratio, T_IO_Context::Transparent_color, and T_IO_Context::Type.
Referenced by Load_surface().
void Set_layer (T_IO_Context * context, byte layer)
Function to call when need to switch layers.
References Add_layer(), CONTEXT_MAIN_IMAGE, T_IO_Context::Current_layer, T_Page::Image, Main_backups, Main_current_layer, Main_layers_visible, T_Page::Nb_layers, T_IO_Context::Nb_layers, T_List_of_pages::Pages, T_IO_Context::Target_address, and T_IO_Context::Type.
Referenced by Load_GIF(), Pre_load(), and Save_GIF().
void Add_backup_file (const char * name)
Adds a file to Backups_main or Backups_spare lists, if it's a backup.
References Backups_main, Backups_spare, Extract_filename(), Main_safety_backup_prefix, MAX_PATH_CHARACTERS, T_String_list::Next, Spare_safety_backup_prefix, and T_String_list::String.
Referenced by Check_recovery(), and Delete_safety_backups().
int String_compare (const void * a, const void * b)
String comparer for sorting.
Referenced by Process_backups().
byte Process_backups (T_String_list ** list)
Reload safety backups, by loading several files in the right order.
References byte, Config, Config_directory, Destroy_context(), Display_all_screen(), Init_context_backup_image(), Load_image(), Main_image_is_modified, MAX_PATH_CHARACTERS, T_Config::Max_undo_pages, T_String_list::Next, T_IO_Context::Original_file_directory, T_IO_Context::Original_file_name, Redraw_layered_image(), T_String_list::String, and String_compare().
Referenced by Check_recovery().
int Check_recovery (void)
Checks if there are any pending safety backups, and then opens them.
Returns:
0 if no problem, -1 if the backup system cannot be activated, >=1 if some backups are restored
References Add_backup_file(), Button_Page(), Compute_limits(), Compute_paintbrush_coordinates(), Config_directory, Create_lock_file(), For_each_file(), Main_offset_X, Main_offset_Y, Process_backups(), and Safety_backup_active.
Referenced by Init_program().
void Rotate_safety_backups (void)
Makes a safety backup periodically.
References Config_directory, Destroy_context(), T_Page::File_directory, T_Page::Filename, T_IO_Context::Format, FORMAT_GIF, Init_context_backup_image(), Main_backups, Main_edits_since_safety_backup, Main_safety_backup_prefix, Main_safety_number, Main_time_of_safety_backup, Max_edits_for_safety_backup, Max_interval_for_safety_backup, MAX_PATH_CHARACTERS, Min_edits_for_safety_backup, Min_interval_for_safety_backup, T_IO_Context::Original_file_directory, T_IO_Context::Original_file_name, T_List_of_pages::Pages, Rotation_safety_backup, Safety_backup_active, and Save_image().
Referenced by End_of_modification().
void Delete_safety_backups (void)
Remove safety backups. Need to call on normal program exit.
References Add_backup_file(), Config_directory, For_each_file(), T_String_list::Next, Release_lock_file(), Safety_backup_active, and T_String_list::String.
Referenced by Program_shutdown().
Variable Documentation
T_Format File_formats[NB_KNOWN_FORMATS]
Initial value:
 {
  {FORMAT_ALL_IMAGES, "(all)", NULL, NULL, NULL, 0, 0, 0, "", "gif;png;bmp;pcx;pkm;lbm;ilbm;iff;img;sci;scq;scf;scn;sco;pi1;pc1;cel;neo;kcf;pal;c64;koa;tga;pnm;xpm;xcf;jpg;jpeg;tif;tiff;ico"},
  {FORMAT_ALL_FILES, "(*.*)", NULL, NULL, NULL, 0, 0, 0, "", "*"},
  {FORMAT_GIF, " gif", Test_GIF, Load_GIF, Save_GIF, 0, 1, 1, "gif", "gif"},
  {FORMAT_PNG, " png", Test_PNG, Load_PNG, Save_PNG, 0, 1, 0, "png", "png"},
  {FORMAT_BMP, " bmp", Test_BMP, Load_BMP, Save_BMP, 0, 0, 0, "bmp", "bmp"},
  {FORMAT_PCX, " pcx", Test_PCX, Load_PCX, Save_PCX, 0, 0, 0, "pcx", "pcx"},
  {FORMAT_PKM, " pkm", Test_PKM, Load_PKM, Save_PKM, 0, 1, 0, "pkm", "pkm"},
  {FORMAT_LBM, " lbm", Test_LBM, Load_LBM, Save_LBM, 0, 0, 0, "lbm", "lbm;iff;ilbm"},
  {FORMAT_IMG, " img", Test_IMG, Load_IMG, Save_IMG, 0, 0, 0, "img", "img"},
  {FORMAT_SCx, " sc?", Test_SCx, Load_SCx, Save_SCx, 0, 0, 0, "sc?", "sci;scq;scf;scn;sco"},
  {FORMAT_PI1, " pi1", Test_PI1, Load_PI1, Save_PI1, 0, 0, 0, "pi1", "pi1"},
  {FORMAT_PC1, " pc1", Test_PC1, Load_PC1, Save_PC1, 0, 0, 0, "pc1", "pc1"},
  {FORMAT_CEL, " cel", Test_CEL, Load_CEL, Save_CEL, 0, 0, 0, "cel", "cel"},
  {FORMAT_NEO, " neo", Test_NEO, Load_NEO, Save_NEO, 0, 0, 0, "neo", "neo"},
  {FORMAT_KCF, " kcf", Test_KCF, Load_KCF, Save_KCF, 1, 0, 0, "kcf", "kcf"},
  {FORMAT_PAL, " pal", Test_PAL, Load_PAL, Save_PAL, 1, 0, 0, "pal", "pal"},
  {FORMAT_C64, " c64", Test_C64, Load_C64, Save_C64, 0, 1, 0, "c64", "c64;koa"},
  {FORMAT_SCR, " cpc", NULL,     NULL,     Save_SCR, 0, 0, 0, "cpc", "cpc;scr"},
  {FORMAT_XPM, " xpm", NULL,     NULL,     Save_XPM, 0, 0, 0, "xpm", "xpm"},
  {FORMAT_MISC,"misc.",NULL,     NULL,     NULL,     0, 0, 0, "",    "tga;pnm;xpm;xcf;jpg;jpeg;tif;tiff;ico"},
}
Array of the known file formats.
Referenced by Button_Load_or_Save(), and Get_fileformat().
byte* Write_buffer
Referenced by End_write(), Init_write_buffer(), and Write_one_byte().
word Write_buffer_index
Referenced by End_write(), Init_write_buffer(), and Write_one_byte().
T_String_list* Backups_main = NULL
A list of files, used for scanning a directory.
Referenced by Add_backup_file().
T_String_list* Backups_spare = NULL
A list of files, used for scanning a directory.
Referenced by Add_backup_file().
const int Rotation_safety_backup = 8
Referenced by Rotate_safety_backups().
const int Min_interval_for_safety_backup = 30000
Referenced by Rotate_safety_backups().
const int Min_edits_for_safety_backup = 10
Referenced by Rotate_safety_backups().
const int Max_interval_for_safety_backup = 60000
Referenced by Rotate_safety_backups().
const int Max_edits_for_safety_backup = 30
Referenced by Rotate_safety_backups().
byte Safety_backup_active = 0
Global indicator that tells if the safety backup system is active.
Referenced by Check_recovery(), Delete_safety_backups(), and Rotate_safety_backups().