GrafX2: loadsave.h File Reference
loadsave.h File Reference
Saving and loading different picture formats.
#include <stdio.h>
#include <SDL_image.h>
Data Structures
struct T_Color_cycle
Data for a cycling color series. Heavily cloned from T_Gradient_array.
struct T_IO_Context
struct T_Format
Data for an image file format.
struct T_IMG_Header
Defines
#define PREVIEW_WIDTH 120
#define PREVIEW_HEIGHT 80
#define NB_KNOWN_FORMATS 19
Total number of known file formats.
Typedefs
typedef void(* Func_IO)(T_IO_Context *)
Type of a function that can be called for a T_IO_Context. Kind of a method.
Enumerations
enum CONTEXT_TYPE { CONTEXT_MAIN_IMAGE, CONTEXT_BRUSH, CONTEXT_PREVIEW, CONTEXT_SURFACE }
Functions
void Init_context_preview (T_IO_Context *context, char *file_name, char *file_directory)
Setup for loading a preview in fileselector.
void Init_context_layered_image (T_IO_Context *context, char *file_name, char *file_directory)
Setup for loading/saving the current main image.
void Init_context_backup_image (T_IO_Context *context, char *file_name, char *file_directory)
void Init_context_flat_image (T_IO_Context *context, char *file_name, char *file_directory)
void Init_context_brush (T_IO_Context *context, char *file_name, char *file_directory)
Setup for loading/saving the flattened version of current main image.
void Init_context_history_step (T_IO_Context *context, T_Page *page)
void Init_context_surface (T_IO_Context *context, char *file_name, char *file_directory)
void Destroy_context (T_IO_Context *context)
Cleans up resources.
void Load_image (T_IO_Context *context)
High-level picture loading function.
void Save_image (T_IO_Context *context)
High-level picture saving function.
int Check_recovery (void)
Checks if there are any pending safety backups, and then opens them.
void Rotate_safety_backups (void)
Makes a safety backup periodically.
void Delete_safety_backups (void)
Remove safety backups. Need to call on normal program exit.
void Image_emergency_backup (void)
Function which attempts to save backups of the images (main and spare), called in case of SIGSEGV.
SDL_Surface * Load_surface (char *full_name)
Load an arbitrary SDL_Surface.
T_Format * Get_fileformat (byte format)
void Pre_load (T_IO_Context *context, short width, short height, long file_size, int format, enum PIXEL_RATIO ratio, byte truecolor)
Generic allocation and similar stuff, done at beginning of image load, as soon as size is known.
void Palette_loaded (T_IO_Context *context)
Remaps the window. To call after palette (last) changes.
byte Get_pixel (T_IO_Context *context, short x, short y)
Generic cleanup done on end of loading (ex: color-conversion from the temporary 24b buffer)
void Set_pixel (T_IO_Context *context, short x, short y, byte c)
Set the color of a pixel (on load)
void Set_pixel_24b (T_IO_Context *context, short x, short y, byte r, byte g, byte b)
Set the color of a 24bit pixel (on load)
void Set_layer (T_IO_Context *context, byte layer)
Function to call when need to switch layers.
void Set_file_error (int value)
void Init_write_buffer (void)
void Write_one_byte (FILE *file, byte b)
void End_write (FILE *file)
Variables
T_Format File_formats []
Array of the known file formats.
Detailed Description
Saving and loading different picture formats.
Also handles showing the preview in fileselectors.
Define Documentation
#define PREVIEW_WIDTH 120
Referenced by Button_Load_or_Save(), Load_image(), Pre_load(), Set_pixel(), and Set_pixel_24b().
#define PREVIEW_HEIGHT 80
Referenced by Button_Load_or_Save(), Load_image(), and Pre_load().
#define NB_KNOWN_FORMATS 19
Total number of known file formats.
Referenced by Button_Load_or_Save(), Get_fileformat(), and Load_image().
Typedef Documentation
typedef void(* Func_IO)(T_IO_Context *)
Type of a function that can be called for a T_IO_Context. Kind of a method.
Enumeration Type Documentation
enum CONTEXT_TYPE
Enumerator:
CONTEXT_MAIN_IMAGE
CONTEXT_BRUSH
CONTEXT_PREVIEW
CONTEXT_SURFACE
Function Documentation
void Init_context_preview (T_IO_Context * context, char * file_name, char * file_directory)
Setup for loading a preview in fileselector.
References CONTEXT_PREVIEW, T_IO_Context::File_directory, T_IO_Context::File_name, T_IO_Context::Format, Main_fileformat, and T_IO_Context::Type.
Referenced by Button_Load_or_Save().
void Init_context_layered_image (T_IO_Context * context, char * file_name, char * file_directory)
Setup for loading/saving the current main image.
References T_Page::Background_transparent, T_IO_Context::Background_transparent, T_IO_Context::Color_cycles, T_IO_Context::Comment, CONTEXT_MAIN_IMAGE, T_IO_Context::Cycle_range, T_Color_cycle::End, T_Gradient_range::End, T_IO_Context::File_directory, T_IO_Context::File_name, T_IO_Context::Format, T_Page::Gradients, T_IO_Context::Height, T_Page::Image, T_Gradient_range::Inverse, T_Color_cycle::Inverse, Main_backups, Main_comment, Main_fileformat, Main_image_height, Main_image_width, Main_palette, T_Page::Nb_layers, T_IO_Context::Nb_layers, T_List_of_pages::Pages, T_IO_Context::Palette, T_IO_Context::Pitch, Pixel_ratio, PIXEL_SIMPLE, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, T_Gradient_array::Range, T_IO_Context::Ratio, T_Gradient_range::Speed, T_Color_cycle::Speed, T_Color_cycle::Start, T_Gradient_range::Start, T_IO_Context::Target_address, T_Page::Transparent_color, T_IO_Context::Transparent_color, T_IO_Context::Type, and T_IO_Context::Width.
Referenced by Button_Autosave(), Button_Quit_local_function(), Button_Reload(), Init_context_backup_image(), Init_program(), Load_picture(), Main_handler(), and Save_picture().
void Init_context_backup_image (T_IO_Context * context, char * file_name, char * file_directory)
References Init_context_layered_image().
Referenced by Process_backups(), and Rotate_safety_backups().
void Init_context_flat_image (T_IO_Context * context, char * file_name, char * file_directory)
void Init_context_brush (T_IO_Context * context, char * file_name, char * file_directory)
Setup for loading/saving the flattened version of current main image.
Setup for loading/saving the user's brush
References T_IO_Context::Background_transparent, Brush, Brush_fileformat, Brush_height, Brush_width, CONTEXT_BRUSH, T_IO_Context::File_directory, T_IO_Context::File_name, T_IO_Context::Format, T_IO_Context::Height, Main_palette, T_IO_Context::Nb_layers, T_IO_Context::Palette, T_IO_Context::Pitch, PIXEL_SIMPLE, T_IO_Context::Ratio, T_IO_Context::Target_address, T_IO_Context::Transparent_color, T_IO_Context::Type, and T_IO_Context::Width.
Referenced by Load_picture(), and Save_picture().
void Init_context_history_step (T_IO_Context * context, T_Page * page)
void Init_context_surface (T_IO_Context * context, char * file_name, char * file_directory)
References T_IO_Context::Background_transparent, CONTEXT_SURFACE, DEFAULT_FILEFORMAT, T_IO_Context::File_directory, T_IO_Context::File_name, T_IO_Context::Format, T_IO_Context::Nb_layers, PIXEL_SIMPLE, T_IO_Context::Ratio, T_IO_Context::Transparent_color, and T_IO_Context::Type.
Referenced by Load_surface().
void Destroy_context (T_IO_Context * context)
Cleans up resources.
References T_IO_Context::Buffer_image, T_IO_Context::Buffer_image_24b, and T_IO_Context::Preview_bitmap.
Referenced by Button_Autosave(), Button_Load_or_Save(), Button_Quit_local_function(), Button_Reload(), Init_program(), Load_picture(), Load_surface(), Main_handler(), Process_backups(), Rotate_safety_backups(), and Save_picture().
void Load_image (T_IO_Context * context)
High-level picture loading function.
References T_IO_Context::Background_transparent, T_Page::Background_transparent, Backup_layers(), Brush, Brush_height, Brush_width, T_IO_Context::Buffer_image, T_IO_Context::Buffer_image_24b, byte, T_IO_Context::Color_cycles, T_IO_Context::Comment, Compute_optimal_menu_colors(), Config, CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, Convert_24b_bitmap_to_256(), Count_used_colors(), Cursor_shape, CURSOR_SHAPE_ARROW, CURSOR_SHAPE_HOURGLASS, T_IO_Context::Cycle_range, DEFAULT_FILEFORMAT, Display_cursor(), Download_infos_page_main(), dword, T_Color_cycle::End, T_Gradient_range::End, Error, Favorite_GUI_color(), T_IO_Context::File_directory, T_Page::File_directory, File_error, T_IO_Context::File_name, T_Page::Filename, Flush_update(), T_IO_Context::Format, FORMAT_ALL_FILES, Get_fileformat(), T_Page::Gradients, T_IO_Context::Height, Hide_cursor, T_Format::Identifier, T_Page::Image, T_Color_cycle::Inverse, T_Gradient_range::Inverse, T_Format::Load, Load_SDL_Image(), Main_backups, Main_comment, Main_current_layer, Main_fileformat, Main_image_height, Main_image_is_modified, Main_image_width, Main_layers_visible, Main_palette, MAX_PAINTBRUSH_SIZE, MC_Black, MC_Light, MC_Window, Menu_factor_X, NB_KNOWN_FORMATS, T_IO_Context::Nb_layers, T_IO_Context::Original_file_directory, T_IO_Context::Original_file_name, T_List_of_pages::Pages, T_Page::Palette, T_IO_Context::Palette, Palette_loaded(), T_Format::Palette_only, Pixel, Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, T_IO_Context::Preview_bitmap, T_IO_Context::Preview_factor_X, T_IO_Context::Preview_factor_Y, PREVIEW_HEIGHT, T_IO_Context::Preview_pos_X, T_IO_Context::Preview_pos_Y, T_IO_Context::Preview_usage, PREVIEW_WIDTH, Print_in_window(), T_Gradient_array::Range, T_IO_Context::Ratio, Remap_screen_after_menu_colors_change(), T_Config::Safety_colors, Set_palette(), Smear_brush, Smear_brush_height, Smear_brush_width, T_Color_cycle::Speed, T_Gradient_range::Speed, T_Color_cycle::Start, T_Gradient_range::Start, T_IO_Context::Surface, T_Format::Test, T_IO_Context::Transparent_color, T_Page::Transparent_color, T_IO_Context::Type, Update_window_area, T_IO_Context::Width, and Window_rectangle().
Referenced by Button_Load_or_Save(), Button_Reload(), Init_program(), Load_picture(), Load_surface(), Main_handler(), and Process_backups().
void Save_image (T_IO_Context * context)
High-level picture saving function.
References Confirmation_box(), CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, Error, File_error, T_IO_Context::Format, Get_fileformat(), Main_backups, T_Page::Nb_layers, T_List_of_pages::Pages, T_Format::Save, T_Format::Supports_layers, and T_IO_Context::Type.
Referenced by Button_Autosave(), Button_Quit_local_function(), Rotate_safety_backups(), and Save_picture().
int Check_recovery (void)
Checks if there are any pending safety backups, and then opens them.
Returns 0 if there were none Returns non-zero if some backups were loaded.
Returns:
0 if no problem, -1 if the backup system cannot be activated, >=1 if some backups are restored
References Add_backup_file(), Button_Page(), Compute_limits(), Compute_paintbrush_coordinates(), Config_directory, Create_lock_file(), For_each_file(), Main_offset_X, Main_offset_Y, Process_backups(), and Safety_backup_active.
Referenced by Init_program().
void Rotate_safety_backups (void)
Makes a safety backup periodically.
References Config_directory, Destroy_context(), T_Page::File_directory, T_Page::Filename, T_IO_Context::Format, FORMAT_GIF, Init_context_backup_image(), Main_backups, Main_edits_since_safety_backup, Main_safety_backup_prefix, Main_safety_number, Main_time_of_safety_backup, Max_edits_for_safety_backup, Max_interval_for_safety_backup, MAX_PATH_CHARACTERS, Min_edits_for_safety_backup, Min_interval_for_safety_backup, T_IO_Context::Original_file_directory, T_IO_Context::Original_file_name, T_List_of_pages::Pages, Rotation_safety_backup, Safety_backup_active, and Save_image().
Referenced by End_of_modification().
void Delete_safety_backups (void)
Remove safety backups. Need to call on normal program exit.
References Add_backup_file(), Config_directory, For_each_file(), T_String_list::Next, Release_lock_file(), Safety_backup_active, and T_String_list::String.
Referenced by Program_shutdown().
void Image_emergency_backup (void)
Function which attempts to save backups of the images (main and spare), called in case of SIGSEGV.
It will save an image only if it has just one layer... otherwise, the risk of flattening a layered image (or saving just one detail layer) is too high.
References Emergency_backup(), T_Bitmap::Image, Main_backups, Main_image_height, Main_image_width, Main_palette, Main_screen, T_Page::Nb_layers, T_List_of_pages::Pages, Spare_backups, Spare_image_height, Spare_image_width, Spare_palette, and Spare_visible_image.
SDL_Surface* Load_surface (char * full_name)
Load an arbitrary SDL_Surface.
References Destroy_context(), Init_context_surface(), Load_image(), and T_IO_Context::Surface.
Referenced by Load_font(), and Load_graphics().
T_Format* Get_fileformat (byte format)
References File_formats, FORMAT_GIF, and NB_KNOWN_FORMATS.
Referenced by Button_Load_or_Save(), Load_image(), Load_picture(), Pre_load(), Read_list_of_files(), Save_image(), and Save_picture().
void Pre_load (T_IO_Context * context, short width, short height, long file_size, int format, enum PIXEL_RATIO ratio, byte truecolor)
Generic allocation and similar stuff, done at beginning of image load, as soon as size is known.
References T_IO_Context::Background_transparent, Backup_new_image(), T_IO_Context::Buffer_image, T_IO_Context::Buffer_image_24b, byte, T_IO_Context::Comment, Compute_optimal_menu_colors(), Config, CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, File_error, T_IO_Context::Format, Get_fileformat(), T_IO_Context::Height, Main_current_layer, Main_format, Main_layers_visible, T_Config::Maximize_preview, MC_Black, MC_Light, Menu_factor_X, Menu_factor_Y, Message_out_of_memory(), T_IO_Context::Nb_layers, Num2str, T_IO_Context::Palette, Palette_loaded(), T_Format::Palette_only, T_IO_Context::Pitch, Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, T_IO_Context::Preview_bitmap, T_IO_Context::Preview_factor_X, T_IO_Context::Preview_factor_Y, PREVIEW_HEIGHT, T_IO_Context::Preview_pos_X, T_IO_Context::Preview_pos_Y, PREVIEW_WIDTH, Print_in_window(), T_IO_Context::Ratio, Round_div_max(), Set_layer(), Set_palette_fake_24b(), T_IO_Context::Surface, T_IO_Context::Target_address, T_IO_Context::Transparent_color, T_IO_Context::Type, Update_window_area, T_IO_Context::Width, Window_pos_X, Window_pos_Y, and Window_rectangle().
Referenced by Load_BMP(), Load_C64(), Load_CEL(), Load_GIF(), Load_IMG(), Load_LBM(), Load_NEO(), Load_PC1(), Load_PCX(), Load_PI1(), Load_PKM(), Load_PNG(), Load_SCx(), and Load_SDL_Image().
void Palette_loaded (T_IO_Context * context)
Remaps the window. To call after palette (last) changes.
References CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, and T_IO_Context::Type.
Referenced by Load_BMP(), Load_C64(), Load_GIF(), Load_image(), Load_IMG(), Load_KCF(), Load_LBM(), Load_NEO(), Load_PAL(), Load_PC1(), Load_PCX(), Load_PI1(), Load_PKM(), Load_PNG(), Load_SCx(), and Pre_load().
byte Get_pixel (T_IO_Context * context, short x, short y)
Generic cleanup done on end of loading (ex: color-conversion from the temporary 24b buffer)
Query the color of a pixel (to save)
References T_IO_Context::Pitch, and T_IO_Context::Target_address.
Referenced by GIF_next_pixel(), mode0interlace(), mode1interlace(), mode2interlace(), mode3interlace(), Save_BMP(), Save_C64_hires(), Save_C64_multi(), Save_CEL(), Save_IMG(), Save_LBM(), Save_NEO(), Save_PC1(), Save_PCX(), Save_PI1(), Save_PKM(), Save_SCx(), and Save_XPM().
void Set_pixel (T_IO_Context * context, short x, short y, byte c)
Set the color of a pixel (on load)
References T_IO_Context::Buffer_image, byte, CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, T_IO_Context::Current_layer, T_IO_Context::Height, Menu_factor_X, T_IO_Context::Pitch, Pixel_in_current_screen(), Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, T_IO_Context::Preview_bitmap, T_IO_Context::Preview_factor_X, T_IO_Context::Preview_factor_Y, T_IO_Context::Preview_usage, PREVIEW_WIDTH, T_IO_Context::Ratio, T_IO_Context::Surface, T_IO_Context::Transparent_color, T_IO_Context::Type, and T_IO_Context::Width.
Referenced by Draw_ILBM_line(), Draw_PCX_line(), GIF_new_pixel(), Load_BMP(), Load_C64_hires(), Load_C64_multi(), Load_CEL(), Load_IMG(), Load_LBM(), Load_NEO(), Load_PC1(), Load_PCX(), Load_PI1(), Load_PKM(), Load_PNG(), Load_SCx(), and Load_SDL_Image().
void Set_pixel_24b (T_IO_Context * context, short x, short y, byte r, byte g, byte b)
Set the color of a 24bit pixel (on load)
References T_Components::B, T_IO_Context::Buffer_image_24b, byte, CONTEXT_BRUSH, CONTEXT_MAIN_IMAGE, CONTEXT_PREVIEW, CONTEXT_SURFACE, T_Components::G, T_IO_Context::Height, Menu_factor_X, T_IO_Context::Preview_bitmap, T_IO_Context::Preview_factor_X, T_IO_Context::Preview_factor_Y, T_IO_Context::Preview_usage, PREVIEW_WIDTH, T_Components::R, T_IO_Context::Type, and T_IO_Context::Width.
Referenced by Load_BMP(), Load_PCX(), Load_PNG(), and Load_SDL_Image().
void Set_layer (T_IO_Context * context, byte layer)
Function to call when need to switch layers.
References Add_layer(), CONTEXT_MAIN_IMAGE, T_IO_Context::Current_layer, T_Page::Image, Main_backups, Main_current_layer, Main_layers_visible, T_Page::Nb_layers, T_IO_Context::Nb_layers, T_List_of_pages::Pages, T_IO_Context::Target_address, and T_IO_Context::Type.
Referenced by Load_GIF(), Pre_load(), and Save_GIF().
void Set_file_error (int value)
References File_error.
Referenced by Load_LBM(), and Load_PCX().
void Init_write_buffer (void)
References byte, Write_buffer, and Write_buffer_index.
Referenced by Save_BMP(), Save_CEL(), Save_GIF(), Save_IMG(), Save_LBM(), Save_PCX(), Save_PKM(), and Save_SCx().
void Write_one_byte (FILE * file, byte b)
References File_error, Write_buffer, Write_buffer_index, and Write_bytes().
Referenced by GIF_empty_buffer(), Save_BMP(), Save_CEL(), Save_IMG(), Save_PCX(), Save_PKM(), Save_SCx(), and Transfer_colors().
void End_write (FILE * file)
References File_error, Write_buffer, Write_buffer_index, and Write_bytes().
Referenced by Save_BMP(), Save_CEL(), Save_GIF(), Save_IMG(), Save_LBM(), Save_PCX(), Save_PKM(), and Save_SCx().
Variable Documentation
T_Format File_formats[]
Array of the known file formats.
Referenced by Button_Load_or_Save(), and Get_fileformat().