GrafX2: misc.h File Reference
misc.h File Reference
Miscellanous unsorted functions.
Functions
void Copy_image_to_brush (short start_x, short start_y, short Brush_width, short Brush_height, word image_width)
void Remap_general_lowlevel (byte *conversion_table, byte *buffer, short width, short height, short buffer_width)
void Scroll_picture (byte *main_src, byte *main_dest, short x_offset, short y_offset)
void Wait_end_of_click (void)
void Set_color (byte color, byte red, byte green, byte blue)
void Set_palette (T_Palette palette)
void Palette_256_to_64 (T_Palette palette)
void Palette_64_to_256 (T_Palette palette)
void Hide_current_image (byte color)
void Hide_current_image_with_stencil (byte color, byte *stencil)
void Slider_timer (byte speed)
dword Round_div (dword numerator, dword divisor)
word Count_used_colors (dword *usage)
Count used palette indexes in the whole picture Return the total number of different colors Fill in "usage" with the count for each color.
word Count_used_colors_area (dword *usage, word start_x, word start_y, word width, word height)
Same as Count_used_colors, but for a given rectangle in the picture only.
word Count_used_colors_screen_area (dword *usage, word start_x, word start_y, word width, word height)
Same as Count_used_colors, but use a block screen memory instead of picture data.
void Pixel_in_brush (word x, word y, byte color)
byte Read_pixel_from_spare_screen (word x, word y)
byte Read_pixel_from_backup_screen (word x, word y)
byte Read_pixel_from_feedback_screen (word x, word y)
byte Read_pixel_from_brush (word x, word y)
void Ellipse_compute_limites (short horizontal_radius, short vertical_radius)
byte Pixel_in_ellipse (void)
byte Pixel_in_circle (void)
void Init_chrono (dword delay)
void Check_timer (void)
void Replace_a_color (byte old_color, byte New_color)
void Replace_colors_within_limits (byte *replace_table)
byte Effect_interpolated_colorize (word x, word y, byte color)
byte Effect_additive_colorize (word x, word y, byte color)
byte Effect_substractive_colorize (word x, word y, byte color)
byte Effect_sieve (word x, word y)
void Flip_Y_lowlevel (byte *src, short width, short height)
Inverts a pixel buffer, according to a horizontal axis.
void Flip_X_lowlevel (byte *src, short width, short height)
Inverts a pixel buffer, according to a vertical axis.
void Rotate_90_deg_lowlevel (byte *source, byte *dest, short width, short height)
Rotate a pixel buffer by 90 degrees, clockwise.
void Rotate_270_deg_lowlevel (byte *source, byte *dest, short width, short height)
Rotate a pixel buffer by 90 degrees, counter-clockwise.
void Rotate_180_deg_lowlevel (byte *src, short width, short height)
Rotate a pixel buffer by 180 degrees.
void Rescale (byte *src_buffer, short src_width, short src_height, byte *dst_buffer, short dst_width, short dst_height, short x_flipped, short y_flipped)
Copies an image to another, rescaling it and optionally flipping it.
void Zoom_a_line (byte *original_line, byte *zoomed_line, word factor, word width)
void Copy_part_of_image_to_another (byte *source, word source_x, word source_y, word width, word height, word source_width, byte *dest, word dest_x, word dest_y, word destination_width)
unsigned long Memory_free (void)
void Num2str (dword number, char *str, byte nb_char)
short Round (float value)
short Round_div_max (short numerator, short divisor)
int Min (int a, int b)
int Max (int a, int b)
char * Mode_label (int mode)
int Convert_videomode_arg (const char *argument)
Variables
byte Timer_state
dword Timer_delay
dword Timer_start
byte New_preview_is_needed
Detailed Description
Miscellanous unsorted functions.
Function Documentation
void Copy_image_to_brush (short start_x, short start_y, short Brush_width, short Brush_height, word image_width)
References Brush, byte, T_Page::Image, Main_backups, Main_current_layer, and T_List_of_pages::Pages.
Referenced by Capture_brush().
void Remap_general_lowlevel (byte * conversion_table, byte * buffer, short width, short height, short buffer_width)
Referenced by Remap_brush(), Remap_image_highlevel(), and Remap_spare().
void Scroll_picture (byte * main_src, byte * main_dest, short x_offset, short y_offset)
References byte, Main_image_height, Main_image_width, Update_rect(), and word.
Referenced by Scroll_0_5(), and Scroll_12_5().
void Wait_end_of_click (void)
References Get_input(), and Mouse_K.
Referenced by Button_Airbrush_menu(), Button_Gradients(), Button_Load_or_Save(), Button_Message_initial(), Button_Palette(), Button_Resolution(), Button_Settings(), Centered_lines_12_7(), Curve_3_points_12_11(), Curve_4_points_2_9(), Distort_brush_1_0(), Fill_1_0(), Fill_2_0(), Filled_polyform_12_8(), Grad_circle_12_8(), Grad_ellipse_12_8(), Grad_rectangle_0_9(), K_line_12_7(), Magnifier_12_0(), Menu_shade(), Menu_tag_colors(), Polyfill_12_9(), Polyform_12_8(), Polygon_12_9(), Readline_ex(), Replace_1_0(), Replace_2_0(), Return_to_draw_mode(), Rotate_brush_12_0(), Select_button(), Stretch_brush_12_0(), and Window_help().
void Set_color (byte color, byte red, byte green, byte blue)
References Screen_SDL.
Referenced by Button_Skins(), Set_blue(), Set_green(), and Set_red().
void Set_palette (T_Palette palette)
References Round_palette_component(), and Screen_SDL.
Referenced by Button_Kill(), Button_Load_or_Save(), Button_Page(), Button_Palette(), Button_Redo(), Button_Secondary_palette(), Button_Skins(), Button_Undo(), Error_function(), Get_colors_from_brush(), Init_mode_video(), Init_preview_24b(), Load_BMP(), Load_C64(), Load_GIF(), Load_image(), Load_IMG(), Load_KCF(), Load_LBM(), Load_NEO(), Load_PAL(), Load_PC1(), Load_PCX(), Load_PI1(), Load_picture(), Load_PKM(), Load_PNG(), Load_SCx(), Load_SDL_Image(), Remap_fileselector(), and Save_picture().
void Palette_256_to_64 (T_Palette palette)
Referenced by Load_LBM(), Save_PKM(), and Save_SCx().
void Palette_64_to_256 (T_Palette palette)
Referenced by Load_LBM(), Load_PAL(), Load_PKM(), and Load_SCx().
void Hide_current_image (byte color)
References T_Page::Image, Main_backups, Main_current_layer, Main_image_height, Main_image_width, and T_List_of_pages::Pages.
Referenced by Button_Clear(), and Button_Clear_with_backcolor().
void Hide_current_image_with_stencil (byte color, byte * stencil)
References byte, T_Page::Image, Main_backups, Main_current_layer, Main_image_height, Main_image_width, and T_List_of_pages::Pages.
Referenced by Button_Clear(), and Button_Clear_with_backcolor().
void Slider_timer (byte speed)
References byte, Get_input(), and Mouse_K.
Referenced by Window_get_button_shortcut(), and Window_get_clicked_button().
dword Round_div (dword numerator, dword divisor)
Referenced by Curve_4_points_0_5(), Effect_smooth(), Reduce_palette(), Window_draw_slider(), and Window_get_clicked_button().
word Count_used_colors (dword * usage)
Count used palette indexes in the whole picture Return the total number of different colors Fill in "usage" with the count for each color.
References Main_image_height, Main_image_width, Main_screen, and word.
Referenced by Button_Stats(), Find_recog(), Save_C64(), Save_C64_multi(), Save_CEL(), Save_KCF(), and Update_color_count().
word Count_used_colors_area (dword * usage, word start_x, word start_y, word width, word height)
Same as Count_used_colors, but for a given rectangle in the picture only.
Used bu the C64 block constraint checker.
References Main_image_width, Main_screen, and word.
Referenced by Save_C64_hires(), and Save_C64_multi().
word Count_used_colors_screen_area (dword * usage, word start_x, word start_y, word width, word height)
Same as Count_used_colors, but use a block screen memory instead of picture data.
Used to count colors in the loading screen.
References Pixel_height, Pixel_width, Screen_pixels, Screen_width, and word.
Referenced by Load_image().
void Pixel_in_brush (word x, word y, byte color)
References Brush, and Brush_width.
Referenced by Button_Sieve_menu(), Capture_brush_with_lasso(), Nibble_brush(), Outline_brush(), Pixel_figure_in_brush(), and Pixel_load_in_brush().
byte Read_pixel_from_spare_screen (word x, word y)
References Spare_image_width, and Spare_screen.
Referenced by Display_pixel(), and Remap_spare().
byte Read_pixel_from_backup_screen (word x, word y)
References Main_image_width, and Screen_backup.
byte Read_pixel_from_feedback_screen (word x, word y)
References FX_feedback_screen, and Main_image_width.
Referenced by Effect_additive_colorize(), Effect_interpolated_colorize(), Effect_quick_shade(), Effect_shade(), Effect_smooth(), and Effect_substractive_colorize().
byte Read_pixel_from_brush (word x, word y)
References Brush, and Brush_width.
Referenced by Button_Sieve_menu(), Capture_brush_with_lasso(), Compute_quad_texture(), Display_paintbrush(), Draw_brush_linear_distort(), Draw_quad_texture_preview(), Effect_tiling(), Get_colors_from_brush(), Remap_brush(), Save_image(), Save_PNG(), and Stretch_brush_preview().
void Ellipse_compute_limites (short horizontal_radius, short vertical_radius)
References Ellipse_horizontal_radius_squared, Ellipse_limit, Ellipse_vertical_radius_squared, and qword.
Referenced by Draw_empty_ellipse_general(), Draw_filled_ellipse(), and Draw_grad_ellipse().
byte Pixel_in_ellipse (void)
References Ellipse_cursor_X, Ellipse_cursor_Y, Ellipse_horizontal_radius_squared, Ellipse_limit, Ellipse_vertical_radius_squared, and qword.
Referenced by Draw_empty_ellipse_general(), Draw_filled_ellipse(), and Draw_grad_ellipse().
byte Pixel_in_circle (void)
References Circle_cursor_X, Circle_cursor_Y, and Circle_limit.
Referenced by Draw_empty_circle_general(), Draw_filled_circle(), and Draw_grad_circle().
void Init_chrono (dword delay)
References Timer_delay, and Timer_start.
Referenced by Button_Load_or_Save().
void Check_timer (void)
References Timer_delay, Timer_start, and Timer_state.
Referenced by Button_Load_or_Save().
void Replace_a_color (byte old_color, byte New_color)
References Main_image_height, Main_image_width, Pixel_in_current_screen(), Read_pixel_from_current_layer(), Update_rect(), and word.
Referenced by Replace().
void Replace_colors_within_limits (byte * replace_table)
References byte, T_Page::Image, Limit_bottom, Limit_left, Limit_right, Limit_top, Main_backups, Main_current_layer, Main_image_width, and T_List_of_pages::Pages.
Referenced by Fill_general().
byte Effect_interpolated_colorize (word x, word y, byte color)
References Best_color(), byte, Factors_inv_table, Factors_table, Main_palette, and Read_pixel_from_feedback_screen().
Referenced by Button_Colorize_mode(), and Transparency_set().
byte Effect_additive_colorize (word x, word y, byte color)
References Best_color(), byte, Main_palette, and Read_pixel_from_feedback_screen().
Referenced by Button_Colorize_mode(), and Transparency_set().
byte Effect_substractive_colorize (word x, word y, byte color)
References Best_color(), byte, Main_palette, and Read_pixel_from_feedback_screen().
Referenced by Button_Colorize_mode(), and Transparency_set().
byte Effect_sieve (word x, word y)
References Sieve, Sieve_height, and Sieve_width.
Referenced by Display_pixel().
void Flip_Y_lowlevel (byte * src, short width, short height)
Inverts a pixel buffer, according to a horizontal axis.
Parameters:
src Pointer to the pixel buffer to process.
width Width of the buffer.
height Height of the buffer.
References byte, and word.
Referenced by Button_Brush_FX(), Button_Transform_menu(), Main_handler(), and Rotate_180_deg_lowlevel().
void Flip_X_lowlevel (byte * src, short width, short height)
Inverts a pixel buffer, according to a vertical axis.
Parameters:
src Pointer to the pixel buffer to process.
width Width of the buffer.
height Height of the buffer.
References byte, and word.
Referenced by Button_Brush_FX(), Button_Transform_menu(), Main_handler(), and Rotate_180_deg_lowlevel().
void Rotate_90_deg_lowlevel (byte * source, byte * dest, short width, short height)
Rotate a pixel buffer by 90 degrees, clockwise.
Parameters:
source Source pixel buffer.
dest Destination pixel buffer.
width Width of the original buffer (height of the destination one).
height Height of the original buffer (width of the destination one).
References word.
Referenced by Button_Transform_menu(), and Rotate_90_deg().
void Rotate_270_deg_lowlevel (byte * source, byte * dest, short width, short height)
Rotate a pixel buffer by 90 degrees, counter-clockwise.
Parameters:
source Source pixel buffer.
dest Destination pixel buffer.
width Width of the original buffer (height of the destination one).
height Height of the original buffer (width of the destination one).
References word.
Referenced by Button_Transform_menu().
void Rotate_180_deg_lowlevel (byte * src, short width, short height)
Rotate a pixel buffer by 180 degrees.
Parameters:
src The pixel buffer (source and destination).
width Width of the buffer.
height Height of the buffer.
References byte, Flip_X_lowlevel(), Flip_Y_lowlevel(), and word.
Referenced by Button_Brush_FX(), Button_Transform_menu(), and Main_handler().
void Rescale (byte * src_buffer, short src_width, short src_height, byte * dst_buffer, short dst_width, short dst_height, short x_flipped, short y_flipped)
Copies an image to another, rescaling it and optionally flipping it.
Parameters:
src_buffer Original image (address of first byte)
src_width Original image's width in pixels
src_height Original image's height in pixels
dst_buffer Destination image (address of first byte)
dst_width Destination image's width in pixels
dst_height Destination image's height in pixels
x_flipped Boolean, true to flip the image horizontally
y_flipped Boolean, true to flip the image vertically
Referenced by Button_Transform_menu(), Store_brush(), and Stretch_brush().
void Zoom_a_line (byte * original_line, byte * zoomed_line, word factor, word width)
References byte, and word.
Referenced by Clear_brush_scaled_double(), Clear_brush_scaled_quad(), Clear_brush_scaled_simple(), Clear_brush_scaled_tall(), Clear_brush_scaled_tall2(), Clear_brush_scaled_triple(), Clear_brush_scaled_wide(), Clear_brush_scaled_wide2(), Display_brush_color_zoom_double(), Display_brush_color_zoom_quad(), Display_brush_color_zoom_simple(), Display_brush_color_zoom_tall(), Display_brush_color_zoom_tall2(), Display_brush_color_zoom_triple(), Display_brush_color_zoom_wide(), Display_brush_color_zoom_wide2(), Display_brush_mono_zoom_double(), Display_brush_mono_zoom_quad(), Display_brush_mono_zoom_simple(), Display_brush_mono_zoom_tall(), Display_brush_mono_zoom_tall2(), Display_brush_mono_zoom_triple(), Display_brush_mono_zoom_wide(), Display_brush_mono_zoom_wide2(), Display_part_of_screen_scaled_double(), Display_part_of_screen_scaled_quad(), Display_part_of_screen_scaled_simple(), Display_part_of_screen_scaled_tall(), Display_part_of_screen_scaled_tall2(), Display_part_of_screen_scaled_triple(), Display_part_of_screen_scaled_wide(), and Display_part_of_screen_scaled_wide2().
void Copy_part_of_image_to_another (byte * source, word source_x, word source_y, word width, word height, word source_width, byte * dest, word dest_x, word dest_y, word destination_width)
References byte.
Referenced by Copy_image_only(), Display_paintbrush(), Fill_general(), Nibble_brush(), Outline_brush(), Resize_image(), and Store_brush().
unsigned long Memory_free (void)
Referenced by Button_Stats().
void Num2str (dword number, char * str, byte nb_char)
Referenced by Brush_12_5(), Button_Airbrush_menu(), Button_Colorize_menu(), Button_Gradients(), Button_Grid_menu(), Button_Palette(), Button_Quick_shade_menu(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Smooth_menu(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Circle_12_5(), Colorpicker_1_1(), Colorpicker_2_1(), Display_coords_rel_or_abs(), Display_menu(), Display_modes_list(), Display_selected_cell_color(), Display_selected_color(), Format_componant(), Grad_circle_12_6(), Grad_rectangle_12_5(), Init_preview(), Menu_shade(), Print_coordinates(), Rectangle_12_5(), Reduce_palette(), Refresh_airbrush_settings(), Rotate_brush_0_5(), Rotate_brush_1_5(), Settings_display_config(), Stretch_brush_0_7(), Stretch_brush_1_7(), and Update_color_count().
short Round (float value)
Referenced by Compute_3_point_curve(), Compute_quad_texture(), Compute_separator_data(), Distance(), Draw_curve_general(), Draw_quad_texture_preview(), Rotate_brush_0_5(), and Transform_point().
short Round_div_max (short numerator, short divisor)
Referenced by Init_preview().
int Min (int a, int b)
Referenced by Button_Text(), Compute_quad_texture(), Copy_image_only(), Cursor_displace(), Draw_curve_general(), Draw_preset_sieve_patterns(), Draw_quad_texture_preview(), Fill(), Fill_general(), Flush_update(), Grad_rectangle_0_5(), Grad_rectangle_0_9(), Grad_rectangle_12_7(), Init_mode_video(), Load_GIF(), Load_PNG(), Resize_image(), Rotate_brush(), Rotate_brush_preview(), Stretch_brush_preview(), Update_part_of_screen(), and Window_redraw_list().
int Max (int a, int b)
Referenced by Cursor_displace(), Display_cursor(), Distort_brush(), Draw_curve_general(), Draw_quad_texture_preview(), Grad_rectangle_0_5(), Grad_rectangle_0_9(), Grad_rectangle_12_7(), Hide_cursor(), Rotate_brush(), Rotate_brush_preview(), and Stretch_brush_preview().
char* Mode_label (int mode)
References Height, Video_mode, and Width.
Referenced by Convert_videomode_arg(), Display_syntax(), and Save_INI().
int Convert_videomode_arg (const char * argument)
References Mode_label(), Nb_video_modes, and Video_mode.
Referenced by Analyze_command_line(), and Load_INI().
Variable Documentation
byte Timer_state
Referenced by Button_Load_or_Save(), and Check_timer().
dword Timer_delay
Referenced by Check_timer(), and Init_chrono().
dword Timer_start
Referenced by Check_timer(), and Init_chrono().
byte New_preview_is_needed
Referenced by Button_Load_or_Save(), and Scroll_fileselector().