GrafX2: miscfileformats.c File Reference
miscfileformats.c File Reference
Formats that aren't fully saving, either because of palette restrictions or other things.
#include <stdlib.h>
#include <string.h>
#include "engine.h"
#include "errors.h"
#include "global.h"
#include "io.h"
#include "libraw2crtc.h"
#include "limits.h"
#include "loadsave.h"
#include "misc.h"
#include "sdlscreen.h"
#include "struct.h"
#include "windows.h"
Data Structures
struct T_PKM_Header
struct T_CEL_Header1
struct T_CEL_Header2
struct T_KCF_Header
Functions
void Test_PAL (T_IO_Context *context)
void Load_PAL (T_IO_Context *context)
void Save_PAL (T_IO_Context *context)
void Test_PKM (T_IO_Context *context)
void Load_PKM (T_IO_Context *context)
void Find_recog (byte *recog1, byte *recog2)
void Save_PKM (T_IO_Context *context)
void Test_CEL (T_IO_Context *context)
void Load_CEL (T_IO_Context *context)
void Save_CEL (T_IO_Context *context)
void Test_KCF (T_IO_Context *context)
void Load_KCF (T_IO_Context *context)
void Save_KCF (T_IO_Context *context)
void PI1_8b_to_16p (byte *src, byte *dest)
void PI1_16p_to_8b (byte *src, byte *dest)
void PI1_decode_palette (byte *src, byte *palette)
void PI1_code_palette (byte *palette, byte *dest)
void Test_PI1 (T_IO_Context *context)
void Load_PI1 (T_IO_Context *context)
void Save_PI1 (T_IO_Context *context)
void PC1_uncompress_packbits (byte *src, byte *dest)
void PC1_compress_packbits (byte *src, byte *dest, int source_size, int *dest_size)
void PC1_4bp_to_1line (byte *src0, byte *src1, byte *src2, byte *src3, byte *dest)
void PC1_1line_to_4bp (byte *src, byte *dst0, byte *dst1, byte *dst2, byte *dst3)
void Test_PC1 (T_IO_Context *context)
void Load_PC1 (T_IO_Context *context)
void Save_PC1 (T_IO_Context *context)
void Test_NEO (T_IO_Context *context)
void Load_NEO (T_IO_Context *context)
void Save_NEO (T_IO_Context *context)
void Test_C64 (T_IO_Context *context)
void Load_C64_hires (T_IO_Context *context, byte *bitmap, byte *colors)
void Load_C64_multi (T_IO_Context *context, byte *bitmap, byte *colors, byte *nybble, byte background)
void Load_C64 (T_IO_Context *context)
int Save_C64_window (byte *saveWhat, byte *loadAddr)
int Save_C64_hires (T_IO_Context *context, char *filename, byte saveWhat, byte loadAddr)
int Save_C64_multi (T_IO_Context *context, char *filename, byte saveWhat, byte loadAddr)
void Save_C64 (T_IO_Context *context)
void Test_SCR (T_IO_Context *context)
void Load_SCR (T_IO_Context *context)
void Save_SCR (T_IO_Context *context)
Detailed Description
Formats that aren't fully saving, either because of palette restrictions or other things.
Function Documentation
void Test_PAL (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), and MAX_PATH_CHARACTERS.
void Load_PAL (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_64_to_256(), Palette_loaded(), and Read_bytes().
void Save_PAL (T_IO_Context * context)
< full filename
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, and T_IO_Context::Palette.
void Test_PKM (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), T_PKM_Header::Height, T_PKM_Header::Ident, T_PKM_Header::Jump, MAX_PATH_CHARACTERS, T_PKM_Header::Method, T_PKM_Header::Palette, Read_byte(), Read_bytes(), Read_word_le(), T_PKM_Header::Recog1, T_PKM_Header::Recog2, and T_PKM_Header::Width.
void Load_PKM (T_IO_Context * context)
References Back_color, byte, T_IO_Context::Comment, COMMENT_SIZE, dword, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_PKM, Get_full_filename(), T_IO_Context::Height, T_PKM_Header::Height, T_PKM_Header::Ident, T_PKM_Header::Jump, MAX_PATH_CHARACTERS, T_PKM_Header::Method, Original_screen_X, Original_screen_Y, T_IO_Context::Palette, T_PKM_Header::Palette, Palette_64_to_256(), Palette_loaded(), PIXEL_SIMPLE, Pre_load(), Read_byte(), Read_bytes(), Read_word_be(), Read_word_le(), T_PKM_Header::Recog1, T_PKM_Header::Recog2, Set_pixel(), T_IO_Context::Width, T_PKM_Header::Width, and word.
void Find_recog (byte * recog1, byte * recog2)
References byte, Count_used_colors(), dword, and word.
Referenced by Save_PKM().
void Save_PKM (T_IO_Context * context)
References Back_color, byte, T_IO_Context::Comment, dword, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Find_recog(), Get_full_filename(), Get_pixel(), T_IO_Context::Height, T_PKM_Header::Height, T_PKM_Header::Ident, Init_write_buffer(), T_PKM_Header::Jump, MAX_PATH_CHARACTERS, T_PKM_Header::Method, T_IO_Context::Palette, T_PKM_Header::Palette, Palette_256_to_64(), T_PKM_Header::Recog1, T_PKM_Header::Recog2, Screen_height, Screen_width, T_IO_Context::Width, T_PKM_Header::Width, word, Write_byte(), Write_bytes(), Write_one_byte(), and Write_word_le().
void Test_CEL (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, File_length(), T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, Get_full_filename(), T_CEL_Header2::Height, T_CEL_Header1::Height, T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, Read_byte(), Read_bytes(), Read_word_le(), T_CEL_Header2::Signature, T_CEL_Header2::Width, T_CEL_Header1::Width, T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Load_CEL (T_IO_Context * context)
References byte, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, FORMAT_CEL, Get_full_filename(), Height, T_CEL_Header2::Height, T_IO_Context::Height, T_CEL_Header1::Height, T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, Original_screen_X, Original_screen_Y, PIXEL_SIMPLE, Pre_load(), Read_byte(), Read_bytes(), Read_word_le(), Set_pixel(), T_CEL_Header2::Signature, T_CEL_Header2::Width, T_IO_Context::Width, T_CEL_Header1::Width, T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Save_CEL (T_IO_Context * context)
References byte, Count_used_colors(), dword, End_write(), T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, Get_full_filename(), Get_pixel(), T_CEL_Header2::Height, T_IO_Context::Height, T_CEL_Header1::Height, Init_write_buffer(), T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, T_CEL_Header2::Signature, T_CEL_Header2::Width, T_IO_Context::Width, T_CEL_Header1::Width, Write_byte(), Write_bytes(), Write_one_byte(), Write_word_le(), T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Test_KCF (T_IO_Context * context)
References T_KCF_Header::color, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, Get_full_filename(), T_CEL_Header2::Height, T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, T_KCF_Header::Palette, Read_byte(), Read_bytes(), Read_word_le(), T_CEL_Header2::Signature, T_CEL_Header2::Width, T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Load_KCF (T_IO_Context * context)
References byte, T_Config::Clear_palette, T_KCF_Header::color, Config, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, Get_full_filename(), T_CEL_Header2::Height, T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, T_IO_Context::Palette, T_KCF_Header::Palette, Palette_loaded(), Read_byte(), Read_bytes(), Read_word_le(), T_CEL_Header2::Signature, T_CEL_Header2::Width, T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void Save_KCF (T_IO_Context * context)
References byte, T_KCF_Header::color, Count_used_colors(), dword, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, T_CEL_Header2::Filler1, T_CEL_Header2::Filler2, Get_full_filename(), T_CEL_Header2::Height, T_CEL_Header2::Kind, MAX_PATH_CHARACTERS, T_CEL_Header2::Nb_bits, T_IO_Context::Palette, T_KCF_Header::Palette, T_CEL_Header2::Signature, T_CEL_Header2::Width, Write_byte(), Write_bytes(), Write_word_le(), T_CEL_Header2::X_offset, and T_CEL_Header2::Y_offset.
void PI1_8b_to_16p (byte * src, byte * dest)
References word.
Referenced by Load_NEO(), and Load_PI1().
void PI1_16p_to_8b (byte * src, byte * dest)
References word.
Referenced by Save_NEO(), and Save_PI1().
void PI1_decode_palette (byte * src, byte * palette)
References word.
Referenced by Load_NEO(), Load_PC1(), and Load_PI1().
void PI1_code_palette (byte * palette, byte * dest)
References word.
Referenced by Save_NEO(), Save_PC1(), and Save_PI1().
void Test_PI1 (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, Read_word_le(), and word.
void Load_PI1 (T_IO_Context * context)
References byte, T_Config::Clear_palette, Config, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_PI1, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_loaded(), PI1_8b_to_16p(), PI1_decode_palette(), PIXEL_SIMPLE, Pre_load(), Read_bytes(), Set_pixel(), T_IO_Context::Width, and word.
void Save_PI1 (T_IO_Context * context)
References byte, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), Get_pixel(), Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, PI1_16p_to_8b(), PI1_code_palette(), Width, and Write_bytes().
void PC1_uncompress_packbits (byte * src, byte * dest)
References File_error, and id.
Referenced by Load_PC1().
void PC1_compress_packbits (byte * src, byte * dest, int source_size, int * dest_size)
References id.
Referenced by Save_PC1().
void PC1_4bp_to_1line (byte * src0, byte * src1, byte * src2, byte * src3, byte * dest)
References byte.
Referenced by Load_PC1().
void PC1_1line_to_4bp (byte * src, byte * dst0, byte * dst1, byte * dst2, byte * dst3)
References byte.
Referenced by Save_PC1().
void Test_PC1 (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, Read_word_le(), and word.
void Load_PC1 (T_IO_Context * context)
References byte, T_Config::Clear_palette, Config, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_PC1, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_loaded(), PC1_4bp_to_1line(), PC1_uncompress_packbits(), PI1_decode_palette(), PIXEL_SIMPLE, Pre_load(), Read_bytes(), Set_pixel(), T_IO_Context::Width, and word.
void Save_PC1 (T_IO_Context * context)
References byte, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), Get_pixel(), Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, PC1_1line_to_4bp(), PC1_compress_packbits(), PI1_code_palette(), Width, and Write_bytes().
void Test_NEO (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), MAX_PATH_CHARACTERS, Read_word_le(), and word.
void Load_NEO (T_IO_Context * context)
References byte, T_Config::Clear_palette, Config, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_NEO, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_loaded(), PI1_8b_to_16p(), PI1_decode_palette(), PIXEL_SIMPLE, Pre_load(), Read_bytes(), Set_pixel(), T_IO_Context::Width, and word.
void Save_NEO (T_IO_Context * context)
References byte, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), Get_pixel(), Height, MAX_PATH_CHARACTERS, T_IO_Context::Palette, PI1_16p_to_8b(), PI1_code_palette(), Width, and Write_bytes().
void Test_C64 (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, Get_full_filename(), and MAX_PATH_CHARACTERS.
void Load_C64_hires (T_IO_Context * context, byte * bitmap, byte * colors)
References Set_pixel().
Referenced by Load_C64().
void Load_C64_multi (T_IO_Context * context, byte * bitmap, byte * colors, byte * nybble, byte background)
References Set_pixel().
Referenced by Load_C64().
void Load_C64 (T_IO_Context * context)
References byte, T_IO_Context::Comment, T_IO_Context::File_directory, File_error, File_length_file(), T_IO_Context::File_name, FORMAT_C64, Get_full_filename(), T_IO_Context::Height, Load_C64_hires(), Load_C64_multi(), MAX_PATH_CHARACTERS, T_IO_Context::Palette, Palette_loaded(), PIXEL_WIDE, Pre_load(), T_IO_Context::Ratio, Read_byte(), Read_bytes(), T_IO_Context::Width, and word.
int Save_C64_window (byte * saveWhat, byte * loadAddr)
References Close_window(), Display_cursor(), LEFT_SIDE, MC_Dark, MC_Light, Open_window(), Print_in_window(), Update_window_area, Window_attribute2, Window_clicked_button(), Window_dropdown_add_item(), Window_dropdown_clear_items(), Window_height, Window_set_dropdown_button(), Window_set_normal_button(), and Window_width.
Referenced by Save_C64().
int Save_C64_hires (T_IO_Context * context, char * filename, byte saveWhat, byte loadAddr)
References byte, Count_used_colors_area(), dword, File_error, Get_pixel(), Warning_message(), word, Write_byte(), and Write_bytes().
Referenced by Save_C64().
int Save_C64_multi (T_IO_Context * context, char * filename, byte saveWhat, byte loadAddr)
References byte, Count_used_colors(), Count_used_colors_area(), dword, File_error, Get_pixel(), Warning_message(), word, Write_byte(), and Write_bytes().
Referenced by Save_C64().
void Save_C64 (T_IO_Context * context)
References byte, Count_used_colors(), dword, T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, Save_C64_hires(), Save_C64_multi(), Save_C64_window(), Warning_message(), and T_IO_Context::Width.
void Test_SCR (T_IO_Context * context)
void Load_SCR (T_IO_Context * context)
void Save_SCR (T_IO_Context * context)
References T_IO_Context::File_directory, File_error, T_IO_Context::File_name, Get_full_filename(), T_IO_Context::Height, MAX_PATH_CHARACTERS, Pixel_ratio, PIXEL_TALL, PIXEL_TALL2, PIXEL_WIDE, PIXEL_WIDE2, raw2crtc(), T_IO_Context::Width, and Write_bytes().