GrafX2: moteur.h File Reference
moteur.h File Reference
Functions
void Gestion_principale (void)
void Tracer_cadre_de_bouton_du_menu (byte Numero, byte Enfonce)
void Desenclencher_bouton (int Numero)
void Enclencher_bouton (int Numero, byte Click)
void Annuler_les_effets (void)
void Restaurer_les_effets (void)
void Ouvrir_fenetre (word Largeur, word Hauteur, char *Titre)
void Fermer_fenetre (void)
void Ouvrir_popup (word Pos_X, word Pos_Y, word Largeur, word Hauteur)
void Fermer_popup (void)
void Fenetre_Dessiner_bouton_normal (word Pos_X, word Pos_Y, word Largeur, word Hauteur, char *Titre, byte Lettre_soulignee, byte Clickable)
void Fenetre_Enfoncer_bouton_normal (word Pos_X, word Pos_Y, word Largeur, word Hauteur)
void Fenetre_Desenfoncer_bouton_normal (word Pos_X, word Pos_Y, word Largeur, word Hauteur)
void Fenetre_Dessiner_bouton_palette (word Pos_X, word Pos_Y)
void Calculer_hauteur_curseur_jauge (struct Fenetre_Bouton_scroller *Enreg)
void Fenetre_Dessiner_jauge (struct Fenetre_Bouton_scroller *Enreg)
void Fenetre_Dessiner_bouton_scroller (struct Fenetre_Bouton_scroller *Enreg)
void Fenetre_Contenu_bouton_saisie (struct Fenetre_Bouton_special *Enreg, char *Contenu)
void Fenetre_Effacer_bouton_saisie (struct Fenetre_Bouton_special *Enreg)
void Fenetre_Dessiner_bouton_saisie (word Pos_X, word Pos_Y, word Largeur_en_caracteres)
struct Fenetre_Bouton_normal * Fenetre_Definir_bouton_normal (word Pos_X, word Pos_Y, word Largeur, word Hauteur, char *Titre, byte Lettre_soulignee, byte Clickable, word Raccourci)
struct Fenetre_Bouton_normal * Fenetre_Definir_bouton_repetable (word Pos_X, word Pos_Y, word Largeur, word Hauteur, char *Titre, byte Lettre_soulignee, byte Clickable, word Raccourci)
struct Fenetre_Bouton_palette * Fenetre_Definir_bouton_palette (word Pos_X, word Pos_Y)
void Fenetre_Effacer_tags (void)
void Tagger_intervalle_palette (byte Debut, byte Fin)
struct Fenetre_Bouton_scroller * Fenetre_Definir_bouton_scroller (word Pos_X, word Pos_Y, word Hauteur, word Nb_elements, word Nb_elements_visibles, word Position_initiale)
struct Fenetre_Bouton_special * Fenetre_Definir_bouton_special (word Pos_X, word Pos_Y, word Largeur, word Hauteur)
struct Fenetre_Bouton_special * Fenetre_Definir_bouton_saisie (word Pos_X, word Pos_Y, word Largeur_en_caracteres)
struct Fenetre_Bouton_dropdown * Fenetre_Definir_bouton_dropdown (word Pos_X, word Pos_Y, word Largeur, word Hauteur, word Largeur_choix, char *Libelle, byte Affiche_choix, byte Affiche_centre, byte Affiche_fleche, byte Bouton_actif)
void Fenetre_Dropdown_choix (struct Fenetre_Bouton_dropdown *Dropdown, word Numero, const char *Libelle)
void Fenetre_Dropdown_vider_choix (struct Fenetre_Bouton_dropdown *Dropdown)
byte Fenetre_click_dans_zone (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y)
short Attendre_click_dans_palette (struct Fenetre_Bouton_palette *Enreg)
void Recuperer_couleur_derriere_fenetre (byte *Couleur, byte *Click)
short Fenetre_Bouton_clicke (void)
int Numero_bouton_sous_souris (void)
short Fenetre_Numero_bouton_clicke (void)
void Remappe_fond_fenetres (byte *Table_de_conversion, int Min_Y, int Max_Y)
void Pixel_fond (int Pos_X, int Pos_Y, byte Couleur)
Function Documentation
void Gestion_principale (void)
References A_DROITE, A_GAUCHE, Afficher_curseur(), Afficher_ecran(), Afficher_menu(), Block, BOUTON_CHOIX_COL, Bouton_Colorize_Menu(), Bouton_Colorize_Mode(), BOUTON_DESSIN, BOUTON_EFFETS, Bouton_Mask_Menu(), Bouton_Mask_Mode(), Bouton_Menu_Grille(), Bouton_Menu_Stencil(), Bouton_Quick_shade_Menu(), Bouton_Quick_shade_Mode(), Bouton_Quit(), Bouton_Shade_Menu(), Bouton_Shade_Mode(), Bouton_Smear_Mode(), Bouton_Smooth_Menu(), Bouton_Smooth_Mode(), Bouton_Snap_Mode(), Bouton_Stencil_Mode(), Bouton_Tiling_Menu(), Bouton_Tiling_Mode(), Bouton_Trame_Menu(), Bouton_Trame_Mode(), Brosse_Decalage_X, Brosse_Decalage_Y, Brosse_Hauteur, Brosse_Largeur, Cacher_curseur, Changer_la_forme_du_pinceau(), CM_Clair, Colorize_Mode, Couleur_debut_palette, Couleur_palette(), Curseur_dans_menu, Curseur_dans_menu_precedent, Demarrer_pile_operation(), Deplacer_Split(), Effacer_curseur, Enclencher_bouton(), Est_Raccourci(), Exclude_color, Flip_X_LOWLEVEL(), Flip_Y_LOWLEVEL(), FORME_PINCEAU_ROND, Get_colors_from_brush(), Get_input(), Grossir_pinceau(), S_Mode_video::Hauteur, Hauteur_ecran, Initialiser_mode_video(), Inverser_trame(), S_Mode_video::Largeur, Largeur_ecran, Load_picture(), Loupe_Hauteur, Loupe_Largeur, Loupe_Mode, Mask_Mode, Menu_Facteur_X, Menu_Facteur_Y, Menu_Ordonnee, Menu_Ordonnee_Texte, Menu_Tag_couleurs(), Menu_visible, Message_Non_disponible(), Mode_video, Modifier_pinceau(), Mouse_K, Mouse_K_Unique, Mouse_X, Mouse_Y, NB_BOUTONS, NB_TOUCHES_SPECIALES, Nibble_brush(), Numero_bouton_sous_souris(), Old_MX, Old_MY, Operation, OPERATION_DESSIN_CONTINU, Operation_en_cours, OPERATION_ETIRER_BROSSE, OPERATION_PIPETTE, OPERATION_REMPLACER, Operation_Taille_pile, OPERATION_TOURNER_BROSSE, Outline_brush(), Pinceau_Forme, Pixel_height, Pixel_width, Principal_Palette, Principal_Split, Principal_X_Zoom, Print_dans_menu(), Quick_shade_Mode, Quit_demande, Remap_brosse(), Resize_Hauteur, Resize_Largeur, Retrecir_pinceau(), Rotate_180_deg_LOWLEVEL(), Rotate_90_deg(), Save_picture(), Scroller_ecran(), Scroller_loupe(), Shade_Mode, Smear_Mode, Smooth_Mode, Snap_Mode, Sortir_du_programme, SPECIAL_BOTTOM_LEFT_ATTACHMENT, SPECIAL_BOTTOM_RIGHT_ATTACHMENT, SPECIAL_CENTER_ATTACHMENT, SPECIAL_CLICK_RIGHT, SPECIAL_COLORIZE_MENU, SPECIAL_COLORIZE_MODE, SPECIAL_DESSIN_CONTINU, SPECIAL_DISTORT, SPECIAL_EXCLUDE_COLORS_MENU, SPECIAL_FLIP_X, SPECIAL_FLIP_Y, SPECIAL_GET_BRUSH_COLORS, SPECIAL_GRID_MENU, SPECIAL_GRID_MODE, SPECIAL_GROSSIR_PINCEAU, SPECIAL_INVERT_SIEVE, SPECIAL_LOAD_BRUSH, SPECIAL_MASK_MENU, SPECIAL_MASK_MODE, Special_Next_backcolor(), SPECIAL_NEXT_BACKCOLOR, Special_Next_forecolor(), SPECIAL_NEXT_FORECOLOR, SPECIAL_NEXT_USER_BACKCOLOR, SPECIAL_NEXT_USER_FORECOLOR, SPECIAL_NIBBLE, SPECIAL_OUTLINE, SPECIAL_PINCEAU_POINT, Special_Previous_backcolor(), SPECIAL_PREVIOUS_BACKCOLOR, Special_Previous_forecolor(), SPECIAL_PREVIOUS_FORECOLOR, SPECIAL_PREVIOUS_USER_BACKCOLOR, SPECIAL_PREVIOUS_USER_FORECOLOR, SPECIAL_QUICK_SHADE_MENU, SPECIAL_QUICK_SHADE_MODE, SPECIAL_RECOLORIZE_BRUSH, SPECIAL_RETRECIR_PINCEAU, SPECIAL_ROTATE_180, SPECIAL_ROTATE_90, SPECIAL_ROTATE_ANY_ANGLE, SPECIAL_SAVE_BRUSH, SPECIAL_SCROLL_DOWN, SPECIAL_SCROLL_DOWN_FAST, SPECIAL_SCROLL_DOWN_SLOW, SPECIAL_SCROLL_LEFT, SPECIAL_SCROLL_LEFT_FAST, SPECIAL_SCROLL_LEFT_SLOW, SPECIAL_SCROLL_RIGHT, SPECIAL_SCROLL_RIGHT_FAST, SPECIAL_SCROLL_RIGHT_SLOW, SPECIAL_SCROLL_UP, SPECIAL_SCROLL_UP_FAST, SPECIAL_SCROLL_UP_SLOW, SPECIAL_SHADE_MENU, SPECIAL_SHADE_MODE, SPECIAL_SHOW_HIDE_CURSOR, SPECIAL_SIEVE_MENU, SPECIAL_SIEVE_MODE, SPECIAL_SMEAR_MODE, SPECIAL_SMOOTH_MENU, SPECIAL_SMOOTH_MODE, SPECIAL_STENCIL_MENU, SPECIAL_STENCIL_MODE, SPECIAL_STRETCH, SPECIAL_TILING_MENU, SPECIAL_TILING_MODE, SPECIAL_TOP_LEFT_ATTACHMENT, SPECIAL_TOP_RIGHT_ATTACHMENT, SPECIAL_ZOOM_IN, SPECIAL_ZOOM_OUT, Stencil_Mode, Tiling_Mode, TITRE_BOUTON, Touche, Tracer_cadre_de_bouton_du_menu(), Trame_Mode, UpdateRect(), Wait_VBL(), and Zoom().
Referenced by main().
void Tracer_cadre_de_bouton_du_menu (byte Numero, byte Enfonce)
References BLOCK_MENU, Bouton, CM_Blanc, CM_Clair, CM_Fonce, CM_Noir, Forme, FORME_BOUTON_RECTANGLE, FORME_BOUTON_SANS_CADRE, FORME_BOUTON_TRIANGLE_BAS_DROITE, FORME_BOUTON_TRIANGLE_HAUT_GAUCHE, Menu_Facteur_X, Menu_Facteur_Y, Menu_Ordonnee, Menu_visible, Pixel_dans_menu, and UpdateRect().
Referenced by Bouton_Kill(), Bouton_Page(), Bouton_Redo(), Bouton_Reload(), Bouton_Undo(), Desenclencher_bouton(), Enclencher_bouton(), Gestion_principale(), and Load_picture().
void Desenclencher_bouton (int Numero)
References Bouton, BOUTON_RELACHE, Enfonce, and Tracer_cadre_de_bouton_du_menu().
Referenced by Bouton_Autosave(), Bouton_Brosse(), Bouton_Brosse_monochrome(), Bouton_Brush_FX(), Bouton_Cacher_menu(), Bouton_Clear(), Bouton_Clear_colore(), Bouton_Copy_page(), Bouton_Degrades(), Bouton_Effets(), Bouton_Inverser_foreback(), Bouton_Kill(), Bouton_Lasso(), Bouton_Load_ou_Save(), Bouton_Loupe(), Bouton_Menu_Loupe(), Bouton_Menu_pinceaux(), Bouton_Page(), Bouton_Pal_left(), Bouton_Pal_left_fast(), Bouton_Pal_right(), Bouton_Pal_right_fast(), Bouton_Palette(), Bouton_Palette_secondaire(), Bouton_Pipette(), Bouton_Quit(), Bouton_Redo(), Bouton_Reload(), Bouton_Resol(), Bouton_Restaurer_brosse(), Bouton_Safety_resol(), Bouton_Settings(), Bouton_Stats(), Bouton_Texte(), Bouton_Undo(), Enclencher_bouton(), Fenetre_aide(), and Pipette_0_1().
void Enclencher_bouton (int Numero, byte Click)
References A_DROITE, Afficher_curseur(), Afficher_sprite_dans_menu(), Attendre_fin_de_click(), Bouton, BOUTON_CERCLES, BOUTON_ENFONCE, BOUTON_FILLCERC, BOUTON_FLOODFILL, BOUTON_LOUPE, BOUTON_POLYFILL, BOUTON_POLYGONES, BOUTON_SPHERES, Desenclencher_bouton(), Effacer_curseur, Famille, FAMILLE_INTERRUPTION, FAMILLE_TOOLBAR, Loupe_Mode, NB_BOUTONS, and Tracer_cadre_de_bouton_du_menu().
Referenced by Bouton_Menu_Loupe(), Bouton_Palette(), Bouton_Spray_Menu(), Bouton_Texte(), Brosse_0_5(), Etirer_brosse_2_7(), Gestion_principale(), Initialisation_du_programme(), Load_picture(), Polybrosse_12_8(), and Tourner_brosse_2_5().
void Annuler_les_effets (void)
References Aucun_effet(), Colorize_Mode, Colorize_Mode_avant_annulation, Fonction_effet, Fonction_effet_avant_annulation, Quick_shade_Mode, Quick_shade_Mode_avant_annulation, Shade_Mode, Shade_Mode_avant_annulation, Smooth_Mode, Smooth_Mode_avant_annulation, Stencil_Mode, Stencil_Mode_avant_annulation, Tiling_Mode, Tiling_Mode_avant_annulation, Trame_Mode, and Trame_Mode_avant_annulation.
void Restaurer_les_effets (void)
References Colorize_Mode, Colorize_Mode_avant_annulation, Fonction_effet, Fonction_effet_avant_annulation, Quick_shade_Mode, Quick_shade_Mode_avant_annulation, Shade_Mode, Shade_Mode_avant_annulation, Smooth_Mode, Smooth_Mode_avant_annulation, Stencil_Mode, Stencil_Mode_avant_annulation, Tiling_Mode, Tiling_Mode_avant_annulation, Trame_Mode, and Trame_Mode_avant_annulation.
void Ouvrir_fenetre (word Largeur, word Hauteur, char * Titre)
References Block, Cacher_pinceau, Cacher_pinceau_avant_fenetre, CM_Blanc, CM_Clair, CM_Fonce, CM_Noir, Effacer_curseur, Fenetre, Fenetre_Afficher_cadre_bombe(), Fenetre_Afficher_cadre_mono(), Fenetre_Hauteur, Fenetre_Largeur, Fenetre_Liste_boutons_dropdown, Fenetre_Liste_boutons_normal, Fenetre_Liste_boutons_palette, Fenetre_Liste_boutons_scroller, Fenetre_Liste_boutons_special, Fenetre_Pos_X, Fenetre_Pos_Y, Fond_fenetre, Forme_curseur, Forme_curseur_avant_fenetre, FORME_CURSEUR_FLECHE, Hauteur_ecran, Largeur_ecran, Menu_Facteur_X, Menu_Facteur_Y, Menu_Ordonnee, Menu_Ordonnee_avant_fenetre, Menu_visible, Menu_visible_avant_fenetre, Nb_boutons_fenetre, Print_dans_fenetre(), and Sauve_fond().
Referenced by Bouton_Brush_FX(), Bouton_Colorize_Menu(), Bouton_Copy_page(), Bouton_Degrades(), Bouton_Effets(), Bouton_Load_ou_Save(), Bouton_Menu_Grille(), Bouton_Menu_Loupe(), Bouton_Menu_pinceaux(), Bouton_Message_initial(), Bouton_Palette(), Bouton_Palette_secondaire(), Bouton_Quick_shade_Menu(), Bouton_Quitter_Routine_locale(), Bouton_Resol(), Bouton_Settings(), Bouton_Smooth_Menu(), Bouton_Spray_Menu(), Bouton_Stats(), Bouton_Texte(), Bouton_Tiling_Menu(), Bouton_Trame_Menu(), Demande_de_confirmation(), Fenetre_aide(), Fenetre_controle(), Menu_Shade(), Menu_Tag_couleurs(), Message_Memoire_insuffisante(), Message_Non_disponible(), and Warning_message().
void Fermer_fenetre (void)
References Afficher_ecran(), Afficher_menu(), Cacher_pinceau, Cacher_pinceau_avant_fenetre, Calculer_coordonnees_pinceau(), Effacer_curseur, Fenetre, Fenetre_Dropdown_vider_choix(), Fenetre_Hauteur, Fenetre_Largeur, Fenetre_Liste_boutons_dropdown, Fenetre_Liste_boutons_normal, Fenetre_Liste_boutons_palette, Fenetre_Liste_boutons_scroller, Fenetre_Liste_boutons_special, Fenetre_Pos_X, Fenetre_Pos_Y, Fond_fenetre, Forme_curseur, Forme_curseur_avant_fenetre, Menu_Facteur_X, Menu_Facteur_Y, Menu_Ordonnee, Menu_Ordonnee_avant_fenetre, Menu_visible, Menu_visible_avant_fenetre, Mouse_K, Old_MX, Old_MY, Restaure_fond(), Touche, and UpdateRect().
Referenced by Bouton_Brush_FX(), Bouton_Colorize_Menu(), Bouton_Copy_page(), Bouton_Degrades(), Bouton_Effets(), Bouton_Load_ou_Save(), Bouton_Menu_Grille(), Bouton_Menu_Loupe(), Bouton_Menu_pinceaux(), Bouton_Message_initial(), Bouton_Palette(), Bouton_Palette_secondaire(), Bouton_Quick_shade_Menu(), Bouton_Quitter_Routine_locale(), Bouton_Resol(), Bouton_Settings(), Bouton_Smooth_Menu(), Bouton_Spray_Menu(), Bouton_Stats(), Bouton_Texte(), Bouton_Tiling_Menu(), Bouton_Trame_Menu(), Demande_de_confirmation(), Fenetre_aide(), Fenetre_controle(), Menu_Shade(), Menu_Tag_couleurs(), Message_Memoire_insuffisante(), Message_Non_disponible(), and Warning_message().
void Ouvrir_popup (word Pos_X, word Pos_Y, word Largeur, word Hauteur)
References Cacher_pinceau, Cacher_pinceau_avant_fenetre, Fenetre, Fenetre_Hauteur, Fenetre_Largeur, Fenetre_Liste_boutons_dropdown, Fenetre_Liste_boutons_normal, Fenetre_Liste_boutons_palette, Fenetre_Liste_boutons_scroller, Fenetre_Liste_boutons_special, Fenetre_Pos_X, Fenetre_Pos_Y, Fond_fenetre, Forme_curseur, Forme_curseur_avant_fenetre, FORME_CURSEUR_FLECHE, Hauteur_ecran, Menu_Ordonnee, Menu_Ordonnee_avant_fenetre, Menu_visible, Menu_visible_avant_fenetre, Nb_boutons_fenetre, and Sauve_fond().
Referenced by Fenetre_Dropdown_click().
void Fermer_popup (void)
References Afficher_ecran(), Afficher_menu(), Cacher_pinceau, Cacher_pinceau_avant_fenetre, Calculer_coordonnees_pinceau(), Effacer_curseur, Fenetre, Fenetre_Dropdown_vider_choix(), Fenetre_Hauteur, Fenetre_Largeur, Fenetre_Liste_boutons_dropdown, Fenetre_Liste_boutons_normal, Fenetre_Liste_boutons_palette, Fenetre_Liste_boutons_scroller, Fenetre_Liste_boutons_special, Fenetre_Pos_X, Fenetre_Pos_Y, Fond_fenetre, Forme_curseur, Forme_curseur_avant_fenetre, Menu_Facteur_X, Menu_Facteur_Y, Menu_Ordonnee, Menu_Ordonnee_avant_fenetre, Menu_visible, Menu_visible_avant_fenetre, Mouse_K, Old_MX, Old_MY, Restaure_fond(), Touche, and UpdateRect().
Referenced by Fenetre_Dropdown_click().
void Fenetre_Dessiner_bouton_normal (word Pos_X, word Pos_Y, word Largeur, word Hauteur, char * Titre, byte Lettre_soulignee, byte Clickable)
References Block, CM_Clair, CM_Fonce, CM_Noir, Fenetre_Afficher_cadre_bombe(), Fenetre_Afficher_cadre_general(), Fenetre_Afficher_cadre_mono(), Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, and Print_dans_fenetre().
Referenced by Bouton_Resol(), Compter_nb_couleurs_utilisees(), Fenetre_Definir_bouton_dropdown(), Fenetre_Definir_bouton_normal(), and Fenetre_Definir_bouton_repetable().
void Fenetre_Enfoncer_bouton_normal (word Pos_X, word Pos_Y, word Largeur, word Hauteur)
References CM_Fonce, CM_Noir, Fenetre_Afficher_cadre_general(), Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, and UpdateRect().
Referenced by Fenetre_bouton_normal_click(), Fenetre_Dropdown_click(), Fenetre_Numero_bouton_clicke(), and Fenetre_Numero_bouton_touche().
void Fenetre_Desenfoncer_bouton_normal (word Pos_X, word Pos_Y, word Largeur, word Hauteur)
References Fenetre_Afficher_cadre_bombe(), Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, and UpdateRect().
Referenced by Fenetre_bouton_normal_click(), Fenetre_Dropdown_click(), Fenetre_Numero_bouton_clicke(), and Fenetre_Numero_bouton_touche().
void Fenetre_Dessiner_bouton_palette (word Pos_X, word Pos_Y)
References Block, Fenetre_Afficher_cadre(), Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, and Menu_Facteur_Y.
Referenced by Bouton_Palette(), and Fenetre_Definir_bouton_palette().
void Calculer_hauteur_curseur_jauge (struct Fenetre_Bouton_scroller * Enreg)
References Fenetre_Bouton_scroller::Hauteur, Fenetre_Bouton_scroller::Hauteur_curseur, Fenetre_Bouton_scroller::Nb_elements, and Fenetre_Bouton_scroller::Nb_visibles.
Referenced by Fenetre_aide(), Fenetre_Definir_bouton_scroller(), Palette_Modifier_jauge(), Preparer_et_afficher_liste_fichiers(), and Scroller_aide().
void Fenetre_Dessiner_jauge (struct Fenetre_Bouton_scroller * Enreg)
References Block, CM_Clair, CM_Noir, Fenetre_Pos_X, Fenetre_Pos_Y, Fenetre_Bouton_scroller::Hauteur, Fenetre_Bouton_scroller::Hauteur_curseur, Menu_Facteur_X, Menu_Facteur_Y, Fenetre_Bouton_scroller::Nb_elements, Fenetre_Bouton_scroller::Nb_visibles, Fenetre_Bouton_scroller::Pos_X, Fenetre_Bouton_scroller::Pos_Y, Fenetre_Bouton_scroller::Position, Round_div(), and UpdateRect().
Referenced by Bouton_Degrades(), Bouton_Palette(), Bouton_Texte(), Fenetre_aide(), Fenetre_Dessiner_bouton_scroller(), Fenetre_Numero_bouton_clicke(), On_vient_de_scroller_dans_le_fileselect(), Palette_Modifier_jauge(), Palette_Reafficher_jauges(), Preparer_et_afficher_liste_fichiers(), Scroller_aide(), Scroller_la_liste_des_modes(), Settings_Afficher_config(), and Spray_Rafficher_infos().
void Fenetre_Dessiner_bouton_scroller (struct Fenetre_Bouton_scroller * Enreg)
References CM_Clair, CM_Fonce, CM_Noir, Fenetre_Afficher_cadre_bombe(), Fenetre_Afficher_cadre_general(), Fenetre_Afficher_cadre_mono(), Fenetre_Dessiner_jauge(), Fenetre_Bouton_scroller::Hauteur, Fenetre_Bouton_scroller::Pos_X, Fenetre_Bouton_scroller::Pos_Y, and Print_dans_fenetre().
Referenced by Fenetre_Definir_bouton_scroller().
void Fenetre_Contenu_bouton_saisie (struct Fenetre_Bouton_special * Enreg, char * Contenu)
References CM_Clair, CM_Noir, Fenetre_Bouton_special::Largeur, Fenetre_Bouton_special::Pos_X, Fenetre_Bouton_special::Pos_Y, and Print_dans_fenetre_limite().
Referenced by Bouton_Colorize_Menu(), Bouton_Menu_Grille(), Bouton_Palette(), Bouton_Quick_shade_Menu(), Bouton_Resol(), Bouton_Settings(), Bouton_Smooth_Menu(), Bouton_Spray_Menu(), Bouton_Texte(), Bouton_Tiling_Menu(), Menu_Shade(), and Settings_Afficher_config().
void Fenetre_Effacer_bouton_saisie (struct Fenetre_Bouton_special * Enreg)
References Block, CM_Clair, Fenetre_Pos_X, Fenetre_Pos_Y, Fenetre_Bouton_special::Largeur, Menu_Facteur_X, Menu_Facteur_Y, Fenetre_Bouton_special::Pos_X, Fenetre_Bouton_special::Pos_Y, and UpdateRect().
void Fenetre_Dessiner_bouton_saisie (word Pos_X, word Pos_Y, word Largeur_en_caracteres)
References Fenetre_Afficher_cadre_creux().
Referenced by Fenetre_Definir_bouton_saisie().
struct Fenetre_Bouton_normal* Fenetre_Definir_bouton_normal (word Pos_X, word Pos_Y, word Largeur, word Hauteur, char * Titre, byte Lettre_soulignee, byte Clickable, word Raccourci) [read]
References Fenetre_Dessiner_bouton_normal(), Fenetre_Liste_boutons_normal, Fenetre_Bouton_normal::Hauteur, Fenetre_Bouton_normal::Largeur, Nb_boutons_fenetre, Fenetre_Bouton_normal::Next, Fenetre_Bouton_normal::Numero, Fenetre_Bouton_normal::Pos_X, Fenetre_Bouton_normal::Pos_Y, Fenetre_Bouton_normal::Raccourci, and Fenetre_Bouton_normal::Repetable.
Referenced by Bouton_Brush_FX(), Bouton_Colorize_Menu(), Bouton_Copy_page(), Bouton_Degrades(), Bouton_Effets(), Bouton_Load_ou_Save(), Bouton_Menu_Grille(), Bouton_Menu_Loupe(), Bouton_Menu_pinceaux(), Bouton_Palette(), Bouton_Palette_secondaire(), Bouton_Quick_shade_Menu(), Bouton_Quitter_Routine_locale(), Bouton_Resol(), Bouton_Settings(), Bouton_Smooth_Menu(), Bouton_Spray_Menu(), Bouton_Stats(), Bouton_Texte(), Bouton_Tiling_Menu(), Bouton_Trame_Menu(), Demande_de_confirmation(), Fenetre_aide(), Fenetre_controle(), Menu_Shade(), Menu_Tag_couleurs(), Message_Memoire_insuffisante(), Message_Non_disponible(), and Warning_message().
struct Fenetre_Bouton_normal* Fenetre_Definir_bouton_repetable (word Pos_X, word Pos_Y, word Largeur, word Hauteur, char * Titre, byte Lettre_soulignee, byte Clickable, word Raccourci) [read]
References Fenetre_Dessiner_bouton_normal(), Fenetre_Liste_boutons_normal, Fenetre_Bouton_normal::Hauteur, Fenetre_Bouton_normal::Largeur, Nb_boutons_fenetre, Fenetre_Bouton_normal::Next, Fenetre_Bouton_normal::Numero, Fenetre_Bouton_normal::Pos_X, Fenetre_Bouton_normal::Pos_Y, Fenetre_Bouton_normal::Raccourci, and Fenetre_Bouton_normal::Repetable.
Referenced by Bouton_Palette(), Bouton_Texte(), and Bouton_Trame_Menu().
struct Fenetre_Bouton_palette* Fenetre_Definir_bouton_palette (word Pos_X, word Pos_Y) [read]
References Fenetre_Dessiner_bouton_palette(), Fenetre_Liste_boutons_palette, Nb_boutons_fenetre, Fenetre_Bouton_palette::Next, Fenetre_Bouton_palette::Numero, Fenetre_Bouton_palette::Pos_X, and Fenetre_Bouton_palette::Pos_Y.
Referenced by Bouton_Degrades(), Bouton_Palette(), Bouton_Spray_Menu(), Menu_Shade(), and Menu_Tag_couleurs().
void Fenetre_Effacer_tags (void)
References Block, CM_Clair, Fenetre_Liste_boutons_palette, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Fenetre_Bouton_dropdown::Pos_X, ToWinH, ToWinL, and UpdateRect().
Referenced by Bouton_Spray_Menu().
void Tagger_intervalle_palette (byte Debut, byte Fin)
References Block, CM_Clair, CM_Noir, Fenetre_Liste_boutons_palette, Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Pixel_dans_fenetre(), Fenetre_Bouton_dropdown::Pos_Y, ToWinH, ToWinL, ToWinX, ToWinY, and UpdateRect().
Referenced by Bouton_Degrades(), Bouton_Palette(), and Menu_Shade().
struct Fenetre_Bouton_scroller* Fenetre_Definir_bouton_scroller (word Pos_X, word Pos_Y, word Hauteur, word Nb_elements, word Nb_elements_visibles, word Position_initiale) [read]
References Calculer_hauteur_curseur_jauge(), Fenetre_Dessiner_bouton_scroller(), Fenetre_Liste_boutons_scroller, Fenetre_Bouton_scroller::Hauteur, Nb_boutons_fenetre, Fenetre_Bouton_scroller::Nb_elements, Fenetre_Bouton_scroller::Nb_visibles, Fenetre_Bouton_scroller::Next, Fenetre_Bouton_scroller::Numero, Fenetre_Bouton_scroller::Pos_X, Fenetre_Bouton_scroller::Pos_Y, and Fenetre_Bouton_scroller::Position.
Referenced by Bouton_Degrades(), Bouton_Load_ou_Save(), Bouton_Palette(), Bouton_Palette_secondaire(), Bouton_Resol(), Bouton_Settings(), Bouton_Spray_Menu(), Bouton_Texte(), Fenetre_aide(), and Menu_Shade().
struct Fenetre_Bouton_special* Fenetre_Definir_bouton_special (word Pos_X, word Pos_Y, word Largeur, word Hauteur) [read]
References Fenetre_Liste_boutons_special, Fenetre_Bouton_special::Hauteur, Fenetre_Bouton_special::Largeur, Nb_boutons_fenetre, Fenetre_Bouton_special::Next, Fenetre_Bouton_special::Numero, Fenetre_Bouton_special::Pos_X, and Fenetre_Bouton_special::Pos_Y.
Referenced by Bouton_Load_ou_Save(), Bouton_Resol(), Bouton_Texte(), Bouton_Trame_Menu(), Fenetre_aide(), Fenetre_Definir_bouton_saisie(), and Menu_Shade().
struct Fenetre_Bouton_special* Fenetre_Definir_bouton_saisie (word Pos_X, word Pos_Y, word Largeur_en_caracteres) [read]
References Fenetre_Definir_bouton_special(), and Fenetre_Dessiner_bouton_saisie().
Referenced by Bouton_Colorize_Menu(), Bouton_Load_ou_Save(), Bouton_Menu_Grille(), Bouton_Palette(), Bouton_Quick_shade_Menu(), Bouton_Resol(), Bouton_Settings(), Bouton_Smooth_Menu(), Bouton_Spray_Menu(), Bouton_Texte(), Bouton_Tiling_Menu(), and Menu_Shade().
struct Fenetre_Bouton_dropdown* Fenetre_Definir_bouton_dropdown (word Pos_X, word Pos_Y, word Largeur, word Hauteur, word Largeur_choix, char * Libelle, byte Affiche_choix, byte Affiche_centre, byte Affiche_fleche, byte Bouton_actif) [read]
References Fenetre_Bouton_dropdown::Affiche_centre, Fenetre_Bouton_dropdown::Affiche_choix, Fenetre_Bouton_dropdown::Affiche_fleche, Fenetre_Bouton_dropdown::Bouton_actif, CM_Clair, CM_Noir, Fenetre_Afficher_sprite_drive(), Fenetre_Dessiner_bouton_normal(), Fenetre_Liste_boutons_dropdown, Fenetre_Bouton_dropdown::Hauteur, Fenetre_Bouton_dropdown::Largeur, Fenetre_Bouton_dropdown::Largeur_choix, Nb_boutons_fenetre, Fenetre_Bouton_dropdown::Next, Fenetre_Bouton_dropdown::Numero, Fenetre_Bouton_dropdown::Pos_X, Fenetre_Bouton_dropdown::Pos_Y, Fenetre_Bouton_dropdown::Premier_choix, and Print_dans_fenetre().
Referenced by Bouton_Load_ou_Save().
void Fenetre_Dropdown_choix (struct Fenetre_Bouton_dropdown * Dropdown, word Numero, const char * Libelle)
References Bouton_dropdown_choix::Libelle, Bouton_dropdown_choix::Next, Bouton_dropdown_choix::Numero, and Fenetre_Bouton_dropdown::Premier_choix.
Referenced by Afficher_bookmark(), and Bouton_Load_ou_Save().
void Fenetre_Dropdown_vider_choix (struct Fenetre_Bouton_dropdown * Dropdown)
References Bouton_dropdown_choix::Next, and Fenetre_Bouton_dropdown::Premier_choix.
Referenced by Afficher_bookmark(), Fermer_fenetre(), and Fermer_popup().
byte Fenetre_click_dans_zone (short Debut_X, short Debut_Y, short Fin_X, short Fin_Y)
References Fenetre_Pos_X, Fenetre_Pos_Y, Menu_Facteur_X, Menu_Facteur_Y, Mouse_X, Mouse_Y, Fenetre_Bouton_dropdown::Pos_X, and Fenetre_Bouton_dropdown::Pos_Y.
Referenced by Attendre_click_dans_palette(), Attendre_click_dans_shade(), Fenetre_bouton_normal_click(), Fenetre_Dropdown_click(), and Fenetre_Numero_bouton_clicke().
short Attendre_click_dans_palette (struct Fenetre_Bouton_palette * Enreg)
References A_DROITE, A_GAUCHE, Afficher_curseur(), Cacher_curseur, Effacer_curseur, Fenetre_click_dans_zone(), Fenetre_Hauteur, Fenetre_Largeur, Fenetre_Pos_X, Fenetre_Pos_Y, Forme_curseur, FORME_CURSEUR_CIBLE, FORME_CURSEUR_FLECHE, Get_input(), Lit_pixel, Loupe_Mode, Menu_Facteur_X, Menu_Facteur_Y, Mouse_K, Mouse_X, Mouse_Y, Fenetre_Bouton_palette::Pos_X, Fenetre_Bouton_palette::Pos_Y, Touche, TOUCHE_ESC, and Wait_VBL().
Referenced by Bouton_Palette().
void Recuperer_couleur_derriere_fenetre (byte * Couleur, byte * Click)
References Afficher_curseur(), Afficher_ecran(), Afficher_ligne, Afficher_menu(), BOUTON_CHOIX_COL, Cacher_curseur, Cacher_pinceau, Effacer_curseur, Erreur, Fenetre_Hauteur, Fenetre_Largeur, Fenetre_Pos_X, Fenetre_Pos_Y, Forme_curseur, FORME_CURSEUR_CIBLE_PIPETTE, FORME_CURSEUR_FLECHE, Get_input(), Hauteur, Largeur, Lire_ligne, Lit_pixel, Menu_Facteur_X, Menu_Facteur_Y, Menu_Ordonnee, Menu_Ordonnee_avant_fenetre, Menu_Ordonnee_Texte, Menu_visible, Menu_visible_avant_fenetre, Mouse_K, Mouse_X, Mouse_Y, Pixel_width, Principal_Palette, Print_dans_menu(), Print_general(), TITRE_BOUTON, Touche, TOUCHE_ESC, UpdateRect(), and Wait_VBL().
Referenced by Bouton_Degrades(), Bouton_Palette(), Bouton_Spray_Menu(), Menu_Shade(), and Menu_Tag_couleurs().
short Fenetre_Bouton_clicke (void)
References Bouton, Deplacer_fenetre(), Fenetre_Hauteur, Fenetre_Largeur, Fenetre_Numero_bouton_clicke(), Fenetre_Numero_bouton_touche(), Fenetre_Pos_X, Fenetre_Pos_Y, Get_input(), Menu_Facteur_X, Menu_Facteur_Y, Mouse_K, Mouse_X, Mouse_Y, Touche, and Wait_VBL().
Referenced by Bouton_Brush_FX(), Bouton_Colorize_Menu(), Bouton_Copy_page(), Bouton_Degrades(), Bouton_Effets(), Bouton_Load_ou_Save(), Bouton_Menu_Grille(), Bouton_Menu_Loupe(), Bouton_Menu_pinceaux(), Bouton_Palette(), Bouton_Palette_secondaire(), Bouton_Quick_shade_Menu(), Bouton_Quitter_Routine_locale(), Bouton_Resol(), Bouton_Settings(), Bouton_Smooth_Menu(), Bouton_Spray_Menu(), Bouton_Stats(), Bouton_Texte(), Bouton_Tiling_Menu(), Bouton_Trame_Menu(), Demande_de_confirmation(), Fenetre_aide(), Fenetre_controle(), Menu_Shade(), Menu_Tag_couleurs(), Message_Memoire_insuffisante(), Message_Non_disponible(), and Warning_message().
int Numero_bouton_sous_souris (void)
References Bouton, Decalage_X, Forme, FORME_BOUTON_RECTANGLE, FORME_BOUTON_SANS_CADRE, FORME_BOUTON_TRIANGLE_BAS_DROITE, FORME_BOUTON_TRIANGLE_HAUT_GAUCHE, Largeur, Menu_Facteur_X, Menu_Facteur_Y, Menu_Ordonnee, Mouse_X, Mouse_Y, and NB_BOUTONS.
Referenced by Bouton_Aide(), and Gestion_principale().
short Fenetre_Numero_bouton_clicke (void)
References Afficher_curseur(), Fenetre_Bouton_dropdown::Bouton_actif, Config, Effacer_curseur, Fenetre_Attribut1, Fenetre_Attribut2, Fenetre_bouton_normal_click(), Fenetre_click_dans_zone(), Fenetre_Desenfoncer_bouton_normal(), Fenetre_Dessiner_jauge(), Fenetre_Dropdown_click(), Fenetre_Enfoncer_bouton_normal(), Fenetre_Liste_boutons_dropdown, Fenetre_Liste_boutons_normal, Fenetre_Liste_boutons_palette, Fenetre_Liste_boutons_scroller, Fenetre_Liste_boutons_special, Fenetre_Pos_X, Fenetre_Pos_Y, Fenetre_Bouton_dropdown::Hauteur, Fenetre_Bouton_special::Hauteur, Fenetre_Bouton_scroller::Hauteur, Fenetre_Bouton_normal::Hauteur, Fenetre_Bouton_scroller::Hauteur_curseur, Fenetre_Bouton_dropdown::Largeur, Fenetre_Bouton_special::Largeur, Fenetre_Bouton_normal::Largeur, Menu_Facteur_X, Menu_Facteur_Y, Mouse_K, Mouse_X, Mouse_Y, Fenetre_Bouton_scroller::Nb_elements, Fenetre_Bouton_scroller::Nb_visibles, Fenetre_Bouton_dropdown::Next, Fenetre_Bouton_special::Next, Fenetre_Bouton_scroller::Next, Fenetre_Bouton_palette::Next, Fenetre_Bouton_normal::Next, Fenetre_Bouton_dropdown::Numero, Fenetre_Bouton_special::Numero, Fenetre_Bouton_scroller::Numero, Fenetre_Bouton_palette::Numero, Fenetre_Bouton_normal::Numero, Fenetre_Bouton_dropdown::Pos_X, Fenetre_Bouton_special::Pos_X, Fenetre_Bouton_scroller::Pos_X, Fenetre_Bouton_palette::Pos_X, Fenetre_Bouton_normal::Pos_X, Fenetre_Bouton_dropdown::Pos_Y, Fenetre_Bouton_special::Pos_Y, Fenetre_Bouton_scroller::Pos_Y, Fenetre_Bouton_palette::Pos_Y, Fenetre_Bouton_normal::Pos_Y, Fenetre_Bouton_scroller::Position, Fenetre_Bouton_normal::Repetable, Round_div(), Tempo_jauge(), S_Config::Valeur_tempo_jauge_droite, and S_Config::Valeur_tempo_jauge_gauche.
Referenced by Bouton_Effets(), and Fenetre_Bouton_clicke().
void Remappe_fond_fenetres (byte * Table_de_conversion, int Min_Y, int Max_Y)
References Fenetre, Fond_fenetre, Menu_Facteur_X, Menu_Facteur_Y, Pile_Fenetre_Hauteur, Pile_Fenetre_Largeur, Pile_Fenetre_Pos_Y, and Pixel_width.
Referenced by Remap_image_HIGH(), and Remapper_ecran_apres_changement_couleurs_menu().
void Pixel_fond (int Pos_X, int Pos_Y, byte Couleur)
References Fenetre_Largeur, Fond_fenetre, Menu_Facteur_X, and Pixel_width.
Referenced by Afficher_palette_du_menu_en_evitant_la_fenetre().