GrafX2: op_c.h File Reference
op_c.h File Reference
Color reduction and color conversion (24b->8b, RGB<->HSL).
#include "struct.h"
Data Structures
struct T_Conversion_table
struct T_Occurrence_table
struct T_Cluster
struct T_Cluster_set
struct T_Gradient
struct T_Gradient_set
Typedefs
typedef T_Components * T_Bitmap24B
typedef byte * T_Bitmap256
Functions
T_Conversion_table * CT_new (int nbb_r, int nbb_g, int nbb_b)
Creates a new conversion table params: bumber of bits for R, G, B (precision)
void CT_delete (T_Conversion_table *t)
Delete a conversion table and release its memory.
byte CT_get (T_Conversion_table *t, int r, int g, int b)
Get the best palette index for an (R, G, B) color.
void CT_set (T_Conversion_table *t, int r, int g, int b, byte i)
Set an entry of the table, index (RGB), value i.
void RGB_to_HSL (int r, int g, int b, byte *h, byte *s, byte *l)
Convert RGB to HSL.
void HSL_to_RGB (byte h, byte s, byte l, byte *r, byte *g, byte *b)
Convert HSL back to RGB Input and output are all in range 0..255.
long Perceptual_lightness (T_Components *color)
Returns a value that is high when color is near white, and low when it's darker.
void OT_init (T_Occurrence_table *t)
Initialize an occurence table.
T_Occurrence_table * OT_new (int nbb_r, int nbb_g, int nbb_b)
Allocate an occurence table for given number of bits.
void OT_delete (T_Occurrence_table *t)
Delete a table and free the memory.
int OT_get (T_Occurrence_table *t, int r, int g, int b)
Get number of occurences for a given color.
void OT_inc (T_Occurrence_table *t, int r, int g, int b)
Add 1 to the count for a color.
void OT_count_occurrences (T_Occurrence_table *t, T_Bitmap24B image, int size)
Count the use of each color in a 24bit picture and fill in the table.
void Cluster_pack (T_Cluster *c, T_Occurrence_table *to)
Pack a cluster, ie compute its {r,v,b}{min,max} values.
void Cluster_split (T_Cluster *c, T_Cluster *c1, T_Cluster *c2, int hue, T_Occurrence_table *to)
Split a cluster on its longest axis.
void Cluster_compute_hue (T_Cluster *c, T_Occurrence_table *to)
Compute the mean R, G, B (for palette generation) and H, L (for palette sorting)
void CS_Init (T_Cluster_set *cs, T_Occurrence_table *to)
Setup the first cluster before we start the operations This one covers the full palette range.
T_Cluster_set * CS_New (int nbmax, T_Occurrence_table *to)
Allocate a new cluster set.
void CS_Delete (T_Cluster_set *cs)
Free a cluster set.
void CS_Get (T_Cluster_set *cs, T_Cluster *c)
Pop a cluster from the cluster list.
void CS_Set (T_Cluster_set *cs, T_Cluster *c)
Push a cluster in the list.
void CS_Generate (T_Cluster_set *cs, T_Occurrence_table *to)
This is the main median cut algorithm and the function actually called to reduce the palette.
void CS_Compute_colors (T_Cluster_set *cs, T_Occurrence_table *to)
Compute the color associated to each box in the list.
void CS_Generate_color_table_and_palette (T_Cluster_set *cs, T_Conversion_table *tc, T_Components *palette)
Generates the palette from the clusters, then the conversion table to map (RGB) to a palette index.
void GS_Init (T_Gradient_set *ds, T_Cluster_set *cs)
T_Gradient_set * GS_New (T_Cluster_set *cs)
void GS_Delete (T_Gradient_set *ds)
void GS_Generate (T_Gradient_set *ds, T_Cluster_set *cs)
int Convert_24b_bitmap_to_256 (T_Bitmap256 dest, T_Bitmap24B source, int width, int height, T_Components *palette)
Detailed Description
Color reduction and color conversion (24b->8b, RGB<->HSL).
This is called op_c because half of the process was originally coded in op_asm, in assembler.
Typedef Documentation
typedef T_Components* T_Bitmap24B
typedef byte* T_Bitmap256
Function Documentation
T_Conversion_table* CT_new (int nbb_r, int nbb_g, int nbb_b)
Creates a new conversion table params: bumber of bits for R, G, B (precision)
References byte, T_Conversion_table::dec_b, T_Conversion_table::dec_g, T_Conversion_table::dec_r, T_Conversion_table::nbb_b, T_Conversion_table::nbb_g, T_Conversion_table::nbb_r, T_Conversion_table::red_b, T_Conversion_table::red_g, T_Conversion_table::red_r, T_Conversion_table::rng_b, T_Conversion_table::rng_g, T_Conversion_table::rng_r, and T_Conversion_table::table.
Referenced by Optimize_palette().
void CT_delete (T_Conversion_table * t)
Delete a conversion table and release its memory.
References T_Conversion_table::table.
Referenced by Convert_24b_bitmap_to_256(), and Optimize_palette().
byte CT_get (T_Conversion_table * t, int r, int g, int b)
Get the best palette index for an (R, G, B) color.
References T_Conversion_table::dec_b, T_Conversion_table::dec_g, T_Conversion_table::dec_r, T_Conversion_table::red_b, T_Conversion_table::red_g, T_Conversion_table::red_r, and T_Conversion_table::table.
Referenced by Convert_24b_bitmap_to_256_Floyd_Steinberg(), and Convert_24b_bitmap_to_256_nearest_neighbor().
void CT_set (T_Conversion_table * t, int r, int g, int b, byte i)
Set an entry of the table, index (RGB), value i.
References T_Conversion_table::dec_b, T_Conversion_table::dec_g, T_Conversion_table::dec_r, and T_Conversion_table::table.
Referenced by CS_Generate_color_table_and_palette().
void RGB_to_HSL (int r, int g, int b, byte * hr, byte * sr, byte * lr)
Convert RGB to HSL.
Both input and output are in the 0..255 range to use in the palette screen
Referenced by Button_Palette(), Cluster_compute_hue(), Compute_optimal_menu_colors(), Display_sliders(), Draw_all_palette_sliders(), and Set_HSL().
void HSL_to_RGB (byte h, byte s, byte l, byte * r, byte * g, byte * b)
Convert HSL back to RGB Input and output are all in range 0..255.
Referenced by Button_Palette(), and Set_HSL().
long Perceptual_lightness (T_Components * color)
Returns a value that is high when color is near white, and low when it's darker.
Used for sorting.
References T_Components::B, T_Components::G, and T_Components::R.
Referenced by Button_Palette().
void OT_init (T_Occurrence_table * t)
Initialize an occurence table.
References T_Occurrence_table::rng_b, T_Occurrence_table::rng_g, T_Occurrence_table::rng_r, and T_Occurrence_table::table.
T_Occurrence_table* OT_new (int nbb_r, int nbb_g, int nbb_b)
Allocate an occurence table for given number of bits.
References T_Occurrence_table::dec_b, T_Occurrence_table::dec_g, T_Occurrence_table::dec_r, T_Occurrence_table::nbb_b, T_Occurrence_table::nbb_g, T_Occurrence_table::nbb_r, T_Occurrence_table::red_b, T_Occurrence_table::red_g, T_Occurrence_table::red_r, T_Occurrence_table::rng_b, T_Occurrence_table::rng_g, T_Occurrence_table::rng_r, and T_Occurrence_table::table.
Referenced by Optimize_palette().
void OT_delete (T_Occurrence_table * t)
Delete a table and free the memory.
References T_Occurrence_table::table.
Referenced by Optimize_palette().
int OT_get (T_Occurrence_table * t, int r, int g, int b)
Get number of occurences for a given color.
References T_Occurrence_table::dec_b, T_Occurrence_table::dec_g, T_Occurrence_table::dec_r, and T_Occurrence_table::table.
Referenced by Cluster_compute_hue().
void OT_inc (T_Occurrence_table * t, int r, int g, int b)
Add 1 to the count for a color.
References T_Occurrence_table::dec_b, T_Occurrence_table::dec_g, T_Occurrence_table::dec_r, T_Occurrence_table::red_b, T_Occurrence_table::red_g, T_Occurrence_table::red_r, and T_Occurrence_table::table.
Referenced by OT_count_occurrences().
void OT_count_occurrences (T_Occurrence_table * t, T_Bitmap24B image, int size)
Count the use of each color in a 24bit picture and fill in the table.
References T_Components::B, T_Components::G, OT_inc(), and T_Components::R.
Referenced by Optimize_palette().
void Cluster_pack (T_Cluster * c, T_Occurrence_table * to)
Pack a cluster, ie compute its {r,v,b}{min,max} values.
References T_Cluster::bmax, T_Cluster::bmin, T_Cluster::occurences, T_Cluster::plus_large, T_Cluster::rmax, T_Cluster::rmin, T_Occurrence_table::table, T_Cluster::vmax, and T_Cluster::vmin.
Referenced by CS_Generate(), and CS_Init().
void Cluster_split (T_Cluster * c, T_Cluster * c1, T_Cluster * c2, int hue, T_Occurrence_table * to)
Split a cluster on its longest axis.
c = source cluster, c1, c2 = output after split
References T_Cluster::bmax, T_Cluster::Bmax, T_Cluster::Bmin, T_Cluster::bmin, T_Cluster::Gmin, T_Cluster::occurences, T_Cluster::rmax, T_Cluster::Rmax, T_Cluster::Rmin, T_Cluster::rmin, T_Occurrence_table::table, T_Cluster::vmax, T_Cluster::Vmax, and T_Cluster::vmin.
Referenced by CS_Generate().
void Cluster_compute_hue (T_Cluster * c, T_Occurrence_table * to)
Compute the mean R, G, B (for palette generation) and H, L (for palette sorting)
References T_Cluster::b, T_Cluster::bmin, byte, T_Cluster::g, T_Cluster::h, T_Cluster::l, T_Cluster::occurences, OT_get(), T_Cluster::r, T_Occurrence_table::red_b, T_Occurrence_table::red_g, T_Occurrence_table::red_r, RGB_to_HSL(), T_Cluster::rmin, and T_Cluster::vmin.
Referenced by CS_Compute_colors().
void CS_Init (T_Cluster_set * cs, T_Occurrence_table * to)
Setup the first cluster before we start the operations This one covers the full palette range.
References T_Cluster::bmax, T_Cluster::Bmax, T_Cluster::bmin, T_Cluster::Bmin, Cluster_pack(), T_Cluster_set::clusters, T_Cluster::Gmin, T_Cluster_set::nb, T_Cluster::next, T_Cluster::rmax, T_Cluster::Rmax, T_Cluster::rmin, T_Cluster::Rmin, T_Occurrence_table::rng_b, T_Occurrence_table::rng_g, T_Occurrence_table::rng_r, T_Cluster::vmax, T_Cluster::Vmax, and T_Cluster::vmin.
Referenced by CS_New().
T_Cluster_set* CS_New (int nbmax, T_Occurrence_table * to)
Allocate a new cluster set.
References T_Cluster_set::clusters, CS_Init(), T_Cluster_set::nb_max, and OT_count_colors().
Referenced by Optimize_palette().
void CS_Delete (T_Cluster_set * cs)
Free a cluster set.
References T_Cluster_set::clusters, and T_Cluster::next.
Referenced by Optimize_palette().
void CS_Get (T_Cluster_set * cs, T_Cluster * c)
Pop a cluster from the cluster list.
References T_Cluster::bmax, T_Cluster::bmin, T_Cluster_set::clusters, T_Cluster_set::nb, T_Cluster::next, T_Cluster::rmax, T_Cluster::rmin, T_Cluster::vmax, and T_Cluster::vmin.
Referenced by CS_Generate().
void CS_Set (T_Cluster_set * cs, T_Cluster * c)
Push a cluster in the list.
References T_Cluster_set::clusters, T_Cluster_set::nb, T_Cluster::next, and T_Cluster::occurences.
Referenced by CS_Generate().
void CS_Generate (T_Cluster_set * cs, T_Occurrence_table * to)
This is the main median cut algorithm and the function actually called to reduce the palette.
We get the number of pixels for each collor in the occurence table and generate the cluster set from it.
References Cluster_pack(), Cluster_split(), CS_Get(), CS_Set(), T_Cluster_set::nb, T_Cluster_set::nb_max, and T_Cluster::plus_large.
Referenced by Optimize_palette().
void CS_Compute_colors (T_Cluster_set * cs, T_Occurrence_table * to)
Compute the color associated to each box in the list.
References Cluster_compute_hue(), T_Cluster_set::clusters, and T_Cluster::next.
Referenced by Optimize_palette().
void CS_Generate_color_table_and_palette (T_Cluster_set * cs, T_Conversion_table * tc, T_Components * palette)
Generates the palette from the clusters, then the conversion table to map (RGB) to a palette index.
References T_Cluster::b, T_Components::B, T_Cluster::Bmin, T_Cluster_set::clusters, CT_set(), T_Cluster::g, T_Components::G, T_Cluster::Gmin, T_Cluster_set::nb, T_Cluster::next, T_Cluster::r, T_Components::R, and T_Cluster::Rmin.
Referenced by Optimize_palette().
void GS_Init (T_Gradient_set * ds, T_Cluster_set * cs)
References T_Cluster_set::clusters, T_Gradient_set::gradients, T_Cluster::h, T_Gradient::hue, T_Gradient::max, T_Gradient::min, T_Gradient_set::nb, and T_Gradient::nb_colors.
Referenced by GS_New().
T_Gradient_set* GS_New (T_Cluster_set * cs)
References T_Gradient_set::gradients, GS_Init(), T_Cluster_set::nb_max, and T_Gradient_set::nb_max.
Referenced by Optimize_palette().
void GS_Delete (T_Gradient_set * ds)
References T_Gradient_set::gradients.
Referenced by Optimize_palette().
void GS_Generate (T_Gradient_set * ds, T_Cluster_set * cs)
References T_Cluster_set::clusters, T_Gradient_set::gradients, T_Cluster::h, T_Gradient::hue, id, T_Gradient::max, T_Gradient::min, T_Gradient_set::nb, T_Gradient::nb_colors, and T_Cluster::next.
Referenced by Optimize_palette().
int Convert_24b_bitmap_to_256 (T_Bitmap256 dest, T_Bitmap24B source, int width, int height, T_Components * palette)
References Convert_24b_bitmap_to_256_fast(), Convert_24b_bitmap_to_256_nearest_neighbor(), CT_delete(), and Optimize_palette().
Referenced by Load_image().