GrafX2: operatio.h File Reference
operatio.h File Reference
Code for the operations, ie all drawing tools.
Functions
void Start_operation_stack (word new_operation)
Do some housekeeping before starting work on a operation.
void Operation_push (short value)
Put a value on Operation_stack.
void Operation_pop (short *value)
Take a value off Operation_stack.
void Freehand_mode1_1_0 (void)
void Freehand_mode1_1_2 (void)
void Freehand_mode12_0_2 (void)
void Freehand_mode1_2_0 (void)
void Freehand_mode1_2_2 (void)
void Freehand_mode2_1_0 (void)
void Freehand_mode2_1_2 (void)
void Freehand_mode2_2_0 (void)
void Freehand_mode2_2_2 (void)
void Freehand_mode3_1_0 (void)
void Freehand_Mode3_2_0 (void)
void Freehand_mode3_0_1 (void)
void Line_12_0 (void)
void Line_12_5 (void)
void Line_0_5 (void)
void Magnifier_12_0 (void)
void Rectangle_12_0 (void)
void Rectangle_12_5 (void)
void Empty_rectangle_0_5 (void)
void Filled_rectangle_0_5 (void)
void Circle_12_0 (void)
void Circle_12_5 (void)
void Empty_circle_0_5 (void)
void Filled_circle_0_5 (void)
void Ellipse_12_0 (void)
void Ellipse_12_5 (void)
void Empty_ellipse_0_5 (void)
void Filled_ellipse_0_5 (void)
void Brush_12_0 (void)
void Brush_12_5 (void)
void Brush_0_5 (void)
void Stretch_brush_12_0 (void)
void Stretch_brush_1_7 (void)
void Stretch_brush_0_7 (void)
void Stretch_brush_2_7 (void)
void Rotate_brush_12_0 (void)
void Rotate_brush_1_5 (void)
void Rotate_brush_0_5 (void)
void Rotate_brush_2_5 (void)
void Distort_brush_0_0 (void)
void Distort_brush_1_0 (void)
void Distort_brush_2_0 (void)
void Distort_brush_1_8 (void)
void Distort_brush_2_8 (void)
void Distort_brush_1_9 (void)
void Distort_brush_0_9 (void)
void Polybrush_12_8 (void)
void Fill_1_0 (void)
void Fill_2_0 (void)
void Replace_1_0 (void)
void Replace_2_0 (void)
void Pipette_0_0 (void)
void Colorpicker_12_0 (void)
void Colorpicker_1_1 (void)
void Colorpicker_2_1 (void)
void Colorpicker_0_1 (void)
void K_line_12_0 (void)
void K_line_12_6 (void)
void K_line_0_6 (void)
void K_line_12_7 (void)
void Curve_34_points_1_0 (void)
void Curve_34_points_2_0 (void)
void Curve_34_points_1_5 (void)
void Curve_34_points_2_5 (void)
void Curve_4_points_0_5 (void)
void Curve_4_points_1_9 (void)
void Curve_4_points_2_9 (void)
void Curve_3_points_0_5 (void)
void Curve_3_points_0_11 (void)
void Curve_3_points_12_11 (void)
void Airbrush_1_0 (void)
void Airbrush_2_0 (void)
void Airbrush_12_2 (void)
void Airbrush_0_2 (void)
void Polygon_12_0 (void)
void Polygon_12_9 (void)
void Polyfill_12_0 (void)
void Polyfill_0_8 (void)
void Polyfill_12_8 (void)
void Polyfill_12_9 (void)
void Polyform_12_0 (void)
void Polyform_12_8 (void)
void Polyform_0_8 (void)
void Filled_polyform_12_0 (void)
void Filled_polyform_12_8 (void)
void Filled_polyform_0_8 (void)
void Filled_contour_0_8 (void)
void Scroll_12_0 (void)
void Scroll_12_4 (void)
void Scroll_0_4 (void)
void Grad_circle_12_0 (void)
void Grad_circle_12_6 (void)
void Grad_circle_0_6 (void)
void Grad_circle_12_8 (void)
void Grad_circle_or_ellipse_0_8 (void)
void Grad_ellipse_12_0 (void)
void Grad_ellipse_12_6 (void)
void Grad_ellipse_0_6 (void)
void Grad_ellipse_12_8 (void)
void Grad_rectangle_12_0 (void)
void Grad_rectangle_12_5 (void)
void Grad_rectangle_0_5 (void)
void Grad_rectangle_0_7 (void)
void Grad_rectangle_12_7 (void)
void Grad_rectangle_12_9 (void)
void Grad_rectangle_0_9 (void)
void Centered_lines_12_0 (void)
void Centered_lines_12_3 (void)
void Centered_lines_0_3 (void)
void Centered_lines_12_7 (void)
void Centered_lines_0_7 (void)
Detailed Description
Code for the operations, ie all drawing tools.
Function Documentation
void Start_operation_stack (word new_operation)
Do some housekeeping before starting work on a operation.
References Allow_color_change_during_operation, Brush_rotation_center_is_defined, Current_operation, CURSOR_FOR_OPERATION, Cursor_shape, OPERATION_AIRBRUSH, Operation_before_interrupt, OPERATION_CENTERED_LINES, OPERATION_COLORPICK, OPERATION_CONTINUOUS_DRAW, OPERATION_DISCONTINUOUS_DRAW, OPERATION_GRAB_BRUSH, OPERATION_MAGNIFY, OPERATION_POLYBRUSH, OPERATION_ROTATE_BRUSH, Operation_stack_size, and OPERATION_STRETCH_BRUSH.
Referenced by Button_Adjust(), Button_Airbrush(), Button_Brush(), Button_Brush_FX(), Button_Colorpicker(), Button_Curves(), Button_Curves_switch_mode(), Button_Draw(), Button_Draw_switch_mode(), Button_Empty_circle(), Button_Empty_ellipse(), Button_Empty_rectangle(), Button_Fill(), Button_Filled_circle(), Button_Filled_ellipse(), Button_Filled_polyform(), Button_Filled_rectangle(), Button_Grad_circle(), Button_Grad_ellipse(), Button_Grad_rectangle(), Button_Lasso(), Button_Lines(), Button_Lines_switch_mode(), Button_Magnify(), Button_Polyfill(), Button_Polyform(), Button_polygon(), Button_Replace(), Button_Unselect_brush(), Button_Unselect_colorpicker(), Button_Unselect_lasso(), Button_Unselect_magnifier(), Magnifier_12_0(), Main_handler(), Rotate_brush_12_0(), and Stretch_brush_12_0().
void Operation_push (short value)
Put a value on Operation_stack.
References Operation_stack, and Operation_stack_size.
Referenced by Airbrush_12_2(), Airbrush_1_0(), Airbrush_2_0(), Brush_12_0(), Brush_12_5(), Centered_lines_0_3(), Centered_lines_0_7(), Centered_lines_12_0(), Centered_lines_12_3(), Centered_lines_12_7(), Circle_12_0(), Circle_12_5(), Colorpicker_12_0(), Curve_34_points_1_0(), Curve_34_points_1_5(), Curve_34_points_2_0(), Curve_34_points_2_5(), Curve_3_points_0_11(), Curve_3_points_0_5(), Curve_4_points_0_5(), Curve_4_points_1_9(), Distort_brush_1_0(), Distort_brush_1_8(), Distort_brush_1_9(), Ellipse_12_0(), Ellipse_12_5(), Filled_polyform_0_8(), Filled_polyform_12_0(), Filled_polyform_12_8(), Freehand_mode1_1_0(), Freehand_mode1_1_2(), Freehand_mode1_2_0(), Freehand_mode1_2_2(), Freehand_mode2_1_0(), Freehand_mode2_1_2(), Freehand_mode2_2_0(), Freehand_mode2_2_2(), Freehand_mode3_1_0(), Freehand_Mode3_2_0(), Grad_circle_0_6(), Grad_circle_12_0(), Grad_circle_12_6(), Grad_circle_or_ellipse_0_8(), Grad_ellipse_0_6(), Grad_ellipse_12_0(), Grad_ellipse_12_6(), Grad_rectangle_0_5(), Grad_rectangle_0_7(), Grad_rectangle_12_0(), Grad_rectangle_12_5(), Grad_rectangle_12_7(), Grad_rectangle_12_9(), K_line_0_6(), K_line_12_0(), K_line_12_6(), K_line_12_7(), Line_12_0(), Line_12_5(), Polybrush_12_8(), Polyfill_0_8(), Polyfill_12_0(), Polyfill_12_8(), Polyfill_12_9(), Polyform_0_8(), Polyform_12_0(), Polyform_12_8(), Polygon_12_0(), Polygon_12_9(), Rectangle_12_0(), Rectangle_12_5(), Rotate_brush_0_5(), Rotate_brush_12_0(), Rotate_brush_1_5(), Scroll_12_0(), Scroll_12_4(), Stretch_brush_0_7(), Stretch_brush_12_0(), and Stretch_brush_1_7().
void Operation_pop (short * value)
Take a value off Operation_stack.
References Operation_stack, and Operation_stack_size.
Referenced by Airbrush_12_2(), Brush_0_5(), Brush_12_5(), Centered_lines_0_3(), Centered_lines_0_7(), Centered_lines_12_3(), Centered_lines_12_7(), Circle_12_5(), Colorpicker_0_1(), Curve_34_points_1_5(), Curve_34_points_2_5(), Curve_3_points_0_11(), Curve_3_points_0_5(), Curve_3_points_12_11(), Curve_4_points_0_5(), Curve_4_points_1_9(), Curve_4_points_2_9(), Distort_brush_0_9(), Distort_brush_1_8(), Distort_brush_1_9(), Distort_brush_2_8(), Ellipse_12_5(), Empty_circle_0_5(), Empty_ellipse_0_5(), Empty_rectangle_0_5(), Filled_circle_0_5(), Filled_contour_0_8(), Filled_ellipse_0_5(), Filled_polyform_0_8(), Filled_polyform_12_8(), Filled_rectangle_0_5(), Freehand_mode1_1_2(), Freehand_mode1_2_2(), Freehand_mode2_1_2(), Freehand_mode2_2_2(), Grad_circle_0_6(), Grad_circle_12_6(), Grad_circle_12_8(), Grad_circle_or_ellipse_0_8(), Grad_ellipse_0_6(), Grad_ellipse_12_6(), Grad_ellipse_12_8(), Grad_rectangle_0_5(), Grad_rectangle_0_9(), Grad_rectangle_12_5(), Grad_rectangle_12_7(), Grad_rectangle_12_9(), K_line_0_6(), K_line_12_6(), K_line_12_7(), Line_0_5(), Line_12_5(), Polybrush_12_8(), Polyfill_0_8(), Polyfill_12_8(), Polyfill_12_9(), Polyform_0_8(), Polyform_12_8(), Polygon_12_9(), Rectangle_12_5(), Rotate_brush_0_5(), Rotate_brush_1_5(), Rotate_brush_2_5(), Scroll_12_4(), Stretch_brush_0_7(), Stretch_brush_1_7(), and Stretch_brush_2_7().
void Freehand_mode1_1_0 (void)
References Backup(), Display_paintbrush(), Fore_color, Init_start_operation(), Operation_push(), Paintbrush_X, Paintbrush_Y, Shade_table, and Shade_table_left.
Referenced by Init_operations().
void Freehand_mode1_1_2 (void)
References Display_cursor(), Draw_line_permanent(), Fore_color, Hide_cursor, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Print_coordinates().
Referenced by Init_operations().
void Freehand_mode12_0_2 (void)
References End_of_modification(), and Operation_stack_size.
Referenced by Init_operations().
void Freehand_mode1_2_0 (void)
References Back_color, Backup(), Display_paintbrush(), Init_start_operation(), Operation_push(), Paintbrush_X, Paintbrush_Y, Shade_table, and Shade_table_right.
Referenced by Init_operations().
void Freehand_mode1_2_2 (void)
References Back_color, Display_cursor(), Draw_line_permanent(), Hide_cursor, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Print_coordinates().
Referenced by Init_operations().
void Freehand_mode2_1_0 (void)
References Airbrush_delay, Airbrush_next_time, Backup(), Display_paintbrush(), Fore_color, Init_start_operation(), Operation_push(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), Shade_table, and Shade_table_left.
Referenced by Init_operations().
void Freehand_mode2_1_2 (void)
References Airbrush_delay, Airbrush_next_time, Display_cursor(), Display_paintbrush(), Fore_color, Hide_cursor, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Print_coordinates().
Referenced by Init_operations().
void Freehand_mode2_2_0 (void)
References Airbrush_delay, Airbrush_next_time, Back_color, Backup(), Display_paintbrush(), Init_start_operation(), Operation_push(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), Shade_table, and Shade_table_right.
Referenced by Init_operations().
void Freehand_mode2_2_2 (void)
References Airbrush_delay, Airbrush_next_time, Back_color, Display_cursor(), Display_paintbrush(), Hide_cursor, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Print_coordinates().
Referenced by Init_operations().
void Freehand_mode3_1_0 (void)
References Backup(), Display_paintbrush(), Fore_color, Init_start_operation(), Operation_push(), Paintbrush_X, Paintbrush_Y, Shade_table, and Shade_table_left.
Referenced by Init_operations().
void Freehand_Mode3_2_0 (void)
References Back_color, Backup(), Display_paintbrush(), Init_start_operation(), Operation_push(), Paintbrush_X, Paintbrush_Y, Shade_table, and Shade_table_right.
Referenced by Init_operations().
void Freehand_mode3_0_1 (void)
References End_of_modification(), and Operation_stack_size.
Referenced by Init_operations().
void Line_12_0 (void)
References Back_color, Backup(), Config, T_Config::Coords_rel, Fore_color, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_shape, Paintbrush_shape_before_operation, PAINTBRUSH_SHAPE_POINT, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview(), Print_in_menu(), Shade_table, Shade_table_left, Shade_table_right, and Update_part_of_screen().
Referenced by Init_operations().
void Line_12_5 (void)
References Back_color, Clamp_coordinates_regular_angle(), Display_coords_rel_or_abs(), Display_cursor(), Draw_line_preview(), Fore_color, Hide_cursor, Hide_line_preview(), LEFT_SIDE, Mouse_K, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Pixel_figure_preview().
Referenced by Init_operations().
void Line_0_5 (void)
References Config, T_Config::Coords_rel, Display_paintbrush(), Draw_line_permanent(), End_of_modification(), Hide_line_preview(), Menu_is_visible, Operation_pop(), Paintbrush_shape, Paintbrush_shape_before_operation, Pixel_figure_preview_auto(), Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Magnifier_12_0 (void)
References Compute_limits(), Compute_paintbrush_coordinates(), Display_all_screen(), Display_cursor(), Limit_bottom, Limit_right, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_magnifier_width, Main_offset_X, Main_offset_Y, Mouse_X, Mouse_Y, Operation_before_interrupt, Pixel_preview, Pixel_preview_magnifier, Position_screen_according_to_zoom(), Start_operation_stack(), and Wait_end_of_click().
Referenced by Init_operations().
void Rectangle_12_0 (void)
References Back_color, Config, T_Config::Coords_rel, Display_cursor(), Fore_color, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_X, Paintbrush_Y, Print_in_menu(), Shade_table, Shade_table_left, and Shade_table_right.
Referenced by Init_operations().
void Rectangle_12_5 (void)
References Config, T_Config::Coords_rel, Menu_is_visible, Num2str(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Empty_rectangle_0_5 (void)
References Backup(), Config, T_Config::Coords_rel, Draw_empty_rectangle(), End_of_modification(), Hide_cursor, Menu_is_visible, Operation_pop(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Filled_rectangle_0_5 (void)
References Backup(), Config, T_Config::Coords_rel, Draw_filled_rectangle(), End_of_modification(), Hide_cursor, Menu_is_visible, Operation_pop(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Circle_12_0 (void)
References Back_color, Backup(), Config, T_Config::Coords_rel, Fore_color, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_shape, Paintbrush_shape_before_operation, PAINTBRUSH_SHAPE_POINT, Paintbrush_X, Paintbrush_Y, Print_in_menu(), Shade_table, Shade_table_left, and Shade_table_right.
Referenced by Init_operations().
void Circle_12_5 (void)
References Circle_limit, Config, T_Config::Coords_rel, Display_cursor(), Distance(), Draw_empty_circle_preview(), Hide_cursor, Hide_empty_circle_preview(), Menu_is_visible, Num2str(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Empty_circle_0_5 (void)
References Circle_limit, Config, T_Config::Coords_rel, Draw_empty_circle_permanent(), End_of_modification(), Hide_empty_circle_preview(), Menu_is_visible, Operation_pop(), Paintbrush_shape, Paintbrush_shape_before_operation, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Filled_circle_0_5 (void)
References Circle_limit, Config, T_Config::Coords_rel, Draw_filled_circle(), End_of_modification(), Hide_empty_circle_preview(), Menu_is_visible, Operation_pop(), Paintbrush_shape, Paintbrush_shape_before_operation, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Ellipse_12_0 (void)
References Back_color, Backup(), Config, T_Config::Coords_rel, Fore_color, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_shape, Paintbrush_shape_before_operation, PAINTBRUSH_SHAPE_POINT, Paintbrush_X, Paintbrush_Y, Print_in_menu(), Shade_table, Shade_table_left, and Shade_table_right.
Referenced by Init_operations().
void Ellipse_12_5 (void)
References Display_coords_rel_or_abs(), Display_cursor(), Draw_empty_ellipse_preview(), Hide_cursor, Hide_empty_ellipse_preview(), Operation_pop(), Operation_push(), Paintbrush_X, and Paintbrush_Y.
Referenced by Init_operations().
void Empty_ellipse_0_5 (void)
References Config, T_Config::Coords_rel, Draw_empty_ellipse_permanent(), End_of_modification(), Hide_empty_ellipse_preview(), Menu_is_visible, Operation_pop(), Paintbrush_shape, Paintbrush_shape_before_operation, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Filled_ellipse_0_5 (void)
References Config, T_Config::Coords_rel, Draw_filled_ellipse(), End_of_modification(), Hide_empty_ellipse_preview(), Menu_is_visible, Operation_pop(), Paintbrush_shape, Paintbrush_shape_before_operation, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Brush_12_0 (void)
References Backup(), Config, T_Config::Coords_rel, Display_cursor(), Init_start_operation(), Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_X, Paintbrush_Y, Print_in_menu(), and RIGHT_SIDE.
Referenced by Init_operations().
void Brush_12_5 (void)
References Config, T_Config::Coords_rel, Menu_is_visible, Num2str(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Brush_0_5 (void)
References T_Config::Adjust_brush_pick, Brush_offset_X, Brush_offset_Y, Capture_brush(), Config, End_of_modification(), Hide_cursor, Operation_pop(), Operation_stack_size, Paintbrush_X, Paintbrush_Y, Return_to_draw_mode(), Snap_height, Snap_mode, and Snap_width.
Referenced by Init_operations().
void Stretch_brush_12_0 (void)
References Config, T_Config::Coords_rel, Display_cursor(), Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_before_interrupt, Operation_push(), Paintbrush_X, Paintbrush_Y, Print_in_menu(), Start_operation_stack(), and Wait_end_of_click().
Referenced by Init_operations().
void Stretch_brush_1_7 (void)
References T_Config::Adjust_brush_pick, Config, T_Config::Coords_rel, Display_all_screen(), Display_cursor(), Hide_cursor, Menu_is_visible, Num2str(), Operation_pop(), Operation_push(), Operation_stack_size, Paintbrush_X, Paintbrush_Y, Print_coordinates(), Print_in_menu(), Snap_mode, and Stretch_brush_preview().
Referenced by Init_operations().
void Stretch_brush_0_7 (void)
References Brush_height, Brush_width, byte, Config, T_Config::Coords_rel, Display_all_screen(), Display_cursor(), Key_ANSI, Menu_is_visible, Num2str(), Operation_pop(), Operation_push(), Operation_stack_size, Paintbrush_X, Paintbrush_Y, Print_coordinates(), Print_in_menu(), and Stretch_brush_preview().
Referenced by Init_operations().
void Stretch_brush_2_7 (void)
References Display_all_screen(), Operation_pop(), Operation_stack_size, Return_to_draw_mode(), and Stretch_brush().
Referenced by Init_operations().
void Rotate_brush_12_0 (void)
References Brush_rotation_center_is_defined, Brush_rotation_center_X, Brush_rotation_center_Y, Brush_width, Config, T_Config::Coords_rel, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_before_interrupt, Operation_push(), Paintbrush_X, Paintbrush_Y, Print_in_menu(), Start_operation_stack(), and Wait_end_of_click().
Referenced by Init_operations().
void Rotate_brush_1_5 (void)
References Brush_rotation_center_X, Brush_rotation_center_Y, Config, T_Config::Coords_rel, Display_all_screen(), Display_cursor(), M_2PI, Menu_is_visible, Num2str(), Operation_pop(), Operation_push(), Operation_stack_size, Paintbrush_X, Paintbrush_Y, Print_coordinates(), Print_in_menu(), and Rotate_brush_preview().
Referenced by Init_operations().
void Rotate_brush_0_5 (void)
References Brush_rotation_center_X, Brush_rotation_center_Y, byte, Config, T_Config::Coords_rel, Display_all_screen(), Display_cursor(), Key_ANSI, M_2PI, Menu_is_visible, Num2str(), Operation_pop(), Operation_push(), Operation_stack_size, Paintbrush_X, Paintbrush_Y, Print_coordinates(), Print_in_menu(), Rotate_brush_preview(), and Round().
Referenced by Init_operations().
void Rotate_brush_2_5 (void)
References Brush_rotation_center_X, Brush_rotation_center_Y, Display_all_screen(), M_2PI, Operation_pop(), Operation_stack_size, Return_to_draw_mode(), and Rotate_brush().
Referenced by Init_operations().
void Distort_brush_0_0 (void)
References Menu_is_visible, and Print_in_menu().
Referenced by Init_operations().
void Distort_brush_1_0 (void)
References Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, Config, T_Config::Coords_rel, Display_cursor(), Distort_brush_preview(), Draw_stretch_spot(), Hide_cursor, Init_start_operation(), Menu_is_visible, Operation_push(), Operation_stack, Paintbrush_hidden, Paintbrush_X, Paintbrush_Y, Print_in_menu(), Update_part_of_screen(), and Wait_end_of_click().
Referenced by Init_operations().
void Distort_brush_2_0 (void)
References Config, T_Config::Coords_rel, Display_all_screen(), Menu_is_visible, Paintbrush_hidden, Print_in_menu(), and Return_to_draw_mode().
Referenced by Init_operations().
void Distort_brush_1_8 (void)
References Config, T_Config::Coords_rel, Distance(), Menu_is_visible, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), Print_in_menu(), and REACH_DISTANCE.
Referenced by Init_operations().
void Distort_brush_2_8 (void)
References Display_all_screen(), Distort_brush(), Operation_pop(), Paintbrush_hidden, and Return_to_draw_mode().
Referenced by Init_operations().
void Distort_brush_1_9 (void)
References Config, T_Config::Coords_rel, Display_all_screen(), Display_cursor(), Distort_brush_preview(), Draw_stretch_spot(), Hide_cursor, Menu_is_visible, Menu_Y, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), Print_in_menu(), Screen_width, and Update_rect().
Referenced by Init_operations().
void Distort_brush_0_9 (void)
References Operation_pop().
Referenced by Init_operations().
void Polybrush_12_8 (void)
References T_Config::Adjust_brush_pick, Brush_offset_X, Brush_offset_Y, Capture_brush_with_lasso(), Config, Display_all_screen(), Display_cursor(), Draw_line_preview_xor(), End_of_modification(), Hide_cursor, Mouse_K, T_Config::Nb_max_vertices_per_polygon, Operation_pop(), Operation_push(), Paintbrush_hidden, Paintbrush_X, Paintbrush_Y, Polyfill_number_of_points, Polyfill_table_of_points, Print_coordinates(), Return_to_draw_mode(), RIGHT_SIDE, Snap_height, Snap_mode, and Snap_width.
Referenced by Init_operations().
void Fill_1_0 (void)
References Display_cursor(), End_of_modification(), Fill_general(), Fore_color, Hide_cursor, Shade_table, Shade_table_left, and Wait_end_of_click().
Referenced by Init_operations().
void Fill_2_0 (void)
References Back_color, Display_cursor(), End_of_modification(), Fill_general(), Hide_cursor, Shade_table, Shade_table_right, and Wait_end_of_click().
Referenced by Init_operations().
void Replace_1_0 (void)
References Backup(), Display_cursor(), End_of_modification(), Fore_color, Hide_cursor, Replace(), and Wait_end_of_click().
Referenced by Init_operations().
void Replace_2_0 (void)
References Back_color, Backup(), Display_cursor(), End_of_modification(), Hide_cursor, Replace(), and Wait_end_of_click().
Referenced by Init_operations().
void Pipette_0_0 (void)
void Colorpicker_12_0 (void)
References Colorpicker_color, Init_start_operation(), LEFT_SIDE, Mouse_K, Operation_push(), Set_back_color(), and Set_fore_color().
Referenced by Init_operations().
void Colorpicker_1_1 (void)
References Colorpicker_color, Colorpicker_X, Colorpicker_Y, Display_cursor(), Fore_color, Hide_cursor, Main_image_height, Main_image_width, Menu_factor_X, Menu_is_visible, Menu_status_Y, Num2str(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), Print_general(), Print_in_menu(), Read_pixel_from_current_screen(), and Set_fore_color().
Referenced by Init_operations().
void Colorpicker_2_1 (void)
References Back_color, Colorpicker_color, Colorpicker_X, Colorpicker_Y, Display_cursor(), Hide_cursor, Main_image_height, Main_image_width, Menu_factor_X, Menu_is_visible, Menu_status_Y, Num2str(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), Print_general(), Print_in_menu(), Read_pixel_from_current_screen(), and Set_back_color().
Referenced by Init_operations().
void Colorpicker_0_1 (void)
References BUTTON_COLORPICKER, Colorpicker_color, LEFT_SIDE, Operation_pop(), Set_back_color(), Set_fore_color(), and Unselect_button().
Referenced by Init_operations().
void K_line_12_0 (void)
References Back_color, Backup(), byte, Config, T_Config::Coords_rel, Fore_color, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_shape, Paintbrush_shape_before_operation, PAINTBRUSH_SHAPE_POINT, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview(), Print_in_menu(), Shade_table, Shade_table_left, and Shade_table_right.
Referenced by Init_operations().
void K_line_12_6 (void)
References Display_coords_rel_or_abs(), Display_cursor(), Draw_line_preview(), Hide_cursor, Hide_line_preview(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Pixel_figure_preview().
Referenced by Init_operations().
void K_line_0_6 (void)
References Config, T_Config::Coords_rel, Display_paintbrush(), Draw_line_permanent(), Hide_line_preview(), Menu_is_visible, Operation_pop(), Operation_push(), Paintbrush_shape, Paintbrush_shape_before_operation, PAINTBRUSH_SHAPE_POINT, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview_auto(), and Print_in_menu().
Referenced by Init_operations().
void K_line_12_7 (void)
References Config, T_Config::Coords_rel, Display_cursor(), End_of_modification(), Hide_cursor, Hide_line_preview(), Menu_is_visible, Mouse_K, Operation_pop(), Operation_push(), Paintbrush_shape, Paintbrush_shape_before_operation, Pixel_figure_preview_auto(), Print_coordinates(), Print_in_menu(), and Wait_end_of_click().
Referenced by Init_operations().
void Curve_34_points_1_0 (void)
References Backup(), Config, T_Config::Coords_rel, Fore_color, Init_start_operation(), Menu_is_visible, Operation_push(), Paintbrush_hidden, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview(), Print_in_menu(), Shade_table, Shade_table_left, and Update_part_of_screen().
Referenced by Init_operations().
void Curve_34_points_2_0 (void)
References Back_color, Backup(), Config, T_Config::Coords_rel, Init_start_operation(), Menu_is_visible, Operation_push(), Paintbrush_hidden, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview(), Print_in_menu(), Shade_table, Shade_table_right, and Update_part_of_screen().
Referenced by Init_operations().
void Curve_34_points_1_5 (void)
References Display_coords_rel_or_abs(), Display_cursor(), Draw_line_preview(), Fore_color, Hide_cursor, Hide_line_preview(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Pixel_figure_preview().
Referenced by Init_operations().
void Curve_34_points_2_5 (void)
References Back_color, Display_coords_rel_or_abs(), Display_cursor(), Draw_line_preview(), Hide_cursor, Hide_line_preview(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Pixel_figure_preview().
Referenced by Init_operations().
void Curve_4_points_0_5 (void)
References Config, T_Config::Coords_rel, Cursor_hidden, Cursor_hidden_before_curve, Draw_curve_cross(), Draw_curve_preview(), Hide_line_preview(), Menu_is_visible, Operation_pop(), Operation_push(), Print_coordinates(), Print_in_menu(), and Round_div().
Referenced by Init_operations().
void Curve_4_points_1_9 (void)
References byte, Display_cursor(), Distance(), Draw_curve_cross(), Draw_curve_preview(), Hide_cursor, Hide_curve_preview(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Print_coordinates().
Referenced by Init_operations().
void Curve_4_points_2_9 (void)
References Cursor_hidden, Cursor_hidden_before_curve, Display_cursor(), Draw_curve_cross(), Draw_curve_permanent(), End_of_modification(), Hide_cursor, Hide_curve_preview(), Operation_pop(), Paintbrush_hidden, and Wait_end_of_click().
Referenced by Init_operations().
void Curve_3_points_0_5 (void)
References Compute_3_point_curve(), Config, T_Config::Coords_rel, Draw_curve_preview(), Hide_line_preview(), Menu_is_visible, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Curve_3_points_0_11 (void)
References Compute_3_point_curve(), Display_cursor(), Draw_curve_preview(), Hide_cursor, Hide_curve_preview(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Print_coordinates().
Referenced by Init_operations().
void Curve_3_points_12_11 (void)
References Compute_3_point_curve(), Display_cursor(), Draw_curve_permanent(), End_of_modification(), Hide_cursor, Hide_curve_preview(), Operation_pop(), Paintbrush_hidden, and Wait_end_of_click().
Referenced by Init_operations().
void Airbrush_1_0 (void)
References Airbrush(), Airbrush_delay, Airbrush_next_time, Backup(), Init_start_operation(), LEFT_SIDE, Operation_push(), Paintbrush_X, Paintbrush_Y, Shade_table, and Shade_table_left.
Referenced by Init_operations().
void Airbrush_2_0 (void)
References Airbrush(), Airbrush_delay, Airbrush_next_time, Backup(), Init_start_operation(), Operation_push(), Paintbrush_X, Paintbrush_Y, RIGHT_SIDE, Shade_table, and Shade_table_right.
Referenced by Init_operations().
void Airbrush_12_2 (void)
References Airbrush(), Airbrush_delay, Airbrush_next_time, Display_cursor(), Hide_cursor, Menu_is_visible, Mouse_K_unique, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Print_coordinates().
Referenced by Init_operations().
void Airbrush_0_2 (void)
References End_of_modification(), and Operation_stack_size.
Referenced by Init_operations().
void Polygon_12_0 (void)
References Back_color, Backup(), byte, Config, T_Config::Coords_rel, Fore_color, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_shape, Paintbrush_shape_before_operation, PAINTBRUSH_SHAPE_POINT, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview(), Print_in_menu(), Shade_table, Shade_table_left, Shade_table_right, and Update_part_of_screen().
Referenced by Init_operations().
void Polygon_12_9 (void)
References Config, T_Config::Coords_rel, Display_cursor(), Draw_line_permanent(), End_of_modification(), Hide_cursor, Hide_line_preview(), Menu_is_visible, Mouse_K, Operation_pop(), Operation_push(), Paintbrush_shape, Paintbrush_shape_before_operation, PAINTBRUSH_SHAPE_POINT, Pixel_figure_preview_auto(), Print_coordinates(), Print_in_menu(), and Wait_end_of_click().
Referenced by Init_operations().
void Polyfill_12_0 (void)
References Back_color, Backup(), byte, Config, T_Config::Coords_rel, Fore_color, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, T_Config::Nb_max_vertices_per_polygon, Operation_push(), Paintbrush_hidden, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview_xor(), Polyfill_number_of_points, Polyfill_table_of_points, Print_in_menu(), Shade_table, Shade_table_left, Shade_table_right, and Update_part_of_screen().
Referenced by Init_operations().
void Polyfill_0_8 (void)
References Config, T_Config::Coords_rel, Draw_line_preview_xor(), Menu_is_visible, T_Config::Nb_max_vertices_per_polygon, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Polyfill_number_of_points, Polyfill_table_of_points, and Print_in_menu().
Referenced by Init_operations().
void Polyfill_12_8 (void)
References Display_coords_rel_or_abs(), Display_cursor(), Draw_line_preview_xor(), Hide_cursor, Operation_pop(), Operation_push(), Paintbrush_X, and Paintbrush_Y.
Referenced by Init_operations().
void Polyfill_12_9 (void)
References Config, T_Config::Coords_rel, Display_all_screen(), Display_cursor(), Draw_line_preview_xor(), End_of_modification(), Hide_cursor, Menu_is_visible, Mouse_K, Operation_pop(), Operation_push(), Paintbrush_hidden, Polyfill(), Polyfill_number_of_points, Polyfill_table_of_points, Print_coordinates(), Print_in_menu(), and Wait_end_of_click().
Referenced by Init_operations().
void Polyform_12_0 (void)
References Back_color, Backup(), Display_paintbrush(), Fore_color, Init_start_operation(), LEFT_SIDE, Mouse_K, Operation_push(), Paintbrush_X, Paintbrush_Y, Pixel_figure_preview(), Shade_table, Shade_table_left, and Shade_table_right.
Referenced by Init_operations().
void Polyform_12_8 (void)
References Display_cursor(), Draw_line_permanent(), End_of_modification(), Hide_cursor, Hide_line_preview(), Mouse_K, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Pixel_figure_preview(), Pixel_figure_preview_auto(), Print_coordinates(), and Wait_end_of_click().
Referenced by Init_operations().
void Polyform_0_8 (void)
References Display_cursor(), Draw_line_preview(), Hide_cursor, Hide_line_preview(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Print_coordinates().
Referenced by Init_operations().
void Filled_polyform_12_0 (void)
References Back_color, Backup(), Config, Current_operation, Fore_color, Init_start_operation(), LEFT_SIDE, Mouse_K, T_Config::Nb_max_vertices_per_polygon, OPERATION_FILLED_CONTOUR, OPERATION_FILLED_POLYFORM, Operation_push(), Paintbrush_hidden, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview_xor(), Polyfill_number_of_points, Polyfill_table_of_points, RIGHT_SIDE, Shade_table, Shade_table_left, Shade_table_right, and Update_part_of_screen().
Referenced by Init_operations().
void Filled_polyform_12_8 (void)
References Config, Current_operation, Display_all_screen(), Display_cursor(), Draw_line_preview_xor(), Draw_line_preview_xorback(), End_of_modification(), Hide_cursor, Mouse_K, T_Config::Nb_max_vertices_per_polygon, OPERATION_FILLED_CONTOUR, Operation_pop(), Operation_push(), Paintbrush_hidden, Paintbrush_X, Paintbrush_Y, Polyfill(), Polyfill_number_of_points, Polyfill_table_of_points, Print_coordinates(), and Wait_end_of_click().
Referenced by Init_operations().
void Filled_polyform_0_8 (void)
References Display_cursor(), Draw_line_preview_xor(), Hide_cursor, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Print_coordinates().
Referenced by Init_operations().
void Filled_contour_0_8 (void)
References Display_all_screen(), Display_cursor(), End_of_modification(), Hide_cursor, Operation_pop(), Paintbrush_hidden, Polyfill(), Polyfill_number_of_points, Polyfill_table_of_points, and Print_coordinates().
Referenced by Init_operations().
void Scroll_12_0 (void)
References Backup(), Config, T_Config::Coords_rel, Cursor_hidden, Cursor_hidden_before_scroll, Init_start_operation(), Menu_is_visible, Operation_push(), Paintbrush_X, Paintbrush_Y, and Print_in_menu().
Referenced by Init_operations().
void Scroll_12_4 (void)
References Display_all_screen(), Display_coords_rel_or_abs(), Main_image_height, Main_image_width, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Scroll_picture().
Referenced by Init_operations().
void Scroll_0_4 (void)
References Config, T_Config::Coords_rel, Cursor_hidden, Cursor_hidden_before_scroll, End_of_modification(), Menu_is_visible, Operation_stack_size, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Grad_circle_12_0 (void)
References Back_color, Backup(), byte, Config, T_Config::Coords_rel, Fore_color, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_hidden, Paintbrush_hidden_before_scroll, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview(), Print_in_menu(), Shade_table, Shade_table_left, Shade_table_right, and Update_part_of_screen().
Referenced by Init_operations().
void Grad_circle_12_6 (void)
References Circle_limit, Config, T_Config::Coords_rel, Display_cursor(), Distance(), Draw_empty_circle_preview(), Hide_cursor, Hide_empty_circle_preview(), Menu_is_visible, Num2str(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Grad_circle_0_6 (void)
References Back_color, Circle_limit, Config, T_Config::Coords_rel, Cursor_shape, CURSOR_SHAPE_TARGET, CURSOR_SHAPE_XOR_TARGET, Display_coords_rel_or_abs(), Draw_curve_cross(), Draw_filled_circle(), End_of_modification(), Hide_empty_circle_preview(), LEFT_SIDE, Menu_is_visible, Operation_pop(), Operation_push(), Paintbrush_hidden, Paintbrush_hidden_before_scroll, Paintbrush_X, Paintbrush_Y, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Grad_circle_12_8 (void)
References Circle_limit, Config, T_Config::Coords_rel, Cursor_shape, CURSOR_SHAPE_TARGET, Display_cursor(), Draw_curve_cross(), Draw_grad_circle(), End_of_modification(), Hide_cursor, Hide_empty_circle_preview(), Menu_is_visible, Mouse_K, Operation_pop(), Operation_stack_size, Paintbrush_hidden, Paintbrush_hidden_before_scroll, Paintbrush_X, Paintbrush_Y, Print_coordinates(), Print_in_menu(), and Wait_end_of_click().
Referenced by Init_operations().
void Grad_circle_or_ellipse_0_8 (void)
References Display_coords_rel_or_abs(), Operation_pop(), Operation_push(), Paintbrush_X, and Paintbrush_Y.
Referenced by Init_operations().
void Grad_ellipse_12_0 (void)
References Back_color, Backup(), byte, Config, T_Config::Coords_rel, Fore_color, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_hidden, Paintbrush_hidden_before_scroll, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview(), Print_in_menu(), Shade_table, Shade_table_left, Shade_table_right, and Update_part_of_screen().
Referenced by Init_operations().
void Grad_ellipse_12_6 (void)
References Display_coords_rel_or_abs(), Display_cursor(), Draw_empty_ellipse_preview(), Hide_cursor, Hide_empty_ellipse_preview(), Operation_pop(), Operation_push(), Paintbrush_X, and Paintbrush_Y.
Referenced by Init_operations().
void Grad_ellipse_0_6 (void)
References Back_color, Config, T_Config::Coords_rel, Cursor_shape, CURSOR_SHAPE_TARGET, CURSOR_SHAPE_XOR_TARGET, Display_coords_rel_or_abs(), Draw_curve_cross(), Draw_filled_ellipse(), End_of_modification(), Hide_empty_ellipse_preview(), LEFT_SIDE, Menu_is_visible, Operation_pop(), Operation_push(), Paintbrush_hidden, Paintbrush_hidden_before_scroll, Paintbrush_X, Paintbrush_Y, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Grad_ellipse_12_8 (void)
References Config, T_Config::Coords_rel, Cursor_shape, CURSOR_SHAPE_TARGET, Display_cursor(), Draw_curve_cross(), Draw_grad_ellipse(), End_of_modification(), Hide_cursor, Hide_empty_ellipse_preview(), Menu_is_visible, Mouse_K, Operation_pop(), Operation_stack_size, Paintbrush_hidden, Paintbrush_hidden_before_scroll, Paintbrush_X, Paintbrush_Y, Print_coordinates(), Print_in_menu(), and Wait_end_of_click().
Referenced by Init_operations().
void Grad_rectangle_12_0 (void)
References Backup(), Config, T_Config::Coords_rel, Display_cursor(), Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_X, Paintbrush_Y, Print_in_menu(), Shade_table, Shade_table_left, and Shade_table_right.
Referenced by Init_operations().
void Grad_rectangle_12_5 (void)
References Config, T_Config::Coords_rel, Menu_is_visible, Num2str(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Print_coordinates(), and Print_in_menu().
Referenced by Init_operations().
void Grad_rectangle_0_5 (void)
References Hide_cursor, Horizontal_XOR_line, Horizontal_XOR_line_zoom(), Limit_left_zoom, Limit_top_zoom, Limit_visible_bottom_zoom, Limit_visible_right_zoom, Main_image_height, Main_image_width, Main_magnifier_mode, Main_offset_X, Main_offset_Y, Main_separator_position, Max(), Menu_Y, Min(), Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Screen_width, Update_rect(), Vertical_XOR_line, and Vertical_XOR_line_zoom().
Referenced by Init_operations().
void Grad_rectangle_0_7 (void)
References Operation_push(), Operation_stack_size, Paintbrush_X, Paintbrush_Y, and Print_coordinates().
Referenced by Init_operations().
void Grad_rectangle_12_7 (void)
References Horizontal_XOR_line, Horizontal_XOR_line_zoom(), Limit_left_zoom, Limit_top_zoom, Limit_visible_bottom_zoom, Limit_visible_right_zoom, Main_image_height, Main_image_width, Main_magnifier_mode, Main_offset_X, Main_offset_Y, Main_separator_position, Max(), Menu_Y, Min(), Mouse_K, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, Screen_width, Update_rect(), Vertical_XOR_line, and Vertical_XOR_line_zoom().
Referenced by Init_operations().
void Grad_rectangle_12_9 (void)
References Clamp_coordinates_regular_angle(), Display_coords_rel_or_abs(), Draw_line_preview_xor(), Operation_pop(), Operation_push(), Paintbrush_X, and Paintbrush_Y.
Referenced by Init_operations().
void Grad_rectangle_0_9 (void)
References Config, T_Config::Coords_rel, Display_cursor(), Draw_grad_rectangle(), End_of_modification(), Hide_cursor, Hide_line_preview(), Horizontal_XOR_line, Horizontal_XOR_line_zoom(), Limit_left_zoom, Limit_top_zoom, Limit_visible_bottom_zoom, Limit_visible_right_zoom, Main_image_height, Main_image_width, Main_magnifier_mode, Main_offset_X, Main_offset_Y, Main_separator_position, Max(), Menu_is_visible, Menu_Y, Min(), Operation_pop(), Operation_stack_size, Print_coordinates(), Print_in_menu(), Screen_width, Update_rect(), Vertical_XOR_line, Vertical_XOR_line_zoom(), and Wait_end_of_click().
Referenced by Init_operations().
void Centered_lines_12_0 (void)
References Backup(), Config, T_Config::Coords_rel, Init_start_operation(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_push(), Paintbrush_X, Paintbrush_Y, Print_in_menu(), Shade_table, Shade_table_left, and Shade_table_right.
Referenced by Init_operations().
void Centered_lines_12_3 (void)
References Operation_pop(), Operation_push(), Paintbrush_X, and Paintbrush_Y.
Referenced by Init_operations().
void Centered_lines_0_3 (void)
References Back_color, Fore_color, LEFT_SIDE, Operation_pop(), Operation_push(), Paintbrush_shape, Paintbrush_shape_before_operation, PAINTBRUSH_SHAPE_POINT, Paintbrush_X, Paintbrush_Y, and Pixel_figure_preview().
Referenced by Init_operations().
void Centered_lines_12_7 (void)
References Back_color, Config, T_Config::Coords_rel, Display_cursor(), Display_paintbrush(), Draw_line_permanent(), Draw_line_preview(), End_of_modification(), Fore_color, Hide_cursor, Hide_line_preview(), LEFT_SIDE, Menu_is_visible, Mouse_K, Operation_pop(), Operation_push(), Paintbrush_shape, Paintbrush_shape_before_operation, PAINTBRUSH_SHAPE_POINT, Paintbrush_X, Paintbrush_Y, Pixel_figure_preview(), Pixel_figure_preview_auto(), Print_coordinates(), Print_in_menu(), Smear_start, and Wait_end_of_click().
Referenced by Init_operations().
void Centered_lines_0_7 (void)
References Back_color, Display_coords_rel_or_abs(), Display_cursor(), Draw_line_preview(), Fore_color, Hide_cursor, Hide_line_preview(), LEFT_SIDE, Operation_pop(), Operation_push(), Paintbrush_X, Paintbrush_Y, and Pixel_figure_preview().
Referenced by Init_operations().