GrafX2: pages.c File Reference
pages.c File Reference
#include <stddef.h>
#include <string.h>
#include <stdlib.h>
#include "global.h"
#include "pages.h"
#include "erreurs.h"
#include "divers.h"
#include "windows.h"
Functions
void Initialiser_S_Page (S_Page *Page)
GESTION DES PAGES.
void Download_infos_page_principal (S_Page *Page)
void Upload_infos_page_principal (S_Page *Page)
void Download_infos_page_brouillon (S_Page *Page)
void Upload_infos_page_brouillon (S_Page *Page)
void Download_infos_backup (S_Liste_de_pages *Liste)
int Allouer_une_page (S_Page *Page, int Largeur, int Hauteur)
void Liberer_une_page (S_Page *Page)
void Copier_S_page (S_Page *Destination, S_Page *Source)
int Taille_d_une_page (S_Page *Page)
void Initialiser_S_Liste_de_pages (S_Liste_de_pages *Liste)
GESTION DES LISTES DE PAGES.
int Allouer_une_liste_de_pages (S_Liste_de_pages *Liste, int Taille)
void Liberer_une_liste_de_pages (S_Liste_de_pages *Liste)
int Taille_d_une_liste_de_pages (S_Liste_de_pages *Liste)
void Reculer_dans_une_liste_de_pages (S_Liste_de_pages *Liste)
void Avancer_dans_une_liste_de_pages (S_Liste_de_pages *Liste)
int Nouvelle_page_possible (S_Page *Nouvelle_page, S_Liste_de_pages *Liste_courante, S_Liste_de_pages *Liste_secondaire)
void Detruire_derniere_page_allouee_de_la_liste (S_Liste_de_pages *Liste)
void Creer_nouvelle_page (S_Page *Nouvelle_page, S_Liste_de_pages *Liste_courante, S_Liste_de_pages *Liste_secondaire)
void Changer_nombre_de_pages_d_une_liste (S_Liste_de_pages *Liste, int Nb)
void Detruire_la_page_courante_d_une_liste (S_Liste_de_pages *Liste)
int Initialiser_les_listes_de_backups_en_debut_de_programme (int Taille, int Largeur, int Hauteur)
GESTION DES BACKUPS.
void Detruire_les_listes_de_backups_en_fin_de_programme (void)
void Nouveau_nombre_de_backups (int Nouveau)
int Backup_avec_nouvelles_dimensions (int Upload, int Largeur, int Hauteur)
int Backuper_et_redimensionner_brouillon (int Largeur, int Hauteur)
void Backup (void)
void Undo (void)
void Redo (void)
void Detruire_la_page_courante (void)
void Interchanger_image_principale_et_brouillon (void)
int Emprunt_memoire_de_page_possible (int taille)
GESTION DES EMPRUNTS DE MEMOIRE DE PAGE.
void * Emprunter_memoire_de_page (int taille)
Function Documentation
void Initialiser_S_Page (S_Page * Page)
GESTION DES PAGES.
References S_Page::Commentaire, S_Page::Format_fichier, FORMAT_PAR_DEFAUT, S_Page::Hauteur, S_Page::Image, S_Page::Largeur, S_Page::Nom_fichier, S_Page::Palette, and S_Page::Repertoire_fichier.
Referenced by Allouer_une_liste_de_pages(), Avancer_dans_une_liste_de_pages(), Backup(), Backup_avec_nouvelles_dimensions(), Backuper_et_redimensionner_brouillon(), Changer_nombre_de_pages_d_une_liste(), Initialiser_les_listes_de_backups_en_debut_de_programme(), and Reculer_dans_une_liste_de_pages().
void Download_infos_page_principal (S_Page * Page)
References Calculer_coordonnees_pinceau(), Calculer_limites(), S_Page::Commentaire, S_Page::Format_fichier, S_Page::Hauteur, S_Page::Image, S_Page::Largeur, Loupe_Mode, S_Page::Nom_fichier, S_Page::Palette, Pixel_Preview, Pixel_Preview_Normal, Principal_Commentaire, Principal_Decalage_X, Principal_Decalage_Y, Principal_Ecran, Principal_Format_fichier, Principal_Hauteur_image, Principal_Largeur_image, Principal_Nom_fichier, Principal_Palette, Principal_Repertoire_fichier, and S_Page::Repertoire_fichier.
Referenced by Backup(), Backup_avec_nouvelles_dimensions(), Charger_image(), Detruire_la_page_courante(), Initialiser_les_listes_de_backups_en_debut_de_programme(), Interchanger_image_principale_et_brouillon(), Redo(), and Undo().
void Upload_infos_page_principal (S_Page * Page)
References S_Page::Commentaire, S_Page::Format_fichier, S_Page::Hauteur, S_Page::Image, S_Page::Largeur, S_Page::Nom_fichier, S_Page::Palette, Principal_Commentaire, Principal_Ecran, Principal_Format_fichier, Principal_Hauteur_image, Principal_Largeur_image, Principal_Nom_fichier, Principal_Palette, Principal_Repertoire_fichier, and S_Page::Repertoire_fichier.
Referenced by Backup(), Backup_avec_nouvelles_dimensions(), Bouton_Load(), Bouton_Reload(), Initialiser_les_listes_de_backups_en_debut_de_programme(), Interchanger_image_principale_et_brouillon(), Redo(), and Undo().
void Download_infos_page_brouillon (S_Page * Page)
References Brouillon_Commentaire, Brouillon_Ecran, Brouillon_Format_fichier, Brouillon_Hauteur_image, Brouillon_Largeur_image, Brouillon_Nom_fichier, Brouillon_Palette, Brouillon_Repertoire_fichier, S_Page::Commentaire, S_Page::Format_fichier, S_Page::Hauteur, S_Page::Image, S_Page::Largeur, S_Page::Nom_fichier, S_Page::Palette, and S_Page::Repertoire_fichier.
Referenced by Backuper_et_redimensionner_brouillon(), Initialiser_les_listes_de_backups_en_debut_de_programme(), and Interchanger_image_principale_et_brouillon().
void Upload_infos_page_brouillon (S_Page * Page)
References Brouillon_Commentaire, Brouillon_Ecran, Brouillon_Format_fichier, Brouillon_Hauteur_image, Brouillon_Largeur_image, Brouillon_Nom_fichier, Brouillon_Palette, Brouillon_Repertoire_fichier, S_Page::Commentaire, S_Page::Format_fichier, S_Page::Hauteur, S_Page::Image, S_Page::Largeur, S_Page::Nom_fichier, S_Page::Palette, and S_Page::Repertoire_fichier.
Referenced by Backuper_et_redimensionner_brouillon(), and Interchanger_image_principale_et_brouillon().
void Download_infos_backup (S_Liste_de_pages * Liste)
References Config, Ecran_backup, S_Config::FX_Feedback, FX_Feedback_Ecran, S_Page::Image, and S_Liste_de_pages::Pages.
Referenced by Backup(), Backup_avec_nouvelles_dimensions(), Detruire_la_page_courante(), Initialiser_les_listes_de_backups_en_debut_de_programme(), Interchanger_image_principale_et_brouillon(), Redo(), and Undo().
int Allouer_une_page (S_Page * Page, int Largeur, int Hauteur)
References S_Page::Hauteur, S_Page::Image, and S_Page::Largeur.
void Liberer_une_page (S_Page * Page)
References S_Page::Hauteur, S_Page::Image, and S_Page::Largeur.
Referenced by Changer_nombre_de_pages_d_une_liste(), and Detruire_derniere_page_allouee_de_la_liste().
void Copier_S_page (S_Page * Destination, S_Page * Source)
Referenced by Avancer_dans_une_liste_de_pages(), Backup(), Changer_nombre_de_pages_d_une_liste(), Creer_nouvelle_page(), and Reculer_dans_une_liste_de_pages().
int Taille_d_une_page (S_Page * Page)
References S_Page::Hauteur, and S_Page::Largeur.
Referenced by Emprunt_memoire_de_page_possible(), Nouvelle_page_possible(), and Taille_d_une_liste_de_pages().
void Initialiser_S_Liste_de_pages (S_Liste_de_pages * Liste)
GESTION DES LISTES DE PAGES.
References S_Liste_de_pages::Nb_pages_allouees, S_Liste_de_pages::Pages, and S_Liste_de_pages::Taille_liste.
Referenced by Initialisation_du_programme().
int Allouer_une_liste_de_pages (S_Liste_de_pages * Liste, int Taille)
References Initialiser_S_Page(), S_Liste_de_pages::Nb_pages_allouees, S_Liste_de_pages::Pages, and S_Liste_de_pages::Taille_liste.
Referenced by Initialiser_les_listes_de_backups_en_debut_de_programme().
void Liberer_une_liste_de_pages (S_Liste_de_pages * Liste)
References S_Liste_de_pages::Nb_pages_allouees, S_Liste_de_pages::Pages, and S_Liste_de_pages::Taille_liste.
Referenced by Detruire_les_listes_de_backups_en_fin_de_programme().
int Taille_d_une_liste_de_pages (S_Liste_de_pages * Liste)
References S_Liste_de_pages::Nb_pages_allouees, S_Liste_de_pages::Pages, and Taille_d_une_page().
Referenced by Emprunt_memoire_de_page_possible(), and Nouvelle_page_possible().
void Reculer_dans_une_liste_de_pages (S_Liste_de_pages * Liste)
References Copier_S_page(), Initialiser_S_Page(), S_Liste_de_pages::Nb_pages_allouees, and S_Liste_de_pages::Pages.
Referenced by Detruire_la_page_courante_d_une_liste(), and Undo().
void Avancer_dans_une_liste_de_pages (S_Liste_de_pages * Liste)
References Copier_S_page(), Initialiser_S_Page(), S_Liste_de_pages::Nb_pages_allouees, and S_Liste_de_pages::Pages.
Referenced by Redo().
int Nouvelle_page_possible (S_Page * Nouvelle_page, S_Liste_de_pages * Liste_courante, S_Liste_de_pages * Liste_secondaire)
References Memoire_libre(), S_Liste_de_pages::Pages, QUANTITE_MINIMALE_DE_MEMOIRE_A_CONSERVER, Taille_d_une_liste_de_pages(), and Taille_d_une_page().
Referenced by Backup_avec_nouvelles_dimensions(), Backuper_et_redimensionner_brouillon(), and Initialiser_les_listes_de_backups_en_debut_de_programme().
void Detruire_derniere_page_allouee_de_la_liste (S_Liste_de_pages * Liste)
References Liberer_une_page(), S_Liste_de_pages::Nb_pages_allouees, and S_Liste_de_pages::Pages.
Referenced by Creer_nouvelle_page(), Detruire_la_page_courante_d_une_liste(), Detruire_les_listes_de_backups_en_fin_de_programme(), and Emprunter_memoire_de_page().
void Creer_nouvelle_page (S_Page * Nouvelle_page, S_Liste_de_pages * Liste_courante, S_Liste_de_pages * Liste_secondaire)
References Copier_S_page(), Detruire_derniere_page_allouee_de_la_liste(), Erreur, ERREUR_SORRY_SORRY_SORRY, S_Page::Hauteur, S_Page::Image, S_Page::Largeur, Memoire_libre(), S_Liste_de_pages::Nb_pages_allouees, S_Liste_de_pages::Pages, QUANTITE_MINIMALE_DE_MEMOIRE_A_CONSERVER, and S_Liste_de_pages::Taille_liste.
Referenced by Backup(), Backup_avec_nouvelles_dimensions(), Backuper_et_redimensionner_brouillon(), and Initialiser_les_listes_de_backups_en_debut_de_programme().
void Changer_nombre_de_pages_d_une_liste (S_Liste_de_pages * Liste, int Nb)
References Copier_S_page(), Initialiser_S_Page(), Liberer_une_page(), Min(), S_Liste_de_pages::Nb_pages_allouees, S_Liste_de_pages::Pages, and S_Liste_de_pages::Taille_liste.
Referenced by Nouveau_nombre_de_backups().
void Detruire_la_page_courante_d_une_liste (S_Liste_de_pages * Liste)
References Detruire_derniere_page_allouee_de_la_liste(), S_Liste_de_pages::Nb_pages_allouees, Principal_Backups, and Reculer_dans_une_liste_de_pages().
Referenced by Detruire_la_page_courante().
int Initialiser_les_listes_de_backups_en_debut_de_programme (int Taille, int Largeur, int Hauteur)
GESTION DES BACKUPS.
References Allouer_une_liste_de_pages(), Brouillon_Backups, Brouillon_Ecran, Brouillon_Hauteur_image, Brouillon_Largeur_image, Creer_nouvelle_page(), Download_infos_backup(), Download_infos_page_brouillon(), Download_infos_page_principal(), S_Page::Hauteur, Initialiser_S_Page(), S_Page::Largeur, Nouvelle_page_possible(), Principal_Backups, Principal_Ecran, Principal_Hauteur_image, Principal_Largeur_image, and Upload_infos_page_principal().
Referenced by Initialisation_du_programme().
void Detruire_les_listes_de_backups_en_fin_de_programme (void)
References Brouillon_Backups, Detruire_derniere_page_allouee_de_la_liste(), Liberer_une_liste_de_pages(), S_Liste_de_pages::Nb_pages_allouees, and Principal_Backups.
void Nouveau_nombre_de_backups (int Nouveau)
References Brouillon_Backups, Changer_nombre_de_pages_d_une_liste(), and Principal_Backups.
Referenced by Bouton_Settings(), and Fermeture_du_programme().
int Backup_avec_nouvelles_dimensions (int Upload, int Largeur, int Hauteur)
References Brouillon_Backups, Creer_nouvelle_page(), Download_infos_backup(), Download_infos_page_principal(), S_Page::Hauteur, Initialiser_S_Page(), S_Page::Largeur, Nouvelle_page_possible(), S_Liste_de_pages::Pages, Principal_Backups, Principal_Ecran, Principal_Hauteur_image, Principal_Largeur_image, and Upload_infos_page_principal().
Referenced by Initialiser_preview(), and Redimentionner_image().
int Backuper_et_redimensionner_brouillon (int Largeur, int Hauteur)
References Brouillon_Backups, Creer_nouvelle_page(), Download_infos_page_brouillon(), S_Page::Hauteur, Initialiser_S_Page(), S_Page::Largeur, Nouvelle_page_possible(), S_Liste_de_pages::Pages, Principal_Backups, and Upload_infos_page_brouillon().
Referenced by Copier_image_seule().
void Backup (void)
References Brouillon_Backups, Copier_S_page(), Creer_nouvelle_page(), Download_infos_backup(), Download_infos_page_principal(), Ecran_backup, Initialiser_S_Page(), S_Liste_de_pages::Pages, Principal_Backups, Principal_Ecran, Principal_Hauteur_image, Principal_Image_modifiee, Principal_Largeur_image, and Upload_infos_page_principal().
Referenced by Bouton_Clear(), Bouton_Clear_colore(), Bouton_Palette(), Brosse_12_0(), Cercle_12_0(), Cercle_degrade_12_0(), Courbe_34_points_1_0(), Courbe_34_points_2_0(), Ellipse_12_0(), Ellipse_degradee_12_0(), Filled_polyform_12_0(), Freehand_Mode1_1_0(), Freehand_Mode1_2_0(), Freehand_Mode2_1_0(), Freehand_Mode2_2_0(), Freehand_Mode3_1_0(), Freehand_Mode3_2_0(), Get_colors_from_brush(), K_Ligne_12_0(), Ligne_12_0(), Lignes_centrees_12_0(), Polyfill_12_0(), Polyform_12_0(), Polygone_12_0(), Rectangle_Degrade_12_0(), Rectangle_plein_0_5(), Rectangle_vide_0_5(), Remplacer_1_0(), Remplacer_2_0(), Remplir(), Scroll_12_0(), Spray_1_0(), and Spray_2_0().
void Undo (void)
References Download_infos_backup(), Download_infos_page_principal(), S_Liste_de_pages::Pages, Principal_Backups, Reculer_dans_une_liste_de_pages(), and Upload_infos_page_principal().
Referenced by Bouton_Undo().
void Redo (void)
References Avancer_dans_une_liste_de_pages(), Download_infos_backup(), Download_infos_page_principal(), S_Liste_de_pages::Pages, Principal_Backups, and Upload_infos_page_principal().
Referenced by Bouton_Redo().
void Detruire_la_page_courante (void)
References Detruire_la_page_courante_d_une_liste(), Download_infos_backup(), Download_infos_page_principal(), S_Liste_de_pages::Pages, and Principal_Backups.
Referenced by Bouton_Kill().
void Interchanger_image_principale_et_brouillon (void)
References Brouillon_Backups, Download_infos_backup(), Download_infos_page_brouillon(), Download_infos_page_principal(), S_Page::Hauteur, S_Page::Largeur, S_Liste_de_pages::Pages, Principal_Backups, Principal_Hauteur_image, Principal_Largeur_image, Upload_infos_page_brouillon(), and Upload_infos_page_principal().
Referenced by Bouton_Page().
int Emprunt_memoire_de_page_possible (int taille)
GESTION DES EMPRUNTS DE MEMOIRE DE PAGE.
References Brouillon_Backups, Memoire_libre(), S_Liste_de_pages::Pages, Principal_Backups, QUANTITE_MINIMALE_DE_MEMOIRE_A_CONSERVER, Taille_d_une_liste_de_pages(), and Taille_d_une_page().
Referenced by Emprunter_memoire_de_page().
void* Emprunter_memoire_de_page (int taille)
References Brouillon_Backups, Detruire_derniere_page_allouee_de_la_liste(), Emprunt_memoire_de_page_possible(), Memoire_libre(), S_Liste_de_pages::Nb_pages_allouees, S_Liste_de_pages::Pages, Principal_Backups, and QUANTITE_MINIMALE_DE_MEMOIRE_A_CONSERVER.
Referenced by Initialiser_preview_24b().