GrafX2: pages.h File Reference
pages.h File Reference
Handler for the Undo/Redo system.
Functions
void Download_infos_page_main (T_Page *page)
INDIVIDUAL PAGES.
void Upload_infos_page_main (T_Page *page)
byte Add_layer (T_List_of_pages *list, byte layer)
Add a new layer to latest page of a list. Returns 0 on success.
byte Delete_layer (T_List_of_pages *list, byte layer)
Delete a layer from the latest page of a list. Returns 0 on success.
byte Merge_layer ()
Merges the current layer onto the one below it.
T_Page * New_page (byte nb_layers)
Allocate and initialize a new page.
void Download_infos_page_spare (T_Page *page)
void Upload_infos_page_spare (T_Page *page)
void Download_infos_backup (T_List_of_pages *list)
void Clear_page (T_Page *page)
void Copy_S_page (T_Page *dest, T_Page *source)
void Init_list_of_pages (T_List_of_pages *list)
LISTS OF PAGES.
int Allocate_list_of_pages (T_List_of_pages *list)
void Backward_in_list_of_pages (T_List_of_pages *list)
void Advance_in_list_of_pages (T_List_of_pages *list)
void Free_last_page_of_list (T_List_of_pages *list)
int Create_new_page (T_Page *new_page, T_List_of_pages *current_list, dword layer_mask)
void Change_page_number_of_list (T_List_of_pages *list, int number)
void Free_page_of_a_list (T_List_of_pages *list)
int Init_all_backup_lists (int width, int height)
BACKUP HIGH-LEVEL FUNCTIONS.
void Set_number_of_backups (int nb_backups)
int Backup_with_new_dimensions (int upload, byte layers, int width, int height)
int Backup_and_resize_the_spare (int width, int height)
void Backup (void)
Backup with a new copy for the working layer, and references for all others.
void Backup_layers (dword layer_mask)
Backup with a new copy of some layers (the others are references).
void Undo (void)
void Redo (void)
void Free_current_page (void)
void Exchange_main_and_spare (void)
void End_of_modification (void)
void Update_depth_buffer (void)
void Redraw_layered_image (void)
void Redraw_current_layer (void)
void Update_screen_targets (void)
Variables
T_Image Visible_image [2]
Array of two images, that contains the "flattened" version of the visible layers.
T_Image Visible_image_depth_buffer
long Stats_pages_number
STATISTICS.
long long Stats_pages_memory
Total memory used by bitmaps (layers, animation frames, backups).
Detailed Description
Handler for the Undo/Redo system.
Function Documentation
void Download_infos_page_main (T_Page * page)
INDIVIDUAL PAGES.
References T_Page::Comment, Compute_limits(), Compute_paintbrush_coordinates(), T_Page::File_directory, T_Page::File_format, T_Page::Filename, T_Page::Height, Main_comment, Main_file_directory, Main_fileformat, Main_filename, Main_image_height, Main_image_width, Main_magnifier_mode, Main_offset_X, Main_offset_Y, Main_palette, T_Page::Palette, Pixel_preview, Pixel_preview_normal, and T_Page::Width.
Referenced by Backup_layers(), Backup_with_new_dimensions(), Exchange_main_and_spare(), Free_current_page(), Init_all_backup_lists(), Load_image(), Redo(), and Undo().
void Upload_infos_page_main (T_Page * page)
References T_Page::Comment, T_Page::File_directory, T_Page::File_format, T_Page::Filename, T_Page::Height, Main_comment, Main_file_directory, Main_fileformat, Main_filename, Main_image_height, Main_image_width, Main_palette, T_Page::Palette, and T_Page::Width.
Referenced by Backup_layers(), Backup_with_new_dimensions(), Button_Load(), Button_Reload(), Exchange_main_and_spare(), Init_all_backup_lists(), Redo(), and Undo().
byte Add_layer (T_List_of_pages * list, byte layer)
Add a new layer to latest page of a list. Returns 0 on success.
References byte, dword, Error, T_Page::Height, T_Page::Image, Main_backups, Main_current_layer, Main_layers_visible, T_Page::Nb_layers, New_layer(), T_Page::Next, T_List_of_pages::Pages, T_Page::Prev, Spare_current_layer, Spare_layers_visible, T_Page::Transparent_color, and T_Page::Width.
Referenced by Load_GIF(), and Main_handler().
byte Delete_layer (T_List_of_pages * list, byte layer)
Delete a layer from the latest page of a list. Returns 0 on success.
References byte, dword, Free_layer(), T_Page::Image, Main_backups, Main_current_layer, Main_layers_visible, T_Page::Nb_layers, T_List_of_pages::Pages, Spare_current_layer, and Spare_layers_visible.
Referenced by Main_handler(), and Merge_layer().
byte Merge_layer ()
Merges the current layer onto the one below it.
References byte, Delete_layer(), T_Page::Image, Main_backups, Main_current_layer, Main_image_height, Main_image_width, T_List_of_pages::Pages, and T_Page::Transparent_color.
Referenced by Main_handler().
T_Page* New_page (byte nb_layers)
Allocate and initialize a new page.
References byte, T_Page::Comment, DEFAULT_FILEFORMAT, T_Page::File_directory, T_Page::File_format, T_Page::Filename, T_Page::Height, T_Page::Image, T_Page::Nb_layers, T_Page::Next, T_Page::Palette, T_Page::Prev, and T_Page::Width.
Referenced by Allocate_list_of_pages(), Backup_and_resize_the_spare(), Backup_layers(), and Backup_with_new_dimensions().
void Download_infos_page_spare (T_Page * page)
References T_Page::Comment, T_Page::File_directory, T_Page::File_format, T_Page::Filename, T_Page::Height, T_Page::Palette, Spare_comment, Spare_file_directory, Spare_fileformat, Spare_filename, Spare_image_height, Spare_image_width, Spare_palette, and T_Page::Width.
Referenced by Backup_and_resize_the_spare(), Exchange_main_and_spare(), and Init_all_backup_lists().
void Upload_infos_page_spare (T_Page * page)
References T_Page::Comment, T_Page::File_directory, T_Page::File_format, T_Page::Filename, T_Page::Height, T_Page::Palette, Spare_comment, Spare_file_directory, Spare_fileformat, Spare_filename, Spare_image_height, Spare_image_width, Spare_palette, and T_Page::Width.
Referenced by Backup_and_resize_the_spare(), and Exchange_main_and_spare().
void Download_infos_backup (T_List_of_pages * list)
References Config, T_Config::FX_Feedback, FX_feedback_screen, T_Page::Image, Main_current_layer, T_Page::Next, and T_List_of_pages::Pages.
Referenced by Backup_layers(), Backup_with_new_dimensions(), End_of_modification(), Exchange_main_and_spare(), Free_current_page(), Init_all_backup_lists(), Redo(), Redraw_layered_image(), Undo(), and Update_depth_buffer().
void Clear_page (T_Page * page)
References Free_layer(), T_Page::Height, T_Page::Image, T_Page::Nb_layers, and T_Page::Width.
Referenced by Free_last_page_of_list().
void Copy_S_page (T_Page * dest, T_Page * source)
Referenced by Backup_layers().
void Init_list_of_pages (T_List_of_pages * list)
LISTS OF PAGES.
References T_List_of_pages::List_size, and T_List_of_pages::Pages.
Referenced by Init_program().
int Allocate_list_of_pages (T_List_of_pages * list)
References T_List_of_pages::List_size, NB_LAYERS, New_page(), T_Page::Next, T_List_of_pages::Pages, and T_Page::Prev.
Referenced by Init_all_backup_lists().
void Backward_in_list_of_pages (T_List_of_pages * list)
References Last_backed_up_layers, T_Page::Next, T_List_of_pages::Pages, and T_Page::Prev.
Referenced by Free_page_of_a_list(), and Undo().
void Advance_in_list_of_pages (T_List_of_pages * list)
References Last_backed_up_layers, T_Page::Next, T_List_of_pages::Pages, and T_Page::Prev.
Referenced by Redo().
void Free_last_page_of_list (T_List_of_pages * list)
References Clear_page(), T_List_of_pages::List_size, T_Page::Next, T_List_of_pages::Pages, and T_Page::Prev.
Referenced by Change_page_number_of_list(), Create_new_page(), and Free_page_of_a_list().
int Create_new_page (T_Page * new_page, T_List_of_pages * current_list, dword layer_mask)
References Config, Dup_layer(), Free_last_page_of_list(), T_Page::Height, T_Page::Image, T_List_of_pages::List_size, T_Config::Max_undo_pages, T_Page::Nb_layers, New_layer(), T_Page::Next, T_List_of_pages::Pages, T_Page::Prev, and T_Page::Width.
Referenced by Backup_and_resize_the_spare(), Backup_layers(), and Backup_with_new_dimensions().
void Change_page_number_of_list (T_List_of_pages * list, int number)
References Free_last_page_of_list(), and T_List_of_pages::List_size.
Referenced by Set_number_of_backups().
void Free_page_of_a_list (T_List_of_pages * list)
References Backward_in_list_of_pages(), Free_last_page_of_list(), T_List_of_pages::List_size, and Main_backups.
Referenced by Free_current_page(), Redo(), and Undo().
int Init_all_backup_lists (int width, int height)
BACKUP HIGH-LEVEL FUNCTIONS.
References Allocate_list_of_pages(), T_Page::Comment, DEFAULT_FILEFORMAT, Download_infos_backup(), Download_infos_page_main(), Download_infos_page_spare(), End_of_modification(), T_Page::File_directory, T_Page::File_format, T_Page::Filename, T_Image::Height, T_Page::Height, T_Image::Image, T_Page::Image, Main_backups, Main_palette, NB_LAYERS, T_Page::Nb_layers, New_layer(), T_List_of_pages::Pages, T_Page::Palette, Spare_backups, Spare_current_directory, Update_buffers(), Upload_infos_page_main(), T_Image::Width, and T_Page::Width.
Referenced by Init_program().
void Set_number_of_backups (int nb_backups)
References Change_page_number_of_list(), Main_backups, and Spare_backups.
Referenced by Button_Settings(), and Program_shutdown().
int Backup_with_new_dimensions (int upload, byte layers, int width, int height)
References Create_new_page(), Download_infos_backup(), Download_infos_page_main(), Error, T_Page::Height, T_Page::Image, Main_backups, New_page(), T_List_of_pages::Pages, Update_buffers(), Upload_infos_page_main(), and T_Page::Width.
Referenced by Button_Transform_menu(), Init_preview(), and Resize_image().
int Backup_and_resize_the_spare (int width, int height)
References byte, Create_new_page(), Download_infos_page_spare(), Error, T_Page::Height, T_Page::Image, T_Page::Nb_layers, New_page(), T_List_of_pages::Pages, Spare_backups, Upload_infos_page_spare(), and T_Page::Width.
Referenced by Copy_image_only().
void Backup (void)
Backup with a new copy for the working layer, and references for all others.
References Backup_layers(), and Main_current_layer.
Referenced by Airbrush_1_0(), Airbrush_2_0(), Brush_12_0(), Button_Clear(), Button_Clear_with_backcolor(), Centered_lines_12_0(), Circle_12_0(), Curve_34_points_1_0(), Curve_34_points_2_0(), Ellipse_12_0(), Empty_rectangle_0_5(), Fill_general(), Filled_polyform_12_0(), Filled_rectangle_0_5(), Freehand_mode1_1_0(), Freehand_mode1_2_0(), Freehand_mode2_1_0(), Freehand_mode2_2_0(), Freehand_mode3_1_0(), Freehand_Mode3_2_0(), Grad_circle_12_0(), Grad_ellipse_12_0(), Grad_rectangle_12_0(), K_line_12_0(), Line_12_0(), Polyfill_12_0(), Polyform_12_0(), Polygon_12_0(), Replace_1_0(), Replace_2_0(), and Scroll_12_0().
void Backup_layers (dword layer_mask)
Backup with a new copy of some layers (the others are references).
References Copy_S_page(), Create_new_page(), Download_infos_backup(), Download_infos_page_main(), Error, T_Page::Image, Main_backups, Main_image_height, Main_image_is_modified, Main_image_width, T_Page::Nb_layers, New_page(), T_Page::Next, T_List_of_pages::Pages, and Upload_infos_page_main().
Referenced by Backup(), Button_Palette(), Get_colors_from_brush(), Main_handler(), and Scroll_12_0().
void Undo (void)
References Backward_in_list_of_pages(), Download_infos_backup(), Download_infos_page_main(), Free_page_of_a_list(), T_Page::Height, Last_backed_up_layers, Main_backups, Main_current_layer, T_Page::Nb_layers, T_List_of_pages::Pages, Redraw_layered_image(), Update_buffers(), Upload_infos_page_main(), and T_Page::Width.
Referenced by Button_Undo().
void Redo (void)
References Advance_in_list_of_pages(), Download_infos_backup(), Download_infos_page_main(), Free_page_of_a_list(), T_Page::Height, Last_backed_up_layers, Main_backups, Main_current_layer, T_Page::Nb_layers, T_List_of_pages::Pages, Redraw_layered_image(), Update_buffers(), Upload_infos_page_main(), and T_Page::Width.
Referenced by Button_Redo().
void Free_current_page (void)
References Download_infos_backup(), Download_infos_page_main(), Free_page_of_a_list(), T_Page::Height, Main_backups, T_List_of_pages::Pages, Redraw_layered_image(), Update_buffers(), and T_Page::Width.
Referenced by Button_Kill().
void Exchange_main_and_spare (void)
References Download_infos_backup(), Download_infos_page_main(), Download_infos_page_spare(), T_Page::Height, Main_backups, Main_image_height, Main_image_width, T_List_of_pages::Pages, Redraw_layered_image(), Spare_backups, Update_buffers(), Upload_infos_page_main(), Upload_infos_page_spare(), and T_Page::Width.
Referenced by Button_Page().
void End_of_modification (void)
References Download_infos_backup(), Main_backups, Main_image_height, Main_image_width, and Update_screen_targets().
Referenced by Airbrush_0_2(), Brush_0_5(), Button_Clear(), Button_Clear_with_backcolor(), Button_Palette(), Button_Transform_menu(), Centered_lines_12_7(), Curve_3_points_12_11(), Curve_4_points_2_9(), Empty_circle_0_5(), Empty_ellipse_0_5(), Empty_rectangle_0_5(), Fill_1_0(), Fill_2_0(), Fill_general(), Filled_circle_0_5(), Filled_contour_0_8(), Filled_ellipse_0_5(), Filled_polyform_12_8(), Filled_rectangle_0_5(), Freehand_mode12_0_2(), Freehand_mode3_0_1(), Get_colors_from_brush(), Grad_circle_0_6(), Grad_circle_12_8(), Grad_ellipse_0_6(), Grad_ellipse_12_8(), Grad_rectangle_0_9(), Init_all_backup_lists(), K_line_12_7(), Line_0_5(), Main_handler(), Polybrush_12_8(), Polyfill_12_9(), Polyform_12_8(), Polygon_12_9(), Replace_1_0(), Replace_2_0(), and Scroll_0_5().
void Update_depth_buffer (void)
References byte, Download_infos_backup(), T_Page::Image, T_Image::Image, Main_backups, Main_current_layer, Main_image_height, Main_image_width, Main_layers_visible, T_Page::Nb_layers, T_List_of_pages::Pages, and T_Page::Transparent_color.
Referenced by Layer_activate(), Main_handler(), and Scroll_0_5().
void Redraw_layered_image (void)
References byte, Download_infos_backup(), T_Image::Image, T_Page::Image, Main_backups, Main_current_layer, Main_image_height, Main_image_width, Main_layers_visible, T_Page::Nb_layers, T_List_of_pages::Pages, T_Page::Transparent_color, and Update_screen_targets().
Referenced by Button_Clear(), Button_Clear_with_backcolor(), Button_Reload(), Button_Transform_menu(), Exchange_main_and_spare(), Free_current_page(), Layer_activate(), Load_picture(), Main_handler(), Redo(), Resize_image(), and Undo().
void Redraw_current_layer (void)
References byte, T_Page::Image, T_Image::Image, Main_backups, Main_current_layer, Main_image_height, Main_image_width, T_List_of_pages::Pages, and T_Page::Transparent_color.
Referenced by Scroll_12_5().
void Update_screen_targets (void)
References T_Page::Image, T_Image::Image, Main_backups, Main_current_layer, Main_screen, T_Page::Next, T_List_of_pages::Pages, and Screen_backup.
Referenced by Button_Page(), End_of_modification(), Layer_activate(), Main_handler(), Redraw_layered_image(), and Update_buffers().
Variable Documentation
T_Image Visible_image[2]
Array of two images, that contains the "flattened" version of the visible layers.
Referenced by Init_program().
T_Image Visible_image_depth_buffer
Referenced by Init_program(), Pixel_in_current_screen(), and Read_pixel_from_current_screen().
long Stats_pages_number
STATISTICS.
Total number of unique bitmaps (layers, animation frames, backups)
Referenced by Button_Stats(), Free_layer(), and New_layer().
long long Stats_pages_memory
Total memory used by bitmaps (layers, animation frames, backups).
Referenced by Button_Stats(), Free_layer(), and New_layer().