GrafX2: palette.c File Reference
palette.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "const.h"
#include "struct.h"
#include "global.h"
#include "misc.h"
#include "engine.h"
#include "readline.h"
#include "buttons.h"
#include "pages.h"
#include "help.h"
#include "sdlscreen.h"
#include "errors.h"
#include "op_c.h"
#include "windows.h"
#include "input.h"
#include "palette.h"
#include "shade.h"
Functions
void Set_palette_RGB_scale (int scale)
Choose the number of graduations for RGB components, from 2 to 256.
int Get_palette_RGB_scale (void)
byte Round_palette_component (byte comp)
Round a 0-255 RGB component according to the RGB_scale.
int Reduce_component (int comp)
Turns a RGB component from 0-255 scale to 0-(RGB_scale-1).
int Expand_component (int comp)
Turns a RGB component from 0-(RGB_scale-1) to 0-255.
void Component_unit (int count)
void Set_HSL (T_Palette start_palette, T_Palette end_palette, byte color, short diff_h, short diff_s, short diff_l)
void Set_red (byte color, short new_color, T_Palette palette)
void Set_green (byte color, short new_color, T_Palette palette)
void Set_blue (byte color, short new_color, T_Palette palette)
void Format_component (byte value, char *str)
void Spread_colors (short start, short end, T_Palette palette)
void Update_color_count (short *used_colors, dword *color_usage)
void Remap_zone_highlevel (short x1, short y1, short x2, short y2, byte *conversion_table)
void Remap_image_highlevel (byte *conversion_table)
void Swap (int with_remap, short block_1_start, short block_2_start, short block_size, T_Palette palette, dword *color_usage)
void Set_nice_menu_colors (dword *color_usage, int not_picture)
Adds 4 menu colors in the current palette.
void Reduce_palette (short *used_colors, int nb_colors_asked, T_Palette palette, dword *color_usage)
void Set_palette_slider (T_Scroller_button *slider, word nb_elements, word position, char *value, short x_pos)
void Display_sliders (T_Scroller_button *red_slider, T_Scroller_button *green_slider, T_Scroller_button *blue_slider, byte block_is_selected, T_Components *palette)
void Draw_all_palette_sliders (T_Scroller_button *red_slider, T_Scroller_button *green_slider, T_Scroller_button *blue_slider, T_Palette palette, byte start, byte end)
int Window_Histogram (unsigned char block_start, unsigned char block_end, dword *color_usage)
void Print_RGB_or_HSL (byte mode)
void Tag_used_colors (byte color, dword color_usage[])
void Button_Palette (void)
Open the palette menu and handles everything inside it.
void Button_Secondary_palette (void)
Open the secondary palette menu and handles it.
void Set_clipboard_colors (int nb_colors, T_Components *colors)
Put some colors in the clipboard.
int Get_clipboard_colors (T_Palette palette, byte start_color)
Get some RGB colors from clipboard.
const T_Components * Favorite_GUI_color (byte color_index)
Get the favorite color to use for GUI's black,dark,light or white.
Variables
byte Palette_view_is_RGB = 1
static const int COUNT_X = 258
static const int COUNT_Y = 49
int RGB_scale = 256
int Color_count = 256
int Color_max = 255
int Color_halfstep = 0
static const int NUMERIC_R_X = 176
static const int NUMERIC_G_X = 203
static const int NUMERIC_B_X = 230
static const int NUMERIC_Y = 171
static const int NUMERIC_BOX_X = 175
static const int NUMERIC_BOX_Y = 169
static const int NUMERIC_BOX_W = 81
static const int NUMERIC_BOX_H = 12
int Palette_clipboard_count = 0
T_Palette Palette_clipboard
Function Documentation
void Set_palette_RGB_scale (int scale)
Choose the number of graduations for RGB components, from 2 to 256.
References RGB_scale.
Referenced by Analyze_command_line(), and Button_Secondary_palette().
int Get_palette_RGB_scale (void)
References RGB_scale.
Referenced by Compute_optimal_menu_colors().
byte Round_palette_component (byte comp)
Round a 0-255 RGB component according to the RGB_scale.
Scale a component (R, G or B) according to the current RGB graduations.
The result is also in the 0-255 range.
References RGB_scale.
Referenced by Compute_optimal_menu_colors(), Set_blue(), Set_green(), Set_nice_menu_colors(), Set_palette(), and Set_red().
int Reduce_component (int comp)
Turns a RGB component from 0-255 scale to 0-(RGB_scale-1).
The passed value should come from Round_palette_component(), otherwise the rounding will be "down".
References Color_max.
Referenced by Button_Palette().
int Expand_component (int comp)
Turns a RGB component from 0-(RGB_scale-1) to 0-255.
References Color_max.
Referenced by Display_sliders(), and Draw_all_palette_sliders().
void Component_unit (int count)
References Color_count, Color_halfstep, and Color_max.
Referenced by Button_Palette().
void Set_HSL (T_Palette start_palette, T_Palette end_palette, byte color, short diff_h, short diff_s, short diff_l)
References byte, HSL_to_RGB(), and RGB_to_HSL().
Referenced by Button_Palette().
void Set_red (byte color, short new_color, T_Palette palette)
References Round_palette_component().
Referenced by Button_Palette(), and Spread_colors().
void Set_green (byte color, short new_color, T_Palette palette)
References Round_palette_component().
Referenced by Button_Palette(), and Spread_colors().
void Set_blue (byte color, short new_color, T_Palette palette)
References Round_palette_component().
Referenced by Button_Palette(), and Spread_colors().
void Format_component (byte value, char * str)
References Num2str.
Referenced by Button_Palette(), Display_sliders(), and Draw_all_palette_sliders().
void Spread_colors (short start, short end, T_Palette palette)
References Set_blue(), Set_green(), Set_palette(), and Set_red().
Referenced by Button_Palette().
void Update_color_count (short * used_colors, dword * color_usage)
References Count_used_colors(), COUNT_X, COUNT_Y, Cursor_shape, CURSOR_SHAPE_ARROW, CURSOR_SHAPE_HOURGLASS, Display_cursor(), Hide_cursor, MC_Black, MC_Light, Num2str, and Print_in_window().
Referenced by Button_Palette(), and Reduce_palette().
void Remap_zone_highlevel (short x1, short y1, short x2, short y2, byte * conversion_table)
References Menu_factor_X, Menu_factor_Y, Pixel, Read_pixel, Window_height, Window_pos_X, Window_pos_Y, and Window_width.
Referenced by Remap_image_highlevel(), and Set_nice_menu_colors().
void Remap_image_highlevel (byte * conversion_table)
References T_Page::Image, Main_backups, Main_image_height, Main_image_width, Main_magnifier_factor, Main_magnifier_mode, Main_screen, Main_separator_position, Main_X_zoom, Menu_factor_X, Menu_Y_before_window, T_Page::Nb_layers, T_List_of_pages::Pages, Remap_general_lowlevel(), Remap_window_backgrounds(), Remap_zone_highlevel(), Screen_width, SEPARATOR_WIDTH, and T_Page::Transparent_color.
Referenced by Button_Palette(), Reduce_palette(), Set_nice_menu_colors(), and Swap().
void Swap (int with_remap, short block_1_start, short block_2_start, short block_size, T_Palette palette, dword * color_usage)
References T_Components::B, byte, dword, T_Components::G, T_Components::R, Remap_image_highlevel(), SWAP_BYTES, and SWAP_DWORDS.
Referenced by Button_Palette().
void Set_nice_menu_colors (dword * color_usage, int not_picture)
Adds 4 menu colors in the current palette.
Parameters:
color_usage An up-to-date color usage table (byte[256]) (read only)
not_picture 0 if the caller is the palette screen, 1 if it's a preview in the file selector.
References T_Components::B, Best_color_nonexcluded(), byte, Display_cursor(), Favorite_GUI_color(), T_Components::G, Hide_cursor, Main_palette, T_Components::R, Remap_image_highlevel(), Remap_zone_highlevel(), Round_palette_component(), Screen_height, and Screen_width.
Referenced by Button_Palette().
void Reduce_palette (short * used_colors, int nb_colors_asked, T_Palette palette, dword * color_usage)
References byte, COUNT_X, COUNT_Y, Display_cursor(), dword, Hide_cursor, MC_Black, MC_Light, Num2str, Print_in_window(), Remap_image_highlevel(), Round_div(), and Update_color_count().
Referenced by Button_Palette().
void Set_palette_slider (T_Scroller_button * slider, word nb_elements, word position, char * value, short x_pos)
References Compute_slider_cursor_length(), MC_Black, MC_Light, T_Scroller_button::Nb_elements, NUMERIC_Y, T_Scroller_button::Position, Print_counter(), and Window_draw_slider().
Referenced by Display_sliders().
void Display_sliders (T_Scroller_button * red_slider, T_Scroller_button * green_slider, T_Scroller_button * blue_slider, byte block_is_selected, T_Components * palette)
References T_Components::B, byte, Color_count, Color_max, Expand_component(), Fore_color, Format_component(), T_Components::G, NUMERIC_B_X, NUMERIC_G_X, NUMERIC_R_X, Palette_view_is_RGB, T_Components::R, RGB_to_HSL(), and Set_palette_slider().
Referenced by Button_Palette().
void Draw_all_palette_sliders (T_Scroller_button * red_slider, T_Scroller_button * green_slider, T_Scroller_button * blue_slider, T_Palette palette, byte start, byte end)
References byte, Color_count, Color_max, DEBUG, Display_cursor(), Expand_component(), Format_component(), Hide_cursor, MC_Black, MC_Light, NUMERIC_B_X, NUMERIC_G_X, NUMERIC_R_X, NUMERIC_Y, Palette_view_is_RGB, T_Scroller_button::Position, Print_counter(), RGB_to_HSL(), and Window_draw_slider().
Referenced by Button_Palette().
int Window_Histogram (unsigned char block_start, unsigned char block_end, dword * color_usage)
References Close_window(), Display_cursor(), T_Special_button::Height, Hide_cursor, Key, KEY_ESC, MC_Black, MC_Dark, MC_Light, Menu_factor_X, Mouse_K, Mouse_X, Num2str, Open_window(), T_Special_button::Pos_X, T_Special_button::Pos_Y, Print_in_window(), Update_window_area, Warning_message(), T_Special_button::Width, Window_click_in_rectangle(), Window_clicked_button(), Window_pos_X, Window_rectangle(), Window_set_normal_button(), and Window_set_special_button().
Referenced by Button_Palette().
void Print_RGB_or_HSL (byte mode)
References MC_Dark, MC_Light, and Print_in_window().
Referenced by Button_Palette().
void Tag_used_colors (byte color, dword color_usage[])
References byte, MC_Light, MC_White, Update_window_area, Window_palette_button_list, Window_rectangle(), and word.
Referenced by Button_Palette().
void Button_Palette (void)
Open the palette menu and handles everything inside it.
References T_Components::B, Back_color, Backup_layers(), T_Dropdown_button::Bottom_up, BUTTON_COLORPICKER, BUTTON_HELP, BUTTON_PALETTE, BUTTON_UNDO, byte, Close_window(), Color_count, Color_max, Component_unit(), Compute_optimal_menu_colors(), Config, Display_cursor(), Display_grad_block_in_window(), Display_menu(), Display_sliders(), Draw_all_palette_sliders(), Draw_thingumajig(), Dropdown_activate(), T_Dropdown_button::Dropdown_width, dword, End_of_modification(), T_Dropdown_button::First_item, Fore_color, Format_component(), T_Components::G, Get_clipboard_colors(), Get_color_behind_window(), T_Dropdown_button::Height, Hide_cursor, HSL_to_RGB(), Input_sticky_control, INPUT_TYPE_HEXA, Is_shortcut(), Key, KEY_ESC, KEY_NONE, LEFT_SIDE, Main_palette, MC_Black, MC_Dark, MC_Light, MC_White, Menu_factor_Y, Menu_Y_before_window, MOD_CTRL, Mouse_K, Mouse_X, Mouse_Y, Num2str, T_Dropdown_choice::Number, NUMERIC_B_X, NUMERIC_BOX_H, NUMERIC_BOX_W, NUMERIC_BOX_X, NUMERIC_BOX_Y, NUMERIC_G_X, NUMERIC_R_X, NUMERIC_Y, Open_window(), Palette_view_is_RGB, Perceptual_lightness(), T_Dropdown_button::Pos_X, T_Dropdown_button::Pos_Y, T_Scroller_button::Position, Print_counter(), Print_in_window(), Print_RGB_or_HSL(), T_Components::R, Read_pixel, Readline(), Reduce_component(), Reduce_palette(), Remap_image_highlevel(), Remap_screen_after_menu_colors_change(), Reposition_palette(), Requester_window(), RGB_scale, RGB_to_HSL(), RIGHT_SIDE, T_Config::Safety_colors, Screen_width, Select_button(), Set_blue(), Set_clipboard_colors(), Set_green(), Set_HSL(), Set_nice_menu_colors(), Set_palette(), Set_red(), SPECIAL_NEXT_BACKCOLOR, SPECIAL_NEXT_FORECOLOR, SPECIAL_PREVIOUS_BACKCOLOR, SPECIAL_PREVIOUS_FORECOLOR, Spread_colors(), Swap(), SWAP_BYTES, SWAP_DWORDS, Tag_color_range(), Tag_used_colors(), Unselect_button(), Update_color_count(), Update_rect(), Update_window_area, Wait_click_in_palette(), Wait_end_of_click(), Window_attribute2, Window_clicked_button(), Window_display_frame(), Window_display_frame_mono(), Window_draw_normal_bouton(), Window_draw_palette_bouton(), Window_draw_slider(), Window_dropdown_add_item(), Window_dropdown_clear_items(), Window_height, Window_help(), Window_Histogram(), Window_palette_button_list, Window_pos_Y, Window_rectangle(), Window_set_dropdown_button(), Window_set_normal_button(), Window_set_palette_button(), Window_set_repeatable_button(), Window_set_scroller_button(), and word.
Referenced by Button_Select_forecolor(), and Init_buttons().
void Button_Secondary_palette (void)
Open the secondary palette menu and handles it.
References BUTTON_HELP, BUTTON_PAL_LEFT, BUTTON_PAL_RIGHT, BUTTON_PALETTE, BUTTON_RELEASED, byte, Change_palette_cells(), Close_window(), Compute_optimal_menu_colors(), Config, Display_cursor(), Display_menu(), Display_sprite_in_menu(), Draw_menu_button(), Exclude_color, Hide_cursor, Is_shortcut(), Key, KEY_ESC, Main_palette, MC_Black, MC_Dark, MC_Light, MENU_SPRITE_VERTICAL_PALETTE_SCROLL, Menu_tag_colors(), Num2str, Open_window(), T_Config::Palette_cells_X, T_Config::Palette_cells_Y, T_Config::Palette_vertical, T_Scroller_button::Position, Print_in_window(), RGB_scale, Set_palette(), Set_palette_RGB_scale(), Shade_settings_menu(), SPECIAL_EXCLUDE_COLORS_MENU, Unselect_button(), Update_window_area, Window_attribute2, Window_clicked_button(), Window_display_frame(), Window_draw_slider(), Window_help(), Window_set_normal_button(), Window_set_scroller_button(), and word.
Referenced by Init_buttons().
void Set_clipboard_colors (int nb_colors, T_Components * colors)
Put some colors in the clipboard.
Parameters:
nb_colors Number of colors to push
colors First color of the input array
References Palette_clipboard, and Palette_clipboard_count.
Referenced by Button_Palette().
int Get_clipboard_colors (T_Palette palette, byte start_color)
Get some RGB colors from clipboard.
Parameters:
palette Target palette
start_color Index of first color to replace
Returns:
Number of colors retrieved (0-256)
References Palette_clipboard, and Palette_clipboard_count.
Referenced by Button_Palette().
const T_Components* Favorite_GUI_color (byte color_index)
Get the favorite color to use for GUI's black,dark,light or white.
References T_Components::B, T_Gui_skin::Color, T_Gui_skin::Default_palette, T_Components::G, Gfx, T_Components::R, and RGB_scale.
Referenced by Load_image(), and Set_nice_menu_colors().
Variable Documentation
byte Palette_view_is_RGB = 1
Referenced by Button_Palette(), Display_sliders(), and Draw_all_palette_sliders().
const int COUNT_X = 258 [static]
Referenced by Reduce_palette(), and Update_color_count().
const int COUNT_Y = 49 [static]
Referenced by Reduce_palette(), and Update_color_count().
int RGB_scale = 256
Referenced by Button_Palette(), Button_Secondary_palette(), Favorite_GUI_color(), Get_palette_RGB_scale(), Round_palette_component(), and Set_palette_RGB_scale().
int Color_count = 256
Referenced by Button_Palette(), Component_unit(), Display_sliders(), and Draw_all_palette_sliders().
int Color_max = 255
Referenced by Button_Palette(), Component_unit(), Display_sliders(), Draw_all_palette_sliders(), Expand_component(), and Reduce_component().
int Color_halfstep = 0
Referenced by Component_unit().
const int NUMERIC_R_X = 176 [static]
Referenced by Button_Palette(), Display_sliders(), and Draw_all_palette_sliders().
const int NUMERIC_G_X = 203 [static]
Referenced by Button_Palette(), Display_sliders(), and Draw_all_palette_sliders().
const int NUMERIC_B_X = 230 [static]
Referenced by Button_Palette(), Display_sliders(), and Draw_all_palette_sliders().
const int NUMERIC_Y = 171 [static]
Referenced by Button_Palette(), Draw_all_palette_sliders(), and Set_palette_slider().
const int NUMERIC_BOX_X = 175 [static]
Referenced by Button_Palette().
const int NUMERIC_BOX_Y = 169 [static]
Referenced by Button_Palette().
const int NUMERIC_BOX_W = 81 [static]
Referenced by Button_Palette().
const int NUMERIC_BOX_H = 12 [static]
Referenced by Button_Palette().
int Palette_clipboard_count = 0
Referenced by Get_clipboard_colors(), and Set_clipboard_colors().
T_Palette Palette_clipboard
Referenced by Get_clipboard_colors(), and Set_clipboard_colors().