GrafX2: palette.h File Reference
palette.h File Reference
Palette screen, and some palette-related high-level functions.
Functions
void Button_Palette (void)
Open the palette menu and handles everything inside it.
void Button_Secondary_palette (void)
Open the secondary palette menu and handles it.
void Set_palette_RGB_scale (int)
Choose the number of graduations for RGB components, from 2 to 256.
int Get_palette_RGB_scale (void)
byte Round_palette_component (byte comp)
Scale a component (R, G or B) according to the current RGB graduations.
void Set_nice_menu_colors (dword *color_usage, int not_picture)
Adds 4 menu colors in the current palette.
void Set_clipboard_colors (int nb_colors, T_Components *colors)
Put some colors in the clipboard.
int Get_clipboard_colors (T_Palette palette, byte start_color)
Get some RGB colors from clipboard.
const T_Components * Favorite_GUI_color (byte color_index)
Get the favorite color to use for GUI's black,dark,light or white.
Detailed Description
Palette screen, and some palette-related high-level functions.
Function Documentation
void Button_Palette (void)
Open the palette menu and handles everything inside it.
References T_Components::B, Back_color, Backup_layers(), T_Dropdown_button::Bottom_up, BUTTON_COLORPICKER, BUTTON_HELP, BUTTON_PALETTE, BUTTON_UNDO, byte, Close_window(), Color_count, Color_max, Component_unit(), Compute_optimal_menu_colors(), Config, Display_cursor(), Display_grad_block_in_window(), Display_menu(), Display_sliders(), Draw_all_palette_sliders(), Draw_thingumajig(), Dropdown_activate(), T_Dropdown_button::Dropdown_width, dword, End_of_modification(), T_Dropdown_button::First_item, Fore_color, Format_component(), T_Components::G, Get_clipboard_colors(), Get_color_behind_window(), T_Dropdown_button::Height, Hide_cursor, HSL_to_RGB(), Input_sticky_control, INPUT_TYPE_HEXA, Is_shortcut(), Key, KEY_ESC, KEY_NONE, LEFT_SIDE, Main_palette, MC_Black, MC_Dark, MC_Light, MC_White, Menu_factor_Y, Menu_Y_before_window, MOD_CTRL, Mouse_K, Mouse_X, Mouse_Y, Num2str, T_Dropdown_choice::Number, NUMERIC_B_X, NUMERIC_BOX_H, NUMERIC_BOX_W, NUMERIC_BOX_X, NUMERIC_BOX_Y, NUMERIC_G_X, NUMERIC_R_X, NUMERIC_Y, Open_window(), Palette_view_is_RGB, Perceptual_lightness(), T_Dropdown_button::Pos_X, T_Dropdown_button::Pos_Y, T_Scroller_button::Position, Print_counter(), Print_in_window(), Print_RGB_or_HSL(), T_Components::R, Read_pixel, Readline(), Reduce_component(), Reduce_palette(), Remap_image_highlevel(), Remap_screen_after_menu_colors_change(), Reposition_palette(), Requester_window(), RGB_scale, RGB_to_HSL(), RIGHT_SIDE, T_Config::Safety_colors, Screen_width, Select_button(), Set_blue(), Set_clipboard_colors(), Set_green(), Set_HSL(), Set_nice_menu_colors(), Set_palette(), Set_red(), SPECIAL_NEXT_BACKCOLOR, SPECIAL_NEXT_FORECOLOR, SPECIAL_PREVIOUS_BACKCOLOR, SPECIAL_PREVIOUS_FORECOLOR, Spread_colors(), Swap(), SWAP_BYTES, SWAP_DWORDS, Tag_color_range(), Tag_used_colors(), Unselect_button(), Update_color_count(), Update_rect(), Update_window_area, Wait_click_in_palette(), Wait_end_of_click(), Window_attribute2, Window_clicked_button(), Window_display_frame(), Window_display_frame_mono(), Window_draw_normal_bouton(), Window_draw_palette_bouton(), Window_draw_slider(), Window_dropdown_add_item(), Window_dropdown_clear_items(), Window_height, Window_help(), Window_Histogram(), Window_palette_button_list, Window_pos_Y, Window_rectangle(), Window_set_dropdown_button(), Window_set_normal_button(), Window_set_palette_button(), Window_set_repeatable_button(), Window_set_scroller_button(), and word.
Referenced by Button_Select_forecolor(), and Init_buttons().
void Button_Secondary_palette (void)
Open the secondary palette menu and handles it.
References BUTTON_HELP, BUTTON_PAL_LEFT, BUTTON_PAL_RIGHT, BUTTON_PALETTE, BUTTON_RELEASED, byte, Change_palette_cells(), Close_window(), Compute_optimal_menu_colors(), Config, Display_cursor(), Display_menu(), Display_sprite_in_menu(), Draw_menu_button(), Exclude_color, Hide_cursor, Is_shortcut(), Key, KEY_ESC, Main_palette, MC_Black, MC_Dark, MC_Light, MENU_SPRITE_VERTICAL_PALETTE_SCROLL, Menu_tag_colors(), Num2str, Open_window(), T_Config::Palette_cells_X, T_Config::Palette_cells_Y, T_Config::Palette_vertical, T_Scroller_button::Position, Print_in_window(), RGB_scale, Set_palette(), Set_palette_RGB_scale(), Shade_settings_menu(), SPECIAL_EXCLUDE_COLORS_MENU, Unselect_button(), Update_window_area, Window_attribute2, Window_clicked_button(), Window_display_frame(), Window_draw_slider(), Window_help(), Window_set_normal_button(), Window_set_scroller_button(), and word.
Referenced by Init_buttons().
void Set_palette_RGB_scale (int)
Choose the number of graduations for RGB components, from 2 to 256.
References RGB_scale.
Referenced by Analyze_command_line(), and Button_Secondary_palette().
int Get_palette_RGB_scale (void)
References RGB_scale.
Referenced by Compute_optimal_menu_colors().
byte Round_palette_component (byte comp)
Scale a component (R, G or B) according to the current RGB graduations.
Returns the resulting value, in the [0-255] range.
Scale a component (R, G or B) according to the current RGB graduations.
The result is also in the 0-255 range.
References RGB_scale.
Referenced by Compute_optimal_menu_colors(), Set_blue(), Set_green(), Set_nice_menu_colors(), Set_palette(), and Set_red().
void Set_nice_menu_colors (dword * color_usage, int not_picture)
Adds 4 menu colors in the current palette.
Parameters:
color_usage An up-to-date color usage table (byte[256]) (read only)
not_picture 0 if the caller is the palette screen, 1 if it's a preview in the file selector.
References T_Components::B, Best_color_nonexcluded(), byte, Display_cursor(), Favorite_GUI_color(), T_Components::G, Hide_cursor, Main_palette, T_Components::R, Remap_image_highlevel(), Remap_zone_highlevel(), Round_palette_component(), Screen_height, and Screen_width.
Referenced by Button_Palette().
void Set_clipboard_colors (int nb_colors, T_Components * colors)
Put some colors in the clipboard.
Parameters:
nb_colors Number of colors to push
colors First color of the input array
References Palette_clipboard, and Palette_clipboard_count.
Referenced by Button_Palette().
int Get_clipboard_colors (T_Palette palette, byte start_color)
Get some RGB colors from clipboard.
Parameters:
palette Target palette
start_color Index of first color to replace
Returns:
Number of colors retrieved (0-256)
References Palette_clipboard, and Palette_clipboard_count.
Referenced by Button_Palette().
const T_Components* Favorite_GUI_color (byte color_index)
Get the favorite color to use for GUI's black,dark,light or white.
References T_Components::B, T_Gui_skin::Color, T_Gui_skin::Default_palette, T_Components::G, Gfx, T_Components::R, and RGB_scale.
Referenced by Load_image(), and Set_nice_menu_colors().