GrafX2: pxdouble.c File Reference
pxdouble.c File Reference
#include <string.h>
#include <stdlib.h>
#include <SDL.h>
#include "global.h"
#include "sdlscreen.h"
#include "misc.h"
#include "graph.h"
#include "pxdouble.h"
#include "pxwide.h"
Defines
#define ZOOMX 2
#define ZOOMY 2
Functions
void Pixel_double (word x, word y, byte color)
byte Read_pixel_double (word x, word y)
void Block_double (word start_x, word start_y, word width, word height, byte color)
void Display_part_of_screen_double (word width, word height, word image_width)
void Pixel_preview_normal_double (word x, word y, byte color)
void Pixel_preview_magnifier_double (word x, word y, byte color)
void Horizontal_XOR_line_double (word x_pos, word y_pos, word width)
void Vertical_XOR_line_double (word x_pos, word y_pos, word height)
void Display_brush_color_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
void Display_brush_mono_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, byte color, word brush_width)
void Clear_brush_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word image_width)
void Display_brush_double (byte *brush, word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
void Remap_screen_double (word x_pos, word y_pos, word width, word height, byte *conversion_table)
void Display_line_on_screen_fast_double (word x_pos, word y_pos, word width, byte *line)
void Display_line_on_screen_double (word x_pos, word y_pos, word width, byte *line)
void Display_transparent_mono_line_on_screen_double (word x_pos, word y_pos, word width, byte *line, byte transp_color, byte color)
void Read_line_screen_double (word x_pos, word y_pos, word width, byte *line)
void Display_part_of_screen_scaled_double (word width, word height, word image_width, byte *buffer)
void Display_brush_color_zoom_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word brush_width, byte *buffer)
void Display_brush_mono_zoom_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, byte color, word brush_width, byte *buffer)
void Clear_brush_scaled_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word image_width, byte *buffer)
Define Documentation
#define ZOOMX 2
Referenced by Block_double(), Clear_brush_double(), Clear_brush_scaled_double(), Display_brush_color_double(), Display_brush_color_zoom_double(), Display_brush_double(), Display_brush_mono_double(), Display_line_on_screen_double(), Display_line_on_screen_fast_double(), Display_part_of_screen_double(), Display_part_of_screen_scaled_double(), Display_transparent_mono_line_on_screen_double(), Horizontal_XOR_line_double(), Pixel_double(), Read_line_screen_double(), Read_pixel_double(), Remap_screen_double(), and Vertical_XOR_line_double().
#define ZOOMY 2
Referenced by Block_double(), Clear_brush_double(), Display_brush_color_double(), Display_brush_color_zoom_double(), Display_brush_double(), Display_brush_mono_double(), Display_brush_mono_zoom_double(), Display_line_on_screen_double(), Display_line_on_screen_fast_double(), Display_part_of_screen_double(), Horizontal_XOR_line_double(), Pixel_double(), Read_line_screen_double(), Read_pixel_double(), Remap_screen_double(), and Vertical_XOR_line_double().
Function Documentation
void Pixel_double (word x, word y, byte color)
References Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video(), Pixel_preview_magnifier_double(), and Pixel_preview_normal_double().
byte Read_pixel_double (word x, word y)
References Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Block_double (word start_x, word start_y, word width, word height, byte color)
References Screen_SDL, ZOOMX, and ZOOMY.
Referenced by Init_mode_video(), and Pixel_preview_magnifier_double().
void Display_part_of_screen_double (word width, word height, word image_width)
References byte, Main_offset_X, Main_offset_Y, Main_screen, Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Pixel_preview_normal_double (word x, word y, byte color)
References Main_offset_X, Main_offset_Y, and Pixel_double().
Referenced by Init_mode_video().
void Pixel_preview_magnifier_double (word x, word y, byte color)
References Block_double(), Limit_left_zoom, Limit_top_zoom, Limit_visible_bottom_zoom, Limit_visible_right_zoom, Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_offset_X, Main_offset_Y, Main_X_zoom, Menu_Y, and Pixel_double().
Referenced by Init_mode_video().
void Horizontal_XOR_line_double (word x_pos, word y_pos, word width)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Vertical_XOR_line_double (word x_pos, word y_pos, word height)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_color_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
References Brush, byte, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, word, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_mono_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, byte color, word brush_width)
References Brush, byte, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Clear_brush_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word image_width)
References byte, Main_offset_X, Main_offset_Y, Main_screen, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_double (byte * brush, word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, word, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Remap_screen_double (word x_pos, word y_pos, word width, word height, byte * conversion_table)
References byte, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_line_on_screen_fast_double (word x_pos, word y_pos, word width, byte * line)
References Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Clear_brush_scaled_double(), Display_part_of_screen_scaled_double(), and Init_mode_video().
void Display_line_on_screen_double (word x_pos, word y_pos, word width, byte * line)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_transparent_mono_line_on_screen_double (word x_pos, word y_pos, word width, byte * line, byte transp_color, byte color)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, and ZOOMX.
Referenced by Display_brush_mono_zoom_double().
void Read_line_screen_double (word x_pos, word y_pos, word width, byte * line)
References Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_part_of_screen_scaled_double (word width, word height, word image_width, byte * buffer)
References byte, Display_line_on_screen_fast_double(), Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_screen, Main_X_zoom, Redraw_grid(), Update_rect(), Zoom_a_line(), and ZOOMX.
Referenced by Init_mode_video().
void Display_brush_color_zoom_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word brush_width, byte * buffer)
References Brush, byte, Display_transparent_line_on_screen_wide(), Main_magnifier_factor, Screen_pixels, VIDEO_LINE_WIDTH, word, Zoom_a_line(), ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_mono_zoom_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, byte color, word brush_width, byte * buffer)
References Brush, byte, Display_transparent_mono_line_on_screen_double(), Main_magnifier_factor, Redraw_grid(), Update_rect(), Zoom_a_line(), and ZOOMY.
Referenced by Init_mode_video().
void Clear_brush_scaled_double (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word image_width, byte * buffer)
References byte, Display_line_on_screen_fast_double(), Main_magnifier_factor, Main_screen, Redraw_grid(), Update_rect(), Zoom_a_line(), and ZOOMX.
Referenced by Init_mode_video().