GrafX2: pxsimple.h File Reference
pxsimple.h File Reference
#include "struct.h"
Functions
void Pixel_simple (word x, word y, byte color)
byte Read_pixel_simple (word x, word y)
void Block_simple (word start_x, word start_y, word width, word height, byte color)
void Pixel_preview_normal_simple (word x, word y, byte color)
void Pixel_preview_magnifier_simple (word x, word y, byte color)
void Horizontal_XOR_line_simple (word x_pos, word y_pos, word width)
void Vertical_XOR_line_simple (word x_pos, word y_pos, word height)
void Display_brush_color_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
void Display_brush_mono_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, byte color, word brush_width)
void Clear_brush_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word image_width)
void Remap_screen_simple (word x_pos, word y_pos, word width, word height, byte *conversion_table)
void Display_part_of_screen_simple (word width, word height, word image_width)
void Display_line_on_screen_simple (word x_pos, word y_pos, word width, byte *line)
void Read_line_screen_simple (word x_pos, word y_pos, word width, byte *line)
void Display_part_of_screen_scaled_simple (word width, word height, word image_width, byte *buffer)
void Display_brush_color_zoom_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word brush_width, byte *buffer)
void Display_brush_mono_zoom_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, byte color, word brush_width, byte *buffer)
void Clear_brush_scaled_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word image_width, byte *buffer)
void Display_brush_simple (byte *brush, word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
void Display_transparent_mono_line_on_screen_simple (word x_pos, word y_pos, word width, byte *line, byte transp_color, byte color)
void Display_transparent_line_on_screen_simple (word x_pos, word y_pos, word width, byte *line, byte transp_color)
Function Documentation
void Pixel_simple (word x, word y, byte color)
References Screen_pixels, and Screen_width.
Referenced by Init_mode_video(), Pixel_preview_magnifier_simple(), and Pixel_preview_normal_simple().
byte Read_pixel_simple (word x, word y)
References Screen_pixels, and Screen_width.
Referenced by Init_mode_video().
void Block_simple (word start_x, word start_y, word width, word height, byte color)
References Screen_SDL.
Referenced by Init_mode_video(), and Pixel_preview_magnifier_simple().
void Pixel_preview_normal_simple (word x, word y, byte color)
References Main_offset_X, Main_offset_Y, and Pixel_simple().
Referenced by Init_mode_video().
void Pixel_preview_magnifier_simple (word x, word y, byte color)
References Block_simple(), Limit_left_zoom, Limit_top_zoom, Limit_visible_bottom_zoom, Limit_visible_right_zoom, Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_offset_X, Main_offset_Y, Main_X_zoom, Menu_Y, Pixel_simple(), and Zoom_factor_table.
Referenced by Init_mode_video().
void Horizontal_XOR_line_simple (word x_pos, word y_pos, word width)
References byte, Screen_pixels, and Screen_width.
Referenced by Init_mode_video().
void Vertical_XOR_line_simple (word x_pos, word y_pos, word height)
References byte, Screen_pixels, and Screen_width.
Referenced by Init_mode_video().
void Display_brush_color_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
References Brush, byte, Screen_pixels, Screen_width, Update_rect(), and word.
Referenced by Init_mode_video().
void Display_brush_mono_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, byte color, word brush_width)
References Brush, byte, Screen_pixels, Screen_width, and Update_rect().
Referenced by Init_mode_video().
void Clear_brush_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word image_width)
References byte, Main_offset_X, Main_offset_Y, Main_screen, Screen_pixels, Screen_width, and Update_rect().
Referenced by Init_mode_video().
void Remap_screen_simple (word x_pos, word y_pos, word width, word height, byte * conversion_table)
References byte, Screen_pixels, Screen_width, and Update_rect().
Referenced by Init_mode_video().
void Display_part_of_screen_simple (word width, word height, word image_width)
References byte, Main_offset_X, Main_offset_Y, Main_screen, Screen_pixels, and Screen_width.
Referenced by Init_mode_video().
void Display_line_on_screen_simple (word x_pos, word y_pos, word width, byte * line)
References Screen_pixels, and Screen_width.
Referenced by Clear_brush_scaled_simple(), Display_part_of_screen_scaled_simple(), Display_part_of_screen_scaled_tall(), and Init_mode_video().
void Read_line_screen_simple (word x_pos, word y_pos, word width, byte * line)
References Screen_pixels, and Screen_width.
Referenced by Init_mode_video().
void Display_part_of_screen_scaled_simple (word width, word height, word image_width, byte * buffer)
References byte, Display_line_on_screen_simple(), Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_screen, Main_X_zoom, Update_rect(), and Zoom_a_line().
Referenced by Init_mode_video().
void Display_brush_color_zoom_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word brush_width, byte * buffer)
References Brush, byte, Display_transparent_line_on_screen_simple(), Main_magnifier_factor, word, and Zoom_a_line().
Referenced by Init_mode_video().
void Display_brush_mono_zoom_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, byte color, word brush_width, byte * buffer)
References Brush, byte, Display_transparent_mono_line_on_screen_simple(), Main_magnifier_factor, Update_rect(), and Zoom_a_line().
Referenced by Init_mode_video().
void Clear_brush_scaled_simple (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word image_width, byte * buffer)
References byte, Display_line_on_screen_simple(), Main_magnifier_factor, Main_screen, Update_rect(), and Zoom_a_line().
Referenced by Init_mode_video().
void Display_brush_simple (byte * brush, word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
References byte, Screen_pixels, Screen_width, and word.
Referenced by Init_mode_video().
void Display_transparent_mono_line_on_screen_simple (word x_pos, word y_pos, word width, byte * line, byte transp_color, byte color)
References byte, Screen_pixels, and Screen_width.
Referenced by Display_brush_mono_zoom_simple(), and Display_brush_mono_zoom_tall().
void Display_transparent_line_on_screen_simple (word x_pos, word y_pos, word width, byte * line, byte transp_color)
References byte, Screen_pixels, Screen_width, and word.
Referenced by Display_brush_color_zoom_simple(), and Display_brush_color_zoom_tall().