GrafX2: pxtall.c File Reference
pxtall.c File Reference
#include <string.h>
#include <stdlib.h>
#include <SDL.h>
#include "global.h"
#include "sdlscreen.h"
#include "misc.h"
#include "graph.h"
#include "pxtall.h"
#include "pxsimple.h"
Defines
#define ZOOMX 1
#define ZOOMY 2
Functions
void Pixel_tall (word x, word y, byte color)
byte Read_pixel_tall (word x, word y)
void Block_tall (word start_x, word start_y, word width, word height, byte color)
void Display_part_of_screen_tall (word width, word height, word image_width)
void Pixel_preview_normal_tall (word x, word y, byte color)
void Pixel_preview_magnifier_tall (word x, word y, byte color)
void Horizontal_XOR_line_tall (word x_pos, word y_pos, word width)
void Vertical_XOR_line_tall (word x_pos, word y_pos, word height)
void Display_brush_color_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
void Display_brush_mono_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, byte color, word brush_width)
void Clear_brush_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word image_width)
void Display_brush_tall (byte *brush, word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
void Remap_screen_tall (word x_pos, word y_pos, word width, word height, byte *conversion_table)
void Display_line_on_screen_tall (word x_pos, word y_pos, word width, byte *line)
void Read_line_screen_tall (word x_pos, word y_pos, word width, byte *line)
void Display_part_of_screen_scaled_tall (word width, word height, word image_width, byte *buffer)
void Display_brush_color_zoom_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word brush_width, byte *buffer)
void Display_brush_mono_zoom_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, byte color, word brush_width, byte *buffer)
void Clear_brush_scaled_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word image_width, byte *buffer)
Define Documentation
#define ZOOMX 1
#define ZOOMY 2
Referenced by Block_tall(), Clear_brush_tall(), Display_brush_color_tall(), Display_brush_color_zoom_tall(), Display_brush_mono_tall(), Display_brush_mono_zoom_tall(), Display_brush_tall(), Display_line_on_screen_tall(), Display_part_of_screen_scaled_tall(), Horizontal_XOR_line_tall(), Pixel_tall(), Read_line_screen_tall(), Read_pixel_tall(), Remap_screen_tall(), and Vertical_XOR_line_tall().
Function Documentation
void Pixel_tall (word x, word y, byte color)
References Screen_pixels, VIDEO_LINE_WIDTH, and ZOOMY.
Referenced by Init_mode_video(), Pixel_preview_magnifier_tall(), and Pixel_preview_normal_tall().
byte Read_pixel_tall (word x, word y)
References Screen_pixels, VIDEO_LINE_WIDTH, and ZOOMY.
Referenced by Init_mode_video().
void Block_tall (word start_x, word start_y, word width, word height, byte color)
References Screen_SDL, and ZOOMY.
Referenced by Init_mode_video(), and Pixel_preview_magnifier_tall().
void Display_part_of_screen_tall (word width, word height, word image_width)
References byte, Main_offset_X, Main_offset_Y, Main_screen, Screen_pixels, and VIDEO_LINE_WIDTH.
Referenced by Init_mode_video().
void Pixel_preview_normal_tall (word x, word y, byte color)
References Main_offset_X, Main_offset_Y, and Pixel_tall().
Referenced by Init_mode_video().
void Pixel_preview_magnifier_tall (word x, word y, byte color)
References Block_tall(), Limit_left_zoom, Limit_top_zoom, Limit_visible_bottom_zoom, Limit_visible_right_zoom, Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_offset_X, Main_offset_Y, Main_X_zoom, Menu_Y, and Pixel_tall().
Referenced by Init_mode_video().
void Horizontal_XOR_line_tall (word x_pos, word y_pos, word width)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, and ZOOMY.
Referenced by Init_mode_video().
void Vertical_XOR_line_tall (word x_pos, word y_pos, word height)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_color_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
References Brush, byte, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, word, and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_mono_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, byte color, word brush_width)
References Brush, byte, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, and ZOOMY.
Referenced by Init_mode_video().
void Clear_brush_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word image_width)
References byte, Main_offset_X, Main_offset_Y, Main_screen, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_tall (byte * brush, word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, word, and ZOOMY.
Referenced by Init_mode_video().
void Remap_screen_tall (word x_pos, word y_pos, word width, word height, byte * conversion_table)
References byte, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, and ZOOMY.
Referenced by Init_mode_video().
void Display_line_on_screen_tall (word x_pos, word y_pos, word width, byte * line)
References Screen_pixels, VIDEO_LINE_WIDTH, and ZOOMY.
Referenced by Clear_brush_scaled_tall(), and Init_mode_video().
void Read_line_screen_tall (word x_pos, word y_pos, word width, byte * line)
References Screen_pixels, VIDEO_LINE_WIDTH, and ZOOMY.
Referenced by Init_mode_video().
void Display_part_of_screen_scaled_tall (word width, word height, word image_width, byte * buffer)
References byte, Display_line_on_screen_simple(), Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_screen, Main_X_zoom, Redraw_grid(), Update_rect(), Zoom_a_line(), and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_color_zoom_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word brush_width, byte * buffer)
References Brush, byte, Display_transparent_line_on_screen_simple(), Main_magnifier_factor, Screen_pixels, VIDEO_LINE_WIDTH, word, Zoom_a_line(), and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_mono_zoom_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, byte color, word brush_width, byte * buffer)
References Brush, byte, Display_transparent_mono_line_on_screen_simple(), Main_magnifier_factor, Redraw_grid(), Update_rect(), Zoom_a_line(), and ZOOMY.
Referenced by Init_mode_video().
void Clear_brush_scaled_tall (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word image_width, byte * buffer)
References byte, Display_line_on_screen_tall(), Main_magnifier_factor, Main_screen, Redraw_grid(), Update_rect(), and Zoom_a_line().
Referenced by Init_mode_video().