GrafX2: pxwide.c File Reference
pxwide.c File Reference
#include <string.h>
#include <stdlib.h>
#include <SDL.h>
#include "global.h"
#include "sdlscreen.h"
#include "misc.h"
#include "graph.h"
#include "pxwide.h"
Defines
#define ZOOMX 2
#define ZOOMY 1
Functions
void Pixel_wide (word x, word y, byte color)
byte Read_pixel_wide (word x, word y)
void Block_wide (word start_x, word start_y, word width, word height, byte color)
void Display_part_of_screen_wide (word width, word height, word image_width)
void Pixel_preview_normal_wide (word x, word y, byte color)
void Pixel_preview_magnifier_wide (word x, word y, byte color)
void Horizontal_XOR_line_wide (word x_pos, word y_pos, word width)
void Vertical_XOR_line_wide (word x_pos, word y_pos, word height)
void Display_brush_color_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
void Display_brush_mono_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, byte color, word brush_width)
void Clear_brush_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word image_width)
void Display_brush_wide (byte *brush, word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
void Remap_screen_wide (word x_pos, word y_pos, word width, word height, byte *conversion_table)
void Display_line_on_screen_fast_wide (word x_pos, word y_pos, word width, byte *line)
void Display_line_on_screen_wide (word x_pos, word y_pos, word width, byte *line)
void Display_transparent_mono_line_on_screen_wide (word x_pos, word y_pos, word width, byte *line, byte transp_color, byte color)
void Read_line_screen_wide (word x_pos, word y_pos, word width, byte *line)
void Display_part_of_screen_scaled_wide (word width, word height, word image_width, byte *buffer)
void Display_transparent_line_on_screen_wide (word x_pos, word y_pos, word width, byte *line, byte transp_color)
void Display_brush_color_zoom_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word brush_width, byte *buffer)
void Display_brush_mono_zoom_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, byte color, word brush_width, byte *buffer)
void Clear_brush_scaled_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word image_width, byte *buffer)
Define Documentation
#define ZOOMX 2
Referenced by Block_wide(), Clear_brush_scaled_wide(), Clear_brush_wide(), Display_brush_color_wide(), Display_brush_mono_wide(), Display_brush_wide(), Display_line_on_screen_fast_wide(), Display_line_on_screen_wide(), Display_part_of_screen_scaled_wide(), Display_part_of_screen_wide(), Display_transparent_line_on_screen_wide(), Display_transparent_mono_line_on_screen_wide(), Horizontal_XOR_line_wide(), Pixel_wide(), Read_line_screen_wide(), Read_pixel_wide(), Remap_screen_wide(), and Vertical_XOR_line_wide().
#define ZOOMY 1
Referenced by Block_wide(), Clear_brush_wide(), Display_brush_color_wide(), Display_brush_color_zoom_wide(), Display_brush_mono_wide(), Display_brush_mono_zoom_wide(), Display_brush_wide(), Display_line_on_screen_fast_wide(), Display_line_on_screen_wide(), Display_part_of_screen_wide(), Horizontal_XOR_line_wide(), Pixel_wide(), Read_line_screen_wide(), Read_pixel_wide(), Remap_screen_wide(), and Vertical_XOR_line_wide().
Function Documentation
void Pixel_wide (word x, word y, byte color)
References Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video(), Pixel_preview_magnifier_wide(), and Pixel_preview_normal_wide().
byte Read_pixel_wide (word x, word y)
References Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Block_wide (word start_x, word start_y, word width, word height, byte color)
References Screen_SDL, ZOOMX, and ZOOMY.
Referenced by Init_mode_video(), and Pixel_preview_magnifier_wide().
void Display_part_of_screen_wide (word width, word height, word image_width)
References byte, Main_offset_X, Main_offset_Y, Main_screen, Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Pixel_preview_normal_wide (word x, word y, byte color)
References Main_offset_X, Main_offset_Y, and Pixel_wide().
Referenced by Init_mode_video().
void Pixel_preview_magnifier_wide (word x, word y, byte color)
References Block_wide(), Limit_left_zoom, Limit_top_zoom, Limit_visible_bottom_zoom, Limit_visible_right_zoom, Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_offset_X, Main_offset_Y, Main_X_zoom, Menu_Y, and Pixel_wide().
Referenced by Init_mode_video().
void Horizontal_XOR_line_wide (word x_pos, word y_pos, word width)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Vertical_XOR_line_wide (word x_pos, word y_pos, word height)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_color_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
References Brush, byte, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, word, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_mono_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, byte color, word brush_width)
References Brush, byte, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Clear_brush_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word image_width)
References byte, Main_offset_X, Main_offset_Y, Main_screen, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_wide (byte * brush, word x_pos, word y_pos, word x_offset, word y_offset, word width, word height, byte transp_color, word brush_width)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, word, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Remap_screen_wide (word x_pos, word y_pos, word width, word height, byte * conversion_table)
References byte, Screen_pixels, Update_rect(), VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_line_on_screen_fast_wide (word x_pos, word y_pos, word width, byte * line)
References Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Clear_brush_scaled_wide(), Display_part_of_screen_scaled_wide(), and Init_mode_video().
void Display_line_on_screen_wide (word x_pos, word y_pos, word width, byte * line)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_transparent_mono_line_on_screen_wide (word x_pos, word y_pos, word width, byte * line, byte transp_color, byte color)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, and ZOOMX.
Referenced by Display_brush_mono_zoom_wide().
void Read_line_screen_wide (word x_pos, word y_pos, word width, byte * line)
References Screen_pixels, VIDEO_LINE_WIDTH, ZOOMX, and ZOOMY.
Referenced by Init_mode_video().
void Display_part_of_screen_scaled_wide (word width, word height, word image_width, byte * buffer)
References byte, Display_line_on_screen_fast_wide(), Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_screen, Main_X_zoom, Redraw_grid(), Update_rect(), Zoom_a_line(), and ZOOMX.
Referenced by Init_mode_video().
void Display_transparent_line_on_screen_wide (word x_pos, word y_pos, word width, byte * line, byte transp_color)
References byte, Screen_pixels, VIDEO_LINE_WIDTH, word, and ZOOMX.
Referenced by Display_brush_color_zoom_double(), and Display_brush_color_zoom_wide().
void Display_brush_color_zoom_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word brush_width, byte * buffer)
References Brush, byte, Display_transparent_line_on_screen_wide(), Main_magnifier_factor, word, Zoom_a_line(), and ZOOMY.
Referenced by Init_mode_video().
void Display_brush_mono_zoom_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, byte color, word brush_width, byte * buffer)
References Brush, byte, Display_transparent_mono_line_on_screen_wide(), Main_magnifier_factor, Redraw_grid(), Update_rect(), Zoom_a_line(), and ZOOMY.
Referenced by Init_mode_video().
void Clear_brush_scaled_wide (word x_pos, word y_pos, word x_offset, word y_offset, word width, word end_y_pos, byte transp_color, word image_width, byte * buffer)
References byte, Display_line_on_screen_fast_wide(), Main_magnifier_factor, Main_screen, Redraw_grid(), Update_rect(), Zoom_a_line(), and ZOOMX.
Referenced by Init_mode_video().