GrafX2: readini.c File Reference
readini.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include "const.h"
#include "errors.h"
#include "global.h"
#include "misc.h"
#include "readini.h"
Defines
#define _XOPEN_SOURCE 500
Functions
void Load_INI_clear_string (char *str, byte keep_comments)
int Load_INI_seek_pattern (char *buffer, char *pattern)
int Load_INI_reach_group (FILE *file, char *buffer, char *group)
int Load_INI_get_string (FILE *file, char *buffer, char *option_name, char *return_code, byte raw_text)
Find the next string in the .INI file.
int Load_INI_get_value (char *str, int *index, int *value)
int Load_INI_get_values (FILE *file, char *buffer, char *option_name, int nb_expected_values, int *values)
int Load_INI (T_Config *conf)
Define Documentation
#define _XOPEN_SOURCE 500
Function Documentation
void Load_INI_clear_string (char * str, byte keep_comments)
Referenced by Load_INI_get_string(), Load_INI_get_values(), Load_INI_reach_group(), Save_INI_reach_group(), Save_INI_set_strings(), and Save_INI_set_values().
int Load_INI_seek_pattern (char * buffer, char * pattern)
Referenced by Load_INI_get_string(), Load_INI_get_value(), Load_INI_get_values(), Load_INI_reach_group(), Save_INI_reach_group(), Save_INI_set_strings(), and Save_INI_set_values().
int Load_INI_reach_group (FILE * file, char * buffer, char * group)
References ERROR_INI_CORRUPTED, Line_number_in_INI_file, Load_INI_clear_string(), and Load_INI_seek_pattern().
Referenced by Load_INI().
int Load_INI_get_string (FILE * file, char * buffer, char * option_name, char * return_code, byte raw_text)
Find the next string in the .INI file.
Parameters:
file INI file currently opened
buffer Current text buffer, preserved from one call to the next
option_name string to search
return_code the found value will be copied there. (must be allocaed)
raw_text Boolean: true to return the raw value (up to end-of-line), false to strip comments.
References ERROR_INI_CORRUPTED, Line_number_in_INI_file, Load_INI_clear_string(), and Load_INI_seek_pattern().
Referenced by Load_INI().
int Load_INI_get_value (char * str, int * index, int * value)
References ERROR_INI_CORRUPTED, and Load_INI_seek_pattern().
Referenced by Load_INI_get_values().
int Load_INI_get_values (FILE * file, char * buffer, char * option_name, int nb_expected_values, int * values)
References ERROR_INI_CORRUPTED, Line_number_in_INI_file, Load_INI_clear_string(), Load_INI_get_value(), and Load_INI_seek_pattern().
Referenced by Load_INI().
int Load_INI (T_Config * conf)
References T_Config::Adjust_brush_pick, T_Config::Auto_discontinuous, T_Config::Auto_nb_used, T_Config::Auto_save, T_Config::Auto_set_res, T_Components::B, T_Config::Backup, T_Config::Bookmark_directory, T_Config::Bookmark_label, T_Config::Clear_palette, T_Config::Clear_with_stencil, Config_directory, Convert_videomode_arg(), T_Config::Coords_rel, T_Config::Cursor, Data_directory, T_Config::Default_resolution, T_Config::Delay_left_click_on_slider, T_Config::Delay_right_click_on_slider, T_Config::Display_image_limits, T_Config::Double_click_speed, T_Config::Double_key_speed, ELLIPSIS_CHARACTER, ERROR_INI_CORRUPTED, ERROR_INI_MISSING, T_Config::Fast_zoom, T_Config::Fav_menu_colors, T_Config::Find_file_fast, T_Config::Font_file, T_Config::FX_Feedback, T_Components::G, T_Config::Grid_XOR_color, Height, T_Video_mode::Height, Line_number_in_INI_file, Load_INI_get_string(), Load_INI_get_values(), Load_INI_reach_group(), T_Config::Max_undo_pages, T_Config::Maximize_preview, Menu_bars, MENUBAR_COUNT, MENUBAR_STATUS, T_Config::Mouse_merge_movement, T_Config::Mouse_sensitivity_index_x, T_Config::Mouse_sensitivity_index_y, NB_BOOKMARKS, T_Config::Nb_max_vertices_per_polygon, T_Config::Opening_message, T_Config::Palette_cells_X, T_Config::Palette_cells_Y, T_Config::Palette_vertical, PIXEL_DOUBLE, PIXEL_QUAD, Pixel_ratio, PIXEL_SIMPLE, PIXEL_TALL, PIXEL_TALL2, PIXEL_TRIPLE, PIXEL_WIDE, PIXEL_WIDE2, T_Components::R, T_Config::Ratio, T_Config::Right_click_colorpick, T_Config::Safety_colors, T_Config::Screen_size_in_GIF, T_Config::Separate_colors, T_Config::Set_resolution_according_to, T_Config::Show_hidden_directories, T_Config::Show_hidden_files, T_Config::Skin_file, T_Config::Stylus_mode, T_Config::Sync_views, T_Config::Timer_delay, Video_mode, T_Menu_Bar::Visible, Width, T_Video_mode::Width, T_Config::Window_pos_x, and T_Config::Window_pos_y.
Referenced by Init_program(), and Settings_load_config().