GrafX2: readline.h File Reference
readline.h File Reference
Text input functions.
Functions
byte Readline (word x_pos, word y_pos, char *str, byte visible_size, byte input_type)
Lets the user input a line of text, exit by Esc or Return.
byte Readline_ex (word x_pos, word y_pos, char *str, byte visible_size, byte max_size, byte input_type)
Lets the user input a line of text, exit by Esc or Return.
Detailed Description
Text input functions.
Function Documentation
byte Readline (word x_pos, word y_pos, char * str, byte visible_size, byte input_type)
Lets the user input a line of text, exit by Esc or Return.
Parameters:
x_pos Coordinates of input, in window coordinates before scaling.
y_pos Coordinates of input, in window coordinates before scaling.
str The original string value (will be modified, unless user cancels.
visible_size Number of characters visible and editable.
input_type 0=string, 1=number, 2=filename (255 editable characters)
Returns:
0 if user cancelled (esc), 1 if accepted (return)
References byte, and Readline_ex().
Referenced by Button_Airbrush_menu(), Button_Colorize_menu(), Button_Grid_menu(), Button_Load_or_Save(), Button_Palette(), Button_Quick_shade_menu(), Button_Resolution(), Button_Settings(), Button_Smooth_menu(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), and Menu_shade().
byte Readline_ex (word x_pos, word y_pos, char * str, byte visible_size, byte max_size, byte input_type)
Lets the user input a line of text, exit by Esc or Return.
Parameters:
x_pos Coordinates of input, in window coordinates before scaling.
y_pos Coordinates of input, in window coordinates before scaling.
str The original string value (will be modified, unless user cancels.
visible_size Number of characters visible.
max_size Number of characters editable.
input_type 0=string, 1=number, 2=filename (255 editable characters)
Returns:
0 if user cancelled (esc), 1 if accepted (return)
References BACKGROUND_COLOR, Block, byte, Display_cursor(), Display_whole_string(), Flush_update(), Get_input(), Hide_cursor, Insert_character(), Key_ANSI, KEY_ESC, LEFT_TRIANGLE_CHARACTER, Menu_factor_X, Menu_factor_Y, Mouse_K, Print_in_window(), Print_in_window_limited(), Remove_character(), RIGHT_SIDE, RIGHT_TRIANGLE_CHARACTER, TEXT_COLOR, Update_rect(), Valid_character(), Window_pos_X, Window_pos_Y, and word.
Referenced by Button_Load_or_Save(), Button_Text(), and Readline().