GrafX2: readini.h File Reference
readini.h File Reference
Reading settings in gfx2.ini.
Functions
int Load_INI (T_Config *conf)
int Load_INI_seek_pattern (char *buffer, char *pattern)
void Load_INI_clear_string (char *str, byte keep_comments)
Detailed Description
Reading settings in gfx2.ini.
Function Documentation
int Load_INI (T_Config * conf)
References T_Config::Adjust_brush_pick, T_Config::Auto_discontinuous, T_Config::Auto_nb_used, T_Config::Auto_save, T_Config::Auto_set_res, T_Components::B, T_Config::Backup, T_Config::Bookmark_directory, T_Config::Bookmark_label, T_Config::Clear_palette, T_Config::Clear_with_stencil, Config_directory, Convert_videomode_arg(), T_Config::Coords_rel, T_Config::Cursor, Data_directory, T_Config::Default_resolution, T_Config::Delay_left_click_on_slider, T_Config::Delay_right_click_on_slider, T_Config::Display_image_limits, T_Config::Double_click_speed, T_Config::Double_key_speed, ELLIPSIS_CHARACTER, ERROR_INI_CORRUPTED, ERROR_INI_MISSING, T_Config::Fast_zoom, T_Config::Fav_menu_colors, T_Config::Find_file_fast, T_Config::Font_file, T_Config::FX_Feedback, T_Components::G, T_Config::Grid_XOR_color, T_Video_mode::Height, Line_number_in_INI_file, Load_INI_get_string(), Load_INI_get_values(), Load_INI_reach_group(), T_Config::Max_undo_pages, T_Config::Maximize_preview, Mouse_fix_factor_X, T_Config::Mouse_fix_factor_X, Mouse_fix_factor_Y, T_Config::Mouse_fix_factor_Y, T_Config::Mouse_merge_movement, T_Config::Mouse_sensitivity_index_x, T_Config::Mouse_sensitivity_index_y, NB_BOOKMARKS, T_Config::Nb_max_vertices_per_polygon, T_Config::Opening_message, T_Config::Palette_cells_X, T_Config::Palette_cells_Y, T_Config::Palette_vertical, T_Components::R, T_Config::Ratio, T_Config::Safety_colors, T_Config::Screen_size_in_GIF, T_Config::Separate_colors, T_Config::Set_resolution_according_to, T_Config::Show_hidden_directories, T_Config::Show_hidden_files, T_Config::Skin_file, T_Config::Timer_delay, Video_mode, T_Video_mode::Width, T_Config::Window_pos_x, and T_Config::Window_pos_y.
Referenced by Init_program(), and Settings_load_config().
int Load_INI_seek_pattern (char * buffer, char * pattern)
Referenced by Load_INI_get_string(), Load_INI_get_value(), Load_INI_get_values(), Load_INI_reach_group(), Save_INI_reach_group(), Save_INI_set_strings(), and Save_INI_set_values().
void Load_INI_clear_string (char * str, byte keep_comments)
Referenced by Load_INI_get_string(), Load_INI_get_values(), Load_INI_reach_group(), Save_INI_reach_group(), Save_INI_set_strings(), and Save_INI_set_values().