GrafX2: readline.c File Reference
readline.c File Reference
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "const.h"
#include "struct.h"
#include "global.h"
#include "misc.h"
#include "errors.h"
#include "sdlscreen.h"
#include "readline.h"
#include "windows.h"
#include "input.h"
Defines
#define TEXT_COLOR MC_Black
#define BACKGROUND_COLOR MC_Light
#define CURSOR_COLOR MC_Black
#define CURSOR_BACKGROUND_COLOR MC_Dark
Functions
void Remove_character (char *str, byte position)
void Insert_character (char *str, char letter, byte position)
int Valid_character (int c)
void Display_whole_string (word x_pos, word y_pos, char *str, byte position)
void Init_virtual_keyboard (word y_pos, word keyboard_width, word keyboard_height)
byte Readline (word x_pos, word y_pos, char *str, byte visible_size, byte input_type)
Lets the user input a line of text, exit by Esc or Return.
byte Readline_ex (word x_pos, word y_pos, char *str, byte visible_size, byte max_size, byte input_type, byte decimal_places)
Lets the user input a line of text, exit by Esc or Return.
void Sprint_double (char *str, double value, byte decimal_places, byte min_positions)
Converts a double to string.
Define Documentation
#define TEXT_COLOR MC_Black
Referenced by Display_whole_string(), and Readline_ex().
#define BACKGROUND_COLOR MC_Light
Referenced by Display_whole_string(), and Readline_ex().
#define CURSOR_COLOR MC_Black
Referenced by Display_whole_string().
#define CURSOR_BACKGROUND_COLOR MC_Dark
Referenced by Display_whole_string().
Function Documentation
void Remove_character (char * str, byte position)
Referenced by Readline_ex().
void Insert_character (char * str, char letter, byte position)
Referenced by Readline_ex().
int Valid_character (int c)
Referenced by Readline_ex().
void Display_whole_string (word x_pos, word y_pos, char * str, byte position)
References BACKGROUND_COLOR, CURSOR_BACKGROUND_COLOR, CURSOR_COLOR, Menu_factor_X, Print_general(), and TEXT_COLOR.
Referenced by Readline_ex().
void Init_virtual_keyboard (word y_pos, word keyboard_width, word keyboard_height)
References Hide_cursor, MC_Black, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, Open_popup(), Screen_height, Screen_width, Window_height, Window_pos_X, Window_pos_Y, Window_rectangle(), and Window_width.
Referenced by Readline_ex().
byte Readline (word x_pos, word y_pos, char * str, byte visible_size, byte input_type)
Lets the user input a line of text, exit by Esc or Return.
Parameters:
x_pos Coordinates of input, in window coordinates before scaling.
y_pos Coordinates of input, in window coordinates before scaling.
str The original string value (will be modified, unless user cancels.
visible_size Number of characters visible and editable.
input_type one of enum INPUT_TYPE
Returns:
0 if user cancelled (esc), 1 if accepted (return)
References byte, and Readline_ex().
Referenced by Button_Airbrush_menu(), Button_Colorize_menu(), Button_Grid_menu(), Button_Load_or_Save(), Button_Palette(), Button_Quick_shade_menu(), Button_Resolution(), Button_Settings(), Button_Smooth_menu(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Menu_shade(), and Requester_window().
byte Readline_ex (word x_pos, word y_pos, char * str, byte visible_size, byte max_size, byte input_type, byte decimal_places)
Lets the user input a line of text, exit by Esc or Return.
Parameters:
x_pos Coordinates of input, in window coordinates before scaling.
y_pos Coordinates of input, in window coordinates before scaling.
str The original string value (will be modified, unless user cancels.
visible_size Number of characters visible.
max_size Number of characters editable.
input_type one of enum INPUT_TYPE
decimal_places Number of decimal places (used only with decimal type)
Returns:
0 if user cancelled (esc), 1 if accepted (return)
References BACKGROUND_COLOR, Block, byte, Close_popup(), Display_cursor(), Display_whole_string(), Flush_update(), Fround(), Get_input(), Hide_cursor, Init_virtual_keyboard(), Input_sticky_control, INPUT_TYPE_DECIMAL, INPUT_TYPE_FILENAME, INPUT_TYPE_HEXA, INPUT_TYPE_INTEGER, INPUT_TYPE_STRING, Insert_character(), Key_ANSI, KEY_ESC, KEY_NONE, Keyboard_click_allowed, LEFT_TRIANGLE_CHARACTER, MC_Black, MC_Light, Menu_factor_X, Menu_factor_Y, Mouse_K, Print_in_window(), Print_in_window_limited(), Remove_character(), RIGHT_SIDE, RIGHT_TRIANGLE_CHARACTER, Sprint_double(), TEXT_COLOR, Update_rect(), Update_window_area, Valid_character(), Wait_end_of_click(), Window_clicked_button(), Window_display_frame_in(), Window_height, Window_pos_X, Window_pos_Y, Window_set_normal_button(), Window_width, and word.
Referenced by Button_Load_or_Save(), Button_Text(), and Readline().
void Sprint_double (char * str, double value, byte decimal_places, byte min_positions)
Converts a double to string.
Parameters:
str Target string, should be pre-allocated and at least 40 characters, to be safe.
value The number to convert
decimal_places Number of decimal places to keep. 15 seems the maximum.
min_positions Minimum number of characters: Will pad spaces on the left to meet this minimum.
Referenced by Readline_ex().