GrafX2: saveini.c File Reference
saveini.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "const.h"
#include "global.h"
#include "readini.h"
#include "io.h"
#include "errors.h"
#include "misc.h"
#include "saveini.h"
Functions
int Save_INI_reach_group (FILE *old_file, FILE *new_file, char *buffer, char *group)
int Save_INI_char_in_value_alphabet (char c)
void Save_INI_set_value (char *dest, char *source, int nb_values_to_set, int *values, int litteral)
void Save_INI_set_string (char *dest, char *source, char *value)
int Save_INI_set_strings (FILE *old_file, FILE *new_file, char *buffer, char *option_name, char *value)
int Save_INI_set_values (FILE *old_file, FILE *new_file, char *buffer, char *option_name, int nb_values_to_set, int *values, int litteral)
void Save_INI_flush (FILE *old_file, FILE *new_file, char *buffer)
int Save_INI (T_Config *conf)
Function Documentation
int Save_INI_reach_group (FILE * old_file, FILE * new_file, char * buffer, char * group)
References ERROR_INI_CORRUPTED, ERROR_SAVING_INI, Load_INI_clear_string(), and Load_INI_seek_pattern().
Referenced by Save_INI().
int Save_INI_char_in_value_alphabet (char c)
Referenced by Save_INI_set_string(), and Save_INI_set_value().
void Save_INI_set_value (char * dest, char * source, int nb_values_to_set, int * values, int litteral)
References Save_INI_char_in_value_alphabet().
Referenced by Save_INI_set_values().
void Save_INI_set_string (char * dest, char * source, char * value)
References Save_INI_char_in_value_alphabet().
Referenced by Save_INI_set_strings().
int Save_INI_set_strings (FILE * old_file, FILE * new_file, char * buffer, char * option_name, char * value)
References ERROR_INI_CORRUPTED, ERROR_SAVING_INI, Load_INI_clear_string(), Load_INI_seek_pattern(), and Save_INI_set_string().
Referenced by Save_INI().
int Save_INI_set_values (FILE * old_file, FILE * new_file, char * buffer, char * option_name, int nb_values_to_set, int * values, int litteral)
References ERROR_INI_CORRUPTED, ERROR_SAVING_INI, Load_INI_clear_string(), Load_INI_seek_pattern(), and Save_INI_set_value().
Referenced by Save_INI().
void Save_INI_flush (FILE * old_file, FILE * new_file, char * buffer)
Referenced by Save_INI().
int Save_INI (T_Config * conf)
References T_Config::Adjust_brush_pick, T_Config::Auto_discontinuous, T_Config::Auto_nb_used, T_Config::Auto_save, T_Config::Auto_set_res, T_Components::B, T_Config::Backup, T_Config::Bookmark_directory, T_Config::Bookmark_label, T_Config::Clear_palette, T_Config::Clear_with_stencil, Config_directory, T_Config::Coords_rel, T_Config::Cursor, Data_directory, T_Config::Default_resolution, T_Config::Delay_left_click_on_slider, T_Config::Delay_right_click_on_slider, T_Config::Display_image_limits, ERROR_INI_MISSING, ERROR_SAVING_INI, T_Config::Fast_zoom, T_Config::Fav_menu_colors, File_exists(), T_Config::Find_file_fast, T_Config::Font, T_Config::FX_Feedback, T_Components::G, T_Video_mode::Height, MAX_PATH_CHARACTERS, T_Config::Max_undo_pages, T_Config::Maximize_preview, Mode_label(), T_Config::Mouse_fix_factor_X, T_Config::Mouse_fix_factor_Y, T_Config::Mouse_merge_movement, T_Config::Mouse_sensitivity_index_x, T_Config::Mouse_sensitivity_index_y, NB_BOOKMARKS, T_Config::Nb_max_vertices_per_polygon, T_Config::Opening_message, T_Config::Palette_cells_X, T_Config::Palette_cells_Y, T_Config::Palette_vertical, T_Components::R, T_Config::Ratio, T_Config::Safety_colors, Save_INI_flush(), Save_INI_reach_group(), Save_INI_set_strings(), Save_INI_set_values(), T_Config::Screen_size_in_GIF, T_Config::Separate_colors, T_Config::Set_resolution_according_to, T_Config::Show_hidden_directories, T_Config::Show_hidden_files, T_Config::Timer_delay, Video_mode, T_Video_mode::Width, T_Config::Window_pos_x, and T_Config::Window_pos_y.
Referenced by Program_shutdown(), and Settings_save_config().