GrafX2: sdlscreen.h File Reference
sdlscreen.h File Reference
Screen update (refresh) system, and some SDL-specific graphic functions.
#include <SDL.h>
#include "struct.h"
Defines
#define VIDEO_LINE_WIDTH (Screen_SDL->pitch)
This is the number of bytes in a video line for the current mode.
Functions
void Set_mode_SDL (int *, int *, int)
Sets the new screen/window dimensions.
void Update_rect (short x, short y, unsigned short width, unsigned short height)
void Flush_update (void)
byte * Surface_to_bytefield (SDL_Surface *source, byte *dest)
Converts a SDL_Surface (indexed colors or RGB) into an array of bytes (indexed colors).
SDL_Color Color_to_SDL_color (byte)
Gets the RGB 24-bit color currently associated with a palette index.
byte Get_SDL_pixel_8 (SDL_Surface *bmp, int x, int y)
Reads a pixel in a 8-bit SDL surface.
dword Get_SDL_pixel_hicolor (SDL_Surface *bmp, int x, int y)
Reads a pixel in a multi-byte SDL surface.
void Get_SDL_Palette (const SDL_Palette *sdl_palette, T_Palette palette)
Convert a SDL Palette to a grafx2 palette.
void Clear_border (byte color)
Clears the parts of screen that are outside of the editing area.
Variables
SDL_Rect ** List_SDL_video_modes
byte * Screen_pixels
Detailed Description
Screen update (refresh) system, and some SDL-specific graphic functions.
Define Documentation
#define VIDEO_LINE_WIDTH (Screen_SDL->pitch)
This is the number of bytes in a video line for the current mode.
On many platforms it will be the video mode's width (in pixels), rounded up to be a multiple of 4.
Referenced by Clear_brush_double(), Clear_brush_quad(), Clear_brush_simple(), Clear_brush_tall(), Clear_brush_tall2(), Clear_brush_triple(), Clear_brush_wide(), Clear_brush_wide2(), Display_brush_color_double(), Display_brush_color_quad(), Display_brush_color_simple(), Display_brush_color_tall(), Display_brush_color_tall2(), Display_brush_color_triple(), Display_brush_color_wide(), Display_brush_color_wide2(), Display_brush_color_zoom_double(), Display_brush_color_zoom_quad(), Display_brush_color_zoom_tall(), Display_brush_color_zoom_tall2(), Display_brush_color_zoom_triple(), Display_brush_color_zoom_wide2(), Display_brush_double(), Display_brush_mono_double(), Display_brush_mono_quad(), Display_brush_mono_simple(), Display_brush_mono_tall(), Display_brush_mono_tall2(), Display_brush_mono_triple(), Display_brush_mono_wide(), Display_brush_mono_wide2(), Display_brush_quad(), Display_brush_simple(), Display_brush_tall(), Display_brush_tall2(), Display_brush_triple(), Display_brush_wide(), Display_brush_wide2(), Display_line_on_screen_double(), Display_line_on_screen_fast_double(), Display_line_on_screen_fast_quad(), Display_line_on_screen_fast_tall2(), Display_line_on_screen_fast_triple(), Display_line_on_screen_fast_wide(), Display_line_on_screen_fast_wide2(), Display_line_on_screen_quad(), Display_line_on_screen_simple(), Display_line_on_screen_tall(), Display_line_on_screen_tall2(), Display_line_on_screen_triple(), Display_line_on_screen_wide(), Display_line_on_screen_wide2(), Display_part_of_screen_double(), Display_part_of_screen_quad(), Display_part_of_screen_simple(), Display_part_of_screen_tall(), Display_part_of_screen_tall2(), Display_part_of_screen_triple(), Display_part_of_screen_wide(), Display_part_of_screen_wide2(), Display_transparent_line_on_screen_simple(), Display_transparent_line_on_screen_wide(), Display_transparent_mono_line_on_screen_double(), Display_transparent_mono_line_on_screen_quad(), Display_transparent_mono_line_on_screen_simple(), Display_transparent_mono_line_on_screen_tall2(), Display_transparent_mono_line_on_screen_triple(), Display_transparent_mono_line_on_screen_wide(), Display_transparent_mono_line_on_screen_wide2(), Horizontal_grid_line(), Horizontal_XOR_line_double(), Horizontal_XOR_line_quad(), Horizontal_XOR_line_simple(), Horizontal_XOR_line_tall(), Horizontal_XOR_line_tall2(), Horizontal_XOR_line_triple(), Horizontal_XOR_line_wide(), Horizontal_XOR_line_wide2(), Pixel_double(), Pixel_quad(), Pixel_simple(), Pixel_tall(), Pixel_tall2(), Pixel_triple(), Pixel_wide(), Pixel_wide2(), Read_line_screen_double(), Read_line_screen_quad(), Read_line_screen_simple(), Read_line_screen_tall(), Read_line_screen_tall2(), Read_line_screen_triple(), Read_line_screen_wide(), Read_line_screen_wide2(), Read_pixel_double(), Read_pixel_quad(), Read_pixel_simple(), Read_pixel_tall(), Read_pixel_tall2(), Read_pixel_triple(), Read_pixel_wide(), Read_pixel_wide2(), Remap_screen_double(), Remap_screen_quad(), Remap_screen_simple(), Remap_screen_tall(), Remap_screen_tall2(), Remap_screen_triple(), Remap_screen_wide(), Remap_screen_wide2(), Vertical_grid_line(), Vertical_XOR_line_double(), Vertical_XOR_line_quad(), Vertical_XOR_line_simple(), Vertical_XOR_line_tall(), Vertical_XOR_line_tall2(), Vertical_XOR_line_triple(), Vertical_XOR_line_wide(), and Vertical_XOR_line_wide2().
Function Documentation
void Set_mode_SDL (int * , int * , int)
Sets the new screen/window dimensions.
References DEBUG, Screen_pixels, and Screen_SDL.
Referenced by Init_mode_video().
void Update_rect (short x, short y, unsigned short width, unsigned short height)
References Max_X, Max_Y, Min_X, Min_Y, Pixel_height, Pixel_width, and Screen_SDL.
Referenced by Button_Airbrush_menu(), Button_Magnify(), Button_Magnify_menu(), Button_Palette(), Button_Quick_shade_menu(), Button_Sieve_menu(), Button_Stats(), Button_Text(), Check_mode_button(), Clear_brush_double(), Clear_brush_quad(), Clear_brush_scaled_double(), Clear_brush_scaled_quad(), Clear_brush_scaled_simple(), Clear_brush_scaled_tall(), Clear_brush_scaled_tall2(), Clear_brush_scaled_triple(), Clear_brush_scaled_wide(), Clear_brush_scaled_wide2(), Clear_brush_simple(), Clear_brush_tall(), Clear_brush_tall2(), Clear_brush_triple(), Clear_brush_wide(), Clear_brush_wide2(), Close_popup(), Close_window(), Confirmation_box(), Display_all_screen(), Display_all_shade(), Display_brush_color_double(), Display_brush_color_quad(), Display_brush_color_simple(), Display_brush_color_tall(), Display_brush_color_tall2(), Display_brush_color_triple(), Display_brush_color_wide(), Display_brush_color_wide2(), Display_brush_mono_double(), Display_brush_mono_quad(), Display_brush_mono_simple(), Display_brush_mono_tall(), Display_brush_mono_tall2(), Display_brush_mono_triple(), Display_brush_mono_wide(), Display_brush_mono_wide2(), Display_brush_mono_zoom_double(), Display_brush_mono_zoom_quad(), Display_brush_mono_zoom_simple(), Display_brush_mono_zoom_tall(), Display_brush_mono_zoom_tall2(), Display_brush_mono_zoom_triple(), Display_brush_mono_zoom_wide(), Display_brush_mono_zoom_wide2(), Display_cursor(), Display_effect_sprite(), Display_foreback(), Display_grad_block_in_window(), Display_help(), Display_image_limits(), Display_menu(), Display_menu_palette(), Display_menu_palette_avoiding_window(), Display_paintbrush_in_menu(), Display_paintbrush_in_window(), Display_part_of_screen_scaled_double(), Display_part_of_screen_scaled_quad(), Display_part_of_screen_scaled_simple(), Display_part_of_screen_scaled_tall(), Display_part_of_screen_scaled_tall2(), Display_part_of_screen_scaled_triple(), Display_part_of_screen_scaled_wide(), Display_part_of_screen_scaled_wide2(), Display_separator(), Display_sprite_in_menu(), Distort_brush_1_9(), Draw_button_gradient_style(), Draw_gradient_preview(), Draw_menu_button_frame(), Draw_preset_sieve_patterns(), Draw_sieve_scaled(), Fill_general(), Frame_menu_color(), Get_color_behind_window(), Grad_rectangle_0_5(), Grad_rectangle_0_9(), Grad_rectangle_12_7(), Hide_cursor(), Horizontal_XOR_line_zoom(), Main_handler(), Menu_shade(), Move_separator(), Move_window(), Print_coordinates(), Print_counter(), Print_in_menu(), Print_in_window(), Readline_ex(), Refresh_airbrush_settings(), Remap_screen_double(), Remap_screen_quad(), Remap_screen_simple(), Remap_screen_tall(), Remap_screen_tall2(), Remap_screen_triple(), Remap_screen_wide(), Remap_screen_wide2(), Replace_a_color(), Requester_window(), Scroll_picture(), Shade_draw_grad_ranges(), Stencil_update_color(), Tag_color_range(), Tag_shades(), Update_part_of_screen(), Update_sieve_area(), Vertical_XOR_line_zoom(), Warning_message(), Window_clear_input_button(), Window_clear_tags(), Window_display_icon_sprite(), Window_draw_slider(), Window_dropdown_on_click(), Window_help(), Window_select_normal_button(), Window_set_shortcut(), and Window_unselect_normal_button().
void Flush_update (void)
References Max_X, Max_Y, Min(), Min_X, Min_Y, Pixel_height, Pixel_width, Screen_height, Screen_SDL, and Screen_width.
Referenced by Get_input(), Load_image(), Pixel_figure_permanent(), and Readline_ex().
byte* Surface_to_bytefield (SDL_Surface * source, byte * dest)
Converts a SDL_Surface (indexed colors or RGB) into an array of bytes (indexed colors).
If dest is NULL, it's allocated by malloc(). Otherwise, be sure to pass a buffer of the right dimensions.
References byte.
Referenced by Render_text_SFont(), and Render_text_TTF().
SDL_Color Color_to_SDL_color (byte)
Gets the RGB 24-bit color currently associated with a palette index.
References Main_palette.
Referenced by Render_text_TTF().
byte Get_SDL_pixel_8 (SDL_Surface * bmp, int x, int y)
Reads a pixel in a 8-bit SDL surface.
References byte.
Referenced by GUI_seek_down(), GUI_seek_right(), Load_SDL_Image(), Parse_font(), Parse_skin(), and Read_GUI_block().
dword Get_SDL_pixel_hicolor (SDL_Surface * bmp, int x, int y)
Reads a pixel in a multi-byte SDL surface.
References byte, dword, and word.
Referenced by Load_SDL_Image().
void Get_SDL_Palette (const SDL_Palette * sdl_palette, T_Palette palette)
Convert a SDL Palette to a grafx2 palette.
Referenced by Load_SDL_Image(), and Parse_skin().
void Clear_border (byte color)
Clears the parts of screen that are outside of the editing area.
There is such area only if the screen mode is not a multiple of the pixel size, eg: 3x3 pixels in 1024x768 leaves 1 column on the right, 0 rows on bottom.
References Pixel_height, Pixel_width, Screen_height, Screen_SDL, and Screen_width.
Referenced by Init_mode_video(), Remap_menu_sprites(), and Remap_screen_after_menu_colors_change().
Variable Documentation
SDL_Rect** List_SDL_video_modes
byte* Screen_pixels
Referenced by Clear_brush_double(), Clear_brush_quad(), Clear_brush_simple(), Clear_brush_tall(), Clear_brush_tall2(), Clear_brush_triple(), Clear_brush_wide(), Clear_brush_wide2(), Count_used_colors_screen_area(), Display_brush_color_double(), Display_brush_color_quad(), Display_brush_color_simple(), Display_brush_color_tall(), Display_brush_color_tall2(), Display_brush_color_triple(), Display_brush_color_wide(), Display_brush_color_wide2(), Display_brush_color_zoom_double(), Display_brush_color_zoom_quad(), Display_brush_color_zoom_tall(), Display_brush_color_zoom_tall2(), Display_brush_color_zoom_triple(), Display_brush_color_zoom_wide2(), Display_brush_double(), Display_brush_mono_double(), Display_brush_mono_quad(), Display_brush_mono_simple(), Display_brush_mono_tall(), Display_brush_mono_tall2(), Display_brush_mono_triple(), Display_brush_mono_wide(), Display_brush_mono_wide2(), Display_brush_quad(), Display_brush_simple(), Display_brush_tall(), Display_brush_tall2(), Display_brush_triple(), Display_brush_wide(), Display_brush_wide2(), Display_line_on_screen_double(), Display_line_on_screen_fast_double(), Display_line_on_screen_fast_quad(), Display_line_on_screen_fast_tall2(), Display_line_on_screen_fast_triple(), Display_line_on_screen_fast_wide(), Display_line_on_screen_fast_wide2(), Display_line_on_screen_quad(), Display_line_on_screen_simple(), Display_line_on_screen_tall(), Display_line_on_screen_tall2(), Display_line_on_screen_triple(), Display_line_on_screen_wide(), Display_line_on_screen_wide2(), Display_part_of_screen_double(), Display_part_of_screen_quad(), Display_part_of_screen_simple(), Display_part_of_screen_tall(), Display_part_of_screen_tall2(), Display_part_of_screen_triple(), Display_part_of_screen_wide(), Display_part_of_screen_wide2(), Display_transparent_line_on_screen_simple(), Display_transparent_line_on_screen_wide(), Display_transparent_mono_line_on_screen_double(), Display_transparent_mono_line_on_screen_quad(), Display_transparent_mono_line_on_screen_simple(), Display_transparent_mono_line_on_screen_tall2(), Display_transparent_mono_line_on_screen_triple(), Display_transparent_mono_line_on_screen_wide(), Display_transparent_mono_line_on_screen_wide2(), Horizontal_grid_line(), Horizontal_XOR_line_double(), Horizontal_XOR_line_quad(), Horizontal_XOR_line_simple(), Horizontal_XOR_line_tall(), Horizontal_XOR_line_tall2(), Horizontal_XOR_line_triple(), Horizontal_XOR_line_wide(), Horizontal_XOR_line_wide2(), Pixel_double(), Pixel_quad(), Pixel_simple(), Pixel_tall(), Pixel_tall2(), Pixel_triple(), Pixel_wide(), Pixel_wide2(), Read_line_screen_double(), Read_line_screen_quad(), Read_line_screen_simple(), Read_line_screen_tall(), Read_line_screen_tall2(), Read_line_screen_triple(), Read_line_screen_wide(), Read_line_screen_wide2(), Read_pixel_double(), Read_pixel_quad(), Read_pixel_simple(), Read_pixel_tall(), Read_pixel_tall2(), Read_pixel_triple(), Read_pixel_wide(), Read_pixel_wide2(), Remap_screen_double(), Remap_screen_quad(), Remap_screen_simple(), Remap_screen_tall(), Remap_screen_tall2(), Remap_screen_triple(), Remap_screen_wide(), Remap_screen_wide2(), Set_mode_SDL(), Vertical_grid_line(), Vertical_XOR_line_double(), Vertical_XOR_line_quad(), Vertical_XOR_line_simple(), Vertical_XOR_line_tall(), Vertical_XOR_line_tall2(), Vertical_XOR_line_triple(), Vertical_XOR_line_wide(), and Vertical_XOR_line_wide2().
Generated for GrafX2 by