GrafX2: setup.h File Reference
setup.h File Reference
Functions that determine where grafx2 is running, finds its data, and reads and writes configuration files.
Functions
void Set_program_directory (const char *argv0, char *program_dir)
Determine which directory contains the executable.
void Set_data_directory (const char *program_dir, char *data_dir)
Determine which directory contains the read-only data.
void Set_config_directory (const char *program_dir, char *config_dir)
Determine which directory should store the user's configuration.
Detailed Description
Functions that determine where grafx2 is running, finds its data, and reads and writes configuration files.
Function Documentation
void Set_program_directory (const char * argv0, char * program_dir)
Determine which directory contains the executable.
IN: Main's argv[0], some platforms need it, some don't.
OUT: Write into program_dir. Trailing / or \ is kept. Note : in fact this is only used to check for the datafiles and fonts in this same directory.
void Set_data_directory (const char * program_dir, char * data_dir)
Determine which directory contains the read-only data.
IN: The directory containing the executable OUT: Write into data_dir. Trailing / or \ is kept.
Referenced by Init_program().
void Set_config_directory (const char * program_dir, char * config_dir)
Determine which directory should store the user's configuration.
For most Unix and Windows platforms: If a config file already exists in program_dir, it will return it in priority (Useful for development, and possibly for upgrading from DOS version) If the standard directory doesn't exist yet, this function will attempt to create it (/home/pulkomandy/.grafx2, or APPDATA%\GrafX2) If it cannot be created, this function will return the executable's own directory. IN: The directory containing the executable OUT: Write into config_dir. Trailing / or \ is kept.
References Create_ConfigDirectory(), Directory_exists(), File_exists(), MAX_PATH_CHARACTERS, and PATH_SEPARATOR.
Referenced by Init_program().