GrafX2: setup.c File Reference
setup.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "struct.h"
#include "io.h"
#include "setup.h"
Defines
#define ARG_UNUSED
Functions
int Create_ConfigDirectory (char *config_dir)
void Set_program_directory (ARG_UNUSED const char *argv0, char *program_dir)
void Set_data_directory (const char *program_dir, char *data_dir)
Determine which directory contains the read-only data.
void Set_config_directory (const char *program_dir, char *config_dir)
Determine which directory should store the user's configuration.
Define Documentation
#define ARG_UNUSED
Function Documentation
int Create_ConfigDirectory (char * config_dir)
Referenced by Set_config_directory().
void Set_program_directory (ARG_UNUSED const char * argv0, char * program_dir)
References Extract_path().
Referenced by Init_program().
void Set_data_directory (const char * program_dir, char * data_dir)
Determine which directory contains the read-only data.
IN: The directory containing the executable OUT: Write into data_dir. Trailing / or \ is kept.
Referenced by Init_program().
void Set_config_directory (const char * program_dir, char * config_dir)
Determine which directory should store the user's configuration.
For most Unix and Windows platforms: If a config file already exists in program_dir, it will return it in priority (Useful for development, and possibly for upgrading from DOS version) If the standard directory doesn't exist yet, this function will attempt to create it (/home/pulkomandy/.grafx2, or APPDATA%\GrafX2) If it cannot be created, this function will return the executable's own directory. IN: The directory containing the executable OUT: Write into config_dir. Trailing / or \ is kept.
References Create_ConfigDirectory(), Directory_exists(), File_exists(), MAX_PATH_CHARACTERS, and PATH_SEPARATOR.
Referenced by Init_program().