GrafX2: SFont.h File Reference
SFont.h File Reference
Text rendering system, that uses bitmaps as fonts.
#include <SDL.h>
Data Structures
struct SFont_Font
Declare one variable of this type for each font you are using.
Functions
SFont_Font * SFont_InitFont (SDL_Surface *Font)
Initializes the font.
void SFont_FreeFont (SFont_Font *Font)
Frees the font.
void SFont_Write (SDL_Surface *Surface, const SFont_Font *Font, int x, int y, const char *text)
Blits a string to a surface.
int SFont_TextWidth (const SFont_Font *Font, const char *text)
Returns the width of "text" in pixels.
int SFont_TextHeight (const SFont_Font *Font)
Returns the height of "text" in pixels (which is always equal to Font->Surface->h)
void SFont_WriteCenter (SDL_Surface *Surface, const SFont_Font *Font, int y, const char *text)
Blits a string to Surface with centered x position.
Detailed Description
Text rendering system, that uses bitmaps as fonts.
Not specific to Grafx2, it writes to SDL_Surface.
Function Documentation
SFont_Font* SFont_InitFont (SDL_Surface * Font)
Initializes the font.
Parameters:
Font this contains the suface with the font. The Surface must be loaded before calling this function
References SFont_Font::CharBegin, SFont_Font::CharWidth, GetPixel(), SFont_Font::Space, and SFont_Font::Surface.
Referenced by Render_text_SFont().
void SFont_FreeFont (SFont_Font * Font)
Frees the font.
Parameters:
Font The font to free The font must be loaded before using this function.
References SFont_Font::Surface.
Referenced by Render_text_SFont().
void SFont_Write (SDL_Surface * Surface, const SFont_Font * Font, int x, int y, const char * text)
Blits a string to a surface.
Parameters:
Surface The surface you want to blit to.
Font The font to use.
text A string containing the text you want to blit.
x Coordinates to start drawing.
y Coordinates to start drawing.
References SFont_Font::CharBegin, SFont_Font::CharWidth, SFont_Font::Space, and SFont_Font::Surface.
Referenced by Render_text_SFont(), and SFont_WriteCenter().
int SFont_TextWidth (const SFont_Font * Font, const char * text)
Returns the width of "text" in pixels.
References SFont_Font::CharWidth, and SFont_Font::Space.
Referenced by Render_text_SFont(), and SFont_WriteCenter().
int SFont_TextHeight (const SFont_Font * Font)
Returns the height of "text" in pixels (which is always equal to Font->Surface->h)
References SFont_Font::Surface.
Referenced by Render_text_SFont().
void SFont_WriteCenter (SDL_Surface * Surface, const SFont_Font * Font, int y, const char * text)
Blits a string to Surface with centered x position.
References SFont_TextWidth(), and SFont_Write().