GrafX2: SFont.c File Reference
SFont.c File Reference
#include <SDL.h>
#include <SDL_video.h>
#include <assert.h>
#include <stdlib.h>
#include "SFont.h"
Functions
static Uint32 GetPixel (SDL_Surface *Surface, Sint32 X, Sint32 Y)
SFont_Font * SFont_InitFont (SDL_Surface *Surface)
void SFont_FreeFont (SFont_Font *FontInfo)
void SFont_Write (SDL_Surface *Surface, const SFont_Font *Font, int x, int y, const char *text)
int SFont_TextWidth (const SFont_Font *Font, const char *text)
int SFont_TextHeight (const SFont_Font *Font)
void SFont_WriteCenter (SDL_Surface *Surface, const SFont_Font *Font, int y, const char *text)
Function Documentation
static Uint32 GetPixel (SDL_Surface * Surface, Sint32 X, Sint32 Y) [static]
Referenced by SFont_InitFont().
SFont_Font* SFont_InitFont (SDL_Surface * Surface)
References SFont_Font::CharPos, GetPixel(), SFont_Font::MaxPos, and SFont_Font::Surface.
Referenced by Render_text_SFont().
void SFont_FreeFont (SFont_Font * FontInfo)
References SFont_Font::Surface.
Referenced by Render_text_SFont().
void SFont_Write (SDL_Surface * Surface, const SFont_Font * Font, int x, int y, const char * text)
References SFont_Font::CharPos, SFont_Font::MaxPos, and SFont_Font::Surface.
Referenced by Render_text_SFont(), and SFont_WriteCenter().
int SFont_TextWidth (const SFont_Font * Font, const char * text)
References SFont_Font::CharPos, and SFont_Font::MaxPos.
Referenced by Render_text_SFont(), and SFont_WriteCenter().
int SFont_TextHeight (const SFont_Font * Font)
References SFont_Font::Surface.
Referenced by Render_text_SFont().
void SFont_WriteCenter (SDL_Surface * Surface, const SFont_Font * Font, int y, const char * text)
References SFont_TextWidth(), and SFont_Write().