GrafX2: shade.h File Reference
shade.h File Reference
Screens for Shade and Quick-shade settings.
Functions
void Button_Quick_shade_menu (void)
int Shade_settings_menu (void)
Handles the screen with Shade settings.
Detailed Description
Screens for Shade and Quick-shade settings.
Function Documentation
void Button_Quick_shade_menu (void)
References BUTTON_EFFECTS, BUTTON_HELP, Button_Quick_shade_mode(), byte, Close_window(), Display_cursor(), Display_shade_mode(), Hide_cursor, INPUT_TYPE_INTEGER, Is_shortcut(), Key, KEY_ESC, MC_Dark, MC_Light, Menu_factor_X, Menu_factor_Y, Num2str, Open_window(), Print_in_window(), Quick_shade_loop, Quick_shade_mode, Quick_shade_step, Readline(), SPECIAL_QUICK_SHADE_MENU, Update_rect(), Window_clicked_button(), Window_help(), Window_input_content(), Window_pos_X, Window_pos_Y, Window_set_input_button(), and Window_set_normal_button().
Referenced by Button_Effects(), and Main_handler().
int Shade_settings_menu (void)
Handles the screen with Shade settings.
Returns:
true if user clicked ok, false if he cancelled
References byte, Display_cursor(), Menu_shade(), Shade_current, Shade_list, Shade_list_to_lookup_tables(), Shade_table_left, and Shade_table_right.
Referenced by Button_Secondary_palette(), and Button_Shade_menu().