GrafX2: shade.c File Reference
shade.c File Reference
#include <string.h>
#include <stdlib.h>
#include "global.h"
#include "graph.h"
#include "engine.h"
#include "errors.h"
#include "misc.h"
#include "readline.h"
#include "help.h"
#include "sdlscreen.h"
#include "windows.h"
#include "input.h"
#include "shade.h"
Functions
void Button_Shade_mode (void)
Callback for the shade button (in the FX window).
void Button_Quick_shade_mode (void)
Callback for the QSHade button (in the FX window).
void Shade_draw_grad_ranges (void)
void Tag_shades (word selection_start, word selection_end)
void Display_selected_cell_color (word selection_start, word selection_end)
void Display_selected_color (word selection_start, word selection_end)
void Display_shade_mode (short x, short y, byte mode)
void Display_all_shade (word selection_start1, word selection_end1, word selection_start2, word selection_end2)
void Remove_shade (word selection_start, word selection_end)
void Insert_shade (byte first_color, byte last_color, word selection_start)
void Insert_empty_cell_in_shade (word position)
short Wait_click_in_shade_table ()
void Swap_shade (short block_1_start, short block_2_start, short block_size)
int Menu_shade (void)
int Shade_settings_menu (void)
Handles the screen with Shade settings.
void Button_Shade_menu (void)
Callback for the Shade button (in the FX window) right click.
void Button_Quick_shade_menu (void)
Function Documentation
void Button_Shade_mode (void)
Callback for the shade button (in the FX window).
Toogle the shade mode.
References Colorize_mode, Effect_function, Effect_shade(), No_effect(), Quick_shade_mode, Shade_mode, Smear_mode, Smooth_mode, and Tiling_mode.
Referenced by Button_Effects(), Button_Shade_menu(), and Main_handler().
void Button_Quick_shade_mode (void)
Callback for the QSHade button (in the FX window).
Toogle the Quick Shade effect.
References Colorize_mode, Effect_function, Effect_quick_shade(), No_effect(), Quick_shade_mode, Shade_mode, Smear_mode, Smooth_mode, and Tiling_mode.
Referenced by Button_Effects(), Button_Quick_shade_menu(), and Main_handler().
void Shade_draw_grad_ranges (void)
References Block, T_Shade::List, MC_Light, Menu_factor_X, Menu_factor_Y, Pixel, Shade_current, Shade_list, Update_rect(), Window_display_frame_out(), Window_pos_X, Window_pos_Y, and word.
Referenced by Display_all_shade(), and Menu_shade().
void Tag_shades (word selection_start, word selection_end)
References Block, MC_Black, MC_Light, MC_White, Menu_factor_X, Menu_factor_Y, Shade_current, Shade_list, Update_rect(), Window_pos_X, Window_pos_Y, and word.
Referenced by Display_all_shade(), and Menu_shade().
void Display_selected_cell_color (word selection_start, word selection_end)
References MC_Black, MC_Light, Num2str(), Print_in_window(), Shade_current, and Shade_list.
Referenced by Display_all_shade(), and Menu_shade().
void Display_selected_color (word selection_start, word selection_end)
References MC_Black, MC_Light, Num2str(), and Print_in_window().
Referenced by Display_all_shade(), and Menu_shade().
void Display_shade_mode (short x, short y, byte mode)
References MC_Black, MC_Light, Print_in_window(), SHADE_MODE_LOOP, and SHADE_MODE_NORMAL.
Referenced by Button_Quick_shade_menu(), Display_all_shade(), and Menu_shade().
void Display_all_shade (word selection_start1, word selection_end1, word selection_start2, word selection_end2)
References Block, Display_selected_cell_color(), Display_selected_color(), Display_shade_mode(), MC_Light, Menu_factor_X, Menu_factor_Y, Shade_current, Shade_draw_grad_ranges(), Shade_list, Tag_shades(), Update_rect(), Window_display_frame_out(), Window_pos_X, Window_pos_Y, and word.
Referenced by Menu_shade().
void Remove_shade (word selection_start, word selection_end)
References Shade_current, Shade_list, and word.
Referenced by Menu_shade().
void Insert_shade (byte first_color, byte last_color, word selection_start)
References T_Shade::List, Shade_current, Shade_list, and word.
Referenced by Menu_shade().
void Insert_empty_cell_in_shade (word position)
References T_Shade::List, Shade_current, Shade_list, and word.
Referenced by Menu_shade().
short Wait_click_in_shade_table ()
References byte, Cursor_hidden, Cursor_shape, CURSOR_SHAPE_ARROW, CURSOR_SHAPE_TARGET, Display_cursor(), Get_input(), Hide_cursor, Key, KEY_ESC, LEFT_SIDE, Menu_factor_X, Menu_factor_Y, Mouse_K, Mouse_X, Mouse_Y, RIGHT_SIDE, Window_click_in_rectangle(), Window_height, Window_pos_X, Window_pos_Y, and Window_width.
Referenced by Menu_shade().
void Swap_shade (short block_1_start, short block_2_start, short block_size)
References T_Shade::List, Shade_current, Shade_list, and word.
Referenced by Menu_shade().
int Menu_shade (void)
References Block, BUTTON_EFFECTS, BUTTON_HELP, byte, Close_window(), Display_all_shade(), Display_cursor(), Display_grad_block_in_window(), Display_selected_cell_color(), Display_selected_color(), Display_shade_mode(), Fore_color, Get_color_behind_window(), Hide_cursor, Insert_empty_cell_in_shade(), Insert_shade(), Is_shortcut(), Key, KEY_ESC, T_Shade::List, MC_Black, MC_Dark, MC_Light, Menu_factor_X, Menu_factor_Y, T_Shade::Mode, Mouse_K, Mouse_X, Mouse_Y, Num2str(), Open_window(), Print_in_window(), Read_pixel, Readline(), Remove_shade(), RIGHT_SIDE, Set_fore_color(), Shade_current, Shade_draw_grad_ranges(), Shade_list, SPECIAL_SHADE_MENU, T_Shade::Step, Swap_shade(), Tag_color_range(), Tag_shades(), Update_rect(), Wait_click_in_shade_table(), Wait_end_of_click(), Window_attribute1, Window_attribute2, Window_clicked_button(), Window_display_frame(), Window_display_frame_in(), Window_help(), Window_input_content(), Window_pos_X, Window_pos_Y, Window_set_input_button(), Window_set_normal_button(), Window_set_palette_button(), Window_set_scroller_button(), Window_set_special_button(), and word.
Referenced by Shade_settings_menu().
int Shade_settings_menu (void)
Handles the screen with Shade settings.
Returns:
true if user clicked ok, false if he cancelled
References byte, Display_cursor(), Menu_shade(), Shade_current, Shade_list, Shade_list_to_lookup_tables(), Shade_table_left, and Shade_table_right.
Referenced by Button_Secondary_palette(), and Button_Shade_menu().
void Button_Shade_menu (void)
Callback for the Shade button (in the FX window) right click.
Displays the shade setup menu.
References Button_Shade_mode(), Shade_mode, and Shade_settings_menu().
Referenced by Button_Effects(), and Main_handler().
void Button_Quick_shade_menu (void)
References BUTTON_EFFECTS, BUTTON_HELP, Button_Quick_shade_mode(), byte, Close_window(), Display_cursor(), Display_shade_mode(), Hide_cursor, Is_shortcut(), Key, KEY_ESC, MC_Dark, MC_Light, Menu_factor_X, Menu_factor_Y, Num2str(), Open_window(), Print_in_window(), Quick_shade_loop, Quick_shade_mode, Quick_shade_step, Readline(), SPECIAL_QUICK_SHADE_MENU, Update_rect(), Window_clicked_button(), Window_help(), Window_input_content(), Window_pos_X, Window_pos_Y, Window_set_input_button(), and Window_set_normal_button().
Referenced by Button_Effects(), and Main_handler().