GrafX2: special.c File Reference
special.c File Reference
#include <stdlib.h>
#include <string.h>
#include "const.h"
#include "struct.h"
#include "global.h"
#include "graph.h"
#include "engine.h"
#include "windows.h"
#include "special.h"
#include "pages.h"
#include "misc.h"
#include "buttons.h"
Functions
int Circle_squared_diameter (int diameter)
void Set_paintbrush_size (int width, int height)
void Smaller_paintbrush (void)
void Bigger_paintbrush (void)
void Special_next_forecolor (void)
void Special_previous_forecolor (void)
void Special_next_backcolor (void)
void Special_previous_backcolor (void)
void Special_next_user_forecolor (void)
Picks the next foreground color, according to current shade table.
void Special_previous_user_forecolor (void)
Picks the previous foreground color, according to current shade table.
void Special_next_user_backcolor (void)
Picks the next background color, according to current shade table.
void Special_previous_user_backcolor (void)
Picks the previous background color, according to current shade table.
void Scroll_screen (short delta_x, short delta_y)
void Scroll_magnifier (short delta_x, short delta_y)
void Zoom (short delta)
void Zoom_set (int index)
Set zoom value.
void Transparency_set (byte amount)
Command that sets the transparency level.
void Layer_activate (short layer, short side)
void Special_add_layer ()
void Special_delete_layer ()
Function Documentation
int Circle_squared_diameter (int diameter)
Referenced by Set_paintbrush_size().
void Set_paintbrush_size (int width, int height)
References Circle_squared_diameter(), MAX_PAINTBRUSH_SIZE, Paintbrush_height, Paintbrush_offset_X, Paintbrush_offset_Y, Paintbrush_shape, PAINTBRUSH_SHAPE_ANTISLASH, PAINTBRUSH_SHAPE_CROSS, PAINTBRUSH_SHAPE_DIAMOND, PAINTBRUSH_SHAPE_HORIZONTAL_BAR, PAINTBRUSH_SHAPE_PLUS, PAINTBRUSH_SHAPE_RANDOM, PAINTBRUSH_SHAPE_ROUND, PAINTBRUSH_SHAPE_SIEVE_ROUND, PAINTBRUSH_SHAPE_SIEVE_SQUARE, PAINTBRUSH_SHAPE_SLASH, PAINTBRUSH_SHAPE_SQUARE, PAINTBRUSH_SHAPE_VERTICAL_BAR, Paintbrush_sprite, and Paintbrush_width.
Referenced by Bigger_paintbrush(), Main_handler(), Restore_brush(), and Smaller_paintbrush().
void Smaller_paintbrush (void)
References Display_cursor(), Display_paintbrush_in_menu(), Hide_cursor, Paintbrush_height, Paintbrush_shape, PAINTBRUSH_SHAPE_ANTISLASH, PAINTBRUSH_SHAPE_CROSS, PAINTBRUSH_SHAPE_DIAMOND, PAINTBRUSH_SHAPE_HORIZONTAL_BAR, PAINTBRUSH_SHAPE_MISC, PAINTBRUSH_SHAPE_PLUS, PAINTBRUSH_SHAPE_RANDOM, PAINTBRUSH_SHAPE_ROUND, PAINTBRUSH_SHAPE_SIEVE_ROUND, PAINTBRUSH_SHAPE_SIEVE_SQUARE, PAINTBRUSH_SHAPE_SLASH, PAINTBRUSH_SHAPE_SQUARE, PAINTBRUSH_SHAPE_VERTICAL_BAR, Paintbrush_width, and Set_paintbrush_size().
Referenced by Main_handler().
void Bigger_paintbrush (void)
References Display_cursor(), Display_paintbrush_in_menu(), Hide_cursor, MAX_PAINTBRUSH_SIZE, Paintbrush_height, Paintbrush_shape, PAINTBRUSH_SHAPE_ANTISLASH, PAINTBRUSH_SHAPE_CROSS, PAINTBRUSH_SHAPE_DIAMOND, PAINTBRUSH_SHAPE_HORIZONTAL_BAR, PAINTBRUSH_SHAPE_MISC, PAINTBRUSH_SHAPE_PLUS, PAINTBRUSH_SHAPE_RANDOM, PAINTBRUSH_SHAPE_ROUND, PAINTBRUSH_SHAPE_SIEVE_ROUND, PAINTBRUSH_SHAPE_SIEVE_SQUARE, PAINTBRUSH_SHAPE_SLASH, PAINTBRUSH_SHAPE_SQUARE, PAINTBRUSH_SHAPE_VERTICAL_BAR, Paintbrush_width, and Set_paintbrush_size().
Referenced by Main_handler().
void Special_next_forecolor (void)
References Display_cursor(), Fore_color, Hide_cursor, and Set_fore_color().
Referenced by Main_handler().
void Special_previous_forecolor (void)
References Display_cursor(), Fore_color, Hide_cursor, and Set_fore_color().
Referenced by Main_handler().
void Special_next_backcolor (void)
References Back_color, Display_cursor(), Hide_cursor, and Set_back_color().
Referenced by Main_handler().
void Special_previous_backcolor (void)
References Back_color, Display_cursor(), Hide_cursor, and Set_back_color().
Referenced by Main_handler().
void Special_next_user_forecolor (void)
Picks the next foreground color, according to current shade table.
References Display_cursor(), Fore_color, Hide_cursor, Set_fore_color(), and Shade_table_left.
Referenced by Main_handler().
void Special_previous_user_forecolor (void)
Picks the previous foreground color, according to current shade table.
References Display_cursor(), Fore_color, Hide_cursor, Set_fore_color(), and Shade_table_right.
Referenced by Main_handler().
void Special_next_user_backcolor (void)
Picks the next background color, according to current shade table.
References Back_color, Display_cursor(), Hide_cursor, Set_back_color(), and Shade_table_left.
Referenced by Main_handler().
void Special_previous_user_backcolor (void)
Picks the previous background color, according to current shade table.
References Back_color, Display_cursor(), Hide_cursor, Set_back_color(), and Shade_table_right.
Referenced by Main_handler().
void Scroll_screen (short delta_x, short delta_y)
References Compute_limits(), Compute_paintbrush_coordinates(), Display_all_screen(), Display_cursor(), Hide_cursor, Main_image_height, Main_image_width, Main_offset_X, Main_offset_Y, Menu_Y, and Screen_width.
Referenced by Main_handler().
void Scroll_magnifier (short delta_x, short delta_y)
References Compute_limits(), Compute_paintbrush_coordinates(), Display_all_screen(), Display_cursor(), Hide_cursor, Main_image_height, Main_image_width, Main_magnifier_height, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_magnifier_width, and Position_screen_according_to_zoom().
Referenced by Main_handler().
void Zoom (short delta)
References Change_magnifier_factor(), Display_all_screen(), Display_cursor(), Hide_cursor, Main_magnifier_factor, Main_magnifier_mode, NB_ZOOM_FACTORS, and ZOOM_FACTOR.
Referenced by Draw_preset_sieve_patterns(), and Main_handler().
void Zoom_set (int index)
Set zoom value.
Negative value means no zoom.
References BUTTON_MAGNIFIER, Change_magnifier_factor(), Display_all_screen(), Display_cursor(), Hide_cursor, Main_magnifier_mode, Select_button(), and Unselect_button().
Referenced by Main_handler().
void Transparency_set (byte amount)
Command that sets the transparency level.
References Colorize_current_mode, Colorize_mode, Colorize_opacity, Compute_colorize_table(), Config, T_Config::Double_key_speed, Effect_additive_colorize(), Effect_function, Effect_interpolated_colorize(), Effect_substractive_colorize(), Quick_shade_mode, Shade_mode, Smooth_mode, and Tiling_mode.
Referenced by Main_handler().
void Layer_activate (short layer, short side)
References Display_all_screen(), Display_cursor(), dword, Hide_cursor, LEFT_SIDE, Main_backups, Main_current_layer, Main_layers_visible, T_Page::Nb_layers, T_List_of_pages::Pages, Redraw_layered_image(), RIGHT_SIDE, Update_depth_buffer(), Update_screen_targets(), and word.
Referenced by Main_handler().
void Special_add_layer (void)
void Special_delete_layer (void)