GrafX2: special.h File Reference
special.h File Reference
Editor functions that can be hooked to a keyboard shortcut, but don't have a menu button associated to them.
Functions
void Set_paintbrush_size (int width, int height)
void Smaller_paintbrush (void)
void Bigger_paintbrush (void)
void Special_next_forecolor (void)
void Special_previous_forecolor (void)
void Special_next_backcolor (void)
void Special_previous_backcolor (void)
void Special_next_user_forecolor (void)
Picks the next foreground color, according to current shade table.
void Special_previous_user_forecolor (void)
Picks the previous foreground color, according to current shade table.
void Special_next_user_backcolor (void)
Picks the next background color, according to current shade table.
void Special_previous_user_backcolor (void)
Picks the previous background color, according to current shade table.
void Scroll_screen (short delta_x, short delta_y)
void Scroll_magnifier (short delta_x, short delta_y)
void Zoom (short delta)
void Zoom_set (int index)
Set zoom value.
void Display_stored_brush_in_window (word x, word y, int number)
void Store_brush (int index)
byte Restore_brush (int index)
Detailed Description
Editor functions that can be hooked to a keyboard shortcut, but don't have a menu button associated to them.
Function Documentation
void Set_paintbrush_size (int width, int height)
References Circle_squared_diameter(), MAX_PAINTBRUSH_SIZE, Paintbrush_height, Paintbrush_offset_X, Paintbrush_offset_Y, Paintbrush_shape, PAINTBRUSH_SHAPE_ANTISLASH, PAINTBRUSH_SHAPE_CROSS, PAINTBRUSH_SHAPE_DIAMOND, PAINTBRUSH_SHAPE_HORIZONTAL_BAR, PAINTBRUSH_SHAPE_PLUS, PAINTBRUSH_SHAPE_RANDOM, PAINTBRUSH_SHAPE_ROUND, PAINTBRUSH_SHAPE_SIEVE_ROUND, PAINTBRUSH_SHAPE_SIEVE_SQUARE, PAINTBRUSH_SHAPE_SLASH, PAINTBRUSH_SHAPE_SQUARE, PAINTBRUSH_SHAPE_VERTICAL_BAR, Paintbrush_sprite, and Paintbrush_width.
Referenced by Bigger_paintbrush(), Main_handler(), Restore_brush(), and Smaller_paintbrush().
void Smaller_paintbrush (void)
References Display_cursor(), Display_paintbrush_in_menu(), Hide_cursor, Paintbrush_height, Paintbrush_shape, PAINTBRUSH_SHAPE_ANTISLASH, PAINTBRUSH_SHAPE_CROSS, PAINTBRUSH_SHAPE_DIAMOND, PAINTBRUSH_SHAPE_HORIZONTAL_BAR, PAINTBRUSH_SHAPE_MISC, PAINTBRUSH_SHAPE_PLUS, PAINTBRUSH_SHAPE_RANDOM, PAINTBRUSH_SHAPE_ROUND, PAINTBRUSH_SHAPE_SIEVE_ROUND, PAINTBRUSH_SHAPE_SIEVE_SQUARE, PAINTBRUSH_SHAPE_SLASH, PAINTBRUSH_SHAPE_SQUARE, PAINTBRUSH_SHAPE_VERTICAL_BAR, Paintbrush_width, and Set_paintbrush_size().
Referenced by Main_handler().
void Bigger_paintbrush (void)
References Display_cursor(), Display_paintbrush_in_menu(), Hide_cursor, MAX_PAINTBRUSH_SIZE, Paintbrush_height, Paintbrush_shape, PAINTBRUSH_SHAPE_ANTISLASH, PAINTBRUSH_SHAPE_CROSS, PAINTBRUSH_SHAPE_DIAMOND, PAINTBRUSH_SHAPE_HORIZONTAL_BAR, PAINTBRUSH_SHAPE_MISC, PAINTBRUSH_SHAPE_PLUS, PAINTBRUSH_SHAPE_RANDOM, PAINTBRUSH_SHAPE_ROUND, PAINTBRUSH_SHAPE_SIEVE_ROUND, PAINTBRUSH_SHAPE_SIEVE_SQUARE, PAINTBRUSH_SHAPE_SLASH, PAINTBRUSH_SHAPE_SQUARE, PAINTBRUSH_SHAPE_VERTICAL_BAR, Paintbrush_width, and Set_paintbrush_size().
Referenced by Main_handler().
void Special_next_forecolor (void)
References Display_cursor(), Fore_color, Hide_cursor, and Set_fore_color().
Referenced by Main_handler().
void Special_previous_forecolor (void)
References Display_cursor(), Fore_color, Hide_cursor, and Set_fore_color().
Referenced by Main_handler().
void Special_next_backcolor (void)
References Back_color, Display_cursor(), Hide_cursor, and Set_back_color().
Referenced by Main_handler().
void Special_previous_backcolor (void)
References Back_color, Display_cursor(), Hide_cursor, and Set_back_color().
Referenced by Main_handler().
void Special_next_user_forecolor (void)
Picks the next foreground color, according to current shade table.
References Display_cursor(), Fore_color, Hide_cursor, Set_fore_color(), and Shade_table_left.
Referenced by Main_handler().
void Special_previous_user_forecolor (void)
Picks the previous foreground color, according to current shade table.
References Display_cursor(), Fore_color, Hide_cursor, Set_fore_color(), and Shade_table_right.
Referenced by Main_handler().
void Special_next_user_backcolor (void)
Picks the next background color, according to current shade table.
References Back_color, Display_cursor(), Hide_cursor, Set_back_color(), and Shade_table_left.
Referenced by Main_handler().
void Special_previous_user_backcolor (void)
Picks the previous background color, according to current shade table.
References Back_color, Display_cursor(), Hide_cursor, Set_back_color(), and Shade_table_right.
Referenced by Main_handler().
void Scroll_screen (short delta_x, short delta_y)
References Compute_limits(), Compute_paintbrush_coordinates(), Display_all_screen(), Display_cursor(), Hide_cursor, Main_image_height, Main_image_width, Main_offset_X, Main_offset_Y, Menu_Y, and Screen_width.
Referenced by Main_handler().
void Scroll_magnifier (short delta_x, short delta_y)
References Compute_limits(), Compute_paintbrush_coordinates(), Display_all_screen(), Display_cursor(), Hide_cursor, Main_image_height, Main_image_width, Main_magnifier_height, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_magnifier_width, and Position_screen_according_to_zoom().
Referenced by Main_handler().
void Zoom (short delta)
References Change_magnifier_factor(), Display_all_screen(), Display_cursor(), Hide_cursor, Main_magnifier_factor, Main_magnifier_mode, NB_ZOOM_FACTORS, and ZOOM_FACTOR.
Referenced by Draw_preset_sieve_patterns(), and Main_handler().
void Zoom_set (int index)
Set zoom value.
Negative value means no zoom.
References BUTTON_MAGNIFIER, Change_magnifier_factor(), Display_all_screen(), Display_cursor(), Hide_cursor, Main_magnifier_mode, Select_button(), and Unselect_button().
Referenced by Main_handler().
void Display_stored_brush_in_window (word x, word y, int number)
References Brush_container, BRUSH_CONTAINER_PREVIEW_HEIGHT, BRUSH_CONTAINER_PREVIEW_WIDTH, byte, T_Brush_template::Height, Height, MC_Black, MC_Light, Paintbrush_shape, PAINTBRUSH_SHAPE_MAX, PAINTBRUSH_SHAPE_MISC, Pixel_in_window(), T_Brush_template::Thumbnail, Update_window_area, T_Brush_template::Width, Width, and Window_rectangle().
Referenced by Button_Brush_container(), and Button_Paintbrush_menu().
void Store_brush (int index)
References T_Brush_template::Brush, Brush, Brush_container, BRUSH_CONTAINER_PREVIEW_HEIGHT, BRUSH_CONTAINER_PREVIEW_WIDTH, Brush_height, Brush_width, byte, Copy_part_of_image_to_another(), Error, T_Brush_template::Height, MAX_PAINTBRUSH_SIZE, Paintbrush_height, T_Brush_template::Paintbrush_shape, Paintbrush_shape, PAINTBRUSH_SHAPE_COLOR_BRUSH, PAINTBRUSH_SHAPE_MAX, PAINTBRUSH_SHAPE_MISC, PAINTBRUSH_SHAPE_MONO_BRUSH, Paintbrush_sprite, Paintbrush_width, Rescale(), T_Brush_template::Transp_color, and T_Brush_template::Width.
Referenced by Button_Brush_container(), and Button_Paintbrush_menu().
byte Restore_brush (int index)
References Brush, Brush_container, BRUSH_CONTAINER_PREVIEW_HEIGHT, BRUSH_CONTAINER_PREVIEW_WIDTH, Brush_height, Brush_offset_X, Brush_offset_Y, Brush_width, byte, Change_paintbrush_shape(), Height, T_Brush_template::Height, MAX_PAINTBRUSH_SIZE, Paintbrush_height, Paintbrush_offset_X, Paintbrush_offset_Y, Paintbrush_shape, T_Brush_template::Paintbrush_shape, PAINTBRUSH_SHAPE_COLOR_BRUSH, PAINTBRUSH_SHAPE_HORIZONTAL_BAR, PAINTBRUSH_SHAPE_MAX, PAINTBRUSH_SHAPE_MISC, PAINTBRUSH_SHAPE_MONO_BRUSH, PAINTBRUSH_SHAPE_VERTICAL_BAR, Paintbrush_sprite, Paintbrush_width, Realloc_brush(), Set_paintbrush_size(), T_Brush_template::Thumbnail, Width, T_Brush_template::Width, and word.
Referenced by Button_Brush_container(), and Button_Paintbrush_menu().