GrafX2: text.c File Reference
text.c File Reference
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <SDL_ttf.h>
#include <SDL_image.h>
#include "SFont.h"
#include "struct.h"
#include "global.h"
#include "sdlscreen.h"
#include "io.h"
#include "errors.h"
Data Structures
struct T_Font
Defines
#define EXTID(a, b, c) ((((a)&255)<<16) | (((b)&255)<<8) | (((c)&255)))
#define EXTID4(a, b, c, d) ((((a)&255)<<24) | (((b)&255)<<16) | (((c)&255)<<8) | (((d)&255)))
Functions
int Compare_fonts (T_Font *font_1, T_Font *font_2)
void Add_font (const char *name)
Add a new font to the list to propose to the user.
char * Font_name (int index)
Finds the filename of a font declared with Add_font().
char * Font_label (int index)
Finds a label to display for a font declared with Add_font().
int TrueType_font (int index)
Returns true if the font of this number is TrueType, false if it's a SFont bitmap.
void Init_text (void)
Initialization of text settings, needs to be called once on program startup.
int TrueType_is_supported ()
Returns true if text.c was compiled with TrueType support.
byte * Render_text_TTF (const char *str, int font_number, int size, int antialias, int bold, int italic, int *width, int *height)
byte * Render_text_SFont (const char *str, int font_number, int *width, int *height)
byte * Render_text (const char *str, int font_number, int size, int antialias, int bold, int italic, int *width, int *height)
Creates a brush, from the parameters given:.
Variables
T_Font * font_list_start
int Nb_fonts
Number of fonts declared with a series of Add_font().
Define Documentation
#define EXTID (a, b, c) ((((a)&255)<<16) | (((b)&255)<<8) | (((c)&255)))
Referenced by Add_font().
#define EXTID4 (a, b, c, d) ((((a)&255)<<24) | (((b)&255)<<16) | (((c)&255)<<8) | (((d)&255)))
Function Documentation
int Compare_fonts (T_Font * font_1, T_Font * font_2)
References T_Font::Is_bitmap, and T_Font::Label.
Referenced by Add_font().
void Add_font (const char * name)
Add a new font to the list to propose to the user.
References Compare_fonts(), EXTID, Find_last_slash(), T_Font::Is_bitmap, T_Font::Is_truetype, T_Font::Label, T_Font::Name, Nb_fonts, T_Font::Next, and T_Font::Previous.
Referenced by Init_text().
char* Font_name (int index)
Finds the filename of a font declared with Add_font().
References T_Font::Name, Nb_fonts, and T_Font::Next.
Referenced by Render_text_SFont(), and Render_text_TTF().
char* Font_label (int index)
Finds a label to display for a font declared with Add_font().
References T_Font::Label, Nb_fonts, and T_Font::Next.
Referenced by Draw_font_selector().
int TrueType_font (int index)
Returns true if the font of this number is TrueType, false if it's a SFont bitmap.
References T_Font::Is_truetype, Nb_fonts, and T_Font::Next.
Referenced by Button_Text().
void Init_text (void)
Initialization of text settings, needs to be called once on program startup.
References Add_font(), For_each_file(), MAX_PATH_CHARACTERS, Nb_fonts, and Repertoire_des_donnees.
Referenced by Init_program().
int TrueType_is_supported (void)
Returns true if text.c was compiled with TrueType support.
Referenced by Button_Stats().
byte* Render_text_TTF (const char * str, int font_number, int size, int antialias, int bold, int italic, int * width, int * height)
References Back_color, byte, Color_to_SDL_color(), Font_name(), Fore_color, MC_Black, MC_White, and Surface_to_bytefield().
Referenced by Render_text().
byte* Render_text_SFont (const char * str, int font_number, int * width, int * height)
References byte, DEBUG, Font_name(), SFont_FreeFont(), SFont_InitFont(), SFont_TextHeight(), SFont_TextWidth(), SFont_Write(), and Surface_to_bytefield().
Referenced by Render_text().
byte* Render_text (const char * str, int font_number, int size, int antialias, int bold, int italic, int * width, int * height)
Creates a brush, from the parameters given:.
Parameters:
str The text to render
font_number The index of the font to use. Pass 0 for the first font you declared with Add_font(), 1 for the second etc.
size The size in points (unused for bitmap fonts)
antialias Boolean, true to use antialiasing in TrueType
bold Boolean, true to use bold rendering in TrueType
italic Boolean, true to use italic rendering in TrueType
width Returns the width of the created brush, in pixels.
height Returns the height of the created brush, in pixels. Returns true on success.
References T_Font::Is_truetype, Nb_fonts, T_Font::Next, Render_text_SFont(), and Render_text_TTF().
Referenced by Button_Text().
Variable Documentation
T_Font* font_list_start
int Nb_fonts
Number of fonts declared with a series of Add_font().
This is public for convenience, but functionaly it is read-only.
Referenced by Add_font(), Button_Text(), Font_label(), Font_name(), Init_text(), Render_text(), and TrueType_font().