GrafX2: texte.c File Reference
texte.c File Reference
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <SDL_ttf.h>
#include <SDL_image.h>
#include "SFont.h"
#include "struct.h"
#include "global.h"
#include "sdlscreen.h"
#include "io.h"
Data Structures
struct T_Font
Defines
#define EXTID(a, b, c) ((((a)&255)<<16) | (((b)&255)<<8) | (((c)&255)))
#define EXTID4(a, b, c, d) ((((a)&255)<<24) | (((b)&255)<<16) | (((c)&255)<<8) | (((d)&255)))
Functions
int Compare_fonts (T_Font *font_1, T_Font *font_2)
void Add_font (const char *name)
char * Font_name (int index)
char * Font_label (int index)
int TrueType_font (int index)
void Init_text (void)
int TrueType_is_supported ()
byte * Render_text_TTF (const char *str, int font_number, int size, int antialias, int bold, int italic, int *width, int *height)
byte * Render_text_SFont (const char *str, int font_number, int *width, int *height)
byte * Render_text (const char *str, int font_number, int size, int antialias, int bold, int italic, int *width, int *height)
Variables
T_Font * font_list_start
int Nb_fonts
Define Documentation
#define EXTID (a, b, c) ((((a)&255)<<16) | (((b)&255)<<8) | (((c)&255)))
Referenced by Add_font().
#define EXTID4 (a, b, c, d) ((((a)&255)<<24) | (((b)&255)<<16) | (((c)&255)<<8) | (((d)&255)))
Function Documentation
int Compare_fonts (T_Font * font_1, T_Font * font_2)
References T_Font::Is_bitmap, and T_Font::Label.
Referenced by Add_font().
void Add_font (const char * name)
References Compare_fonts(), EXTID, Find_last_slash(), T_Font::Is_bitmap, T_Font::Is_truetype, T_Font::Label, T_Font::Name, Nb_fonts, T_Font::Next, and T_Font::Previous.
Referenced by Init_text().
char* Font_name (int index)
References T_Font::Name, Nb_fonts, and T_Font::Next.
Referenced by Render_text_SFont(), and Render_text_TTF().
char* Font_label (int index)
References T_Font::Label, Nb_fonts, and T_Font::Next.
Referenced by Draw_font_selector().
int TrueType_font (int index)
References T_Font::Is_truetype, Nb_fonts, and T_Font::Next.
Referenced by Button_Text().
void Init_text (void)
References Add_font(), For_each_file(), MAX_PATH_CHARACTERS, Nb_fonts, and Repertoire_des_donnees.
Referenced by Init_program().
int TrueType_is_supported (void)
Referenced by Button_Stats().
byte* Render_text_TTF (const char * str, int font_number, int size, int antialias, int bold, int italic, int * width, int * height)
References Back_color, byte, Color_to_SDL_color(), Font_name(), Fore_color, MC_Black, MC_White, and Surface_to_bytefield().
Referenced by Render_text().
byte* Render_text_SFont (const char * str, int font_number, int * width, int * height)
References byte, Font_name(), SFont_FreeFont(), SFont_InitFont(), SFont_TextHeight(), SFont_TextWidth(), SFont_Write(), and Surface_to_bytefield().
Referenced by Render_text().
byte* Render_text (const char * str, int font_number, int size, int antialias, int bold, int italic, int * width, int * height)
References T_Font::Is_truetype, Nb_fonts, T_Font::Next, Render_text_SFont(), and Render_text_TTF().
Referenced by Button_Text().
Variable Documentation
T_Font* font_list_start
int Nb_fonts
Referenced by Add_font(), Button_Text(), Font_label(), Font_name(), Init_text(), Render_text(), and TrueType_font().