GrafX2: text.h File Reference
text.h File Reference
Functions related to rendering text as a brush, using TrueType or SFont.
Functions
void Init_text (void)
Initialization of text settings, needs to be called once on program startup.
int TrueType_is_supported (void)
Returns true if text.c was compiled with TrueType support.
void Add_font (const char *name)
Add a new font to the list to propose to the user.
byte * Render_text (const char *str, int font_number, int size, int antialias, int bold, int italic, int *width, int *height)
Creates a brush, from the parameters given:.
char * Font_label (int index)
Finds a label to display for a font declared with Add_font().
char * Font_name (int index)
Finds the filename of a font declared with Add_font().
char * TrueType_font (int index)
Returns true if the font of this number is TrueType, false if it's a SFont bitmap.
Variables
int Nb_fonts
Number of fonts declared with a series of Add_font().
Detailed Description
Functions related to rendering text as a brush, using TrueType or SFont.
Function Documentation
void Init_text (void)
Initialization of text settings, needs to be called once on program startup.
References Add_font(), Data_directory, For_each_file(), MAX_PATH_CHARACTERS, and Nb_fonts.
Referenced by Init_program().
int TrueType_is_supported (void)
Returns true if text.c was compiled with TrueType support.
Referenced by Button_Stats().
void Add_font (const char * name)
Add a new font to the list to propose to the user.
References Compare_fonts(), EXTID, Find_last_slash(), T_Font::Is_bitmap, T_Font::Is_truetype, T_Font::Label, T_Font::Name, Nb_fonts, T_Font::Next, and T_Font::Previous.
Referenced by Init_text().
byte* Render_text (const char * str, int font_number, int size, int antialias, int bold, int italic, int * width, int * height)
Creates a brush, from the parameters given:.
Parameters:
str The text to render
font_number The index of the font to use. Pass 0 for the first font you declared with Add_font(), 1 for the second etc.
size The size in points (unused for bitmap fonts)
antialias Boolean, true to use antialiasing in TrueType
bold Boolean, true to use bold rendering in TrueType
italic Boolean, true to use italic rendering in TrueType
width Returns the width of the created brush, in pixels.
height Returns the height of the created brush, in pixels. Returns true on success.
References T_Font::Is_truetype, Nb_fonts, T_Font::Next, Render_text_SFont(), and Render_text_TTF().
Referenced by Button_Text().
char* Font_label (int index)
Finds a label to display for a font declared with Add_font().
References T_Font::Label, Nb_fonts, and T_Font::Next.
Referenced by Draw_one_font_name().
char* Font_name (int index)
Finds the filename of a font declared with Add_font().
References T_Font::Name, Nb_fonts, and T_Font::Next.
Referenced by Render_text_SFont(), and Render_text_TTF().
char* TrueType_font (int index)
Returns true if the font of this number is TrueType, false if it's a SFont bitmap.
References T_Font::Is_truetype, Nb_fonts, and T_Font::Next.
Referenced by Button_Text().
Variable Documentation
int Nb_fonts
Number of fonts declared with a series of Add_font().
This is public for convenience, but functionaly it is read-only.
Referenced by Add_font(), Button_Text(), Font_label(), Font_name(), Init_text(), Render_text(), and TrueType_font().