GrafX2: transform.h File Reference
transform.h File Reference
Screen and functions for picture transform.
Functions
void Button_Transform_menu (void)
Opens and handles the Picture transform screen.
Detailed Description
Screen and functions for picture transform.
Function Documentation
void Button_Transform_menu (void)
Opens and handles the Picture transform screen.
References Backup_with_new_dimensions(), BUTTON_ADJUST, BUTTON_HELP, byte, Close_window(), Compute_dimension(), Current_operation, Display_all_screen(), Display_cursor(), End_of_modification(), Factorize(), Flip_X_lowlevel(), Flip_Y_lowlevel(), Hide_cursor, T_Page::Image, INPUT_TYPE_INTEGER, Is_shortcut(), Key, KEY_ESC, LEFT_SIDE, Main_backups, Main_image_height, Main_image_is_modified, Main_image_width, MC_Black, MC_Dark, MC_Light, Message_out_of_memory(), T_Page::Nb_layers, T_Page::Next, Num2str, Open_window(), OPERATION_SCROLL, T_List_of_pages::Pages, Print_in_window(), Print_in_window_limited(), Readline(), Redraw_layered_image(), Rescale(), RIGHT_SIDE, Rotate_180_deg_lowlevel(), Rotate_270_deg_lowlevel(), Rotate_90_deg_lowlevel(), Unselect_button(), Update_window_area, Upload_infos_page_main(), Width, Window_attribute2, Window_clicked_button(), Window_display_frame(), Window_dropdown_add_item(), Window_height, Window_help(), Window_set_dropdown_button(), Window_set_input_button(), Window_set_normal_button(), and Window_width.
Referenced by Init_buttons().