GrafX2: windows.h File Reference
windows.h File Reference
Graphical interface management functions (windows, menu, cursor).
#include "struct.h"
Defines
#define ToWinX(x) (((x)*Menu_factor_X)+Window_pos_X)
#define ToWinY(y) (((y)*Menu_factor_Y)+Window_pos_Y)
#define ToWinL(l) ((l)*Menu_factor_X)
#define ToWinH(h) ((h)*Menu_factor_Y)
#define Update_window_area(x, y, w, h) Update_rect(Window_pos_X+(x)*Menu_factor_X,Window_pos_Y+(y)*Menu_factor_Y,(w)*Menu_factor_X,(h)*Menu_factor_Y);
Functions
void Display_cursor (void)
void Hide_cursor (void)
void Remap_screen_after_menu_colors_change (void)
void Compute_optimal_menu_colors (T_Components *palette)
void Position_screen_according_to_zoom (void)
void Compute_separator_data (void)
void Compute_magnifier_data (void)
void Compute_limits (void)
void Compute_paintbrush_coordinates (void)
void Pixel_in_toolbar (word x, word y, byte color)
void Pixel_in_window (word x, word y, byte color)
void Set_fore_color (byte color)
void Set_back_color (byte color)
void Frame_menu_color (byte id)
Redraw the cell in the menu palette for Fore_color.
void Display_menu_palette (void)
void Display_menu (void)
Display the whole menu.
void Reposition_palette (void)
void Change_palette_cells (void)
int Pick_color_in_palette (void)
word Palette_cells_X (void)
word Palette_cells_Y (void)
void Print_general (short x, short y, const char *str, byte text_color, byte background_color)
void Print_in_window (short x, short y, const char *str, byte text_color, byte background_color)
Draws a string in a window.
void Print_in_window_limited (short x, short y, const char *str, byte size, byte text_color, byte background_color)
Draws a char in a window, checking for bounds.
void Print_char_in_window (short x_pos, short y_pos, const unsigned char c, byte text_color, byte background_color)
Draws a char in a window.
void Print_in_menu (const char *str, short position)
void Print_coordinates (void)
Draws the mouse coordinates on the menu Only update the digits and doesn't refresh the "X: Y:" labels.
void Print_filename (void)
void Print_counter (short x, short y, const char *str, byte text_color, byte background_color)
byte Confirmation_box (char *message)
void Warning_message (char *message)
Window that show a warning message and wait for a click on the OK button.
void Verbose_error_message (const char *message)
Window that shows a big message, and waits for a click on OK.
int Requester_window (char *message, int initial_value)
Window that allows you to enter a single value.
void Display_image_limits (void)
void Display_all_screen (void)
void Window_rectangle (word x_pos, word y_pos, word width, word height, byte color)
void Window_display_frame_generic (word x_pos, word y_pos, word width, word height, byte color_tl, byte color_br, byte color_s, byte color_tlc, byte color_brc)
void Window_display_frame_mono (word x_pos, word y_pos, word width, word height, byte color)
void Window_display_frame_in (word x_pos, word y_pos, word width, word height)
void Window_display_frame_out (word x_pos, word y_pos, word width, word height)
void Window_display_frame (word x_pos, word y_pos, word width, word height)
void Display_sprite_in_menu (int btn_number, int sprite_number)
void Display_paintbrush_in_menu (void)
void Display_paintbrush_in_window (word x, word y, int number)
void Draw_thingumajig (word x, word y, byte color, short direction)
void Display_grad_block_in_window (word x_pos, word y_pos, word block_start, word block_end)
void Window_display_icon_sprite (word x_pos, word y_pos, byte type)
byte Best_color (byte red, byte green, byte blue)
byte Best_color_nonexcluded (byte red, byte green, byte blue)
void Horizontal_XOR_line_zoom (short x_pos, short y_pos, short width)
void Vertical_XOR_line_zoom (short x_pos, short y_pos, short height)
void Change_magnifier_factor (byte factor_index)
Detailed Description
Graphical interface management functions (windows, menu, cursor).
Define Documentation
#define ToWinX (x) (((x)*Menu_factor_X)+Window_pos_X)
Referenced by Display_effect_sprite(), Display_grad_block_in_window(), Display_paintbrush_in_window(), Draw_preset_sieve_patterns(), Tag_color_range(), and Window_display_icon_sprite().
#define ToWinY (y) (((y)*Menu_factor_Y)+Window_pos_Y)
Referenced by Display_effect_sprite(), Display_grad_block_in_window(), Display_paintbrush_in_window(), Draw_preset_sieve_patterns(), Tag_color_range(), and Window_display_icon_sprite().
#define ToWinL (l) ((l)*Menu_factor_X)
Referenced by Display_grad_block_in_window(), Display_paintbrush_in_window(), Draw_preset_sieve_patterns(), Tag_color_range(), Window_clear_tags(), and Window_display_icon_sprite().
#define ToWinH (h) ((h)*Menu_factor_Y)
Referenced by Display_grad_block_in_window(), Display_paintbrush_in_window(), Draw_preset_sieve_patterns(), Tag_color_range(), Window_clear_tags(), and Window_display_icon_sprite().
#define Update_window_area (x, y, w, h) Update_rect(Window_pos_X+(x)*Menu_factor_X,Window_pos_Y+(y)*Menu_factor_Y,(w)*Menu_factor_X,(h)*Menu_factor_Y);
Referenced by Button_Airbrush_menu(), Button_Brush_container(), Button_Brush_FX(), Button_Colorize_menu(), Button_Copy_page(), Button_Effects(), Button_Gradients(), Button_Grid_menu(), Button_Load_or_Save(), Button_Magnify_menu(), Button_Message_initial(), Button_Paintbrush_menu(), Button_Palette(), Button_Quit_local_function(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Skins(), Button_Smooth_menu(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Display_stored_brush_in_window(), Draw_palette_preview(), Init_preview(), Menu_tag_colors(), Message_out_of_memory(), Prepare_and_display_filelist(), Print_current_directory(), Print_filename_in_fileselector(), Save_C64_window(), and Verbose_error_message().
Function Documentation
void Display_cursor (void)
References Brush_height, Brush_rotation_center_is_defined, Brush_rotation_center_X, Brush_rotation_center_Y, Brush_width, byte, Config, T_Config::Cursor, Cursor_background, Cursor_hidden, T_Gui_skin::Cursor_offset_X, T_Gui_skin::Cursor_offset_Y, Cursor_shape, CURSOR_SHAPE_ARROW, CURSOR_SHAPE_COLORPICKER, CURSOR_SHAPE_HORIZONTAL, CURSOR_SHAPE_HOURGLASS, CURSOR_SHAPE_MULTIDIRECTIONAL, CURSOR_SHAPE_TARGET, CURSOR_SHAPE_THIN_COLORPICKER, CURSOR_SHAPE_THIN_TARGET, CURSOR_SHAPE_XOR_RECTANGLE, CURSOR_SHAPE_XOR_TARGET, T_Gui_skin::Cursor_sprite, Display_paintbrush(), Draw_line_preview_xor(), Fore_color, Gfx, Horizontal_XOR_line, Horizontal_XOR_line_zoom(), Limit_bottom, Limit_left, Limit_left_zoom, Limit_right, Limit_top, Limit_top_zoom, Limit_visible_bottom_zoom, Limit_visible_right_zoom, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_width, Main_offset_X, Main_offset_Y, Main_separator_position, Main_X_zoom, Max(), MC_Trans, Menu_Y, Mouse_X, Mouse_Y, Paintbrush_hidden, Paintbrush_X, Paintbrush_Y, Pixel, Pixel_figure_preview_xor(), Read_pixel, Screen_height, Screen_width, Transform_point(), Update_rect(), Vertical_XOR_line, Vertical_XOR_line_zoom(), and Windows_open.
Referenced by Airbrush(), Airbrush_12_2(), Bigger_paintbrush(), Brush_12_0(), Button_Adjust(), Button_Airbrush(), Button_Airbrush_menu(), Button_Autosave(), Button_Brush(), Button_Brush_container(), Button_Brush_FX(), Button_Brush_monochrome(), Button_Clear(), Button_Clear_with_backcolor(), Button_Colorize_menu(), Button_Colorpicker(), Button_Copy_page(), Button_Curves(), Button_Curves_switch_mode(), Button_Draw(), Button_Draw_switch_mode(), Button_Effects(), Button_Empty_circle(), Button_Empty_ellipse(), Button_Empty_rectangle(), Button_Fill(), Button_Filled_circle(), Button_Filled_ellipse(), Button_Filled_polyform(), Button_Filled_rectangle(), Button_Grad_circle(), Button_Grad_ellipse(), Button_Grad_rectangle(), Button_Gradients(), Button_Grid_menu(), Button_Hide_menu(), Button_Invert_foreback(), Button_Kill(), Button_Lasso(), Button_Lines(), Button_Lines_switch_mode(), Button_Load_or_Save(), Button_Magnify(), Button_Magnify_menu(), Button_Message_initial(), Button_Page(), Button_Paintbrush_menu(), Button_Pal_left(), Button_Pal_left_fast(), Button_Pal_right(), Button_Pal_right_fast(), Button_Palette(), Button_Polyfill(), Button_Polyform(), Button_polygon(), Button_Quick_shade_menu(), Button_Quit(), Button_Quit_local_function(), Button_Redo(), Button_Reload(), Button_Replace(), Button_Resolution(), Button_Restore_brush(), Button_Safety_resolution(), Button_Secondary_palette(), Button_Select_backcolor(), Button_Select_forecolor(), Button_Settings(), Button_Show_grid(), Button_Sieve_menu(), Button_Skins(), Button_Smooth_menu(), Button_Snap_mode(), Button_Stats(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Button_Undo(), Centered_lines_0_7(), Centered_lines_12_7(), Circle_12_5(), Colorpicker_1_1(), Colorpicker_2_1(), Confirmation_box(), Curve_34_points_1_5(), Curve_34_points_2_5(), Curve_3_points_0_11(), Curve_3_points_12_11(), Curve_4_points_1_9(), Curve_4_points_2_9(), Distort_brush_1_0(), Distort_brush_1_9(), Draw_all_palette_sliders(), Ellipse_12_5(), Fill_1_0(), Fill_2_0(), Fill_general(), Filled_contour_0_8(), Filled_polyform_0_8(), Filled_polyform_12_8(), Freehand_mode1_1_2(), Freehand_mode1_2_2(), Freehand_mode2_1_2(), Freehand_mode2_2_2(), Get_color_behind_window(), Get_colors_from_brush(), Get_input(), Grad_circle_12_6(), Grad_circle_12_8(), Grad_ellipse_12_6(), Grad_ellipse_12_8(), Grad_rectangle_0_9(), Grad_rectangle_12_0(), Init_program(), K_line_12_6(), K_line_12_7(), Line_12_5(), Load_image(), Load_picture(), Magnifier_12_0(), Main_handler(), Menu_shade(), Menu_tag_colors(), Message_out_of_memory(), Move_separator(), Move_window(), Polybrush_12_8(), Polyfill_12_8(), Polyfill_12_9(), Polyform_0_8(), Polyform_12_8(), Polygon_12_9(), Readline_ex(), Rectangle_12_0(), Redefine_control(), Reduce_palette(), Replace_1_0(), Replace_2_0(), Requester_window(), Resize_image(), Return_to_draw_mode(), Rotate_brush_0_5(), Rotate_brush_1_5(), Save_C64_window(), Save_picture(), Scroll_fileselector(), Scroll_help(), Scroll_list_of_modes(), Scroll_magnifier(), Scroll_screen(), Select_button(), Set_nice_menu_colors(), Settings_display_config(), Shade_settings_menu(), Smaller_paintbrush(), Special_next_backcolor(), Special_next_forecolor(), Special_next_user_backcolor(), Special_next_user_forecolor(), Special_previous_backcolor(), Special_previous_forecolor(), Special_previous_user_backcolor(), Special_previous_user_forecolor(), Stretch_brush_0_7(), Stretch_brush_12_0(), Stretch_brush_1_7(), Update_color_count(), Verbose_error_message(), Wait_click_in_palette(), Wait_click_in_shade_table(), Warning_message(), Window_clicked_button(), Window_dropdown_on_click(), Window_get_button_shortcut(), Window_get_clicked_button(), Window_help(), Window_normal_button_onclick(), Window_set_shortcut(), Zoom(), and Zoom_set().
void Hide_cursor (void)
References Brush_height, Brush_rotation_center_is_defined, Brush_rotation_center_X, Brush_rotation_center_Y, Brush_width, byte, Config, T_Config::Cursor, Cursor_background, Cursor_hidden, T_Gui_skin::Cursor_offset_X, T_Gui_skin::Cursor_offset_Y, Cursor_shape, CURSOR_SHAPE_ARROW, CURSOR_SHAPE_COLORPICKER, CURSOR_SHAPE_HORIZONTAL, CURSOR_SHAPE_HOURGLASS, CURSOR_SHAPE_MULTIDIRECTIONAL, CURSOR_SHAPE_TARGET, CURSOR_SHAPE_THIN_COLORPICKER, CURSOR_SHAPE_THIN_TARGET, CURSOR_SHAPE_XOR_RECTANGLE, CURSOR_SHAPE_XOR_TARGET, Draw_line_preview_xor(), Gfx, Hide_paintbrush(), Horizontal_XOR_line, Horizontal_XOR_line_zoom(), Limit_bottom, Limit_left, Limit_left_zoom, Limit_right, Limit_top, Limit_top_zoom, Limit_visible_bottom_zoom, Limit_visible_right_zoom, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_width, Main_offset_X, Main_offset_Y, Main_separator_position, Main_X_zoom, Max(), Menu_Y, Mouse_X, Mouse_Y, Paintbrush_hidden, Paintbrush_X, Paintbrush_Y, Pixel, Pixel_figure_preview_xor(), Screen_height, Screen_width, Transform_point(), Update_rect(), Vertical_XOR_line, Vertical_XOR_line_zoom(), and Windows_open.
void Remap_screen_after_menu_colors_change (void)
References byte, Clear_border(), Display_menu_palette_avoiding_window(), MC_Black, MC_Dark, MC_Light, MC_Trans, MC_White, Menu_factor_X, Menu_factor_Y, Menu_is_visible_before_window, Menu_Y_before_window, Remap_screen, Remap_window_backgrounds(), Screen_height, Screen_width, Window_height, Window_pos_X, Window_pos_Y, and Window_width.
Referenced by Button_Palette(), and Remap_fileselector().
void Compute_optimal_menu_colors (T_Components * palette)
References T_Gui_skin::Bold_font, byte, Clear_border(), Compute_4_best_colors_for_1_menu_color(), T_Gui_skin::Cursor_sprite, CURSOR_SPRITE_HEIGHT, CURSOR_SPRITE_WIDTH, T_Gui_skin::Effect_sprite, Fav_menu_colors, Gfx, T_Gui_skin::Help_font_norm, T_Gui_skin::Help_font_t1, T_Gui_skin::Help_font_t2, T_Gui_skin::Help_font_t3, T_Gui_skin::Help_font_t4, T_Gui_skin::Icon_sprite, ICON_SPRITE_HEIGHT, ICON_SPRITE_WIDTH, MC_Black, MC_Dark, MC_Light, MC_Trans, MC_White, T_Gui_skin::Menu_block, MENU_HEIGHT, T_Gui_skin::Menu_sprite, MENU_SPRITE_HEIGHT, MENU_SPRITE_WIDTH, MENU_WIDTH, NB_CURSOR_SPRITES, NB_EFFECTS_SPRITES, NB_ICON_SPRITES, NB_MENU_SPRITES, and Remap_pixel().
Referenced by Button_Kill(), Button_Load_or_Save(), Button_Page(), Button_Palette(), Button_Redo(), Button_Reload(), Button_Settings(), Button_Undo(), Get_colors_from_brush(), Init_preview(), Init_preview_24b(), Init_program(), Load_picture(), and Remap_fileselector().
void Position_screen_according_to_zoom (void)
References Main_image_height, Main_image_width, Main_magnifier_height, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_magnifier_width, Main_offset_X, Main_offset_Y, Main_separator_position, and Menu_Y.
Referenced by Button_Hide_menu(), Button_Magnify(), Change_magnifier_factor(), Init_mode_video(), Magnifier_12_0(), Move_separator(), and Scroll_magnifier().
void Compute_separator_data (void)
References Main_magnifier_factor, Main_separator_position, Main_separator_proportion, Main_X_zoom, Menu_factor_X, NB_ZOOMED_PIXELS_MIN, Round(), Screen_width, and SEPARATOR_WIDTH.
Referenced by Compute_magnifier_data(), and Move_separator().
void Compute_magnifier_data (void)
References Compute_separator_data(), Main_image_height, Main_image_width, Main_magnifier_factor, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_magnifier_width, Main_X_zoom, Menu_Y, and Screen_width.
Referenced by Button_Hide_menu(), Button_Magnify(), Change_magnifier_factor(), Init_mode_video(), Init_program(), and Move_separator().
void Compute_limits (void)
References Limit_bottom, Limit_bottom_zoom, Limit_left, Limit_left_zoom, Limit_right, Limit_right_zoom, Limit_top, Limit_top_zoom, Limit_visible_bottom, Limit_visible_bottom_zoom, Limit_visible_right, Limit_visible_right_zoom, Main_image_height, Main_image_width, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_magnifier_width, Main_offset_X, Main_offset_Y, Main_separator_position, Menu_is_visible, Menu_Y, Screen_height, and Screen_width.
Referenced by Button_Hide_menu(), Button_Magnify(), Button_Reload(), Button_Unselect_magnifier(), Change_magnifier_factor(), Download_infos_page_main(), Init_mode_video(), Init_program(), Load_picture(), Magnifier_12_0(), Move_separator(), Scroll_magnifier(), and Scroll_screen().
void Compute_paintbrush_coordinates (void)
References Current_operation, Main_magnifier_factor, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_offset_X, Main_offset_Y, Main_X_zoom, Mouse_X, Mouse_Y, OPERATION_LINE, Paintbrush_X, Paintbrush_Y, Snap_axis, Snap_axis_origin_X, Snap_axis_origin_Y, Snap_height, Snap_mode, Snap_offset_X, Snap_offset_Y, and Snap_width.
Referenced by Button_Hide_menu(), Button_Magnify(), Button_Reload(), Button_Snap_mode(), Button_Unselect_magnifier(), Change_magnifier_factor(), Close_popup(), Close_window(), Download_infos_page_main(), Get_input(), Init_mode_video(), Init_program(), Load_picture(), Magnifier_12_0(), Scroll_magnifier(), and Scroll_screen().
void Pixel_in_toolbar (word x, word y, byte color)
References Block, Menu_factor_X, Menu_factor_Y, and Menu_Y.
Referenced by Button_Hide_menu(), and Init_program().
void Pixel_in_window (word x, word y, byte color)
References Block, Menu_factor_X, Menu_factor_Y, Window_pos_X, and Window_pos_Y.
Referenced by Button_Brush_FX(), Button_Message_initial(), Button_Skins(), Display_effect_sprite(), Display_stored_brush_in_window(), Draw_button_gradient_style(), Draw_thingumajig(), Print_counter(), Tag_color_range(), Window_display_frame_generic(), and Window_display_icon_sprite().
void Set_fore_color (byte color)
References byte, Display_foreback(), Fore_color, Frame_menu_color(), and Reposition_palette().
Referenced by Button_Select_forecolor(), Colorpicker_0_1(), Colorpicker_12_0(), Colorpicker_1_1(), Menu_shade(), Special_next_forecolor(), Special_next_user_forecolor(), Special_previous_forecolor(), and Special_previous_user_forecolor().
void Set_back_color (byte color)
References Back_color, byte, Display_foreback(), and Frame_menu_color().
Referenced by Button_Select_backcolor(), Colorpicker_0_1(), Colorpicker_12_0(), Colorpicker_2_1(), Special_next_backcolor(), Special_next_user_backcolor(), Special_previous_backcolor(), and Special_previous_user_backcolor().
void Frame_menu_color (byte id)
Redraw the cell in the menu palette for Fore_color.
This function checks bounds, it won't draw anything if Fore_color is not visible.
Parameters:
id,: Color number to frame
References Back_color, Block, byte, Config, First_color_in_palette, Fore_color, MC_Black, MC_Dark, MC_White, Menu_cells_X, Menu_cells_Y, Menu_factor_X, Menu_factor_Y, Menu_height, Menu_is_visible, Menu_palette_cell_width, Menu_Y, Palette_cell_X(), Palette_cell_Y(), T_Config::Separate_colors, Update_rect(), and word.
Referenced by Button_Invert_foreback(), Display_menu_palette(), Set_back_color(), and Set_fore_color().
void Display_menu_palette (void)
References Back_color, Block, byte, Config, First_color_in_palette, Fore_color, Frame_menu_color(), MC_Black, Menu_cells_X, Menu_cells_Y, Menu_factor_X, Menu_factor_Y, Menu_height, Menu_is_visible, Menu_palette_cell_width, MENU_WIDTH, Menu_Y, Palette_cell_X(), Palette_cell_Y(), Screen_width, T_Config::Separate_colors, and Update_rect().
Referenced by Button_Pal_left(), Button_Pal_left_fast(), Button_Pal_right(), Button_Pal_right_fast(), Display_menu(), and Reposition_palette().
void Display_menu (void)
Display the whole menu.
References Block, Colorpicker_color, Current_operation, Display_foreback(), Display_menu_palette(), Gfx, Main_magnifier_mode, Main_separator_position, Main_X_zoom, MC_Light, T_Gui_skin::Menu_block, Menu_factor_X, Menu_factor_Y, Menu_height, MENU_HEIGHT, Menu_is_visible, Menu_status_Y, MENU_WIDTH, Menu_Y, Mouse_X, Mouse_Y, Num2str(), OPERATION_COLORPICK, OPERATION_REPLACE, Pixel_in_menu, Print_coordinates(), Print_filename(), Print_general(), Print_in_menu(), Screen_width, Update_rect(), Windows_open, and word.
Referenced by Button_Hide_menu(), Button_Kill(), Button_Load_or_Save(), Button_Page(), Button_Palette(), Button_Redo(), Button_Reload(), Button_Resolution(), Button_Safety_resolution(), Button_Secondary_palette(), Button_Settings(), Button_Skins(), Button_Undo(), Close_popup(), Close_window(), Get_color_behind_window(), Get_colors_from_brush(), Init_program(), Load_picture(), and Main_handler().
void Reposition_palette (void)
References byte, Config, Display_menu_palette(), First_color_in_palette, Fore_color, Menu_cells_X, Menu_cells_Y, and T_Config::Palette_vertical.
Referenced by Button_Invert_foreback(), Button_Palette(), Button_Resolution(), Button_Safety_resolution(), Main_handler(), and Set_fore_color().
void Change_palette_cells (void)
References BUTTON_CHOOSE_COL, Buttons_Pool, Config, First_color_in_palette, Menu_cells_X, Menu_cells_Y, Menu_factor_X, Menu_height, Menu_palette_cell_width, MENU_WIDTH, T_Config::Palette_cells_X, T_Config::Palette_cells_Y, T_Config::Palette_vertical, and Screen_width.
Referenced by Button_Secondary_palette(), and Init_mode_video().
int Pick_color_in_palette (void)
References Config, First_color_in_palette, Menu_cells_X, Menu_cells_Y, Menu_factor_X, Menu_factor_Y, Menu_height, Menu_palette_cell_width, MENU_WIDTH, Menu_Y, Mouse_X, Mouse_Y, and T_Config::Palette_vertical.
Referenced by Button_Select_backcolor(), Button_Select_forecolor(), and Main_handler().
word Palette_cells_X (void)
References Menu_cells_X.
Referenced by Button_Pal_left(), Button_Pal_left_fast(), Button_Pal_right(), and Button_Pal_right_fast().
word Palette_cells_Y (void)
References Menu_cells_Y.
Referenced by Button_Pal_left(), Button_Pal_left_fast(), Button_Pal_right(), and Button_Pal_right_fast().
void Print_general (short x, short y, const char * str, byte text_color, byte background_color)
References byte, Display_line_fast, Horizontal_line_buffer, Menu_factor_X, Menu_factor_Y, Menu_font, Pixel_width, and word.
Referenced by Colorpicker_1_1(), Colorpicker_2_1(), Display_menu(), Get_color_behind_window(), Print_coordinates(), Print_filename(), Print_in_menu(), and Print_in_window().
void Print_in_window (short x, short y, const char * str, byte text_color, byte background_color)
Draws a string in a window.
References Menu_factor_X, Menu_factor_Y, Print_general(), Update_rect(), Window_pos_X, and Window_pos_Y.
Referenced by Button_Airbrush_menu(), Button_Brush_FX(), Button_Colorize_display_selection(), Button_Colorize_menu(), Button_Effects(), Button_Gradients(), Button_Grid_menu(), Button_Load_or_Save(), Button_Message_initial(), Button_Palette(), Button_Quick_shade_menu(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Skins(), Button_Stats(), Button_Text(), Button_Tiling_menu(), Button_Transform_menu(), Confirmation_box(), Display_bookmark(), Display_effect_state(), Display_feedback_state(), Display_file_list(), Display_modes_list(), Display_selected_cell_color(), Display_selected_color(), Display_shade_mode(), Display_whole_string(), Draw_one_font_name(), Draw_one_skin_name(), Init_preview(), Menu_shade(), Message_out_of_memory(), Open_window(), Print_current_directory(), Print_in_window_limited(), Readline_ex(), Redefine_control(), Reduce_palette(), Refresh_airbrush_settings(), Requester_window(), Save_C64_window(), Settings_display_config(), Verbose_error_message(), Warning_message(), Window_draw_normal_bouton(), Window_draw_scroller_bouton(), Window_dropdown_on_click(), Window_set_dropdown_button(), and Window_set_shortcut().
void Print_in_window_limited (short x, short y, const char * str, byte size, byte text_color, byte background_color)
Draws a char in a window, checking for bounds.
References ELLIPSIS_CHARACTER, and Print_in_window().
Referenced by Button_Transform_menu(), Display_bookmark(), Print_filename_in_fileselector(), Readline_ex(), Window_dropdown_on_click(), Window_input_content(), and Window_set_shortcut().
void Print_char_in_window (short x_pos, short y_pos, const unsigned char c, byte text_color, byte background_color)
Draws a char in a window.
References Block, byte, Menu_factor_X, Menu_factor_Y, Menu_font, Window_pos_X, and Window_pos_Y.
Referenced by Button_Smooth_menu(), and Display_whole_string().
void Print_in_menu (const char * str, short position)
References MC_Black, MC_Light, Menu_factor_X, Menu_factor_Y, Menu_status_Y, Print_general(), and Update_rect().
Referenced by Brush_12_0(), Brush_12_5(), Button_Colorpicker(), Button_Fill(), Button_Replace(), Button_Unselect_colorpicker(), Button_Unselect_fill(), Centered_lines_12_0(), Centered_lines_12_7(), Circle_12_0(), Circle_12_5(), Colorpicker_1_1(), Colorpicker_2_1(), Curve_34_points_1_0(), Curve_34_points_2_0(), Curve_3_points_0_5(), Curve_4_points_0_5(), Display_coords_rel_or_abs(), Display_menu(), Distort_brush_0_0(), Distort_brush_1_0(), Distort_brush_1_8(), Distort_brush_1_9(), Distort_brush_2_0(), Ellipse_12_0(), Empty_circle_0_5(), Empty_ellipse_0_5(), Empty_rectangle_0_5(), Filled_circle_0_5(), Filled_ellipse_0_5(), Filled_rectangle_0_5(), Get_color_behind_window(), Grad_circle_0_6(), Grad_circle_12_0(), Grad_circle_12_6(), Grad_circle_12_8(), Grad_ellipse_0_6(), Grad_ellipse_12_0(), Grad_ellipse_12_8(), Grad_rectangle_0_9(), Grad_rectangle_12_0(), Grad_rectangle_12_5(), K_line_0_6(), K_line_12_0(), K_line_12_7(), Line_0_5(), Line_12_0(), Main_handler(), Polyfill_0_8(), Polyfill_12_0(), Polyfill_12_9(), Polygon_12_0(), Polygon_12_9(), Print_coordinates(), Rectangle_12_0(), Rectangle_12_5(), Return_to_draw_mode(), Rotate_brush_0_5(), Rotate_brush_12_0(), Rotate_brush_1_5(), Scroll_0_4(), Scroll_12_0(), Stretch_brush_0_7(), Stretch_brush_12_0(), and Stretch_brush_1_7().
void Print_coordinates (void)
Draws the mouse coordinates on the menu Only update the digits and doesn't refresh the "X: Y:" labels.
This function needs to be fast as it is called each time the mouse moves.
References Colorpicker_color, Colorpicker_X, Colorpicker_Y, Current_operation, Cursor_in_menu, dword, Main_image_height, Main_image_width, Menu_factor_X, Menu_factor_Y, Menu_is_visible, Menu_status_Y, Num2str(), OPERATION_COLORPICK, OPERATION_REPLACE, Paintbrush_X, Paintbrush_Y, Print_general(), Print_in_menu(), Read_pixel_from_current_screen(), and Update_rect().
Referenced by Airbrush_12_2(), Brush_12_5(), Centered_lines_12_7(), Circle_12_5(), Colorpicker_1_1(), Colorpicker_2_1(), Curve_3_points_0_11(), Curve_3_points_0_5(), Curve_4_points_0_5(), Curve_4_points_1_9(), Display_coords_rel_or_abs(), Display_menu(), Distort_brush_1_8(), Distort_brush_1_9(), Empty_circle_0_5(), Empty_ellipse_0_5(), Empty_rectangle_0_5(), Filled_circle_0_5(), Filled_contour_0_8(), Filled_ellipse_0_5(), Filled_polyform_0_8(), Filled_polyform_12_8(), Filled_rectangle_0_5(), Freehand_mode1_1_2(), Freehand_mode1_2_2(), Freehand_mode2_1_0(), Freehand_mode2_1_2(), Freehand_mode2_2_0(), Freehand_mode2_2_2(), Grad_circle_0_6(), Grad_circle_12_6(), Grad_circle_12_8(), Grad_ellipse_0_6(), Grad_ellipse_12_8(), Grad_rectangle_0_7(), Grad_rectangle_0_9(), Grad_rectangle_12_5(), Init_operations(), K_line_12_7(), Line_0_5(), Polybrush_12_8(), Polyfill_12_9(), Polyform_0_8(), Polyform_12_8(), Polygon_12_9(), Rectangle_12_5(), Return_to_draw_mode(), Rotate_brush_0_5(), Rotate_brush_1_5(), Scroll_0_4(), Stretch_brush_0_7(), and Stretch_brush_1_7().
void Print_filename (void)
References Block, ELLIPSIS_CHARACTER, Main_filename, MC_Black, MC_Light, Menu_factor_X, Menu_factor_Y, Menu_is_visible, Menu_status_Y, Print_general(), and Screen_width.
Referenced by Display_menu(), Load_picture(), and Save_picture().
void Print_counter (short x, short y, const char * str, byte text_color, byte background_color)
References byte, Menu_factor_X, Menu_factor_Y, Ob, Pixel_in_window(), Update_rect(), Window_pos_X, Window_pos_Y, and word.
Referenced by Button_Palette(), Draw_all_palette_sliders(), and Set_palette_slider().
byte Confirmation_box (char * message)
References Close_window(), Display_cursor(), Key, KEY_ESC, MC_Black, MC_Light, Menu_factor_X, Menu_factor_Y, Open_window(), Print_in_window(), Update_rect(), Window_clicked_button(), Window_pos_X, Window_pos_Y, Window_set_normal_button(), and word.
Referenced by Button_Autosave(), Button_Copy_page(), Button_Kill(), Button_Load_or_Save(), Button_Quit_local_function(), Button_Reload(), Copy_some_colors(), Get_colors_from_brush(), Load_picture(), and Save_picture().
void Warning_message (char * message)
Window that show a warning message and wait for a click on the OK button.
References Close_window(), Display_cursor(), Key, KEY_ESC, MC_Black, MC_Light, Menu_factor_X, Menu_factor_Y, Open_window(), Print_in_window(), Update_rect(), Window_clicked_button(), Window_pos_X, Window_pos_Y, Window_set_normal_button(), and word.
Referenced by Button_Kill(), main(), Save_C64(), Save_C64_hires(), and Save_C64_multi().
void Verbose_error_message (const char * message)
Window that shows a big message, and waits for a click on OK.
References Close_window(), Display_cursor(), Key, KEY_ESC, MC_Black, MC_Light, Open_window(), Print_in_window(), Update_window_area, Window_clicked_button(), Window_height, Window_set_normal_button(), and Window_width.
Referenced by Button_Skins().
int Requester_window (char * message, int initial_value)
Window that allows you to enter a single value.
References Close_window(), Display_cursor(), Key, MC_Black, MC_Light, Menu_factor_X, Menu_factor_Y, Open_window(), Print_in_window(), Readline(), Update_rect(), Window_clicked_button(), Window_pos_X, Window_pos_Y, Window_set_input_button(), Window_set_normal_button(), and word.
Referenced by Button_Palette().
void Display_image_limits (void)
References byte, Limit_bottom, Limit_bottom_zoom, Limit_left, Limit_right, Limit_right_zoom, Limit_top, Limit_visible_bottom_zoom, Limit_visible_right_zoom, Main_image_height, Main_image_width, Main_magnifier_mode, Main_separator_position, MC_Black, MC_White, Menu_Y, Pixel_preview, Screen_width, and Update_rect().
Referenced by Button_Reload(), and Display_all_screen().
void Display_all_screen (void)
References Block, Config, Display_image_limits(), T_Config::Display_image_limits, Display_screen, Display_separator(), Display_zoomed_screen, Horizontal_line_buffer, Main_image_height, Main_image_width, Main_magnifier_factor, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_width, Main_separator_position, Main_X_zoom, Menu_Y, Screen_width, Update_rect(), and word.
Referenced by Button_Clear(), Button_Clear_with_backcolor(), Button_Hide_menu(), Button_Kill(), Button_Magnify(), Button_Magnify_menu(), Button_Page(), Button_Redo(), Button_Reload(), Button_Resolution(), Button_Safety_resolution(), Button_Show_grid(), Button_Transform_menu(), Button_Undo(), Button_Unselect_magnifier(), Close_popup(), Close_window(), Distort_brush_1_9(), Distort_brush_2_0(), Distort_brush_2_8(), Filled_contour_0_8(), Filled_polyform_12_8(), Get_color_behind_window(), Get_colors_from_brush(), Init_mode_video(), Load_picture(), Magnifier_12_0(), Main_handler(), Move_separator(), Polybrush_12_8(), Polyfill_12_9(), Replace(), Rotate_brush_0_5(), Rotate_brush_1_5(), Rotate_brush_2_5(), Scroll_12_4(), Scroll_magnifier(), Scroll_screen(), Stretch_brush_0_7(), Stretch_brush_1_7(), Stretch_brush_2_7(), Zoom(), and Zoom_set().
void Window_rectangle (word x_pos, word y_pos, word width, word height, byte color)
References Block, Menu_factor_X, Menu_factor_Y, Window_pos_X, and Window_pos_Y.
Referenced by Button_Load_or_Save(), Button_Resolution(), Button_Text(), Display_bookmark(), Display_stored_brush_in_window(), Draw_palette_preview(), Init_preview(), Prepare_and_display_filelist(), Print_current_directory(), Print_filename_in_fileselector(), and Window_dropdown_on_click().
void Window_display_frame_generic (word x_pos, word y_pos, word width, word height, byte color_tl, byte color_br, byte color_s, byte color_tlc, byte color_brc)
References Block, Menu_factor_X, Menu_factor_Y, Pixel_in_window(), Window_pos_X, and Window_pos_Y.
Referenced by Window_display_frame_in(), Window_display_frame_mono(), Window_display_frame_out(), Window_draw_normal_bouton(), Window_draw_scroller_bouton(), and Window_select_normal_button().
void Window_display_frame_mono (word x_pos, word y_pos, word width, word height, byte color)
References Window_display_frame_generic().
Referenced by Open_window(), Window_draw_normal_bouton(), and Window_draw_scroller_bouton().
void Window_display_frame_in (word x_pos, word y_pos, word width, word height)
References MC_Dark, MC_Light, MC_White, and Window_display_frame_generic().
Referenced by Button_Gradients(), Button_Load_or_Save(), Button_Message_initial(), Button_Resolution(), Button_Sieve_menu(), Button_Skins(), Button_Stats(), Button_Text(), Menu_shade(), Window_display_frame(), Window_draw_input_bouton(), Window_help(), and Window_set_shortcut().
void Window_display_frame_out (word x_pos, word y_pos, word width, word height)
References MC_Dark, MC_Light, MC_White, and Window_display_frame_generic().
Referenced by Display_all_shade(), Open_window(), Shade_draw_grad_ranges(), Window_display_frame(), Window_draw_normal_bouton(), Window_draw_scroller_bouton(), Window_dropdown_on_click(), and Window_unselect_normal_button().
void Window_display_frame (word x_pos, word y_pos, word width, word height)
References Window_display_frame_in(), and Window_display_frame_out().
Referenced by Button_Airbrush_menu(), Button_Brush_FX(), Button_Colorize_menu(), Button_Paintbrush_menu(), Button_Palette(), Button_Resolution(), Button_Secondary_palette(), Button_Settings(), Button_Sieve_menu(), Button_Smooth_menu(), Button_Transform_menu(), Menu_shade(), and Window_draw_palette_bouton().
void Display_sprite_in_menu (int btn_number, int sprite_number)
References BUTTON_SHAPE_TRIANGLE_BOTTOM_RIGHT, Buttons_Pool, byte, Gfx, T_Gui_skin::Menu_block, Menu_factor_X, Menu_factor_Y, T_Gui_skin::Menu_sprite, MENU_SPRITE_HEIGHT, MENU_SPRITE_WIDTH, Menu_Y, Pixel_in_menu, Shape, Update_rect(), word, X_offset, and Y_offset.
Referenced by Button_Curves_switch_mode(), Button_Draw_switch_mode(), Button_Lines_switch_mode(), Button_Secondary_palette(), Init_program(), and Select_button().
void Display_paintbrush_in_menu (void)
References byte, Gfx, MAX_PAINTBRUSH_SIZE, MC_Black, MC_Light, T_Gui_skin::Menu_block, Menu_factor_X, Menu_factor_Y, T_Gui_skin::Menu_sprite, MENU_SPRITE_HEIGHT, MENU_SPRITE_WIDTH, Menu_Y, Paintbrush_height, Paintbrush_offset_X, Paintbrush_offset_Y, Paintbrush_shape, PAINTBRUSH_SHAPE_COLOR_BRUSH, PAINTBRUSH_SHAPE_MONO_BRUSH, Paintbrush_sprite, Paintbrush_width, Pixel_in_menu, and Update_rect().
Referenced by Bigger_paintbrush(), Change_paintbrush_shape(), Init_program(), and Smaller_paintbrush().
void Display_paintbrush_in_window (word x, word y, int number)
References Block, Gfx, MC_Black, MC_Light, Menu_factor_X, Menu_factor_Y, T_Gui_skin::Paintbrush_sprite, Pixel_height, Pixel_width, T_Gui_skin::Preset_paintbrush_height, T_Gui_skin::Preset_paintbrush_offset_X, T_Gui_skin::Preset_paintbrush_offset_Y, T_Gui_skin::Preset_paintbrush_width, ToWinH, ToWinL, ToWinX, ToWinY, Update_rect(), Window_pos_X, Window_pos_Y, and word.
Referenced by Button_Paintbrush_menu().
void Draw_thingumajig (word x, word y, byte color, short direction)
References Pixel_in_window(), and word.
Referenced by Button_Palette().
void Display_grad_block_in_window (word x_pos, word y_pos, word block_start, word block_end)
References Block, Menu_factor_X, Menu_factor_Y, Selected_line_mode, ToWinH, ToWinL, ToWinX, ToWinY, Update_rect(), Window_pos_X, Window_pos_Y, and word.
Referenced by Button_Palette(), and Menu_shade().
void Window_display_icon_sprite (word x_pos, word y_pos, byte type)
References Gfx, T_Gui_skin::Icon_sprite, ICON_SPRITE_HEIGHT, ICON_SPRITE_WIDTH, Pixel_in_window(), ToWinH, ToWinL, ToWinX, ToWinY, Update_rect(), and word.
Referenced by Button_Load_or_Save(), and Window_set_dropdown_button().
byte Best_color (byte red, byte green, byte blue)
References byte, Exclude_color, and Main_palette.
Referenced by Draw_ILBM_line(), Effect_additive_colorize(), Effect_interpolated_colorize(), Effect_smooth(), Effect_substractive_colorize(), Remap_brush(), and Remap_spare().
byte Best_color_nonexcluded (byte red, byte green, byte blue)
References byte, and Main_palette.
Referenced by Set_nice_menu_colors().
void Horizontal_XOR_line_zoom (short x_pos, short y_pos, short width)
References Horizontal_XOR_line, Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_X_zoom, Menu_Y, and Update_rect().
Referenced by Display_cursor(), Grad_rectangle_0_5(), Grad_rectangle_0_9(), Grad_rectangle_12_7(), and Hide_cursor().
void Vertical_XOR_line_zoom (short x_pos, short y_pos, short height)
References Horizontal_XOR_line, Main_magnifier_factor, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_X_zoom, Menu_Y, and Update_rect().
Referenced by Display_cursor(), Grad_rectangle_0_5(), Grad_rectangle_0_9(), Grad_rectangle_12_7(), and Hide_cursor().
void Change_magnifier_factor (byte factor_index)
References Compute_limits(), Compute_magnifier_data(), Compute_paintbrush_coordinates(), Main_image_height, Main_image_width, Main_magnifier_factor, Main_magnifier_height, Main_magnifier_mode, Main_magnifier_offset_X, Main_magnifier_offset_Y, Main_magnifier_width, Pixel_preview, Pixel_preview_magnifier, Pixel_preview_normal, Position_screen_according_to_zoom(), and ZOOM_FACTOR.
Referenced by Button_Magnify_menu(), Button_Page(), Zoom(), and Zoom_set().